unpackaged/main/default/objects/Pricebook2/fields/Periodo_Fin__c.field-meta.xml
<CustomField>
    <fullName>Periodo_Fin__c</fullName>
    <label>Periodo Fin</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2022-05-30</fullName>
                <label>MAYO 2023</label>
            </value>
            <value>
                <fullName>2023-06-30</fullName>
                <label>JUNIO 2023</label>
            </value>
            <value>
                <fullName>2023-07-31</fullName>
                <label>JULIO 2023</label>
            </value>
            <value>
                <fullName>2023-08-31</fullName>
                <label>AGOSTO 2023</label>
            </value>
            <value>
                <fullName>2023-09-30</fullName>
                <label>SEPTIEMBRE 2023</label>
            </value>
            <value>
                <fullName>2023-10-31</fullName>
                <label>OCTUBRE 2023</label>
            </value>
            <value>
                <fullName>2023-11-30</fullName>
                <label>NOVIEMBRE 2023</label>
            </value>
            <value>
                <fullName>2023-12-31</fullName>
                <label>DICIEMBRE 2023</label>
            </value>
            <value>
                <fullName>ENERO 2024</fullName>
            </value>
            <value>
                <fullName>FEBRERO 2024</fullName>
            </value>
            <value>
                <fullName>MARZO 2024</fullName>
            </value>
            <value>
                <fullName>ABRIL 2024</fullName>
            </value>
            <value>
                <fullName>MAYO 2024</fullName>
            </value>
            <value>
                <fullName>JUNIO 2024</fullName>
            </value>
            <value>
                <fullName>JULIO 2024</fullName>
            </value>
            <value>
                <fullName>AGOSTO 2024</fullName>
            </value>
            <value>
                <fullName>SEPTIEMBRE 2024</fullName>
            </value>
            <value>
                <fullName>OCTUBRE 2024</fullName>
            </value>
            <value>
                <fullName>NOVIEMBRE 2024</fullName>
            </value>
            <value>
                <fullName>DICIEMBRE 2024</fullName>
            </value>
            <value>
                <fullName>ENERO 2025</fullName>
            </value>
            <value>
                <fullName>FEBRERO 2025</fullName>
            </value>
            <value>
                <fullName>MARZO 2025</fullName>
            </value>
            <value>
                <fullName>ABRIL 2025</fullName>
            </value>
            <value>
                <fullName>MAYO 2025</fullName>
            </value>
            <value>
                <fullName>JUNIO 2025</fullName>
            </value>
            <value>
                <fullName>JULIO 2025</fullName>
            </value>
            <value>
                <fullName>AGOSTO 2025</fullName>
            </value>
            <value>
                <fullName>SEPTIEMBRE 2025</fullName>
            </value>
            <value>
                <fullName>OCTUBRE 2025</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Pricebook2/fields/Periodo_Inicio__c.field-meta.xml
<CustomField>
    <fullName>Periodo_Inicio__c</fullName>
    <label>Periodo Inicio</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2023-05-01</fullName>
                <label>MAYO 2023</label>
            </value>
            <value>
                <fullName>2023-06-01</fullName>
                <label>JUNIO 2023</label>
            </value>
            <value>
                <fullName>2023-07-01</fullName>
                <label>JULIO 2023</label>
            </value>
            <value>
                <fullName>2023-08-01</fullName>
                <label>AGOSTO 2023</label>
            </value>
            <value>
                <fullName>2023-09-01</fullName>
                <label>SEPTIEMBRE 2023</label>
            </value>
            <value>
                <fullName>2023-10-01</fullName>
                <label>OCTUBRE 2023</label>
            </value>
            <value>
                <fullName>2023-11-01</fullName>
                <label>NOVIEMBRE 2023</label>
            </value>
            <value>
                <fullName>2023-12-01</fullName>
                <label>DICIEMBRE 2023</label>
            </value>
            <value>
                <fullName>ENERO 2024</fullName>
            </value>
            <value>
                <fullName>FEBRERO 2024</fullName>
            </value>
            <value>
                <fullName>MARZO 2024</fullName>
            </value>
            <value>
                <fullName>ABRIL 2024</fullName>
            </value>
            <value>
                <fullName>MAYO 2024</fullName>
            </value>
            <value>
                <fullName>JUNIO 2024</fullName>
            </value>
            <value>
                <fullName>JULIO 2024</fullName>
            </value>
            <value>
                <fullName>AGOSTO 2024</fullName>
            </value>
            <value>
                <fullName>SEPTIEMBRE 2024</fullName>
            </value>
            <value>
                <fullName>OCTUBRE 2024</fullName>
            </value>
            <value>
                <fullName>NOVIEMBRE 2024</fullName>
            </value>
            <value>
                <fullName>DICIEMBRE 2024</fullName>
            </value>
            <value>
                <fullName>ENERO 2025</fullName>
            </value>
            <value>
                <fullName>FEBRERO 2025</fullName>
            </value>
            <value>
                <fullName>MARZO 2025</fullName>
            </value>
            <value>
                <fullName>ABRIL 2025</fullName>
            </value>
            <value>
                <fullName>MAYO 2025</fullName>
            </value>
            <value>
                <fullName>JUNIO 2025</fullName>
            </value>
            <value>
                <fullName>JULIO 2025</fullName>
            </value>
            <value>
                <fullName>AGOSTO 2025</fullName>
            </value>
            <value>
                <fullName>SEPTIEMBRE 2025</fullName>
            </value>
            <value>
                <fullName>OCTUBRE 2025</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Pricebook2/fields/Vigente_Desde__c.field-meta.xml
<CustomField>
    <fullName>Vigente_Desde__c</fullName>
    <label>Vigente Desde</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Pricebook2/fields/Vigente_Hasta__c.field-meta.xml
<CustomField>
    <fullName>Vigente_Hasta__c</fullName>
    <label>Vigente Hasta</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Pricebook2/recordTypes/Producto_Generico.recordType-meta.xml
<RecordType>
    <fullName>Producto_Generico</fullName>
    <active>true</active>
    <label>Producto Genérico</label>
</RecordType>

unpackaged/main/default/objects/Product2/fields/Numero_Filtro__c.field-meta.xml
<CustomField>
    <fullName>Numero_Filtro__c</fullName>
    <description>Se crea este campo para poder filtrar en diferentes campos de búsqueda de otros objetos relacionados a producto</description>
    <label>Número Filtro</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Precio_Venta__c.field-meta.xml
<CustomField>
    <fullName>Precio_Venta__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Precio Venta al Cliente</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Product2/recordTypes/Productos_Genericos.recordType-meta.xml
<RecordType>
    <fullName>Productos_Genericos</fullName>
    <active>true</active>
    <label>Productos Genéricos</label>
</RecordType>

unpackaged/main/default/classes/AddProducts_Test.cls
@isTest
public class AddProducts_Test {
    @isTest(seeAllData=true)
    public static void testMethod1() {
        Product2 prod1 = new Product2();
        prod1.name = 'test11';
        prod1.Numero_Filtro__c = 2;
        prod1.IsActive = true;
        prod1.Precio_Venta__c = 10.0;
        prod1.Description = 'test';
        prod1.ProductCode = 'Pro-X';
        prod1.Precio_Venta__c = 10.0;
        prod1.RecordTypeId = Schema.SObjectType.Product2.getRecordTypeInfosBydevelopername().get('Productos_Genericos').getRecordTypeId();
        insert prod1;
        Pricebook2 pb1  = new Pricebook2();
        pb1.Name = 'Standard Price Book1';
        pb1.Description = 'test';
        pb1.Periodo_Inicio__c='JUNIO 2023';
        pb1.Periodo_Fin__c='JUNIO 2023';
        pb1.Vigente_Desde__c = system.today() ;
        pb1.Vigente_Hasta__c= Date.newInstance(2023, 08, 30);
        pb1.RecordTypeId = Schema.SObjectType.Pricebook2.getRecordTypeInfosBydevelopername().get('Producto_Generico').getRecordTypeId();
        insert pb1;
        Test.startTest();
        AddProducts.fetchProducts();
        AddProducts.fetchPbRecords(prod1.Id);
        AddProducts.updateProdRecords(pb1.Id, prod1.Id);
        Test.stopTest();
    }
}