unpackaged/main/default/objects/ConsultaWS__c/ConsultaWS__c.object-meta.xml
<CustomObject>
    <label>ConsultaWS</label>
    <nameField>
        <label>Nombre de ConsultaWS</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ConsultaWS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ConsultaWS__c/fields/Apellido_Materno__c.field-meta.xml
<CustomField>
    <fullName>Apellido_Materno__c</fullName>
    <label>Apellido Materno</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ConsultaWS__c/fields/Apellido_Paterno__c.field-meta.xml
<CustomField>
    <fullName>Apellido_Paterno__c</fullName>
    <label>Apellido Paterno</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ConsultaWS__c/fields/NSS__c.field-meta.xml
<CustomField>
    <fullName>NSS__c</fullName>
    <label>NSS</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/AccountProcessorTest.cls
@isTest
public class AccountProcessorTest {
    
    @testSetup 
    static void setup() {
        
    }
    
    static testmethod void test() {        
        Test.startTest();
        List<ConsultaWS__c> accounts = new List<ConsultaWS__c>();
        accounts.add(new ConsultaWS__c(Name='ROCIO PRUEBA TESTCUATRO', Nombre__c='ROCIO', Apellido_Materno__c='PRUEBA', Apellido_Paterno__c='TESTCUATRO', NSS__c='01234758694', Fecha_Nacimiento__c = Date.newInstance(1990, 12, 9)));
        Database.executeBatch(new AccountProcessor(accounts), 1);  
        Test.stopTest();
    }
    
}