unpackaged/main/default/objects/Plan_de_Venta__c/Plan_de_Venta__c.object-meta.xml
<CustomObject>
    <label>Plan de Venta</label>
    <nameField>
        <displayFormat>Plan de Venta-{000000}</displayFormat>
        <label>Plan de Venta</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plan de Venta</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Plan_de_Venta__c.field-meta.xml
<CustomField>
    <fullName>Plan_de_Venta__c</fullName>
    <formula>&quot;Plan de Venta&quot; &amp; &quot; &quot;&amp;  Oportunidad__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Plan de Venta</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Ubicacion_Compania__c.field-meta.xml
<CustomField>
    <fullName>Ubicacion_Compania__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ubicación Compañia</label>
    <referenceTo>Ubicacion__c</referenceTo>
    <relationshipLabel>Plan de Venta</relationshipLabel>
    <relationshipName>Plan_de_Venta</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Ubicacion__c/Ubicacion__c.object-meta.xml
<CustomObject>
    <label>Ubicación Compañia</label>
    <nameField>
        <displayFormat>U-{00}</displayFormat>
        <label>Ubicación</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ubicaciones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Ubicacion__c/fields/Direccion_Fisica__c.field-meta.xml
<CustomField>
    <fullName>Direccion_Fisica__c</fullName>
    <label>Dirección Física</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Ubicacion__c/fields/Nombre_de_la_Compania__c.field-meta.xml
<CustomField>
    <fullName>Nombre_de_la_Compania__c</fullName>
    <formula>Compania__r.Name</formula>
    <label>Nombre de la Compañia</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/CONTROL_AvisoPrivacidadPdf.cls
public with sharing class CONTROL_AvisoPrivacidadPdf {
    
    public string compania {get; set;}
    public string domicilio {get; set;}

    public CONTROL_AvisoPrivacidadPdf(ApexPages.StandardController controller) {
        Plan_de_Venta__c pVAux = (Plan_de_Venta__c)controller.getRecord();
        Plan_de_Venta__c pv = [Select Id, Ubicacion_Compania__c From Plan_de_Venta__c Where Id = : pVAux.Id Limit 1];
        Ubicacion__c[] u = [Select Id, Nombre_de_la_Compania__c, Direccion_Fisica__c From Ubicacion__c Where Id = :pv.Ubicacion_Compania__c Limit 1];
        if(u.size() == 0){
            compania = ' N/A';
            domicilio = ' N/A';
        }
        else{
            compania = ' ' + u[0].Nombre_de_la_Compania__c;
            domicilio = ' ' + u[0].Direccion_Fisica__c;
        }   
    }
}