unpackaged/main/default/objects/Plan_de_Venta__c/Plan_de_Venta__c.object-meta.xml
<CustomObject>
    <label>Plan de Venta</label>
    <nameField>
        <displayFormat>Plan de Venta-{000000}</displayFormat>
        <label>Plan de Venta</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plan de Venta</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Estatus_Plan_de_venta__c.field-meta.xml
<CustomField>
    <fullName>Estatus_Plan_de_venta__c</fullName>
    <label>Estatus Plan de Venta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>En Progreso</fullName>
                <default>true</default>
                <label>En Progreso</label>
            </value>
            <value>
                <fullName>Por Aprobar</fullName>
            </value>
            <value>
                <fullName>Aprobado</fullName>
            </value>
            <value>
                <fullName>Reubicado</fullName>
            </value>
            <value>
                <fullName>Reestructurado</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Plan_de_Venta__c.field-meta.xml
<CustomField>
    <fullName>Plan_de_Venta__c</fullName>
    <formula>&quot;Plan de Venta&quot; &amp; &quot; &quot;&amp;  Oportunidad__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Plan de Venta</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Plan_de_Venta_Original__c.field-meta.xml
<CustomField>
    <fullName>Plan_de_Venta_Original__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plan de Venta Original</label>
    <referenceTo>Plan_de_Venta__c</referenceTo>
    <relationshipLabel>Plan de Venta</relationshipLabel>
    <relationshipName>Plan_de_Venta</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Precio_Unitario__c.field-meta.xml
<CustomField>
    <fullName>Precio_Unitario__c</fullName>
    <formula>trCalc_Precio_Unitario__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Precio Unitario</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <description>Identifica si el plan de venta es un plan convencional, o en caso de existir una reestructura, se mostrará el correspondiente como &quot;Reestructura&quot; y el original deberá cambiar a &quot;Plan de Venta Cancelado&quot;</description>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Plan de Venta</fullName>
                <default>true</default>
                <label>Plan de Venta</label>
            </value>
            <value>
                <fullName>Reestructura</fullName>
            </value>
            <value>
                <fullName>Plan de Venta Cancelado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Producto_de_Plan_de_Venta__c/Producto_de_Plan_de_Venta__c.object-meta.xml
<CustomObject>
    <label>Producto de Plan de Venta</label>
    <nameField>
        <displayFormat>PPV-{YYYY}-{MM}-{000000}</displayFormat>
        <label>Nombre de Producto de Plan de Venta</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Productos de Plan de Venta</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Producto_de_Plan_de_Venta__c/fields/Lista_de_Precios__c.field-meta.xml
<CustomField>
    <fullName>Lista_de_Precios__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lista de Precios</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Productos de Plan de Venta</relationshipLabel>
    <relationshipName>Productos_de_Plan_de_Venta</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Producto_de_Plan_de_Venta__c/fields/Plan_de_Venta__c.field-meta.xml
<CustomField>
    <fullName>Plan_de_Venta__c</fullName>
    <label>Plan de Venta</label>
    <referenceTo>Plan_de_Venta__c</referenceTo>
    <relationshipLabel>Productos de Plan de Venta</relationshipLabel>
    <relationshipName>Productos_de_Plan_de_Venta</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Producto_de_Plan_de_Venta__c/fields/Precio_Unitario__c.field-meta.xml
<CustomField>
    <fullName>Precio_Unitario__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Precio Unitario</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Producto_de_Plan_de_Venta__c/fields/Producto__c.field-meta.xml
<CustomField>
    <fullName>Producto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Productos de Plan de Venta</relationshipLabel>
    <relationshipName>Productos_de_Plan_de_Venta</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Producto_de_Plan_de_Venta__c/fields/Producto_de_oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Producto_de_oportunidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producto de oportunidad</label>
    <referenceTo>OpportunityLineItem</referenceTo>
    <relationshipLabel>Productos de Plan de Venta</relationshipLabel>
    <relationshipName>Productos_de_Plan_de_Venta</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Producto_de_Plan_de_Venta__c/fields/Tipo_de_Producto__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Producto__c</fullName>
    <label>Tipo de Producto</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/PlanDeVenta_Clone.cls
public class PlanDeVenta_Clone {
	@AuraEnabled
    public static String clonePDV(String recId){
        try{
            Set<String> SobjectFields = Schema.getGlobalDescribe().get('Plan_de_Venta__c').getDescribe().fields.getMap().keySet();
            List<String> fieldsInList = new List<String>(SobjectFields);
            List<Plan_de_Venta__c> originalRecord = Database.query('SELECT ' + String.join(fieldsInList, ',') + ' FROM Plan_de_Venta__c WHERE Id=:recId');
            List<Producto_de_Plan_de_Venta__c> productosToClone = new List<Producto_de_Plan_de_Venta__c>();
            
            Plan_de_Venta__c clonedRecord = originalRecord[0].clone(false,true,false,false);
            clonedRecord.Tipo__c = 'Reestructura';
            clonedRecord.Plan_de_Venta_Original__c = originalRecord[0].Id;
            clonedRecord.Estatus_Plan_de_venta__c = 'En Progreso'; 
            insert clonedRecord;
            
            for(Producto_de_Plan_de_Venta__c pdv: [SELECT Id,Cantidad__c,Lista_de_Precios__c,Precio_Unitario__c,Producto__c,Producto_de_oportunidad__c,Tipo_de_Producto__c 
                                                   FROM Producto_de_Plan_de_Venta__c WHERE Plan_de_Venta__c =: originalRecord[0].Id])
            {
                Producto_de_Plan_de_Venta__c newPDF = pdv.clone(false,true,false,false);
                newPDF.Plan_de_Venta__c = clonedRecord.Id;
                productosToClone.add(newPDF);
            }
            insert productosToClone;
            
            originalRecord[0].Tipo__c = 'Plan de Venta Cancelado';
            
            update originalRecord[0];
            return clonedRecord.Id;
        }
        catch(Exception e){
            return 'ERROR: '+e.getMessage();
        }
    }
}