unpackaged/main/default/objects/Plan_de_Venta__c/Plan_de_Venta__c.object-meta.xml
<CustomObject>
    <label>Plan de Venta</label>
    <nameField>
        <displayFormat>Plan de Venta-{000000}</displayFormat>
        <label>Plan de Venta</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plan de Venta</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Plan_de_Venta__c.field-meta.xml
<CustomField>
    <fullName>Plan_de_Venta__c</fullName>
    <formula>&quot;Plan de Venta&quot; &amp; &quot; &quot;&amp;  Oportunidad__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Plan de Venta</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Vivienda_Es_Casa_Muestra__c.field-meta.xml
<CustomField>
    <fullName>Vivienda_Es_Casa_Muestra__c</fullName>
    <formula>Vivienda__r.Casa_Muestra__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Vivienda Es Casa Muestra?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Producto_de_Plan_de_Venta__c/Producto_de_Plan_de_Venta__c.object-meta.xml
<CustomObject>
    <label>Producto de Plan de Venta</label>
    <nameField>
        <displayFormat>PPV-{YYYY}-{MM}-{000000}</displayFormat>
        <label>Nombre de Producto de Plan de Venta</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Productos de Plan de Venta</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Producto_de_Plan_de_Venta__c/fields/Plan_de_Venta__c.field-meta.xml
<CustomField>
    <fullName>Plan_de_Venta__c</fullName>
    <label>Plan de Venta</label>
    <referenceTo>Plan_de_Venta__c</referenceTo>
    <relationshipLabel>Productos de Plan de Venta</relationshipLabel>
    <relationshipName>Productos_de_Plan_de_Venta</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Producto_de_Plan_de_Venta__c/fields/Tipo_de_Producto__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Producto__c</fullName>
    <label>Tipo de Producto</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/CLASS_ProductoPlanVenta.cls
public class CLASS_ProductoPlanVenta {
    public static void ValidaCasaMuestra(List<Producto_de_Plan_de_Venta__c> newList) {
        for (Producto_de_Plan_de_Venta__c pr : newList) {
            List <Plan_de_Venta__c> pdv = [SELECT id, Vivienda_Es_Casa_Muestra__c FROM Plan_de_Venta__c WHERE Id = :pr.Plan_de_Venta__c LIMIT 1];
            if (pdv.size()>0) {
                if (!pdv[0].Vivienda_Es_Casa_Muestra__c && pr.Tipo_de_Producto__c=='Casa Muestra'){
                    system.debug('**** No se permite agregar Casa Muestra con flag Casa Muestra');
                    pr.addError('No se puede agregar un Producto Casa Muestra porque la Vivienda esta marcada como Casa Muestra');
                }
            }
        }
    }
}