unpackaged/main/default/objects/Meta__c/Meta__c.object-meta.xml
<CustomObject>
    <label>Meta</label>
    <nameField>
        <label>Fraccionamiento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metas</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/TablaDescenso__c/TablaDescenso__c.object-meta.xml
<CustomObject>
    <label>Tabla descenso</label>
    <nameField>
        <label>Fraccionamiento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tabla descenso</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/TablaDescenso__c/fields/Asesor__c.field-meta.xml
<CustomField>
    <fullName>Asesor__c</fullName>
    <label>Asesor</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/TablaDescenso__c/fields/CantidadAsesores__c.field-meta.xml
<CustomField>
    <fullName>CantidadAsesores__c</fullName>
    <label>Cantidad de asesores</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/TablaDescenso__c/fields/IdPeriodo__c.field-meta.xml
<CustomField>
    <fullName>IdPeriodo__c</fullName>
    <label>Id Periodo</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/TablaDescenso__c/fields/Meta__c.field-meta.xml
<CustomField>
    <fullName>Meta__c</fullName>
    <label>Meta</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/TablaDescenso__c/fields/Promedio__c.field-meta.xml
<CustomField>
    <fullName>Promedio__c</fullName>
    <label>Promedio</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/TablaDescenso__c/fields/PromedioAnualEscrituras__c.field-meta.xml
<CustomField>
    <fullName>PromedioAnualEscrituras__c</fullName>
    <label>Promedio anual de escrituras</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/TablaDescenso__c/fields/PromedioRequerido__c.field-meta.xml
<CustomField>
    <fullName>PromedioRequerido__c</fullName>
    <label>Promedio requerido</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/TablaDescenso__c/fields/ResultadoAnual__c.field-meta.xml
<CustomField>
    <fullName>ResultadoAnual__c</fullName>
    <label>Resultado Anual</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/TablaDescenso__c/fields/ResultadoMensual__c.field-meta.xml
<CustomField>
    <fullName>ResultadoMensual__c</fullName>
    <label>Resultado mensual</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/TablaDescenso__c/fields/Total__c.field-meta.xml
<CustomField>
    <fullName>Total__c</fullName>
    <label>Total</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/ImportarTablaDescensoWS.cls
public class ImportarTablaDescensoWS {
    public List<TablaDescenso__c> listaDescenso {get;set;}
    
    public ImportarTablaDescensoWS(){
        
    }
    
	public PageReference consultar(){
        PageReference page = ApexPages.currentPage();
        listaDescenso = new List<TablaDescenso__c>();
        esbJaverComMxReportsRptdescenso.RptDescensoPort wsPort =  new esbJaverComMxReportsRptdescenso.RptDescensoPort();
        wsPort.timeout_x = 120000;
        List<TablaDescenso__c> listAux = [Select Id, Name FROM TablaDescenso__c LIMIT 48000];
         esbJaverComReportsDescensoTypes.Descenso_element respuesta = wsPort.DescensoCurrentAndPrevious();
        List<User> usuarios = [Select Id, Name FROM User WHERE isActive = True LIMIT 10000];
        Map<String, Id> mapaIds = new Map<String, Id>();
        for(User us : usuarios){
            mapaIds.put(us.Name.toLowerCase(), us.Id);
        }
        List<esbJaverComReportsDescensoTypes.OutputType> tablaDescensos = respuesta.Row;
        if(tablaDescensos != null){
            for(esbJaverComReportsDescensoTypes.OutputType td : tablaDescensos){
               TablaDescenso__c t = new TablaDescenso__c();
                t.Name = td.FRACCIONAMIENTO; //FRACCIONAMIENTO
                t.Asesor__c = td.ASESOR;
                t.CantidadAsesores__c = '' + td.CANTIDAD_ASESORES;
                t.IdPeriodo__c = td.ID_PERIODO;
                t.Meta__c = td.META;
                t.Promedio__c = '' + td.PROMEDIO;
                t.PromedioAnualEscrituras__c = '' + td.PROMEDIO_ANUAL_ESCRITURAS;
                t.PromedioRequerido__c = '' + td.PROMEDIO_REQUERIDO;
                t.ResultadoAnual__c = '' +(td.MES_ACTUAL + td.MES_ACTUAL_1 + td.MES_ACTUAL_2 + td.MES_ACTUAL_3);
                t.ResultadoMensual__c = '' + td.MES_ACTUAL;
                t.Total__c = ''+ td.RESULTADO;
                
                
                try{
                	t.OwnerId = mapaIds.get(t.Asesor__c.toLowerCase());
                }catch(Exception w){
                    t.OwnerId = UserInfo.getUserId();
                }
                
                if(t.OwnerId == null){
                    t.OwnerId = UserInfo.getUserId();
                }
                
                
                listaDescenso.add(t);
            }
        }
        delete listAux;
        insert listaDescenso;
        return page;
    }
    
        public void method(){
        Integer i = 0;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
    }
}