unpackaged/main/default/objects/Co_Acreditado__c/Co_Acreditado__c.object-meta.xml
<CustomObject>
    <label>Co Acreditado</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Folio Co Acreditado</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Co Acreditados</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Co_Acreditado__c/fields/Apellido_Materno_CO_Acreditado__c.field-meta.xml
<CustomField>
    <fullName>Apellido_Materno_CO_Acreditado__c</fullName>
    <label>Apellido Materno CO Acreditado</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Co_Acreditado__c/fields/Apellido_Paterno_CO_Acreditado__c.field-meta.xml
<CustomField>
    <fullName>Apellido_Paterno_CO_Acreditado__c</fullName>
    <label>Apellido Paterno CO Acreditado</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Co_Acreditado__c/fields/Co_Acreditado__c.field-meta.xml
<CustomField>
    <fullName>Co_Acreditado__c</fullName>
    <formula>HYPERLINK(&quot;/lightning/r/co_acreditado__c/&quot; &amp; Id &amp; &quot;/view&quot;,Name &amp; &quot; - &quot; &amp; Nombre__c &amp; &quot; &quot; &amp; Apellido_Paterno_CO_Acreditado__c  &amp; &quot; &quot; &amp; Apellido_Paterno_CO_Acreditado__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Co Acreditado</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Co_Acreditado__c/fields/Fecha_de_Nacimiento_CO_Acreditado__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_Nacimiento_CO_Acreditado__c</fullName>
    <label>Fecha de Nacimiento CO Acreditado</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Co_Acreditado__c/fields/Lugar_de_nacimiento__c.field-meta.xml
<CustomField>
    <fullName>Lugar_de_nacimiento__c</fullName>
    <label>Lugar de nacimiento Co Acreditado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lugar_Nacimiento</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Co_Acreditado__c/fields/Nombre__c.field-meta.xml
<CustomField>
    <fullName>Nombre__c</fullName>
    <label>Nombre Co Acreditado</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Co_Acreditado__c/fields/Sexo__c.field-meta.xml
<CustomField>
    <fullName>Sexo__c</fullName>
    <label>Sexo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MASCULINO</fullName>
            </value>
            <value>
                <fullName>FEMENINO</fullName>
            </value>
            <value>
                <fullName>INDISTINTO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/Lugar_Nacimiento.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AGUASCALIENTES</fullName>
    </customValue>
    <customValue>
        <fullName>BAJA CALIFORNIA</fullName>
    </customValue>
    <customValue>
        <fullName>BAJA CALIFORNIA SUR</fullName>
    </customValue>
    <customValue>
        <fullName>CAMPECHE</fullName>
    </customValue>
    <customValue>
        <fullName>CHIAPAS</fullName>
    </customValue>
    <customValue>
        <fullName>CHIHUAHUA</fullName>
    </customValue>
    <customValue>
        <fullName>CIUDAD DE MEXICO</fullName>
    </customValue>
    <customValue>
        <fullName>COAHUILA</fullName>
    </customValue>
    <customValue>
        <fullName>COLIMA</fullName>
    </customValue>
    <customValue>
        <fullName>DURANGO</fullName>
    </customValue>
    <customValue>
        <fullName>ESTADO DE MEXICO</fullName>
    </customValue>
    <customValue>
        <fullName>EXTRANJERO</fullName>
    </customValue>
    <customValue>
        <fullName>GUANAJUATO</fullName>
    </customValue>
    <customValue>
        <fullName>GUERRERO</fullName>
    </customValue>
    <customValue>
        <fullName>HIDALGO</fullName>
    </customValue>
    <customValue>
        <fullName>JALISCO</fullName>
    </customValue>
    <customValue>
        <fullName>MICHOACAN</fullName>
    </customValue>
    <customValue>
        <fullName>MORELOS</fullName>
    </customValue>
    <customValue>
        <fullName>NAYARIT</fullName>
    </customValue>
    <customValue>
        <fullName>NUEVO LEON</fullName>
    </customValue>
    <customValue>
        <fullName>OAXACA</fullName>
    </customValue>
    <customValue>
        <fullName>PUEBLA</fullName>
    </customValue>
    <customValue>
        <fullName>QUERETARO</fullName>
    </customValue>
    <customValue>
        <fullName>QUINTANA ROO</fullName>
    </customValue>
    <customValue>
        <fullName>SAN LUIS POTOSI</fullName>
    </customValue>
    <customValue>
        <fullName>SINALOA</fullName>
    </customValue>
    <customValue>
        <fullName>SONORA</fullName>
    </customValue>
    <customValue>
        <fullName>TABASCO</fullName>
    </customValue>
    <customValue>
        <fullName>TAMAULIPAS</fullName>
    </customValue>
    <customValue>
        <fullName>TLAXCALA</fullName>
    </customValue>
    <masterLabel>Lugar de Nacimiento</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/CoAcreditadoTriggerHandler_Test.cls
@isTest
public class CoAcreditadoTriggerHandler_Test {
	static TestMethod void Test1() {
        Co_Acreditado__c c = new Co_Acreditado__c(Apellido_Paterno_CO_Acreditado__c = 'Paterno', Apellido_Materno_CO_Acreditado__c = 'Materno', Sexo__c = 'MASCULINO',
                                                 Nombre__c = 'nom',Fecha_de_Nacimiento_CO_Acreditado__c = system.today(),Lugar_de_nacimiento__c = 'AGUASCALIENTES');
        insert c;
        c.Lugar_de_nacimiento__c = 'BAJA CALIFORNIA';
        update c;
    }
}