unpackaged/main/default/objects/SolicitudTerreno__c/SolicitudTerreno__c.object-meta.xml
<CustomObject>
    <label>Solicitud de Terreno</label>
    <nameField>
        <label>Nombre de Solicitud de Terreno</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Solicitudes de Terreno</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SolicitudTerreno__c/fields/NombreDeDocumento__c.field-meta.xml
<CustomField>
    <fullName>NombreDeDocumento__c</fullName>
    <externalId>true</externalId>
    <label>Nombre (Id Externo)</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/SolicitudTerreno__c/fields/StatusInternoAprobacion__c.field-meta.xml
<CustomField>
    <fullName>StatusInternoAprobacion__c</fullName>
    <description>El campo se actualizara cuando se Apruebe/Rechace una solicitud desde SalesForce.</description>
    <label>Status Interno Aprobacion</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/trg_Aprobacion_SolicitudTerreno_Test.cls
@isTest
public class trg_Aprobacion_SolicitudTerreno_Test {
    static TestMethod void testMethod1() {
        SolicitudTerreno__c solicitud = new SolicitudTerreno__c();
        solicitud.Name = 'TEST' ;
        solicitud.NombreDeDocumento__c = 'test';
        solicitud.StatusInternoAprobacion__c = 'xxxxxx';
        insert solicitud;
        Test.startTest();
        solicitud.StatusInternoAprobacion__c = 'Aprobado';
        solicitud.Aprobacion_Externa__c = false;
        update solicitud;
        Test.stopTest();
    }
     static TestMethod void testMethod2() {
        SolicitudTerreno__c solicitud = new SolicitudTerreno__c();
        solicitud.Name = 'TEST' ;
        solicitud.NombreDeDocumento__c = 'test';
        solicitud.StatusInternoAprobacion__c = 'xxxxxx';
        insert solicitud;
        Test.startTest();
        solicitud.StatusInternoAprobacion__c = 'Aprobado';
        solicitud.Aprobacion_Externa__c = true;
        update solicitud;
        Test.stopTest();
    }
}