unpackaged/main/default/objects/Check_List__c/Check_List__c.object-meta.xml
<CustomObject>
    <label>Check List</label>
    <nameField>
        <label>No. CheckList</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Check List</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Check_List__c/fields/Estatus__c.field-meta.xml
<CustomField>
    <fullName>Estatus__c</fullName>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Abierto</fullName>
            </value>
            <value>
                <fullName>Guardado</fullName>
            </value>
            <value>
                <fullName>Cerrado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Check_List__c/fields/Vivienda__c.field-meta.xml
<CustomField>
    <fullName>Vivienda__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vivienda</label>
    <referenceTo>Inventario__c</referenceTo>
    <relationshipLabel>Check List</relationshipLabel>
    <relationshipName>CheckList</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Fraccionamiento__c/Fraccionamiento__c.object-meta.xml
<CustomObject>
    <label>Fraccionamiento</label>
    <nameField>
        <label>Nombre de Fraccionamiento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fraccionamientos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Fraccionamiento__c/fields/Prototipo__c.field-meta.xml
<CustomField>
    <fullName>Prototipo__c</fullName>
    <label>Prototipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prototipo 1</fullName>
            </value>
            <value>
                <fullName>Prototipo 2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Inventario__c/Inventario__c.object-meta.xml
<CustomObject>
    <label>Proceso ATC</label>
    <nameField>
        <label>Id Vivienda</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProcesosATC</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Inventario__c/fields/Condominio__c.field-meta.xml
<CustomField>
    <fullName>Condominio__c</fullName>
    <label>Condominio</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Conjunto__c.field-meta.xml
<CustomField>
    <fullName>Conjunto__c</fullName>
    <label>Conjunto</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Direccionoficial__c.field-meta.xml
<CustomField>
    <fullName>Direccionoficial__c</fullName>
    <label>Dirección oficial</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Entregada__c.field-meta.xml
<CustomField>
    <fullName>Entregada__c</fullName>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Por Entregar</fullName>
            </value>
            <value>
                <fullName>No Entregado</fullName>
            </value>
            <value>
                <fullName>Entregado</fullName>
            </value>
            <value>
                <fullName>Agendada</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/EnviarSibel__c.field-meta.xml
<CustomField>
    <fullName>EnviarSibel__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enviar a Sibel</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/FechaDTU_DTI__c.field-meta.xml
<CustomField>
    <fullName>FechaDTU_DTI__c</fullName>
    <label>Fecha DTU o DTI</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/FechaDTUDTI__c.field-meta.xml
<CustomField>
    <fullName>FechaDTUDTI__c</fullName>
    <label>Fecha DTU o DTI</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Fracc__c.field-meta.xml
<CustomField>
    <fullName>Fracc__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fraccionamiento</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>(1 OR 5 OR 2 OR 4) AND 3</booleanFilter>
        <filterItems>
            <field>$User.Fraccionamiento_autorizado__c</field>
            <operation>contains</operation>
            <valueField>Fraccionamiento__c.Name</valueField>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>Administrador del sistema</value>
        </filterItems>
        <filterItems>
            <field>Fraccionamiento__c.Activo_frac__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$User.Fraccionamiento_autorizado__c</field>
            <operation>equals</operation>
            <value>TODOS</value>
        </filterItems>
        <filterItems>
            <field>$User.Fraccionamiento_autorizado__c</field>
            <operation>contains</operation>
            <valueField>Fraccionamiento__c.Name</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Fraccionamiento__c</referenceTo>
    <relationshipLabel>ProcesosATC</relationshipLabel>
    <relationshipName>Inventarios</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Fraccionamiento__c.field-meta.xml
<CustomField>
    <fullName>Fraccionamiento__c</fullName>
    <label>Fraccionamiento</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Frente__c.field-meta.xml
<CustomField>
    <fullName>Frente__c</fullName>
    <label>Frente</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/IsEntrega__c.field-meta.xml
<CustomField>
    <fullName>IsEntrega__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsEntrega</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Lote__c.field-meta.xml
<CustomField>
    <fullName>Lote__c</fullName>
    <label>Lote</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Manzana__c.field-meta.xml
<CustomField>
    <fullName>Manzana__c</fullName>
    <label>Manzana</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/NumeroInterior__c.field-meta.xml
<CustomField>
    <fullName>NumeroInterior__c</fullName>
    <label>Número Interno</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Plantas__c.field-meta.xml
<CustomField>
    <fullName>Plantas__c</fullName>
    <formula>Proto__r.Plantas__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Plantas</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Proto__c.field-meta.xml
<CustomField>
    <fullName>Proto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prototipo</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Prototipo__c.Fraccionamiento__c</field>
            <operation>equals</operation>
            <valueField>$Source.Fracc__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Prototipo__c</referenceTo>
    <relationshipLabel>ProcesosATC</relationshipLabel>
    <relationshipName>Inventarios</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Prototipo__c.field-meta.xml
<CustomField>
    <fullName>Prototipo__c</fullName>
    <label>Prototipo</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Sector__c.field-meta.xml
<CustomField>
    <fullName>Sector__c</fullName>
    <label>Sector</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Unidad_privativa__c.field-meta.xml
<CustomField>
    <fullName>Unidad_privativa__c</fullName>
    <label>Unidad privativa</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/LogATC__c/LogATC__c.object-meta.xml
<CustomObject>
    <label>LogATC</label>
    <nameField>
        <label>Nombre de LogATC</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LogATC</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/LogATC__c/fields/FechaHora__c.field-meta.xml
<CustomField>
    <fullName>FechaHora__c</fullName>
    <label>Fecha y Hora</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/LogATC__c/fields/Mensaje__c.field-meta.xml
<CustomField>
    <fullName>Mensaje__c</fullName>
    <label>Mensaje</label>
    <length>130000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/LogATC__c/fields/Metodo__c.field-meta.xml
<CustomField>
    <fullName>Metodo__c</fullName>
    <label>Método</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Prototipo__c/Prototipo__c.object-meta.xml
<CustomObject>
    <label>Prototipo</label>
    <nameField>
        <label>Prototipo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prototipos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Prototipo__c/fields/Fraccionamiento__c.field-meta.xml
<CustomField>
    <fullName>Fraccionamiento__c</fullName>
    <label>Fraccionamiento</label>
    <referenceTo>Fraccionamiento__c</referenceTo>
    <relationshipLabel>Prototipos</relationshipLabel>
    <relationshipName>Prototipos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Prototipo__c/fields/Plantas__c.field-meta.xml
<CustomField>
    <fullName>Plantas__c</fullName>
    <label>Plantas</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Vivienda__c/Vivienda__c.object-meta.xml
<CustomObject>
    <label>Vivienda</label>
    <nameField>
        <label>Vivienda</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Viviendas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Vivienda__c/fields/Estatus__c.field-meta.xml
<CustomField>
    <fullName>Estatus__c</fullName>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>17</fullName>
                <label>Disponible</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>Reservado</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>Formalizado</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>Escriturado</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>Entregado</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>No Disponible</label>
            </value>
            <value>
                <fullName>21</fullName>
                <label>Migración / Disponible</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Vivienda__c/fields/Fraccionamiento__c.field-meta.xml
<CustomField>
    <fullName>Fraccionamiento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fraccionamiento</label>
    <referenceTo>Fraccionamiento__c</referenceTo>
    <relationshipLabel>Viviendas</relationshipLabel>
    <relationshipName>Viviendas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Vivienda__c/fields/Lote__c.field-meta.xml
<CustomField>
    <fullName>Lote__c</fullName>
    <label>Lote</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Vivienda__c/fields/Manzana__c.field-meta.xml
<CustomField>
    <fullName>Manzana__c</fullName>
    <label>Manzana</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Vivienda__c/fields/Prototipo__c.field-meta.xml
<CustomField>
    <fullName>Prototipo__c</fullName>
    <label>Prototipo</label>
    <referenceTo>Prototipo__c</referenceTo>
    <relationshipLabel>Viviendas</relationshipLabel>
    <relationshipName>Viviendas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Vivienda__c/fields/Unidad_Privativa__c.field-meta.xml
<CustomField>
    <fullName>Unidad_Privativa__c</fullName>
    <label>Unidad Privativa</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/ViviendaWSController.cls
public class ViviendaWSController {
    
    @future(callout=true)
    public static void run(String dias){        
        if(dias == null){
            dias = '1';
        }
        LogATC__c log = new LogATC__c();
        log.FechaHora__c = Datetime.now();
        log.Metodo__c = 'ViviendaWS';
        
        RecordType planta1 = [SELECT Id, Name FROM RecordType WHERE Name = 'Planta 1'];
        RecordType planta2 = [SELECT Id, Name FROM RecordType WHERE Name = 'Planta 2'];
        RecordType planta3 = [SELECT Id, Name FROM RecordType WHERE Name = 'Planta 3'];
        
        
        esbJaverComMxAtencionclientesInvviv.InvViviendaBindingQSPort wsPort = new esbJaverComMxAtencionclientesInvviv.InvViviendaBindingQSPort();
        
        wsPort.timeout_x = 20000;
        
        esbJaverComMxAtencionclientesInvviv.GetInvViviendaRs_element respuesta = new esbJaverComMxAtencionclientesInvviv.GetInvViviendaRs_element();
        esbJaverComMxAtencionclientesInvviv.ReporteInvVivienda_element env = new esbJaverComMxAtencionclientesInvviv.ReporteInvVivienda_element();
        List<esbJaverComMxAtencionclientesInvviv.Row_element> listObj = new List<esbJaverComMxAtencionclientesInvviv.Row_element>();
        if(!Test.isRunningTest()){
            try{
                respuesta = wsPort.GetInvVivienda(dias);
                
                log.Mensaje__c += 'Estatus SIEBEL: '+respuesta.Result.Success;
                log.Mensaje__c += '\r\n';
                log.Mensaje__c += 'Respuesta SIEBEL: '+respuesta.Result.SysMessage;
                log.Mensaje__c += '\r\n';
                log.Mensaje__c += 'Cantidad de registros: '+listObj.size();
                log.Mensaje__c += '\r\n';
            }catch(Exception o){
                log.Mensaje__c += 'ERROR: '+o.getMessage() +' - '+o.getStackTraceString();
                log.Mensaje__c += '\r\n';
                upsert log;
            }
        }else{
            esbJaverComMxAtencionclientesInvviv n = new esbJaverComMxAtencionclientesInvviv();
            n.method();
            esbJaverComMxAtencionclientesInvviv.GetInvViviendaRq_element ff = new esbJaverComMxAtencionclientesInvviv.GetInvViviendaRq_element();
            ff.NumDias = '1';
            respuesta.Result = new esbJaverComMxAtencionclientesInvviv.Result_element();
            respuesta.ReporteInvVivienda = new esbJaverComMxAtencionclientesInvviv.ReporteInvVivienda_element();
            respuesta.ReporteInvVivienda.Row = new List<esbJaverComMxAtencionclientesInvviv.Row_element>();
            respuesta.ReporteInvVivienda.ItemQuantity = 1;
            
            esbJaverComMxAtencionclientesInvviv.Row_element e = new esbJaverComMxAtencionclientesInvviv.Row_element();
            e.IdVivienda = '';
            e.Fraccionamiento = '';
            e.Prototipo = '';
            e.NumInterno = '';
            e.NunInterior = '';
            e.IdManzana = '';
            e.Manzana = '';
            e.IdLote = '';
            e.Lote = '';
            e.Sector = '';
            e.UnidadPrivativa = '';
            e.Condominio = '';
            e.Dtu = '';
            e.DireccionOficial = '';
            e.Frente = '';
            e.Seccion = '';
            e.Conjunto = '';
            e.Concepto = '';
            e.Concepto = '';
            respuesta.ReporteInvVivienda.Row.add(e);
        }
        
        env = respuesta.ReporteInvVivienda;
        listObj = env.Row;
        
        List<String> filtroViviendas = new List<String>();
        List<Id> filtroFraccionamientos = new List<Id>();
        
        if(listObj != null){
            if(!listObj.isEmpty()){
                for(esbJaverComMxAtencionclientesInvviv.Row_element vivienda : listObj){
                    filtroViviendas.add(vivienda.NumInterno);
                }
            }
        }
        
        Map<String, Id> mapFracc = new Map<String,Id>();
        Map<String, Prototipo__c> mapProto = new Map<String,Prototipo__c>();
        Map<String, Inventario__c> inventarios = new Map<String,Inventario__c>();
        
        
        List<Inventario__c> allInventarios = [SELECT Id, Name,Fracc__r.Id FROM Inventario__c WHERE Name IN :filtroViviendas LIMIT 13000];
        for(Inventario__c i :allInventarios){
            filtroFraccionamientos.add(i.Fracc__r.Id);
            inventarios.put(i.Name, i);
        }
        
        List<Fraccionamiento__c> fraccionamientos = [SELECT Id, Name FROM Fraccionamiento__c WHERE Id IN :filtroFraccionamientos LIMIT 13000];
        for(Fraccionamiento__c f: fraccionamientos){
            mapFracc.put(f.Name.toUpperCase(), f.Id);
        }
        
        List<Prototipo__c> prototipos = [SELECT Id, Name, Fraccionamiento__r.Name, Plantas__c FROM Prototipo__c WHERE Fraccionamiento__r.Id IN: filtroFraccionamientos LIMIT 13000];        
        for(Prototipo__c p: prototipos){
            mapProto.put(p.Name.toUpperCase() + ' '+p.Fraccionamiento__r.Name, p);
        }
        
        Set<Inventario__c> upsertInventarios = new Set<Inventario__c>();
        if(listObj != null){
            if(!listObj.isEmpty()){
                for(esbJaverComMxAtencionclientesInvviv.Row_element vivienda : listObj){
                    Inventario__c inventario = new Inventario__c();
                    
                    inventario.Name = vivienda.NumInterno;
                    
                    inventario.Fraccionamiento__c = vivienda.Fraccionamiento;
                    
                    try{
                        inventario.Fracc__c = mapFracc.get(vivienda.Fraccionamiento.toUpperCase());
                    }catch(Exception e){
                        inventario.Fracc__c = null;
                    }
                    
                    inventario.IsEntrega__c = false;
                    inventario.Prototipo__c = vivienda.Prototipo;
                    
                    try{
                        inventario.Proto__c = mapProto.get(vivienda.Prototipo.toUpperCase()+' '+vivienda.Fraccionamiento.toUpperCase()).Id;
                    }catch(Exception e){
                        inventario.Proto__c = null;
                    }
                    
                    inventario.NumeroInterior__c = vivienda.NumInterno;
                    //inventario. = vivienda.NunInterior;
                    //inventario.Manzana__c = vivienda.IdManzana;
                    inventario.Manzana__c = vivienda.Manzana;
                    //inventario. = vivienda.IdLote;
                    inventario.Lote__c = vivienda.Lote;
                    inventario.Sector__c = vivienda.Sector;
                    inventario.Unidad_privativa__c = vivienda.UnidadPrivativa;
                    inventario.Condominio__c = vivienda.Condominio;
                    
                    inventario.FechaDTU_DTI__c = vivienda.Dtu;
                    
                    try{
                        inventario.FechaDTUDTI__c = getDateString(vivienda.Dtu);
                    }catch(Exception d){
                        inventario.FechaDTUDTI__c = null;
                    }
                    
                    inventario.Direccionoficial__c = vivienda.DireccionOficial;
                    inventario.Frente__c = vivienda.Frente;
                    //inventario. = vivienda.Seccion;
                    inventario.Conjunto__c = vivienda.Conjunto;
                    //inventario. = vivienda.Concepto;
                    inventario.EnviarSibel__c = false;
                    
                    try{
                        inventario.Id = inventarios.get(inventario.Name).Id;
                    }catch(Exception o){
                        
                    }
                    
                    upsertInventarios.add(inventario);
                    
                    if(inventario.Id == null){
                        inventario.Entregada__c = 'No Entregado';
                        insert inventario;
                        
                        Check_List__c ch = new Check_List__c();
                        
                        ch.Vivienda__c = inventario.Id;
                        
                        if(inventario.Proto__c != null){
                            if(mapProto.get(vivienda.Prototipo.toUpperCase()+' '+vivienda.Fraccionamiento.toUpperCase()).Plantas__c.equals('1')){
                                ch.RecordTypeId = planta1.ID;
                            }else if(mapProto.get(vivienda.Prototipo.toUpperCase()+' '+vivienda.Fraccionamiento.toUpperCase()).Plantas__c.equals('3')){
                                ch.RecordTypeId = planta3.ID;
                            }else{
                                ch.RecordTypeId = planta2.ID;
                            }
                        }else{
                            ch.RecordTypeId = planta2.Id;
                        }
                        ch.Name =vivienda.Manzana +'-' + vivienda.Lote + '-' +vivienda.NumInterno+ ' - ' + vivienda.Fraccionamiento.toUpperCase() +' V1';
                        ch.Estatus__c = 'Abierto';
                        insert ch;
                    }else{
                        update inventario;
                    }
                }
                log.Mensaje__c += 'Inventarios Insertados/Actualizados: '+upsertInventarios.size();
                log.Mensaje__c += '\r\n';
                upsert log;
            }else{
                log.Mensaje__c += 'No hay inventarios';
                log.Mensaje__c += '\r\n';
                upsert log;
            }
        }else{
            log.Mensaje__c += 'No hay inventarios';
            log.Mensaje__c += '\r\n';
            upsert log;
        }
    }
    
    public static Date getDateString(String fecha){
        //2015-01-06T00:00:00.000-05:00
        String[] fechaArray = fecha.split('T');
        System.debug('FECHARRAY : '+fechaArray);
        System.debug('AAA: '+fechaArray[1].substring(0,  fechaArray[1].lastIndexOf('.')));
        return Date.valueOf(fechaArray[0] + ' ' + fechaArray[1].substring(0,  fechaArray[1].lastIndexOf('.')));
    }
    
    
    public ViviendaWSController(){
    }
}