unpackaged/main/default/objects/Check_List__c/Check_List__c.object-meta.xml
<CustomObject>
    <label>Check List</label>
    <nameField>
        <label>No. CheckList</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Check List</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Check_List__c/fields/Completado__c.field-meta.xml
<CustomField>
    <fullName>Completado__c</fullName>
    <label>% Completado</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Check_List__c/fields/Estatus__c.field-meta.xml
<CustomField>
    <fullName>Estatus__c</fullName>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Abierto</fullName>
            </value>
            <value>
                <fullName>Guardado</fullName>
            </value>
            <value>
                <fullName>Cerrado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Check_List__c/fields/Seleccionartodo__c.field-meta.xml
<CustomField>
    <fullName>Seleccionartodo__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Seleccionar todo</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Check_List__c/fields/Vivienda__c.field-meta.xml
<CustomField>
    <fullName>Vivienda__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vivienda</label>
    <referenceTo>Inventario__c</referenceTo>
    <relationshipLabel>Check List</relationshipLabel>
    <relationshipName>CheckList</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Checklist1__c/Checklist1__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Configuración del checklist planta1</description>
    <label>Checklist1</label>
</CustomObject>

unpackaged/main/default/objects/CheckList2__c/CheckList2__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Configuración del checklist planta2</description>
    <label>CheckList2</label>
</CustomObject>

unpackaged/main/default/objects/Checklist3__c/Checklist3__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Configuración del checklist planta3</description>
    <label>CheckList3</label>
</CustomObject>

unpackaged/main/default/objects/Inventario__c/Inventario__c.object-meta.xml
<CustomObject>
    <label>Proceso ATC</label>
    <nameField>
        <label>Id Vivienda</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProcesosATC</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Inventario__c/fields/PorcentajeCheckList__c.field-meta.xml
<CustomField>
    <fullName>PorcentajeCheckList__c</fullName>
    <label>Porcentaje Check List</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Vivienda__c/Vivienda__c.object-meta.xml
<CustomObject>
    <label>Vivienda</label>
    <nameField>
        <label>Vivienda</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Viviendas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Vivienda__c/fields/Estatus__c.field-meta.xml
<CustomField>
    <fullName>Estatus__c</fullName>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>17</fullName>
                <label>Disponible</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>Reservado</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>Formalizado</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>Escriturado</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>Entregado</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>No Disponible</label>
            </value>
            <value>
                <fullName>21</fullName>
                <label>Migración / Disponible</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/CheckListController.cls
public class CheckListController{
    public CheckListController(Check_List__c lista){
        Integer pct = 0;
        List<String> okList = new List<String>();
        Map<String, Schema.SObjectField> fieldsMap = Schema.SObjectType.Check_List__c.fields.getMap();
        for (Schema.SObjectField field : fieldsMap.values()){
            if(field.getDescribe().getType() == Schema.DisplayType.BOOLEAN){
                if(field.getDescribe().getName() != 'IsDeleted' && field.getDescribe().getName() != 'Seleccionartodo__c'
                  && field.getDescribe().getName() != 'SoloLectura__c'){
                    if(lista.get(field.getDescribe().getName()) == true){
                        okList.add(field.getDescribe().getName());
                    }
                }
            }
        }
        System.debug('ok->'+okList);
        RecordType p1 = [SELECT Id FROM RecordType WHERE Name = 'Planta 1'];
        RecordType p2 = [SELECT Id FROM RecordType WHERE Name = 'Planta 2'];
        RecordType p3 = [SELECT Id FROM RecordType WHERE Name = 'Planta 3'];
        if(lista.RecordTypeId == p1.Id){
            pct = validarPlanta1(okList);
        }
        if(lista.RecordTypeId == p2.Id){
            pct = validarPlanta2(okList);
        }
        if(lista.RecordTypeId == p3.Id){
            pct = validarPlanta3(okList);
        }
        System.debug('tipo->'+lista.RecordTypeId);
        lista.Completado__c = pct;
        if(pct > 91){
            lista.Estatus__c = 'Cerrado';
        }
        try{
            Inventario__c inv = [SELECT PorcentajeCheckList__c,Id FROM Inventario__c WHERE Id =: lista.Vivienda__c];
            inv.PorcentajeCheckList__c = pct;
            update inv;
        }catch(Exception e){
            System.debug('SE ESTÁ GUARDANDO DESDE EL WS --- ' + e.getMessage() +' ' + e.getLineNumber());
        }
    }
    private Integer validarPlanta1(List<String> okList){
        Integer pct = 0;
        Checklist1__c chs = Checklist1__c.getOrgDefaults();
        for(String d : okList){
            pct += Integer.valueOf(chs.get(d));
        }
        return pct;
    }
    private Integer validarPlanta2(List<String> okList){
        Integer pct = 0;
        Checklist2__c chs = Checklist2__c.getOrgDefaults();
        for(String d : okList){
            pct += Integer.valueOf(chs.get(d));
        }
        return pct;
    }
    private Integer validarPlanta3(List<String> okList){
        Integer pct = 0;
        Checklist3__c chs = Checklist3__c.getOrgDefaults();
        for(String d : okList){
            pct += Integer.valueOf(chs.get(d));
        }
        return pct;
    }
}