unpackaged/main/default/objects/Proveedor__c/Proveedor__c.object-meta.xml
<CustomObject>
    <label>Proveedor</label>
    <nameField>
        <label>Proveedor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proveedores</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Proveedor__c/fields/Producto__c.field-meta.xml
<CustomField>
    <fullName>Producto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Proveedores</relationshipLabel>
    <relationshipName>Proveedores</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Relacion_Precio_Proveedor__c/Relacion_Precio_Proveedor__c.object-meta.xml
<CustomObject>
    <label>Proveedor</label>
    <nameField>
        <displayFormat>RPP-{000000}</displayFormat>
        <label>Folio</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proveedores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Relacion_Precio_Proveedor__c/fields/Producto__c.field-meta.xml
<CustomField>
    <fullName>Producto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Relacion_Productos_Proveedores</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Relacion_Precio_Proveedor__c/fields/Proveedor__c.field-meta.xml
<CustomField>
    <fullName>Proveedor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proveedor</label>
    <referenceTo>Proveedor__c</referenceTo>
    <relationshipName>Relacion_Productos_Proveedores</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/Relacion_Proveedor.cls
public class Relacion_Proveedor {
    @AuraEnabled
    public static String saveRecord(String provId, string prodId){
        string message = '';
        try {
            List<Proveedor__c> provlist = [Select Id, Name from Proveedor__c where Id =: provId];
            String provName  ;
            if(provlist != null && provlist.size()>0){
                provName = provlist[0].Name;
            }
            list<Relacion_Precio_Proveedor__c> plist= [select id, Name ,Name__c, Producto__c from Relacion_Precio_Proveedor__c Where Name__c =: provName AND Producto__c = :prodId];
            if(plist != null && plist.size()>0){
                message = 'Error al duplicar!'; 
            }
            else{
                Relacion_Precio_Proveedor__c pro = new Relacion_Precio_Proveedor__c();
                pro.Producto__c = prodId;
                pro.Proveedor__c = provId;
                insert pro;
                message = 'success!';
            }
            return message;
        }
        catch(DmlException e) {
            System.debug('The following exception has occurred: ' + e.getMessage());
            message =  e.getDmlMessage(0);
            return message;
        }
    }
}