unpackaged/main/default/objects/Account/fields/Apellidomaterno_cta__c.field-meta.xml
<CustomField>
    <fullName>Apellidomaterno_cta__c</fullName>
    <label>Apellido Materno</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Canal_de_Venta__c.field-meta.xml
<CustomField>
    <fullName>Canal_de_Venta__c</fullName>
    <label>Canal de Venta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Canal_de_Venta</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/CorreoElectronico__c.field-meta.xml
<CustomField>
    <fullName>CorreoElectronico__c</fullName>
    <label>Correo Electrónico</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Otro_Telefono__c.field-meta.xml
<CustomField>
    <fullName>Otro_Telefono__c</fullName>
    <label>Otro Teléfono</label>
    <type>Phone</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/TelefonoCelular__c.field-meta.xml
<CustomField>
    <fullName>TelefonoCelular__c</fullName>
    <label>Teléfono Celular</label>
    <type>Phone</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Prospecto.recordType-meta.xml
<RecordType>
    <fullName>Prospecto</fullName>
    <active>true</active>
    <label>Prospecto</label>
</RecordType>

unpackaged/main/default/objects/WhatsApp__c/WhatsApp__c.object-meta.xml
<CustomObject>
    <label>Mensaje de WhatsApp</label>
    <nameField>
        <displayFormat>W-{0000}</displayFormat>
        <label>WhatsApp Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mensajes de WhatsApp</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/WhatsApp__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

unpackaged/main/default/objects/WhatsApp__c/fields/Prospect__c.field-meta.xml
<CustomField>
    <fullName>Prospect__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prospect</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>WhatsApp</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/globalValueSets/Canal_de_Venta.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>DIGITAL ASESOR</fullName>
    </customValue>
    <customValue>
        <fullName>EVENTO</fullName>
    </customValue>
    <customValue>
        <fullName>LLAMADA CALL CENTER</fullName>
    </customValue>
    <customValue>
        <fullName>MACROVENTA</fullName>
    </customValue>
    <customValue>
        <fullName>MACROVENTA 2015</fullName>
    </customValue>
    <customValue>
        <fullName>MEDIO PUBLICITARIO</fullName>
    </customValue>
    <customValue>
        <fullName>MEDIOS DIGITALES</fullName>
    </customValue>
    <customValue>
        <fullName>PROGRAMAS INSTITUCIONALES</fullName>
    </customValue>
    <customValue>
        <fullName>PROMOTOR EXTERNO</fullName>
    </customValue>
    <customValue>
        <fullName>PROSPECCION</fullName>
    </customValue>
    <customValue>
        <fullName>PROSPECTO ASESOR</fullName>
    </customValue>
    <customValue>
        <fullName>REFERIDOS</fullName>
    </customValue>
    <customValue>
        <fullName>VENTA EMPRESARIAL</fullName>
    </customValue>
    <customValue>
        <fullName>CARGA INICIAL</fullName>
    </customValue>
    <masterLabel>Canal de Venta</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/WhatsappScheduler_Test.cls
@isTest
public class WhatsappScheduler_Test {
    static TestMethod void testScheduledJob() {
         Account acc = new Account();
        acc.FirstName= 'Lopez';
        acc.LastName= 'test';
        acc.RecordTypeId =Schema.sObjectType.Account.getRecordTypeInfosBydevelopername().get('Prospecto_Persona_Fisica').getRecordTypeId();
        acc.CorreoElectronico__c = 'test@prospects.com';
        acc.Apellidomaterno_cta__c = 'dahuoh';
        acc.Phone = '+528119928819';
        acc.Otro_Telefono__c = '+528119928819';
        acc.TelefonoCelular__c='+525530303030'; 
        acc.Canal_de_Venta__c = 'PROSPECTO ASESOR';
        insert acc;
        WhatsApp__c wp = new WhatsApp__c();
        wp.Message__c = 'tset';
        wp.Prospect__c = acc.Id ;
        insert wp;
        WhatsApp__c wp1 = new WhatsApp__c();
        wp1.Message__c = 'test';
        wp1.Prospect__c = acc.Id ;
        insert wp1;
        Attachment att = new Attachment();
        att.Body = Blob.valueOf('test');
        att.ParentId = wp.id;
        att.Description = 'Whatsapp media - ';
        att.Name = 'test';
        att.isprivate = false;
        insert att; 
        Attachment att1 = new Attachment();
        att1.Body = Blob.valueOf('test');
        att1.ParentId = wp1.id;
        att1.Description = 'Whatsapp media - ';
        att1.Name = 'test';
        att1.isprivate = false;
        insert att1; 
        Datetime scheduleTime = Datetime.now().addSeconds(55);
        String cronExpression = '0 ' + scheduleTime.minute() + ' ' + scheduleTime.hour() + ' ' + scheduleTime.day() + ' ' + scheduleTime.month() + ' ? ' + scheduleTime.year();
        Test.startTest();
        String jobId = System.schedule('Test Job', cronExpression, new WhatsappScheduler());
        Test.stopTest();
        
    }
}