unpackaged/main/default/objects/Account/fields/Apellidomaterno_cta__c.field-meta.xml
<CustomField>
    <fullName>Apellidomaterno_cta__c</fullName>
    <label>Apellido Materno</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Asesor__c.field-meta.xml
<CustomField>
    <fullName>Asesor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asesor</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR 3</booleanFilter>
        <errorMessage>El usuario seleccionado no tiene asignado el fraccionamiento elegido.</errorMessage>
        <filterItems>
            <field>User.ProfileId</field>
            <operation>equals</operation>
            <value>00e23000000anFuAAI</value>
        </filterItems>
        <filterItems>
            <field>User.FraccionamientoAutorizados__c</field>
            <operation>contains</operation>
            <valueField>$Source.Nombre_Fraccionamiento__c</valueField>
        </filterItems>
        <filterItems>
            <field>User.ProfileId</field>
            <operation>equals</operation>
            <value>00e23000000anG0AAI</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Fraccionamiento_cta__c.field-meta.xml
<CustomField>
    <fullName>Fraccionamiento_cta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fraccionamiento</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>(1 OR 5 OR 2 OR 4 OR 6) AND 3</booleanFilter>
        <filterItems>
            <field>$User.Fraccionamiento_autorizado__c</field>
            <operation>contains</operation>
            <valueField>Fraccionamiento__c.Name</valueField>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>Administrador del sistema</value>
        </filterItems>
        <filterItems>
            <field>Fraccionamiento__c.Activo_frac__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$User.Fraccionamiento_autorizado__c</field>
            <operation>equals</operation>
            <value>TODOS</value>
        </filterItems>
        <filterItems>
            <field>$User.FraccionamientoAutorizados__c</field>
            <operation>contains</operation>
            <valueField>Fraccionamiento__c.Name</valueField>
        </filterItems>
        <filterItems>
            <field>$User.Fraccionamiento_autorizado__c</field>
            <operation>contains</operation>
            <valueField>Fraccionamiento__c.Name</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Fraccionamiento__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Nombre__c.field-meta.xml
<CustomField>
    <fullName>Nombre__c</fullName>
    <formula>IF(
 OR(
  RecordType.DeveloperName = &#39;Prospecto_Persona_Fisica&#39;,
  RecordType.DeveloperName = &#39;Afluente_Persona_Fisica&#39;,
  RecordType.DeveloperName = &#39;Cliente_Persona_Fisica&#39;),
 FirstName + &#39; &#39; + LastName + &#39; &#39; + Apellidomaterno_cta__c,
 Name + &#39; &#39; +  Apellidopaterno_cta__c + &#39; &#39; + Apellidomaterno_cta__c
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nombre Completo</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Prospectador__c.field-meta.xml
<CustomField>
    <fullName>Prospectador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prospectador</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR 3</booleanFilter>
        <filterItems>
            <field>User.ProfileId</field>
            <operation>equals</operation>
            <value>00e23000000anG7AAI</value>
        </filterItems>
        <filterItems>
            <field>User.FraccionamientoAutorizados__c</field>
            <operation>contains</operation>
            <valueField>$Source.Nombre_Fraccionamiento__c</valueField>
        </filterItems>
        <filterItems>
            <field>User.ProfileId</field>
            <operation>equals</operation>
            <value>00e23000000anG0AAI</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Cuentas1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Fraccionamiento__c/Fraccionamiento__c.object-meta.xml
<CustomObject>
    <label>Fraccionamiento</label>
    <nameField>
        <label>Nombre de Fraccionamiento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fraccionamientos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/User/fields/FRACCIONAMIENTOS__c.field-meta.xml
<CustomField>
    <fullName>FRACCIONAMIENTOS__c</fullName>
    <label>FRACCIONAMIENTOS</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ACACIAS</fullName>
            </value>
            <value>
                <fullName>ACACIAS II</fullName>
            </value>
            <value>
                <fullName>ALBERI RESIDENCIAL</fullName>
            </value>
            <value>
                <fullName>ALVENTO</fullName>
            </value>
            <value>
                <fullName>ARBOLADA</fullName>
            </value>
            <value>
                <fullName>BOSQUE REAL</fullName>
            </value>
            <value>
                <fullName>BOSQUES DEL NEVADO</fullName>
            </value>
            <value>
                <fullName>MAGNOLIAS IV</fullName>
            </value>
            <value>
                <fullName>MISION DE LOS ANGELES 1ER SECTOR ARCANGELES</fullName>
            </value>
            <value>
                <fullName>MURIEL RESIDENCIAL</fullName>
            </value>
            <value>
                <fullName>PASEO SAN JUNIPERO</fullName>
            </value>
            <value>
                <fullName>PASEOS DEL SUR</fullName>
            </value>
            <value>
                <fullName>PRIVADA BELTERRA</fullName>
            </value>
            <value>
                <fullName>PRIVADAS CARANDAY</fullName>
            </value>
            <value>
                <fullName>PRIVALIA AMBIENTA</fullName>
            </value>
            <value>
                <fullName>TODOS</fullName>
            </value>
            <value>
                <fullName>VALLE DE LINCOLN SECTOR MINAS</fullName>
            </value>
            <value>
                <fullName>VALLE DE SANTA ELENA</fullName>
            </value>
            <value>
                <fullName>VALLE DE TEJEDA II</fullName>
            </value>
            <value>
                <fullName>VALLE SANTA ISABEL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/Homepageclass.cls
public without sharing class Homepageclass {
    @AuraEnabled 
    public static wrap fetchUser(Boolean recent){
        User u = [select id,Name,Profile.Name,Fraccionamientos__c from User where id =: userInfo.getUserId()];
        List<Account>accl = new List<Account>();
        String query = 'select Id, FirstName,Lastname,PersonMobilePhone,Name,Apellidomaterno_cta__c,recordtype.Name,Fraccionamiento_cta__r.Name,Nombre__c,Prospectador__c,Asesor__c,LastModifiedDate,LastViewedDate from Account where CreatedDate !=null';
        if(u.Profile.Name == 'Asesor'){
            query += ' AND Asesor__c = \''+ u.Id+'\'';
        }
        if(u.Profile.Name == 'Prospectador'){
            query += ' AND Prospectador__c = \''+ u.Id+'\'';
        }
        if(recent){
            query += ' Order by LastModifiedDate DESC NULLS LAST LIMIT 5';
        }
        else {
            query += ' Order by LastModifiedDate DESC NULLS LAST';
        }
        accl = Database.query(query);
        wrap wr = new wrap();
        wr.userName = u.Name;
        if(accl != null && accl.size()>0){
            wr.AccountList = accl;
        }
        return wr;
    }
     @AuraEnabled 
    public static void logoutFromSite(){
      JaverClass.logout();
    }
    public class wrap{
        @AuraEnabled public List<Account> AccountList ;	
        @AuraEnabled public String  userName;
    }  
}