unpackaged/main/default/objects/Account/fields/Apellidomaterno_cta__c.field-meta.xml
<CustomField>
    <fullName>Apellidomaterno_cta__c</fullName>
    <label>Apellido Materno</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Canal_de_Venta__c.field-meta.xml
<CustomField>
    <fullName>Canal_de_Venta__c</fullName>
    <label>Canal de Venta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Canal_de_Venta</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/CorreoElectronico__c.field-meta.xml
<CustomField>
    <fullName>CorreoElectronico__c</fullName>
    <label>Correo Electrónico</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Nombre__c.field-meta.xml
<CustomField>
    <fullName>Nombre__c</fullName>
    <formula>IF(
 OR(
  RecordType.DeveloperName = &#39;Prospecto_Persona_Fisica&#39;,
  RecordType.DeveloperName = &#39;Afluente_Persona_Fisica&#39;,
  RecordType.DeveloperName = &#39;Cliente_Persona_Fisica&#39;),
 FirstName + &#39; &#39; + LastName + &#39; &#39; + Apellidomaterno_cta__c,
 Name + &#39; &#39; +  Apellidopaterno_cta__c + &#39; &#39; + Apellidomaterno_cta__c
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nombre Completo</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Nombre_cta__c.field-meta.xml
<CustomField>
    <fullName>Nombre_cta__c</fullName>
    <label>Nombre2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/NSS__c.field-meta.xml
<CustomField>
    <fullName>NSS__c</fullName>
    <inlineHelpText>Obligatorio en Crédito Infonavit o Cofinavit</inlineHelpText>
    <label>NSS</label>
    <length>11</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Account/fields/Otro_Telefono__c.field-meta.xml
<CustomField>
    <fullName>Otro_Telefono__c</fullName>
    <label>Otro Teléfono</label>
    <type>Phone</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Prospecto.recordType-meta.xml
<RecordType>
    <fullName>Prospecto</fullName>
    <active>true</active>
    <label>Prospecto</label>
</RecordType>

unpackaged/main/default/objects/ConsultaWS__c/ConsultaWS__c.object-meta.xml
<CustomObject>
    <label>ConsultaWS</label>
    <nameField>
        <label>Nombre de ConsultaWS</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ConsultaWS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ConsultaWS__c/fields/Apellido_Materno__c.field-meta.xml
<CustomField>
    <fullName>Apellido_Materno__c</fullName>
    <label>Apellido Materno</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ConsultaWS__c/fields/Apellido_Paterno__c.field-meta.xml
<CustomField>
    <fullName>Apellido_Paterno__c</fullName>
    <label>Apellido Paterno</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ConsultaWS__c/fields/NSS__c.field-meta.xml
<CustomField>
    <fullName>NSS__c</fullName>
    <label>NSS</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/globalValueSets/Canal_de_Venta.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>DIGITAL ASESOR</fullName>
    </customValue>
    <customValue>
        <fullName>EVENTO</fullName>
    </customValue>
    <customValue>
        <fullName>LLAMADA CALL CENTER</fullName>
    </customValue>
    <customValue>
        <fullName>MACROVENTA</fullName>
    </customValue>
    <customValue>
        <fullName>MACROVENTA 2015</fullName>
    </customValue>
    <customValue>
        <fullName>MEDIO PUBLICITARIO</fullName>
    </customValue>
    <customValue>
        <fullName>MEDIOS DIGITALES</fullName>
    </customValue>
    <customValue>
        <fullName>PROGRAMAS INSTITUCIONALES</fullName>
    </customValue>
    <customValue>
        <fullName>PROMOTOR EXTERNO</fullName>
    </customValue>
    <customValue>
        <fullName>PROSPECCION</fullName>
    </customValue>
    <customValue>
        <fullName>PROSPECTO ASESOR</fullName>
    </customValue>
    <customValue>
        <fullName>REFERIDOS</fullName>
    </customValue>
    <customValue>
        <fullName>VENTA EMPRESARIAL</fullName>
    </customValue>
    <customValue>
        <fullName>CARGA INICIAL</fullName>
    </customValue>
    <masterLabel>Canal de Venta</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/Test_TestWSManageProspecto.cls
@isTest
public class Test_TestWSManageProspecto {
    static testMethod void mainCuentasUser(){
        Test.startTest();
        CuentasByUserWS c = new CuentasByUserWS();
        c.method();
        Test.stopTest();
    }
    
    static testMethod void mainGeo(){
        Test.startTest();
        geolocalizacion_ctr c = new geolocalizacion_ctr();
        c.method();
        Test.stopTest();
    }
    
    static testMethod void mainCuenta(){
        Account acc = new Account();
        acc.FirstName= 'Lopez';
        acc.LastName= 'test';
        acc.CorreoElectronico__c = 'test@prospects.com';
        acc.Apellidomaterno_cta__c = 'dahuoh';
        acc.PersonBirthdate=date.parse('11/09/1991');
        acc.Phone = '+528119928819';
        acc.Otro_Telefono__c = '+528119928819';
        acc.Canal_de_Venta__c = 'PROSPECTO ASESOR';
        insert acc;
        
    }
    static testMethod void main(){
        Test.startTest();
        Date pruebaDate = date.today();
        pruebadate.addYears(-21);
        TestWSManageProspecto javer = new TestWSManageProspecto();
        list<TestWSManageProspecto.ObjetoRespuesta> resp = new List<TestWSManageProspecto.ObjetoRespuesta>();
        TestWSManageProspecto.ObjetoRespuesta obj = new TestWSManageProspecto.ObjetoRespuesta();
        javer.requestObj = new ConsultaWS__c(
            Nombre__c = 'CLASETEST',
            Apellido_Materno__C = 'ApellidoM',
            Apellido_Paterno__C = 'ApellidoP',
            Fecha_Nacimiento__c = pruebaDate,
            NSS__c = '00000000000'
        );
        resp.add(obj);
        Javer.listResponse = resp;
        ConsultaWS__c con = new ConsultaWS__c(); insert con;
        ApexPages.StandardController controller = new ApexPages.StandardController(con);
        TestWSManageProspecto javer1 = new TestWSManageProspecto(controller);
        Javer.consultar();
        javer.method();
        javer.guardarNuevo();
        List<Account> cuentaBorrar = [SELECT Id, Name FROM Account WHERE Nombre_cta__c = 'CLASETEST'];
        if(!cuentaBorrar.isEmpty()){
            delete cuentaBorrar;    
        }
        esbJaverComManageprospecto manage2 = new esbJaverComManageprospecto();
        esbJaverComManageprospectoTypes manage3 = new esbJaverComManageprospectoTypes();
        esbJaverComCommon manage4 = new esbJaverComCommon();
        manage2.method();
        manage3.method();
        manage4.method();
        recursionCheck.canIRun();
        recursionCheck.stopRecursion();
        recursionCheck.allowTorun();
        Acentos.removeAcentos('Á'); 
        GuardarMasComercialAsync.guardar(new List<String>(), 'CLASETEST');
        Test.stopTest();
    }
}