unpackaged/main/default/objects/Account/fields/Apellidomaterno_cta__c.field-meta.xml
<CustomField>
    <fullName>Apellidomaterno_cta__c</fullName>
    <label>Apellido Materno</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Asesor__c.field-meta.xml
<CustomField>
    <fullName>Asesor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asesor</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR 3</booleanFilter>
        <errorMessage>El usuario seleccionado no tiene asignado el fraccionamiento elegido.</errorMessage>
        <filterItems>
            <field>User.ProfileId</field>
            <operation>equals</operation>
            <value>00e23000000anFuAAI</value>
        </filterItems>
        <filterItems>
            <field>User.FraccionamientoAutorizados__c</field>
            <operation>contains</operation>
            <valueField>$Source.Nombre_Fraccionamiento__c</valueField>
        </filterItems>
        <filterItems>
            <field>User.ProfileId</field>
            <operation>equals</operation>
            <value>00e23000000anG0AAI</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Canal_de_Venta__c.field-meta.xml
<CustomField>
    <fullName>Canal_de_Venta__c</fullName>
    <label>Canal de Venta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Canal_de_Venta</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/CorreoElectronico__c.field-meta.xml
<CustomField>
    <fullName>CorreoElectronico__c</fullName>
    <label>Correo Electrónico</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Fraccionamiento_cta__c.field-meta.xml
<CustomField>
    <fullName>Fraccionamiento_cta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fraccionamiento</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>(1 OR 5 OR 2 OR 4 OR 6) AND 3</booleanFilter>
        <filterItems>
            <field>$User.Fraccionamiento_autorizado__c</field>
            <operation>contains</operation>
            <valueField>Fraccionamiento__c.Name</valueField>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>Administrador del sistema</value>
        </filterItems>
        <filterItems>
            <field>Fraccionamiento__c.Activo_frac__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$User.Fraccionamiento_autorizado__c</field>
            <operation>equals</operation>
            <value>TODOS</value>
        </filterItems>
        <filterItems>
            <field>$User.FraccionamientoAutorizados__c</field>
            <operation>contains</operation>
            <valueField>Fraccionamiento__c.Name</valueField>
        </filterItems>
        <filterItems>
            <field>$User.Fraccionamiento_autorizado__c</field>
            <operation>contains</operation>
            <valueField>Fraccionamiento__c.Name</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Fraccionamiento__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Otro_Telefono__c.field-meta.xml
<CustomField>
    <fullName>Otro_Telefono__c</fullName>
    <label>Otro Teléfono</label>
    <type>Phone</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/TelefonoCelular__c.field-meta.xml
<CustomField>
    <fullName>TelefonoCelular__c</fullName>
    <label>Teléfono Celular</label>
    <type>Phone</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/TelefonoOtro__c.field-meta.xml
<CustomField>
    <fullName>TelefonoOtro__c</fullName>
    <label>Teléfono Otro</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Prospecto.recordType-meta.xml
<RecordType>
    <fullName>Prospecto</fullName>
    <active>true</active>
    <label>Prospecto</label>
</RecordType>

unpackaged/main/default/objects/Fraccionamiento__c/Fraccionamiento__c.object-meta.xml
<CustomObject>
    <label>Fraccionamiento</label>
    <nameField>
        <label>Nombre de Fraccionamiento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fraccionamientos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Historial_Asignacion__c/Historial_Asignacion__c.object-meta.xml
<CustomObject>
    <label>Historial de Asignación</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Folio</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Historial de Asignaciones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Historial_Asignacion__c/fields/Asesor__c.field-meta.xml
<CustomField>
    <fullName>Asesor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asesor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Historial_de_Asignaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Historial_Asignacion__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Historico_de_Asignaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Historial_Asignacion__c/fields/Fraccionamiento__c.field-meta.xml
<CustomField>
    <fullName>Fraccionamiento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fraccionamiento</label>
    <referenceTo>Fraccionamiento__c</referenceTo>
    <relationshipLabel>Historial de Asignaciones</relationshipLabel>
    <relationshipName>Historial_de_Asignaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/globalValueSets/Canal_de_Venta.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>DIGITAL ASESOR</fullName>
    </customValue>
    <customValue>
        <fullName>EVENTO</fullName>
    </customValue>
    <customValue>
        <fullName>LLAMADA CALL CENTER</fullName>
    </customValue>
    <customValue>
        <fullName>MACROVENTA</fullName>
    </customValue>
    <customValue>
        <fullName>MACROVENTA 2015</fullName>
    </customValue>
    <customValue>
        <fullName>MEDIO PUBLICITARIO</fullName>
    </customValue>
    <customValue>
        <fullName>MEDIOS DIGITALES</fullName>
    </customValue>
    <customValue>
        <fullName>PROGRAMAS INSTITUCIONALES</fullName>
    </customValue>
    <customValue>
        <fullName>PROMOTOR EXTERNO</fullName>
    </customValue>
    <customValue>
        <fullName>PROSPECCION</fullName>
    </customValue>
    <customValue>
        <fullName>PROSPECTO ASESOR</fullName>
    </customValue>
    <customValue>
        <fullName>REFERIDOS</fullName>
    </customValue>
    <customValue>
        <fullName>VENTA EMPRESARIAL</fullName>
    </customValue>
    <customValue>
        <fullName>CARGA INICIAL</fullName>
    </customValue>
    <masterLabel>Canal de Venta</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/JaverClass_Test.cls
@isTest
public class JaverClass_Test {
    
    @testSetup
    Public static void Setup(){
        Fraccionamiento__c f = new Fraccionamiento__c(Name = 'ACACIAS');
        insert f;
        Account acc = new Account();
        acc.FirstName= 'Lopez';
        acc.LastName= 'test';
        acc.RecordTypeId =Schema.sObjectType.Account.getRecordTypeInfosBydevelopername().get('Prospecto_Persona_Fisica').getRecordTypeId();
        acc.CorreoElectronico__c = 'test@prospects.com';
        acc.Apellidomaterno_cta__c = 'dahuoh';
        acc.PersonBirthdate=date.parse('11/09/1991');
        acc.Phone = '+528119928819';
        acc.TelefonoOtro__c = '+528119928819';
        acc.Otro_Telefono__c = '+528119928819';
        acc.TelefonoCelular__c = '+528119928819';
        acc.Canal_de_Venta__c = 'PROSPECTO ASESOR';
        acc.Fraccionamiento_cta__c= f.Id;
        insert acc;
        
    }
    
    @isTest
    public static void test_logOut(){
        JaverClass.logout();
    }
    
    @isTest 
    public static void test_updateFraccAsessor(){
        Account acc = [Select Id From Account Limit 1];
        Fraccionamiento__c frac = [Select id, Name From Fraccionamiento__c Limit 1];
        Historial_Asignacion__c h = new  Historial_Asignacion__c();
        h.Fraccionamiento__c = frac.id;
        h.Asesor__c = UserInfo.getUserId();
        h.Cuenta__c= acc.id;
        insert h; 
        
        try{
            JaverClass.updateFraccAsessor(acc.Id, frac.Name); 
        }
        catch(Exception e){
            System.debug('Exception'+ e);
        }
        
    }
    
    @isTest 
    public static void test_updateFraccAsessorException(){
        Account acc = [Select Id From Account Limit 1];
        Fraccionamiento__c frac = [Select id, Name From Fraccionamiento__c Limit 1];
        try{
            JaverClass.updateFraccAsessor(acc.Id, frac.Name); 
        }
        catch(Exception e){
            System.debug('Exception'+ e);
        }
        
    }
}