unpackaged/main/default/objects/Account/fields/Apellidomaterno_cta__c.field-meta.xml
<CustomField>
    <fullName>Apellidomaterno_cta__c</fullName>
    <label>Apellido Materno</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Canal_de_Venta__c.field-meta.xml
<CustomField>
    <fullName>Canal_de_Venta__c</fullName>
    <label>Canal de Venta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Canal_de_Venta</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/CorreoElectronico__c.field-meta.xml
<CustomField>
    <fullName>CorreoElectronico__c</fullName>
    <label>Correo Electrónico</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Otro_Telefono__c.field-meta.xml
<CustomField>
    <fullName>Otro_Telefono__c</fullName>
    <label>Otro Teléfono</label>
    <type>Phone</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/TelefonoCelular__c.field-meta.xml
<CustomField>
    <fullName>TelefonoCelular__c</fullName>
    <label>Teléfono Celular</label>
    <type>Phone</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Vivienda_Mas_Reciente__c.field-meta.xml
<CustomField>
    <fullName>Vivienda_Mas_Reciente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vivienda Mas Reciente</label>
    <referenceTo>Inventario__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Prospecto.recordType-meta.xml
<RecordType>
    <fullName>Prospecto</fullName>
    <active>true</active>
    <label>Prospecto</label>
</RecordType>

unpackaged/main/default/objects/Fraccionamiento__c/Fraccionamiento__c.object-meta.xml
<CustomObject>
    <label>Fraccionamiento</label>
    <nameField>
        <label>Nombre de Fraccionamiento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fraccionamientos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Fraccionamiento__c/fields/Jefe_Atencion_Clientes__c.field-meta.xml
<CustomField>
    <fullName>Jefe_Atencion_Clientes__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Jefe de Atención a Clientes</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Fraccionamientos6</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Fraccionamiento__c/fields/Programadora_de_Vivienda__c.field-meta.xml
<CustomField>
    <fullName>Programadora_de_Vivienda__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Programadora de Vivienda</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Fraccionamientos5</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Fraccionamiento__c/fields/Residente1__c.field-meta.xml
<CustomField>
    <fullName>Residente1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Residente 1</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Fraccionamientos</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/Inventario__c.object-meta.xml
<CustomObject>
    <label>Proceso ATC</label>
    <nameField>
        <label>Id Vivienda</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProcesosATC</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Inventario__c/fields/Condominio__c.field-meta.xml
<CustomField>
    <fullName>Condominio__c</fullName>
    <label>Condominio</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Inventarios</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Entregada__c.field-meta.xml
<CustomField>
    <fullName>Entregada__c</fullName>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Por Entregar</fullName>
            </value>
            <value>
                <fullName>No Entregado</fullName>
            </value>
            <value>
                <fullName>Entregado</fullName>
            </value>
            <value>
                <fullName>Agendada</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Fraccionamiento__c.field-meta.xml
<CustomField>
    <fullName>Fraccionamiento__c</fullName>
    <label>Fraccionamiento</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Revisiones_en_Vivienda__c.field-meta.xml
<CustomField>
    <fullName>Revisiones_en_Vivienda__c</fullName>
    <label>¿Cuántas veces revisaste la vivienda?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <default>true</default>
                <label>0</label>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Task/recordTypes/Talkdesk.recordType-meta.xml
<RecordType>
    <fullName>Talkdesk</fullName>
    <active>true</active>
    <label>Talkdesk</label>
</RecordType>

unpackaged/main/default/objects/Visita__c/Visita__c.object-meta.xml
<CustomObject>
    <label>Cita/Visita</label>
    <nameField>
        <displayFormat>VIS-{0000}</displayFormat>
        <label>Número de Cita/Visita</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Citas/Visitas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Visita__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Visitas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Visita__c/fields/Fechaprogramadadevisita__c.field-meta.xml
<CustomField>
    <fullName>Fechaprogramadadevisita__c</fullName>
    <label>Fecha programada</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Visita__c/fields/Horafindevisita__c.field-meta.xml
<CustomField>
    <fullName>Horafindevisita__c</fullName>
    <label>Hora fin de visita</label>
    <required>true</required>
    <type>Time</type>
</CustomField>

unpackaged/main/default/objects/Visita__c/fields/Horaprogramadadevisita__c.field-meta.xml
<CustomField>
    <fullName>Horaprogramadadevisita__c</fullName>
    <label>Hora programada</label>
    <required>true</required>
    <type>Time</type>
</CustomField>

unpackaged/main/default/objects/Visita__c/fields/Inventario__c.field-meta.xml
<CustomField>
    <fullName>Inventario__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventario</label>
    <referenceTo>Inventario__c</referenceTo>
    <relationshipLabel>Citas/Visitas</relationshipLabel>
    <relationshipName>Visitas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/globalValueSets/Canal_de_Venta.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>DIGITAL ASESOR</fullName>
    </customValue>
    <customValue>
        <fullName>EVENTO</fullName>
    </customValue>
    <customValue>
        <fullName>LLAMADA CALL CENTER</fullName>
    </customValue>
    <customValue>
        <fullName>MACROVENTA</fullName>
    </customValue>
    <customValue>
        <fullName>MACROVENTA 2015</fullName>
    </customValue>
    <customValue>
        <fullName>MEDIO PUBLICITARIO</fullName>
    </customValue>
    <customValue>
        <fullName>MEDIOS DIGITALES</fullName>
    </customValue>
    <customValue>
        <fullName>PROGRAMAS INSTITUCIONALES</fullName>
    </customValue>
    <customValue>
        <fullName>PROMOTOR EXTERNO</fullName>
    </customValue>
    <customValue>
        <fullName>PROSPECCION</fullName>
    </customValue>
    <customValue>
        <fullName>PROSPECTO ASESOR</fullName>
    </customValue>
    <customValue>
        <fullName>REFERIDOS</fullName>
    </customValue>
    <customValue>
        <fullName>VENTA EMPRESARIAL</fullName>
    </customValue>
    <customValue>
        <fullName>CARGA INICIAL</fullName>
    </customValue>
    <masterLabel>Canal de Venta</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/TaskTriggerHandler_Test.cls
@isTest 
public without sharing class TaskTriggerHandler_Test {
    @testSetup
    public static void setup(){
        Account acc = new Account();
        acc.FirstName= 'Lopez';
        acc.LastName= 'test';
        acc.RecordTypeId =Schema.sObjectType.Account.getRecordTypeInfosBydevelopername().get('Prospecto_Persona_Fisica').getRecordTypeId();
        acc.CorreoElectronico__c = 'test@prospects.com';
        acc.Apellidomaterno_cta__c = 'dahuoh';
        acc.Phone = '+528119928819';
        acc.Otro_Telefono__c = '+528119928819';
        acc.TelefonoCelular__c='+528119928819'; 
        acc.Canal_de_Venta__c = 'PROSPECTO ASESOR';
        insert acc;
        
        Inventario__c inventario = new Inventario__c();
        inventario.Condominio__c = 'Condominio';
        inventario.Entregada__c = 'Entregado';
        inventario.Cuenta__c = acc.Id;
        inventario.Revisiones_en_Vivienda__c = '3';
        insert inventario;
        
        acc.Vivienda_Mas_Reciente__c = inventario.Id;
        update acc;
        
        Fraccionamiento__c fracc = new Fraccionamiento__c();
        fracc.Name = 'Test';
        fracc.Jefe_Atencion_Clientes__c = UserInfo.getUserId();
        fracc.Programadora_de_Vivienda__c = UserInfo.getUserId();
        fracc.Residente1__c = UserInfo.getUserId();
        insert fracc;
        
        inventario.Fraccionamiento__c = fracc.Id;
        update inventario;
        
    }
    
    @isTest
    private static void TaskTriggerHandler(){
        Account acc = new Account();
        acc.FirstName= 'Lopez';
        acc.LastName= 'test';
        acc.RecordTypeId =Schema.sObjectType.Account.getRecordTypeInfosBydevelopername().get('Prospecto_Persona_Fisica').getRecordTypeId();
        acc.CorreoElectronico__c = 'test@prospects.com';
        acc.Apellidomaterno_cta__c = 'dahuoh';
        acc.Phone = '+528119928819';
        acc.Otro_Telefono__c = '+528119928819';
        acc.TelefonoCelular__c='+528119928819'; 
        acc.Canal_de_Venta__c = 'PROSPECTO ASESOR';
        insert acc;
        
        talkdesk__Talkdesk_Activity__c tda = new talkdesk__Talkdesk_Activity__c();
        tda.Name = 'test';
        tda.talkdesk__Talkdesk_Id__c = 'test';
        insert tda;
        
        Visita__c v = new Visita__c();
        v.Fechaprogramadadevisita__c = System.today()+1;
        v.Horaprogramadadevisita__c = time.newInstance(15, 0, 0, 0);
        v.Horafindevisita__c = time.newInstance(17, 0, 0, 0);
        v.Cuenta__c = acc.id;
        insert v;
        Task task = new Task();
        task.Tipificacion_nivel_1__c = 'Entrega';
        task.Tipificacion_nivel_2__c = 'Solicita Fecha de Entrega';
        task.Telefono__c = '+528119928819';
        task.talkdesk__Talkdesk_Id__c = 'test';
        task.TD_Tiempo_Inicio_de_Llamada__c = '1608768656';
        task.OwnerId = UserInfo.getUserId();
        task.Subject = 'test subject';
        task.RecordTypeId = Schema.SObjectType.Task.getRecordTypeInfosByName().get('Talkdesk').getRecordTypeId();
        insert task;
        
        List <User> adminJaver = [Select Id From User Where Name Like '%Javer%'];
        if(adminJaver != null && adminJaver.size()>0){
            task.OwnerId = adminJaver[0].Id;
        }
        task.WhatId = acc.id;
        update task;
        
        delete task;
    }
}