unpackaged/main/default/objects/Account/fields/Apellidomaterno_cta__c.field-meta.xml
<CustomField>
    <fullName>Apellidomaterno_cta__c</fullName>
    <label>Apellido Materno</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Aprobo_Check_Apellido__c.field-meta.xml
<CustomField>
    <fullName>Aprobo_Check_Apellido__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Aprobo Check Apellido</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Canal_de_Venta__c.field-meta.xml
<CustomField>
    <fullName>Canal_de_Venta__c</fullName>
    <label>Canal de Venta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Canal_de_Venta</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Check_Apellido__c.field-meta.xml
<CustomField>
    <fullName>Check_Apellido__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Check Apellido</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/CorreoElectronico__c.field-meta.xml
<CustomField>
    <fullName>CorreoElectronico__c</fullName>
    <label>Correo Electrónico</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Estatus_Lista_Negra_QEQ__c.field-meta.xml
<CustomField>
    <fullName>Estatus_Lista_Negra_QEQ__c</fullName>
    <label>Estatus Lista Negra</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SIN VALIDAR</fullName>
                <default>true</default>
                <label>SIN VALIDAR</label>
            </value>
            <value>
                <fullName>LISTA NEGRA</fullName>
            </value>
            <value>
                <fullName>LN CONFIRMADO</fullName>
            </value>
            <value>
                <fullName>VALIDADO</fullName>
            </value>
            <value>
                <fullName>PPE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Fecha_de_Afluencia__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_Afluencia__c</fullName>
    <label>Fecha de Afluencia</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Lugar_Nacimiento__c.field-meta.xml
<CustomField>
    <fullName>Lugar_Nacimiento__c</fullName>
    <label>Lugar de Nacimiento</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Nacionalidad__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Lugar_Nacimiento</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Nacionalidad__c.field-meta.xml
<CustomField>
    <fullName>Nacionalidad__c</fullName>
    <label>Nacionalidad</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Nacionalidad</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Otro_Telefono__c.field-meta.xml
<CustomField>
    <fullName>Otro_Telefono__c</fullName>
    <label>Otro Teléfono</label>
    <type>Phone</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Sexo__c.field-meta.xml
<CustomField>
    <fullName>Sexo__c</fullName>
    <label>Sexo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sexo</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Sub_canal_de_venta__c.field-meta.xml
<CustomField>
    <fullName>Sub_canal_de_venta__c</fullName>
    <label>Sub canal de venta</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Canal_de_Venta__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Sub_canal_de_venta</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/TelefonoCelular__c.field-meta.xml
<CustomField>
    <fullName>TelefonoCelular__c</fullName>
    <label>Teléfono Celular</label>
    <type>Phone</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Vivienda_Mas_Reciente__c.field-meta.xml
<CustomField>
    <fullName>Vivienda_Mas_Reciente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vivienda Mas Reciente</label>
    <referenceTo>Inventario__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Prospecto.recordType-meta.xml
<RecordType>
    <fullName>Prospecto</fullName>
    <active>true</active>
    <label>Prospecto</label>
</RecordType>

unpackaged/main/default/objects/Inventario__c/Inventario__c.object-meta.xml
<CustomObject>
    <label>Proceso ATC</label>
    <nameField>
        <label>Id Vivienda</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProcesosATC</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Inventario__c/fields/Condominio__c.field-meta.xml
<CustomField>
    <fullName>Condominio__c</fullName>
    <label>Condominio</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Inventarios</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Se llena con el valor del email de la cuenta asignada al ProcesoATC</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Entregada__c.field-meta.xml
<CustomField>
    <fullName>Entregada__c</fullName>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Por Entregar</fullName>
            </value>
            <value>
                <fullName>No Entregado</fullName>
            </value>
            <value>
                <fullName>Entregado</fullName>
            </value>
            <value>
                <fullName>Agendada</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Revisiones_en_Vivienda__c.field-meta.xml
<CustomField>
    <fullName>Revisiones_en_Vivienda__c</fullName>
    <label>¿Cuántas veces revisaste la vivienda?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <default>true</default>
                <label>0</label>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/SurveyInvitation/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Survey Invitations</relationshipLabel>
    <relationshipName>Survey_Invitations</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SurveyInvitation/fields/Proceso_ATC__c.field-meta.xml
<CustomField>
    <fullName>Proceso_ATC__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proceso ATC</label>
    <referenceTo>Inventario__c</referenceTo>
    <relationshipLabel>Invitaciones de encuestas</relationshipLabel>
    <relationshipName>Invitaciones_de_encuestas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SurveyResponse__c/SurveyResponse__c.object-meta.xml
<CustomObject>
    <label>Survey Response (ATC)</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Responses (ATC)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SurveyResponse__c/fields/Proceso_ATC__c.field-meta.xml
<CustomField>
    <fullName>Proceso_ATC__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proceso ATC</label>
    <referenceTo>Inventario__c</referenceTo>
    <relationshipLabel>Survey Responses (ATC)</relationshipLabel>
    <relationshipName>Survey_Responses_ATC</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SurveyResponse__c/fields/Survey_Invitation__c.field-meta.xml
<CustomField>
    <fullName>Survey_Invitation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Survey Invitation</label>
    <referenceTo>SurveyInvitation</referenceTo>
    <relationshipName>SurveyResponse_Mocks</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/globalValueSets/Canal_de_Venta.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>DIGITAL ASESOR</fullName>
    </customValue>
    <customValue>
        <fullName>EVENTO</fullName>
    </customValue>
    <customValue>
        <fullName>LLAMADA CALL CENTER</fullName>
    </customValue>
    <customValue>
        <fullName>MACROVENTA</fullName>
    </customValue>
    <customValue>
        <fullName>MACROVENTA 2015</fullName>
    </customValue>
    <customValue>
        <fullName>MEDIO PUBLICITARIO</fullName>
    </customValue>
    <customValue>
        <fullName>MEDIOS DIGITALES</fullName>
    </customValue>
    <customValue>
        <fullName>PROGRAMAS INSTITUCIONALES</fullName>
    </customValue>
    <customValue>
        <fullName>PROMOTOR EXTERNO</fullName>
    </customValue>
    <customValue>
        <fullName>PROSPECCION</fullName>
    </customValue>
    <customValue>
        <fullName>PROSPECTO ASESOR</fullName>
    </customValue>
    <customValue>
        <fullName>REFERIDOS</fullName>
    </customValue>
    <customValue>
        <fullName>VENTA EMPRESARIAL</fullName>
    </customValue>
    <customValue>
        <fullName>CARGA INICIAL</fullName>
    </customValue>
    <masterLabel>Canal de Venta</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Lugar_Nacimiento.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AGUASCALIENTES</fullName>
    </customValue>
    <customValue>
        <fullName>BAJA CALIFORNIA</fullName>
    </customValue>
    <customValue>
        <fullName>BAJA CALIFORNIA SUR</fullName>
    </customValue>
    <customValue>
        <fullName>CAMPECHE</fullName>
    </customValue>
    <customValue>
        <fullName>CHIAPAS</fullName>
    </customValue>
    <customValue>
        <fullName>CHIHUAHUA</fullName>
    </customValue>
    <customValue>
        <fullName>CIUDAD DE MEXICO</fullName>
    </customValue>
    <customValue>
        <fullName>COAHUILA</fullName>
    </customValue>
    <customValue>
        <fullName>COLIMA</fullName>
    </customValue>
    <customValue>
        <fullName>DURANGO</fullName>
    </customValue>
    <customValue>
        <fullName>ESTADO DE MEXICO</fullName>
    </customValue>
    <customValue>
        <fullName>EXTRANJERO</fullName>
    </customValue>
    <customValue>
        <fullName>GUANAJUATO</fullName>
    </customValue>
    <customValue>
        <fullName>GUERRERO</fullName>
    </customValue>
    <customValue>
        <fullName>HIDALGO</fullName>
    </customValue>
    <customValue>
        <fullName>JALISCO</fullName>
    </customValue>
    <customValue>
        <fullName>MICHOACAN</fullName>
    </customValue>
    <customValue>
        <fullName>MORELOS</fullName>
    </customValue>
    <customValue>
        <fullName>NAYARIT</fullName>
    </customValue>
    <customValue>
        <fullName>NUEVO LEON</fullName>
    </customValue>
    <customValue>
        <fullName>OAXACA</fullName>
    </customValue>
    <customValue>
        <fullName>PUEBLA</fullName>
    </customValue>
    <customValue>
        <fullName>QUERETARO</fullName>
    </customValue>
    <customValue>
        <fullName>QUINTANA ROO</fullName>
    </customValue>
    <customValue>
        <fullName>SAN LUIS POTOSI</fullName>
    </customValue>
    <customValue>
        <fullName>SINALOA</fullName>
    </customValue>
    <customValue>
        <fullName>SONORA</fullName>
    </customValue>
    <customValue>
        <fullName>TABASCO</fullName>
    </customValue>
    <customValue>
        <fullName>TAMAULIPAS</fullName>
    </customValue>
    <customValue>
        <fullName>TLAXCALA</fullName>
    </customValue>
    <masterLabel>Lugar de Nacimiento</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Nacionalidad.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>MEXICANA</fullName>
        <default>true</default>
        <label>MEXICANA</label>
    </customValue>
    <customValue>
        <fullName>ABJASIA</fullName>
    </customValue>
    <customValue>
        <fullName>ACROTIRENSE</fullName>
    </customValue>
    <customValue>
        <fullName>AFGANA</fullName>
    </customValue>
    <customValue>
        <fullName>ALBANESA</fullName>
    </customValue>
    <customValue>
        <fullName>ALEMANA</fullName>
    </customValue>
    <customValue>
        <fullName>ANDORRANA</fullName>
    </customValue>
    <customValue>
        <fullName>ANGOLEÑA</fullName>
    </customValue>
    <customValue>
        <fullName>ANGUILENSE</fullName>
    </customValue>
    <customValue>
        <fullName>ANTIGUANA</fullName>
    </customValue>
    <customValue>
        <fullName>ARGELINA</fullName>
    </customValue>
    <customValue>
        <fullName>ARGENTINA</fullName>
    </customValue>
    <customValue>
        <fullName>ARMENIA</fullName>
    </customValue>
    <customValue>
        <fullName>ARTSAJI</fullName>
    </customValue>
    <customValue>
        <fullName>ARUBEÑA</fullName>
    </customValue>
    <customValue>
        <fullName>AUSTRALIANA</fullName>
    </customValue>
    <customValue>
        <fullName>AUSTRIACA</fullName>
    </customValue>
    <customValue>
        <fullName>AZERBAIYANA</fullName>
    </customValue>
    <customValue>
        <fullName>BAHAMEÑA</fullName>
    </customValue>
    <customValue>
        <fullName>BANGLADESI</fullName>
    </customValue>
    <customValue>
        <fullName>BARBADENSE</fullName>
    </customValue>
    <customValue>
        <fullName>BAREINI</fullName>
    </customValue>
    <customValue>
        <fullName>BELGA</fullName>
    </customValue>
    <customValue>
        <fullName>BELICEÑA</fullName>
    </customValue>
    <customValue>
        <fullName>BENINESA</fullName>
    </customValue>
    <customValue>
        <fullName>BERMUDEÑA</fullName>
    </customValue>
    <customValue>
        <fullName>BIELORRUSA</fullName>
    </customValue>
    <customValue>
        <fullName>BIRMANA</fullName>
    </customValue>
    <customValue>
        <fullName>BOLIVIANA</fullName>
    </customValue>
    <customValue>
        <fullName>BOSNIA</fullName>
    </customValue>
    <masterLabel>Nacionalidad</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Sexo.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>MASCULINO</fullName>
    </customValue>
    <customValue>
        <fullName>FEMENINO</fullName>
    </customValue>
    <customValue>
        <fullName>NO BINARIO</fullName>
    </customValue>
    <masterLabel>Sexo</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Sub_canal_de_venta.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1-2GUPNA8</fullName>
    </customValue>
    <customValue>
        <fullName>ACTIVACION/EVENTO</fullName>
    </customValue>
    <customValue>
        <fullName>ACTIVACION/EVENTO/PERIFERIA</fullName>
    </customValue>
    <customValue>
        <fullName>AGS FERIA CANADEVI</fullName>
    </customValue>
    <customValue>
        <fullName>AGS MOCTEZUMA</fullName>
    </customValue>
    <customValue>
        <fullName>AGS SAN DIEGO</fullName>
    </customValue>
    <customValue>
        <fullName>AGS VILLA ASUNCION</fullName>
    </customValue>
    <customValue>
        <fullName>APP INVITADO</fullName>
    </customValue>
    <customValue>
        <fullName>BLOGGER/TANIA RENDON</fullName>
    </customValue>
    <customValue>
        <fullName>BUEN FIN</fullName>
    </customValue>
    <customValue>
        <fullName>CALL CENTER/TELEMARKETING</fullName>
    </customValue>
    <customValue>
        <fullName>CAMBACEO</fullName>
    </customValue>
    <customValue>
        <fullName>CARTELERA MOVIL</fullName>
    </customValue>
    <customValue>
        <fullName>CARTELERA PV</fullName>
    </customValue>
    <customValue>
        <fullName>CARTERA DE CLIENTES</fullName>
    </customValue>
    <customValue>
        <fullName>CARTERA PROPIA</fullName>
    </customValue>
    <customValue>
        <fullName>CITA ASESOR</fullName>
    </customValue>
    <customValue>
        <fullName>COLABORADOR JAVER</fullName>
    </customValue>
    <customValue>
        <fullName>COMPAÑERO DE TRABAJO</fullName>
    </customValue>
    <customValue>
        <fullName>CONVENIO PABELLON M</fullName>
    </customValue>
    <customValue>
        <fullName>CORREO</fullName>
    </customValue>
    <customValue>
        <fullName>CORREO DIRECTO/CARTA</fullName>
    </customValue>
    <customValue>
        <fullName>EDO MEX SAMARA</fullName>
    </customValue>
    <customValue>
        <fullName>EN EMPRESA (VENTA EMPRESARIAL)</fullName>
    </customValue>
    <customValue>
        <fullName>ESPECTACULAR/CARTELERA</fullName>
    </customValue>
    <customValue>
        <fullName>EVENTO (MACROVENTA, SUPERVTA)</fullName>
    </customValue>
    <customValue>
        <fullName>EXPO/FERIA</fullName>
    </customValue>
    <customValue>
        <fullName>FACEBOOK</fullName>
    </customValue>
    <customValue>
        <fullName>FACEBOOK INBOX</fullName>
    </customValue>
    <customValue>
        <fullName>FAMILIAR</fullName>
    </customValue>
    <customValue>
        <fullName>PROSPECTO ASESOR</fullName>
    </customValue>
    <masterLabel>Sub canal de venta</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/Test_Survey4.cls
@isTest
public class Test_Survey4 {
    static void setup() {
        
    }
    @isTest(SeeAllData=true)
    public static void testMigrate4(){
         Account acc = new Account(FirstName= 'Lopez', LastName= 'test', CorreoElectronico__c = 'test@prospects.com', Apellidomaterno_cta__c = 'dahuoh', PersonBirthdate=date.today().addyears(-20),Phone = '+528119928819',Otro_Telefono__c = '+528119928819',TelefonoCelular__c='+525530303030',Canal_de_Venta__c = 'PROSPECTO ASESOR', Estatus_Lista_Negra_QEQ__c = 'VALIDADO');
        Account acc1 = acc.clone(false, true, false, false);
        acc1.RecordTypeId =Schema.sObjectType.Account.getRecordTypeInfosBydevelopername().get('Prospecto_Persona_Fisica').getRecordTypeId();
        acc1.Canal_de_Venta__c = 'MEDIOS DIGITALES';
        acc1.Sub_canal_de_venta__c = '';
        acc1.Check_Apellido__c = true;
        acc1.Sexo__c = 'MASCULINO';
        acc1.Nacionalidad__c = 'MEXICANA';
        acc1.Lugar_Nacimiento__c = 'AGUASCALIENTES';
        acc1.CorreoElectronico__c = 'test@portal123453.com';
        acc1.Fecha_de_Afluencia__c = date.today().addDays(-1);
        acc1.BillingPostalCode = '123456';
        insert acc1;
        Inventario__c inventario = new Inventario__c(Condominio__c = 'Condominio', Entregada__c = 'Entregado', Cuenta__c = acc1.Id, Revisiones_en_Vivienda__c = '3');
        insert inventario;
        acc1.Apellidomaterno_cta__c = 'test';
        acc1.Aprobo_Check_Apellido__c  = false;
        acc1.Vivienda_Mas_Reciente__c = inventario.Id;
        update acc1; 
        Survey S1 = [Select Id from Survey where Name = 'Entrega vivienda' LIMIT 1];
        SurveyInvitation SI1 = new SurveyInvitation(Name = 'TEST', Email__c = 'test@Test.com', Proceso_ATC__c = inventario.Id, SurveyId = S1.Id);
        insert SI1;
        SurveyInvitation SI = [Select Id, Proceso_ATC__c from SurveyInvitation where SurveyId =: S1.Id LIMIT 1];// new SurveyInvitation(Name = 'TEST', Email__c = 'test@Test.com', Proceso_ATC__c = inventario.Id, SurveyId = S1.Id);
        //insert SI;
        Test.startTest();
        SurveyResponse SR = [Select Id from SurveyResponse LIMIT 1];
        SurveyResponse__c srCust = new SurveyResponse__c(Survey_Invitation__c = SI.id);
        insert srCust;
        Survey_Migration_Monthly_Fix EM = new Survey_Migration_Monthly_Fix();
        Id batchId = Database.executeBatch(EM,9);
        Test.stopTest();
    }
}