unpackaged/main/default/objects/Account/fields/Apellidomaterno_cta__c.field-meta.xml
<CustomField>
    <fullName>Apellidomaterno_cta__c</fullName>
    <label>Apellido Materno</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Canal_de_Venta__c.field-meta.xml
<CustomField>
    <fullName>Canal_de_Venta__c</fullName>
    <label>Canal de Venta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Canal_de_Venta</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Otro_Telefono__c.field-meta.xml
<CustomField>
    <fullName>Otro_Telefono__c</fullName>
    <label>Otro Teléfono</label>
    <type>Phone</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Prospecto.recordType-meta.xml
<RecordType>
    <fullName>Prospecto</fullName>
    <active>true</active>
    <label>Prospecto</label>
</RecordType>

unpackaged/main/default/objects/Colonia__c/Colonia__c.object-meta.xml
<CustomObject>
    <label>Colonia</label>
    <nameField>
        <label>Colonia</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Colonias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/WhatsApp__c/WhatsApp__c.object-meta.xml
<CustomObject>
    <label>Mensaje de WhatsApp</label>
    <nameField>
        <displayFormat>W-{0000}</displayFormat>
        <label>WhatsApp Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mensajes de WhatsApp</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/WhatsApp__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

unpackaged/main/default/objects/WhatsApp__c/fields/Prospect__c.field-meta.xml
<CustomField>
    <fullName>Prospect__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prospect</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>WhatsApp</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/globalValueSets/Canal_de_Venta.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>DIGITAL ASESOR</fullName>
    </customValue>
    <customValue>
        <fullName>EVENTO</fullName>
    </customValue>
    <customValue>
        <fullName>LLAMADA CALL CENTER</fullName>
    </customValue>
    <customValue>
        <fullName>MACROVENTA</fullName>
    </customValue>
    <customValue>
        <fullName>MACROVENTA 2015</fullName>
    </customValue>
    <customValue>
        <fullName>MEDIO PUBLICITARIO</fullName>
    </customValue>
    <customValue>
        <fullName>MEDIOS DIGITALES</fullName>
    </customValue>
    <customValue>
        <fullName>PROGRAMAS INSTITUCIONALES</fullName>
    </customValue>
    <customValue>
        <fullName>PROMOTOR EXTERNO</fullName>
    </customValue>
    <customValue>
        <fullName>PROSPECCION</fullName>
    </customValue>
    <customValue>
        <fullName>PROSPECTO ASESOR</fullName>
    </customValue>
    <customValue>
        <fullName>REFERIDOS</fullName>
    </customValue>
    <customValue>
        <fullName>VENTA EMPRESARIAL</fullName>
    </customValue>
    <customValue>
        <fullName>CARGA INICIAL</fullName>
    </customValue>
    <masterLabel>Canal de Venta</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/WhatsAppIntegration_Test.cls
@isTest
public class WhatsAppIntegration_Test {
@isTest
    public static void Test1() {
        Account A = new Account(Name = 'AccName',Apellidomaterno_cta__c = 'materno',Phone = '+528119928819',Otro_Telefono__c = '+528119928819',Canal_de_Venta__c = 'PROSPECTO ASESOR');
        insert A;
        contact con = new contact(LastName = 'Lname',AccountId = A.id, MobilePhone = '+525656565656');
        insert con;
        Colonia__c C = new Colonia__c();
        C.Name = 'test';
        insert C;
        WhatsApp__c W = new WhatsApp__c();
        W.Message__c = 'Hi';
        W.Prospect__c = a.id;
        insert W;
        Test.setMock(HttpCalloutMock.class, new MockHttpProspects());     
        Test.startTest();
        WhatsAppIntegration.sendSms(con.Id);
        Test.stopTest();
    }
}