unpackaged/main/default/objects/Account/fields/Apellidomaterno_cta__c.field-meta.xml
<CustomField>
    <fullName>Apellidomaterno_cta__c</fullName>
    <label>Apellido Materno</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Apellidopaterno_cta__c.field-meta.xml
<CustomField>
    <fullName>Apellidopaterno_cta__c</fullName>
    <label>Apellido Paterno</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/CorreoElectronico__c.field-meta.xml
<CustomField>
    <fullName>CorreoElectronico__c</fullName>
    <label>Correo Electrónico</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/isATC__c.field-meta.xml
<CustomField>
    <fullName>isATC__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isATC</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Nombre_cta__c.field-meta.xml
<CustomField>
    <fullName>Nombre_cta__c</fullName>
    <label>Nombre2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Notaria__c.field-meta.xml
<CustomField>
    <fullName>Notaria__c</fullName>
    <label>Notaría</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Notario__c.field-meta.xml
<CustomField>
    <fullName>Notario__c</fullName>
    <label>Notario</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Numerodecliente__c.field-meta.xml
<CustomField>
    <fullName>Numerodecliente__c</fullName>
    <label>Número de cliente</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/ProductoFinanciero__c.field-meta.xml
<CustomField>
    <fullName>ProductoFinanciero__c</fullName>
    <label>Producto Financiero</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/ReferenciaBancariaCliente__c.field-meta.xml
<CustomField>
    <fullName>ReferenciaBancariaCliente__c</fullName>
    <label>Referencia bancaria cliente</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/TipoCredito__c.field-meta.xml
<CustomField>
    <fullName>TipoCredito__c</fullName>
    <label>Tipo de crédito2</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BANCO - SOFOL</fullName>
            </value>
            <value>
                <fullName>BANJERCITO</fullName>
            </value>
            <value>
                <fullName>CAJA FLORENCIO ROSAS</fullName>
            </value>
            <value>
                <fullName>CONTADO</fullName>
            </value>
            <value>
                <fullName>CONTINGENCIA</fullName>
            </value>
            <value>
                <fullName>FOVISSSTE</fullName>
            </value>
            <value>
                <fullName>INFONAVIT</fullName>
            </value>
            <value>
                <fullName>ISSFAM</fullName>
            </value>
            <value>
                <fullName>ISSSTELEON</fullName>
            </value>
            <value>
                <fullName>SHF/BANCO</fullName>
            </value>
            <value>
                <fullName>PENSIONES</fullName>
            </value>
            <value>
                <fullName>COFINAVIT</fullName>
            </value>
            <value>
                <fullName>BANSEFI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Inventario__c/Inventario__c.object-meta.xml
<CustomObject>
    <label>Proceso ATC</label>
    <nameField>
        <label>Id Vivienda</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProcesosATC</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Inventario__c/fields/Condominio__c.field-meta.xml
<CustomField>
    <fullName>Condominio__c</fullName>
    <label>Condominio</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Inventarios</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Entregada__c.field-meta.xml
<CustomField>
    <fullName>Entregada__c</fullName>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Por Entregar</fullName>
            </value>
            <value>
                <fullName>No Entregado</fullName>
            </value>
            <value>
                <fullName>Entregado</fullName>
            </value>
            <value>
                <fullName>Agendada</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/FechadeHabitabilidad__c.field-meta.xml
<CustomField>
    <fullName>FechadeHabitabilidad__c</fullName>
    <label>Fecha de Habitabilidad</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/FechaHabitabilidad__c.field-meta.xml
<CustomField>
    <fullName>FechaHabitabilidad__c</fullName>
    <label>Fecha Habitabilidad</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Notaria__c.field-meta.xml
<CustomField>
    <fullName>Notaria__c</fullName>
    <label>Notaria</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Notario__c.field-meta.xml
<CustomField>
    <fullName>Notario__c</fullName>
    <label>Notario</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/PorcentajeCheckList__c.field-meta.xml
<CustomField>
    <fullName>PorcentajeCheckList__c</fullName>
    <label>Porcentaje Check List</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/ProductoFinanciero__c.field-meta.xml
<CustomField>
    <fullName>ProductoFinanciero__c</fullName>
    <label>Producto Financiero</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/ReferenciaBancariaCliente__c.field-meta.xml
<CustomField>
    <fullName>ReferenciaBancariaCliente__c</fullName>
    <label>Referencia Bancaria del cliente</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Revisiones_en_Vivienda__c.field-meta.xml
<CustomField>
    <fullName>Revisiones_en_Vivienda__c</fullName>
    <label>¿Cuántas veces revisaste la vivienda?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <default>true</default>
                <label>0</label>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/TipoCredito__c.field-meta.xml
<CustomField>
    <fullName>TipoCredito__c</fullName>
    <label>Tipo de crédito</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BANCO - SOFOL</fullName>
            </value>
            <value>
                <fullName>BANJERCITO</fullName>
            </value>
            <value>
                <fullName>CAJA FLORENCIO ROSAS</fullName>
            </value>
            <value>
                <fullName>CONTADO</fullName>
            </value>
            <value>
                <fullName>CONTINGENCIA</fullName>
            </value>
            <value>
                <fullName>FOVISSSTE</fullName>
            </value>
            <value>
                <fullName>INFONAVIT</fullName>
            </value>
            <value>
                <fullName>ISSFAM</fullName>
            </value>
            <value>
                <fullName>ISSSTELEON</fullName>
            </value>
            <value>
                <fullName>SHF/BANCO</fullName>
            </value>
            <value>
                <fullName>PENSIONES</fullName>
            </value>
            <value>
                <fullName>COFINAVIT</fullName>
            </value>
            <value>
                <fullName>BANSEFI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Notaria__c/Notaria__c.object-meta.xml
<CustomObject>
    <label>Notaría</label>
    <nameField>
        <label>Notaría</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notarías</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Notaria__c/fields/Notario__c.field-meta.xml
<CustomField>
    <fullName>Notario__c</fullName>
    <label>Notario</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/classes/GCPV_Test.cls
@isTest(SeeAllData=true)
public class GCPV_Test {
    static void setup() {
        Id rtATC = [SELECT Id FROM RecordType WHERE Name LIKE 'Clientes ATC%' AND IsPersonType=True LIMIT 1].ID;
        
        Account cuenta = new Account();
        cuenta.isATC__c = true;
        cuenta.Numerodecliente__c = 'AA';
        cuenta.Nombre_cta__c = 'PRUEBA';
        cuenta.Apellidopaterno_cta__c = 'PRUEBA';
        cuenta.Apellidomaterno_cta__c = 'PRUEBA';
        cuenta.ProductoFinanciero__c = 'PRUEBA';
        cuenta.TipoCredito__c = 'BANJERCITO';
        cuenta.CorreoElectronico__c = 'prueba@prueba.com';
        cuenta.Notaria__c = 'PRUEBA';
        cuenta.Notario__c = 'PRUEBA';
        cuenta.ReferenciaBancariaCliente__c = 'PRUEBA';
        cuenta.FirstName = 'PRUEBA';
        /*cuenta.MiddleName = 'PRUEBA';*/
        cuenta.LastName = 'PRUEBA';
        //cuenta.Name = cuenta.Nombre_cta__c + ' ' + cuenta.Apellidopaterno_cta__c + ' ' + cuenta.Apellidomaterno_cta__c;
        cuenta.RecordTypeId = rtATC;
        cuenta.Phone = '+8888888888';
        insert cuenta;
        
        Inventario__c inventario = new Inventario__c();
        inventario.Condominio__c = 'Condominio';
        inventario.Name = 'AABBCCDDEE-Prueba';
        inventario.Entregada__c = 'Por Entregar';
        inventario.FechaHabitabilidad__c = System.today().format();
        inventario.PorcentajeCheckList__c = 0;
        inventario.FechadeHabitabilidad__c = System.today();
        inventario.Cuenta__c = cuenta.Id;
        inventario.Revisiones_en_Vivienda__c = '3';
        insert inventario;
        
    }
    
    static testmethod void test() {        
        Test.startTest();
                        
        User adminJVR = [SELECT Id FROM User WHERE Name LIKE 'Admin J%' LIMIT 1];
        System.runAs(adminJVR) {
            Inventario__c inventario = [Select Id From Inventario__c Limit 1];
            
            Test.setMock(HttpCalloutMock.class, new GCPV_PagaresMock());
            GCPV_PagaresWS PWS = new GCPV_PagaresWS();
            GCPV_PagaresWS_Schedule EM = new GCPV_PagaresWS_Schedule();
            EM.execute(null);
           
            
            Test.stopTest();
            
             
            
            PageReference page = Page.CartaNoAdeudo;
            page.getParameters().put('id',inventario.Id);
            Test.setCurrentPageReference(page);
            CartaNoAdeudoController ctr = new CartaNoAdeudoController();
        }
    }
    
    static testmethod void testSR() {  
        GCPV_Recordatorios_Schedule RS = new GCPV_Recordatorios_Schedule();
        RS.execute(null);
    }
}