unpackaged/main/default/objects/Account/fields/Apellidomaterno_cta__c.field-meta.xml
<CustomField>
    <fullName>Apellidomaterno_cta__c</fullName>
    <label>Apellido Materno</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Asesor__c.field-meta.xml
<CustomField>
    <fullName>Asesor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asesor</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR 3</booleanFilter>
        <errorMessage>El usuario seleccionado no tiene asignado el fraccionamiento elegido.</errorMessage>
        <filterItems>
            <field>User.ProfileId</field>
            <operation>equals</operation>
            <value>00e23000000anFuAAI</value>
        </filterItems>
        <filterItems>
            <field>User.FraccionamientoAutorizados__c</field>
            <operation>contains</operation>
            <valueField>$Source.Nombre_Fraccionamiento__c</valueField>
        </filterItems>
        <filterItems>
            <field>User.ProfileId</field>
            <operation>equals</operation>
            <value>00e23000000anG0AAI</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Canal_de_Venta__c.field-meta.xml
<CustomField>
    <fullName>Canal_de_Venta__c</fullName>
    <label>Canal de Venta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Canal_de_Venta</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Colonia_cta__c.field-meta.xml
<CustomField>
    <fullName>Colonia_cta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Colonia</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Colonia__c.Municipio__c</field>
            <operation>equals</operation>
            <valueField>$Source.Municipiocta__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Colonia__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/CorreoElectronico__c.field-meta.xml
<CustomField>
    <fullName>CorreoElectronico__c</fullName>
    <label>Correo Electrónico</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/DependientesEconomicos__c.field-meta.xml
<CustomField>
    <fullName>DependientesEconomicos__c</fullName>
    <inlineHelpText>Número</inlineHelpText>
    <label>Dependientes económicos</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Empresa__c.field-meta.xml
<CustomField>
    <fullName>Empresa__c</fullName>
    <label>Empresa</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Estatus__c.field-meta.xml
<CustomField>
    <fullName>Estatus__c</fullName>
    <description>Campos informativo, viaja a través de la interfaz, si es una cuenta nueva por default “Por Asignar”</description>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Por Asignar</fullName>
            </value>
            <value>
                <fullName>Asignado</fullName>
            </value>
            <value>
                <fullName>Por Reasignar</fullName>
            </value>
            <value>
                <fullName>Baja</fullName>
            </value>
            <value>
                <fullName>Incubadora</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/FechaAsignacion__c.field-meta.xml
<CustomField>
    <fullName>FechaAsignacion__c</fullName>
    <label>Fecha de asignación</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/FechaNacimiento__c.field-meta.xml
<CustomField>
    <fullName>FechaNacimiento__c</fullName>
    <label>Fecha de Nacimiento</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/FechaProspeccion__c.field-meta.xml
<CustomField>
    <fullName>FechaProspeccion__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <description>Fecha que se registra</description>
    <label>Fecha de Prospección 1</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Fraccionamiento_cta__c.field-meta.xml
<CustomField>
    <fullName>Fraccionamiento_cta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fraccionamiento</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>(1 OR 5 OR 2 OR 4 OR 6) AND 3</booleanFilter>
        <filterItems>
            <field>$User.Fraccionamiento_autorizado__c</field>
            <operation>contains</operation>
            <valueField>Fraccionamiento__c.Name</valueField>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>Administrador del sistema</value>
        </filterItems>
        <filterItems>
            <field>Fraccionamiento__c.Activo_frac__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$User.Fraccionamiento_autorizado__c</field>
            <operation>equals</operation>
            <value>TODOS</value>
        </filterItems>
        <filterItems>
            <field>$User.FraccionamientoAutorizados__c</field>
            <operation>contains</operation>
            <valueField>Fraccionamiento__c.Name</valueField>
        </filterItems>
        <filterItems>
            <field>$User.Fraccionamiento_autorizado__c</field>
            <operation>contains</operation>
            <valueField>Fraccionamiento__c.Name</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Fraccionamiento__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Hijos__c.field-meta.xml
<CustomField>
    <fullName>Hijos__c</fullName>
    <inlineHelpText>Número</inlineHelpText>
    <label>Hijos</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Id_Colaborador_Javer__c.field-meta.xml
<CustomField>
    <fullName>Id_Colaborador_Javer__c</fullName>
    <label>Id Colaborador Javer</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/IdMasComercial__c.field-meta.xml
<CustomField>
    <fullName>IdMasComercial__c</fullName>
    <label>IdMasComercial</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Ingresos_Mensuales__c.field-meta.xml
<CustomField>
    <fullName>Ingresos_Mensuales__c</fullName>
    <label>Ingresos Mensuales</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Ingresos_Mensuales</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Meses__c.field-meta.xml
<CustomField>
    <fullName>Meses__c</fullName>
    <inlineHelpText>Número</inlineHelpText>
    <label>Meses</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Nombre_Ase__c.field-meta.xml
<CustomField>
    <fullName>Nombre_Ase__c</fullName>
    <label>Nombre_Ase</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Nombre_Colaborador_Javer__c.field-meta.xml
<CustomField>
    <fullName>Nombre_Colaborador_Javer__c</fullName>
    <label>Nombre Colaborador Javer</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Nombre_Pro__c.field-meta.xml
<CustomField>
    <fullName>Nombre_Pro__c</fullName>
    <label>Nombre_Pro</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/NSS__c.field-meta.xml
<CustomField>
    <fullName>NSS__c</fullName>
    <inlineHelpText>Obligatorio en Crédito Infonavit o Cofinavit</inlineHelpText>
    <label>NSS</label>
    <length>11</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Account/fields/Origen__c.field-meta.xml
<CustomField>
    <fullName>Origen__c</fullName>
    <label>Origen</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Origen</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Prospectador__c.field-meta.xml
<CustomField>
    <fullName>Prospectador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prospectador</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR 3</booleanFilter>
        <filterItems>
            <field>User.ProfileId</field>
            <operation>equals</operation>
            <value>00e23000000anG7AAI</value>
        </filterItems>
        <filterItems>
            <field>User.FraccionamientoAutorizados__c</field>
            <operation>contains</operation>
            <valueField>$Source.Nombre_Fraccionamiento__c</valueField>
        </filterItems>
        <filterItems>
            <field>User.ProfileId</field>
            <operation>equals</operation>
            <value>00e23000000anG0AAI</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Cuentas1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Puesto__c.field-meta.xml
<CustomField>
    <fullName>Puesto__c</fullName>
    <label>Puesto</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Sexo__c.field-meta.xml
<CustomField>
    <fullName>Sexo__c</fullName>
    <label>Sexo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sexo</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Sub_canal_de_venta__c.field-meta.xml
<CustomField>
    <fullName>Sub_canal_de_venta__c</fullName>
    <label>Sub canal de venta</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Canal_de_Venta__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Sub_canal_de_venta</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/TelefonoCelular__c.field-meta.xml
<CustomField>
    <fullName>TelefonoCelular__c</fullName>
    <label>Teléfono Celular</label>
    <type>Phone</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/TelefonoOtro__c.field-meta.xml
<CustomField>
    <fullName>TelefonoOtro__c</fullName>
    <label>Teléfono Otro</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/ClientesATC.recordType-meta.xml
<RecordType>
    <fullName>ClientesATC</fullName>
    <active>false</active>
    <label>Clientes ATC</label>
</RecordType>

unpackaged/main/default/objects/Account/recordTypes/Prospecto.recordType-meta.xml
<RecordType>
    <fullName>Prospecto</fullName>
    <active>true</active>
    <label>Prospecto</label>
</RecordType>

unpackaged/main/default/objects/Fraccionamiento__c/Fraccionamiento__c.object-meta.xml
<CustomObject>
    <label>Fraccionamiento</label>
    <nameField>
        <label>Nombre de Fraccionamiento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fraccionamientos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Fraccionamiento__c/fields/Prototipo__c.field-meta.xml
<CustomField>
    <fullName>Prototipo__c</fullName>
    <label>Prototipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prototipo 1</fullName>
            </value>
            <value>
                <fullName>Prototipo 2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Fraccionamiento__c/fields/Todo__c.field-meta.xml
<CustomField>
    <fullName>Todo__c</fullName>
    <externalId>true</externalId>
    <label>Todo</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Prototipo__c/Prototipo__c.object-meta.xml
<CustomObject>
    <label>Prototipo</label>
    <nameField>
        <label>Prototipo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prototipos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Prototipo__c/fields/Activo_pro__c.field-meta.xml
<CustomField>
    <fullName>Activo_pro__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Prototipo__c/fields/Fraccionamiento__c.field-meta.xml
<CustomField>
    <fullName>Fraccionamiento__c</fullName>
    <label>Fraccionamiento</label>
    <referenceTo>Fraccionamiento__c</referenceTo>
    <relationshipLabel>Prototipos</relationshipLabel>
    <relationshipName>Prototipos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Prototipo__c/fields/Precio_Presupuesto__c.field-meta.xml
<CustomField>
    <fullName>Precio_Presupuesto__c</fullName>
    <label>Precio Presupuesto</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Prototipo__c/fields/Precio_pro__c.field-meta.xml
<CustomField>
    <fullName>Precio_pro__c</fullName>
    <label>Precio</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Prototipo__c/fields/Prototipo_pro__c.field-meta.xml
<CustomField>
    <fullName>Prototipo_pro__c</fullName>
    <label>Campo Control</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Prototipo__c/fields/Todo__c.field-meta.xml
<CustomField>
    <fullName>Todo__c</fullName>
    <defaultValue>&#39;TODO&#39;</defaultValue>
    <externalId>true</externalId>
    <label>Todo</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Prototipo__c/fields/Version_Precio_Presupuesto__c.field-meta.xml
<CustomField>
    <fullName>Version_Precio_Presupuesto__c</fullName>
    <label>Versión Precio Presupuesto</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Oficial Firmada</fullName>
            </value>
            <value>
                <fullName>Working</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/Canal_de_Venta.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>DIGITAL ASESOR</fullName>
    </customValue>
    <customValue>
        <fullName>EVENTO</fullName>
    </customValue>
    <customValue>
        <fullName>LLAMADA CALL CENTER</fullName>
    </customValue>
    <customValue>
        <fullName>MACROVENTA</fullName>
    </customValue>
    <customValue>
        <fullName>MACROVENTA 2015</fullName>
    </customValue>
    <customValue>
        <fullName>MEDIO PUBLICITARIO</fullName>
    </customValue>
    <customValue>
        <fullName>MEDIOS DIGITALES</fullName>
    </customValue>
    <customValue>
        <fullName>PROGRAMAS INSTITUCIONALES</fullName>
    </customValue>
    <customValue>
        <fullName>PROMOTOR EXTERNO</fullName>
    </customValue>
    <customValue>
        <fullName>PROSPECCION</fullName>
    </customValue>
    <customValue>
        <fullName>PROSPECTO ASESOR</fullName>
    </customValue>
    <customValue>
        <fullName>REFERIDOS</fullName>
    </customValue>
    <customValue>
        <fullName>VENTA EMPRESARIAL</fullName>
    </customValue>
    <customValue>
        <fullName>CARGA INICIAL</fullName>
    </customValue>
    <masterLabel>Canal de Venta</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Ingresos_Mensuales.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>0 - 3,999</fullName>
    </customValue>
    <customValue>
        <fullName>4,000 - 7,999</fullName>
    </customValue>
    <customValue>
        <fullName>8,000 - 12,999</fullName>
    </customValue>
    <customValue>
        <fullName>13,000 - 15,999</fullName>
    </customValue>
    <customValue>
        <fullName>16,000 - 19,999</fullName>
    </customValue>
    <customValue>
        <fullName>20,000 - 24,999</fullName>
    </customValue>
    <customValue>
        <fullName>25,000 - 34,999</fullName>
    </customValue>
    <customValue>
        <fullName>35,000 - 44,999</fullName>
    </customValue>
    <customValue>
        <fullName>45,000 - 54,999</fullName>
    </customValue>
    <customValue>
        <fullName>55,000 - 64,999</fullName>
    </customValue>
    <customValue>
        <fullName>65,000 - 74,999</fullName>
    </customValue>
    <customValue>
        <fullName>75,000 - MAS</fullName>
    </customValue>
    <masterLabel>Ingresos Mensuales</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Origen.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CONTACTO JAVER</fullName>
    </customValue>
    <customValue>
        <fullName>Enfoque Comercial</fullName>
        <default>true</default>
        <label>ENFOQUE COMERCIAL</label>
    </customValue>
    <customValue>
        <fullName>SALES CLOUD</fullName>
    </customValue>
    <customValue>
        <fullName>PROSPECTO ASESOR</fullName>
    </customValue>
    <customValue>
        <fullName>MERCADOTECNIA</fullName>
    </customValue>
    <customValue>
        <fullName>AFLUENCIA</fullName>
    </customValue>
    <customValue>
        <fullName>COLABORADOR JAVER</fullName>
    </customValue>
    <customValue>
        <fullName>CONTACTO TELEFONICO</fullName>
    </customValue>
    <customValue>
        <fullName>PROSPECCION</fullName>
    </customValue>
    <customValue>
        <fullName>SMS</fullName>
    </customValue>
    <customValue>
        <fullName>Enlace</fullName>
        <label>ENLACE</label>
    </customValue>
    <masterLabel>Origen</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Sexo.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>MASCULINO</fullName>
    </customValue>
    <customValue>
        <fullName>FEMENINO</fullName>
    </customValue>
    <customValue>
        <fullName>NO BINARIO</fullName>
    </customValue>
    <masterLabel>Sexo</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Sub_canal_de_venta.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1-2GUPNA8</fullName>
    </customValue>
    <customValue>
        <fullName>ACTIVACION/EVENTO</fullName>
    </customValue>
    <customValue>
        <fullName>ACTIVACION/EVENTO/PERIFERIA</fullName>
    </customValue>
    <customValue>
        <fullName>AGS FERIA CANADEVI</fullName>
    </customValue>
    <customValue>
        <fullName>AGS MOCTEZUMA</fullName>
    </customValue>
    <customValue>
        <fullName>AGS SAN DIEGO</fullName>
    </customValue>
    <customValue>
        <fullName>AGS VILLA ASUNCION</fullName>
    </customValue>
    <customValue>
        <fullName>APP INVITADO</fullName>
    </customValue>
    <customValue>
        <fullName>BLOGGER/TANIA RENDON</fullName>
    </customValue>
    <customValue>
        <fullName>BUEN FIN</fullName>
    </customValue>
    <customValue>
        <fullName>CALL CENTER/TELEMARKETING</fullName>
    </customValue>
    <customValue>
        <fullName>CAMBACEO</fullName>
    </customValue>
    <customValue>
        <fullName>CARTELERA MOVIL</fullName>
    </customValue>
    <customValue>
        <fullName>CARTELERA PV</fullName>
    </customValue>
    <customValue>
        <fullName>CARTERA DE CLIENTES</fullName>
    </customValue>
    <customValue>
        <fullName>CARTERA PROPIA</fullName>
    </customValue>
    <customValue>
        <fullName>CITA ASESOR</fullName>
    </customValue>
    <customValue>
        <fullName>COLABORADOR JAVER</fullName>
    </customValue>
    <customValue>
        <fullName>COMPAÑERO DE TRABAJO</fullName>
    </customValue>
    <customValue>
        <fullName>CONVENIO PABELLON M</fullName>
    </customValue>
    <customValue>
        <fullName>CORREO</fullName>
    </customValue>
    <customValue>
        <fullName>CORREO DIRECTO/CARTA</fullName>
    </customValue>
    <customValue>
        <fullName>EDO MEX SAMARA</fullName>
    </customValue>
    <customValue>
        <fullName>EN EMPRESA (VENTA EMPRESARIAL)</fullName>
    </customValue>
    <customValue>
        <fullName>ESPECTACULAR/CARTELERA</fullName>
    </customValue>
    <customValue>
        <fullName>EVENTO (MACROVENTA, SUPERVTA)</fullName>
    </customValue>
    <customValue>
        <fullName>EXPO/FERIA</fullName>
    </customValue>
    <customValue>
        <fullName>FACEBOOK</fullName>
    </customValue>
    <customValue>
        <fullName>FACEBOOK INBOX</fullName>
    </customValue>
    <customValue>
        <fullName>FAMILIAR</fullName>
    </customValue>
    <customValue>
        <fullName>PROSPECTO ASESOR</fullName>
    </customValue>
    <masterLabel>Sub canal de venta</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/GuardarMasComercialQbApx_Test.cls
@isTest (seealldata=true)
public class GuardarMasComercialQbApx_Test {

    @isTest
    static void testQueueable1() {
        // Fraccionamiento__c f = new Fraccionamiento__c(name = 'ACACIAS');
        // insert f;
        Fraccionamiento__c[] f = [SELECT Id, Name FROM Fraccionamiento__c where Name='ACACIAS' LIMIT 1];
        list<Account> AccList = new list<Account>();
        Prototipo__c proto = new Prototipo__c(Name='TAMARINDO', Activo_pro__c=true, Fraccionamiento__c=f[0].Id, Precio_pro__c=2500000, Prototipo_pro__c='TAMARINDO - ACACIAS', Precio_Presupuesto__c=1850000.00, Version_Precio_Presupuesto__c='Working', Todo__c='TODO');
        insert proto;
        UserRole portalRole = [Select Id From UserRole Where PortalType = 'None' Limit 1];
        String usrJaverGenerico = Label.JAVER_GENERICO_User;
        List<User> usr = [Select Id,UserRoleId, Profile.Name from User where id = :usrJaverGenerico  LIMIT 1];

        // Create test accounts
        // List<Account> testAccounts = [SELECT Id, Apellidomaterno_cta__c, Asesor__c, Canal_de_Venta__c, Colonia_cta__c, CorreoElectronico__c, DependientesEconomicos__c, 
        //     Empresa__c, Estado_Civil__c, Estatus__c, FechaAsignacion__c, FechaNacimiento__c, FechaProspeccion__c, FirstName, Fraccionamiento_cta__c, Hijos__c, 
        //     IdMasComercial__c, Id_Colaborador_Javer__c, Ingresos_Mensuales__c, LastName, Meses__c, NSS__c, Nombre_Ase__c, Nombre_Colaborador_Javer__c, Nombre_pro__c, 
        //     Origen__c, Phone, Prospectador__c, Puesto__c, RecordTypeId, Sexo__c, Sub_canal_de_venta__c, TelefonoCelular__c, TelefonoOtro__c, TelefonoRecados__c, 
        //     TelefonoTrabajo__c, Tipo_Credito__c, anios__c
        //     FROM Account order by createddate DESC LIMIT 1];

        Account acc = new Account(FirstName= 'Lopez', LastName= 'test', CorreoElectronico__c = 'test@prospects.com', Apellidomaterno_cta__c = 'dahuoh', PersonBirthdate=date.today().addyears(-20),Phone = '+528119928819',Otro_Telefono__c = '+528119928819',TelefonoCelular__c='+525530303030',Canal_de_Venta__c = 'PROSPECTO ASESOR', Estatus_Lista_Negra_QEQ__c = 'VALIDADO');
        Account acc1 = acc.clone(false, true, false, false);
        acc1.RecordTypeId =Schema.sObjectType.Account.getRecordTypeInfosBydevelopername().get('Prospecto_Persona_Fisica').getRecordTypeId();
        acc1.Canal_de_Venta__c = 'MEDIOS DIGITALES';
        acc1.Sub_canal_de_venta__c = '';
        acc1.Check_Apellido__c = true;
        acc1.Nombre_Fraccionamiento__c='ACACIAS';
        acc1.Sexo__c = 'MASCULINO';
        acc1.Nacionalidad__c = 'MEXICANA';
        acc1.Lugar_Nacimiento__c = 'AGUASCALIENTES';
        acc1.CorreoElectronico__c = 'test@portal123453.com';
        acc1.Fecha_de_Afluencia__c = date.today().addDays(-1);
        acc1.BillingPostalCode = '123456';
        acc1.Fraccionamiento_cta__c = f[0].id;
        acc1.Prototipo_lookup__c = proto.id;
        acc1.Aprobo_Check_Apellido__c = false;
        acc1.Apellidomaterno_cta__c = 'dahuoh';
        //acc1.Lead_Profiler__c = UserInfo.getUserId();
        acc1.Prospectador__c = UserInfo.getUserId();
        acc1.Asesor__c =usr[0].Id;
        acc1.ValidationBypassDateTime__c=datetime.now();
        //insert acc1;

        Account acc3 = new Account(FirstName= 'JOSEtest', LastName= 'PEREZtest', CorreoElectronico__c = 'test2@prospects.com', Apellidomaterno_cta__c = 'LOPEZtest', PersonBirthdate=date.today().addyears(-21),Phone = '+528119928820',Otro_Telefono__c = '+528119928821',TelefonoCelular__c='+525530303031',Canal_de_Venta__c = 'PROSPECTO ASESOR', Estatus_Lista_Negra_QEQ__c = 'VALIDADO');
        Account acc2 = acc3.clone(false, true, false, false);
        acc2.RecordTypeId =Schema.sObjectType.Account.getRecordTypeInfosBydevelopername().get('ClientesATC').getRecordTypeId();
        acc2.Canal_de_Venta__c = 'MEDIOS DIGITALES';
        acc2.Sub_canal_de_venta__c = '';
        acc2.Check_Apellido__c = true;
        acc2.Nombre_Fraccionamiento__c='ACACIAS';
        acc2.Sexo__c = 'MASCULINO';
        acc2.Nacionalidad__c = 'MEXICANA';
        acc2.Lugar_Nacimiento__c = 'AGUASCALIENTES';
        acc2.Fecha_de_Afluencia__c = date.today().addDays(-1);
        acc2.BillingPostalCode = '123456';
        acc2.Fraccionamiento_cta__c = f[0].id;
        acc2.Prototipo_lookup__c = proto.id;
        acc2.Aprobo_Check_Apellido__c = false;
        //acc2.Lead_Profiler__c = UserInfo.getUserId();
        acc2.Prospectador__c = UserInfo.getUserId();
        acc2.Asesor__c =usr[0].Id;
        acc2.ValidationBypassDateTime__c=datetime.now();

        List <Account> testAccounts = new List <Account>();
        testAccounts.add(acc1);
        //testAccounts.add(acc2);
        insert testAccounts;

        Test.startTest();

        // Enqueue the Queueable class
        System.enqueueJob(new GuardarMasComercialQbApx(testAccounts));

        // Wait for the Queueable job to complete
        Test.stopTest();

    }
    @isTest
    static void testQueueable2() {
		/*
        Fraccionamiento__c f = new Fraccionamiento__c(name = 'ACACIAS');
        insert f;
        list<Account> AccList = new list<Account>();
        Prototipo__c proto = new Prototipo__c(Name='TAMARINDO', Activo_pro__c=true, Fraccionamiento__c=f.Id, Precio_pro__c=2500000, Prototipo_pro__c='TAMARINDO - BOSQUE REAL', Precio_Presupuesto__c=1850000.00, Version_Precio_Presupuesto__c='Working', Todo__c='TODO');
        insert proto;
        UserRole portalRole = [Select Id From UserRole Where PortalType = 'None' Limit 1];
        List<User> usr = [Select Id,UserRoleId, Profile.Name from User where UserRoleId=:portalRole.Id OR Profile.Name  = 'Asesor'  LIMIT 1];

        Account acc = new Account(FirstName= 'testF', LastName= 'testL', MiddleName='testM', Name='testF testM testL', CorreoElectronico__c = 'test@prospects.com', PersonBirthdate=date.today().addyears(-20),Phone = '+528119928819',Otro_Telefono__c = '+528119928819',TelefonoCelular__c='+525530303030',Canal_de_Venta__c = 'PROSPECTO ASESOR', Estatus_Lista_Negra_QEQ__c = 'VALIDADO');
        Account acc1 = acc.clone(false, true, false, false);
        acc1.RecordTypeId = Schema.sObjectType.Account.getRecordTypeInfosBydevelopername().get('ClientesATC').getRecordTypeId();
        acc1.Canal_de_Venta__c = 'MEDIOS DIGITALES';
        acc1.Sub_canal_de_venta__c = '';
        acc1.Check_Apellido__c = true;
        acc1.Nombre_Fraccionamiento__c='ACACIAS';
        acc1.Sexo__c = 'MASCULINO';
        acc1.Nacionalidad__c = 'MEXICANA';
        acc1.Lugar_Nacimiento__c = 'AGUASCALIENTES';
        acc1.CorreoElectronico__c = 'test@portal123453.com';
        acc1.Fecha_de_Afluencia__c = date.today().addDays(-1);
        acc1.BillingPostalCode = '123456';
        acc1.Fraccionamiento_cta__c = f.id;
        acc1.Prototipo_lookup__c = proto.id;
        acc1.Aprobo_Check_Apellido__c = false;
        //acc1.Apellidomaterno_cta__c = 'dahuoh';
        //acc1.Lead_Profiler__c = UserInfo.getUserId();
        acc1.Prospectador__c = UserInfo.getUserId();
        acc1.Asesor__c =usr[0].Id;
        acc1.ValidationBypassDateTime__c=datetime.now();

        List <Account> testAccounts = new List <Account>();
        testAccounts.add(acc1);
        insert testAccounts;
		*/
        Id rtId = Schema.sObjectType.Account.getRecordTypeInfosBydevelopername().get('PersonAccount').getRecordTypeId();
        
        List<Account> testAccounts = [SELECT Id, Apellidomaterno_cta__c, Asesor__c, Canal_de_Venta__c, Colonia_cta__c, CorreoElectronico__c, DependientesEconomicos__c, 
            Empresa__c, Estado_Civil__c, Estatus__c, FechaAsignacion__c, FechaNacimiento__c, FechaProspeccion__c, FirstName, Fraccionamiento_cta__c, Hijos__c, 
            IdMasComercial__c, Id_Colaborador_Javer__c, Ingresos_Mensuales__c, LastName, Meses__c, NSS__c, Nombre_Ase__c, Nombre_Colaborador_Javer__c, Nombre_pro__c, 
            Origen__c, Phone, Prospectador__c, Puesto__c, RecordTypeId, Sexo__c, Sub_canal_de_venta__c, TelefonoCelular__c, TelefonoOtro__c, TelefonoRecados__c, 
            TelefonoTrabajo__c, Tipo_Credito__c, anios__c
            FROM Account
            WHERE RecordTypeId = :rtId order by createddate DESC LIMIT 1];
        Test.startTest();

        // Enqueue the Queueable class
        System.enqueueJob(new GuardarMasComercialQbApx(testAccounts));

        // Wait for the Queueable job to complete
        Test.stopTest();

    }
    @isTest
    static void testQueueable3() {
        list<account> acc = new list<account>();
		GuardarMasComercialQbApx guardartest = new GuardarMasComercialQbApx(acc);
        guardartest.codeCoverage();
    }
}