unpackaged/main/default/objects/Account/fields/Apellidomaterno_cta__c.field-meta.xml
<CustomField>
    <fullName>Apellidomaterno_cta__c</fullName>
    <label>Apellido Materno</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Asesor__c.field-meta.xml
<CustomField>
    <fullName>Asesor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asesor</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR 3</booleanFilter>
        <errorMessage>El usuario seleccionado no tiene asignado el fraccionamiento elegido.</errorMessage>
        <filterItems>
            <field>User.ProfileId</field>
            <operation>equals</operation>
            <value>00e23000000anFuAAI</value>
        </filterItems>
        <filterItems>
            <field>User.FraccionamientoAutorizados__c</field>
            <operation>contains</operation>
            <valueField>$Source.Nombre_Fraccionamiento__c</valueField>
        </filterItems>
        <filterItems>
            <field>User.ProfileId</field>
            <operation>equals</operation>
            <value>00e23000000anG0AAI</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Canal_de_Venta__c.field-meta.xml
<CustomField>
    <fullName>Canal_de_Venta__c</fullName>
    <label>Canal de Venta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Canal_de_Venta</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Fraccionamiento_cta__c.field-meta.xml
<CustomField>
    <fullName>Fraccionamiento_cta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fraccionamiento</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>(1 OR 5 OR 2 OR 4 OR 6) AND 3</booleanFilter>
        <filterItems>
            <field>$User.Fraccionamiento_autorizado__c</field>
            <operation>contains</operation>
            <valueField>Fraccionamiento__c.Name</valueField>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>Administrador del sistema</value>
        </filterItems>
        <filterItems>
            <field>Fraccionamiento__c.Activo_frac__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$User.Fraccionamiento_autorizado__c</field>
            <operation>equals</operation>
            <value>TODOS</value>
        </filterItems>
        <filterItems>
            <field>$User.FraccionamientoAutorizados__c</field>
            <operation>contains</operation>
            <valueField>Fraccionamiento__c.Name</valueField>
        </filterItems>
        <filterItems>
            <field>$User.Fraccionamiento_autorizado__c</field>
            <operation>contains</operation>
            <valueField>Fraccionamiento__c.Name</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Fraccionamiento__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Otro_Telefono__c.field-meta.xml
<CustomField>
    <fullName>Otro_Telefono__c</fullName>
    <label>Otro Teléfono</label>
    <type>Phone</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Company_Javer.recordType-meta.xml
<RecordType>
    <fullName>Company_Javer</fullName>
    <active>true</active>
    <label>COMPAÑÍA JAVER</label>
</RecordType>

unpackaged/main/default/objects/Account/recordTypes/Prospecto.recordType-meta.xml
<RecordType>
    <fullName>Prospecto</fullName>
    <active>true</active>
    <label>Prospecto</label>
</RecordType>

unpackaged/main/default/objects/Contact/fields/Asesor__c.field-meta.xml
<CustomField>
    <fullName>Asesor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asesor 1</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Asesor</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Fraccionamiento__c/Fraccionamiento__c.object-meta.xml
<CustomObject>
    <label>Fraccionamiento</label>
    <nameField>
        <label>Nombre de Fraccionamiento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fraccionamientos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Historial_Asignacion__c/Historial_Asignacion__c.object-meta.xml
<CustomObject>
    <label>Historial de Asignación</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Folio</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Historial de Asignaciones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Historial_Asignacion__c/fields/Asesor__c.field-meta.xml
<CustomField>
    <fullName>Asesor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asesor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Historial_de_Asignaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Historial_Asignacion__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Historico_de_Asignaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Historial_Asignacion__c/fields/Fraccionamiento__c.field-meta.xml
<CustomField>
    <fullName>Fraccionamiento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fraccionamiento</label>
    <referenceTo>Fraccionamiento__c</referenceTo>
    <relationshipLabel>Historial de Asignaciones</relationshipLabel>
    <relationshipName>Historial_de_Asignaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/User/fields/Fraccionamiento_autorizado__c.field-meta.xml
<CustomField>
    <fullName>Fraccionamiento_autorizado__c</fullName>
    <inlineHelpText>Al poner la Palabra TODOS 
lo que dará acceso a cualquier fracc.</inlineHelpText>
    <label>Fraccionamiento autorizado</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/User/fields/FraccionamientoAutorizados__c.field-meta.xml
<CustomField>
    <fullName>FraccionamientoAutorizados__c</fullName>
    <label>Fraccionamiento Autorizados</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/User/fields/FRACCIONAMIENTOS__c.field-meta.xml
<CustomField>
    <fullName>FRACCIONAMIENTOS__c</fullName>
    <label>FRACCIONAMIENTOS</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ACACIAS</fullName>
            </value>
            <value>
                <fullName>ACACIAS II</fullName>
            </value>
            <value>
                <fullName>ALBERI RESIDENCIAL</fullName>
            </value>
            <value>
                <fullName>ALVENTO</fullName>
            </value>
            <value>
                <fullName>ARBOLADA</fullName>
            </value>
            <value>
                <fullName>BOSQUE REAL</fullName>
            </value>
            <value>
                <fullName>BOSQUES DEL NEVADO</fullName>
            </value>
            <value>
                <fullName>MAGNOLIAS IV</fullName>
            </value>
            <value>
                <fullName>MISION DE LOS ANGELES 1ER SECTOR ARCANGELES</fullName>
            </value>
            <value>
                <fullName>MURIEL RESIDENCIAL</fullName>
            </value>
            <value>
                <fullName>PASEO SAN JUNIPERO</fullName>
            </value>
            <value>
                <fullName>PASEOS DEL SUR</fullName>
            </value>
            <value>
                <fullName>PRIVADA BELTERRA</fullName>
            </value>
            <value>
                <fullName>PRIVADAS CARANDAY</fullName>
            </value>
            <value>
                <fullName>PRIVALIA AMBIENTA</fullName>
            </value>
            <value>
                <fullName>TODOS</fullName>
            </value>
            <value>
                <fullName>VALLE DE LINCOLN SECTOR MINAS</fullName>
            </value>
            <value>
                <fullName>VALLE DE SANTA ELENA</fullName>
            </value>
            <value>
                <fullName>VALLE DE TEJEDA II</fullName>
            </value>
            <value>
                <fullName>VALLE SANTA ISABEL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/Canal_de_Venta.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>DIGITAL ASESOR</fullName>
    </customValue>
    <customValue>
        <fullName>EVENTO</fullName>
    </customValue>
    <customValue>
        <fullName>LLAMADA CALL CENTER</fullName>
    </customValue>
    <customValue>
        <fullName>MACROVENTA</fullName>
    </customValue>
    <customValue>
        <fullName>MACROVENTA 2015</fullName>
    </customValue>
    <customValue>
        <fullName>MEDIO PUBLICITARIO</fullName>
    </customValue>
    <customValue>
        <fullName>MEDIOS DIGITALES</fullName>
    </customValue>
    <customValue>
        <fullName>PROGRAMAS INSTITUCIONALES</fullName>
    </customValue>
    <customValue>
        <fullName>PROMOTOR EXTERNO</fullName>
    </customValue>
    <customValue>
        <fullName>PROSPECCION</fullName>
    </customValue>
    <customValue>
        <fullName>PROSPECTO ASESOR</fullName>
    </customValue>
    <customValue>
        <fullName>REFERIDOS</fullName>
    </customValue>
    <customValue>
        <fullName>VENTA EMPRESARIAL</fullName>
    </customValue>
    <customValue>
        <fullName>CARGA INICIAL</fullName>
    </customValue>
    <masterLabel>Canal de Venta</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/userInfoClass_test.cls
@isTest
public class userInfoClass_test {
    @testSetup static void setup() {
        Fraccionamiento__c f = new Fraccionamiento__c(Name = 'ACACIAS II');
        insert f;
        Account ac = new Account();
        ac.name= 'test';
        ac.Phone = '+528119928819';
        ac.Otro_Telefono__c = '+528119928819'; 
        ac.Apellidomaterno_cta__c = 'materno';
        ac.Canal_de_Venta__c = 'PROSPECTO ASESOR';
        ac.Fraccionamiento_cta__c = f.id; 
        insert ac;
        contact c = new contact(LastName = 'testCon', accountId= ac.id);
        insert c;  
    }
    static TestMethod void Test1() {
        Date fromDate= Date.newInstance(2023, 3, 14); Date EndDate = Date.newInstance(2023, 3, 15);
        Test.startTest();
        userInfoClass.userInfoMethod();
        userInfoClass.NeighMethod();
        userInfoClass.filterAccounts('Todos' , 'Prospecto',fromdate, enddate, 'This Week',true);
        userInfoClass.filterAccounts('ACACIAS' , 'Prospecto',fromdate, enddate, 'Last Week',false);
        userInfoClass.filterAccounts('ACACIAS' , 'Prospecto',fromdate, enddate, 'This Month',true);
        userInfoClass.filterAccounts('ACACIAS' , 'Prospecto',fromdate, enddate, 'Last Month',true);
        userInfoClass.filterAccounts('ACACIAS' , 'Prospecto',fromdate, enddate, 'Older',true);
        userInfoClass.searchDivision('DIVISION');
        userInfoClass.searchDivision('');
        Test.stopTest();
    }
    static TestMethod void Test2() {
        Test.startTest();
        UserRole userrole = [Select Id, DeveloperName From UserRole Where PortalType= 'None' Limit 1];
        Id profileId = [SELECT Id FROM Profile WHERE Name = 'JAVER - Generico' LIMIT 1].Id;
        system.debug('profileId='+profileId);
        User user = new User(alias = 'test123', email='test123@noemail.com',
                             emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US',UserroleId = userrole.id,
                             localesidkey='en_US', profileid = profileId, country='United States',IsActive =true,
                             timezonesidkey='America/Los_Angeles', username='testUserInfo@email.com',FRACCIONAMIENTOS__c = 'ACACIAS;ACACIAS II',
                             FraccionamientoAutorizados__c = 'ACACIAS');
        insert user;
        System.runAs(user) {
            Fraccionamiento__c f = new Fraccionamiento__c(Name = 'ACACIAS II');
            insert f;
            Account ac = new Account();
            ac.name= 'test';
            ac.RecordTypeId =Schema.sObjectType.Account.getRecordTypeInfosBydevelopername().get('Company_Javer').getRecordTypeId();
            ac.Phone = '+528119928819';
            ac.Otro_Telefono__c = '+528119928819'; 
            ac.Apellidomaterno_cta__c = 'materno';
            ac.Canal_de_Venta__c = 'PROSPECTO ASESOR';
            ac.Fraccionamiento_cta__c = f.id; 
            insert ac;
            
            Historial_Asignacion__c h = new  Historial_Asignacion__c();
            h.Fraccionamiento__c = f.id;
            h.Asesor__c = user.id;
            h.Cuenta__c= ac.id;
            insert h; 
            userInfoClass.updateMethod(ac.Id, 'ACACIAS II');
            userInfoClass.logoutFromSite();
            userInfoClass.updateFA(ac.Id,'ACACIAS II');
            userInfoClass.updateFA(ac.Id,'');
            Boolean exceptionThrown = false;
            try  {
               userInfoClass.updateOwner(ac.Id);               
            }
            catch(Exception e) {
                exceptionThrown = true;
            }   
        }
        Test.stopTest();
    }
    static TestMethod void Test3() {
        Test.startTest();
        Date fromDate= Date.newInstance(2023, 3, 14); Date EndDate = Date.newInstance(2023, 3, 15);        
        Id profileId = [SELECT Id FROM Profile WHERE Name = 'JAVER - Generico' LIMIT 1].Id;
        Contact con  = [Select Id, Name from contact where LastName = 'testCon'];
        UserRole userrole = [Select Id From UserRole Where PortalType = 'None' Limit 1];
        User user = new User(alias = 'test123', email='test123@noemail.com',
                             emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US',UserroleId = userrole.id,
                             localesidkey='en_US', profileid = profileId, country='United States',IsActive =true,
                             timezonesidkey='America/Los_Angeles', username='testUserInfo@email.com',FRACCIONAMIENTOS__c = 'ACACIAS;BOSQUES DEL NEVADO',
                             Fraccionamiento_autorizado__c = 'ACACIAS', FraccionamientoAutorizados__c = 'ACACIAS');
        insert user;
        System.runAs(user){
            Fraccionamiento__c f = new Fraccionamiento__c(Name = 'ACACIAS II');
            insert f;
            Account ac = new Account();
            ac.RecordTypeId =Schema.sObjectType.Account.getRecordTypeInfosBydevelopername().get('Company_Javer').getRecordTypeId();
            ac.name= 'test';
            ac.Phone = '+528119928819';
            ac.Otro_Telefono__c = '+528119928819'; 
            ac.Apellidomaterno_cta__c = 'materno';
            ac.Canal_de_Venta__c = 'PROSPECTO ASESOR';
            ac.Fraccionamiento_cta__c = f.id; 
            insert ac;
            
            userInfoClass.logoutFromSite();
            Boolean exceptionThrown = false;
            try  {
                userInfoClass.updateOwner(ac.Id);               
            }
            catch(Exception e) {
                exceptionThrown = true;
            } 
            try {
                userInfoClass.filterAccounts('Todos' , 'Prospecto',fromdate, enddate, 'This Week',true);
                userInfoClass.updateMethod(ac.Id, 'ACACIAS II');               
            }
            catch(exception e) {}   
        }
        Test.stopTest();
    }
    static TestMethod void TestupdateMethod_Prospectador() {
        
        Date fromDate= Date.newInstance(2023, 3, 14); Date EndDate = Date.newInstance(2023, 3, 15);
        Id profileId = [SELECT Id FROM Profile WHERE Name = 'Prospectador' LIMIT 1].Id;
        Contact con  = [Select Id, Name from contact where LastName = 'testCon'];
        UserRole userrole = [Select Id From UserRole Where PortalType = 'None' Limit 1];
        User user = new User(alias = 'test123', email='test123@noemail.com',
                             emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US',UserRoleId = userrole.Id,
                             localesidkey='en_US', profileid = profileId, country='United States',IsActive =true,ContactId =con.id,
                             timezonesidkey='America/Los_Angeles', username='testUserInfo@email.com',FRACCIONAMIENTOS__c = 'ACACIAS;BOSQUES DEL NEVADO',
                             Fraccionamiento_autorizado__c = 'ACACIAS', FraccionamientoAutorizados__c = 'ACACIAS');
        insert user;
        Test.startTest();
        System.runAs(user){
            try {
                Account ac = [Select id, Name from Account Where name = 'test' LIMIT 1];
                userInfoClass.filterAccounts('Todos' , 'Prospecto',fromdate, enddate, 'This Week',true);
                userInfoClass.updateMethod(ac.Id, 'ACACIAS II');                            
            }
            catch(exception e) {}   
        }
        Test.stopTest();
    }
    static TestMethod void TestNeighMethod_Prospectador() {
        
        
        Date fromDate= Date.newInstance(2023, 3, 14); Date EndDate = Date.newInstance(2023, 3, 15);
        userInfoClass.filterAccounts('Todos' , 'Prospecto',fromdate, enddate, 'This Week',true);
        Id profileId = [SELECT Id FROM Profile WHERE Name = 'Prospectador' LIMIT 1].Id;
        UserRole userrole = [Select Id From UserRole Where PortalType = 'None' Limit 1];
        Contact con  = [Select Id, Name from contact where LastName = 'testCon'];
        User user = new User(alias = 'test123', email='test123@noemail.com',
                             emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US',UserRoleId = userrole.Id,
                             localesidkey='en_US', profileid = profileId, country='United States',IsActive =true,ContactId =con.id,
                             timezonesidkey='America/Los_Angeles', username='testUserInfo@email.com',FRACCIONAMIENTOS__c = 'ACACIAS;BOSQUES DEL NEVADO',
                             Fraccionamiento_autorizado__c = 'ACACIAS', FraccionamientoAutorizados__c = 'ACACIAS');
        insert user;
        Test.startTest();
        System.runAs(user){
            try  { 
                Fraccionamiento__c f = new Fraccionamiento__c(Name = 'ACACIAS II');
                insert f;
                Account ac = new Account();
                ac.name= 'test';
                ac.Phone = '+528119928819';
                ac.Otro_Telefono__c = '+528119928819'; 
                ac.Apellidomaterno_cta__c = 'materno';
                ac.Canal_de_Venta__c = 'PROSPECTO ASESOR';
                ac.Fraccionamiento_cta__c = f.id; 
                insert ac;
                userInfoClass.NeighMethod();                
            }
            catch(exception e) {}   
        }
        Test.stopTest();
    }
    static TestMethod void TestNeighMethod_Asesor() {
        
        
        Date fromDate= Date.newInstance(2023, 3, 14); Date EndDate = Date.newInstance(2023, 3, 15);
        userInfoClass.filterAccounts('Todos' , 'Prospecto',fromdate, enddate, 'This Week',true);
        Id profileId = [SELECT Id FROM Profile WHERE Name = 'Asesor' LIMIT 1].Id;
        UserRole userrole = [Select Id From UserRole Where PortalType = 'None' Limit 1];
        Contact con  = [Select Id, Name from contact where LastName = 'testCon'];
        User user = new User(alias = 'test123', email='test123@noemail.com',
                             emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US',UserRoleId = userrole.Id,
                             localesidkey='en_US', profileid = profileId, country='United States',IsActive =true,ContactId =con.id,
                             timezonesidkey='America/Los_Angeles', username='testUserInfo@email.com',FRACCIONAMIENTOS__c = 'ACACIAS;BOSQUES DEL NEVADO',
                             Fraccionamiento_autorizado__c = 'ACACIAS', FraccionamientoAutorizados__c = 'ACACIAS');
        insert user;
        Test.startTest();
        System.runAs(user){
            try  { 
                Fraccionamiento__c f = new Fraccionamiento__c(Name = 'ACACIAS II');
                insert f;
                Account ac = new Account();
                ac.name= 'test';
                ac.Phone = '+528119928819';
                ac.Otro_Telefono__c = '+528119928819'; 
                ac.Apellidomaterno_cta__c = 'materno';
                ac.Canal_de_Venta__c = 'PROSPECTO ASESOR';
                ac.Fraccionamiento_cta__c = f.id; 
                insert ac;
                userInfoClass.NeighMethod();                
            }
            catch(exception e) {}   
        }
        Test.stopTest();
    }
}