unpackaged/main/default/objects/Account/fields/Apellidomaterno_cta__c.field-meta.xml
<CustomField>
    <fullName>Apellidomaterno_cta__c</fullName>
    <label>Apellido Materno</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Canal_de_Venta__c.field-meta.xml
<CustomField>
    <fullName>Canal_de_Venta__c</fullName>
    <label>Canal de Venta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Canal_de_Venta</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/CorreoElectronico__c.field-meta.xml
<CustomField>
    <fullName>CorreoElectronico__c</fullName>
    <label>Correo Electrónico</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Empresa__c.field-meta.xml
<CustomField>
    <fullName>Empresa__c</fullName>
    <label>Empresa</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Estatus_Lista_Negra_QEQ__c.field-meta.xml
<CustomField>
    <fullName>Estatus_Lista_Negra_QEQ__c</fullName>
    <label>Estatus Lista Negra</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SIN VALIDAR</fullName>
                <default>true</default>
                <label>SIN VALIDAR</label>
            </value>
            <value>
                <fullName>LISTA NEGRA</fullName>
            </value>
            <value>
                <fullName>LN CONFIRMADO</fullName>
            </value>
            <value>
                <fullName>VALIDADO</fullName>
            </value>
            <value>
                <fullName>PPE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Notaria__c.field-meta.xml
<CustomField>
    <fullName>Notaria__c</fullName>
    <label>Notaría</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Otro_Telefono__c.field-meta.xml
<CustomField>
    <fullName>Otro_Telefono__c</fullName>
    <label>Otro Teléfono</label>
    <type>Phone</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/TelefonoCelular__c.field-meta.xml
<CustomField>
    <fullName>TelefonoCelular__c</fullName>
    <label>Teléfono Celular</label>
    <type>Phone</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo de Cuenta</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospecto</fullName>
            </value>
            <value>
                <fullName>Afluente</fullName>
            </value>
            <value>
                <fullName>Cliente</fullName>
            </value>
            <value>
                <fullName>Compañía Javer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Prospecto.recordType-meta.xml
<RecordType>
    <fullName>Prospecto</fullName>
    <active>true</active>
    <label>Prospecto</label>
</RecordType>

unpackaged/main/default/objects/Contract/fields/Canal_de_venta__c.field-meta.xml
<CustomField>
    <fullName>Canal_de_venta__c</fullName>
    <label>Canal de venta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>DIGITAL ASESOR</fullName>
            </value>
            <value>
                <fullName>EVENTO</fullName>
            </value>
            <value>
                <fullName>LLAMADA CALL CENTER</fullName>
            </value>
            <value>
                <fullName>MACROVENTA</fullName>
            </value>
            <value>
                <fullName>MEDIO PUBLICITARIO</fullName>
            </value>
            <value>
                <fullName>MEDIOS DIGITALES</fullName>
            </value>
            <value>
                <fullName>PROGRAMAS INSTITUCIONALES</fullName>
            </value>
            <value>
                <fullName>PROMOTOR EXTERNO</fullName>
            </value>
            <value>
                <fullName>PROSPECCION</fullName>
            </value>
            <value>
                <fullName>PROSPECTO ASESOR</fullName>
            </value>
            <value>
                <fullName>REFERIDOS</fullName>
            </value>
            <value>
                <fullName>VENTA EMPRESARIAL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contract/fields/Empresa__c.field-meta.xml
<CustomField>
    <fullName>Empresa__c</fullName>
    <label>Empresa</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contract/fields/Es_usted_el_Titular_de_Recursos__c.field-meta.xml
<CustomField>
    <fullName>Es_usted_el_Titular_de_Recursos__c</fullName>
    <label>¿Es usted el Titular de Recursos?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SI</fullName>
            </value>
            <value>
                <fullName>NO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contract/fields/Escritura_a_favor_de_un_Tercero__c.field-meta.xml
<CustomField>
    <fullName>Escritura_a_favor_de_un_Tercero__c</fullName>
    <description>Cesión Vivienda</description>
    <label>¿Escritura a favor de un Tercero?</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Firma_Directa_Cliente__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SI</fullName>
            </value>
            <value>
                <fullName>NO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contract/fields/Existe_un_Tercero_que_aporta_Recursos__c.field-meta.xml
<CustomField>
    <fullName>Existe_un_Tercero_que_aporta_Recursos__c</fullName>
    <description>¿Existe un Tercero que aporta Recursos Total o Parcial?</description>
    <label>¿Existe un Tercero que aporta Recursos?</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Es_usted_el_Titular_de_Recursos__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SI</fullName>
            </value>
            <value>
                <fullName>NO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contract/fields/Fecha_de_Constituci_n__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_Constituci_n__c</fullName>
    <label>Fecha de Constitución</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Contract/fields/No_Escritura__c.field-meta.xml
<CustomField>
    <fullName>No_Escritura__c</fullName>
    <label>No. Escritura</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contract/fields/Notaria__c.field-meta.xml
<CustomField>
    <fullName>Notaria__c</fullName>
    <label>Notaría</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contract/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proceso de Venta</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Dictaminación</relationshipLabel>
    <relationshipName>Dictaminacion</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contract/fields/Otro_telefono__c.field-meta.xml
<CustomField>
    <fullName>Otro_telefono__c</fullName>
    <formula>Account.Otro_Telefono__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Otro teléfono</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contract/fields/RFC_Compania__c.field-meta.xml
<CustomField>
    <fullName>RFC_Compania__c</fullName>
    <label>RFC Compañía</label>
    <length>13</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contract/fields/TelefonoCelular__c.field-meta.xml
<CustomField>
    <fullName>TelefonoCelular__c</fullName>
    <formula>Account.TelefonoCelular__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Teléfono Celular</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Direcciones__c/Direcciones__c.object-meta.xml
<CustomObject>
    <label>Dirección</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Folio</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Direcciones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Direcciones__c/fields/Contrato__c.field-meta.xml
<CustomField>
    <fullName>Contrato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contrato</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Direcciones</relationshipLabel>
    <relationshipName>Direcciones</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Direcciones__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Dirección Afluencia</fullName>
            </value>
            <value>
                <fullName>Dirección Principal</fullName>
            </value>
            <value>
                <fullName>Dirección Laboral</fullName>
            </value>
            <value>
                <fullName>Dirección Empresa</fullName>
            </value>
            <value>
                <fullName>Dirección Principal CO Acreditado</fullName>
            </value>
            <value>
                <fullName>Dirección Laboral CO Acreditado</fullName>
            </value>
            <value>
                <fullName>Dirección Rep Legal Laboral</fullName>
            </value>
            <value>
                <fullName>Dirección Rep Legal / Apoderado</fullName>
            </value>
            <value>
                <fullName>Dirección Tercero Persona Física</fullName>
            </value>
            <value>
                <fullName>Dirección Tercero Laboral Persona Física</fullName>
            </value>
            <value>
                <fullName>Direccion_3ro_Moral_Principal</fullName>
                <label>Dirección 3ro Moral Principal</label>
            </value>
            <value>
                <fullName>Direccion_3ro_Domicilio_Moral</fullName>
                <label>Dirección 3ro Domicilio Moral</label>
            </value>
            <value>
                <fullName>Direccion_3ro_Laboral_Moral</fullName>
                <label>Dirección 3ro Laboral Moral</label>
            </value>
            <value>
                <fullName>Dirección Cesión Principal PF</fullName>
            </value>
            <value>
                <fullName>Dirección Cesión Laboral PF</fullName>
            </value>
            <value>
                <fullName>Dirección Cesión Principal PM</fullName>
            </value>
            <value>
                <fullName>Dirección Cesión Laboral PM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Canal_de_venta__c.field-meta.xml
<CustomField>
    <fullName>Canal_de_venta__c</fullName>
    <label>Canal de venta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Canal_de_Venta</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/TelefonoCelular__c.field-meta.xml
<CustomField>
    <fullName>TelefonoCelular__c</fullName>
    <formula>Account.TelefonoCelular__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Teléfono Celular</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/Plan_de_Venta__c.object-meta.xml
<CustomObject>
    <label>Plan de Venta</label>
    <nameField>
        <displayFormat>Plan de Venta-{000000}</displayFormat>
        <label>Plan de Venta</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plan de Venta</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proceso de Venta</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Plan de Venta</relationshipLabel>
    <relationshipName>Plan_de_Venta</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Referencia_familiar__c/Referencia_familiar__c.object-meta.xml
<CustomObject>
    <label>Referencia Familiar</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Folio</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referencias Familiares</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Referencia_familiar__c/fields/Contrato__c.field-meta.xml
<CustomField>
    <fullName>Contrato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contrato</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Referencias Familiares</relationshipLabel>
    <relationshipName>Referencias_Familiares</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/globalValueSets/Canal_de_Venta.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>DIGITAL ASESOR</fullName>
    </customValue>
    <customValue>
        <fullName>EVENTO</fullName>
    </customValue>
    <customValue>
        <fullName>LLAMADA CALL CENTER</fullName>
    </customValue>
    <customValue>
        <fullName>MACROVENTA</fullName>
    </customValue>
    <customValue>
        <fullName>MACROVENTA 2015</fullName>
    </customValue>
    <customValue>
        <fullName>MEDIO PUBLICITARIO</fullName>
    </customValue>
    <customValue>
        <fullName>MEDIOS DIGITALES</fullName>
    </customValue>
    <customValue>
        <fullName>PROGRAMAS INSTITUCIONALES</fullName>
    </customValue>
    <customValue>
        <fullName>PROMOTOR EXTERNO</fullName>
    </customValue>
    <customValue>
        <fullName>PROSPECCION</fullName>
    </customValue>
    <customValue>
        <fullName>PROSPECTO ASESOR</fullName>
    </customValue>
    <customValue>
        <fullName>REFERIDOS</fullName>
    </customValue>
    <customValue>
        <fullName>VENTA EMPRESARIAL</fullName>
    </customValue>
    <customValue>
        <fullName>CARGA INICIAL</fullName>
    </customValue>
    <masterLabel>Canal de Venta</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/TRIGGER_PlanDeVenta_Handler_Test.cls
@isTest
public with sharing class TRIGGER_PlanDeVenta_Handler_Test {
    
    @isTest
    static void testPagarePreventaSemanal(){
        List<Contract> contracts = new List<Contract>();
        Account acc = new Account();
        acc.FirstName= 'Lopez';
        acc.LastName= 'test';
        acc.RecordTypeId =Schema.sObjectType.Account.getRecordTypeInfosBydevelopername().get('Prospecto_Persona_Fisica').getRecordTypeId();
        acc.CorreoElectronico__c = 'test@prospects.com';
        acc.Apellidomaterno_cta__c = 'dahuoh';
        acc.PersonBirthdate=date.today().addyears(-20);
        acc.Phone = '+528119928819';
        acc.Otro_Telefono__c = '+528119928819';
        acc.TelefonoCelular__c='+525530303030'; 
        acc.Canal_de_Venta__c = 'PROSPECTO ASESOR';
        acc.Estatus_Lista_Negra_QEQ__c = 'VALIDADO';
        insert acc;
        opportunity opp = new opportunity();
        opp.Name = 'Test';
        opp.StageName = 'Reservado';
        opp.CloseDate = Date.today().adddays(10);
        insert opp;
        for (Integer i = 0; i < 5; i++) {
            contracts.add(new Contract
                          (Name = 'Test Contract ' + i, AccountId = acc.Id, Oportunidad__c = opp.id, Empresa__c = 'test', RFC_Compania__c = 'test'
                           ,Fecha_de_Constituci_n__c = system.today(),No_Escritura__c = 'test',Notaria__c = 'test'
                           /*  Escritura_a_favor_de_un_Tercero__c = 'SI',  Es_usted_el_Titular_de_Recursos__c = 'NO',Existe_un_Tercero_que_aporta_Recursos__c = 'SI' */));
        }
        
        insert contracts;
        List<Direcciones__c> addresses = new List<Direcciones__c>();
        for (Contract contract : contracts) {
            addresses.add(new Direcciones__c(Contrato__c = contract.Id, Tipo__c = 'Dirección Principal'));
        }
        insert addresses;
        List<Referencia_familiar__c> references = new List<Referencia_familiar__c>();
        for (Integer i = 0; i < 3; i++) {
            Referencia_familiar__c reference = new Referencia_familiar__c();
            reference.Contrato__c = contracts[0].Id;
            reference.Apellido_Paterno__c = 'test';
            reference.Apellido_Materno__c = 'Test';
            reference.Telefono_1__c = '+525530303030';
            reference.Telefono_2__c = '+528119928819'; 
            references.add(reference);
        }
        
        Plan_de_Venta__c pdv = New Plan_de_Venta__c();
        pdv.Plazo__c = 10;
        pdv.Frecuencia__c = 'Mensual';
        pdv.Modificacion_Automatica__c = 10;
        pdv.Estatus_Plan_de_venta__c = 'En Progreso';
        pdv.Oportunidad__c = opp.Id;
        pdv.Fecha_de_Vencimiento__c = system.today().addDays(1);
        pdv.Fecha_de_Inicio_de_Cobranza__c = system.today();
        insert pdv;
        Pagare_Preventa__c pagares = new Pagare_Preventa__c();
        pagares.Plan_de_Venta__c = pdv.id;
        pagares.Fecha_de_Vencimiento__c = system.today().addDays(1);
        insert pagares;
        pdv.Plazo__c = 4;
        pdv.Frecuencia__c = 'Semanal';
        pdv.Fecha_de_Vencimiento__c =  system.today().addDays(10);
        pdv.Fecha_de_Inicio_de_Cobranza__c = system.today();
        pdv.Modificacion_Automatica__c = 10;
        Test.startTest(); 
        Boolean exceptionThrown = false;
        try {
            update pdv; 
        } 
        catch (Exception e) {
            exceptionThrown = true;
            Boolean expectedExceptionThrown =  (e.getMessage().contains('No')) ? true : false; 
            System.AssertEquals(true, expectedExceptionThrown, e.getMessage()); 
        }   
        test.stopTest();
    }
    
}