unpackaged/main/default/objects/Account/fields/Apellidomaterno_cta__c.field-meta.xml
<CustomField>
    <fullName>Apellidomaterno_cta__c</fullName>
    <label>Apellido Materno</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Canal_de_Venta__c.field-meta.xml
<CustomField>
    <fullName>Canal_de_Venta__c</fullName>
    <label>Canal de Venta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Canal_de_Venta</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Otro_Telefono__c.field-meta.xml
<CustomField>
    <fullName>Otro_Telefono__c</fullName>
    <label>Otro Teléfono</label>
    <type>Phone</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Prospecto.recordType-meta.xml
<RecordType>
    <fullName>Prospecto</fullName>
    <active>true</active>
    <label>Prospecto</label>
</RecordType>

unpackaged/main/default/objects/Privacy_Notice__c/Privacy_Notice__c.object-meta.xml
<CustomObject>
    <label>Privacy Notice</label>
    <nameField>
        <displayFormat>PN{0}</displayFormat>
        <label>Privacy Notice No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Privacy Notices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Privacy_Notice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compañía</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>contains</operation>
            <value>COMPAÑÍA</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Privacy Notices</relationshipLabel>
    <relationshipName>Privacy_Notices</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Privacy_Notice__c/fields/Notice_Text__c.field-meta.xml
<CustomField>
    <fullName>Notice_Text__c</fullName>
    <label>Notice Text</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

unpackaged/main/default/objects/Privacy_Notice__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aviso de Inicio</fullName>
            </value>
            <value>
                <fullName>Aviso de Empresa</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/Canal_de_Venta.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>DIGITAL ASESOR</fullName>
    </customValue>
    <customValue>
        <fullName>EVENTO</fullName>
    </customValue>
    <customValue>
        <fullName>LLAMADA CALL CENTER</fullName>
    </customValue>
    <customValue>
        <fullName>MACROVENTA</fullName>
    </customValue>
    <customValue>
        <fullName>MACROVENTA 2015</fullName>
    </customValue>
    <customValue>
        <fullName>MEDIO PUBLICITARIO</fullName>
    </customValue>
    <customValue>
        <fullName>MEDIOS DIGITALES</fullName>
    </customValue>
    <customValue>
        <fullName>PROGRAMAS INSTITUCIONALES</fullName>
    </customValue>
    <customValue>
        <fullName>PROMOTOR EXTERNO</fullName>
    </customValue>
    <customValue>
        <fullName>PROSPECCION</fullName>
    </customValue>
    <customValue>
        <fullName>PROSPECTO ASESOR</fullName>
    </customValue>
    <customValue>
        <fullName>REFERIDOS</fullName>
    </customValue>
    <customValue>
        <fullName>VENTA EMPRESARIAL</fullName>
    </customValue>
    <customValue>
        <fullName>CARGA INICIAL</fullName>
    </customValue>
    <masterLabel>Canal de Venta</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/Privacy_Notice_Trigger_Test.cls
@isTest
public class Privacy_Notice_Trigger_Test {
    static TestMethod void Test1() {
        Id accRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('COMPAÑÍA JAVER').getRecordTypeId();
        Account acc = new Account();
        acc.name= 'COMPAÑÍA';
        acc.RecordtypeId= accRecordTypeId;
        acc.Phone = '+528119928819';
        acc.Otro_Telefono__c = '+528119928819'; 
        acc.Apellidomaterno_cta__c = 'materno';
        acc.Canal_de_Venta__c = 'PROSPECTO ASESOR';
        insert acc;
        Privacy_Notice__c pn = new  Privacy_Notice__c();
        pn.Account__c = acc.Id;
        pn.Active__c = true;
        pn.Notice_Text__c = 'test ||TODAY||';
        pn.Type__c = 'Aviso de Inicio';
        insert pn;
        pn.Active__c = false;
        update pn;
    }
    static TestMethod void Test2() {
        Id accRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('COMPAÑÍA JAVER').getRecordTypeId();
        Account acc = new Account();
        acc.RecordtypeId= accRecordTypeId;
        acc.name= 'COMPAÑÍA';
        acc.Phone = '+528119928819';
        acc.Otro_Telefono__c = '+528119928819'; 
        acc.Apellidomaterno_cta__c = 'materno';
        acc.Canal_de_Venta__c = 'PROSPECTO ASESOR';
        insert acc;
        Privacy_Notice__c pn = new  Privacy_Notice__c();
        pn.Account__c = acc.Id;
        pn.Active__c = true;
        pn.Notice_Text__c = 'test ||TODAY||';
        pn.Type__c = 'Aviso de Empresa';
        insert pn;
         Privacy_Notice__c pn1 = new  Privacy_Notice__c();
        pn1.Account__c = acc.Id;
        pn1.Active__c = true;
        pn1.Notice_Text__c = 'test ||TODAY||';
        pn1.Type__c = 'Aviso de Empresa';
        insert pn1;
        update pn;
    }
}