unpackaged/main/default/objects/Account/fields/Apellidomaterno_cta__c.field-meta.xml
<CustomField>
    <fullName>Apellidomaterno_cta__c</fullName>
    <label>Apellido Materno</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Apellidopaterno_cta__c.field-meta.xml
<CustomField>
    <fullName>Apellidopaterno_cta__c</fullName>
    <label>Apellido Paterno</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/CorreoElectronico__c.field-meta.xml
<CustomField>
    <fullName>CorreoElectronico__c</fullName>
    <label>Correo Electrónico</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/FechaNacimiento__c.field-meta.xml
<CustomField>
    <fullName>FechaNacimiento__c</fullName>
    <label>Fecha de Nacimiento</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/IdMasComercial__c.field-meta.xml
<CustomField>
    <fullName>IdMasComercial__c</fullName>
    <label>IdMasComercial</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/isATC__c.field-meta.xml
<CustomField>
    <fullName>isATC__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isATC</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Nombre_cta__c.field-meta.xml
<CustomField>
    <fullName>Nombre_cta__c</fullName>
    <label>Nombre2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Notaria__c.field-meta.xml
<CustomField>
    <fullName>Notaria__c</fullName>
    <label>Notaría</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Notario__c.field-meta.xml
<CustomField>
    <fullName>Notario__c</fullName>
    <label>Notario</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Numerodecliente__c.field-meta.xml
<CustomField>
    <fullName>Numerodecliente__c</fullName>
    <label>Número de cliente</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/ProductoFinanciero__c.field-meta.xml
<CustomField>
    <fullName>ProductoFinanciero__c</fullName>
    <label>Producto Financiero</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/ReferenciaBancariaCliente__c.field-meta.xml
<CustomField>
    <fullName>ReferenciaBancariaCliente__c</fullName>
    <label>Referencia bancaria cliente</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Telefono2__c.field-meta.xml
<CustomField>
    <fullName>Telefono2__c</fullName>
    <label>Teléfono 2</label>
    <type>Phone</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/TelefonoCelular__c.field-meta.xml
<CustomField>
    <fullName>TelefonoCelular__c</fullName>
    <label>Teléfono Celular</label>
    <type>Phone</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/TelefonoOtro__c.field-meta.xml
<CustomField>
    <fullName>TelefonoOtro__c</fullName>
    <label>Teléfono Otro</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/TipoCredito__c.field-meta.xml
<CustomField>
    <fullName>TipoCredito__c</fullName>
    <label>Tipo de crédito2</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BANCO - SOFOL</fullName>
            </value>
            <value>
                <fullName>BANJERCITO</fullName>
            </value>
            <value>
                <fullName>CAJA FLORENCIO ROSAS</fullName>
            </value>
            <value>
                <fullName>CONTADO</fullName>
            </value>
            <value>
                <fullName>CONTINGENCIA</fullName>
            </value>
            <value>
                <fullName>FOVISSSTE</fullName>
            </value>
            <value>
                <fullName>INFONAVIT</fullName>
            </value>
            <value>
                <fullName>ISSFAM</fullName>
            </value>
            <value>
                <fullName>ISSSTELEON</fullName>
            </value>
            <value>
                <fullName>SHF/BANCO</fullName>
            </value>
            <value>
                <fullName>PENSIONES</fullName>
            </value>
            <value>
                <fullName>COFINAVIT</fullName>
            </value>
            <value>
                <fullName>BANSEFI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Inventario__c/Inventario__c.object-meta.xml
<CustomObject>
    <label>Proceso ATC</label>
    <nameField>
        <label>Id Vivienda</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProcesosATC</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Inventario__c/fields/Notaria__c.field-meta.xml
<CustomField>
    <fullName>Notaria__c</fullName>
    <label>Notaria</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Notario__c.field-meta.xml
<CustomField>
    <fullName>Notario__c</fullName>
    <label>Notario</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/ProductoFinanciero__c.field-meta.xml
<CustomField>
    <fullName>ProductoFinanciero__c</fullName>
    <label>Producto Financiero</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/ReferenciaBancariaCliente__c.field-meta.xml
<CustomField>
    <fullName>ReferenciaBancariaCliente__c</fullName>
    <label>Referencia Bancaria del cliente</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/TipoCredito__c.field-meta.xml
<CustomField>
    <fullName>TipoCredito__c</fullName>
    <label>Tipo de crédito</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BANCO - SOFOL</fullName>
            </value>
            <value>
                <fullName>BANJERCITO</fullName>
            </value>
            <value>
                <fullName>CAJA FLORENCIO ROSAS</fullName>
            </value>
            <value>
                <fullName>CONTADO</fullName>
            </value>
            <value>
                <fullName>CONTINGENCIA</fullName>
            </value>
            <value>
                <fullName>FOVISSSTE</fullName>
            </value>
            <value>
                <fullName>INFONAVIT</fullName>
            </value>
            <value>
                <fullName>ISSFAM</fullName>
            </value>
            <value>
                <fullName>ISSSTELEON</fullName>
            </value>
            <value>
                <fullName>SHF/BANCO</fullName>
            </value>
            <value>
                <fullName>PENSIONES</fullName>
            </value>
            <value>
                <fullName>COFINAVIT</fullName>
            </value>
            <value>
                <fullName>BANSEFI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/LogATC__c/LogATC__c.object-meta.xml
<CustomObject>
    <label>LogATC</label>
    <nameField>
        <label>Nombre de LogATC</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LogATC</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/LogATC__c/fields/FechaHora__c.field-meta.xml
<CustomField>
    <fullName>FechaHora__c</fullName>
    <label>Fecha y Hora</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/LogATC__c/fields/Mensaje__c.field-meta.xml
<CustomField>
    <fullName>Mensaje__c</fullName>
    <label>Mensaje</label>
    <length>130000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/LogATC__c/fields/Metodo__c.field-meta.xml
<CustomField>
    <fullName>Metodo__c</fullName>
    <label>Método</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Notaria__c/Notaria__c.object-meta.xml
<CustomObject>
    <label>Notaría</label>
    <nameField>
        <label>Notaría</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notarías</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Notaria__c/fields/Notario__c.field-meta.xml
<CustomField>
    <fullName>Notario__c</fullName>
    <label>Notario</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/PaqueteEntrega__c/PaqueteEntrega__c.object-meta.xml
<CustomObject>
    <label>Paquete</label>
    <nameField>
        <label>Nombre del Paquete</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Paquetes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/EntregasWS_Queueable.cls
public without sharing class EntregasWS_Queueable implements Queueable, Database.AllowsCallouts{

    Integer daysBefore;

    public EntregasWS_Queueable(Integer daysBefore){
        this.daysBefore = daysBefore;
    }
    
    public void execute(QueueableContext context){
        recursionCheck.entregasWS = true;

        LogATC__c log = new LogATC__c();
        log.FechaHora__c = Datetime.now();
        log.Metodo__c = 'ImportarEntregaWS';

        Date defaultDate = date.newInstance(1900, 1, 1);

        boolean runningInASandbox = [SELECT IsSandbox FROM Organization LIMIT 1].IsSandbox;

        try{
            
            List<Account> listaCuenta = new List<Account>();
            xmlnsOracleComJavergtiEntrega.bpelQueryEntrega_pt wsPort = new xmlnsOracleComJavergtiEntrega.bpelQueryEntrega_pt();
            wsPort.timeout_x = 120000;  
            xmlnsOracleComJavergtiEntrega.getEntregaRs_element respuesta = new xmlnsOracleComJavergtiEntrega.getEntregaRs_element();
            respuesta = wsPort.getEntrega(daysBefore);

            xmlnsOracleComJavergtiEntrega.Result_element mensaje = respuesta.Result;
            xmlnsOracleComJavergtiEntrega.ReporteEntrega_element reporteEntrega = respuesta.ReporteEntrega;
            List<xmlnsOracleComJavergtiEntrega.RowType> resultados = new List<xmlnsOracleComJavergtiEntrega.RowType>();
            resultados.addAll(reporteEntrega.Row);   

            List<String> filtroCuentas = new List<String>();
            List<String> filtroCuentas2 = new List<String>();

            log.Mensaje__c = 'Estatus SIEBEL: '+mensaje.Success;
            log.Mensaje__c += '\r\n';
            log.Mensaje__c += 'Respuesta SIEBEL: '+mensaje.SysMessage;
            log.Mensaje__c += '\r\n';
            log.Mensaje__c += 'Cantidad de registros: '+resultados.size();
            log.Mensaje__c += '\r\n';

            for(xmlnsOracleComJavergtiEntrega.RowType obj : resultados){
                if(obj.Estatus != 'Firmado'){
                    filtroCuentas.add(obj.Numero_cliente);
                    filtroCuentas2.add((obj.Nombre +' '+obj.Apellido_Paterno+' '+obj.Apellido_Materno).toUpperCase());
                }else{
                    log.Mensaje__c += '\r\n';
                    log.Mensaje__c += 'Proceso con estatus no válido: '+ obj.Num_Proceso + ' - ' + obj.Nombre +' '+obj.Apellido_Paterno+' '+obj.Apellido_Materno ;
                    log.Mensaje__c += '\r\n';
                    log.Mensaje__c += '\r\n';
                }
            } 

            Map<String, Id> entregas = new Map<String, Id>();
            Map<String, Account> cuentas = new Map<String, Account>();
            Map<String, Id> fraccionamientos = new Map<String, Id>();
            Map<String, Inventario__c> inventarios = new Map<String, Inventario__c>();

            /*for(Account c : [SELECT Id, Name, MiddleName, LastName, Nombre_cta__c, Apellidomaterno_cta__c, RecordTypeId, Apellidopaterno_cta__c,FechaNacimiento__c, CorreoElectronico__c, Telefono2__c, NumerodeCliente__c 
                            FROM Account WHERE((NumerodeCliente__c IN : filtroCuentas AND NumerodeCliente__c != null) OR (IdMasComercial__c IN :filtroCuentas AND IdMasComercial__c != null) OR Name IN :filtroCuentas2) LIMIT 48000]){
                cuentas.put(c.Numerodecliente__c, c);
            }*/
            
            for(Account c : [SELECT Id, Name, LastName, Nombre_cta__c, Apellidomaterno_cta__c, RecordTypeId, Apellidopaterno_cta__c,FechaNacimiento__c, CorreoElectronico__c, Telefono2__c, NumerodeCliente__c 
                            FROM Account WHERE((NumerodeCliente__c IN : filtroCuentas AND NumerodeCliente__c != null) OR (IdMasComercial__c IN :filtroCuentas AND IdMasComercial__c != null) OR Name IN :filtroCuentas2) LIMIT 48000]){
                cuentas.put(c.Numerodecliente__c, c);
            }

            filtroCuentas.clear();
            filtroCuentas2.clear();
            
            List<String> numerosDeCliente = new List<String>();
                
            List<Account> upsertCuentas = new List<Account>();
            List<Inventario__c> upsertInventarios = new List<Inventario__c>();
            List<PaqueteEntrega__c> upsertPaquetes = new List<PaqueteEntrega__c>();
            
            Id recordtypeA = [SELECT Id, Name FROM RecordType WHERE Name = 'Clientes ATC' AND IsPersonType=False].Id;
            Id recordtypePA = [SELECT Id, Name FROM RecordType WHERE Name = 'Clientes ATC' AND IsPersonType=True].Id;

            Map<String, Account> rCuenta = new Map<String, Account>();
            Map<String, Account> mapAyudaCuenta = new Map<String, Account>();
            
            for(xmlnsOracleComJavergtiEntrega.RowType obj : resultados){
                if(obj.Estatus != 'Firmado'){
                    Account cuenta = new Account();
                    
                    cuenta.isATC__c = true;
                    cuenta.Numerodecliente__c = obj.Numero_cliente;
                    cuenta.IdMasComercial__c = obj.Numero_cliente;
                    cuenta.Nombre_cta__c = obj.Nombre;
                    cuenta.Apellidopaterno_cta__c = obj.Apellido_Paterno;
                    cuenta.Apellidomaterno_cta__c = obj.Apellido_Materno;
                    cuenta.ProductoFinanciero__c = obj.Producto_Financiero;
                    cuenta.TipoCredito__c = obj.Tipo_de_Credito;
                    //cuenta.CorreoElectronico__c = obj.Correo_electronico;
                    cuenta.Notaria__c = obj.Notaria;
                    cuenta.Notario__c = obj.Notario;
                    cuenta.ReferenciaBancariaCliente__c = obj.Referencia_bancaria_cliente;
                    //validar longitud 10 digitos + valores numericos -> dejar valor nulo 
                    //+52 - > null, null -> -1, 1 -> 1
                    cuenta.Phone = obj.Telefono_casa != null && obj.Telefono_casa != '' && obj.Telefono_casa != '-1' && obj.Telefono_casa != '1'  && obj.Telefono_casa != '0'&& obj.Telefono_casa != '+0'? getFilteredPhoneWPrefix(obj.Telefono_casa) : '+52';
                    cuenta.TelefonoCelular__c = obj.Telefono_celular != null && obj.Telefono_celular != '' && obj.Telefono_celular != '-1' && obj.Telefono_celular != '1'  && obj.Telefono_celular != '0'&& obj.Telefono_celular != '+0'? getFilteredPhoneWPrefix(obj.Telefono_celular) : '+52';
                    cuenta.TelefonoOtro__c = obj.Telefono_Otro != null && obj.Telefono_Otro != '' && obj.Telefono_Otro != '-1' && obj.Telefono_Otro != '1' && obj.Telefono_Otro != '0' && obj.Telefono_Otro != '+0'? getFilteredPhoneWPrefix(obj.Telefono_Otro) : '+52';
                    //cuenta.Phone = obj.Telefono_casa.Substring(0,1) == '52' ? '+'+obj.Telefono_casa : obj.Telefono_casa.Substring(0,2) == '+52' ? obj.Telefono_casa : '+52'+obj.Telefono_casa;
                    //cuenta.TelefonoCelular__c = obj.Telefono_celular.Substring(0,2) == '52' ? '+'+obj.Telefono_celular : obj.Telefono_celular.Substring(0,2) == '+52' ? obj.Telefono_celular : '+52'+obj.Telefono_celular;
                    //cuenta.TelefonoOtro__c = obj.Telefono_Otro.Substring(0,2) == '52' ? '+'+obj.Telefono_Otro : obj.Telefono_Otro.Substring(0,2) == '+52' ? obj.Telefono_Otro : '+52'+obj.Telefono_Otro;

                    String RawEmail = obj.Correo_electronico;
                    if(RawEmail.startsWith('.')){
                        RawEmail = RawEmail.right(RawEmail.length()-1);
                    }
                    String empty_regex = '^\\s*$';
                    String regex = '^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$';
                    Pattern regexPattern_empty = Pattern.compile(empty_regex);
                    Matcher regexMatcher_empty = regexPattern_empty.matcher(RawEmail);
                    Pattern regexPattern = Pattern.compile(regex);
                    Matcher regexMatcher = regexPattern.matcher(RawEmail);
                    String replacedMessage = 'Error al verificar email: ' + RawEmail + ', ' + cuenta.Name + '. Se asignara una direccion predeterminada';

                    if((regexMatcher_empty.find() || regexMatcher.find()) && !runningInASandbox) {
                        try{
                            cuenta.CorreoElectronico__c = RawEmail;
                        }catch(Exception ex){
                            system.debug('ERROR ' + ex.getMessage());
                        }
                    }else{
                        try{
                            System.debug(System.LoggingLevel.ERROR, replacedMessage);
                            System.debug(cuenta.Name);
                            cuenta.CorreoElectronico__c = 'undefined.atc@javer.com.mx';
                        }catch(Exception ex){
                            system.debug('ERROR ' + ex.getMessage());
                        }
                    }

                    if(cuentas.containsKey(cuenta.Numerodecliente__c)){
                        Account cuentaTemp = cuentas.get(cuenta.Numerodecliente__c);
                        cuenta.Id = cuentaTemp.Id;
                        if(cuentaTemp.RecordTypeId == recordtypePA){
                            cuenta.FirstName = obj.Nombre;
                            /*cuenta.MiddleName = obj.Apellido_Paterno;*/
                            cuenta.LastName = obj.Apellido_Materno;
                            cuenta.RecordTypeId = recordtypePA;
                            cuenta.PersonBirthdate = obj.FechaNacimiento;
                            cuenta.PersonEmail = cuenta.CorreoElectronico__c;
                        }else{
                            cuenta.Name = cuenta.Nombre_cta__c + ' ' + cuenta.Apellidopaterno_cta__c + ' ' + cuenta.Apellidomaterno_cta__c;
                            cuenta.RecordTypeId = recordtypeA;
                        }
                    }else{
                        cuenta.FirstName = obj.Nombre;
                        /*cuenta.MiddleName = obj.Apellido_Paterno;*/
                        cuenta.PersonBirthdate = obj.FechaNacimiento;
                        cuenta.LastName = obj.Apellido_Materno;
                        cuenta.RecordTypeId = recordtypePA;
                    }
                    
                    try{
                        mapAyudaCuenta.put(obj.Numero_cliente, cuenta);
                    }catch(Exception p){
                        mapAyudaCuenta.put(obj.Numero_cliente, cuenta);
                    }
                }
            }

            //for(String key :mapAyudaCuenta.keySet()){
                //upsertCuentas.add(mapAyudaCuenta.get(key));
            //}

            upsert mapAyudaCuenta.values();
            log.Mensaje__c += 'Cuentas Actualizadas/Insertadas: '+mapAyudaCuenta.size();
            log.Mensaje__c += '\r\n';

            //for(Account cu : mapAyudaCuenta.values()){
              //  rCuenta.put(cu.Numerodecliente__c, cu);
            //}

            EntregasWSInventario_Queueable EntregasWSInventario_Queueable = new EntregasWSInventario_Queueable(daysBefore, log, mapAyudaCuenta);
            ID jobID = System.enqueueJob(EntregasWSInventario_Queueable);

        }catch(Exception io){
            log.Mensaje__c += 'EXCEPTION: ' + io.getMessage() + ' - ' + io.getLineNumber() +' - ' + io.getCause() +' - '+io.getStackTraceString();
            log.Mensaje__c += '\r\n';
            insert log;
            
            if(Test.isRunningTest()){
                testingClass();
            }
        }
    }

    public static String getFilteredPhoneWPrefix(String phone){
        System.debug(phone);
        if(!String.isBlank(phone) && phone.length() == 10 && phone.Substring(0,1) != '+' && phone.Substring(0,4) != '+521' && phone.Substring(0,2) != '52'){
            phone = '+52' + phone;
        }else if(!String.isBlank(phone) && phone.length() > 9){
            if(phone.Substring(0,2) == '52' || (phone.Substring(0,2) == '+1' && phone.length() == 12)){
                phone = '+52' + phone.Substring(2,phone.length());
            }else if(phone.Substring(0,1) == '1' && phone.length() ==  11){
                phone = '+52' + phone.Substring(1,phone.length());
            }else if(phone.Substring(0,3) == '521' && phone.length() ==  13){
                phone = '+52' + phone.Substring(3,phone.length());
            }else if(phone.Substring(0,3) == '+52' && phone.length() == 13){
            }else if(phone.Substring(0,4) == '+521' && phone.length() == 14){
                phone = '+52' + phone.Substring(4,phone.length());
            }else if(phone.length() == 11 && phone.Substring(0,1) == '+'){
                phone = '+52' + phone.Substring(1,phone.length());
            }else if(phone.length() == 10 && phone.Substring(0,1) != '+' && phone.Substring(0,4) != '+521' && phone.Substring(0,2) != '52' ){
                phone = '+52' + phone;
            }else{
                phone = '+52';
            }
        }else{
            phone = '+52';
        }
        System.debug(phone);
        return phone;
    }
    
    public void testingClass(){
       Integer i = 1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
         i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        i=1;
        
    }

}