unpackaged/main/default/objects/Account/fields/Apellidomaterno_cta__c.field-meta.xml
<CustomField>
    <fullName>Apellidomaterno_cta__c</fullName>
    <label>Apellido Materno</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Canal_de_Venta__c.field-meta.xml
<CustomField>
    <fullName>Canal_de_Venta__c</fullName>
    <label>Canal de Venta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Canal_de_Venta</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/CorreoElectronico__c.field-meta.xml
<CustomField>
    <fullName>CorreoElectronico__c</fullName>
    <label>Correo Electrónico</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Empresa__c.field-meta.xml
<CustomField>
    <fullName>Empresa__c</fullName>
    <label>Empresa</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Estatus_Lista_Negra_QEQ__c.field-meta.xml
<CustomField>
    <fullName>Estatus_Lista_Negra_QEQ__c</fullName>
    <label>Estatus Lista Negra</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SIN VALIDAR</fullName>
                <default>true</default>
                <label>SIN VALIDAR</label>
            </value>
            <value>
                <fullName>LISTA NEGRA</fullName>
            </value>
            <value>
                <fullName>LN CONFIRMADO</fullName>
            </value>
            <value>
                <fullName>VALIDADO</fullName>
            </value>
            <value>
                <fullName>PPE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Notaria__c.field-meta.xml
<CustomField>
    <fullName>Notaria__c</fullName>
    <label>Notaría</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Otro_Telefono__c.field-meta.xml
<CustomField>
    <fullName>Otro_Telefono__c</fullName>
    <label>Otro Teléfono</label>
    <type>Phone</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Sexo__c.field-meta.xml
<CustomField>
    <fullName>Sexo__c</fullName>
    <label>Sexo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sexo</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/TelefonoCelular__c.field-meta.xml
<CustomField>
    <fullName>TelefonoCelular__c</fullName>
    <label>Teléfono Celular</label>
    <type>Phone</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Prospecto.recordType-meta.xml
<RecordType>
    <fullName>Prospecto</fullName>
    <active>true</active>
    <label>Prospecto</label>
</RecordType>

unpackaged/main/default/objects/Co_Acreditado__c/Co_Acreditado__c.object-meta.xml
<CustomObject>
    <label>Co Acreditado</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Folio Co Acreditado</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Co Acreditados</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Co_Acreditado__c/fields/Apellido_Materno_CO_Acreditado__c.field-meta.xml
<CustomField>
    <fullName>Apellido_Materno_CO_Acreditado__c</fullName>
    <label>Apellido Materno CO Acreditado</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Co_Acreditado__c/fields/Apellido_Paterno_CO_Acreditado__c.field-meta.xml
<CustomField>
    <fullName>Apellido_Paterno_CO_Acreditado__c</fullName>
    <label>Apellido Paterno CO Acreditado</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Co_Acreditado__c/fields/Co_Acreditado__c.field-meta.xml
<CustomField>
    <fullName>Co_Acreditado__c</fullName>
    <formula>HYPERLINK(&quot;/lightning/r/co_acreditado__c/&quot; &amp; Id &amp; &quot;/view&quot;,Name &amp; &quot; - &quot; &amp; Nombre__c &amp; &quot; &quot; &amp; Apellido_Paterno_CO_Acreditado__c  &amp; &quot; &quot; &amp; Apellido_Paterno_CO_Acreditado__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Co Acreditado</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Co_Acreditado__c/fields/Contrato__c.field-meta.xml
<CustomField>
    <fullName>Contrato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dictaminación</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Co Acreditados</relationshipLabel>
    <relationshipName>Co_Acreditados</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Co_Acreditado__c/fields/Sexo__c.field-meta.xml
<CustomField>
    <fullName>Sexo__c</fullName>
    <label>Sexo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MASCULINO</fullName>
            </value>
            <value>
                <fullName>FEMENINO</fullName>
            </value>
            <value>
                <fullName>INDISTINTO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contract/fields/Canal_de_venta__c.field-meta.xml
<CustomField>
    <fullName>Canal_de_venta__c</fullName>
    <label>Canal de venta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>DIGITAL ASESOR</fullName>
            </value>
            <value>
                <fullName>EVENTO</fullName>
            </value>
            <value>
                <fullName>LLAMADA CALL CENTER</fullName>
            </value>
            <value>
                <fullName>MACROVENTA</fullName>
            </value>
            <value>
                <fullName>MEDIO PUBLICITARIO</fullName>
            </value>
            <value>
                <fullName>MEDIOS DIGITALES</fullName>
            </value>
            <value>
                <fullName>PROGRAMAS INSTITUCIONALES</fullName>
            </value>
            <value>
                <fullName>PROMOTOR EXTERNO</fullName>
            </value>
            <value>
                <fullName>PROSPECCION</fullName>
            </value>
            <value>
                <fullName>PROSPECTO ASESOR</fullName>
            </value>
            <value>
                <fullName>REFERIDOS</fullName>
            </value>
            <value>
                <fullName>VENTA EMPRESARIAL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contract/fields/Empresa__c.field-meta.xml
<CustomField>
    <fullName>Empresa__c</fullName>
    <label>Empresa</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contract/fields/Fecha_de_Constituci_n__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_Constituci_n__c</fullName>
    <label>Fecha de Constitución</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Contract/fields/No_Escritura__c.field-meta.xml
<CustomField>
    <fullName>No_Escritura__c</fullName>
    <label>No. Escritura</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contract/fields/Notaria__c.field-meta.xml
<CustomField>
    <fullName>Notaria__c</fullName>
    <label>Notaría</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contract/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proceso de Venta</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Dictaminación</relationshipLabel>
    <relationshipName>Dictaminacion</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contract/fields/Otro_telefono__c.field-meta.xml
<CustomField>
    <fullName>Otro_telefono__c</fullName>
    <formula>Account.Otro_Telefono__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Otro teléfono</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contract/fields/RFC_Compania__c.field-meta.xml
<CustomField>
    <fullName>RFC_Compania__c</fullName>
    <label>RFC Compañía</label>
    <length>13</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contract/fields/Sexo__c.field-meta.xml
<CustomField>
    <fullName>Sexo__c</fullName>
    <formula>TEXT(Account.Sexo__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sexo</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contract/fields/TelefonoCelular__c.field-meta.xml
<CustomField>
    <fullName>TelefonoCelular__c</fullName>
    <formula>Account.TelefonoCelular__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Teléfono Celular</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contrato__c/Contrato__c.object-meta.xml
<CustomObject>
    <label>Contratos</label>
    <nameField>
        <label>No. Interno</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contratos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Notaria__c/Notaria__c.object-meta.xml
<CustomObject>
    <label>Notaría</label>
    <nameField>
        <label>Notaría</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notarías</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Opportunity/fields/Canal_de_venta__c.field-meta.xml
<CustomField>
    <fullName>Canal_de_venta__c</fullName>
    <label>Canal de venta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Canal_de_Venta</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Plan_de_Venta__c.field-meta.xml
<CustomField>
    <fullName>Plan_de_Venta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plan de Venta</label>
    <referenceTo>Plan_de_Venta__c</referenceTo>
    <relationshipLabel>Procesos de Ventas</relationshipLabel>
    <relationshipName>Procesos_de_Ventas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/TelefonoCelular__c.field-meta.xml
<CustomField>
    <fullName>TelefonoCelular__c</fullName>
    <formula>Account.TelefonoCelular__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Teléfono Celular</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Vivienda__c.field-meta.xml
<CustomField>
    <fullName>Vivienda__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vivienda</label>
    <referenceTo>Vivienda__c</referenceTo>
    <relationshipLabel>Procesos de Ventas</relationshipLabel>
    <relationshipName>Procesos_de_Ventas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/Plan_de_Venta__c.object-meta.xml
<CustomObject>
    <label>Plan de Venta</label>
    <nameField>
        <displayFormat>Plan de Venta-{000000}</displayFormat>
        <label>Plan de Venta</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plan de Venta</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Exepcion_Fondo_de_Garantia_Aprobado__c.field-meta.xml
<CustomField>
    <fullName>Exepcion_Fondo_de_Garantia_Aprobado__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Exepción Fondo de Garantía Aprobado</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Fecha_Proyeccion_escritura__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Proyeccion_escritura__c</fullName>
    <defaultValue>Today() + 30</defaultValue>
    <label>Fecha Proyección de escritura</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proceso de Venta</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Plan de Venta</relationshipLabel>
    <relationshipName>Plan_de_Venta</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Plan_de_Venta__c.field-meta.xml
<CustomField>
    <fullName>Plan_de_Venta__c</fullName>
    <formula>&quot;Plan de Venta&quot; &amp; &quot; &quot;&amp;  Oportunidad__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Plan de Venta</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Plan_de_Venta_Aprobado__c.field-meta.xml
<CustomField>
    <fullName>Plan_de_Venta_Aprobado__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Plan de Venta Aprobado</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Vivienda__c.field-meta.xml
<CustomField>
    <fullName>Vivienda__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vivienda</label>
    <referenceTo>Vivienda__c</referenceTo>
    <relationshipLabel>Plan de Venta</relationshipLabel>
    <relationshipName>Plan_de_Venta</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Vivienda__c/Vivienda__c.object-meta.xml
<CustomObject>
    <label>Vivienda</label>
    <nameField>
        <label>Vivienda</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Viviendas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/globalValueSets/Canal_de_Venta.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>DIGITAL ASESOR</fullName>
    </customValue>
    <customValue>
        <fullName>EVENTO</fullName>
    </customValue>
    <customValue>
        <fullName>LLAMADA CALL CENTER</fullName>
    </customValue>
    <customValue>
        <fullName>MACROVENTA</fullName>
    </customValue>
    <customValue>
        <fullName>MACROVENTA 2015</fullName>
    </customValue>
    <customValue>
        <fullName>MEDIO PUBLICITARIO</fullName>
    </customValue>
    <customValue>
        <fullName>MEDIOS DIGITALES</fullName>
    </customValue>
    <customValue>
        <fullName>PROGRAMAS INSTITUCIONALES</fullName>
    </customValue>
    <customValue>
        <fullName>PROMOTOR EXTERNO</fullName>
    </customValue>
    <customValue>
        <fullName>PROSPECCION</fullName>
    </customValue>
    <customValue>
        <fullName>PROSPECTO ASESOR</fullName>
    </customValue>
    <customValue>
        <fullName>REFERIDOS</fullName>
    </customValue>
    <customValue>
        <fullName>VENTA EMPRESARIAL</fullName>
    </customValue>
    <customValue>
        <fullName>CARGA INICIAL</fullName>
    </customValue>
    <masterLabel>Canal de Venta</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Sexo.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>MASCULINO</fullName>
    </customValue>
    <customValue>
        <fullName>FEMENINO</fullName>
    </customValue>
    <customValue>
        <fullName>NO BINARIO</fullName>
    </customValue>
    <masterLabel>Sexo</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/CLASS_Plan_Venta_Aprobacion_Test.cls
@isTest
public class CLASS_Plan_Venta_Aprobacion_Test {
    @isTest 
    static void testPlanVentaAprobacion() {
        Account acc = new Account();
        acc.FirstName= 'Lopez';
        acc.LastName= 'test';
        acc.RecordTypeId =Schema.sObjectType.Account.getRecordTypeInfosBydevelopername().get('Prospecto_Persona_Fisica').getRecordTypeId();
        acc.CorreoElectronico__c = 'test@prospects.com';
        acc.Apellidomaterno_cta__c = 'dahuoh';
        acc.PersonBirthdate=date.today().addyears(-20);
        acc.Phone = '+528119928819';
        acc.Otro_Telefono__c = '+528119928819';
        acc.TelefonoCelular__c='+525530303030'; 
        acc.Canal_de_Venta__c = 'PROSPECTO ASESOR';
        acc.Estatus_Lista_Negra_QEQ__c = 'VALIDADO';
        insert acc;
        Opportunity opp = new Opportunity(Name = 'Test Opportunity');
        opp.StageName = 'Validación';
        opp.CloseDate = Date.today().adddays(10);
        insert opp;
        opp.AccountId = acc.Id;
        update opp;
        Contract c =  new Contract();
        c.Name = 'Test Contract ' ;
        c.AccountId = acc.Id;
        c.Oportunidad__c = opp.id;
        c.Empresa__c = 'test';
        c.RFC_Compania__c = 'test';
        c.Fecha_de_Constituci_n__c = system.today();
        c.No_Escritura__c = 'test';
        c.Notaria__c = 'test';
        insert c;
        Co_Acreditado__c acr = new Co_Acreditado__c();
        acr.Contrato__c = c.Id;
        acr.Apellido_Paterno_CO_Acreditado__c = 'test';
        acr.Apellido_Materno_CO_Acreditado__c = 'test';
        acr.Sexo__c = 'MASCULINO';
        insert acr;
        Plan_de_Venta__c planVenta = new Plan_de_Venta__c(Oportunidad__c = opp.Id, 
                                                          Exepcion_Fondo_de_Garantia_Aprobado__c = true, Fecha_Proyeccion_escritura__c = Date.today(),
                                                          Plan_de_Venta_Aprobado__c = false);
        insert planVenta; //Vivienda__c = vv.Id,
      
        CLASS_Plan_Venta_Aprobacion.PlanVentaInputWrapper input = new CLASS_Plan_Venta_Aprobacion.PlanVentaInputWrapper();
        input.PlanVentaId = planVenta.Id;
        List<CLASS_Plan_Venta_Aprobacion.PlanVentaInputWrapper> inputList = new List<CLASS_Plan_Venta_Aprobacion.PlanVentaInputWrapper>();
        inputList.add(input);
        Test.startTest();
        List<CLASS_Plan_Venta_Aprobacion.PlanVentaDetailsWrapper> outputList = CLASS_Plan_Venta_Aprobacion.CLASS_Plan_Venta_Aprobacion(inputList);
        Test.stopTest();
      
    }
   /* @isTest
    static void testPlanVentaAprobacion2() {
        Account acc = new Account();
        acc.FirstName= 'Lopez';
        acc.LastName= 'test';
        acc.RecordTypeId =Schema.sObjectType.Account.getRecordTypeInfosBydevelopername().get('Prospecto_Persona_Fisica').getRecordTypeId();
        acc.CorreoElectronico__c = 'test@prospects.com';
        acc.Apellidomaterno_cta__c = 'dahuoh';
        acc.PersonBirthdate=date.today().addyears(-20);
        acc.Phone = '+528119928819';
        acc.Otro_Telefono__c = '+528119928819';
        acc.TelefonoCelular__c='+525530303030'; 
        acc.Canal_de_Venta__c = 'PROSPECTO ASESOR';
        acc.Estatus_Lista_Negra_QEQ__c = 'VALIDADO';
        insert acc;
        Opportunity opp = new Opportunity(Name = 'Test Opportunity');
        opp.StageName = 'Validación';
        opp.CloseDate = Date.today().adddays(10);
        insert opp;
        opp.AccountId = acc.Id;
        update opp;
        Plan_de_Venta__c planVenta = new Plan_de_Venta__c(Oportunidad__c = opp.Id,
                                                          Plan_de_Venta_Aprobado__c = false);
        insert planVenta;
        Contract contract = new Contract(Name = 'Test Contract ', AccountId = acc.Id, Oportunidad__c = opp.id);
        insert contract;
        Co_Acreditado__c acr = new Co_Acreditado__c();
        acr.Contrato__c = contract.id;
        acr.Apellido_Paterno_CO_Acreditado__c = 'test';
        acr.Apellido_Materno_CO_Acreditado__c = 'test';
        acr.Sexo__c = 'MASCULINO';
        insert acr;
        CLASS_Plan_Venta_Aprobacion.PlanVentaInputWrapper input = new CLASS_Plan_Venta_Aprobacion.PlanVentaInputWrapper();
        input.PlanVentaId = planVenta.Id;
        List<CLASS_Plan_Venta_Aprobacion.PlanVentaInputWrapper> inputList = new List<CLASS_Plan_Venta_Aprobacion.PlanVentaInputWrapper>();
        inputList.add(input);
        Test.startTest();
        List<CLASS_Plan_Venta_Aprobacion.PlanVentaDetailsWrapper> outputList = CLASS_Plan_Venta_Aprobacion.CLASS_Plan_Venta_Aprobacion(inputList);
        Test.stopTest();
        System.assertEquals(1, outputList.size());
        CLASS_Plan_Venta_Aprobacion.PlanVentaDetailsWrapper output = outputList[0];
        System.assertNotEquals(null, output.PlanVentaResult);
        Plan_de_Venta__c updatedPlanVenta = [SELECT Plan_de_Venta_Aprobado__c FROM Plan_de_Venta__c WHERE Id = :planVenta.Id];
        System.assertEquals(false, updatedPlanVenta.Plan_de_Venta_Aprobado__c);
    } */
}