unpackaged/main/default/objects/Account/fields/Apellidomaterno_cta__c.field-meta.xml
<CustomField>
    <fullName>Apellidomaterno_cta__c</fullName>
    <label>Apellido Materno</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Canal_de_Venta__c.field-meta.xml
<CustomField>
    <fullName>Canal_de_Venta__c</fullName>
    <label>Canal de Venta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Canal_de_Venta</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/CorreoElectronico__c.field-meta.xml
<CustomField>
    <fullName>CorreoElectronico__c</fullName>
    <label>Correo Electrónico</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Sub_canal_de_venta__c.field-meta.xml
<CustomField>
    <fullName>Sub_canal_de_venta__c</fullName>
    <label>Sub canal de venta</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Canal_de_Venta__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Sub_canal_de_venta</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/TelefonoCelular__c.field-meta.xml
<CustomField>
    <fullName>TelefonoCelular__c</fullName>
    <label>Teléfono Celular</label>
    <type>Phone</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/TelefonoOtro__c.field-meta.xml
<CustomField>
    <fullName>TelefonoOtro__c</fullName>
    <label>Teléfono Otro</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/globalValueSets/Canal_de_Venta.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>DIGITAL ASESOR</fullName>
    </customValue>
    <customValue>
        <fullName>EVENTO</fullName>
    </customValue>
    <customValue>
        <fullName>LLAMADA CALL CENTER</fullName>
    </customValue>
    <customValue>
        <fullName>MACROVENTA</fullName>
    </customValue>
    <customValue>
        <fullName>MACROVENTA 2015</fullName>
    </customValue>
    <customValue>
        <fullName>MEDIO PUBLICITARIO</fullName>
    </customValue>
    <customValue>
        <fullName>MEDIOS DIGITALES</fullName>
    </customValue>
    <customValue>
        <fullName>PROGRAMAS INSTITUCIONALES</fullName>
    </customValue>
    <customValue>
        <fullName>PROMOTOR EXTERNO</fullName>
    </customValue>
    <customValue>
        <fullName>PROSPECCION</fullName>
    </customValue>
    <customValue>
        <fullName>PROSPECTO ASESOR</fullName>
    </customValue>
    <customValue>
        <fullName>REFERIDOS</fullName>
    </customValue>
    <customValue>
        <fullName>VENTA EMPRESARIAL</fullName>
    </customValue>
    <customValue>
        <fullName>CARGA INICIAL</fullName>
    </customValue>
    <masterLabel>Canal de Venta</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Sub_canal_de_venta.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1-2GUPNA8</fullName>
    </customValue>
    <customValue>
        <fullName>ACTIVACION/EVENTO</fullName>
    </customValue>
    <customValue>
        <fullName>ACTIVACION/EVENTO/PERIFERIA</fullName>
    </customValue>
    <customValue>
        <fullName>AGS FERIA CANADEVI</fullName>
    </customValue>
    <customValue>
        <fullName>AGS MOCTEZUMA</fullName>
    </customValue>
    <customValue>
        <fullName>AGS SAN DIEGO</fullName>
    </customValue>
    <customValue>
        <fullName>AGS VILLA ASUNCION</fullName>
    </customValue>
    <customValue>
        <fullName>APP INVITADO</fullName>
    </customValue>
    <customValue>
        <fullName>BLOGGER/TANIA RENDON</fullName>
    </customValue>
    <customValue>
        <fullName>BUEN FIN</fullName>
    </customValue>
    <customValue>
        <fullName>CALL CENTER/TELEMARKETING</fullName>
    </customValue>
    <customValue>
        <fullName>CAMBACEO</fullName>
    </customValue>
    <customValue>
        <fullName>CARTELERA MOVIL</fullName>
    </customValue>
    <customValue>
        <fullName>CARTELERA PV</fullName>
    </customValue>
    <customValue>
        <fullName>CARTERA DE CLIENTES</fullName>
    </customValue>
    <customValue>
        <fullName>CARTERA PROPIA</fullName>
    </customValue>
    <customValue>
        <fullName>CITA ASESOR</fullName>
    </customValue>
    <customValue>
        <fullName>COLABORADOR JAVER</fullName>
    </customValue>
    <customValue>
        <fullName>COMPAÑERO DE TRABAJO</fullName>
    </customValue>
    <customValue>
        <fullName>CONVENIO PABELLON M</fullName>
    </customValue>
    <customValue>
        <fullName>CORREO</fullName>
    </customValue>
    <customValue>
        <fullName>CORREO DIRECTO/CARTA</fullName>
    </customValue>
    <customValue>
        <fullName>EDO MEX SAMARA</fullName>
    </customValue>
    <customValue>
        <fullName>EN EMPRESA (VENTA EMPRESARIAL)</fullName>
    </customValue>
    <customValue>
        <fullName>ESPECTACULAR/CARTELERA</fullName>
    </customValue>
    <customValue>
        <fullName>EVENTO (MACROVENTA, SUPERVTA)</fullName>
    </customValue>
    <customValue>
        <fullName>EXPO/FERIA</fullName>
    </customValue>
    <customValue>
        <fullName>FACEBOOK</fullName>
    </customValue>
    <customValue>
        <fullName>FACEBOOK INBOX</fullName>
    </customValue>
    <customValue>
        <fullName>FAMILIAR</fullName>
    </customValue>
    <masterLabel>Sub canal de venta</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/BatchLinkAccountActivity_Test.cls
@isTest 
public with sharing class BatchLinkAccountActivity_Test {

    @testSetup
    public static void setup(){
		 Account acc = new Account(Apellidomaterno_cta__c = 'materno',FirstName = 'fName',LastName = 'lName',Canal_de_Venta__c = 'PROGRAMAS INSTITUCIONALES',
                                      TelefonoCelular__c = '+525656566567',phone = '+525656566567',Sub_canal_de_venta__c = 'COLABORADOR JAVER',
                                  CorreoElectronico__c = 'abc@test.com',TelefonoOtro__c = '+525656566567',
                                      RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Prospecto_Persona_Fisica').getRecordTypeId());
        insert acc;
        
        talkdesk__Talkdesk_Activity__c tda = new talkdesk__Talkdesk_Activity__c();
        tda.Name = 'test';
        tda.talkdesk__Talkdesk_Id__c = 'test';
        tda.talkdesk__Contact_Phone__c = '+525656566567';
        insert tda;
        
        tda.talkdesk__Account__c = null;
        update tda;

    }

    @isTest
    public static void BatchLinkAccountActivity(){
        BatchLinkAccountActivity BLTA = new BatchLinkAccountActivity();
        Id batchId = Database.executeBatch(BLTA);
    }
}