unpackaged/main/default/objects/Account/fields/Apellidomaterno_cta__c.field-meta.xml
<CustomField>
    <fullName>Apellidomaterno_cta__c</fullName>
    <label>Apellido Materno</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Apellidopaterno_cta__c.field-meta.xml
<CustomField>
    <fullName>Apellidopaterno_cta__c</fullName>
    <label>Apellido Paterno</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Estatus__c.field-meta.xml
<CustomField>
    <fullName>Estatus__c</fullName>
    <description>Campos informativo, viaja a través de la interfaz, si es una cuenta nueva por default “Por Asignar”</description>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Por Asignar</fullName>
            </value>
            <value>
                <fullName>Asignado</fullName>
            </value>
            <value>
                <fullName>Por Reasignar</fullName>
            </value>
            <value>
                <fullName>Baja</fullName>
            </value>
            <value>
                <fullName>Incubadora</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Estatus_Integracion__c.field-meta.xml
<CustomField>
    <fullName>Estatus_Integracion__c</fullName>
    <label>Estatus Integración</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Completada</fullName>
            </value>
            <value>
                <fullName>Incidencia</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/FechaNacimiento__c.field-meta.xml
<CustomField>
    <fullName>FechaNacimiento__c</fullName>
    <label>Fecha de Nacimiento</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/IdMasComercial__c.field-meta.xml
<CustomField>
    <fullName>IdMasComercial__c</fullName>
    <label>IdMasComercial</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Nombre_cta__c.field-meta.xml
<CustomField>
    <fullName>Nombre_cta__c</fullName>
    <label>Nombre2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/NSS__c.field-meta.xml
<CustomField>
    <fullName>NSS__c</fullName>
    <inlineHelpText>Obligatorio en Crédito Infonavit o Cofinavit</inlineHelpText>
    <label>NSS</label>
    <length>11</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Account/fields/NumCliente__c.field-meta.xml
<CustomField>
    <fullName>NumCliente__c</fullName>
    <label>Número de Cliente</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Trigger_Override__c.field-meta.xml
<CustomField>
    <fullName>Trigger_Override__c</fullName>
    <label>Trigger Override</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/ValidationBypassDateTime__c.field-meta.xml
<CustomField>
    <fullName>ValidationBypassDateTime__c</fullName>
    <defaultValue>$System.OriginDateTime</defaultValue>
    <label>ValidationBypassDateTime</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Contacto.recordType-meta.xml
<RecordType>
    <fullName>Contacto</fullName>
    <active>true</active>
    <label>Contacto</label>
</RecordType>

unpackaged/main/default/objects/Account/recordTypes/Prospecto.recordType-meta.xml
<RecordType>
    <fullName>Prospecto</fullName>
    <active>true</active>
    <label>Prospecto</label>
</RecordType>

unpackaged/main/default/objects/Debug_Log__c/Debug_Log__c.object-meta.xml
<CustomObject>
    <label>Debug Log</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Debug Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Debug Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Debug_Log__c/fields/Log_Info__c.field-meta.xml
<CustomField>
    <fullName>Log_Info__c</fullName>
    <label>Log Info</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

unpackaged/main/default/objects/Informe_Siebel__c/Informe_Siebel__c.object-meta.xml
<CustomObject>
    <label>Informe_Siebel</label>
    <nameField>
        <label>Nombre de Informe_M_Comercial</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Informe_Siebel</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Informe_Siebel__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Informe_Siebel</relationshipLabel>
    <relationshipName>Informe_Siebel</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Informe_Siebel__c/fields/Estatus__c.field-meta.xml
<CustomField>
    <fullName>Estatus__c</fullName>
    <label>Estatus</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Informe_Siebel__c/fields/Mensaje__c.field-meta.xml
<CustomField>
    <fullName>Mensaje__c</fullName>
    <label>Mensaje</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Informe_Siebel__c/fields/Nombre_cta__c.field-meta.xml
<CustomField>
    <fullName>Nombre_cta__c</fullName>
    <label>Nombre_cta</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/GuardarMasComercialAsync.cls
global class GuardarMasComercialAsync{
    // @future(callout= true) 
    public static void guardar(List<String> prospectos, String cuenta){
        Id idre = [SELECT Id FROM RecordType WHERE Name = 'Contacto' LIMIT 1].Id;
		Id idre2 = [SELECT Id FROM RecordType WHERE Name = 'Contacto solo lectura' LIMIT 1].Id;
        Id idre3 = [SELECT Id FROM RecordType WHERE Name = 'AFLUENTE PERSONA FISICA' LIMIT 1].Id;
        Id idre4 = [SELECT Id FROM RecordType WHERE Name = 'AFLUENTE PERSONA MORAL' LIMIT 1].Id;
        Boolean errCall = false;

        esbJaverComManageprospecto.ManageProspectoPort wsPro 
            = new esbJaverComManageprospecto.ManageProspectoPort();
        wsPro.timeout_x = 100000;
        List<Informe_Siebel__c> informes = new List<Informe_Siebel__c>();
        
        if(!cuenta.equals('CLASETEST')){
        for(String prospecto : prospectos){
            esbJaverComCommon.CuentaType1 pro = (esbJaverComCommon.CuentaType1) JSON.deserialize(prospecto, esbJaverComCommon.CuentaType1.class);
            
            // debug_log__c dLog = new debug_log__c ();
            // dLog.Log_Info__c = json.serialize(pro);
            // insert dLog;

            esbJaverComCommon.GenericSystemResponseType respues = new esbJaverComCommon.GenericSystemResponseType();
            esbJaverComManageprospectoTypes.UpdateProspectoByUserRs_element 
             fullRS = new esbJaverComManageprospectoTypes.UpdateProspectoByUserRs_element(); 
            esbJaverComManageprospectoTypes.SearchProspectosRs_element 
             respuesta = new esbJaverComManageprospectoTypes.SearchProspectosRs_element();
            Informe_Siebel__c info = new Informe_Siebel__c();
             
           String nombreC = pro.Nombre + ' ' + pro.ApellidoPaterno + ' ' + pro.ApellidoMaterno;  
            List<Account> acclist = new List<Account>();
            Account ac = null;
            system.debug('*** pro.Nombre '+pro.Nombre);
            system.debug('*** pro.ApellidoPaterno '+pro.ApellidoPaterno);
            system.debug('*** pro.ApellidoMaterno '+pro.ApellidoMaterno);
            // try{
            acclist = [SELECT Id, FirstName, Nombre_cta__c, ApellidoMaterno_cta__c, ApellidoPaterno_cta__c, RecordTypeId, NSS__c, FechaNacimiento__c, IdMasComercial__c, Estatus__c 
                       FROM Account WHERE FirstName = :pro.Nombre AND LastName = :pro.ApellidoPaterno AND ApellidoMaterno_cta__c = :pro.ApellidoMaterno ORDER BY CreatedDate Desc LIMIT 1];
            if(acclist != null && acclist.size()>0){
                ac = acclist[0];
            }
            // }catch(Exception e){
                
            // }
            try{
            	fullRS = wsPro.UpdateProspectoByUser1(cuenta, pro);
                system.debug('RESPUESTA '+ fullRS);
                respues = fullRS.SysResponse;
                system.debug ('*** Respuesta servicio: '+respues);
            }
            catch(Exception e){
                info.Name= '' + Date.today();
                info.Nombre_cta__c = nombreC;
                if(ac != null ){
                    info.Cuenta__c = ac.Id;
                }
                info.Estatus__c = '-1';
            	info.Mensaje__c = 'El servicio tardó mucho en responder, intente guardar de nuevo.';
                
                system.debug('ERROR: '+e.getMessage());
                errCall=true;
            }

            if (!errCall && ac!=null) {
                try{
                    system.debug('**** respuesta idCuenta: '+fullRS.IdCuenta);

                    if(ac.IdMasComercial__c == null && fullRS.IdCuenta != null){
                        ac.IdMasComercial__c = fullRS.IdCuenta;
                        ac.Trigger_Override__c = Datetime.now();
                        ac.ValidationBypassDateTime__c = datetime.now();
                        update ac;
                    }
                    // if(ac.NumCliente__c == null && fullRS.NumCliente != null){
                    //     ac.NumCliente__c = fullRS.NumCliente;
                    // }
                }catch(Exception e){
                    system.debug('*** Error update en GuardarMasComercialAsync');
                }

            }

            // try{
                /* Comentado 7/19
                system.debug ('*** llamando a SearchProspectos:');
                system.debug ('*** pro.Nombre:'+pro.Nombre);
                system.debug ('*** pro.ApellidoPaterno:'+pro.ApellidoPaterno);
                system.debug ('*** pro.ApellidoMaterno:'+pro.ApellidoMaterno);
                system.debug ('*** ac.FechaNacimiento__c:'+ac.FechaNacimiento__c);
                String fechaNac = Datetime.newInstance(ac.FechaNacimiento__c.year(), ac.FechaNacimiento__c.month(), ac.FechaNacimiento__c.day()).format('dd/MM/yyyy');
                system.debug ('*** ac.NSS__c:'+ac.NSS__c);
                respuesta = wsPro.SearchProspectos(
                 pro.Nombre.toUpperCase(),
                 pro.ApellidoPaterno.toUpperCase(),
                 pro.ApellidoMaterno.toUpperCase(),
                 fechaNac, // ac.FechaNacimiento__c
                 ac.NSS__c);
                 */
            // }catch(Exception e){
            //     system.debug ('*** error en llamado SearchProspectos');
            // }
            
            /* HMF 7/19
            // try{
                system.debug('*** entro a deslgose de llamado a SearchProspectos');
                esbJaverComCommon.GenericSystemResponseType status = respuesta.SysResponse;
                esbJaverComCommon.CuentaListType cuentas = respuesta.Prospectos;
                List<esbJaverComCommon.CuentaType> cuentas1 = cuentas.Cuenta;
                for(esbJaverComCommon.CuentaType cu : cuentas1){
                    Map<String,String> mapAttribute = new Map<String,String>();
                     
                     for(esbJaverComCommon.DinamicAttributeType da : 
                         pro.DinamicAttributes.Attribute){
                             mapAttribute.put(da.Key, da.Value);
                             system.debug(da.Key + da.Value);
                     }
                    if(respues.Estatus != '-1'){
                        system.debug('*** respues.Estatus <>-1 linea 70');
                        //ac.IdMasComercial__c = mapAttribute.get('idcuenta');
                        ac.Estatus__c = mapAttribute.get('estatusCuenta');
                    }
                }
            // }catch(Exception e){
            //     system.debug('*** ERROR CON RESPUESTA linea 76');
            // }
            Date hoy = Date.today();
            info.Name = '' + hoy;
            info.Nombre_cta__c = nombreC;
            info.Estatus__c = respues.Estatus;
            system.debug('ERROR '+ respues.Estatus);
            if(respues.Message != null){
                info.Mensaje__c = respues.Message;
            }
            system.debug('ERROR '+ respues.Message); //Aqui esta regresando msg de error
            try{
            if(info.Mensaje__c.contains('se ha interrumpido') || info.Mensaje__c.contains('guardar de nuevo')){
                info.Estatus__c = '-1';
            }
            }catch(Exception f){
                if(respues.Estatus == '0'){
                    info.Estatus__c = '0';
                    info.Mensaje__c = 'Registro integrado correctamente.';
                }
                
            }
            if(info.Estatus__c != '-1'){
                ac.Estatus_Integracion__c = 'Completada';
            }else{
                ac.Estatus_Integracion__c = 'Incidencia';
            }
            
            if(info.Estatus__c == '0' && ac.Estatus_Integracion__c == 'Completada'){
                info.Mensaje__c = 'Registro integrado correctamente.';
            }
            */

            recursionCheck.stopRecursion();
            /* HMF 7/19
            if(ac.RecordTypeId != idre && ac.RecordTypeId != idre2 && ac.RecordTypeId != idre3){
            	update ac;
                info.Cuenta__c = ac.Id;
            	informes.add(info);
            }
            
            try{
                esbJaverComManageprospecto.ManageProspectoPort wsPro2
                    = new esbJaverComManageprospecto.ManageProspectoPort();
                string nss = ac.NSS__c!=null ? ac.NSS__c : '';
                String fechaNac2 = Datetime.newInstance(ac.FechaNacimiento__c.year(), ac.FechaNacimiento__c.month(), ac.FechaNacimiento__c.day()).format('dd/MM/yyyy');
                esbJaverComManageprospectoTypes.SearchProspectosRs_element 
                    respuesta2 = wsPro2.SearchProspectos(
                        ac.FirstName, //ac.Nombre_cta__c,
                        ac.ApellidoPaterno_cta__c,
                        ac.ApellidoMaterno_cta__c,
                        fechaNac2,
                        nss);
                for(esbJaverComCommon.CuentaType cu : respuesta2.Prospectos.Cuenta){
                    Map<String,String> mapAttribute = new Map<String,String>();
                    
                    for(esbJaverComCommon.DinamicAttributeType da : 
                        cu.DinamicAttributes.Attribute){
                            mapAttribute.put(da.Key, da.Value);
                        }
                    
                    //ac.IdMasComercial__c = mapAttribute.get('idcuenta');
                }
            }catch(Exception o){
                //ac.IdMasComercial__c = '';
            }
            try{
                if(ac.IdMasComercial__c == null && fullRS.IdCuenta != null){
                    ac.IdMasComercial__c = fullRS.IdCuenta;
                }
                if(ac.NumCliente__c == null && fullRS.NumCliente != null){
                    ac.NumCliente__c = fullRS.NumCliente;
                }
            }catch(Exception e){
                
            }
            update ac;
            */
        }
        }else{
            Integer i = 0;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
        }
        // upsert informes;
    }
}