unpackaged/main/default/objects/Account/fields/Apellidomaterno_cta__c.field-meta.xml
<CustomField>
    <fullName>Apellidomaterno_cta__c</fullName>
    <label>Apellido Materno</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Apellidopaterno_cta__c.field-meta.xml
<CustomField>
    <fullName>Apellidopaterno_cta__c</fullName>
    <label>Apellido Paterno</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/CorreoElectronico__c.field-meta.xml
<CustomField>
    <fullName>CorreoElectronico__c</fullName>
    <label>Correo Electrónico</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/isATC__c.field-meta.xml
<CustomField>
    <fullName>isATC__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isATC</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Nombre_cta__c.field-meta.xml
<CustomField>
    <fullName>Nombre_cta__c</fullName>
    <label>Nombre2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Notaria__c.field-meta.xml
<CustomField>
    <fullName>Notaria__c</fullName>
    <label>Notaría</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Notario__c.field-meta.xml
<CustomField>
    <fullName>Notario__c</fullName>
    <label>Notario</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Numerodecliente__c.field-meta.xml
<CustomField>
    <fullName>Numerodecliente__c</fullName>
    <label>Número de cliente</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/ProductoFinanciero__c.field-meta.xml
<CustomField>
    <fullName>ProductoFinanciero__c</fullName>
    <label>Producto Financiero</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/ReferenciaBancariaCliente__c.field-meta.xml
<CustomField>
    <fullName>ReferenciaBancariaCliente__c</fullName>
    <label>Referencia bancaria cliente</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/TipoCredito__c.field-meta.xml
<CustomField>
    <fullName>TipoCredito__c</fullName>
    <label>Tipo de crédito2</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BANCO - SOFOL</fullName>
            </value>
            <value>
                <fullName>BANJERCITO</fullName>
            </value>
            <value>
                <fullName>CAJA FLORENCIO ROSAS</fullName>
            </value>
            <value>
                <fullName>CONTADO</fullName>
            </value>
            <value>
                <fullName>CONTINGENCIA</fullName>
            </value>
            <value>
                <fullName>FOVISSSTE</fullName>
            </value>
            <value>
                <fullName>INFONAVIT</fullName>
            </value>
            <value>
                <fullName>ISSFAM</fullName>
            </value>
            <value>
                <fullName>ISSSTELEON</fullName>
            </value>
            <value>
                <fullName>SHF/BANCO</fullName>
            </value>
            <value>
                <fullName>PENSIONES</fullName>
            </value>
            <value>
                <fullName>COFINAVIT</fullName>
            </value>
            <value>
                <fullName>BANSEFI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Casos_Residente__c/Casos_Residente__c.object-meta.xml
<CustomObject>
    <label>Caso ATC</label>
    <nameField>
        <displayFormat>CAS-{00000000}</displayFormat>
        <label>Folio</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Casos ATC</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Casos_Residente__c/fields/CasoResidente__c.field-meta.xml
<CustomField>
    <fullName>CasoResidente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Caso Residentes</label>
    <referenceTo>Casos_Residente__c</referenceTo>
    <relationshipName>CasosResidentes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Casos_Residente__c/fields/ContactEmail__c.field-meta.xml
<CustomField>
    <fullName>ContactEmail__c</fullName>
    <label>Email del contacto</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Casos_Residente__c/fields/ContactMobile__c.field-meta.xml
<CustomField>
    <fullName>ContactMobile__c</fullName>
    <label>Teléfono celular del contacto</label>
    <type>Phone</type>
</CustomField>

unpackaged/main/default/objects/Casos_Residente__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Clientes ATC</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Casos ATC</relationshipLabel>
    <relationshipName>Casos_Residentes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Casos_Residente__c/fields/Detalledelreporte__c.field-meta.xml
<CustomField>
    <fullName>Detalledelreporte__c</fullName>
    <label>Detalle del reporte</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Casos_Residente__c/fields/Fecha_Cierre_Cancelacion__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Cierre_Cancelacion__c</fullName>
    <label>Fecha de Cierre/Cancelación</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Casos_Residente__c/fields/Visita__c.field-meta.xml
<CustomField>
    <fullName>Visita__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Visita</label>
    <referenceTo>Visita__c</referenceTo>
    <relationshipName>Casos_Residentes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Casos_Residente__c/fields/ViviendaProceso__c.field-meta.xml
<CustomField>
    <fullName>ViviendaProceso__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Vivienda</label>
    <referenceTo>Inventario__c</referenceTo>
    <relationshipLabel>Casos ATC</relationshipLabel>
    <relationshipName>Casos_ATC</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/Inventario__c.object-meta.xml
<CustomObject>
    <label>Proceso ATC</label>
    <nameField>
        <label>Id Vivienda</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProcesosATC</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Inventario__c/fields/Condominio__c.field-meta.xml
<CustomField>
    <fullName>Condominio__c</fullName>
    <label>Condominio</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Inventarios</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/FechaEntrega__c.field-meta.xml
<CustomField>
    <fullName>FechaEntrega__c</fullName>
    <label>Fecha de Entrega</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/FechaEntregaEsperada__c.field-meta.xml
<CustomField>
    <fullName>FechaEntregaEsperada__c</fullName>
    <label>Fecha de entrega esperada</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Notaria__c.field-meta.xml
<CustomField>
    <fullName>Notaria__c</fullName>
    <label>Notaria</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Notario__c.field-meta.xml
<CustomField>
    <fullName>Notario__c</fullName>
    <label>Notario</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/ProductoFinanciero__c.field-meta.xml
<CustomField>
    <fullName>ProductoFinanciero__c</fullName>
    <label>Producto Financiero</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/ReferenciaBancariaCliente__c.field-meta.xml
<CustomField>
    <fullName>ReferenciaBancariaCliente__c</fullName>
    <label>Referencia Bancaria del cliente</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/TipoCredito__c.field-meta.xml
<CustomField>
    <fullName>TipoCredito__c</fullName>
    <label>Tipo de crédito</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BANCO - SOFOL</fullName>
            </value>
            <value>
                <fullName>BANJERCITO</fullName>
            </value>
            <value>
                <fullName>CAJA FLORENCIO ROSAS</fullName>
            </value>
            <value>
                <fullName>CONTADO</fullName>
            </value>
            <value>
                <fullName>CONTINGENCIA</fullName>
            </value>
            <value>
                <fullName>FOVISSSTE</fullName>
            </value>
            <value>
                <fullName>INFONAVIT</fullName>
            </value>
            <value>
                <fullName>ISSFAM</fullName>
            </value>
            <value>
                <fullName>ISSSTELEON</fullName>
            </value>
            <value>
                <fullName>SHF/BANCO</fullName>
            </value>
            <value>
                <fullName>PENSIONES</fullName>
            </value>
            <value>
                <fullName>COFINAVIT</fullName>
            </value>
            <value>
                <fullName>BANSEFI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Notaria__c/Notaria__c.object-meta.xml
<CustomObject>
    <label>Notaría</label>
    <nameField>
        <label>Notaría</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notarías</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Notaria__c/fields/Notario__c.field-meta.xml
<CustomField>
    <fullName>Notario__c</fullName>
    <label>Notario</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Visita__c/Visita__c.object-meta.xml
<CustomObject>
    <label>Cita/Visita</label>
    <nameField>
        <displayFormat>VIS-{0000}</displayFormat>
        <label>Número de Cita/Visita</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Citas/Visitas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Visita__c/fields/CasoResidente__c.field-meta.xml
<CustomField>
    <fullName>CasoResidente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Caso</label>
    <referenceTo>Casos_Residente__c</referenceTo>
    <relationshipLabel>Citas/Visitas</relationshipLabel>
    <relationshipName>Visitas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Visita__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Visitas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Visita__c/fields/Fechaprogramadadevisita__c.field-meta.xml
<CustomField>
    <fullName>Fechaprogramadadevisita__c</fullName>
    <label>Fecha programada</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Visita__c/fields/Horafindevisita__c.field-meta.xml
<CustomField>
    <fullName>Horafindevisita__c</fullName>
    <label>Hora fin de visita</label>
    <required>true</required>
    <type>Time</type>
</CustomField>

unpackaged/main/default/objects/Visita__c/fields/Horaprogramadadevisita__c.field-meta.xml
<CustomField>
    <fullName>Horaprogramadadevisita__c</fullName>
    <label>Hora programada</label>
    <required>true</required>
    <type>Time</type>
</CustomField>

unpackaged/main/default/objects/Visita__c/fields/Inventario__c.field-meta.xml
<CustomField>
    <fullName>Inventario__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventario</label>
    <referenceTo>Inventario__c</referenceTo>
    <relationshipLabel>Citas/Visitas</relationshipLabel>
    <relationshipName>Visitas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/Test_NewCall.cls
@isTest
public class Test_NewCall {
    static testMethod void validar(){
        Test.startTest();
        
        Inventario__c inventario = new Inventario__c();
        inventario.Condominio__c = 'Condominio';
        inventario.FechaEntregaEsperada__c = System.today();
        inventario.FechaEntrega__c=system.today()-1;
        insert inventario;
        
        Id usuar = [SELECT Id FROM User WHERE Name LIKE 'Admin%' LIMIT 1].ID;
        Id rtATC = [SELECT Id FROM RecordType WHERE Name LIKE 'Clientes ATC%' LIMIT 1].ID;
        
        Account cuenta = new Account();
        cuenta.isATC__c = true;
        cuenta.Numerodecliente__c = 'AA';
        cuenta.Nombre_cta__c = 'PRUEBA';
        cuenta.Apellidopaterno_cta__c = 'PRUEBA';
        cuenta.Apellidomaterno_cta__c = 'PRUEBA';
        cuenta.ProductoFinanciero__c = 'PRUEBA';
        cuenta.TipoCredito__c = 'BANJERCITO';
        cuenta.CorreoElectronico__c = 'prueba@prueba.com';
        cuenta.Notaria__c = 'PRUEBA';
        cuenta.Notario__c = 'PRUEBA';
        cuenta.ReferenciaBancariaCliente__c = 'PRUEBA';
        cuenta.Name = cuenta.Nombre_cta__c + ' ' + cuenta.Apellidopaterno_cta__c + ' ' + cuenta.Apellidomaterno_cta__c;
        cuenta.RecordTypeId = rtATC;
        cuenta.Phone = '88888888';
        insert cuenta;
        inventario.cuenta__c=cuenta.Id;
        update inventario;
        
        Casos_Residente__c caso = new Casos_Residente__c();
        caso.Detalledelreporte__c = 'asdasd';
        caso.Cuenta__c = cuenta.Id;
        caso.ViviendaProceso__c = inventario.Id;
        caso.ContactEmail__c='correo@prueba.com';
        caso.ContactMobile__c='88888888';
        caso.OwnerId = usuar;
        caso.Fecha_Cierre_Cancelacion__c = system.today()-1;
        insert caso;
        
        Visita__c v1 = new Visita__c();
        v1.Fechaprogramadadevisita__c = System.today()+1;
        v1.Horaprogramadadevisita__c = time.newInstance(15, 0, 0, 0);
        v1.Horafindevisita__c = time.newInstance(17, 0, 0, 0);        
        v1.OwnerID = usuar;
        v1.CasoResidente__c = caso.Id;
        insert v1;
        

        Task t = new Task(whatId=cuenta.Id);
        insert t;
        Test.stopTest();
    }
    static testMethod void taskTest(){
        
        GetTask.NewCall();
    }
    
}