unpackaged/main/default/objects/Account/fields/Apellidomaterno_cta__c.field-meta.xml
<CustomField>
    <fullName>Apellidomaterno_cta__c</fullName>
    <label>Apellido Materno</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Apellidopaterno_cta__c.field-meta.xml
<CustomField>
    <fullName>Apellidopaterno_cta__c</fullName>
    <label>Apellido Paterno</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Calle__c.field-meta.xml
<CustomField>
    <fullName>Calle__c</fullName>
    <label>Calle</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Colonia_cta__c.field-meta.xml
<CustomField>
    <fullName>Colonia_cta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Colonia</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Colonia__c.Municipio__c</field>
            <operation>equals</operation>
            <valueField>$Source.Municipiocta__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Colonia__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Edad__c.field-meta.xml
<CustomField>
    <fullName>Edad__c</fullName>
    <formula>IF(ISNULL(FechaNacimiento__c), null, 
			FLOOR((TODAY()-FechaNacimiento__c +1)/365.2425))</formula>
    <label>Edad</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Estado_cta__c.field-meta.xml
<CustomField>
    <fullName>Estado_cta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estado</label>
    <referenceTo>Estado__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/FechaEscrituracion__c.field-meta.xml
<CustomField>
    <fullName>FechaEscrituracion__c</fullName>
    <label>Fecha de Escrituración</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/FechaFormalizacion__c.field-meta.xml
<CustomField>
    <fullName>FechaFormalizacion__c</fullName>
    <label>Fecha de Formalización</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/FechaNacimiento__c.field-meta.xml
<CustomField>
    <fullName>FechaNacimiento__c</fullName>
    <label>Fecha de Nacimiento</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Fraccionamiento_cta__c.field-meta.xml
<CustomField>
    <fullName>Fraccionamiento_cta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fraccionamiento</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>(1 OR 5 OR 2 OR 4 OR 6) AND 3</booleanFilter>
        <filterItems>
            <field>$User.Fraccionamiento_autorizado__c</field>
            <operation>contains</operation>
            <valueField>Fraccionamiento__c.Name</valueField>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>Administrador del sistema</value>
        </filterItems>
        <filterItems>
            <field>Fraccionamiento__c.Activo_frac__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$User.Fraccionamiento_autorizado__c</field>
            <operation>equals</operation>
            <value>TODOS</value>
        </filterItems>
        <filterItems>
            <field>$User.FraccionamientoAutorizados__c</field>
            <operation>contains</operation>
            <valueField>Fraccionamiento__c.Name</valueField>
        </filterItems>
        <filterItems>
            <field>$User.Fraccionamiento_autorizado__c</field>
            <operation>contains</operation>
            <valueField>Fraccionamiento__c.Name</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Fraccionamiento__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Lugar_Nacimiento__c.field-meta.xml
<CustomField>
    <fullName>Lugar_Nacimiento__c</fullName>
    <label>Lugar de Nacimiento</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Nacionalidad__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Lugar_Nacimiento</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Nacionalidad__c.field-meta.xml
<CustomField>
    <fullName>Nacionalidad__c</fullName>
    <label>Nacionalidad</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Nacionalidad</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/NSS__c.field-meta.xml
<CustomField>
    <fullName>NSS__c</fullName>
    <inlineHelpText>Obligatorio en Crédito Infonavit o Cofinavit</inlineHelpText>
    <label>NSS</label>
    <length>11</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Account/fields/NumeroExterior__c.field-meta.xml
<CustomField>
    <fullName>NumeroExterior__c</fullName>
    <label>Numero Exterior</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/NumeroInterior__c.field-meta.xml
<CustomField>
    <fullName>NumeroInterior__c</fullName>
    <label>Numero Interior</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Pais_cta__c.field-meta.xml
<CustomField>
    <fullName>Pais_cta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Atención en los acentos, la información origen los manda con y sin acentos.
México - Mexico</description>
    <label>País</label>
    <referenceTo>Pais__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Consumo_Servicios__c/Consumo_Servicios__c.object-meta.xml
<CustomObject>
    <label>Consumo de servicios</label>
    <nameField>
        <displayFormat>RC-{00000}</displayFormat>
        <label>Nombre de Consumos de servicio</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consumos de servicios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Consumo_Servicios__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Registros_de_consumo_de_servicios</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Consumo_Servicios__c/fields/Nombre_del_servicio__c.field-meta.xml
<CustomField>
    <fullName>Nombre_del_servicio__c</fullName>
    <label>Nombre del servicio</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Consumo_Servicios__c/fields/Proceso_de_Venta__c.field-meta.xml
<CustomField>
    <fullName>Proceso_de_Venta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proceso de Venta</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Opportunity.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Cuenta__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Consumos de servicios</relationshipLabel>
    <relationshipName>Registros_de_consumo_de_servicios</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contract/fields/Edad__c.field-meta.xml
<CustomField>
    <fullName>Edad__c</fullName>
    <formula>Account.Edad__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Edad</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Contract/fields/NSS__c.field-meta.xml
<CustomField>
    <fullName>NSS__c</fullName>
    <formula>Account.NSS__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>NSS</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contract/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proceso de Venta</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Dictaminación</relationshipLabel>
    <relationshipName>Dictaminacion</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Direcciones__c/Direcciones__c.object-meta.xml
<CustomObject>
    <label>Dirección</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Folio</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Direcciones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Direcciones__c/fields/Calle__c.field-meta.xml
<CustomField>
    <fullName>Calle__c</fullName>
    <label>Calle</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Direcciones__c/fields/Contrato__c.field-meta.xml
<CustomField>
    <fullName>Contrato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contrato</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Direcciones</relationshipLabel>
    <relationshipName>Direcciones</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/NSS__c.field-meta.xml
<CustomField>
    <fullName>NSS__c</fullName>
    <formula>Account.NSS__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>NSS</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Plan_de_Venta__c.field-meta.xml
<CustomField>
    <fullName>Plan_de_Venta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plan de Venta</label>
    <referenceTo>Plan_de_Venta__c</referenceTo>
    <relationshipLabel>Procesos de Ventas</relationshipLabel>
    <relationshipName>Procesos_de_Ventas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Vivienda__c.field-meta.xml
<CustomField>
    <fullName>Vivienda__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vivienda</label>
    <referenceTo>Vivienda__c</referenceTo>
    <relationshipLabel>Procesos de Ventas</relationshipLabel>
    <relationshipName>Procesos_de_Ventas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/OpportunityLineItem/fields/Vivienda__c.field-meta.xml
<CustomField>
    <fullName>Vivienda__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Vivienda</label>
    <referenceTo>Vivienda__c</referenceTo>
    <relationshipLabel>Producto de oportunidad</relationshipLabel>
    <relationshipName>Producto_de_oportunidad</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/Plan_de_Venta__c.object-meta.xml
<CustomObject>
    <label>Plan de Venta</label>
    <nameField>
        <displayFormat>Plan de Venta-{000000}</displayFormat>
        <label>Plan de Venta</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plan de Venta</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proceso de Venta</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Plan de Venta</relationshipLabel>
    <relationshipName>Plan_de_Venta</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Plan_de_Venta__c.field-meta.xml
<CustomField>
    <fullName>Plan_de_Venta__c</fullName>
    <formula>&quot;Plan de Venta&quot; &amp; &quot; &quot;&amp;  Oportunidad__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Plan de Venta</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Vivienda__c.field-meta.xml
<CustomField>
    <fullName>Vivienda__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vivienda</label>
    <referenceTo>Vivienda__c</referenceTo>
    <relationshipLabel>Plan de Venta</relationshipLabel>
    <relationshipName>Plan_de_Venta</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Referencia_familiar__c/Referencia_familiar__c.object-meta.xml
<CustomObject>
    <label>Referencia Familiar</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Folio</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referencias Familiares</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Referencia_familiar__c/fields/Contrato__c.field-meta.xml
<CustomField>
    <fullName>Contrato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contrato</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Referencias Familiares</relationshipLabel>
    <relationshipName>Referencias_Familiares</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Referencia_familiar__c/fields/Proceso_de_Venta__c.field-meta.xml
<CustomField>
    <fullName>Proceso_de_Venta__c</fullName>
    <formula>Dictaminacion__r.Oportunidad__r.Numero_Proceso_de_Venta__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Proceso</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/globalValueSets/Lugar_Nacimiento.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AGUASCALIENTES</fullName>
    </customValue>
    <customValue>
        <fullName>BAJA CALIFORNIA</fullName>
    </customValue>
    <customValue>
        <fullName>BAJA CALIFORNIA SUR</fullName>
    </customValue>
    <customValue>
        <fullName>CAMPECHE</fullName>
    </customValue>
    <customValue>
        <fullName>CHIAPAS</fullName>
    </customValue>
    <customValue>
        <fullName>CHIHUAHUA</fullName>
    </customValue>
    <customValue>
        <fullName>CIUDAD DE MEXICO</fullName>
    </customValue>
    <customValue>
        <fullName>COAHUILA</fullName>
    </customValue>
    <customValue>
        <fullName>COLIMA</fullName>
    </customValue>
    <customValue>
        <fullName>DURANGO</fullName>
    </customValue>
    <customValue>
        <fullName>ESTADO DE MEXICO</fullName>
    </customValue>
    <customValue>
        <fullName>EXTRANJERO</fullName>
    </customValue>
    <customValue>
        <fullName>GUANAJUATO</fullName>
    </customValue>
    <customValue>
        <fullName>GUERRERO</fullName>
    </customValue>
    <customValue>
        <fullName>HIDALGO</fullName>
    </customValue>
    <customValue>
        <fullName>JALISCO</fullName>
    </customValue>
    <customValue>
        <fullName>MICHOACAN</fullName>
    </customValue>
    <customValue>
        <fullName>MORELOS</fullName>
    </customValue>
    <customValue>
        <fullName>NAYARIT</fullName>
    </customValue>
    <customValue>
        <fullName>NUEVO LEON</fullName>
    </customValue>
    <customValue>
        <fullName>OAXACA</fullName>
    </customValue>
    <customValue>
        <fullName>PUEBLA</fullName>
    </customValue>
    <customValue>
        <fullName>QUERETARO</fullName>
    </customValue>
    <customValue>
        <fullName>QUINTANA ROO</fullName>
    </customValue>
    <customValue>
        <fullName>SAN LUIS POTOSI</fullName>
    </customValue>
    <customValue>
        <fullName>SINALOA</fullName>
    </customValue>
    <customValue>
        <fullName>SONORA</fullName>
    </customValue>
    <customValue>
        <fullName>TABASCO</fullName>
    </customValue>
    <customValue>
        <fullName>TAMAULIPAS</fullName>
    </customValue>
    <customValue>
        <fullName>TLAXCALA</fullName>
    </customValue>
    <masterLabel>Lugar de Nacimiento</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Nacionalidad.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>MEXICANA</fullName>
        <default>true</default>
        <label>MEXICANA</label>
    </customValue>
    <customValue>
        <fullName>ABJASIA</fullName>
    </customValue>
    <customValue>
        <fullName>ACROTIRENSE</fullName>
    </customValue>
    <customValue>
        <fullName>AFGANA</fullName>
    </customValue>
    <customValue>
        <fullName>ALBANESA</fullName>
    </customValue>
    <customValue>
        <fullName>ALEMANA</fullName>
    </customValue>
    <customValue>
        <fullName>ANDORRANA</fullName>
    </customValue>
    <customValue>
        <fullName>ANGOLEÑA</fullName>
    </customValue>
    <customValue>
        <fullName>ANGUILENSE</fullName>
    </customValue>
    <customValue>
        <fullName>ANTIGUANA</fullName>
    </customValue>
    <customValue>
        <fullName>ARGELINA</fullName>
    </customValue>
    <customValue>
        <fullName>ARGENTINA</fullName>
    </customValue>
    <customValue>
        <fullName>ARMENIA</fullName>
    </customValue>
    <customValue>
        <fullName>ARTSAJI</fullName>
    </customValue>
    <customValue>
        <fullName>ARUBEÑA</fullName>
    </customValue>
    <customValue>
        <fullName>AUSTRALIANA</fullName>
    </customValue>
    <customValue>
        <fullName>AUSTRIACA</fullName>
    </customValue>
    <customValue>
        <fullName>AZERBAIYANA</fullName>
    </customValue>
    <customValue>
        <fullName>BAHAMEÑA</fullName>
    </customValue>
    <customValue>
        <fullName>BANGLADESI</fullName>
    </customValue>
    <customValue>
        <fullName>BARBADENSE</fullName>
    </customValue>
    <customValue>
        <fullName>BAREINI</fullName>
    </customValue>
    <customValue>
        <fullName>BELGA</fullName>
    </customValue>
    <customValue>
        <fullName>BELICEÑA</fullName>
    </customValue>
    <customValue>
        <fullName>BENINESA</fullName>
    </customValue>
    <customValue>
        <fullName>BERMUDEÑA</fullName>
    </customValue>
    <customValue>
        <fullName>BIELORRUSA</fullName>
    </customValue>
    <customValue>
        <fullName>BIRMANA</fullName>
    </customValue>
    <customValue>
        <fullName>BOLIVIANA</fullName>
    </customValue>
    <customValue>
        <fullName>BOSNIA</fullName>
    </customValue>
    <masterLabel>Nacionalidad</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/CLASS_EBS_Cuentas.cls
/**
 * @description       : 
 * @author            : Jose V. Aguilar Tlaseca
 * @group             : 
 * @last modified on  : 2023-06-12
 * @last modified by  : Jose V. Aguilar Tlaseca
**/
public without sharing class CLASS_EBS_Cuentas {
	
    @InvocableMethod(label='Consume EBS Service Accounts by OPP' description='' category='Opportunity')
  	public static List<Output> getAccountNames(List<Input> datos) {
    	
        Integer requisicionCrm = datos.get(0).requisicion;
        List<Output> lstRespuestas = new List<Output>();
		Request lstData = new Request();
		List<Output> lstOutputs = new List<Output>();
		Savepoint sp = Database.setSavepoint();
		
        
        lstData = generaDatos(datos.get(0).identificadores, datos.get(0).requisicion);

		if(lstData != null){
			Output out = new Output();

			String payload = JSON.serialize(lstData);

			System.debug('https://qesb.javer.com.mx:11962/services/EBS/ClientesSfCRMtoERPReq/rest REQUEST: ' + payload);
			
			Try{
        	
            HttpRequest request = new HttpRequest();
     		request.setEndpoint('https://qesb.javer.com.mx:11962/services/EBS/ClientesSfCRMtoERPReq/rest');
     		request.setMethod('POST');
            request.setBody(payload);
			request.setTimeout(120000);
			
            
            Http http = new Http();
     		HTTPResponse res = http.send(request);
            Response resp = new Response();
            resp = (Response) JSON.deserialize(res.getBody(), Response.CLASS);
     		System.debug(res.getBody());
            
            out.codigoRespuesta = 0;
            out.MensajeRespuesta = 'Success';
    		lstOutputs.add(out);
            
        	}catch(Exception e){
            	out.codigoRespuesta = 1;
            	out.MensajeRespuesta = 'Error: ' + e.getMessage();
            	lstOutputs.add(out);    
        	}
		}
		
        
        return lstRespuestas; 
  	}


	  private Static Request generaDatos(List<String> idsRegistros, Integer requisicionCrm){ //private Static List<Request> generaDatos(List<String> idsRegistros, Integer requisicionCrm){ 
		
		Request lstData = new Request(); //List<Request> lstData = new List<Request>(); 
		
		//try{

			//Obtenemos los registros necesarios
        	
            //---Direcciones
        	DescribeSObjectResult describeResultDir = Direcciones__c.getSObjectType().getDescribe();	
			List<String> fieldNamesDir = new List<String>( describeResultDir.fields.getMap().keySet() );
        	String queryDir =' SELECT ' + String.join( fieldNamesDir, ',' ) + ' FROM ' + describeResultDir.getName() + ' WHERE ' + ' id IN :idsRegistros ';
        	List<Direcciones__c> lstDir = Database.query( queryDir );
            
        	//---Opportunidades
        	DescribeSObjectResult describeResultOpp = Opportunity.getSObjectType().getDescribe();	
			List<String> fieldNamesOpp = new List<String>( describeResultOpp.fields.getMap().keySet() );
        	String queryOpp =' SELECT ' + String.join( fieldNamesOpp, ',' ) + ' FROM ' + describeResultOpp.getName() + ' WHERE ' + ' id IN :idsRegistros ';
        	List<Opportunity> lstOpp = Database.query( queryOpp );
        
        	//---Dictaminaciones
        	DescribeSObjectResult describeResultContract = Contract.getSObjectType().getDescribe();	
			List<String> fieldNamesContract = new List<String>( describeResultContract.fields.getMap().keySet() );
        	String queryContr =' SELECT ' + String.join( fieldNamesContract, ',' ) + ' FROM ' + describeResultContract.getName() + ' WHERE ' + ' Oportunidad__c IN :idsRegistros ';
        	List<Contract> lstContract = Database.query( queryContr );
        
        	//---Planes de venta
        	DescribeSObjectResult describeResultPlanVenta = Plan_de_Venta__c.getSObjectType().getDescribe();	
			List<String> fieldNamesPlanVenta = new List<String>( describeResultPlanVenta.fields.getMap().keySet() );
        	String queryPlanVenta =' SELECT ' + String.join( fieldNamesPlanVenta, ',' ) + ' FROM ' + describeResultPlanVenta.getName() + ' WHERE ' + ' Oportunidad__c IN :idsRegistros ';
        	List<Plan_de_Venta__c> lstPlanesVenta = Database.query( queryPlanVenta );
        
        	//---Cuentas
        	set<String> idsCuentas = new set<String>();
        	for(Opportunity oppTemp : lstOpp){idsCuentas.add(oppTemp.AccountId);}
        	DescribeSObjectResult describeAccount = Account.getSObjectType().getDescribe();	
			List<String> fieldAccount = new List<String>( describeAccount.fields.getMap().keySet() );
        	String queryAccount =' SELECT ' + String.join( fieldAccount, ',' ) + ' FROM ' + describeAccount.getName() + ' WHERE ' + ' Id IN :idsCuentas ';
        	List<Account> lstAccounts = Database.query( queryAccount );

			//---Referencias
			set<String> idsDictaminaciones = new set<String>();
        	for(Contract contr : lstContract){idsDictaminaciones.add(contr.Id);}
        	DescribeSObjectResult describeRefer = Referencia_familiar__c.getSObjectType().getDescribe();	
			List<String> fieldRefer = new List<String>( describeRefer.fields.getMap().keySet() );
        	String queryRefer =' SELECT Contrato__r.Oportunidad__c, ' + String.join( fieldRefer, ',' ) + ' FROM ' + describeRefer.getName() + ' WHERE ' + ' Contrato__c IN :idsDictaminaciones ';
        	List<Referencia_familiar__c> lstReferencias = Database.query( queryRefer );

			//---ProductosOportunidad
			DescribeSObjectResult describeProdOpp = OpportunityLineItem.getSObjectType().getDescribe();	
			List<String> fieldProdOpp = new List<String>( describeProdOpp.fields.getMap().keySet() );
        	String queryProdOpp =' SELECT ' + String.join( fieldProdOpp, ',' ) + ' FROM ' + describeProdOpp.getName() + ' WHERE ' + ' OpportunityId IN :idsRegistros ';
        	List<OpportunityLineItem> lstProdOpp = Database.query( queryProdOpp );

			//---Viviendas
			set<String> idsViviendas = new set<String>();
        	for(OpportunityLineItem oppLin : lstProdOpp){idsViviendas.add(oppLin.Vivienda__c);}
        	DescribeSObjectResult describeViv = Vivienda__c.getSObjectType().getDescribe();	
			List<String> fieldViv = new List<String>( describeViv.fields.getMap().keySet() );
        	String queryViv =' SELECT ' + String.join( fieldViv, ',' ) + ' FROM ' + describeViv.getName() + ' WHERE ' + ' Id IN :idsViviendas ';
        	List<Vivienda__c> lstViv = Database.query( queryViv );


			//Generamos mapas de la informacion acomodada por id de la oportunidad a excepcion de la cuenta que esa es por id
        	Map<String,Contract> mapDictaminaciones = new Map<String,Contract>();
        	for(Contract cont : lstContract){
				mapDictaminaciones.put(cont.Oportunidad__c, cont);  
        	}
        
        	Map<String,List<Plan_de_Venta__c>> mapPlanesVenta = new Map<String,List<Plan_de_Venta__c>>();
    		for(Plan_de_Venta__c planVent : lstPlanesVenta){
            	if(!mapPlanesVenta.containsKey(planVent.Oportunidad__c)){
            		List<Plan_de_Venta__c> lstPlanVenta = new List<Plan_de_Venta__c>();
                	lstPlanVenta.add(planVent);
                	mapPlanesVenta.put(planVent.Oportunidad__c, lstPlanVenta);
            	}else{
                	List<Plan_de_Venta__c> lstPlanVenta = mapPlanesVenta.get(planVent.Oportunidad__c);
                	lstPlanVenta.add(planVent);
                	mapPlanesVenta.put(planVent.Oportunidad__c, lstPlanVenta);
            	}   
        	}
        
        	Map<String,Account> mapAccounts = new Map<String,Account>();
    		for(Account aco : lstAccounts){
            	mapAccounts.put(aco.Id, aco); 
        	}


			Map<String,List<Referencia_familiar__c>> mapReferencias = new Map<String,List<Referencia_familiar__c>>();
			if( null != lstReferencias && !lstReferencias.isEmpty()){
				for(Referencia_familiar__c ref : lstReferencias){
					if(!mapReferencias.containsKey(ref.Contrato__c)){
            			List<Referencia_familiar__c> lstRefTemp = new List<Referencia_familiar__c>();
                		lstRefTemp.add(ref);
                		mapReferencias.put(ref.Contrato__c, lstRefTemp);
            		}else{
                		List<Referencia_familiar__c> lstRefTemp = mapReferencias.get(ref.Contrato__c);
                		lstRefTemp.add(ref);
                		mapReferencias.put(ref.Contrato__c, lstRefTemp);
            		} 
				}
			}


			Map<String,List<OpportunityLineItem>> mapProdOpp = new Map<String,List<OpportunityLineItem>>();
			if( null != lstProdOpp && !lstProdOpp.isEmpty()){
				for(OpportunityLineItem prodOpp : lstProdOpp){
					if(!mapProdOpp.containsKey(prodOpp.OpportunityId)){
            			List<OpportunityLineItem> lstOppTemp = new List<OpportunityLineItem>();
                		lstOppTemp.add(prodOpp);
                		mapProdOpp.put(prodOpp.OpportunityId, lstOppTemp);
            		}else{
                		List<OpportunityLineItem> lstOppTemp = mapProdOpp.get(prodOpp.OpportunityId);
                		lstOppTemp.add(prodOpp);
                		mapProdOpp.put(prodOpp.OpportunityId, lstOppTemp);
            		} 
				}
			}

			Map<String,Vivienda__c> mapViviendas = new Map<String,Vivienda__c>();
			if( null != lstViv && !lstViv.isEmpty()){
				for(Vivienda__c viv : lstViv){
					mapViviendas.put(viv.Id, viv); 
				}
			}

			//Recorremos la lista de los procesos de venta a tratar y generamos los registros a mandar en la peticion
			List<Consumo_Servicios__c> lstConsumos = new List<Consumo_Servicios__c>();
			Map<String,Consumo_Servicios__c> mapConsumos = new Map<String,Consumo_Servicios__c>();
			for( Opportunity oppCon : lstOpp){
				Consumo_Servicios__c consumo = new Consumo_Servicios__c();
				consumo.Cuenta__c = oppCon.AccountId;
				consumo.Nombre_del_servicio__c = 'GDS_Cuentas';
				consumo.Proceso_de_Venta__c = oppCon.Id;
				mapConsumos.put(oppCon.Id, consumo);
			}

			insert mapConsumos.Values();

        	for( Opportunity opp : lstOpp){
            	
                Data data = new Data();
                
                //Datos de cuenta
            	data.ApellidoMaterno 			= mapAccounts.get(opp.AccountId).Apellidomaterno_cta__c != null ? mapAccounts.get(opp.AccountId).Apellidomaterno_cta__c : '' ;
            	data.ApellidoPaterno 			= mapAccounts.get(opp.AccountId).Apellidopaterno_cta__c != null ? mapAccounts.get(opp.AccountId).Apellidopaterno_cta__c : '' ;
            	data.Calle 						= mapAccounts.get(opp.AccountId).Calle__c != null ? mapAccounts.get(opp.AccountId).Calle__c : '' ;
            	data.Ciudad 					= mapAccounts.get(opp.AccountId).BillingCity != null ? mapAccounts.get(opp.AccountId).BillingCity : '' ;
            	data.CodigoPosta 				= mapAccounts.get(opp.AccountId).BillingPostalCode != null ? Integer.valueOf(mapAccounts.get(opp.AccountId).BillingPostalCode) : null ;
            	data.Colonia 					= mapAccounts.get(opp.AccountId).Colonia_cta__c != null ? mapAccounts.get(opp.AccountId).Colonia_cta__c : null ;
		    	data.Created 					= mapAccounts.get(opp.AccountId).CreatedDate != null ? Date.valueOf(mapAccounts.get(opp.AccountId).CreatedDate) : null ;
            	data.CreatedBy 					= mapAccounts.get(opp.AccountId).CreatedById != null ? mapAccounts.get(opp.AccountId).CreatedById : null ;
           		data.Curp 						= mapAccounts.get(opp.AccountId).CURP__c != null ? mapAccounts.get(opp.AccountId).CURP__c : '' ;
					String domicilioFiscal      = String.valueOf
					(
						mapAccounts.get(opp.AccountId).BillingStreet != null ? mapAccounts.get(opp.AccountId).BillingStreet : '' + ', ' + (mapAccounts.get(opp.AccountId).BillingCity != null ? mapAccounts.get(opp.AccountId).BillingCity : '') + ', ' + (mapAccounts.get(opp.AccountId).BillingState != null ? mapAccounts.get(opp.AccountId).BillingState : '') + ', ' + (mapAccounts.get(opp.AccountId).BillingPostalCode != null ? mapAccounts.get(opp.AccountId).BillingPostalCode : '') + ', ' + (mapAccounts.get(opp.AccountId).BillingCountry != null ? mapAccounts.get(opp.AccountId).BillingCountry : '')
					);

            	data.DomicilioOficial 			= domicilioFiscal;
            	data.EDAD 						= mapAccounts.get(opp.AccountId).Edad__c != null ? String.valueOf(mapAccounts.get(opp.AccountId).Edad__c) : '' ;
            	data.Estado 					= mapAccounts.get(opp.AccountId).Estado_cta__c != null ? mapAccounts.get(opp.AccountId).Estado_cta__c : null ;
            	data.FechaNacimiento	 		= mapAccounts.get(opp.AccountId).FechaNacimiento__c != null ? String.valueOf(mapAccounts.get(opp.AccountId).FechaNacimiento__c) : null ;
		    	data.FechaEscrituracion 		= mapAccounts.get(opp.AccountId).FechaEscrituracion__c != null ? mapAccounts.get(opp.AccountId).FechaEscrituracion__c : null ;
		    	data.FechaFormalizacion 		= mapAccounts.get(opp.AccountId).FechaFormalizacion__c != null ? mapAccounts.get(opp.AccountId).FechaFormalizacion__c : null ;
            	data.Fraccionamiento 			= mapAccounts.get(opp.AccountId).Fraccionamiento_cta__c != null ? mapAccounts.get(opp.AccountId).Fraccionamiento_cta__c : '' ;
            	data.IdClienteCrm				= mapAccounts.get(opp.AccountId).Id != null ? mapAccounts.get(opp.AccountId).Id : '' ;
				data.LugarNacimiento	 		= mapAccounts.get(opp.AccountId).Lugar_Nacimiento__c != null ? mapAccounts.get(opp.AccountId).Lugar_Nacimiento__c : '' ;
            	data.Nacionalidad 				= mapAccounts.get(opp.AccountId).Nacionalidad__c != null ? mapAccounts.get(opp.AccountId).Nacionalidad__c : '' ;
            	data.Nombre 					= mapAccounts.get(opp.AccountId).FirstName != null ? mapAccounts.get(opp.AccountId).FirstName : '' ;
            	data.Nombre_Cliente 			= mapAccounts.get(opp.AccountId).Name != null ? mapAccounts.get(opp.AccountId).Name : '' ;
            	data.Nss 						= mapAccounts.get(opp.AccountId).NSS__c != null ? mapAccounts.get(opp.AccountId).NSS__c : '' ;
            	data.NumProcesoAr 				= opp.Name != null ? opp.Name : '' ;
            	data.NumeroDomicilio	 		= mapAccounts.get(opp.AccountId).NumeroExterior__c != null ? mapAccounts.get(opp.AccountId).NumeroExterior__c : '' ;
            	data.NumeroInterno 				= mapAccounts.get(opp.AccountId).NumeroInterior__c != null ? mapAccounts.get(opp.AccountId).NumeroInterior__c : '' ;
            	data.Pais 						= mapAccounts.get(opp.AccountId).Pais_cta__c != null ? mapAccounts.get(opp.AccountId).Pais_cta__c : null ;
            	data.Prototipo 					= mapAccounts.get(opp.AccountId).Prototipo_lookup__c != null ? mapAccounts.get(opp.AccountId).Prototipo_lookup__c : '' ;
            	data.ReferenciaBancaria 		= mapAccounts.get(opp.AccountId).ReferenciaBancariaCliente__c != null ? mapAccounts.get(opp.AccountId).ReferenciaBancariaCliente__c : '' ;
            	data.RequisicionCrm	 			= String.valueOf(requisicionCrm) != null ? String.valueOf(requisicionCrm) : '' ;
            	data.Rfc 						= mapAccounts.get(opp.AccountId).RFC_Completo__c != null ? mapAccounts.get(opp.AccountId).RFC_Completo__c : '' ;
            	data.Sexo 						= mapAccounts.get(opp.AccountId).Sexo__c != null ? mapAccounts.get(opp.AccountId).Sexo__c : '' ;
            	data.TelefonoCelular	 		= mapAccounts.get(opp.AccountId).TelefonoCelular__c != null ? mapAccounts.get(opp.AccountId).TelefonoCelular__c : '' ;
            	data.TelefonoParticular 		= mapAccounts.get(opp.AccountId).TelefonoCelular__c != null ? mapAccounts.get(opp.AccountId).TelefonoCelular__c : '' ;
            	data.TelefonoRefOtro1 			= mapAccounts.get(opp.AccountId).TelefonoOtro__c != null ? mapAccounts.get(opp.AccountId).TelefonoOtro__c : '' ;
            	data.TelefonoRefOtro2 			= mapAccounts.get(opp.AccountId).TelefonoTrabajo__c != null ? mapAccounts.get(opp.AccountId).TelefonoTrabajo__c : '' ;
            	data.TipoCredito				= mapAccounts.get(opp.AccountId).Tipo_Credito__c != null ? mapAccounts.get(opp.AccountId).Tipo_Credito__c : '' ;
            	data.Uen 						= mapAccounts.get(opp.AccountId).UEN__c != null ? mapAccounts.get(opp.AccountId).UEN__c : '' ;
            	data.LastUpd 					= mapAccounts.get(opp.AccountId).LastModifiedDate != null ? Date.valueOf(mapAccounts.get(opp.AccountId).LastModifiedDate) : null ;
		    	data.LastUpdBy	 				= String.valueOf(mapAccounts.get(opp.AccountId).LastModifiedById) != null ? String.valueOf(mapAccounts.get(opp.AccountId).LastModifiedById) : null ;
            	data.DbLastUpd	 				= null;
            	data.DbLastUpdSrc 				= '';
            	data.Fideicomiso 				= String.valueOf(mapDictaminaciones.get(opp.Id).Cliente_Fideicomiso__c) != null ? String.valueOf(mapDictaminaciones.get(opp.Id).Cliente_Fideicomiso__c) : '' ;
            	data.IdInterfase	 			= '';
            	data.IdInterfaseCrm	 			= mapConsumos.get(opp.Id).Id != null ? mapConsumos.get(opp.Id).Id : '' ;
            	data.IdPago 					= '';
            	data.IndExigible 				= 0;
            	data.Interior 					= mapViviendas.get(mapProdOpp.get(opp.Id)[0].Vivienda__c).Num_Interior__c != null ? mapViviendas.get(mapProdOpp.get(opp.Id)[0].Vivienda__c).Num_Interior__c : '' ;
            	data.Lote 						= mapViviendas.get(mapProdOpp.get(opp.Id)[0].Vivienda__c).Lote__c != null ? mapViviendas.get(mapProdOpp.get(opp.Id)[0].Vivienda__c).Lote__c : '' ;
            	data.Manzana					= mapViviendas.get(mapProdOpp.get(opp.Id)[0].Vivienda__c).Manzana__c != null ? mapViviendas.get(mapProdOpp.get(opp.Id)[0].Vivienda__c).Manzana__c : '' ;
		    	data.MetrosTerrenoExcedente		= mapViviendas.get(mapProdOpp.get(opp.Id)[0].Vivienda__c).Excendente_M2__c != null ? mapViviendas.get(mapProdOpp.get(opp.Id)[0].Vivienda__c).Excendente_M2__c : null ;
            	data.NombreReferencia1 			= mapReferencias.get(mapDictaminaciones.get(opp.Id).Id)[0].Nombre__c != null ? mapReferencias.get(mapDictaminaciones.get(opp.Id).Id)[0].Nombre__c : '' ;
            	data.NombreReferencia2 			= mapReferencias.get(mapDictaminaciones.get(opp.Id).Id)[1].Nombre__c != null ? mapReferencias.get(mapDictaminaciones.get(opp.Id).Id)[1].Nombre__c : '' ;
            	data.NombreReferencia3 			= mapReferencias.get(mapDictaminaciones.get(opp.Id).Id)[2].Nombre__c != null ? mapReferencias.get(mapDictaminaciones.get(opp.Id).Id)[2].Nombre__c : '' ;
            	data.RowId 						= '';
            	data.TelefonoRefOtro3 			= '';
            	data.TelefonoReferencia1		= mapReferencias.get(mapDictaminaciones.get(opp.Id).Id)[0].Telefono_1__c != null ? mapReferencias.get(mapDictaminaciones.get(opp.Id).Id)[0].Telefono_1__c : '' ;
            	data.TelefonoReferencia2		= mapReferencias.get(mapDictaminaciones.get(opp.Id).Id)[1].Telefono_1__c != null ? mapReferencias.get(mapDictaminaciones.get(opp.Id).Id)[1].Telefono_1__c : '' ;
            	data.TelefonoReferencia3		= mapReferencias.get(mapDictaminaciones.get(opp.Id).Id)[2].Telefono_1__c != null ? mapReferencias.get(mapDictaminaciones.get(opp.Id).Id)[2].Telefono_1__c : '' ;
            	data.TipoLote		 			= '';
            	data.IdClienteAr	 			= '';
            	data.IdProcesoAr 				= 0;
            	data.MensajeApi 				= '';
            	data.RespuestaApi 				= '';

				lstData.InsClientesSfCRMtoERP = data;
                //lstData.add(data);
        	}

		/*}catch(Exception e){
			System.debug('Error: ' + e.getMessage());
		}*/
	
		return lstData; 
	}
    
    
	public class Data {
        String ApellidoMaterno 				{get;set;}
        String ApellidoPaterno 				{get;set;}
        String Calle 						{get;set;}
        String Ciudad 						{get;set;}
        Integer CodigoPosta 				{get;set;}
        String Colonia 						{get;set;}
		Date Created 						{get;set;}
        String CreatedBy 					{get;set;}
        String Curp 						{get;set;}
		Date DbLastUpd	 					{get;set;}
        String DbLastUpdSrc 				{get;set;}
        String DomicilioOficial 			{get;set;}
        String EDAD 						{get;set;}
        String Estado 						{get;set;}
        String FechaNacimiento	 			{get;set;}
		Date FechaEscrituracion 			{get;set;}
		Date FechaFormalizacion 			{get;set;}
        String Fideicomiso 					{get;set;}
        String Fraccionamiento 				{get;set;}
        String IdClienteCrm		 			{get;set;}
        String IdInterfase	 				{get;set;}
        String IdInterfaseCrm	 			{get;set;}
        String IdPago 						{get;set;}
        Integer IndExigible 				{get;set;}
        String Interior 					{get;set;}
        String Lote 						{get;set;}
        String LugarNacimiento	 			{get;set;}
        String Manzana					 	{get;set;}
		Decimal MetrosTerrenoExcedente	 	{get;set;}
        String Nacionalidad 				{get;set;}
        String Nombre 						{get;set;}
        String Nombre_Cliente 				{get;set;}
        String NombreReferencia1 			{get;set;}
        String NombreReferencia2 			{get;set;}
        String NombreReferencia3 			{get;set;}
        String Nss 							{get;set;}
        String NumProcesoAr 				{get;set;}
        String NumeroDomicilio	 			{get;set;}
        String NumeroInterno 				{get;set;}
        String Pais 						{get;set;}
        String Prototipo 					{get;set;}
        String ReferenciaBancaria 			{get;set;}
        String RequisicionCrm	 			{get;set;}
        String Rfc 							{get;set;}
        String RowId 						{get;set;}
        String Sexo 						{get;set;}
        String TelefonoCelular	 			{get;set;}
        String TelefonoParticular 			{get;set;}
        String TelefonoRefOtro1 			{get;set;}
        String TelefonoRefOtro2 			{get;set;}
        String TelefonoRefOtro3 			{get;set;}
        String TelefonoReferencia1	 		{get;set;}
        String TelefonoReferencia2	 		{get;set;}
        String TelefonoReferencia3		 	{get;set;}
        String TipoCredito				 	{get;set;}
        String TipoLote		 				{get;set;}
        String Uen 							{get;set;}
        String IdClienteAr	 				{get;set;}
        Integer IdProcesoAr 				{get;set;}
		DATE LastUpd 						{get;set;}
		String LastUpdBy	 				{get;set;}
        String MensajeApi 					{get;set;}
        String RespuestaApi 				{get;set;}
  	}
    
    public class Request {
		String something {get;set;}
        Data InsClientesSfCRMtoERP 	{get;set;}
  	}
    
    public class Response {
        String MensajeApi 		{get;set;}
        String RespuestaApi 	{get;set;}
        Integer IdClienteAr 	{get;set;}
        Integer IdProcesoAr 	{get;set;}
        
  	}
    
    public class Input {
  		@InvocableVariable(label='Requisición CRM' description='' required=true)
  		public Integer requisicion;
        
        @InvocableVariable(label='Identificadores' description='' required=true)
  		public List<String> identificadores;
  	}
    
    public class Output {
  		@InvocableVariable(label='Código e respuesta' description='' required=true)
  		public Integer codigoRespuesta;
        
        @InvocableVariable(label='Mensaje respeusta' description='' required=true)
  		public String MensajeRespuesta;
  	}
    
}