unpackaged/main/default/objects/Account/fields/Apellidomaterno_cta__c.field-meta.xml
<CustomField>
    <fullName>Apellidomaterno_cta__c</fullName>
    <label>Apellido Materno</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Canal_de_Venta__c.field-meta.xml
<CustomField>
    <fullName>Canal_de_Venta__c</fullName>
    <label>Canal de Venta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Canal_de_Venta</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/CorreoElectronico__c.field-meta.xml
<CustomField>
    <fullName>CorreoElectronico__c</fullName>
    <label>Correo Electrónico</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Estatus_Lista_Negra_QEQ__c.field-meta.xml
<CustomField>
    <fullName>Estatus_Lista_Negra_QEQ__c</fullName>
    <label>Estatus Lista Negra</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SIN VALIDAR</fullName>
                <default>true</default>
                <label>SIN VALIDAR</label>
            </value>
            <value>
                <fullName>LISTA NEGRA</fullName>
            </value>
            <value>
                <fullName>LN CONFIRMADO</fullName>
            </value>
            <value>
                <fullName>VALIDADO</fullName>
            </value>
            <value>
                <fullName>PPE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/isATC__c.field-meta.xml
<CustomField>
    <fullName>isATC__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isATC</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Nombre_cta__c.field-meta.xml
<CustomField>
    <fullName>Nombre_cta__c</fullName>
    <label>Nombre2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Notaria__c.field-meta.xml
<CustomField>
    <fullName>Notaria__c</fullName>
    <label>Notaría</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Notario__c.field-meta.xml
<CustomField>
    <fullName>Notario__c</fullName>
    <label>Notario</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Numerodecliente__c.field-meta.xml
<CustomField>
    <fullName>Numerodecliente__c</fullName>
    <label>Número de cliente</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Otro_Telefono__c.field-meta.xml
<CustomField>
    <fullName>Otro_Telefono__c</fullName>
    <label>Otro Teléfono</label>
    <type>Phone</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/TelefonoCelular__c.field-meta.xml
<CustomField>
    <fullName>TelefonoCelular__c</fullName>
    <label>Teléfono Celular</label>
    <type>Phone</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Prospecto.recordType-meta.xml
<RecordType>
    <fullName>Prospecto</fullName>
    <active>true</active>
    <label>Prospecto</label>
</RecordType>

unpackaged/main/default/objects/Casos_Residente__c/Casos_Residente__c.object-meta.xml
<CustomObject>
    <label>Caso ATC</label>
    <nameField>
        <displayFormat>CAS-{00000000}</displayFormat>
        <label>Folio</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Casos ATC</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Casos_Residente__c/fields/ContactEmail__c.field-meta.xml
<CustomField>
    <fullName>ContactEmail__c</fullName>
    <label>Email del contacto</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Casos_Residente__c/fields/ContactMobile__c.field-meta.xml
<CustomField>
    <fullName>ContactMobile__c</fullName>
    <label>Teléfono celular del contacto</label>
    <type>Phone</type>
</CustomField>

unpackaged/main/default/objects/Casos_Residente__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Clientes ATC</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Casos ATC</relationshipLabel>
    <relationshipName>Casos_Residentes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Casos_Residente__c/fields/Detalledelreporte__c.field-meta.xml
<CustomField>
    <fullName>Detalledelreporte__c</fullName>
    <label>Detalle del reporte</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Casos_Residente__c/fields/Fecha_Cierre_Cancelacion__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Cierre_Cancelacion__c</fullName>
    <label>Fecha de Cierre/Cancelación</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Casos_Residente__c/fields/Origendegarantia__c.field-meta.xml
<CustomField>
    <fullName>Origendegarantia__c</fullName>
    <label>Origen de garantía</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Apoyo a cliente</fullName>
            </value>
            <value>
                <fullName>Contratista</fullName>
            </value>
            <value>
                <fullName>Producto</fullName>
            </value>
            <value>
                <fullName>Proyecto</fullName>
            </value>
            <value>
                <fullName>Supervisión</fullName>
            </value>
            <value>
                <fullName>Urbanización</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Casos_Residente__c/fields/ViviendaProceso__c.field-meta.xml
<CustomField>
    <fullName>ViviendaProceso__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Vivienda</label>
    <referenceTo>Inventario__c</referenceTo>
    <relationshipLabel>Casos ATC</relationshipLabel>
    <relationshipName>Casos_ATC</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/Inventario__c.object-meta.xml
<CustomObject>
    <label>Proceso ATC</label>
    <nameField>
        <label>Id Vivienda</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProcesosATC</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Inventario__c/fields/Condominio__c.field-meta.xml
<CustomField>
    <fullName>Condominio__c</fullName>
    <label>Condominio</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Inventarios</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Entregada__c.field-meta.xml
<CustomField>
    <fullName>Entregada__c</fullName>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Por Entregar</fullName>
            </value>
            <value>
                <fullName>No Entregado</fullName>
            </value>
            <value>
                <fullName>Entregado</fullName>
            </value>
            <value>
                <fullName>Agendada</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/FechadeHabitabilidad__c.field-meta.xml
<CustomField>
    <fullName>FechadeHabitabilidad__c</fullName>
    <label>Fecha de Habitabilidad</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/FechaHabitabilidad__c.field-meta.xml
<CustomField>
    <fullName>FechaHabitabilidad__c</fullName>
    <label>Fecha Habitabilidad</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Notaria__c.field-meta.xml
<CustomField>
    <fullName>Notaria__c</fullName>
    <label>Notaria</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Notario__c.field-meta.xml
<CustomField>
    <fullName>Notario__c</fullName>
    <label>Notario</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/PorcentajeCheckList__c.field-meta.xml
<CustomField>
    <fullName>PorcentajeCheckList__c</fullName>
    <label>Porcentaje Check List</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Revisiones_en_Vivienda__c.field-meta.xml
<CustomField>
    <fullName>Revisiones_en_Vivienda__c</fullName>
    <label>¿Cuántas veces revisaste la vivienda?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <default>true</default>
                <label>0</label>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Notaria__c/Notaria__c.object-meta.xml
<CustomObject>
    <label>Notaría</label>
    <nameField>
        <label>Notaría</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notarías</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Notaria__c/fields/Notario__c.field-meta.xml
<CustomField>
    <fullName>Notario__c</fullName>
    <label>Notario</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/globalValueSets/Canal_de_Venta.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>DIGITAL ASESOR</fullName>
    </customValue>
    <customValue>
        <fullName>EVENTO</fullName>
    </customValue>
    <customValue>
        <fullName>LLAMADA CALL CENTER</fullName>
    </customValue>
    <customValue>
        <fullName>MACROVENTA</fullName>
    </customValue>
    <customValue>
        <fullName>MACROVENTA 2015</fullName>
    </customValue>
    <customValue>
        <fullName>MEDIO PUBLICITARIO</fullName>
    </customValue>
    <customValue>
        <fullName>MEDIOS DIGITALES</fullName>
    </customValue>
    <customValue>
        <fullName>PROGRAMAS INSTITUCIONALES</fullName>
    </customValue>
    <customValue>
        <fullName>PROMOTOR EXTERNO</fullName>
    </customValue>
    <customValue>
        <fullName>PROSPECCION</fullName>
    </customValue>
    <customValue>
        <fullName>PROSPECTO ASESOR</fullName>
    </customValue>
    <customValue>
        <fullName>REFERIDOS</fullName>
    </customValue>
    <customValue>
        <fullName>VENTA EMPRESARIAL</fullName>
    </customValue>
    <customValue>
        <fullName>CARGA INICIAL</fullName>
    </customValue>
    <masterLabel>Canal de Venta</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/Casos_Cuenta_Vacias_UPD_Test.cls
@isTest
public class Casos_Cuenta_Vacias_UPD_Test {
@testSetup
    public static void setup(){
        Id usuar = [SELECT Id FROM User WHERE Name LIKE 'Admin J%' LIMIT 1].ID;
        Account acc = new Account();
        acc.FirstName= 'Lopez';
        acc.LastName= 'test';
        acc.RecordTypeId =Schema.sObjectType.Account.getRecordTypeInfosBydevelopername().get('Prospecto_Persona_Fisica').getRecordTypeId();
        acc.CorreoElectronico__c = 'test@prospects.com';
        acc.Apellidomaterno_cta__c = 'dahuoh';
        acc.PersonBirthdate=date.today().addyears(-20);
        acc.Phone = '+528119928819';
        acc.Otro_Telefono__c = '+528119928819';
        acc.TelefonoCelular__c='+525530303030'; 
        acc.Canal_de_Venta__c = 'PROSPECTO ASESOR';
        acc.Notaria__c = 'PRUEBA';
        acc.Notario__c = 'PRUEBA';
        acc.isATC__c = true;
        acc.Numerodecliente__c = 'AA';
        acc.Nombre_cta__c = 'PRUEBA';
        acc.Estatus_Lista_Negra_QEQ__c = 'VALIDADO';
        insert acc;
        Inventario__c inventario = new Inventario__c();
        inventario.Condominio__c = 'Condominio';
        inventario.Name = 'AABBCCDDEE-Prueba';
        inventario.Entregada__c = 'Por Entregar';
        inventario.FechaHabitabilidad__c = System.today().format();
        inventario.PorcentajeCheckList__c = 0;
        inventario.FechadeHabitabilidad__c = System.today();
        inventario.Cuenta__c = acc.Id;
        inventario.Revisiones_en_Vivienda__c = '3';
        insert inventario;
        Casos_Residente__c caso = new Casos_Residente__c();
        caso.Detalledelreporte__c = 'asdasd';
        //caso.Cuenta__c = acc.Id;
        caso.ViviendaProceso__c = inventario.Id;
        caso.ContactEmail__c='correo@prueba.com';
        caso.ContactMobile__c='88888888';
        //caso.OwnerId = usuar;
        caso.Origendegarantia__c = 'Producto';
        caso.Fecha_Cierre_Cancelacion__c = system.today()-1;
        insert caso;
    }
    @isTest
    private static void BATCH_WorkdayWorking(){   
        Test.startTest();
        Casos_Cuenta_Vacias_UPD BWW = new Casos_Cuenta_Vacias_UPD();
        Id batchId3 = Database.executeBatch(BWW,10);
        Test.stopTest();
    }
}