unpackaged/main/default/objects/Account/fields/Apellidomaterno_cta__c.field-meta.xml
<CustomField>
    <fullName>Apellidomaterno_cta__c</fullName>
    <label>Apellido Materno</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Aprobo_Check_Apellido__c.field-meta.xml
<CustomField>
    <fullName>Aprobo_Check_Apellido__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Aprobo Check Apellido</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Canal_de_Venta__c.field-meta.xml
<CustomField>
    <fullName>Canal_de_Venta__c</fullName>
    <label>Canal de Venta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Canal_de_Venta</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Check_Apellido__c.field-meta.xml
<CustomField>
    <fullName>Check_Apellido__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Check Apellido</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Fraccionamiento_cta__c.field-meta.xml
<CustomField>
    <fullName>Fraccionamiento_cta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fraccionamiento</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>(1 OR 5 OR 2 OR 4 OR 6) AND 3</booleanFilter>
        <filterItems>
            <field>$User.Fraccionamiento_autorizado__c</field>
            <operation>contains</operation>
            <valueField>Fraccionamiento__c.Name</valueField>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>Administrador del sistema</value>
        </filterItems>
        <filterItems>
            <field>Fraccionamiento__c.Activo_frac__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$User.Fraccionamiento_autorizado__c</field>
            <operation>equals</operation>
            <value>TODOS</value>
        </filterItems>
        <filterItems>
            <field>$User.FraccionamientoAutorizados__c</field>
            <operation>contains</operation>
            <valueField>Fraccionamiento__c.Name</valueField>
        </filterItems>
        <filterItems>
            <field>$User.Fraccionamiento_autorizado__c</field>
            <operation>contains</operation>
            <valueField>Fraccionamiento__c.Name</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Fraccionamiento__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Sub_canal_de_venta__c.field-meta.xml
<CustomField>
    <fullName>Sub_canal_de_venta__c</fullName>
    <label>Sub canal de venta</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Canal_de_Venta__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Sub_canal_de_venta</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/TelefonoCelular__c.field-meta.xml
<CustomField>
    <fullName>TelefonoCelular__c</fullName>
    <label>Teléfono Celular</label>
    <type>Phone</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Vivienda_Mas_Reciente__c.field-meta.xml
<CustomField>
    <fullName>Vivienda_Mas_Reciente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vivienda Mas Reciente</label>
    <referenceTo>Inventario__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Fraccionamiento__c/Fraccionamiento__c.object-meta.xml
<CustomObject>
    <label>Fraccionamiento</label>
    <nameField>
        <label>Nombre de Fraccionamiento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fraccionamientos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Inventario__c/Inventario__c.object-meta.xml
<CustomObject>
    <label>Proceso ATC</label>
    <nameField>
        <label>Id Vivienda</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProcesosATC</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Inventario__c/fields/Condominio__c.field-meta.xml
<CustomField>
    <fullName>Condominio__c</fullName>
    <label>Condominio</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Inventarios</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Entregada__c.field-meta.xml
<CustomField>
    <fullName>Entregada__c</fullName>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Por Entregar</fullName>
            </value>
            <value>
                <fullName>No Entregado</fullName>
            </value>
            <value>
                <fullName>Entregado</fullName>
            </value>
            <value>
                <fullName>Agendada</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Fraccionamiento__c.field-meta.xml
<CustomField>
    <fullName>Fraccionamiento__c</fullName>
    <label>Fraccionamiento</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Revisiones_en_Vivienda__c.field-meta.xml
<CustomField>
    <fullName>Revisiones_en_Vivienda__c</fullName>
    <label>¿Cuántas veces revisaste la vivienda?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <default>true</default>
                <label>0</label>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/User/fields/FraccionamientoAutorizados__c.field-meta.xml
<CustomField>
    <fullName>FraccionamientoAutorizados__c</fullName>
    <label>Fraccionamiento Autorizados</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/User/fields/FRACCIONAMIENTOS__c.field-meta.xml
<CustomField>
    <fullName>FRACCIONAMIENTOS__c</fullName>
    <label>FRACCIONAMIENTOS</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ACACIAS</fullName>
            </value>
            <value>
                <fullName>ACACIAS II</fullName>
            </value>
            <value>
                <fullName>ALBERI RESIDENCIAL</fullName>
            </value>
            <value>
                <fullName>ALVENTO</fullName>
            </value>
            <value>
                <fullName>ARBOLADA</fullName>
            </value>
            <value>
                <fullName>BOSQUE REAL</fullName>
            </value>
            <value>
                <fullName>BOSQUES DEL NEVADO</fullName>
            </value>
            <value>
                <fullName>MAGNOLIAS IV</fullName>
            </value>
            <value>
                <fullName>MISION DE LOS ANGELES 1ER SECTOR ARCANGELES</fullName>
            </value>
            <value>
                <fullName>MURIEL RESIDENCIAL</fullName>
            </value>
            <value>
                <fullName>PASEO SAN JUNIPERO</fullName>
            </value>
            <value>
                <fullName>PASEOS DEL SUR</fullName>
            </value>
            <value>
                <fullName>PRIVADA BELTERRA</fullName>
            </value>
            <value>
                <fullName>PRIVADAS CARANDAY</fullName>
            </value>
            <value>
                <fullName>PRIVALIA AMBIENTA</fullName>
            </value>
            <value>
                <fullName>TODOS</fullName>
            </value>
            <value>
                <fullName>VALLE DE LINCOLN SECTOR MINAS</fullName>
            </value>
            <value>
                <fullName>VALLE DE SANTA ELENA</fullName>
            </value>
            <value>
                <fullName>VALLE DE TEJEDA II</fullName>
            </value>
            <value>
                <fullName>VALLE SANTA ISABEL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/User/fields/is_Data_Migration_User__c.field-meta.xml
<CustomField>
    <fullName>is_Data_Migration_User__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Permitir brincar reglas a los usuarios marcados como TRUE</description>
    <label>Es Usuario de Migración de Datos</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/globalValueSets/Canal_de_Venta.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>DIGITAL ASESOR</fullName>
    </customValue>
    <customValue>
        <fullName>EVENTO</fullName>
    </customValue>
    <customValue>
        <fullName>LLAMADA CALL CENTER</fullName>
    </customValue>
    <customValue>
        <fullName>MACROVENTA</fullName>
    </customValue>
    <customValue>
        <fullName>MACROVENTA 2015</fullName>
    </customValue>
    <customValue>
        <fullName>MEDIO PUBLICITARIO</fullName>
    </customValue>
    <customValue>
        <fullName>MEDIOS DIGITALES</fullName>
    </customValue>
    <customValue>
        <fullName>PROGRAMAS INSTITUCIONALES</fullName>
    </customValue>
    <customValue>
        <fullName>PROMOTOR EXTERNO</fullName>
    </customValue>
    <customValue>
        <fullName>PROSPECCION</fullName>
    </customValue>
    <customValue>
        <fullName>PROSPECTO ASESOR</fullName>
    </customValue>
    <customValue>
        <fullName>REFERIDOS</fullName>
    </customValue>
    <customValue>
        <fullName>VENTA EMPRESARIAL</fullName>
    </customValue>
    <customValue>
        <fullName>CARGA INICIAL</fullName>
    </customValue>
    <masterLabel>Canal de Venta</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Sub_canal_de_venta.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1-2GUPNA8</fullName>
    </customValue>
    <customValue>
        <fullName>ACTIVACION/EVENTO</fullName>
    </customValue>
    <customValue>
        <fullName>ACTIVACION/EVENTO/PERIFERIA</fullName>
    </customValue>
    <customValue>
        <fullName>AGS FERIA CANADEVI</fullName>
    </customValue>
    <customValue>
        <fullName>AGS MOCTEZUMA</fullName>
    </customValue>
    <customValue>
        <fullName>AGS SAN DIEGO</fullName>
    </customValue>
    <customValue>
        <fullName>AGS VILLA ASUNCION</fullName>
    </customValue>
    <customValue>
        <fullName>APP INVITADO</fullName>
    </customValue>
    <customValue>
        <fullName>BLOGGER/TANIA RENDON</fullName>
    </customValue>
    <customValue>
        <fullName>BUEN FIN</fullName>
    </customValue>
    <customValue>
        <fullName>CALL CENTER/TELEMARKETING</fullName>
    </customValue>
    <customValue>
        <fullName>CAMBACEO</fullName>
    </customValue>
    <customValue>
        <fullName>CARTELERA MOVIL</fullName>
    </customValue>
    <customValue>
        <fullName>CARTELERA PV</fullName>
    </customValue>
    <customValue>
        <fullName>CARTERA DE CLIENTES</fullName>
    </customValue>
    <customValue>
        <fullName>CARTERA PROPIA</fullName>
    </customValue>
    <customValue>
        <fullName>CITA ASESOR</fullName>
    </customValue>
    <customValue>
        <fullName>COLABORADOR JAVER</fullName>
    </customValue>
    <customValue>
        <fullName>COMPAÑERO DE TRABAJO</fullName>
    </customValue>
    <customValue>
        <fullName>CONVENIO PABELLON M</fullName>
    </customValue>
    <customValue>
        <fullName>CORREO</fullName>
    </customValue>
    <customValue>
        <fullName>CORREO DIRECTO/CARTA</fullName>
    </customValue>
    <customValue>
        <fullName>EDO MEX SAMARA</fullName>
    </customValue>
    <customValue>
        <fullName>EN EMPRESA (VENTA EMPRESARIAL)</fullName>
    </customValue>
    <customValue>
        <fullName>ESPECTACULAR/CARTELERA</fullName>
    </customValue>
    <customValue>
        <fullName>EVENTO (MACROVENTA, SUPERVTA)</fullName>
    </customValue>
    <customValue>
        <fullName>EXPO/FERIA</fullName>
    </customValue>
    <customValue>
        <fullName>FACEBOOK</fullName>
    </customValue>
    <customValue>
        <fullName>FACEBOOK INBOX</fullName>
    </customValue>
    <customValue>
        <fullName>FAMILIAR</fullName>
    </customValue>
    <masterLabel>Sub canal de venta</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/BatchViviendaMasReciente_Test.cls
@isTest
public class BatchViviendaMasReciente_Test {
    @testSetup
    public static void setup(){
        profile p = [Select Id From Profile Where Name='System Administrator'];
        User user = new User(ProfileID = p.id, EmailEncodingKey = 'ISO-8859-1', LanguageLocaleKey = 'en_US', TimeZoneSidKey = 'America/New_York', LocaleSidKey = 'en_US', is_Data_Migration_User__c = true, 
                             FirstName = 'first', LastName = 'last', Username = 'test@portal123453.com', CommunityNickname = 'testUser123', Alias = 't1', Email = 'no@email.com', IsActive = true,
                             FRACCIONAMIENTOS__c = 'ACACIAS;ACACIAS II', FraccionamientoAutorizados__c = 'ACACIAS');
        insert user;
        System.runAs(user){    
            Id idTipoRegistroProspectoPersonaFisica = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Prospecto_Persona_Fisica').getRecordTypeId();
            Fraccionamiento__c f = new Fraccionamiento__c(name = 'frac');insert f;
            Fraccionamiento__c f1 = new Fraccionamiento__c(name = 'ACACIAS');insert f1;
            Account acc = new Account(Apellidomaterno_cta__c = 'materno',FirstName = 'fName',LastName = 'lName',Canal_de_Venta__c = 'PROGRAMAS INSTITUCIONALES',
                                      TelefonoCelular__c = '+525656566567',phone = '+525656566567',Sub_canal_de_venta__c = 'COLABORADOR JAVER',
                                      Fraccionamiento_cta__c = f1.id,RecordTypeId = idTipoRegistroProspectoPersonaFisica);
            Account acc1 = acc.clone(false, true, false, false);
            acc1.Canal_de_Venta__c = 'MEDIOS DIGITALES';
            acc1.Sub_canal_de_venta__c = '';
            acc1.Check_Apellido__c = true;
            insert acc1;
            Inventario__c inventario = new Inventario__c(Condominio__c = 'Condominio', Entregada__c = 'Entregado', Cuenta__c = acc1.Id, Revisiones_en_Vivienda__c = '3');
            insert inventario;
            acc1.Apellidomaterno_cta__c = 'test';
            acc1.Aprobo_Check_Apellido__c  = false;
            acc1.Vivienda_Mas_Reciente__c = inventario.Id;
            update acc1;
        }
    }
    @isTest
    private static void BatchViviendaMasReciente(){
        user u = [SELECT Id, Name FROM User WHERE LastName = 'last' LIMIT 1];
        System.runAs(u){    
            Test.startTest();
            BatchViviendaMasReciente BVMR = new BatchViviendaMasReciente();
            Id batchId3 = Database.executeBatch(BVMR,10);
            Test.stopTest();
        }
    }
}