unpackaged/main/default/objects/Account/fields/Apellidomaterno_cta__c.field-meta.xml
<CustomField>
    <fullName>Apellidomaterno_cta__c</fullName>
    <label>Apellido Materno</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/CorreoElectronico__c.field-meta.xml
<CustomField>
    <fullName>CorreoElectronico__c</fullName>
    <label>Correo Electrónico</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Fraccionamiento_cta__c.field-meta.xml
<CustomField>
    <fullName>Fraccionamiento_cta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fraccionamiento</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>(1 OR 5 OR 2 OR 4 OR 6) AND 3</booleanFilter>
        <filterItems>
            <field>$User.Fraccionamiento_autorizado__c</field>
            <operation>contains</operation>
            <valueField>Fraccionamiento__c.Name</valueField>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>Administrador del sistema</value>
        </filterItems>
        <filterItems>
            <field>Fraccionamiento__c.Activo_frac__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$User.Fraccionamiento_autorizado__c</field>
            <operation>equals</operation>
            <value>TODOS</value>
        </filterItems>
        <filterItems>
            <field>$User.FraccionamientoAutorizados__c</field>
            <operation>contains</operation>
            <valueField>Fraccionamiento__c.Name</valueField>
        </filterItems>
        <filterItems>
            <field>$User.Fraccionamiento_autorizado__c</field>
            <operation>contains</operation>
            <valueField>Fraccionamiento__c.Name</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Fraccionamiento__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Company_Javer.recordType-meta.xml
<RecordType>
    <fullName>Company_Javer</fullName>
    <active>true</active>
    <label>COMPAÑÍA JAVER</label>
</RecordType>

unpackaged/main/default/objects/Account/recordTypes/Prospecto.recordType-meta.xml
<RecordType>
    <fullName>Prospecto</fullName>
    <active>true</active>
    <label>Prospecto</label>
</RecordType>

unpackaged/main/default/objects/Fraccionamiento__c/Fraccionamiento__c.object-meta.xml
<CustomObject>
    <label>Fraccionamiento</label>
    <nameField>
        <label>Nombre de Fraccionamiento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fraccionamientos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Fraccionamiento__c/fields/Activo_frac__c.field-meta.xml
<CustomField>
    <fullName>Activo_frac__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Fraccionamiento__c/fields/Codigo_Fraccionamiento__c.field-meta.xml
<CustomField>
    <fullName>Codigo_Fraccionamiento__c</fullName>
    <externalId>true</externalId>
    <label>Código Fraccionamiento</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Fraccionamiento__c/fields/Fecha_Vigencia__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Vigencia__c</fullName>
    <label>Fecha Vigencia</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Fraccionamiento__c/fields/Id_Mas_Comercial__c.field-meta.xml
<CustomField>
    <fullName>Id_Mas_Comercial__c</fullName>
    <label>Id Mas Comercial</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Fraccionamiento__c/fields/Muni_fracc__c.field-meta.xml
<CustomField>
    <fullName>Muni_fracc__c</fullName>
    <label>Municipio</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Fraccionamiento__c/fields/Plaza__c.field-meta.xml
<CustomField>
    <fullName>Plaza__c</fullName>
    <label>Plaza</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Fraccionamiento__c/fields/Plaza_Filtro__c.field-meta.xml
<CustomField>
    <fullName>Plaza_Filtro__c</fullName>
    <label>Plaza_Filtro</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Querétaro</fullName>
            </value>
            <value>
                <fullName>Nuevo León</fullName>
            </value>
            <value>
                <fullName>Estado de México</fullName>
            </value>
            <value>
                <fullName>Jalisco</fullName>
            </value>
            <value>
                <fullName>Aguascalientes</fullName>
            </value>
            <value>
                <fullName>Distrito Federal</fullName>
            </value>
            <value>
                <fullName>San Luis Potosi</fullName>
            </value>
            <value>
                <fullName>Quintana Roo</fullName>
            </value>
            <value>
                <fullName>Guanajuato</fullName>
            </value>
            <value>
                <fullName>Tamaulipas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Fraccionamiento__c/fields/Prototipo__c.field-meta.xml
<CustomField>
    <fullName>Prototipo__c</fullName>
    <label>Prototipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prototipo 1</fullName>
            </value>
            <value>
                <fullName>Prototipo 2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Fraccionamiento__c/fields/Segmento__c.field-meta.xml
<CustomField>
    <fullName>Segmento__c</fullName>
    <label>Segmento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Residencial</fullName>
            </value>
            <value>
                <fullName>Media</fullName>
            </value>
            <value>
                <fullName>Interés Social</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Fraccionamiento__c/fields/Sin_Vigencia__c.field-meta.xml
<CustomField>
    <fullName>Sin_Vigencia__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sin Vigencia</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Fraccionamiento__c/fields/Tipode_vivienda__c.field-meta.xml
<CustomField>
    <fullName>Tipode_vivienda__c</fullName>
    <label>Tipo de vivienda</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Residencial</fullName>
                <default>true</default>
                <label>Residencial</label>
            </value>
            <value>
                <fullName>Interés Social</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Fraccionamiento__c/fields/Todo__c.field-meta.xml
<CustomField>
    <fullName>Todo__c</fullName>
    <externalId>true</externalId>
    <label>Todo</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Fraccionamiento__c/fields/Webfracc_frac__c.field-meta.xml
<CustomField>
    <fullName>Webfracc_frac__c</fullName>
    <label>Web Fraccionamiento</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/Prototipo__c/Prototipo__c.object-meta.xml
<CustomObject>
    <label>Prototipo</label>
    <nameField>
        <label>Prototipo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prototipos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Prototipo__c/fields/Activo_pro__c.field-meta.xml
<CustomField>
    <fullName>Activo_pro__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Prototipo__c/fields/Fraccionamiento__c.field-meta.xml
<CustomField>
    <fullName>Fraccionamiento__c</fullName>
    <label>Fraccionamiento</label>
    <referenceTo>Fraccionamiento__c</referenceTo>
    <relationshipLabel>Prototipos</relationshipLabel>
    <relationshipName>Prototipos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Prototipo__c/fields/Id_Mas_Comercial__c.field-meta.xml
<CustomField>
    <fullName>Id_Mas_Comercial__c</fullName>
    <label>Id Mas Comercial</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Prototipo__c/fields/Precio_Presupuesto__c.field-meta.xml
<CustomField>
    <fullName>Precio_Presupuesto__c</fullName>
    <label>Precio Presupuesto</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Prototipo__c/fields/Precio_pro__c.field-meta.xml
<CustomField>
    <fullName>Precio_pro__c</fullName>
    <label>Precio</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Prototipo__c/fields/Prototipo_pro__c.field-meta.xml
<CustomField>
    <fullName>Prototipo_pro__c</fullName>
    <label>Campo Control</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Prototipo__c/fields/Todo__c.field-meta.xml
<CustomField>
    <fullName>Todo__c</fullName>
    <defaultValue>&#39;TODO&#39;</defaultValue>
    <externalId>true</externalId>
    <label>Todo</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Prototipo__c/fields/Version_Precio_Presupuesto__c.field-meta.xml
<CustomField>
    <fullName>Version_Precio_Presupuesto__c</fullName>
    <label>Versión Precio Presupuesto</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Oficial Firmada</fullName>
            </value>
            <value>
                <fullName>Working</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Segmento__c/Segmento__c.object-meta.xml
<CustomObject>
    <label>Segmento</label>
    <nameField>
        <label>Nombre de Segmentos</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Segmentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Segmento__c/fields/Fraccionamiento__c.field-meta.xml
<CustomField>
    <fullName>Fraccionamiento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fraccionamiento</label>
    <referenceTo>Fraccionamiento__c</referenceTo>
    <relationshipLabel>Segmentos</relationshipLabel>
    <relationshipName>Segmentos</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/User/fields/Fraccionamiento_autorizado__c.field-meta.xml
<CustomField>
    <fullName>Fraccionamiento_autorizado__c</fullName>
    <inlineHelpText>Al poner la Palabra TODOS 
lo que dará acceso a cualquier fracc.</inlineHelpText>
    <label>Fraccionamiento autorizado</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/User/fields/FraccionamientoAutorizados__c.field-meta.xml
<CustomField>
    <fullName>FraccionamientoAutorizados__c</fullName>
    <label>Fraccionamiento Autorizados</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/User/fields/FRACCIONAMIENTOS__c.field-meta.xml
<CustomField>
    <fullName>FRACCIONAMIENTOS__c</fullName>
    <label>FRACCIONAMIENTOS</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ACACIAS</fullName>
            </value>
            <value>
                <fullName>ACACIAS II</fullName>
            </value>
            <value>
                <fullName>ALBERI RESIDENCIAL</fullName>
            </value>
            <value>
                <fullName>ALVENTO</fullName>
            </value>
            <value>
                <fullName>ARBOLADA</fullName>
            </value>
            <value>
                <fullName>BOSQUE REAL</fullName>
            </value>
            <value>
                <fullName>BOSQUES DEL NEVADO</fullName>
            </value>
            <value>
                <fullName>MAGNOLIAS IV</fullName>
            </value>
            <value>
                <fullName>MISION DE LOS ANGELES 1ER SECTOR ARCANGELES</fullName>
            </value>
            <value>
                <fullName>MURIEL RESIDENCIAL</fullName>
            </value>
            <value>
                <fullName>PASEO SAN JUNIPERO</fullName>
            </value>
            <value>
                <fullName>PASEOS DEL SUR</fullName>
            </value>
            <value>
                <fullName>PRIVADA BELTERRA</fullName>
            </value>
            <value>
                <fullName>PRIVADAS CARANDAY</fullName>
            </value>
            <value>
                <fullName>PRIVALIA AMBIENTA</fullName>
            </value>
            <value>
                <fullName>TODOS</fullName>
            </value>
            <value>
                <fullName>VALLE DE LINCOLN SECTOR MINAS</fullName>
            </value>
            <value>
                <fullName>VALLE DE SANTA ELENA</fullName>
            </value>
            <value>
                <fullName>VALLE DE TEJEDA II</fullName>
            </value>
            <value>
                <fullName>VALLE SANTA ISABEL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/User/fields/Id_Mas_Comercial__c.field-meta.xml
<CustomField>
    <fullName>Id_Mas_Comercial__c</fullName>
    <label>Id Mas Comercial</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/Prospects_Test.cls
@isTest
public class Prospects_Test {
    @isTest(seeAllData=true)
    public static void Test1() {  
        UserRole userrole = [Select Id, DeveloperName From UserRole Where PortalType= 'None' Limit 1];
        Id profileId = [SELECT Id FROM Profile WHERE Name = 'JAVER - Generico' LIMIT 1].Id;
        system.debug('profileId='+profileId);
        User user = new User(alias = 'test123', email='test123@noemail.com',
                             emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US',UserroleId = userrole.id,
                             localesidkey='en_US', profileid = profileId, country='United States',IsActive =true,
                             timezonesidkey='America/Los_Angeles', username='testUserInfo@email.com',FRACCIONAMIENTOS__c = 'BOSQUE REAL;BOSQUES DEL NEVADO',
                             Fraccionamiento_autorizado__c = 'BOSQUE REAL', FraccionamientoAutorizados__c = 'BOSQUE REAL');
        insert user;
        
        
        System.runAs(user) {
            Fraccionamiento__c f = new Fraccionamiento__c( Activo_frac__c=true, Id_Mas_Comercial__c='MAS-123456', Muni_fracc__c='San Pedro', Webfracc_frac__c='www.bosquereal.com.mx', Plaza__c='Nuevo León', Segmento__c='Residencial', Tipode_vivienda__c='Residencial', Fecha_Vigencia__c=date.today().addmonths(16),
                                                          Sin_Vigencia__c=true, Codigo_Fraccionamiento__c='66278', Plaza_Filtro__c='Nuevo León', Name='BOSQUE REAL');
            insert f;
            
            Prototipo__c proto = new Prototipo__c(Name='TAMARINDO', Activo_pro__c=true, Fraccionamiento__c=f.Id, Precio_pro__c=2500000, Prototipo_pro__c='TAMARINDO - BOSQUE REAL', Precio_Presupuesto__c=1850000.00, Version_Precio_Presupuesto__c='Working', Todo__c='TODO');
            insert proto;
            
            Account acc = new Account();
            acc.FirstName= 'Lopez';
            acc.LastName= 'test';
            acc.RecordTypeId =Schema.sObjectType.Account.getRecordTypeInfosBydevelopername().get('Prospecto_Persona_Fisica').getRecordTypeId();
            acc.CorreoElectronico__c = 'test@prospects.com';
            acc.Apellidomaterno_cta__c = 'dahuoh';
            acc.PersonBirthdate=date.parse('11/09/1991');
            acc.Phone = '+528119928819';
            acc.Fraccionamiento_cta__c = f.id;
            acc.Otro_Telefono__c = '+528119928819';
            acc.Canal_de_Venta__c = 'PROSPECTO ASESOR';
            insert acc;
            Attachment attach=new Attachment();   	
            attach.Name='Unit Test Attachment';
            Blob bodyBlob=Blob.valueOf('Unit Test Attachment Body');
            attach.body=bodyBlob;
            attach.parentId=acc.id;
            insert attach;
            ContentVersion content=new ContentVersion(); 
            content.Title='Header_Picture1'; 
            content.PathOnClient='/' + content.Title + '.jpg'; 
            Blob bodyBlob1=Blob.valueOf('Unit Test ContentVersion Body'); 
            content.VersionData=bodyBlob1; 
            content.origin = 'H';
            insert content;
            ContentDocumentLink contentlink=new ContentDocumentLink();
            contentlink.LinkedEntityId=acc.id;
            contentlink.contentdocumentid=[select contentdocumentid from contentversion where id =: content.id].contentdocumentid;
            contentlink.ShareType = 'I';
            contentlink.Visibility = 'AllUsers'; 
            insert contentlink;
            Account A = new Account(name= 'Lopez',
                                    RecordTypeId =Schema.sObjectType.Account.getRecordTypeInfosBydevelopername().get('Company_Javer').getRecordTypeId(),
                                    Apellidomaterno_cta__c = 'materno',Phone = '+528119928819',Otro_Telefono__c = '+528119928819',Canal_de_Venta__c = 'PROSPECTO ASESOR');
            insert A;
            contact con = new contact(LastName = 'Lname',AccountId = A.id, MobilePhone = '+525656565656');
            insert con;
            WhatsApp__c W = new WhatsApp__c();
            W.Message__c = 'Hi';
            W.Prospect__c = acc.id;
            insert W;
            Datetime startDateTime = Datetime.newInstance(2023, 3, 14,23, 0, 0);
            Datetime EndDateTime = Datetime.newInstance(2023, 3, 15,23, 0, 0);
            Test.setMock(HttpCalloutMock.class, new MockHttpProspects());     
            Test.startTest();
            Prospects.fetchProspectsDetails(acc.Id);
            Prospects.fetchEveTaskSubject();
            Prospects.saveEvents(acc.Id,'Subject',startDateTime,EndDateTime,'Description');
            Prospects.saveTasks(acc.Id, 'Subject', system.today(), 'Test', 'Description');
            Prospects.fetchActivities(acc.Id);
            Prospects.UpdateNote('title','body',acc.Id);
            Prospects.fetchWappConvo(acc.Id);
            Prospects.fetchDocs(acc.Id);
            Prospects.SendEmailToPros(acc.Id, 'subject' , 'msg');
            Prospects.fetchEmailconvo(acc.Id);
            Prospects.sendWhatsappSms('+525656565656');
            //WhatsAppIntegration.sendSms(con.Id);
            Prospects.updatePorpFields(acc.Id,acc, f.Id, proto.Id, '');
            Prospects.pdfGen(acc.Id , true);
            Prospects.updateMethod(acc.Id, f.Id);            
            Test.stopTest();
        }
    }
    
    public static void Test_updateOwner() {  
        Account acc = new Account();
        acc.FirstName= 'Lopez';
        acc.LastName= 'test';
        acc.RecordTypeId =Schema.sObjectType.Account.getRecordTypeInfosBydevelopername().get('Prospecto_Persona_Fisica').getRecordTypeId();
        acc.CorreoElectronico__c = 'test@prospects.com';
        acc.Apellidomaterno_cta__c = 'dahuoh';
        acc.PersonBirthdate=date.parse('11/09/1991');
        acc.Phone = '+528119928819';            
        acc.Otro_Telefono__c = '+528119928819';
        acc.Canal_de_Venta__c = 'PROSPECTO ASESOR';
        insert acc;
        Prospects.updateOwner(acc.Id);   
    }
    
    
}