unpackaged/main/default/objects/Account/fields/Apellidomaterno_cta__c.field-meta.xml
<CustomField>
    <fullName>Apellidomaterno_cta__c</fullName>
    <label>Apellido Materno</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Apellidopaterno_cta__c.field-meta.xml
<CustomField>
    <fullName>Apellidopaterno_cta__c</fullName>
    <label>Apellido Paterno</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Asesor__c.field-meta.xml
<CustomField>
    <fullName>Asesor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asesor</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR 3</booleanFilter>
        <errorMessage>El usuario seleccionado no tiene asignado el fraccionamiento elegido.</errorMessage>
        <filterItems>
            <field>User.ProfileId</field>
            <operation>equals</operation>
            <value>00e23000000anFuAAI</value>
        </filterItems>
        <filterItems>
            <field>User.FraccionamientoAutorizados__c</field>
            <operation>contains</operation>
            <valueField>$Source.Nombre_Fraccionamiento__c</valueField>
        </filterItems>
        <filterItems>
            <field>User.ProfileId</field>
            <operation>equals</operation>
            <value>00e23000000anG0AAI</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Canal_de_Venta__c.field-meta.xml
<CustomField>
    <fullName>Canal_de_Venta__c</fullName>
    <label>Canal de Venta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Canal_de_Venta</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Estatus_Cliente__c.field-meta.xml
<CustomField>
    <fullName>Estatus_Cliente__c</fullName>
    <label>Estatus Cliente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>POR ASIGNAR</fullName>
                <default>true</default>
                <label>POR ASIGNAR</label>
            </value>
            <value>
                <fullName>ASIGNADO</fullName>
            </value>
            <value>
                <fullName>POR REASIGNAR</fullName>
            </value>
            <value>
                <fullName>BAJA</fullName>
            </value>
            <value>
                <fullName>INCUBADORA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Estatus_Lista_Negra_QEQ__c.field-meta.xml
<CustomField>
    <fullName>Estatus_Lista_Negra_QEQ__c</fullName>
    <label>Estatus Lista Negra</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SIN VALIDAR</fullName>
                <default>true</default>
                <label>SIN VALIDAR</label>
            </value>
            <value>
                <fullName>LISTA NEGRA</fullName>
            </value>
            <value>
                <fullName>LN CONFIRMADO</fullName>
            </value>
            <value>
                <fullName>VALIDADO</fullName>
            </value>
            <value>
                <fullName>PPE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Fecha_Asignacion_Asesor_Formula__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Asignacion_Asesor_Formula__c</fullName>
    <formula>IF( ISBLANK(Fecha_Asignacion_Asesor__c) , NULL , IF( LEN(TEXT(DAY(Fecha_Asignacion_Asesor__c))) &gt; 1 , TEXT(DAY(Fecha_Asignacion_Asesor__c)), &quot;0&quot; + TEXT(DAY(Fecha_Asignacion_Asesor__c))) + &quot;/&quot; + IF(LEN(TEXT(MONTH(Fecha_Asignacion_Asesor__c))) &gt; 1 , TEXT(MONTH(Fecha_Asignacion_Asesor__c)), &quot;0&quot; + TEXT(MONTH(Fecha_Asignacion_Asesor__c))) + &quot;/&quot; + TEXT(YEAR(Fecha_Asignacion_Asesor__c)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Fecha_Asignacion_Asesor Formula</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/FechaNacimiento__c.field-meta.xml
<CustomField>
    <fullName>FechaNacimiento__c</fullName>
    <label>Fecha de Nacimiento</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/FechaNacimiento_Formula__c.field-meta.xml
<CustomField>
    <fullName>FechaNacimiento_Formula__c</fullName>
    <formula>IF( ISBLANK(FechaNacimiento__c ) , NULL , IF( LEN(TEXT(DAY(FechaNacimiento__c ))) &gt; 1 , TEXT(DAY(FechaNacimiento__c )), &quot;0&quot; + TEXT(DAY(FechaNacimiento__c ))) + &quot;/&quot; + IF(LEN(TEXT(MONTH(FechaNacimiento__c ))) &gt; 1 , TEXT(MONTH(FechaNacimiento__c )), &quot;0&quot; + TEXT(MONTH(FechaNacimiento__c ))) + &quot;/&quot; + TEXT(YEAR(FechaNacimiento__c )))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>FechaNacimiento Formula</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Lead_Profiler__c.field-meta.xml
<CustomField>
    <fullName>Lead_Profiler__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead Profiler</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR 3</booleanFilter>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>contains</operation>
            <value>Lead</value>
        </filterItems>
        <filterItems>
            <field>User.FraccionamientoAutorizados__c</field>
            <operation>contains</operation>
            <valueField>$Source.Nombre_Fraccionamiento__c</valueField>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>contains</operation>
            <value>Generico</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Cuentas4</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Leader__c.field-meta.xml
<CustomField>
    <fullName>Leader__c</fullName>
    <formula>Lead_Profiler__r.FirstName + &quot; &quot;  +  Lead_Profiler__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Leader</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Nombre_del_Asesor__c.field-meta.xml
<CustomField>
    <fullName>Nombre_del_Asesor__c</fullName>
    <formula>Asesor__r.Contact.FirstName &amp; &quot; &quot; &amp; Asesor__r.Contact.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nombre del Asesor</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Nombre_Fraccionamiento__c.field-meta.xml
<CustomField>
    <fullName>Nombre_Fraccionamiento__c</fullName>
    <label>Nombre Fraccionamiento</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ACACIAS</fullName>
            </value>
            <value>
                <fullName>ACACIAS II</fullName>
            </value>
            <value>
                <fullName>ALBERI RESIDENCIAL</fullName>
            </value>
            <value>
                <fullName>ALBORETO RESIDENCIAL</fullName>
            </value>
            <value>
                <fullName>ALVENTO</fullName>
            </value>
            <value>
                <fullName>AMAIRE</fullName>
            </value>
            <value>
                <fullName>ARBOLADA</fullName>
            </value>
            <value>
                <fullName>ARCOS 7</fullName>
            </value>
            <value>
                <fullName>ARCOS DEL SOL</fullName>
            </value>
            <value>
                <fullName>ARCOS DEL SOL SECTOR ELITE</fullName>
            </value>
            <value>
                <fullName>ARRAYANES</fullName>
            </value>
            <value>
                <fullName>ARRAYANES HABITAT II</fullName>
            </value>
            <value>
                <fullName>BARRIO ALAMEDA</fullName>
            </value>
            <value>
                <fullName>BARRIO ESTRELLA</fullName>
            </value>
            <value>
                <fullName>BARRIO PARQUE</fullName>
            </value>
            <value>
                <fullName>BELCANTO</fullName>
            </value>
            <value>
                <fullName>BELCANTO II</fullName>
            </value>
            <value>
                <fullName>BELLATERRA</fullName>
            </value>
            <value>
                <fullName>BELLA VISTA 2º SECTOR FOMERREY</fullName>
            </value>
            <value>
                <fullName>BELLA VISTA 3ER SECTOR</fullName>
            </value>
            <value>
                <fullName>BELLAVISTA 4TO. SECTOR</fullName>
            </value>
            <value>
                <fullName>BELLO AMANECER RESIDENCIAL</fullName>
            </value>
            <value>
                <fullName>BORRAR D09</fullName>
            </value>
            <value>
                <fullName>BOSQUE BOREAL</fullName>
            </value>
            <value>
                <fullName>BOSQUE DE LOS NOGALES</fullName>
            </value>
            <value>
                <fullName>BOSQUE REAL</fullName>
            </value>
            <value>
                <fullName>BOSQUES</fullName>
            </value>
            <value>
                <fullName>BOSQUES DE CASTILLA</fullName>
            </value>
            <value>
                <fullName>BOSQUES DE LERMA</fullName>
            </value>
            <value>
                <fullName>BOSQUES DEL NEVADO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/NSS__c.field-meta.xml
<CustomField>
    <fullName>NSS__c</fullName>
    <inlineHelpText>Obligatorio en Crédito Infonavit o Cofinavit</inlineHelpText>
    <label>NSS</label>
    <length>11</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Account/fields/Numero_de_Cliente_AutoNum__c.field-meta.xml
<CustomField>
    <fullName>Numero_de_Cliente_AutoNum__c</fullName>
    <displayFormat>CLI-{000000}</displayFormat>
    <label>Número de Cliente</label>
    <type>AutoNumber</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Numerodecliente__c.field-meta.xml
<CustomField>
    <fullName>Numerodecliente__c</fullName>
    <label>Número de cliente</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Origen__c.field-meta.xml
<CustomField>
    <fullName>Origen__c</fullName>
    <label>Origen</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Origen</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/QUOTE_Nombre_Fracc__c.field-meta.xml
<CustomField>
    <fullName>QUOTE_Nombre_Fracc__c</fullName>
    <formula>Fraccionamiento_cta__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nombre Fracc</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/RecordTypeName__c.field-meta.xml
<CustomField>
    <fullName>RecordTypeName__c</fullName>
    <formula>LEFT(RecordType.Name, FIND(&quot; &quot;, RecordType.Name))</formula>
    <label>RecordTypeName</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Sub_canal_de_venta__c.field-meta.xml
<CustomField>
    <fullName>Sub_canal_de_venta__c</fullName>
    <label>Sub canal de venta</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Canal_de_Venta__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Sub_canal_de_venta</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo de Cuenta</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospecto</fullName>
            </value>
            <value>
                <fullName>Afluente</fullName>
            </value>
            <value>
                <fullName>Cliente</fullName>
            </value>
            <value>
                <fullName>Compañía Javer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/Canal_de_Venta.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>DIGITAL ASESOR</fullName>
    </customValue>
    <customValue>
        <fullName>EVENTO</fullName>
    </customValue>
    <customValue>
        <fullName>LLAMADA CALL CENTER</fullName>
    </customValue>
    <customValue>
        <fullName>MACROVENTA</fullName>
    </customValue>
    <customValue>
        <fullName>MACROVENTA 2015</fullName>
    </customValue>
    <customValue>
        <fullName>MEDIO PUBLICITARIO</fullName>
    </customValue>
    <customValue>
        <fullName>MEDIOS DIGITALES</fullName>
    </customValue>
    <customValue>
        <fullName>PROGRAMAS INSTITUCIONALES</fullName>
    </customValue>
    <customValue>
        <fullName>PROMOTOR EXTERNO</fullName>
    </customValue>
    <customValue>
        <fullName>PROSPECCION</fullName>
    </customValue>
    <customValue>
        <fullName>PROSPECTO ASESOR</fullName>
    </customValue>
    <customValue>
        <fullName>REFERIDOS</fullName>
    </customValue>
    <customValue>
        <fullName>VENTA EMPRESARIAL</fullName>
    </customValue>
    <customValue>
        <fullName>CARGA INICIAL</fullName>
    </customValue>
    <masterLabel>Canal de Venta</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Origen.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CONTACTO JAVER</fullName>
    </customValue>
    <customValue>
        <fullName>Enfoque Comercial</fullName>
        <default>true</default>
        <label>ENFOQUE COMERCIAL</label>
    </customValue>
    <customValue>
        <fullName>SALES CLOUD</fullName>
    </customValue>
    <customValue>
        <fullName>PROSPECTO ASESOR</fullName>
    </customValue>
    <customValue>
        <fullName>MERCADOTECNIA</fullName>
    </customValue>
    <customValue>
        <fullName>AFLUENCIA</fullName>
    </customValue>
    <customValue>
        <fullName>COLABORADOR JAVER</fullName>
    </customValue>
    <customValue>
        <fullName>CONTACTO TELEFONICO</fullName>
    </customValue>
    <customValue>
        <fullName>PROSPECCION</fullName>
    </customValue>
    <customValue>
        <fullName>SMS</fullName>
    </customValue>
    <customValue>
        <fullName>Enlace</fullName>
        <label>ENLACE</label>
    </customValue>
    <masterLabel>Origen</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Sub_canal_de_venta.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1-2GUPNA8</fullName>
    </customValue>
    <customValue>
        <fullName>ACTIVACION/EVENTO</fullName>
    </customValue>
    <customValue>
        <fullName>ACTIVACION/EVENTO/PERIFERIA</fullName>
    </customValue>
    <customValue>
        <fullName>AGS FERIA CANADEVI</fullName>
    </customValue>
    <customValue>
        <fullName>AGS MOCTEZUMA</fullName>
    </customValue>
    <customValue>
        <fullName>AGS SAN DIEGO</fullName>
    </customValue>
    <customValue>
        <fullName>AGS VILLA ASUNCION</fullName>
    </customValue>
    <customValue>
        <fullName>APP INVITADO</fullName>
    </customValue>
    <customValue>
        <fullName>BLOGGER/TANIA RENDON</fullName>
    </customValue>
    <customValue>
        <fullName>BUEN FIN</fullName>
    </customValue>
    <customValue>
        <fullName>CALL CENTER/TELEMARKETING</fullName>
    </customValue>
    <customValue>
        <fullName>CAMBACEO</fullName>
    </customValue>
    <customValue>
        <fullName>CARTELERA MOVIL</fullName>
    </customValue>
    <customValue>
        <fullName>CARTELERA PV</fullName>
    </customValue>
    <customValue>
        <fullName>CARTERA DE CLIENTES</fullName>
    </customValue>
    <customValue>
        <fullName>CARTERA PROPIA</fullName>
    </customValue>
    <customValue>
        <fullName>CITA ASESOR</fullName>
    </customValue>
    <customValue>
        <fullName>COLABORADOR JAVER</fullName>
    </customValue>
    <customValue>
        <fullName>COMPAÑERO DE TRABAJO</fullName>
    </customValue>
    <customValue>
        <fullName>CONVENIO PABELLON M</fullName>
    </customValue>
    <customValue>
        <fullName>CORREO</fullName>
    </customValue>
    <customValue>
        <fullName>CORREO DIRECTO/CARTA</fullName>
    </customValue>
    <customValue>
        <fullName>EDO MEX SAMARA</fullName>
    </customValue>
    <customValue>
        <fullName>EN EMPRESA (VENTA EMPRESARIAL)</fullName>
    </customValue>
    <customValue>
        <fullName>ESPECTACULAR/CARTELERA</fullName>
    </customValue>
    <customValue>
        <fullName>EVENTO (MACROVENTA, SUPERVTA)</fullName>
    </customValue>
    <customValue>
        <fullName>EXPO/FERIA</fullName>
    </customValue>
    <customValue>
        <fullName>FACEBOOK</fullName>
    </customValue>
    <customValue>
        <fullName>FACEBOOK INBOX</fullName>
    </customValue>
    <customValue>
        <fullName>FAMILIAR</fullName>
    </customValue>
    <masterLabel>Sub canal de venta</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/AccountSearchController.cls
public class AccountSearchController { 
    @TestVisible public List<Account> acc { get; set; } 
    @TestVisible public String searchQuery { get; set; } 
    @TestVisible public String searchField { get; set; } 
    @TestVisible public String searchKey { get; set; } 

    @TestVisible public void search() {
        
        // SOQL query dynamically using the selected searchField and searchKey
        String fieldToQuery;
        if (searchField == 'NSS__c' || searchField == 'QUOTE_Nombre_Fracc__c' || searchField == 'FirstName'|| searchField == 'Apellidopaterno_cta__c' ||searchField == 'Apellidomaterno_cta__c' || 
            searchField == 'Nombre_Fraccionamiento__c' || searchField == 'Estatus_Cliente__c' || searchField == 'Nombre_del_Asesor__c' || searchField == 'CURP__c' || 
            searchField == 'Origen__c' || searchField == 'Canal_de_Venta__c' || searchField == 'Sub_canal_de_venta__c' || searchField == 'Estatus_Lista_Negra_QEQ__c' ||
             searchField == 'Numerodecliente__c' || searchField == 'Leader__c' || searchField == 'Numero_de_Cliente_AutoNum__c') {
            fieldToQuery = searchField;
        } else if ( searchField == 'FechaNacimiento_Formula__c' || searchField == 'Fecha_Asignacion_Asesor_Formula__c') 
        {
            fieldToQuery = string.valueOf(searchField) ; 
        }
        else if (searchField == 'Lead_Profiler__c') 
        {
            fieldToQuery = 'Lead_Profiler__r.Name';
        } else if (searchField == 'ParentId') 
        {
            fieldToQuery = 'Parent.Name';
        } else if (searchField == 'ParentId') 
        {
            fieldToQuery = 'Numero_de_Cliente_AutoNum__c';
        } else if (searchField == 'Tipo__c')
        {
            fieldToQuery = 'RecordTypeName__c';
        } else {
            // Default to search by Name if an invalid search field is selected
            fieldToQuery = 'Name';
        }
            String searchQuery = 'SELECT Id, Name, NSS__c, RecordTypeName__c, Estatus_Cliente__c, QUOTE_Nombre_Fracc__c, Owner.Name, Asesor__c, lastname, firstname, Nombre_Fraccionamiento__c, CreatedDate, Apellidopaterno_cta__c, Apellidomaterno_cta__c, FechaNacimiento__c, FechaNacimiento_Formula__c, Fecha_Asignacion_Asesor_Formula__c, Fecha_Asignacion_Asesor__c,Tipo__c, Nombre_del_Asesor__c, Lead_Profiler__c, CURP__c, Origen__c, Canal_de_Venta__c, Sub_canal_de_venta__c, Estatus_Lista_Negra_QEQ__c, Numerodecliente__c, Numero_de_Cliente_AutoNum__c ' +
            'FROM Account ' +
            'WHERE ' + fieldToQuery + ' LIKE \'%' + searchKey + '%\' ORDER BY CreatedDate DESC LIMIT 100';

            string whereClause = 'WHERE ' + fieldToQuery + ' LIKE \'%' + searchKey + '%\' ORDER BY CreatedDate DESC LIMIT 100';
        system.debug ('*** whereClause: '+ whereClause);

        // Execute the query and assign the results to the acc property
        acc = Database.query(searchQuery);
    }
    

    public void clear() {
        // Clear the search field and results
        searchField = '';
        searchKey = '';
        acc = null;
    }
}