unpackaged/main/default/objects/Account/fields/Asesor__c.field-meta.xml
<CustomField>
    <fullName>Asesor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asesor</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR 3</booleanFilter>
        <errorMessage>El usuario seleccionado no tiene asignado el fraccionamiento elegido.</errorMessage>
        <filterItems>
            <field>User.ProfileId</field>
            <operation>equals</operation>
            <value>00e23000000anFuAAI</value>
        </filterItems>
        <filterItems>
            <field>User.FraccionamientoAutorizados__c</field>
            <operation>contains</operation>
            <valueField>$Source.Nombre_Fraccionamiento__c</valueField>
        </filterItems>
        <filterItems>
            <field>User.ProfileId</field>
            <operation>equals</operation>
            <value>00e23000000anG0AAI</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Asesor__c.field-meta.xml
<CustomField>
    <fullName>Asesor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asesor 1</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Asesor</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Dictaminacion__c/Dictaminacion__c.object-meta.xml
<CustomObject>
    <label>Dictaminación</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Folio</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dictaminación</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Dictaminacion__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Dictaminaciones</relationshipLabel>
    <relationshipName>Dictaminaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Dictaminacion__c/fields/Asesor__c.field-meta.xml
<CustomField>
    <fullName>Asesor__c</fullName>
    <label>Asesor</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Dictaminacion__c/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Proceso de Venta</description>
    <label>Proceso de Venta</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Asesor__c.field-meta.xml
<CustomField>
    <fullName>Asesor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asesor</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>(1 OR 2) AND 3</booleanFilter>
        <filterItems>
            <field>User.Title</field>
            <operation>equals</operation>
            <value>ASESOR</value>
        </filterItems>
        <filterItems>
            <field>User.Title</field>
            <operation>equals</operation>
            <value>GENERICO</value>
        </filterItems>
        <filterItems>
            <field>User.FraccionamientoAutorizados__c</field>
            <operation>contains</operation>
            <valueField>$Source.Nombre_Fraccionamiento__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Procesos_de_Ventas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Dictaminacion__c.field-meta.xml
<CustomField>
    <fullName>Dictaminacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dictaminación</label>
    <referenceTo>Dictaminacion__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/DictaminacionController.cls
public class DictaminacionController {
    public Boolean showMessage { get; private set; }
    public String errorMessage { get; private set; }

    public String accountId { get; set; }
    public String oppId { get; set; }
    public Boolean navigateToDictaminacion { get; private set; }
    public String dictaminacionUrl { get; private set; }
    private ApexPages.StandardController standardController;
    
    public DictaminacionController(ApexPages.StandardController controller) {
       standardController = controller;
       Opportunity opportunityRecord = (Opportunity)controller.getRecord();
       oppId = opportunityRecord.Id;
       accountId = [SELECT AccountId, Id FROM Opportunity WHERE Id = :oppId].AccountId;
       system.debug('*** oppId: '+oppId);
       system.debug('*** accId: '+accountId);
    }
    
    public void createDictaminacion() {
        // Query to check if a Dictaminacion record already exists for the Opportunity.
        // Replace "Dictaminacion__c" with the actual API name of your Dictaminacion object.
        List<Dictaminacion__c> existingDictaminaciones = [SELECT Id FROM Dictaminacion__c WHERE Oportunidad__c = :standardController.getId() LIMIT 1];

        if (existingDictaminaciones.isEmpty()) {

            String AsesorName = [SELECT Asesor__r.Name FROM Account WHERE id = :accountId].Asesor__r.Name;
            system.debug ('*** AsesorName: '+AsesorName);
            Dictaminacion__c dictaminacion = new Dictaminacion__c();
            dictaminacion.Account__c = accountId;
            dictaminacion.Oportunidad__c = oppId;
            dictaminacion.Asesor__c = AsesorName;
            insert dictaminacion;
            
            navigateToDictaminacion = true;
            dictaminacionUrl = '/' + dictaminacion.Id;
        } else {
            showMessage = true;
            errorMessage = 'Ya existe una Dictaminación para este Proceso de Venta.';
        }
    }

}

/*
public class DictaminacionController {
    private ApexPages.StandardController stdController;
    public Boolean showMessage { get; private set; }
    public String errorMessage { get; private set; }

    public DictaminacionController(ApexPages.StandardController controller) {
        stdController = controller;
        showMessage = false;
        errorMessage = '';
    }

    public PageReference createDictaminacion() {
        // Query to check if a Dictaminacion record already exists for the Opportunity.
        // Replace "Dictaminacion__c" with the actual API name of your Dictaminacion object.
        List<Dictaminacion__c> existingDictaminaciones = [SELECT Id FROM Dictaminacion__c WHERE Opportunity__c = :stdController.getId() LIMIT 1];

        if (existingDictaminaciones.isEmpty()) {
            // Create a new Dictaminacion record.
            Dictaminacion__c newDictaminacion = new Dictaminacion__c();
            newDictaminacion.Opportunity__c = stdController.getId(); // Set the Opportunity reference and other required fields.
            insert newDictaminacion;
        } else {
            showMessage = true;
            errorMessage = 'A Dictaminacion record already exists for this Opportunity.';
        }

        return null;
    }
}
*/