unpackaged/main/default/objects/Account/fields/Calle__c.field-meta.xml
<CustomField>
    <fullName>Calle__c</fullName>
    <label>Calle</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo de Cuenta</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospecto</fullName>
            </value>
            <value>
                <fullName>Afluente</fullName>
            </value>
            <value>
                <fullName>Cliente</fullName>
            </value>
            <value>
                <fullName>Compañía Javer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/ValidationBypassDateTime__c.field-meta.xml
<CustomField>
    <fullName>ValidationBypassDateTime__c</fullName>
    <defaultValue>$System.OriginDateTime</defaultValue>
    <label>ValidationBypassDateTime</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Codigo_Postal__c/Codigo_Postal__c.object-meta.xml
<CustomObject>
    <label>Código Postal</label>
    <nameField>
        <label>Código Postal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Códigos Postales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Codigo_Postal__c/fields/Municipio__c.field-meta.xml
<CustomField>
    <fullName>Municipio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Municipio</label>
    <referenceTo>Municipio__c</referenceTo>
    <relationshipLabel>Códigos Postales</relationshipLabel>
    <relationshipName>Codigos_Postales</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Colonia__c/Colonia__c.object-meta.xml
<CustomObject>
    <label>Colonia</label>
    <nameField>
        <label>Colonia</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Colonias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Contrato__c/Contrato__c.object-meta.xml
<CustomObject>
    <label>Contratos</label>
    <nameField>
        <label>No. Interno</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contratos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Contrato__c/fields/Colonia__c.field-meta.xml
<CustomField>
    <fullName>Colonia__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Colonia</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Colonia__c.Codigo_Postal__c</field>
            <operation>equals</operation>
            <valueField>Colonia__c.Codigo_Postal__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Colonia__c</referenceTo>
    <relationshipLabel>Contratos</relationshipLabel>
    <relationshipName>Contratos</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contrato__c/fields/Municipio__c.field-meta.xml
<CustomField>
    <fullName>Municipio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Municipio</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Estado_Lookup__c</field>
            <operation>equals</operation>
            <valueField>Municipio__c.Estado__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Municipio__c</referenceTo>
    <relationshipLabel>Contratos</relationshipLabel>
    <relationshipName>Contratos</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Dictaminacion__c/Dictaminacion__c.object-meta.xml
<CustomObject>
    <label>Dictaminación</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Folio</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dictaminación</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Dictaminacion__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Dictaminaciones</relationshipLabel>
    <relationshipName>Dictaminaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Dictaminacion__c/fields/Direccion_Empresa__c.field-meta.xml
<CustomField>
    <fullName>Direccion_Empresa__c</fullName>
    <label>Dirección Empresa</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Dictaminacion__c/fields/ValidationBypassDateTime__c.field-meta.xml
<CustomField>
    <fullName>ValidationBypassDateTime__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <description>Actualizar este campo con cualquier valor para brincarse algunas reglas de validacion</description>
    <label>ValidationBypassDateTime</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Direcciones__c/Direcciones__c.object-meta.xml
<CustomObject>
    <label>Dirección</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Folio</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Direcciones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Direcciones__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Direcciones</relationshipLabel>
    <relationshipName>Direcciones</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Direcciones__c/fields/Calle__c.field-meta.xml
<CustomField>
    <fullName>Calle__c</fullName>
    <label>Calle</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Direcciones__c/fields/Codigo_Postal__c.field-meta.xml
<CustomField>
    <fullName>Codigo_Postal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Código Postal</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Codigo_Postal__c.Municipio__c</field>
            <operation>equals</operation>
            <valueField>$Source.Municipio__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Codigo_Postal__c</referenceTo>
    <relationshipLabel>Direcciones</relationshipLabel>
    <relationshipName>Direcciones</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Direcciones__c/fields/Colonia__c.field-meta.xml
<CustomField>
    <fullName>Colonia__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Colonia</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Colonia__c.Codigo_PostalLookup__c</field>
            <operation>equals</operation>
            <valueField>$Source.Codigo_Postal__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Colonia__c</referenceTo>
    <relationshipLabel>Direcciones</relationshipLabel>
    <relationshipName>Direcciones</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Direcciones__c/fields/Contrato__c.field-meta.xml
<CustomField>
    <fullName>Contrato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contrato</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Direcciones</relationshipLabel>
    <relationshipName>Direcciones</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Direcciones__c/fields/Dictaminacion__c.field-meta.xml
<CustomField>
    <fullName>Dictaminacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dictaminación</label>
    <referenceTo>Dictaminacion__c</referenceTo>
    <relationshipLabel>Direcciones</relationshipLabel>
    <relationshipName>Direcciones</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Direcciones__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estado</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Pais__c</field>
            <operation>equals</operation>
            <valueField>Estado__c.Pais__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Estado__c</referenceTo>
    <relationshipLabel>Direcciones</relationshipLabel>
    <relationshipName>Direcciones</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Direcciones__c/fields/Municipio__c.field-meta.xml
<CustomField>
    <fullName>Municipio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Municipio</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Estado__c</field>
            <operation>equals</operation>
            <valueField>Municipio__c.Estado__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Municipio__c</referenceTo>
    <relationshipLabel>Direcciones</relationshipLabel>
    <relationshipName>Direcciones</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Direcciones__c/fields/Numero_Exterior__c.field-meta.xml
<CustomField>
    <fullName>Numero_Exterior__c</fullName>
    <label>Número Exterior</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Direcciones__c/fields/Pais__c.field-meta.xml
<CustomField>
    <fullName>Pais__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>País</label>
    <referenceTo>Pais__c</referenceTo>
    <relationshipLabel>Direcciones</relationshipLabel>
    <relationshipName>Direcciones</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Direcciones__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Dirección Afluencia</fullName>
            </value>
            <value>
                <fullName>Dirección Principal</fullName>
            </value>
            <value>
                <fullName>Dirección Laboral</fullName>
            </value>
            <value>
                <fullName>Dirección Empresa</fullName>
            </value>
            <value>
                <fullName>Dirección Principal CO Acreditado</fullName>
            </value>
            <value>
                <fullName>Dirección Laboral CO Acreditado</fullName>
            </value>
            <value>
                <fullName>Dirección Rep Legal Laboral</fullName>
            </value>
            <value>
                <fullName>Dirección Rep Legal / Apoderado</fullName>
            </value>
            <value>
                <fullName>Dirección Tercero Persona Física</fullName>
            </value>
            <value>
                <fullName>Dirección Tercero Laboral Persona Física</fullName>
            </value>
            <value>
                <fullName>Direccion_3ro_Moral_Principal</fullName>
                <label>Dirección 3ro Moral Principal</label>
            </value>
            <value>
                <fullName>Direccion_3ro_Domicilio_Moral</fullName>
                <label>Dirección 3ro Domicilio Moral</label>
            </value>
            <value>
                <fullName>Direccion_3ro_Laboral_Moral</fullName>
                <label>Dirección 3ro Laboral Moral</label>
            </value>
            <value>
                <fullName>Dirección Cesión Principal PF</fullName>
            </value>
            <value>
                <fullName>Dirección Cesión Laboral PF</fullName>
            </value>
            <value>
                <fullName>Dirección Cesión Principal PM</fullName>
            </value>
            <value>
                <fullName>Dirección Cesión Laboral PM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Estado__c/Estado__c.object-meta.xml
<CustomObject>
    <label>Estado</label>
    <nameField>
        <label>Estado</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estados</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Estado__c/fields/Pais__c.field-meta.xml
<CustomField>
    <fullName>Pais__c</fullName>
    <label>País</label>
    <referenceTo>Pais__c</referenceTo>
    <relationshipLabel>Estados</relationshipLabel>
    <relationshipName>Estados</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Municipio__c/Municipio__c.object-meta.xml
<CustomObject>
    <label>Municipio</label>
    <nameField>
        <label>Municipio</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Municipios</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Municipio__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <referenceTo>Estado__c</referenceTo>
    <relationshipLabel>Municipios</relationshipLabel>
    <relationshipName>Municipios</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Pais__c/Pais__c.object-meta.xml
<CustomObject>
    <label>País</label>
    <nameField>
        <label>País</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Países</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/DireccionesTriggerHandler.cls
public with sharing class DireccionesTriggerHandler extends TriggerHandler{
    private Map<Id, Direcciones__c> newMap;
    private Map<Id, Direcciones__c> oldMap;
    private List<Direcciones__c> newList;
    private List<Direcciones__c> oldList;

    private final String template = 'ya existe una dirección del tipo "{0}".';
    private final String addressTemplate = 'CALLE {0} #{1}, COLONIA {2} CP: {3}, {4} {5}, {6}';
    private final String OFFICE_ADDRESS = 'Dirección Laboral';
    
    public DireccionesTriggerHandler() {
        this.newMap = (Map<Id, Direcciones__c>) trigger.newMap;
        this.oldMap = (Map<Id, Direcciones__c>) trigger.oldMap;
        this.newList = (List<Direcciones__c>) trigger.new;
        this.oldList = (List<Direcciones__c>) trigger.old;

    }

    public override void beforeInsert(){
        PreventDuplicateAddress(this.newList);
        // checkAddressCategory(this.newList);
    }

    public override void afterInsert(){
        Set<Id> officeAddressSet = new Set<Id>();
        for(Direcciones__c address : this.newList){

            if(address.Tipo__c == OFFICE_ADDRESS){
                officeAddressSet.add(
                    address.Id
                );
            }
        }

        if(!officeAddressSet.isEmpty()){
            updateContractOfficeAddress(officeAddressSet);
        }
    }

    public override void beforeUpdate(){
        List<Direcciones__c> addressList = new List<Direcciones__c>();

        for(Direcciones__c address : this.newList){
            if(oldMap.get(address.Id).Tipo__c != address.Tipo__c){
                addressList.add(address);
            }
        }

        // if(!addressList.IsEmpty()){
        //     checkAddressCategory(addressList);
        // }
    }

    public override void afterUpdate (){
        Set<Id> officeAddressSet = new Set<Id>();

        for(Direcciones__c address : this.newList){
            if(address.Tipo__c == OFFICE_ADDRESS){
                officeAddressSet.add(address.Id);
            }
        }

        if(!officeAddressSet.isEmpty()){
            updateContractOfficeAddress(officeAddressSet);
        }
    }

 /*   public void checkAddressCategory(List<Direcciones__c> addressList){
        Set<Id> contractIds = new Set<Id>();

        for(Direcciones__c address : addressList){
            if (address.Dictaminacion__c != null) {
                contractIds.add(address.Dictaminacion__c);
            }
        }

        if (contractIds.size() > 0) {
            List<Direcciones__c> registeredAddressList = [
                SELECT Id, Tipo__c, Dictaminacion__c, contrato__c
                FROM Direcciones__c 
                WHERE Dictaminacion__c IN: contractIds];

            Map<Id, Set<String>> addressCategoryByContractIds = new Map<Id,Set<String>>();
            Set<String> addressCategory;

            for(Direcciones__c address : registeredAddressList){
                addressCategory = addressCategoryByContractIds.get(address.Dictaminacion__c);

                if(addressCategory == null){
                    addressCategory = new Set<String>();
                    addressCategoryByContractIds.put(address.Dictaminacion__c, addressCategory);
                }

                addressCategory.add(address.Tipo__c);
            }

            Id contractId;
            for(Direcciones__c address : addressList){
                contractId = address.Dictaminacion__c;
                addressCategory = addressCategoryByContractIds.get(contractId);

                if(addressCategory != null && addressCategory.contains(address.Tipo__c)){

                    address.addError(
                        String.format(
                            this.template, 
                            new List<Object>{address.Tipo__c}
                            )
                        );
                }
            }
        }
    } */

    public void updateContractOfficeAddress(set<Id> officeAddressSet){
        List<Direcciones__c> addressList = [
            SELECT Id, Colonia__r.Name, 
                Calle__c, Numero_Exterior__c, Contrato__c, Dictaminacion__c,
                Codigo_Postal__r.Name, Estado__r.Name, Municipio__r.Name,
                pais__r.Name
            FROM Direcciones__c 
            WHERE Id IN : officeAddressSet];

        List<Dictaminacion__c> contractList = new List<Dictaminacion__c>();

        for(Direcciones__c address : addressList){
            if(address.Dictaminacion__c != null){
                contractList.add( new Dictaminacion__c( Id = address.Dictaminacion__c, ValidationBypassDateTime__c = DateTime.Now(), Direccion_Empresa__c = String.format( this.addressTemplate, 
                        new List<Object>{address.Calle__c,address.Numero_Exterior__c, address.Colonia__r.Name,address.Codigo_Postal__r.Name,address.Municipio__r.Name, address.Estado__r.Name,address.pais__r.Name
                                }
                            )
                    )
                );
            }
        }
 if(!contractList.isEmpty()){
            update contractList;
        }
    }
   
    public void PreventDuplicateAddress (List<Direcciones__c> addressList) {
        // Gather all account IDs from the new addresses
        Set<Id> accountIds = new Set<Id>();
        for (Direcciones__c address : addressList) {
            if (address.Account__c!=null) {
                accountIds.add(address.Account__c);
            }
        }
        if (accountIds.size()>0) {

            // Query existing addresses for the same account IDs
            Map<String, Direcciones__c> existingAddressesMap = new Map<String, Direcciones__c>();
            for (Direcciones__c existingAddress : [SELECT Id, Tipo__c, Account__c FROM Direcciones__c WHERE Account__c IN :accountIds]) {
                if (!existingAddressesMap.containsKey(existingAddress.Account__c +'|'+ existingAddress.Tipo__c )) {
                    existingAddressesMap.put(existingAddress.Account__c+'|'+ existingAddress.Tipo__c, existingAddress);
                }
            }
            system.debug('existingAddressesMap: '+existingAddressesMap);
            if (existingAddressesMap.size()>0) {       
                // Iterate over the new addresses and check for duplicates
                for (Direcciones__c newAddress : addressList) {
                    if (existingAddressesMap.containsKey(newAddress.Account__c +'|'+ newAddress.Tipo__c)) {
                        newAddress.addError('Ya existe una dirección del mismo tipo para esta Cuenta.');
                    }
                }
            }
        }
    }   
}