unpackaged/main/default/objects/Account/fields/Canal_de_Venta__c.field-meta.xml
<CustomField>
    <fullName>Canal_de_Venta__c</fullName>
    <label>Canal de Venta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Canal_de_Venta</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Check_Apellido__c.field-meta.xml
<CustomField>
    <fullName>Check_Apellido__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Check Apellido</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/CorreoElectronico__c.field-meta.xml
<CustomField>
    <fullName>CorreoElectronico__c</fullName>
    <label>Correo Electrónico</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Fraccionamiento_cta__c.field-meta.xml
<CustomField>
    <fullName>Fraccionamiento_cta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fraccionamiento</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>(1 OR 5 OR 2 OR 4 OR 6) AND 3</booleanFilter>
        <filterItems>
            <field>$User.Fraccionamiento_autorizado__c</field>
            <operation>contains</operation>
            <valueField>Fraccionamiento__c.Name</valueField>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>Administrador del sistema</value>
        </filterItems>
        <filterItems>
            <field>Fraccionamiento__c.Activo_frac__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$User.Fraccionamiento_autorizado__c</field>
            <operation>equals</operation>
            <value>TODOS</value>
        </filterItems>
        <filterItems>
            <field>$User.FraccionamientoAutorizados__c</field>
            <operation>contains</operation>
            <valueField>Fraccionamiento__c.Name</valueField>
        </filterItems>
        <filterItems>
            <field>$User.Fraccionamiento_autorizado__c</field>
            <operation>contains</operation>
            <valueField>Fraccionamiento__c.Name</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Fraccionamiento__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Otro_Telefono__c.field-meta.xml
<CustomField>
    <fullName>Otro_Telefono__c</fullName>
    <label>Otro Teléfono</label>
    <type>Phone</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Prospecto.recordType-meta.xml
<RecordType>
    <fullName>Prospecto</fullName>
    <active>true</active>
    <label>Prospecto</label>
</RecordType>

unpackaged/main/default/objects/Inventario__c/Inventario__c.object-meta.xml
<CustomObject>
    <label>Proceso ATC</label>
    <nameField>
        <label>Id Vivienda</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProcesosATC</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Inventario__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Inventarios</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Se llena con el valor del email de la cuenta asignada al ProcesoATC</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/SurveyInvitation/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Survey Invitations</relationshipLabel>
    <relationshipName>Survey_Invitations</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SurveyInvitation/fields/Last_Email__c.field-meta.xml
<CustomField>
    <fullName>Last_Email__c</fullName>
    <label>Last_Email</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/SurveyInvitation/fields/Proceso_ATC__c.field-meta.xml
<CustomField>
    <fullName>Proceso_ATC__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proceso ATC</label>
    <referenceTo>Inventario__c</referenceTo>
    <relationshipLabel>Invitaciones de encuestas</relationshipLabel>
    <relationshipName>Invitaciones_de_encuestas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/User/fields/FraccionamientoAutorizados__c.field-meta.xml
<CustomField>
    <fullName>FraccionamientoAutorizados__c</fullName>
    <label>Fraccionamiento Autorizados</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/User/fields/FRACCIONAMIENTOS__c.field-meta.xml
<CustomField>
    <fullName>FRACCIONAMIENTOS__c</fullName>
    <label>FRACCIONAMIENTOS</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ACACIAS</fullName>
            </value>
            <value>
                <fullName>ACACIAS II</fullName>
            </value>
            <value>
                <fullName>ALBERI RESIDENCIAL</fullName>
            </value>
            <value>
                <fullName>ALVENTO</fullName>
            </value>
            <value>
                <fullName>ARBOLADA</fullName>
            </value>
            <value>
                <fullName>BOSQUE REAL</fullName>
            </value>
            <value>
                <fullName>BOSQUES DEL NEVADO</fullName>
            </value>
            <value>
                <fullName>MAGNOLIAS IV</fullName>
            </value>
            <value>
                <fullName>MISION DE LOS ANGELES 1ER SECTOR ARCANGELES</fullName>
            </value>
            <value>
                <fullName>MURIEL RESIDENCIAL</fullName>
            </value>
            <value>
                <fullName>PASEO SAN JUNIPERO</fullName>
            </value>
            <value>
                <fullName>PASEOS DEL SUR</fullName>
            </value>
            <value>
                <fullName>PRIVADA BELTERRA</fullName>
            </value>
            <value>
                <fullName>PRIVADAS CARANDAY</fullName>
            </value>
            <value>
                <fullName>PRIVALIA AMBIENTA</fullName>
            </value>
            <value>
                <fullName>TODOS</fullName>
            </value>
            <value>
                <fullName>VALLE DE LINCOLN SECTOR MINAS</fullName>
            </value>
            <value>
                <fullName>VALLE DE SANTA ELENA</fullName>
            </value>
            <value>
                <fullName>VALLE DE TEJEDA II</fullName>
            </value>
            <value>
                <fullName>VALLE SANTA ISABEL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/User/fields/is_Data_Migration_User__c.field-meta.xml
<CustomField>
    <fullName>is_Data_Migration_User__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Permitir brincar reglas a los usuarios marcados como TRUE</description>
    <label>Es Usuario de Migración de Datos</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/globalValueSets/Canal_de_Venta.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>DIGITAL ASESOR</fullName>
    </customValue>
    <customValue>
        <fullName>EVENTO</fullName>
    </customValue>
    <customValue>
        <fullName>LLAMADA CALL CENTER</fullName>
    </customValue>
    <customValue>
        <fullName>MACROVENTA</fullName>
    </customValue>
    <customValue>
        <fullName>MACROVENTA 2015</fullName>
    </customValue>
    <customValue>
        <fullName>MEDIO PUBLICITARIO</fullName>
    </customValue>
    <customValue>
        <fullName>MEDIOS DIGITALES</fullName>
    </customValue>
    <customValue>
        <fullName>PROGRAMAS INSTITUCIONALES</fullName>
    </customValue>
    <customValue>
        <fullName>PROMOTOR EXTERNO</fullName>
    </customValue>
    <customValue>
        <fullName>PROSPECCION</fullName>
    </customValue>
    <customValue>
        <fullName>PROSPECTO ASESOR</fullName>
    </customValue>
    <customValue>
        <fullName>REFERIDOS</fullName>
    </customValue>
    <customValue>
        <fullName>VENTA EMPRESARIAL</fullName>
    </customValue>
    <customValue>
        <fullName>CARGA INICIAL</fullName>
    </customValue>
    <masterLabel>Canal de Venta</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/EncuestasRecordatorioDiario_Test.cls
@isTest 
public class EncuestasRecordatorioDiario_Test {
    
    @isTest(SeeAllData=true)
    public static void EncuestasRecordatorioDiario(){
        profile p = [Select Id From Profile Where Name='System Administrator'];
        User user = new User();
        user.ProfileID = p.id;
        user.EmailEncodingKey = 'ISO-8859-1';
        user.LanguageLocaleKey = 'en_US';
        user.TimeZoneSidKey = 'America/New_York';
        user.LocaleSidKey = 'en_US';
        user.is_Data_Migration_User__c = true;
        user.FirstName = 'first';
        user.LastName = 'last';
        user.Username = 'test@portal123453.com';
        user.CommunityNickname = 'testUser123';
        user.Alias = 't1';
        user.Email = 'no@email.com';
        user.IsActive = true;
        user.FRACCIONAMIENTOS__c = 'ACACIAS;ACACIAS II';
        user.FraccionamientoAutorizados__c = 'ACACIAS';
        insert user;
        System.runAs(user){   
            Account acc = new Account();
            acc.RecordTypeId =Schema.sObjectType.Account.getRecordTypeInfosBydevelopername().get('Prospecto_Persona_Fisica').getRecordTypeId();
            acc.FirstName= 'Lopez';
            acc.LastName= 'test';
            acc.Phone = '+528119928819';
            acc.Check_Apellido__c = true;
            acc.Otro_Telefono__c = '+528119928819';
            acc.Canal_de_Venta__c = 'PROSPECTO ASESOR';
            //acc.Fraccionamiento_cta__c = f.id;
            acc.CorreoElectronico__c ='test@mail.com';
            insert acc; 
            
            Inventario__c PATC = new Inventario__c();
            PATC.Cuenta__c = acc.Id;
            insert PATC;
            
            Survey S1 = [Select Id from Survey where Name = 'Entrega vivienda'];
            Survey S2 = [Select Id from Survey where Name = 'Entrega 3 meses vivienda'];
            Survey S3 = [Select Id from Survey where Name = 'Entrega 1 año'];
            
            SurveyInvitation SI1 = new SurveyInvitation();
            SI1.Name = 'TEST';
            SI1.Email__c = 'test1@test1.com';
            SI1.Proceso_ATC__c = PATC.Id;
            SI1.SurveyId = S1.Id;
            
            SurveyInvitation SI2 = new SurveyInvitation();
            SI2.Name = 'TEST';
            SI2.Email__c = 'test@test.com';
            SI2.Proceso_ATC__c = PATC.Id;
            SI2.SurveyId = S2.Id;
            
            SurveyInvitation SI3 = new SurveyInvitation();
            SI3.Name = 'TEST';
            SI3.Email__c = 'test@Test.com';
            SI3.Proceso_ATC__c = PATC.Id;
            SI3.SurveyId = S3.Id;
            
            Test.startTest();
            insert SI1; insert SI2; insert SI3;
            
            SI1.Last_Email__c = system.today().addDays(-3);
            SI1.InviteExpiryDateTime = system.today().AddDays(3);
            update SI1;
            
            SI2.Last_Email__c = system.today().addDays(-3);
            SI2.InviteExpiryDateTime = system.today().AddDays(3);
            update SI2;
            
            SI3.Last_Email__c = system.today().addDays(-3);
            SI3.InviteExpiryDateTime = system.today().AddDays(3);
            update SI3;
            
            /*EmailTemplate validEmailTemplate1 = new EmailTemplate();
            validEmailTemplate1.isActive = true;
            validEmailTemplate1.Name = 'name';
            validEmailTemplate1.DeveloperName = 'Recordatorio1';
            validEmailTemplate1.TemplateType = 'text';
            validEmailTemplate1.FolderId = UserInfo.getUserId();
            //insert validEmailTemplate1; 
            
            EmailTemplate validEmailTemplate2 = new EmailTemplate();
            validEmailTemplate2.isActive = true;
            validEmailTemplate2.Name = 'name';
            validEmailTemplate2.DeveloperName = 'Recordatorio2';
            validEmailTemplate2.TemplateType = 'text';
            validEmailTemplate2.FolderId = UserInfo.getUserId();
            //insert validEmailTemplate2;
            
            EmailTemplate validEmailTemplate3 = new EmailTemplate();
            validEmailTemplate3.isActive = true;
            validEmailTemplate3.Name = 'name';
            validEmailTemplate3.DeveloperName = 'Recordatorio3';
            validEmailTemplate3.TemplateType = 'text';
            validEmailTemplate3.FolderId = UserInfo.getUserId();
            
            //insert validEmailTemplate3;*/
            SchedulableContext sc = null;
            EncuestasRecordatorioSchedule tsc = new EncuestasRecordatorioSchedule();
            tsc.execute(sc);
            Test.stopTest();
        }
    }
}