unpackaged/main/default/objects/Account/fields/CanalVenta__c.field-meta.xml
<CustomField>
    <fullName>CanalVenta__c</fullName>
    <label>Canal de Venta1</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>AccountSource</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Prospección</fullName>
                <default>true</default>
                <label>Prospección</label>
            </value>
            <value>
                <fullName>Llamada Call Center</fullName>
            </value>
            <value>
                <fullName>Medio Publicitario</fullName>
            </value>
            <value>
                <fullName>Medios Digitales</fullName>
            </value>
            <value>
                <fullName>Programas Institucionales</fullName>
            </value>
            <value>
                <fullName>Referidos</fullName>
            </value>
            <value>
                <fullName>Prospecto Asesor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/FechaEscrituracion__c.field-meta.xml
<CustomField>
    <fullName>FechaEscrituracion__c</fullName>
    <label>Fecha de Escrituración</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Fraccionamiento_cta__c.field-meta.xml
<CustomField>
    <fullName>Fraccionamiento_cta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fraccionamiento</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>(1 OR 5 OR 2 OR 4 OR 6) AND 3</booleanFilter>
        <filterItems>
            <field>$User.Fraccionamiento_autorizado__c</field>
            <operation>contains</operation>
            <valueField>Fraccionamiento__c.Name</valueField>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>Administrador del sistema</value>
        </filterItems>
        <filterItems>
            <field>Fraccionamiento__c.Activo_frac__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$User.Fraccionamiento_autorizado__c</field>
            <operation>equals</operation>
            <value>TODOS</value>
        </filterItems>
        <filterItems>
            <field>$User.FraccionamientoAutorizados__c</field>
            <operation>contains</operation>
            <valueField>Fraccionamiento__c.Name</valueField>
        </filterItems>
        <filterItems>
            <field>$User.Fraccionamiento_autorizado__c</field>
            <operation>contains</operation>
            <valueField>Fraccionamiento__c.Name</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Fraccionamiento__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/JMC_AsesorAsignado__c.field-meta.xml
<CustomField>
    <fullName>JMC_AsesorAsignado__c</fullName>
    <label>Asesor Asignado</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/JMC_Fecha_Afluencia__c.field-meta.xml
<CustomField>
    <fullName>JMC_Fecha_Afluencia__c</fullName>
    <label>Fecha Afluencia</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/JMC_Fecha_Cancelacion__c.field-meta.xml
<CustomField>
    <fullName>JMC_Fecha_Cancelacion__c</fullName>
    <label>Fecha Cancelacion</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/JMC_Fecha_Entrega__c.field-meta.xml
<CustomField>
    <fullName>JMC_Fecha_Entrega__c</fullName>
    <label>Fecha Entrega</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/JMC_Fecha_Visita__c.field-meta.xml
<CustomField>
    <fullName>JMC_Fecha_Visita__c</fullName>
    <label>Fecha Visita</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/JMC_Lote__c.field-meta.xml
<CustomField>
    <fullName>JMC_Lote__c</fullName>
    <label>Lote</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/JMC_Manzana__c.field-meta.xml
<CustomField>
    <fullName>JMC_Manzana__c</fullName>
    <label>Manzana</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/NSS__c.field-meta.xml
<CustomField>
    <fullName>NSS__c</fullName>
    <inlineHelpText>Obligatorio en Crédito Infonavit o Cofinavit</inlineHelpText>
    <label>NSS</label>
    <length>11</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Account/fields/Sexo__c.field-meta.xml
<CustomField>
    <fullName>Sexo__c</fullName>
    <label>Sexo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sexo</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/SubCanalVenta__c.field-meta.xml
<CustomField>
    <fullName>SubCanalVenta__c</fullName>
    <label>Sub Canal de Venta 1</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CanalVenta__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Activación/Evento</fullName>
            </value>
            <value>
                <fullName>Activación/Evento/Periferia</fullName>
            </value>
            <value>
                <fullName>AGS Feria CANADEVI</fullName>
            </value>
            <value>
                <fullName>AGS Moctezuma</fullName>
            </value>
            <value>
                <fullName>AGS Plaza Universidad</fullName>
            </value>
            <value>
                <fullName>AGS San Diego</fullName>
            </value>
            <value>
                <fullName>Ags Villa Asunción</fullName>
            </value>
            <value>
                <fullName>Blogger/Tania Rendón</fullName>
            </value>
            <value>
                <fullName>Call Center / Telemarketing</fullName>
            </value>
            <value>
                <fullName>Cambaceo</fullName>
            </value>
            <value>
                <fullName>Cartelera Móvil</fullName>
            </value>
            <value>
                <fullName>CETRAM Rosario</fullName>
            </value>
            <value>
                <fullName>Cita Asesor</fullName>
            </value>
            <value>
                <fullName>Colaborador Javer</fullName>
            </value>
            <value>
                <fullName>Compañero de Trabajo</fullName>
            </value>
            <value>
                <fullName>Contacto Telefónico</fullName>
            </value>
            <value>
                <fullName>Convenio Femsa</fullName>
            </value>
            <value>
                <fullName>Convenio Pabellon M</fullName>
            </value>
            <value>
                <fullName>Correo</fullName>
            </value>
            <value>
                <fullName>Correo Directo/Carta</fullName>
            </value>
            <value>
                <fullName>Edomex Expo Tu Casa Total WTC</fullName>
            </value>
            <value>
                <fullName>Edomex Feria Canadevi Tlanepantla</fullName>
            </value>
            <value>
                <fullName>Edo Mex Galerias Perinorte</fullName>
            </value>
            <value>
                <fullName>Edomex Plaza Juarez</fullName>
            </value>
            <value>
                <fullName>En Calle</fullName>
            </value>
            <value>
                <fullName>En Empresa (Venta Empresarial)</fullName>
            </value>
            <value>
                <fullName>Espectacular/Cartelera</fullName>
            </value>
            <value>
                <fullName>Eventos (Macroventa, Súpervta)</fullName>
            </value>
            <value>
                <fullName>Expo/Feria</fullName>
            </value>
            <value>
                <fullName>Facebook</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/TelefonoCelular__c.field-meta.xml
<CustomField>
    <fullName>TelefonoCelular__c</fullName>
    <label>Teléfono Celular</label>
    <type>Phone</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo de Cuenta</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospecto</fullName>
            </value>
            <value>
                <fullName>Afluente</fullName>
            </value>
            <value>
                <fullName>Cliente</fullName>
            </value>
            <value>
                <fullName>Compañía Javer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/TipoCredito__c.field-meta.xml
<CustomField>
    <fullName>TipoCredito__c</fullName>
    <label>Tipo de crédito2</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BANCO - SOFOL</fullName>
            </value>
            <value>
                <fullName>BANJERCITO</fullName>
            </value>
            <value>
                <fullName>CAJA FLORENCIO ROSAS</fullName>
            </value>
            <value>
                <fullName>CONTADO</fullName>
            </value>
            <value>
                <fullName>CONTINGENCIA</fullName>
            </value>
            <value>
                <fullName>FOVISSSTE</fullName>
            </value>
            <value>
                <fullName>INFONAVIT</fullName>
            </value>
            <value>
                <fullName>ISSFAM</fullName>
            </value>
            <value>
                <fullName>ISSSTELEON</fullName>
            </value>
            <value>
                <fullName>SHF/BANCO</fullName>
            </value>
            <value>
                <fullName>PENSIONES</fullName>
            </value>
            <value>
                <fullName>COFINAVIT</fullName>
            </value>
            <value>
                <fullName>BANSEFI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/JMC_Analisisinterno__c.field-meta.xml
<CustomField>
    <fullName>JMC_Analisisinterno__c</fullName>
    <description>Campo que detona las reglas en las etapas de prospección y el envío a MAS Comercial.</description>
    <label>Análisis interno</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Asesor externo</fullName>
            </value>
            <value>
                <fullName>Aumento de crédito</fullName>
            </value>
            <value>
                <fullName>Baja</fullName>
            </value>
            <value>
                <fullName>Buscando opciones</fullName>
            </value>
            <value>
                <fullName>Compra a largo plazo</fullName>
            </value>
            <value>
                <fullName>En atención</fullName>
                <label>En atención en fracc</label>
            </value>
            <value>
                <fullName>Error registro</fullName>
            </value>
            <value>
                <fullName>Existe</fullName>
            </value>
            <value>
                <fullName>Mailing WhatsApp</fullName>
                <label>Mailing whatsapp</label>
            </value>
            <value>
                <fullName>Mensaje error Infonavit</fullName>
            </value>
            <value>
                <fullName>No contesta</fullName>
            </value>
            <value>
                <fullName>No lo conocen</fullName>
            </value>
            <value>
                <fullName>No validado</fullName>
            </value>
            <value>
                <fullName>Numero invalido</fullName>
                <label>Número inválido</label>
            </value>
            <value>
                <fullName>Numero suspendido</fullName>
                <label>Número suspendido</label>
            </value>
            <value>
                <fullName>Perfilado</fullName>
            </value>
            <value>
                <fullName>Personas mayores</fullName>
            </value>
            <value>
                <fullName>Producto</fullName>
            </value>
            <value>
                <fullName>Puntos posteriores</fullName>
            </value>
            <value>
                <fullName>Referencias</fullName>
            </value>
            <value>
                <fullName>Registro renta</fullName>
            </value>
            <value>
                <fullName>Sin capacidad de compra</fullName>
            </value>
            <value>
                <fullName>Sin confirmar</fullName>
            </value>
            <value>
                <fullName>Sin oferta de vivienda</fullName>
            </value>
            <value>
                <fullName>Sin validar</fullName>
            </value>
            <value>
                <fullName>Tipo de crédito</fullName>
            </value>
            <value>
                <fullName>Ubicación</fullName>
            </value>
            <value>
                <fullName>No existe</fullName>
                <isActive>false</isActive>
                <label>No existe</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/JMC_AsesorAsignado__c.field-meta.xml
<CustomField>
    <fullName>JMC_AsesorAsignado__c</fullName>
    <description>Campo para asignar el nombre del asesor que dará seguimiento al lead</description>
    <label>Asesor Asignado</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/JMC_Lote__c.field-meta.xml
<CustomField>
    <fullName>JMC_Lote__c</fullName>
    <description>Número de lote de la ubicación reservada</description>
    <label>Lote</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/JMC_Manzana__c.field-meta.xml
<CustomField>
    <fullName>JMC_Manzana__c</fullName>
    <description>Manzana de la ubicación reservada</description>
    <label>Manzana</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/JMC_ValidardatosSiebel__c.field-meta.xml
<CustomField>
    <fullName>JMC_ValidardatosSiebel__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo para detonar el envío a MAS Comercial o reprocesar un registro</description>
    <label>Validar datos Siebel</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/globalValueSets/Sexo.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>MASCULINO</fullName>
    </customValue>
    <customValue>
        <fullName>FEMENINO</fullName>
    </customValue>
    <customValue>
        <fullName>NO BINARIO</fullName>
    </customValue>
    <masterLabel>Sexo</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/AccountHandler_ctrl.cls
global class AccountHandler_ctrl {
    
    
     /*
    * @description método realiza la validación de criterios para ejecutar el WS
    * @param List<Lead> arrLeadsN
    * @param List<Lead> arrLeadso
    * @param Map<Id, Lead> newLeadMap
    * @param Map<Id, Lead> oldLeadMap
    * @return "Metodo void"
    */
    global static void valWSUpd(List<Lead> arrLeadsN, List<Lead> arrLeadso, Map<Id, Lead> newLeadMap , Map<Id, Lead> oldLeadMap) {
        for(Lead l : arrLeadsN){
            if((String.isNotBlank(l.JMC_Analisisinterno__c) && l.JMC_Analisisinterno__c.equals('Perfilado'))
              && (!oldLeadMap.get(l.Id).Status.equals('Envío MAS Comercial') && l.Status.equals('Envío MAS Comercial'))) {
             //   LeadHandler_cls.executeWS(l.Id);
            }
            if(String.isNotBlank(l.JMC_Analisisinterno__c) && l.JMC_Analisisinterno__c.equals('Perfilado') 
               && (!oldLeadMap.get(l.Id).JMC_ValidardatosSiebel__c && l.JMC_ValidardatosSiebel__c)) {
             //   LeadHandler_cls.executeWS(l.Id);
            }
        }
    }
    
    /*
    * @description parsea el objeto json y almacena los datos en objetos custom Salesforce.
    * @param String json
    * @return String strResponse
    */
    public Map<String,String> upAccount(Map<String, Object> mapJson) {
        final Map<String,String> mapResponse =  new  Map<String,String>();
        String mail = LeadsUtils_ctrl.validaDatoVacio((String)mapJson.get('mailLead'));
        System.debug(mail);
        boolean notProcess = true;
        Account l = new Account();
        List<Account> lstAcct = new List<Account>();
        if(String.isNotBlank(mail)) {
            lstAcct = AccountUtils_ctrl.getObjAccount(mail); 
            if(lstAcct!=null && lstAcct.size()>0){
                l = lstAcct[0];
                notProcess =false;
            }            
        }
        if(notProcess) {
            mapResponse.put('idRespuesta', '2');          
            mapResponse.put('respuesta', 'Mail es requerido para poder realizar la actualización');          
            mapResponse.put('idSalesforce','');
        } else {
            l.PersonBirthdate = String.isNotBlank((String)mapJson.get('fechaNac')) ? LeadsUtils_ctrl.getDate((String)mapJson.get('fechaNac')) : l.PersonBirthdate;
            l.FirstName = String.isNotBlank((String)mapJson.get('nombre')) ? String.valueOf((String)mapJson.get('nombre')) : l.FirstName;
            /*l.Middlename = String.isNotBlank((String)mapJson.get('apellidoPaterno')) ? String.valueOf((String)mapJson.get('apellidoPaterno')) : l.Middlename;*/
            l.LastName = String.isNotBlank((String)mapJson.get('apellidoMaterno')) ? String.valueOf((String)mapJson.get('apellidoMaterno')) : l.LastName;
            l.JMC_AsesorAsignado__c = String.isNotBlank((String)mapJson.get('asesor')) ? (String)mapJson.get('asesor') : l.JMC_AsesorAsignado__c;
            l.CanalVenta__c = String.isNotBlank((String)mapJson.get('canalVenta')) ? (String)mapJson.get('canalVenta') : l.CanalVenta__c;
            l.SubCanalVenta__c = String.isNotBlank((String)mapJson.get('subCanal')) ? (String)mapJson.get('subCanal') : l.SubCanalVenta__c;
            l.Tipo__c = String.isNotBlank((String)mapJson.get('estatusCliente')) ? (String)mapJson.get('estatusCliente') : l.Tipo__c; 
            String fracName =  LeadsUtils_ctrl.validaDatoVacio((String)mapJson.get('fraccionamiento'));
            if(String.isNotBlank(fracName)){
                Fraccionamiento__c frac = LeadsUtils_ctrl.getFracc(fracName);
                l.Fraccionamiento_cta__c = frac.Id;
            }
            l.Sexo__c = String.isNotBlank((String)mapJson.get('genero')) ? (String)mapJson.get('genero') : l.Sexo__c;
            l.PersonEmail = String.isNotBlank((String)mapJson.get('mailLead')) ? (String)mapJson.get('mailLead') : l.PersonEmail;
            l.NSS__c = String.isNotBlank((String)mapJson.get('nss')) ? (String)mapJson.get('nss') : l.NSS__c;
            l.phone = String.isNotBlank((String)mapJson.get('phone')) ? LeadsUtils_ctrl.getFilteredPhone((String)mapJson.get('phone')) : l.phone;
            l.PersonHomePhone = String.isNotBlank((String)mapJson.get('telefono')) ? LeadsUtils_ctrl.getFilteredPhone((String)mapJson.get('telefono')) : l.PersonHomePhone;
            l.TelefonoCelular__c = String.isNotBlank((String)mapJson.get('telefono')) ? LeadsUtils_ctrl.getFilteredPhone((String)mapJson.get('telefono')) : l.TelefonoCelular__c;
            l.TipoCredito__c = String.isNotBlank((String)mapJson.get('tipoCredito')) ? (String)mapJson.get('tipoCredito') : l.TipoCredito__c;
            l.JMC_Fecha_Visita__c = String.isNotBlank((String)mapJson.get('fechaVisita')) ? LeadsUtils_ctrl.getDate((String)mapJson.get('fechaVisita')) : l.JMC_Fecha_Visita__c;
            l.JMC_Fecha_Afluencia__c = String.isNotBlank((String)mapJson.get('fechaAfluencia')) ? LeadsUtils_ctrl.getDate((String)mapJson.get('fechaAfluencia')) : l.JMC_Fecha_Afluencia__c;
            l.JMC_Lote__c = String.isNotBlank((String)mapJson.get('lote')) ? ((String)mapJson.get('lote')) : l.JMC_Lote__c;
            l.JMC_Manzana__c = String.isNotBlank((String)mapJson.get('manzana')) ? ((String)mapJson.get('manzana')) : l.JMC_Manzana__c;
            l.JMC_Fecha_Cancelacion__c = String.isNotBlank((String)mapJson.get('fechaCancelacion')) ? LeadsUtils_ctrl.getDate((String)mapJson.get('fechaCancelacion')) : l.JMC_Fecha_Cancelacion__c;
            l.FechaEscrituracion__c = String.isNotBlank((String)mapJson.get('fechaEscrituracion')) ? LeadsUtils_ctrl.getDate((String)mapJson.get('fechaEscrituracion')) : l.FechaEscrituracion__c;
            l.JMC_Fecha_Entrega__c = String.isNotBlank((String)mapJson.get('fechaEntrega')) ? LeadsUtils_ctrl.getDate((String)mapJson.get('fechaEntrega')) : l.JMC_Fecha_Entrega__c;
            l.FechaReserva__c = String.isNotBlank((String)mapJson.get('fechaReserva')) ? LeadsUtils_ctrl.getDate((String)mapJson.get('fechaReserva')) : l.FechaReserva__c;
            l.NumeroInterior__c = String.isNotBlank((String)mapJson.get('numeroInterior')) ? (String)mapJson.get('numeroInterior') : l.NumeroInterior__c;
            l.NumProceso__c = String.isNotBlank((String)mapJson.get('numeroProceso')) ? (String)mapJson.get('numeroProceso') : l.NumProceso__c;
            l.EstatusProceso__c = String.isNotBlank((String)mapJson.get('estatusProceso')) ? (String)mapJson.get('estatusProceso') : l.EstatusProceso__c;
            //l.JMC_Estatus_Proceso__c = String.isNotBlank((String)mapJson.get('EstatusProceso')) ? (String)mapJson.get('EstatusProceso') : l.JMC_Estatus_Proceso__c;
            l.Numerodecliente__c = String.isNotBlank((String)mapJson.get('numeroCliente')) ? (String)mapJson.get('numeroCliente') : l.Numerodecliente__c;
            l.NumCliente__c = String.isNotBlank((String)mapJson.get('numeroCliente')) ? (String)mapJson.get('numeroCliente') : l.NumCliente__c;
            l.FechaFormalizacion__c = String.isNotBlank((String)mapJson.get('fechaFormalizacion')) ? LeadsUtils_ctrl.getDate((String)mapJson.get('fechaFormalizacion')) : l.FechaFormalizacion__c;

            
            
            String leadName = LeadsUtils_ctrl.validaDatoVacio((String)mapJson.get('leadProfiler'));
            if(String.isNotBlank(leadName)){
                //User usr = LeadsUtils_ctrl.getUser(leadName);
                //l.OwnerId = usr.Id;
            }
            update l;
            mapResponse.put('idRespuesta', '0');          
            mapResponse.put('respuesta', 'Actualización de Account exitosa');          
            mapResponse.put('idSalesforce',l.Id);
        } 
        return mapResponse;
    }
    
    /*
    * @description método realiza la conversión de un account al objeto del WS SOAP
    * @param String idLead
    * @return SalesforceLeads_SOAP.leads lstLead 
    */
    public LeadService_SOAP.leads mapConstLead(Account objAccount) { 
        LeadService_SOAP.leads lstLeads = new LeadService_SOAP.leads();
        LeadService_SOAP.lead objLead = new LeadService_SOAP.lead();
        if(objAccount!=null){
            objLead.SalesForceId = objAccount.Id;
            /*objLead.NombreCompleto =  objAccount.FirstName + ' '+objAccount.MiddleName+ ' '+objAccount.LastName;*/
            objLead.NombreCompleto =  objAccount.FirstName + ' '+objAccount.LastName;
            objLead.LeadProfiler = objAccount.Owner.Name; 
            objLead.EstatusLead =  objAccount.JMC_EstatusLead__c;
            objLead.Asesor =  objAccount.Asesor__c;
            objLead.EstatusProceso =  objAccount.EstatusProceso__c;
            objLead.Nombre =  objAccount.FirstName;
            /*objLead.ApellidoPaterno =  objAccount.MiddleName;*/
            objLead.ApellidoMaterno =  objAccount.lastname;
            objLead.FechaNacimiento =  objAccount.FechaNacimiento__c!= null ? String.valueof(objAccount.FechaNacimiento__c) : '';            
            objLead.TelefonoOtro =  objAccount.PersonMobilePhone;
            objLead.Telefono =  objAccount.PersonHomePhone;
            objLead.MailLead =  objAccount.PersonEmail;
            objLead.TipoCredito =  objAccount.TipoCredito__c;
            objLead.NSS =  objAccount.NSS__c; 
            objLead.Genero =  objAccount.Sexo__c; 
            objLead.Fraccionamiento =  objAccount.Fraccionamiento_cta__r.Name;
            objLead.CanalVenta =  objAccount.CanalVenta__c;
            objLead.SubCanal =  objAccount.SubCanalVenta__c;
            System.debug(objLead);
            lstLeads.Lead = objLead;   
        }
        System.debug(lstLeads);
        return lstLeads; 
    }
    
    
}