unpackaged/main/default/objects/Account/fields/Canal_de_Venta__c.field-meta.xml
<CustomField>
    <fullName>Canal_de_Venta__c</fullName>
    <label>Canal de Venta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Canal_de_Venta</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Check_Apellido__c.field-meta.xml
<CustomField>
    <fullName>Check_Apellido__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Check Apellido</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Entrega__c.field-meta.xml
<CustomField>
    <fullName>Entrega__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Entrega</label>
    <referenceTo>Entrega__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Otro_Telefono__c.field-meta.xml
<CustomField>
    <fullName>Otro_Telefono__c</fullName>
    <label>Otro Teléfono</label>
    <type>Phone</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Prospecto.recordType-meta.xml
<RecordType>
    <fullName>Prospecto</fullName>
    <active>true</active>
    <label>Prospecto</label>
</RecordType>

unpackaged/main/default/objects/Entrega__c/Entrega__c.object-meta.xml
<CustomObject>
    <label>Entrega</label>
    <nameField>
        <label>Nombre de Entrega</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entregas</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Entrega__c/fields/FechaEntrega__c.field-meta.xml
<CustomField>
    <fullName>FechaEntrega__c</fullName>
    <label>Fecha de Entrega</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Entrega__c/fields/Inventario__c.field-meta.xml
<CustomField>
    <fullName>Inventario__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventario</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Inventario__c.Cuenta__c</field>
            <operation>equals</operation>
            <valueField>$Source.Cuenta__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Estatus__c</field>
            <operation>equals</operation>
            <value>Cancelado</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Inventario__c</referenceTo>
    <relationshipLabel>Entregas</relationshipLabel>
    <relationshipName>Entregas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/Inventario__c.object-meta.xml
<CustomObject>
    <label>Proceso ATC</label>
    <nameField>
        <label>Id Vivienda</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProcesosATC</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Inventario__c/fields/FechaEntrega__c.field-meta.xml
<CustomField>
    <fullName>FechaEntrega__c</fullName>
    <label>Fecha de Entrega</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/globalValueSets/Canal_de_Venta.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>DIGITAL ASESOR</fullName>
    </customValue>
    <customValue>
        <fullName>EVENTO</fullName>
    </customValue>
    <customValue>
        <fullName>LLAMADA CALL CENTER</fullName>
    </customValue>
    <customValue>
        <fullName>MACROVENTA</fullName>
    </customValue>
    <customValue>
        <fullName>MACROVENTA 2015</fullName>
    </customValue>
    <customValue>
        <fullName>MEDIO PUBLICITARIO</fullName>
    </customValue>
    <customValue>
        <fullName>MEDIOS DIGITALES</fullName>
    </customValue>
    <customValue>
        <fullName>PROGRAMAS INSTITUCIONALES</fullName>
    </customValue>
    <customValue>
        <fullName>PROMOTOR EXTERNO</fullName>
    </customValue>
    <customValue>
        <fullName>PROSPECCION</fullName>
    </customValue>
    <customValue>
        <fullName>PROSPECTO ASESOR</fullName>
    </customValue>
    <customValue>
        <fullName>REFERIDOS</fullName>
    </customValue>
    <customValue>
        <fullName>VENTA EMPRESARIAL</fullName>
    </customValue>
    <customValue>
        <fullName>CARGA INICIAL</fullName>
    </customValue>
    <masterLabel>Canal de Venta</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/EnviarCorreoEntrega_Test.cls
@isTest
public class EnviarCorreoEntrega_Test {
    static TestMethod void testMethod1(){
        Account acc = new Account();
        acc.Name = 'CUENTA ASIGNACION GENERICA';
        acc.Phone = '+528119928819';
        acc.Check_Apellido__c = true;
        acc.Otro_Telefono__c = '+528119928819';
        acc.Canal_de_Venta__c = 'PROSPECTO ASESOR';
        insert acc;
        Inventario__c inventario = new Inventario__c();
        inventario.Name = 'Test Inventario';
        insert inventario;
        contact con = new contact();
        con.FirstName = 'Test';
        con.LastName = 'Contact';
        con.Email = 'test@mail.com';
        insert con;
        Entrega__c entrega = new Entrega__c();
        entrega.Inventario__c = inventario.Id;
        entrega.FechaEntrega__c = Date.today();
        insert entrega;
        Blob bodyBlob=Blob.valueOf('Unit Test ContentVersion Body'); 
        ContentVersion contentVersion_1 = new ContentVersion(  Title='Header_Picture1',    PathOnClient ='test.pdf',VersionData = bodyBlob,   origin = 'H'  );
        insert contentVersion_1;
        Id conDocId = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =:contentVersion_1.Id].ContentDocumentId;
        
        ContentDocumentLink cdl = New ContentDocumentLink();
        cdl.LinkedEntityId = entrega.Id;
        cdl.ContentDocumentId = conDocId;
        cdl.shareType = 'V';
        Insert cdl;
        Test.startTest();
        EnviarCorreoEntrega.run(inventario.Id, JSON.serialize(entrega));
        Test.stopTest();
    }
    
}