unpackaged/main/default/objects/Account/fields/Capcomp_cta__c.field-meta.xml
<CustomField>
    <fullName>Capcomp_cta__c</fullName>
    <formula>Capcom_cta__c + Saldsub_cta__c +  Monaho_cta__c  +Montgast_cta__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>CapacidadCompra__c + SaldoSubCuenta__c + Monto Ahorro voluntario + MontoGastoTitulacionOperaci</inlineHelpText>
    <label>Capacidad de compra total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Fraccionamiento_cta__c.field-meta.xml
<CustomField>
    <fullName>Fraccionamiento_cta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fraccionamiento</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>(1 OR 5 OR 2 OR 4 OR 6) AND 3</booleanFilter>
        <filterItems>
            <field>$User.Fraccionamiento_autorizado__c</field>
            <operation>contains</operation>
            <valueField>Fraccionamiento__c.Name</valueField>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>Administrador del sistema</value>
        </filterItems>
        <filterItems>
            <field>Fraccionamiento__c.Activo_frac__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$User.Fraccionamiento_autorizado__c</field>
            <operation>equals</operation>
            <value>TODOS</value>
        </filterItems>
        <filterItems>
            <field>$User.FraccionamientoAutorizados__c</field>
            <operation>contains</operation>
            <valueField>Fraccionamiento__c.Name</valueField>
        </filterItems>
        <filterItems>
            <field>$User.Fraccionamiento_autorizado__c</field>
            <operation>contains</operation>
            <valueField>Fraccionamiento__c.Name</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Fraccionamiento__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Monaho_cta__c.field-meta.xml
<CustomField>
    <fullName>Monaho_cta__c</fullName>
    <label>Monto ahorro voluntario</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Montgast_cta__c.field-meta.xml
<CustomField>
    <fullName>Montgast_cta__c</fullName>
    <label>Monto gasto por titulación y operación</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Fraccionamiento__c/Fraccionamiento__c.object-meta.xml
<CustomObject>
    <label>Fraccionamiento</label>
    <nameField>
        <label>Nombre de Fraccionamiento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fraccionamientos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Fraccionamiento__c/fields/Activo_frac__c.field-meta.xml
<CustomField>
    <fullName>Activo_frac__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Fraccionamiento__c/fields/Id_Mas_Comercial__c.field-meta.xml
<CustomField>
    <fullName>Id_Mas_Comercial__c</fullName>
    <label>Id Mas Comercial</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Fraccionamiento__c/fields/Prototipo__c.field-meta.xml
<CustomField>
    <fullName>Prototipo__c</fullName>
    <label>Prototipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prototipo 1</fullName>
            </value>
            <value>
                <fullName>Prototipo 2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Prototipo__c/Prototipo__c.object-meta.xml
<CustomObject>
    <label>Prototipo</label>
    <nameField>
        <label>Prototipo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prototipos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Prototipo__c/fields/Fraccionamiento__c.field-meta.xml
<CustomField>
    <fullName>Fraccionamiento__c</fullName>
    <label>Fraccionamiento</label>
    <referenceTo>Fraccionamiento__c</referenceTo>
    <relationshipLabel>Prototipos</relationshipLabel>
    <relationshipName>Prototipos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Prototipo__c/fields/Id_Mas_Comercial__c.field-meta.xml
<CustomField>
    <fullName>Id_Mas_Comercial__c</fullName>
    <label>Id Mas Comercial</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Prototipo__c/fields/Imagen_01__c.field-meta.xml
<CustomField>
    <fullName>Imagen_01__c</fullName>
    <label>Imagen 01</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/Prototipo__c/fields/Imagen_02__c.field-meta.xml
<CustomField>
    <fullName>Imagen_02__c</fullName>
    <label>Imagen 02</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/Prototipo__c/fields/Precio_pro__c.field-meta.xml
<CustomField>
    <fullName>Precio_pro__c</fullName>
    <label>Precio</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Prototipo__c/fields/Tour_360__c.field-meta.xml
<CustomField>
    <fullName>Tour_360__c</fullName>
    <label>Tour 360</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/Simulador_N__c/Simulador_N__c.object-meta.xml
<CustomObject>
    <label>Simulador_N</label>
    <nameField>
        <label>Nombre de Simulador_N</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Simuladores_N</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Simulador_N__c/fields/CapacidadCompra__c.field-meta.xml
<CustomField>
    <fullName>CapacidadCompra__c</fullName>
    <label>CapacidadCompra</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Simulador_N__c/fields/Fraccionamiento__c.field-meta.xml
<CustomField>
    <fullName>Fraccionamiento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fraccionamiento</label>
    <referenceTo>Fraccionamiento__c</referenceTo>
    <relationshipLabel>Simuladores_N</relationshipLabel>
    <relationshipName>Simuladores_N</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/User/fields/Fraccionamiento_autorizado__c.field-meta.xml
<CustomField>
    <fullName>Fraccionamiento_autorizado__c</fullName>
    <inlineHelpText>Al poner la Palabra TODOS 
lo que dará acceso a cualquier fracc.</inlineHelpText>
    <label>Fraccionamiento autorizado</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/User/fields/FraccionamientoAutorizados__c.field-meta.xml
<CustomField>
    <fullName>FraccionamientoAutorizados__c</fullName>
    <label>Fraccionamiento Autorizados</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/User/fields/Id_Mas_Comercial__c.field-meta.xml
<CustomField>
    <fullName>Id_Mas_Comercial__c</fullName>
    <label>Id Mas Comercial</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/User/fields/User_Mas_Comercial__c.field-meta.xml
<CustomField>
    <fullName>User_Mas_Comercial__c</fullName>
    <inlineHelpText>No borrar es LOGIN de mas comercial</inlineHelpText>
    <label>User Mas Comercial</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/SimuladorController.cls
public class SimuladorController{

    public Simulador_N__c simulador {get;set;}
    public Account cuenta {get;set;}
    public Fraccionamiento__c fraccionamiento{get;set;}
    public Double capacidadCompra {get;set;}
    public List<Prototipo__c> prototipos {get;set;}
    public List<SelectOption> fraccs {get;set;}
    public String muestro {get;set;}
    
    public SimuladorController(){
        
    }
    
    public SimuladorController(ApexPages.StandardController controller) {
        
        simulador=(Simulador_N__c)controller.getRecord();
        
		User usuario = [SELECT Id, Name, User_Mas_Comercial__c, Id_Mas_Comercial__c, Fraccionamiento_autorizado__c, FraccionamientoAutorizados__c  FROM User WHERE Id =: UserInfo.getUserId() LIMIT 1];
         List<Fraccionamiento__c> fraccs1 = new List<Fraccionamiento__c>();
        List<String> nombresFracc = new List<String>(); 
        if('Admin Javer' == usuario.Name || usuario.Fraccionamiento_autorizado__c == 'TODOS'){
            fraccs1 = [Select Id, Name FROM Fraccionamiento__c]; 
         }else{
         try{
            nombresFracc.add(usuario.FraccionamientoAutorizados__c);
            nombresFracc.add(usuario.Fraccionamiento_autorizado__c);
         	try{
                nombresFracc.addAll(usuario.Fraccionamiento_autorizado__c.split(', '));
            }catch(Exception o){
                     
            }
            try{
                nombresFracc.addAll(usuario.FraccionamientoAutorizados__c.split(', '));
            }catch(Exception o){
                     
            }   
             
        	fraccs1 = [Select Id, Name FROM Fraccionamiento__c WHERE Name IN : nombresFracc AND Activo_frac__c = true];
         }catch(Exception e){
         }
         }
        
        if(fraccs1.isEmpty()){
             ApexPages.addMessage(new ApexPages.Message
                                     (Apexpages.Severity.ERROR, 
                'El usuario no tiene Fraccionamientos autorizados.')); 
        }
        fraccs1.sort();
        fraccs = new List<SelectOption>();
        for(Fraccionamiento__c frac : fraccs1){
            System.debug('FARC: '+ frac);
            fraccs.add(new SelectOption(frac.Id,frac.Name));
        }
        
        String idCuenta = ApexPages.currentPage().getParameters().get('acc');
        
        List<Account> cuentas = [
            SELECT 
            Id, 
            Name, 
            Fraccionamiento_cta__r.Id, 
            Capcomp_cta__c,
            Monaho_cta__c,
            Montgast_cta__c
            FROM Account
            WHERE Id = :idCuenta];
        
        System.debug('CUENTAS: ' + cuentas);
		System.debug('CUENTAS: ' + simulador);        
        
        
        if(!cuentas.isEmpty()){
            if(cuentas[0].Fraccionamiento_cta__c != null){
               	List<Fraccionamiento__c> frac_cuenta = 
            		[SELECT Id, 
             		Name 
             		FROM Fraccionamiento__c 
             		WHERE Id =: cuentas[0].Fraccionamiento_cta__c];
               simulador.Fraccionamiento__c = cuentas[0].Fraccionamiento_cta__c;
            }
            if(cuentas[0].Capcomp_cta__c != null){
                simulador.CapacidadCompra__c = cuentas[0].Capcomp_cta__c;
            }
        }
                 if(isS1()){
             muestro = 'one-app';
         }
    }
    
    public PageReference consultar(){
        try{
            if(simulador.CapacidadCompra__c == null){
            ApexPages.addMessage(new ApexPages.Message
                                 (Apexpages.Severity.ERROR, 
			'Especifique una capacidad de compra.')); 
                return ApexPages.currentPage();
        	}
        }catch(Exception e){
            ApexPages.addMessage(new ApexPages.Message
                                 (Apexpages.Severity.ERROR, 
			'Especifique una capacidad de compra.')); 
            return ApexPages.currentPage();
        }
            
        prototipos = new List<Prototipo__c>();
        List<Prototipo__c> proto = [SELECT 
                                         Name, 
                                         Imagen_01__c, 
                                         Imagen_02__c,
                                         Precio_pro__c,
                                    	 Tour_360__c
                                         FROM Prototipo__c 
                                         WHERE Fraccionamiento__c = :simulador.Fraccionamiento__c ];
            
        List<Prototipo__c> protoExtra = [SELECT 
                                         Name, 
                                         Imagen_01__c, 
                                         Imagen_02__c,
                                         Precio_pro__c,
                                         Tour_360__c
                                         FROM Prototipo__c 
                                         WHERE Precio_pro__c <=: simulador.CapacidadCompra__c
                                         AND Fraccionamiento__c = :simulador.Fraccionamiento__c 
                                         ORDER BY Precio_pro__c DESC LIMIT 1];
        List<Prototipo__c> protoExtra2 = [SELECT 
                                          Name, 
                                          Imagen_01__c, 
                                          Imagen_02__c,
                                          Precio_pro__c,
                                          Tour_360__c
                                          FROM Prototipo__c 
                                          WHERE Precio_pro__c >: simulador.CapacidadCompra__c
                                          AND Precio_pro__c <: simulador.CapacidadCompra__c * 1.05
                                          AND Fraccionamiento__c = : simulador.Fraccionamiento__c 
                                          ORDER BY Precio_pro__c ASC LIMIT 1];
        if(protoExtra.size() > 0){
            protoExtra[0].Name = protoExtra[0].Name.split('-')[0];
            prototipos.add(protoExtra[0]);
        }
        else if(protoExtra2.size() > 0){
            protoExtra2[0].Name = protoExtra2[0].Name.split('-')[0];
            prototipos.add(protoExtra2[0]);
        }
        try{
            prototipos.get(0);
            prototipos.get(1);
        }catch(Exception e){
            ApexPages.addMessage(new ApexPages.Message
                                 (Apexpages.Severity.WARNING, 
			'El fraccionamiento seleccionado cuenta con '+ prototipos.size()+' prototipo(s)'));
        }
        return ApexPages.currentPage();
    }
    
    public static Boolean isS1(){
 
   String retUrl = ApexPages.currentPage().getParameters().get('retURL');
 
   return String.isNotBlank(ApexPages.currentPage().getParameters().get('sfdcIFrameHost')) ||
   String.isNotBlank(ApexPages.currentPage().getParameters().get('sfdcIFrameOrigin')) ||
   ApexPages.currentPage().getParameters().get('isdtp') == 'p1' ||
   (String.isNotBlank(retUrl) && retURL.contains('projectone'));
 
}
    public void method(){
        Integer i = 0;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;        i = 1;
        i = 1;
        i = 1;i = 1;        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
    }
}