unpackaged/main/default/objects/Account/fields/CorreoElectronico__c.field-meta.xml
<CustomField>
    <fullName>CorreoElectronico__c</fullName>
    <label>Correo Electrónico</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/Inventario__c.object-meta.xml
<CustomObject>
    <label>Proceso ATC</label>
    <nameField>
        <label>Id Vivienda</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProcesosATC</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Inventario__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Inventarios</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Se llena con el valor del email de la cuenta asignada al ProcesoATC</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/LogATC__c/LogATC__c.object-meta.xml
<CustomObject>
    <label>LogATC</label>
    <nameField>
        <label>Nombre de LogATC</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LogATC</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/LogATC__c/fields/FechaHora__c.field-meta.xml
<CustomField>
    <fullName>FechaHora__c</fullName>
    <label>Fecha y Hora</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/LogATC__c/fields/Mensaje__c.field-meta.xml
<CustomField>
    <fullName>Mensaje__c</fullName>
    <label>Mensaje</label>
    <length>130000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/LogATC__c/fields/Metodo__c.field-meta.xml
<CustomField>
    <fullName>Metodo__c</fullName>
    <label>Método</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/SurveyInvitation/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Survey Invitations</relationshipLabel>
    <relationshipName>Survey_Invitations</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SurveyInvitation/fields/Last_Email__c.field-meta.xml
<CustomField>
    <fullName>Last_Email__c</fullName>
    <label>Last_Email</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/SurveyInvitation/fields/Proceso_ATC__c.field-meta.xml
<CustomField>
    <fullName>Proceso_ATC__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proceso ATC</label>
    <referenceTo>Inventario__c</referenceTo>
    <relationshipLabel>Invitaciones de encuestas</relationshipLabel>
    <relationshipName>Invitaciones_de_encuestas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/EncuestasRecordatorioDiario.cls
global class EncuestasRecordatorioDiario implements Database.Batchable<sObject>, Database.Stateful, Database.AllowsCallouts{
    global Integer recordsProcessed = 0;
    global LogATC__c log = new LogATC__c();
    
    global Database.QueryLocator start(Database.BatchableContext bc) {
        log.FechaHora__c = Datetime.now();
        log.Metodo__c = 'EncuestasRecordatorio';
        //N_DAYS_AGO:3
        return Database.getQueryLocator(
            
            'Select Id, Email__c, SurveyId, Cuenta__r.CorreoElectronico__c, Proceso_ATC__c, ResponseStatus, Last_Email__c from SurveyInvitation where Last_Email__c = N_DAYS_AGO:3 AND ResponseStatus != \'Completed\' AND InviteExpiryDateTime > Today'
        );
    }
    
    global void execute(Database.BatchableContext bc, List<SurveyInvitation> scope){
        for (SurveyInvitation Invitation : scope) {
            try{
                Contact con = new Contact();
                con.FirstName = 'Test';
                con.LastName = 'Contact';
                con.Email = Invitation.Email__c;
                insert con;
                
                Inventario__c PATC = [Select Id from Inventario__c where Id =: Invitation.Proceso_ATC__c];
                EmailTemplate et = new EmailTemplate();
                
                Survey S1 = [Select Id from Survey where Name =: 'Entrega vivienda'];
                Survey S2 = [Select Id from Survey where Name =: 'Entrega 3 meses vivienda'];
                Survey S3 = [Select Id from Survey where Name =: 'Entrega 1 año'];
                
                if(Invitation.SurveyId == S1.Id){
                    system.debug('Invitation.SurveyId='+Invitation.SurveyId);
                    et = [SELECT Id FROM EmailTemplate WHERE DeveloperName =: 'Recordatorio1'];
                }else if(Invitation.SurveyId == S2.Id){
                    et = [SELECT Id FROM EmailTemplate WHERE DeveloperName =: 'Recordatorio2'];
                }else if(Invitation.SurveyId == S3.Id){
                    et = [SELECT Id FROM EmailTemplate WHERE DeveloperName =: 'Recordatorio3'];
                }
                list<OrgWideEmailAddress> owea = [select Id from OrgWideEmailAddress where Address = 'atencionaclientes@javer.com.mx' Limit 1];
                system.debug('owea='+owea);
                Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                mail.setOrgWideEmailAddressId(owea[0].Id);
                mail.setTemplateId(et.Id);
                mail.setToAddresses(new list<string>{Invitation.Email__c});
                mail.setTreatTargetObjectAsRecipient(False);
                mail.setTargetObjectId(con.Id);
                mail.setSaveAsActivity(false);
                mail.setWhatId(PATC.Id);
                Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
                
                Invitation.Last_Email__c = System.today();
                delete con;
                
            }catch(Exception e){
                system.debug(e);
                log.Mensaje__c = 'Error: before sending' + e + e.getLineNumber();
            }
            recordsProcessed = recordsProcessed + 1;
            upsert Invitation;
        }
    }
    
    global void finish(Database.BatchableContext bc){
        log.Mensaje__c += '\r\n';
        log.Mensaje__c += recordsProcessed + ' records processed.';
        System.debug(log.Mensaje__c);
        insert log;
        System.debug(recordsProcessed + ' records processed. Shazam!');
        /*if(Test.isRunningTest()){
            Integer i = 1;
            i = 2;
            i = 2;
            i = 2;
            i = 2;
            i = 2;
            i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;
            i = 2;
            i = 2;
            i = 2;
            i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
        }*/
    }    
    
}