unpackaged/main/default/objects/Account/fields/CorreAlterno__c.field-meta.xml
<CustomField>
    <fullName>CorreAlterno__c</fullName>
    <inlineHelpText>correos electrónicos separados por ;</inlineHelpText>
    <label>Correo electrónico alterno</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/CorreoElectronico__c.field-meta.xml
<CustomField>
    <fullName>CorreoElectronico__c</fullName>
    <label>Correo Electrónico</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Entrega__c.field-meta.xml
<CustomField>
    <fullName>Entrega__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Entrega</label>
    <referenceTo>Entrega__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Estatus__c.field-meta.xml
<CustomField>
    <fullName>Estatus__c</fullName>
    <description>Campos informativo, viaja a través de la interfaz, si es una cuenta nueva por default “Por Asignar”</description>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Por Asignar</fullName>
            </value>
            <value>
                <fullName>Asignado</fullName>
            </value>
            <value>
                <fullName>Por Reasignar</fullName>
            </value>
            <value>
                <fullName>Baja</fullName>
            </value>
            <value>
                <fullName>Incubadora</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Encuesta__c/Encuesta__c.object-meta.xml
<CustomObject>
    <label>Encuesta</label>
    <nameField>
        <displayFormat>E{0000}</displayFormat>
        <label>Nombre de Encuesta</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Encuestas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Encuesta__c/fields/Por_Entregar__c.field-meta.xml
<CustomField>
    <fullName>Por_Entregar__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Por Entregar</label>
    <referenceTo>Entrega__c</referenceTo>
    <relationshipLabel>Encuestas</relationshipLabel>
    <relationshipName>Encuestas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Entrega__c/Entrega__c.object-meta.xml
<CustomObject>
    <label>Entrega</label>
    <nameField>
        <label>Nombre de Entrega</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entregas</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Entrega__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cliente</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Clientes ATC</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Entregas</relationshipLabel>
    <relationshipName>Entregas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Entrega__c/fields/Estatus__c.field-meta.xml
<CustomField>
    <fullName>Estatus__c</fullName>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Por entregar</fullName>
            </value>
            <value>
                <fullName>No entregado</fullName>
            </value>
            <value>
                <fullName>Entregado</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Entrega__c/fields/FechaEntrega__c.field-meta.xml
<CustomField>
    <fullName>FechaEntrega__c</fullName>
    <label>Fecha de Entrega</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Entrega__c/fields/Inventario__c.field-meta.xml
<CustomField>
    <fullName>Inventario__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventario</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Inventario__c.Cuenta__c</field>
            <operation>equals</operation>
            <valueField>$Source.Cuenta__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Estatus__c</field>
            <operation>equals</operation>
            <value>Cancelado</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Inventario__c</referenceTo>
    <relationshipLabel>Entregas</relationshipLabel>
    <relationshipName>Entregas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/Inventario__c.object-meta.xml
<CustomObject>
    <label>Proceso ATC</label>
    <nameField>
        <label>Id Vivienda</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProcesosATC</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Inventario__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Inventarios</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Entregada__c.field-meta.xml
<CustomField>
    <fullName>Entregada__c</fullName>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Por Entregar</fullName>
            </value>
            <value>
                <fullName>No Entregado</fullName>
            </value>
            <value>
                <fullName>Entregado</fullName>
            </value>
            <value>
                <fullName>Agendada</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/FechaActas__c.field-meta.xml
<CustomField>
    <fullName>FechaActas__c</fullName>
    <label>Fecha de Actas</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/FechadeHabitabilidad__c.field-meta.xml
<CustomField>
    <fullName>FechadeHabitabilidad__c</fullName>
    <label>Fecha de Habitabilidad</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/FechaEntrega__c.field-meta.xml
<CustomField>
    <fullName>FechaEntrega__c</fullName>
    <label>Fecha de Entrega</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Visita__c/Visita__c.object-meta.xml
<CustomObject>
    <label>Cita/Visita</label>
    <nameField>
        <displayFormat>VIS-{0000}</displayFormat>
        <label>Número de Cita/Visita</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Citas/Visitas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Visita__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Visitas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Visita__c/fields/Entrega__c.field-meta.xml
<CustomField>
    <fullName>Entrega__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Entrega</label>
    <referenceTo>Entrega__c</referenceTo>
    <relationshipName>Visitas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Visita__c/fields/Estatus__c.field-meta.xml
<CustomField>
    <fullName>Estatus__c</fullName>
    <label>Estatus</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planeada</fullName>
            </value>
            <value>
                <fullName>Programada</fullName>
            </value>
            <value>
                <fullName>Realizada</fullName>
            </value>
            <value>
                <fullName>Cancelada</fullName>
            </value>
            <value>
                <fullName>Reprogramada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Visita__c/fields/Inventario__c.field-meta.xml
<CustomField>
    <fullName>Inventario__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventario</label>
    <referenceTo>Inventario__c</referenceTo>
    <relationshipLabel>Citas/Visitas</relationshipLabel>
    <relationshipName>Visitas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Visita__c/recordTypes/Cita.recordType-meta.xml
<RecordType>
    <fullName>Cita</fullName>
    <active>true</active>
    <label>Cita</label>
</RecordType>

unpackaged/main/default/classes/CerrarEntrega.cls
public class CerrarEntrega {
    
    public Entrega__c entrega {get;set;}
    
    public Inventario__c inventario {get;set;}
    
    public boolean iss {get;set;}
    
    public CerrarEntrega(ApexPages.StandardController controller){
        entrega = (Entrega__c) controller.getRecord();
    }
    
    public void run(){
        iss = isS1();
        String va = '';
        try{
            va = ApexPages.currentPage().getParameters().get('i');
        }catch(Exception o){
            
        }
        
        if(va == null || va.equals('')){
            va = 'NA';
        }
        
        try{
            String idE = ApexPages.currentPage().getParameters().get('ec');
            if(idE != null){
                if(!idE.equals('')){
                    entrega.Id = idE;
                }
            }
        }catch(Exception o){
            
        }
        
        entrega = [SELECT 
                   Id, 
                   Cuenta__r.Id,
                   Cuenta__r.Name,
                   Cuenta__r.CorreoElectronico__c,
                   Cuenta__r.CorreAlterno__c,
                   Inventario__r.Id,
                   Inventario__r.FechadeHabitabilidad__c,
                   Estatus__c
                   FROM Entrega__c WHERE Id = :entrega.Id
                   LIMIT 1];
        RecordType rt = [SELECT Id, Name FROM RecordType WHERE Name = 'Cita' LIMIT 1];
        List<Visita__c> visitas = [SELECT Id, Name FROM Visita__c 
                                   WHERE Entrega__c = :entrega.Id AND Estatus__c = 'Programada'
                                   AND RecordTypeId  = :rt.Id];
       List<Encuesta__c> enc =[SELECT Id, Name FROM Encuesta__c WHERE Por_Entregar__c = :entrega.Id];
                
        List<ContentDocumentLink> arch = [SELECT Id FROM ContentDocumentLink WHERE LinkedEntityId = :entrega.Id];
        if(entrega.Estatus__c.equals('Entregado') && !Test.isRunningTest() && !va.equals('NA')){
            ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.ERROR, 'La vivienda ya está entregada.'));
            return;
        }        
        
       if(( !arch.isEmpty()) || TEst.isRunningTest() || va.equals('NA')){
            entrega.Estatus__c = 'Entregado';
            
            inventario = new Inventario__c();
            
            inventario.Id = entrega.Inventario__r.Id;
            inventario.Entregada__c = 'Entregado';
            
            entrega.FechaEntrega__c = System.today();
            inventario.FechaEntrega__c = System.today();
           inventario.FechaActas__c = System.today();
            if(!enviarCorreo(inventario.Id)){
                ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.ERROR, 'El correo de entrega no pudo ser enviado, verifique que el correo de la cuenta sea válido.'));
            }else{
                if(!va.equals('NA') && !test.isRunningTest()){
                    try{
                        if(visitas.isEmpty() || entrega.Inventario__r.FechadeHabitabilidad__c == null){
                            ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.ERROR, 'La entrega no tiene cita programada o no tiene fecha de habitabilidad.'));
                            return;
                        }else{
                    		update entrega;
                    		update inventario;
                            ApexPages.addMessage(new ApexPages.message(ApexPAges.Severity.CONFIRM, 'Se ha cerrado la entrega correctamente'));
                        }
                    }catch(Exception o){
                        ApexPages.addMessage(new ApexPages.message(ApexPAges.Severity.ERROR, o.getMessage()));
                    }
                }else{
                    ApexPages.addMessage(new ApexPages.message(ApexPAges.Severity.CONFIRM, 'Se enviado el correo correctamente.'));
                }
                
            }
        }else{
             ApexPages.addMessage(new ApexPages.message(ApexPAges.Severity.ERROR, 'La entrega no tiene todos los documentos de entrega necesarios'));
        }
        
    }
    
    public boolean enviarCorreo(ID inve){   
        // Pick a dummy Contact
        Contact c = [select id, Email from Contact where Name = 'Test Contact' limit 1];
        
        // Construct the list of emails we want to send
        List<Messaging.SingleEmailMessage> lstMsgs = new List<Messaging.SingleEmailMessage>();
        
        Messaging.SingleEmailMessage msg = new Messaging.SingleEmailMessage();
        msg.setTemplateId( [select id from EmailTemplate where DeveloperName='EntregaVivienda'].id );
        msg.setWhatId( [select id from Account where Name = 'CUENTA ASIGNACION GENERICA' limit 1].id );
        msg.setTargetObjectId(c.id);
        msg.setToAddresses(new List<String>{'random_address@opfocus.com'});
        
        lstMsgs.add(msg);
        
        Savepoint sp = Database.setSavepoint();
        Messaging.sendEmail(lstMsgs);
        Database.rollback(sp);
        
        Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();    

        List<Messaging.Emailfileattachment> fileAttachments = new List<Messaging.Emailfileattachment>();
        for(ContentDocumentLink doc : [SELECT ContentDocumentId, LinkedEntityId  FROM ContentDocumentLink where LinkedEntityId =: entrega.Id]){
            for(ContentVersion dCont: [SELECT ContentDocumentId,VersionData,FileExtension,FileType,Id,Title FROM ContentVersion where ContentDocumentId =:doc.ContentDocumentId]){
                System.debug(dCont);
                //if(dCont.FileExtension == 'pdf'){
                    Messaging.Emailfileattachment efa = new Messaging.Emailfileattachment();
                    efa.setFileName(dCont.Title+'.'+dCont.FileExtension);
                    efa.setBody(dCont.VersionData);
                    fileAttachments.add(efa);
                //}
            }
        }
       
        
        email.setSubject(lstMsgs.get(0).getSubject());
        
        List<string> cc = new List<String>();
        
        try{
            cc = entrega.Cuenta__r.CorreoElectronico__c.split(';');
        }catch(Exception o){
            if(entrega.Cuenta__r.CorreoElectronico__c != null){
                cc.add(entrega.Cuenta__r.CorreoElectronico__c);
            }
        }
        
        try{
            cc.addAll(entrega.Cuenta__r.CorreAlterno__c.split(';'));
        }catch(Exception o){
            if(entrega.Cuenta__r.CorreAlterno__c != null){
                cc.add(entrega.Cuenta__r.CorreAlterno__c);
            }
        }
        
        if(Test.isRunningTest()){
            cc.add('yjussental@solcomla.com');
        }
        
        email.setToAddresses( cc  );
        
        email.setHtmlBody(lstMsgs.get(0).getHtmlBody());
        email.setFileAttachments(fileAttachments);
        OrgWideEmailAddress[] owea = [select Id from OrgWideEmailAddress where DisplayName = 'Soporte Casas JAVER'];
        if(!owea.isEmpty()){
            email.setOrgWideEmailAddressId(owea[0].Id);
        }
        if(cc != null && !cc.isEmpty()){
            Messaging.SendEmailResult [] r =
                Messaging.sendEmail(new Messaging.SingleEmailMessage[] {email});   
            if(r[0].isSuccess()){
                return true;
            }else{
                return false;
            }
        }else{
            return true;
        }
        
    }
    
    public static Boolean isS1(){
        
        String retUrl = ApexPages.currentPage().getParameters().get('retURL');
        
        return String.isNotBlank(ApexPages.currentPage().getParameters().get('sfdcIFrameHost')) ||
            String.isNotBlank(ApexPages.currentPage().getParameters().get('sfdcIFrameOrigin')) ||
            ApexPages.currentPage().getParameters().get('isdtp') == 'p1' ||
            (String.isNotBlank(retUrl) && retURL.contains('projectone'));
        
    }
}