unpackaged/main/default/objects/Account/fields/CorreoElectronico__c.field-meta.xml
<CustomField>
    <fullName>CorreoElectronico__c</fullName>
    <label>Correo Electrónico</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Estatus__c.field-meta.xml
<CustomField>
    <fullName>Estatus__c</fullName>
    <description>Campos informativo, viaja a través de la interfaz, si es una cuenta nueva por default “Por Asignar”</description>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Por Asignar</fullName>
            </value>
            <value>
                <fullName>Asignado</fullName>
            </value>
            <value>
                <fullName>Por Reasignar</fullName>
            </value>
            <value>
                <fullName>Baja</fullName>
            </value>
            <value>
                <fullName>Incubadora</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Casos_Residente__c/Casos_Residente__c.object-meta.xml
<CustomObject>
    <label>Caso ATC</label>
    <nameField>
        <displayFormat>CAS-{00000000}</displayFormat>
        <label>Folio</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Casos ATC</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Casos_Residente__c/fields/CasoResidente__c.field-meta.xml
<CustomField>
    <fullName>CasoResidente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Caso Residentes</label>
    <referenceTo>Casos_Residente__c</referenceTo>
    <relationshipName>CasosResidentes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Casos_Residente__c/fields/Conjunto_Casos__c.field-meta.xml
<CustomField>
    <fullName>Conjunto_Casos__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conjunto de Casos</label>
    <referenceTo>Conjunto_Casos__c</referenceTo>
    <relationshipLabel>Casos ATC</relationshipLabel>
    <relationshipName>Casos_ATC</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Casos_Residente__c/fields/ContactEmail__c.field-meta.xml
<CustomField>
    <fullName>ContactEmail__c</fullName>
    <label>Email del contacto</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Casos_Residente__c/fields/ContactMobile__c.field-meta.xml
<CustomField>
    <fullName>ContactMobile__c</fullName>
    <label>Teléfono celular del contacto</label>
    <type>Phone</type>
</CustomField>

unpackaged/main/default/objects/Casos_Residente__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Clientes ATC</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Casos ATC</relationshipLabel>
    <relationshipName>Casos_Residentes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Casos_Residente__c/fields/Detalledelreporte__c.field-meta.xml
<CustomField>
    <fullName>Detalledelreporte__c</fullName>
    <label>Detalle del reporte</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Casos_Residente__c/fields/DireccionOficial__c.field-meta.xml
<CustomField>
    <fullName>DireccionOficial__c</fullName>
    <formula>ViviendaProceso__r.Direccionoficial__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Dirección oficial</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Casos_Residente__c/fields/Fecha_Cierre_Cancelacion__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Cierre_Cancelacion__c</fullName>
    <label>Fecha de Cierre/Cancelación</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Casos_Residente__c/fields/Fecha_Programada_de_Visita__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Programada_de_Visita__c</fullName>
    <label>Fecha Programada de Visita</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Casos_Residente__c/fields/Fracc__c.field-meta.xml
<CustomField>
    <fullName>Fracc__c</fullName>
    <label>Fraccionamiento</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Casos_Residente__c/fields/MLI__c.field-meta.xml
<CustomField>
    <fullName>MLI__c</fullName>
    <formula>ViviendaProceso__r.MLI__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>MLI</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Casos_Residente__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Asignado</fullName>
                <default>true</default>
                <label>Asignado</label>
            </value>
            <value>
                <fullName>En proceso</fullName>
            </value>
            <value>
                <fullName>Cerrado</fullName>
            </value>
            <value>
                <fullName>No procede</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Casos_Residente__c/fields/Visita__c.field-meta.xml
<CustomField>
    <fullName>Visita__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Visita</label>
    <referenceTo>Visita__c</referenceTo>
    <relationshipName>Casos_Residentes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Casos_Residente__c/fields/ViviendaProceso__c.field-meta.xml
<CustomField>
    <fullName>ViviendaProceso__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Vivienda</label>
    <referenceTo>Inventario__c</referenceTo>
    <relationshipLabel>Casos ATC</relationshipLabel>
    <relationshipName>Casos_ATC</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Conjunto_Casos__c/Conjunto_Casos__c.object-meta.xml
<CustomObject>
    <label>Conjunto de Casos</label>
    <nameField>
        <displayFormat>CDC-{00000000}</displayFormat>
        <label>Nombre de Conjunto de Casos</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Conjuntos de Casos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Conjunto_Visitas__c/Conjunto_Visitas__c.object-meta.xml
<CustomObject>
    <label>Conjunto de Visitas</label>
    <nameField>
        <displayFormat>CV-{000000}</displayFormat>
        <label>Conjunto de Visitas Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Conjuntos de Visitas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Conjunto_Visitas__c/fields/Caso_ATC__c.field-meta.xml
<CustomField>
    <fullName>Caso_ATC__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Caso ATC</label>
    <referenceTo>Casos_Residente__c</referenceTo>
    <relationshipLabel>Conjuntos de Visitas</relationshipLabel>
    <relationshipName>Conjuntos_de_Visitas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Conjunto_Visitas__c/fields/Cita_Visita__c.field-meta.xml
<CustomField>
    <fullName>Cita_Visita__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cita/Visita</label>
    <referenceTo>Visita__c</referenceTo>
    <relationshipLabel>Conjuntos de Visitas</relationshipLabel>
    <relationshipName>Conjuntos_de_Visitas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Conjunto_Visitas__c/fields/Estatus__c.field-meta.xml
<CustomField>
    <fullName>Estatus__c</fullName>
    <formula>TEXT(Cita_Visita__r.Estatus__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Estatus</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Fraccionamiento__c/Fraccionamiento__c.object-meta.xml
<CustomObject>
    <label>Fraccionamiento</label>
    <nameField>
        <label>Nombre de Fraccionamiento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fraccionamientos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Inventario__c/Inventario__c.object-meta.xml
<CustomObject>
    <label>Proceso ATC</label>
    <nameField>
        <label>Id Vivienda</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProcesosATC</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Inventario__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Inventarios</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Direccionoficial__c.field-meta.xml
<CustomField>
    <fullName>Direccionoficial__c</fullName>
    <label>Dirección oficial</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/FechaEntrega__c.field-meta.xml
<CustomField>
    <fullName>FechaEntrega__c</fullName>
    <label>Fecha de Entrega</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Fracc__c.field-meta.xml
<CustomField>
    <fullName>Fracc__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fraccionamiento</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>(1 OR 5 OR 2 OR 4) AND 3</booleanFilter>
        <filterItems>
            <field>$User.Fraccionamiento_autorizado__c</field>
            <operation>contains</operation>
            <valueField>Fraccionamiento__c.Name</valueField>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>Administrador del sistema</value>
        </filterItems>
        <filterItems>
            <field>Fraccionamiento__c.Activo_frac__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$User.Fraccionamiento_autorizado__c</field>
            <operation>equals</operation>
            <value>TODOS</value>
        </filterItems>
        <filterItems>
            <field>$User.Fraccionamiento_autorizado__c</field>
            <operation>contains</operation>
            <valueField>Fraccionamiento__c.Name</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Fraccionamiento__c</referenceTo>
    <relationshipLabel>ProcesosATC</relationshipLabel>
    <relationshipName>Inventarios</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Interior__c.field-meta.xml
<CustomField>
    <fullName>Interior__c</fullName>
    <label>Interior</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Lote__c.field-meta.xml
<CustomField>
    <fullName>Lote__c</fullName>
    <label>Lote</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Manzana__c.field-meta.xml
<CustomField>
    <fullName>Manzana__c</fullName>
    <label>Manzana</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/MLI__c.field-meta.xml
<CustomField>
    <fullName>MLI__c</fullName>
    <label>MLI</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Sector__c.field-meta.xml
<CustomField>
    <fullName>Sector__c</fullName>
    <label>Sector</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Unidad_privativa__c.field-meta.xml
<CustomField>
    <fullName>Unidad_privativa__c</fullName>
    <label>Unidad privativa</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Visita__c/Visita__c.object-meta.xml
<CustomObject>
    <label>Cita/Visita</label>
    <nameField>
        <displayFormat>VIS-{0000}</displayFormat>
        <label>Número de Cita/Visita</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Citas/Visitas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Visita__c/fields/CasoResidente__c.field-meta.xml
<CustomField>
    <fullName>CasoResidente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Caso</label>
    <referenceTo>Casos_Residente__c</referenceTo>
    <relationshipLabel>Citas/Visitas</relationshipLabel>
    <relationshipName>Visitas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Visita__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Visitas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Visita__c/fields/Estatus__c.field-meta.xml
<CustomField>
    <fullName>Estatus__c</fullName>
    <label>Estatus</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planeada</fullName>
            </value>
            <value>
                <fullName>Programada</fullName>
            </value>
            <value>
                <fullName>Realizada</fullName>
            </value>
            <value>
                <fullName>Cancelada</fullName>
            </value>
            <value>
                <fullName>Reprogramada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Visita__c/fields/Fechaprogramadadevisita__c.field-meta.xml
<CustomField>
    <fullName>Fechaprogramadadevisita__c</fullName>
    <label>Fecha programada</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Visita__c/fields/Inventario__c.field-meta.xml
<CustomField>
    <fullName>Inventario__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventario</label>
    <referenceTo>Inventario__c</referenceTo>
    <relationshipLabel>Citas/Visitas</relationshipLabel>
    <relationshipName>Visitas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Visita__c/recordTypes/Cita.recordType-meta.xml
<RecordType>
    <fullName>Cita</fullName>
    <active>true</active>
    <label>Cita</label>
</RecordType>

unpackaged/main/default/objects/Visita__c/recordTypes/Visita.recordType-meta.xml
<RecordType>
    <fullName>Visita</fullName>
    <active>true</active>
    <label>Visita</label>
</RecordType>

unpackaged/main/default/classes/ReporteAtnController.cls
public class ReporteAtnController {
    public Casos_Residente__c caso{get;set;}
    public User propietario {get;set;}
    public Inventario__c vivienda {get;set;}
    public Account residente {get;set;}
    public id conjuntoId {get;set;}
    public String fv {get;set;}
    public String f {get;set;}
    public String d {get;set;}
    public String m {get;set;}
    public String a {get;set;}
    public String filename {get;set;}
    public boolean show {get;set;}
    
    public List<Casos_Residente__c> listCasos {get;set;}
    public Conjunto_Casos__c conjunto {get;set;}
    public void prepare(){
        if(caso.Conjunto_Casos__c == null){
            System.debug('listCasos'+listCasos);
            for(Casos_Residente__c casoTemp : listCasos){
                System.debug('casoTemp'+casoTemp);
                if(casoTemp.Conjunto_Casos__c != null){
                    conjuntoId = caso.Conjunto_Casos__c;
                }
            }
            
            if(conjuntoId == null){
                conjunto = new Conjunto_Casos__c();
                insert conjunto;
            }else{
                conjunto = new Conjunto_Casos__c(Id=conjuntoId);
            }
            
            for(Casos_Residente__c casoTemp : listCasos){
                if(casoTemp.Status__c != 'Asignado' && casoTemp.Status__c != 'En proceso' && casoTemp.Status__c != 'No procede'){
                    casoTemp.Conjunto_Casos__c = conjunto.Id;
                }
            }
            
            update listCasos;
        }
    }
    
    public ReporteAtnController(){
        show = true;
        Date fechaCierre;
        String casoId = Apexpages.currentPage().getparameters().get('id');
        caso = [SELECT Id, Fecha_Programada_de_Visita__c, OwnerId, ContactMobile__c, ContactEmail__c, 
                ViviendaProceso__c, Name, Cuenta__c, Detalledelreporte__c, Conjunto_Casos__c, Fecha_Cierre_Cancelacion__c 
                FROM Casos_Residente__c WHERE Id =: casoId];
        
        listCasos = [SELECT Id, Status__c, OwnerId, ContactMobile__c, ContactEmail__c, ViviendaProceso__c, Name, Cuenta__c, Detalledelreporte__c, Conjunto_Casos__c, Fecha_Programada_de_Visita__c
                     FROM Casos_Residente__c WHERE ViviendaProceso__c =: caso.ViviendaProceso__c AND Fecha_Programada_de_Visita__c =: caso.Fecha_Programada_de_Visita__c AND Fecha_Programada_de_Visita__c != null];
        
        List<Conjunto_Visitas__c> conjuntosVisitas = [SELECT Id, Caso_ATC__c, Estatus__c, Cita_Visita__r.Fechaprogramadadevisita__c FROM Conjunto_Visitas__c WHERE Caso_ATC__c IN: listCasos ORDER BY Cita_Visita__r.Fechaprogramadadevisita__c LIMIT 1];
        system.debug('conjuntosVisitas'+conjuntosVisitas);
        if(!conjuntosVisitas.isEmpty()){
            fechaCierre = conjuntosVisitas[0].Cita_Visita__r.Fechaprogramadadevisita__c;
        }else{
            List<Visita__c> visitas = [SELECT Id, CasoResidente__c, Estatus__c, Fechaprogramadadevisita__c FROM Visita__c WHERE CasoResidente__c IN: listCasos ORDER BY Fechaprogramadadevisita__c LIMIT 1];
            if(!visitas.isEmpty()){
                fechaCierre = visitas[0].Fechaprogramadadevisita__c;
            }else{
                show = false;
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Se necesita una cita programada para descargar el folio.'));      
                isS1(); 
            }
        }
        
        try{
            d = fechaCierre.day()+'';  m = fechaCierre.month()+''; a = fechaCierre.year()+'';
            propietario = [SELECT Name FROM User WHERE Id=:caso.OwnerId];
            residente = [SELECT Name,Phone,CorreoElectronico__c FROM Account WHERE Id=:caso.Cuenta__c];
            vivienda = [SELECT Manzana__c,Lote__c,Sector__c,Unidad_privativa__c,FechaEntrega__c,Fracc__r.Name,Cuenta__r.Name,MLI__c,Direccionoficial__c,Interior__c FROM Inventario__c WHERE Id=:caso.ViviendaProceso__c];
            try{
                f = vivienda.FechaEntrega__c.day() + '-' + vivienda.FechaEntrega__c.month() + '-' + vivienda.FechaEntrega__c.year();
                
                //AggregateResult visita = [SELECT MAX(Fechaprogramadadevisita__c) FROM Visita__c WHERE CasoResidente__c =:casoId][0];
                //Date fechaVisita = (Date)visita.get('expr0');
                //fv = fechaVisita.day() + '-' + fechaVisita.month() + '-' + fechaVisita.year();
            }
            catch(Exception o){     }
            filename = 'filename=Reporte_'+caso.Name+'.pdf';
            if(isS1()){
                Apexpages.currentPage().getHeaders().put('content-disposition', 'attachment;' + filename);
            }else{
                Apexpages.currentPage().getHeaders().put('content-disposition', filename);   
            }
            filename = 'filename=Reporte_'+caso.Name+'.pdf';
            Apexpages.currentPage().getHeaders().put('content-disposition', 'attachment;' + filename);
        } catch(Exception e){
            show = false;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, ''));
            isS1();
        }
    }
    
    public static Boolean isS1(){ 
        String retUrl = ApexPages.currentPage().getParameters().get('retURL');
        return String.isNotBlank(ApexPages.currentPage().getParameters().get('sfdcIFrameHost')) ||
            String.isNotBlank(ApexPages.currentPage().getParameters().get('sfdcIFrameOrigin')) ||
            ApexPages.currentPage().getParameters().get('isdtp') == 'p1' ||
            (String.isNotBlank(retUrl) && retURL.contains('projectone'));
    }
    
    /* public void testClassMethod(){
String i = 'test';
i = 'test';
i = 'test';
i = 'test';
i = 'test';
i = 'test';
i = 'test';
i = 'test';
i = 'test';
i = 'test';
i = 'test';
i = 'test';
i = 'test';
i = 'test';
i = 'test';
i = 'test';
i = 'test';
i = 'test';
i = 'test';
i = 'test';
i = 'test';
i = 'test';
i = 'test';i = 'test';
i = 'test';
i = 'test';
i = 'test';
i = 'test';
i = 'test';
i = 'test';
i = 'test';
i = 'test';
i = 'test';
i = 'test';
i = 'test';
i = 'test';
i = 'test';
i = 'test';
i = 'test';
i = 'test';
i = 'test';
i = 'test';
i = 'test';
i = 'test';
i = 'test';
i = 'test';
i = 'test';
i = 'test';
i = 'test';
i = 'test';
i = 'test';
i = 'test';
i = 'test';
i = 'test';
i = 'test';
i = 'test';
i = 'test';
i = 'test';
i = 'test';
i = 'test';
i = 'test';
i = 'test';
i = 'test';
i = 'test';
i = 'test';
i = 'test';
i = 'test';
i = 'test';
i = 'test';
i = 'test';
i = 'test';
i = 'test';
i = 'test';
i = 'test';
i = 'test';
i = 'test';
i = 'test';
i = 'test';
i = 'test';
i = 'test';
i = 'test';
i = 'test';
i = 'test';
i = 'test';
i = 'test';
}*/
}