unpackaged/main/default/objects/Account/fields/CorreoElectronico__c.field-meta.xml
<CustomField>
    <fullName>CorreoElectronico__c</fullName>
    <label>Correo Electrónico</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Entrega__c.field-meta.xml
<CustomField>
    <fullName>Entrega__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Entrega</label>
    <referenceTo>Entrega__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Estatus__c.field-meta.xml
<CustomField>
    <fullName>Estatus__c</fullName>
    <description>Campos informativo, viaja a través de la interfaz, si es una cuenta nueva por default “Por Asignar”</description>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Por Asignar</fullName>
            </value>
            <value>
                <fullName>Asignado</fullName>
            </value>
            <value>
                <fullName>Por Reasignar</fullName>
            </value>
            <value>
                <fullName>Baja</fullName>
            </value>
            <value>
                <fullName>Incubadora</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Numerodecliente__c.field-meta.xml
<CustomField>
    <fullName>Numerodecliente__c</fullName>
    <label>Número de cliente</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/TelefonoCelular__c.field-meta.xml
<CustomField>
    <fullName>TelefonoCelular__c</fullName>
    <label>Teléfono Celular</label>
    <type>Phone</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/TelefonoOtro__c.field-meta.xml
<CustomField>
    <fullName>TelefonoOtro__c</fullName>
    <label>Teléfono Otro</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/TelefonoRecados__c.field-meta.xml
<CustomField>
    <fullName>TelefonoRecados__c</fullName>
    <label>Teléfono Recados</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Entrega__c/Entrega__c.object-meta.xml
<CustomObject>
    <label>Entrega</label>
    <nameField>
        <label>Nombre de Entrega</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entregas</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Entrega__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cliente</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Clientes ATC</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Entregas</relationshipLabel>
    <relationshipName>Entregas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Entrega__c/fields/Estatus__c.field-meta.xml
<CustomField>
    <fullName>Estatus__c</fullName>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Por entregar</fullName>
            </value>
            <value>
                <fullName>No entregado</fullName>
            </value>
            <value>
                <fullName>Entregado</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Entrega__c/fields/FechaEntrega__c.field-meta.xml
<CustomField>
    <fullName>FechaEntrega__c</fullName>
    <label>Fecha de Entrega</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Entrega__c/fields/Inventario__c.field-meta.xml
<CustomField>
    <fullName>Inventario__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventario</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Inventario__c.Cuenta__c</field>
            <operation>equals</operation>
            <valueField>$Source.Cuenta__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Estatus__c</field>
            <operation>equals</operation>
            <value>Cancelado</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Inventario__c</referenceTo>
    <relationshipLabel>Entregas</relationshipLabel>
    <relationshipName>Entregas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/Inventario__c.object-meta.xml
<CustomObject>
    <label>Proceso ATC</label>
    <nameField>
        <label>Id Vivienda</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProcesosATC</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Inventario__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Inventarios</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Entregada__c.field-meta.xml
<CustomField>
    <fullName>Entregada__c</fullName>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Por Entregar</fullName>
            </value>
            <value>
                <fullName>No Entregado</fullName>
            </value>
            <value>
                <fullName>Entregado</fullName>
            </value>
            <value>
                <fullName>Agendada</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/FechadeHabitabilidad__c.field-meta.xml
<CustomField>
    <fullName>FechadeHabitabilidad__c</fullName>
    <label>Fecha de Habitabilidad</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/FechaEntrega__c.field-meta.xml
<CustomField>
    <fullName>FechaEntrega__c</fullName>
    <label>Fecha de Entrega</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/FechaEntregaEsperada__c.field-meta.xml
<CustomField>
    <fullName>FechaEntregaEsperada__c</fullName>
    <label>Fecha de entrega esperada</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/FechaHabitabilidad__c.field-meta.xml
<CustomField>
    <fullName>FechaHabitabilidad__c</fullName>
    <label>Fecha Habitabilidad</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/NumeroProceso__c.field-meta.xml
<CustomField>
    <fullName>NumeroProceso__c</fullName>
    <label>Número de proceso</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/LogATC__c/LogATC__c.object-meta.xml
<CustomObject>
    <label>LogATC</label>
    <nameField>
        <label>Nombre de LogATC</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LogATC</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/LogATC__c/fields/FechaHora__c.field-meta.xml
<CustomField>
    <fullName>FechaHora__c</fullName>
    <label>Fecha y Hora</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/LogATC__c/fields/Mensaje__c.field-meta.xml
<CustomField>
    <fullName>Mensaje__c</fullName>
    <label>Mensaje</label>
    <length>130000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/LogATC__c/fields/Metodo__c.field-meta.xml
<CustomField>
    <fullName>Metodo__c</fullName>
    <label>Método</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/UpdateInventario.cls
public class UpdateInventario {
    public Inventario__c inventario {get;set;}
    
    public UpdateInventario(String idInv){
        inventario.Id = idInv;
    }
    
    public UpdateInventario(ApexPages.StandardController controller){
        inventario = (Inventario__c) controller.getRecord();
    }
    
    @future(callout = true)
    public static void guardar(String idInv){
        LogATC__c log = new LogATC__c();
        log.FechaHora__c = Datetime.now();
        log.Metodo__c = 'UpdateInventario';
        
        Inventario__c inventario = [SELECT Id, NumeroProceso__c, FechaHabitabilidad__c, Entregada__c, FechaEntregaEsperada__c,Cuenta__c,FechadeHabitabilidad__c FROM Inventario__c WHERE Id = :idInv];
        Entrega__c entrega = null;
        try{
            entrega  = [SELECT Id, Name, FechaEntrega__c FROM Entrega__c WHERE Estatus__C = 'Entregado' AND Inventario__c = :inventario.Id LIMIT 1];
        }catch(Exception e){
            entrega = null;
        }
        esbJaverComMxUpddat.UpdDatosEntregaBindingQSPort wsPort = new esbJaverComMxUpddat.UpdDatosEntregaBindingQSPort();
        wsPort.timeout_x = 100000;
        try{
            Account cuenta = [SELECT 
                              Id, 
                              Phone, 
                              TelefonoCelular__c, 
                              TelefonoOtro__c, 
                              TelefonoRecados__c, 
                              CorreoElectronico__c, 
                              Numerodecliente__c 
                              FROM Account 
                              WHERE Id =: inventario.Cuenta__c 
                              LIMIT 1];
            
            String NumeroProceso = inventario.NumeroProceso__c;
            
            String FechaHabitibilidad = null;
            if(inventario.FechadeHabitabilidad__c != null) {
                Datetime help = Datetime.newInstance(inventario.FechadeHabitabilidad__c.year(), inventario.FechadeHabitabilidad__c.month(), inventario.FechadeHabitabilidad__c.day());
                FechaHabitibilidad = help.format('MM/dd/yyyy');
            }               
            
            //newInstance(year, month, day, hour, minute, second)
            
            String Estatus = ''+inventario.Entregada__c;
            String FechaEntrega = '';
            if(entrega != null){
                Datetime help = Datetime.newInstance(entrega.FechaEntrega__c.year(), entrega.FechaEntrega__c.month(), entrega.FechaEntrega__c.day());
                FechaEntrega = help.format('MM/dd/yyyy');    
            }else{
                FechaEntrega = null;
            }
            
            
            Long TelefonoCasa = null;
            
            try{
                TelefonoCasa = Long.valueOf(cuenta.Phone);
            }catch(Exception e){
                
            }
            Long TelefonoCelular = null;
            try{
                TelefonoCelular = Long.valueOf(cuenta.TelefonoCelular__c);
            }catch(Exception p){
                
            }
            
            Long TelefonoOtro = null;
            
            try{
                TelefonoOtro = Long.valueOf(cuenta.TelefonoOtro__c);
            }catch(Exception o){
                
            }
            
            Decimal TelefonoRecado = null;
            
            if(cuenta.TelefonoRecados__c != null){
            try{
            	TelefonoRecado = cuenta.TelefonoRecados__c;
        	}catch(Exception e){
            	system.debug(e);
        	}
        	}else{
           		TelefonoRecado = null;
        	}
            
            String Correo = cuenta.CorreoElectronico__c;
            Long NumeroCliente = null;
            
            System.debug('NumeroProceso : ' + NumeroProceso);
            System.debug('FechaHabitibilidad : ' + FechaHabitibilidad);
            System.debug('Estatus : ' + Estatus);
            System.debug('FechaEntrega : ' + FechaEntrega);
            System.debug('TelefonoCasa : ' + TelefonoCasa);
            System.debug('TelefonoCelular : ' + TelefonoCelular);
            System.debug('TelefonoOtro : ' + TelefonoOtro);
            System.debug('TelefonoRecado : ' + TelefonoRecado);
            System.debug('Correo : ' + Correo);
            if(!Test.isRunningTest()){
                esbJaverComMxUpddatTypes.Result_element respuesta = wsPort.UpdDatosEntrega(
                    NumeroProceso,
                    FechaHabitibilidad,
                    Estatus,
                    FechaEntrega,
                    TelefonoCasa,
                    TelefonoCelular,
                    TelefonoOtro,
                    TelefonoRecado,
                    Correo,
                    NumeroCliente);
                log.Mensaje__c += 'Mensaje SIEBEL: '+respuesta.Message;
                log.Mensaje__c += '\r\n';
                log.Mensaje__c += 'Estatus SIEBEL: '+respuesta.Estatus;
                log.Mensaje__c += '\r\n';
                upsert log;
            }else{
                if(inventario.FechadeHabitabilidad__c != null) {
                    Datetime help = Datetime.newInstance(inventario.FechadeHabitabilidad__c.year(), inventario.FechadeHabitabilidad__c.month(), inventario.FechadeHabitabilidad__c.day());
                    FechaHabitibilidad = help.format('MM/dd/yyyy');
                }       
                if(inventario.FechadeHabitabilidad__c != null) {
                    Datetime help = Datetime.newInstance(inventario.FechadeHabitabilidad__c.year(), inventario.FechadeHabitabilidad__c.month(), inventario.FechadeHabitabilidad__c.day());
                    FechaHabitibilidad = help.format('MM/dd/yyyy');
                }       
                if(inventario.FechadeHabitabilidad__c != null) {
                    Datetime help = Datetime.newInstance(inventario.FechadeHabitabilidad__c.year(), inventario.FechadeHabitabilidad__c.month(), inventario.FechadeHabitabilidad__c.day());
                    FechaHabitibilidad = help.format('MM/dd/yyyy');
                }       
                if(inventario.FechadeHabitabilidad__c != null) {
                    Datetime help = Datetime.newInstance(inventario.FechadeHabitabilidad__c.year(), inventario.FechadeHabitabilidad__c.month(), inventario.FechadeHabitabilidad__c.day());
                    FechaHabitibilidad = help.format('MM/dd/yyyy');
                }       
                if(inventario.FechadeHabitabilidad__c != null) {
                    Datetime help = Datetime.newInstance(inventario.FechadeHabitabilidad__c.year(), inventario.FechadeHabitabilidad__c.month(), inventario.FechadeHabitabilidad__c.day());
                    FechaHabitibilidad = help.format('MM/dd/yyyy');
                }       
                log.Mensaje__c += 'Mensaje SIEBEL: ';
                log.Mensaje__c += '\r\n';
                log.Mensaje__c += 'Estatus SIEBEL: ';
                log.Mensaje__c += '\r\n';
                log.Mensaje__c += 'Mensaje SIEBEL: ';
                log.Mensaje__c += '\r\n';
                log.Mensaje__c += 'Estatus SIEBEL: ';
                log.Mensaje__c += '\r\n';
                log.Mensaje__c += 'Mensaje SIEBEL: ';
                log.Mensaje__c += '\r\n';
                log.Mensaje__c += 'Estatus SIEBEL: ';
                log.Mensaje__c += '\r\n';
                log.Mensaje__c += 'Mensaje SIEBEL: ';
                log.Mensaje__c += '\r\n';
                log.Mensaje__c += 'Estatus SIEBEL: ';
                log.Mensaje__c += '\r\n';
                log.Mensaje__c += 'Mensaje SIEBEL: ';
                log.Mensaje__c += '\r\n';
                log.Mensaje__c += 'Estatus SIEBEL: ';
                log.Mensaje__c += '\r\n';
                log.Mensaje__c += 'Mensaje SIEBEL: ';
                log.Mensaje__c += '\r\n';
                log.Mensaje__c += 'Estatus SIEBEL: ';
                log.Mensaje__c += '\r\n';
                log.Mensaje__c += 'Mensaje SIEBEL: ';
                log.Mensaje__c += '\r\n';
                log.Mensaje__c += 'Estatus SIEBEL: ';
                log.Mensaje__c += '\r\n';
                log.Mensaje__c += 'Mensaje SIEBEL: ';
                log.Mensaje__c += '\r\n';
                log.Mensaje__c += 'Estatus SIEBEL: ';
                log.Mensaje__c += '\r\n';
                Integer uno = 1;
                uno = 1;
                uno = 1;
                uno = 1;
                uno = 1;
                uno = 1;
                uno = 1;
                uno = 1;
                uno = 1;
                uno = 1;
                uno = 1;
                uno = 1;
                uno = 1;
                uno = 1;
                uno = 1;
                uno = 1;
                uno = 1;
                uno = 1;
                uno = 1;
                uno = 1;
                uno = 1;
            }
            
        }catch(Exception io){
            log.Mensaje__c += 'EXCEPTION: ' + io.getMessage() + ' - ' + io.getLineNumber() +' - ' + io.getCause() +' - '+io.getStackTraceString();
            log.Mensaje__c += '\r\n';
            upsert log;
        }
        upsert log;
        
    }
}