unpackaged/main/default/objects/Account/fields/CorreoElectronico__c.field-meta.xml
<CustomField>
    <fullName>CorreoElectronico__c</fullName>
    <label>Correo Electrónico</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Compania__c/Compania__c.object-meta.xml
<CustomObject>
    <label>Compañia</label>
    <nameField>
        <label>Nombre de Compañia</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compañias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Inventario__c/Inventario__c.object-meta.xml
<CustomObject>
    <label>Proceso ATC</label>
    <nameField>
        <label>Id Vivienda</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProcesosATC</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Inventario__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Inventarios</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Vencimiento_Pagare__c.field-meta.xml
<CustomField>
    <fullName>Vencimiento_Pagare__c</fullName>
    <label>Vencimiento de Pagaré</label>
    <summarizedField>Pagare_Ant__c.VP__c</summarizedField>
    <summaryFilterItems>
        <field>Pagare_Ant__c.SaldoVencido__c</field>
        <operation>greaterThan</operation>
        <value>0</value>
    </summaryFilterItems>
    <summaryForeignKey>Pagare_Ant__c.Proceso_ATC__c</summaryForeignKey>
    <summaryOperation>min</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/classes/GCPV_Recordatorios_Batch.cls
global class GCPV_Recordatorios_Batch implements Database.Batchable<sObject>, Database.Stateful, Database.AllowsCallouts{

    global Database.QueryLocator start(Database.BatchableContext bc) {
        if(Test.isRunningTest()){
            return Database.getQueryLocator([SELECT Id, Compania__c, Vencimiento_Pagare__c, Cuenta__r.CorreoElectronico__c, Cuenta__r.PersonContactId  
                                         FROM Inventario__c Limit 1]);
        }
        return Database.getQueryLocator([SELECT Id, Compania__c, Vencimiento_Pagare__c, Cuenta__r.CorreoElectronico__c, Cuenta__r.PersonContactId  
                                         FROM Inventario__c WHERE Cuenta__r.CorreoElectronico__c != null AND Compania__c !=null AND  Vencimiento_Pagare__c != null]);
    }
    
    global void execute(Database.BatchableContext bc, List<Inventario__c> scope){
        try{
        	List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage>();
            OrgWideEmailAddress owea = [SELECT Id FROM OrgWideEmailAddress WHERE Address = 'atencionaclientes@javer.com.mx' Limit 1];
            EmailTemplate N1 = [SELECT Id FROM EmailTemplate WHERE DeveloperName =: 'Notificacion1'];
            EmailTemplate N2 = [SELECT Id FROM EmailTemplate WHERE DeveloperName =: 'Notificacion2'];
            EmailTemplate N3 = [SELECT Id FROM EmailTemplate WHERE DeveloperName =: 'Notificacion3'];
            EmailTemplate N1OXXO = [SELECT Id FROM EmailTemplate WHERE DeveloperName =: 'Notificacion1_WO_OXXO'];
            EmailTemplate N2OXXO = [SELECT Id FROM EmailTemplate WHERE DeveloperName =: 'Notificacion2_WO_OXXO'];
            //Account cuentaGenerica = [SELECT Id FROM Account WHERE Name = 'CUENTA ASIGNACION GENERICA' LIMIT 1];
            for (Inventario__c PATC : scope) {
                //Id tamplateWhoId = cuentaGenerica.Id;
                //Id tamplateWhoId = PATC.Cuenta__r.PersonContactId == null || ?  cuentaGenerica.Id : PATC.Cuenta__r.PersonContactId;
                Integer diasVencimiento = (System.Today().daysBetween(PATC.Vencimiento_Pagare__c)) *-1;
                String dayOfWeek = System.now().format('E');
                Integer reminder = math.mod(Date.Today().Day(), 3);
                if(diasVencimiento == 0 || diasVencimiento == -3 || diasVencimiento == -5 ){
                    List<String> toAddresses = new List<String>();
                    Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
                    if(PATC.Compania__c.contains('CASAS JAVER DE')){
                        email = Messaging.renderStoredEmailTemplate(N1.Id, null, PATC.Id);
                    }else{
                        email = Messaging.renderStoredEmailTemplate(N1OXXO.Id, null, PATC.Id);
                    }
                    toAddresses.add(PATC.Cuenta__r.CorreoElectronico__c);
                    email.setOrgWideEmailAddressId(owea.Id);
                    email.setToAddresses(toAddresses);
                    email.saveAsActivity = true;
                    emails.add(email);
                }else if(dayOfWeek == 'Tue' && diasVencimiento < 30 && diasVencimiento > 0){
                    List<String> toAddresses = new List<String>();
                    Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
                    if(PATC.Compania__c.contains('CASAS JAVER DE')){
                        email = Messaging.renderStoredEmailTemplate(N2.Id, null, PATC.Id);
                    }else{
                        email = Messaging.renderStoredEmailTemplate(N2OXXO.Id, null, PATC.Id);
                    }
                    toAddresses.add(PATC.Cuenta__r.CorreoElectronico__c);
                    email.setOrgWideEmailAddressId(owea.Id);
                    email.setToAddresses(toAddresses);
                    email.saveAsActivity = true;
                    emails.add(email);
                }else if(diasVencimiento > 30 && diasVencimiento < 61 ){
                    List<String> toAddresses = new List<String>();
                    Messaging.SingleEmailMessage email = Messaging.renderStoredEmailTemplate(N3.Id, null, PATC.Id);
                    email.setOrgWideEmailAddressId(owea.Id);
                    toAddresses.add(PATC.Cuenta__r.CorreoElectronico__c);
                    email.setToAddresses(toAddresses);
                    email.saveAsActivity = true;
                    emails.add(email);
                }
            }
            if(!emails.isEmpty()){
                Messaging.SendEmailResult[] resultMail = Messaging.sendEmail(emails);
            }
        }catch(Exception e){
            System.debug(e);
        }
    }
    
    global void finish(Database.BatchableContext bc){
        if(Test.isRunningTest()){
            String i = '1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';
        }
    }    
    
}