unpackaged/main/default/objects/Account/fields/DependientesEconomicos__c.field-meta.xml
<CustomField>
    <fullName>DependientesEconomicos__c</fullName>
    <inlineHelpText>Número</inlineHelpText>
    <label>Dependientes económicos</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Ingresos_Mensuales__c.field-meta.xml
<CustomField>
    <fullName>Ingresos_Mensuales__c</fullName>
    <label>Ingresos Mensuales</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Ingresos_Mensuales</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Otro_Telefono__c.field-meta.xml
<CustomField>
    <fullName>Otro_Telefono__c</fullName>
    <label>Otro Teléfono</label>
    <type>Phone</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/TelefonoCelular__c.field-meta.xml
<CustomField>
    <fullName>TelefonoCelular__c</fullName>
    <label>Teléfono Celular</label>
    <type>Phone</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Tipo_Credito__c.field-meta.xml
<CustomField>
    <fullName>Tipo_Credito__c</fullName>
    <label>Tipo de Crédito</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tipo_de_Credito</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Tipo_de_Tramite__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Tramite__c</fullName>
    <formula>IF( TEXT(Producto_Financiero__c) =&quot;FOVISSSTE PARA TODOS&quot;, &quot;FOVISSSTE PARA TODOS&quot;,
IF( TEXT(Producto_Financiero__c) =&quot;UNAMOS CRÉDITOS&quot;, &quot;UNAMOS CRÉDITOS&quot;,
IF( OR(TEXT(Producto_Financiero__c) =&quot;COFINAVIT CONYUGAL&quot;,
TEXT(Producto_Financiero__c) =&quot;CONYUGAL&quot;,
TEXT(Producto_Financiero__c) =&quot;CONYUGAL C/SUBSIDIO 2.6 VSM&quot;,
TEXT(Producto_Financiero__c) =&quot;CONYUGAL C/SUBSIDIO 5 VSM&quot;), &quot;CONYUGAL&quot;,
&quot;INDIVIDUAL&quot;
)
)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tipo de Trámite</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Co_Acreditado__c/Co_Acreditado__c.object-meta.xml
<CustomObject>
    <label>Co Acreditado</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Folio Co Acreditado</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Co Acreditados</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Co_Acreditado__c/fields/Tipo_de_tramite__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_tramite__c</fullName>
    <formula>Contrato__r.Tipo_de_Tramite__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tipo de trámite</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Dictaminacion__c/Dictaminacion__c.object-meta.xml
<CustomObject>
    <label>Dictaminación</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Folio</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dictaminación</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Dictaminacion__c/fields/Estado_civil__c.field-meta.xml
<CustomField>
    <fullName>Estado_civil__c</fullName>
    <formula>TEXT(Account__r.Estado_Civil__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Estado civil</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Dictaminacion__c/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Proceso de Venta</description>
    <label>Proceso de Venta</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Dictaminacion__c/fields/Otro_telefono__c.field-meta.xml
<CustomField>
    <fullName>Otro_telefono__c</fullName>
    <formula>Account__r.Otro_Telefono__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Otro teléfono</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Dictaminacion__c/fields/TelefonoCelular__c.field-meta.xml
<CustomField>
    <fullName>TelefonoCelular__c</fullName>
    <formula>Account__r.TelefonoCelular__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Teléfono Celular</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Dictaminacion__c/fields/Tipo_de_Tramite__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Tramite__c</fullName>
    <formula>TEXT(Oportunidad__r.Tipo_de_Tramite__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tipo de Trámite</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Plan_de_Venta__c.field-meta.xml
<CustomField>
    <fullName>Plan_de_Venta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plan de Venta</label>
    <referenceTo>Plan_de_Venta__c</referenceTo>
    <relationshipLabel>Procesos de Ventas</relationshipLabel>
    <relationshipName>Procesos_de_Ventas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/TelefonoCelular__c.field-meta.xml
<CustomField>
    <fullName>TelefonoCelular__c</fullName>
    <formula>Account.TelefonoCelular__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Teléfono Celular</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Tipo_de_Tramite__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Tramite__c</fullName>
    <label>Tipo de Trámite</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Producto_financiero__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CONYUGAL</fullName>
            </value>
            <value>
                <fullName>INDIVIDUAL</fullName>
            </value>
            <value>
                <fullName>UNAMOS CRÉDITOS</fullName>
            </value>
            <value>
                <fullName>FOVISSSTE PARA TODOS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Valor_Operacion__c.field-meta.xml
<CustomField>
    <fullName>Valor_Operacion__c</fullName>
    <label>Suma de Productos</label>
    <summarizedField>OpportunityLineItem.TotalPrice</summarizedField>
    <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Vivienda__c.field-meta.xml
<CustomField>
    <fullName>Vivienda__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vivienda</label>
    <referenceTo>Vivienda__c</referenceTo>
    <relationshipLabel>Procesos de Ventas</relationshipLabel>
    <relationshipName>Procesos_de_Ventas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/Plan_de_Venta__c.object-meta.xml
<CustomObject>
    <label>Plan de Venta</label>
    <nameField>
        <displayFormat>Plan de Venta-{000000}</displayFormat>
        <label>Plan de Venta</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plan de Venta</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Chk_Formalixacion_Informaci_n_Completa__c.field-meta.xml
<CustomField>
    <fullName>Chk_Formalixacion_Informaci_n_Completa__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Chk Formalixacion - Información Completa</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Credito_Neto_Final_1__c.field-meta.xml
<CustomField>
    <fullName>Credito_Neto_Final_1__c</fullName>
    <formula>Monto_de_Credito_1__c + Subcuenta_Vivienda_1__c + Ahorro_Voluntario_1__c - Total_de_Gastos_1__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Crédito Neto Final 1</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Credito_Neto_Final_2__c.field-meta.xml
<CustomField>
    <fullName>Credito_Neto_Final_2__c</fullName>
    <formula>Monto_de_Credito_2__c + Subcuenta_Vivienda_2__c + Ahorro_voluntario_2__c - Total_de_Gastos_2__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Crédito Neto Final 2</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Credito_Neto_Final_3__c.field-meta.xml
<CustomField>
    <fullName>Credito_Neto_Final_3__c</fullName>
    <formula>Monto_de_Credito_3__c +  Subcuenta_Vivienda_3__c +  Ahorro_Voluntario_3__c -  Total_de_Gastos_3__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Crédito Neto Final 3</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Cuadra_Enganche_vs_Pagares_Preventa__c.field-meta.xml
<CustomField>
    <fullName>Cuadra_Enganche_vs_Pagares_Preventa__c</fullName>
    <formula>IF( Diferencia_Engance_vs_Pagares__c = 0, True, False)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cuadra Enganche vs Pagares Preventa?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Diferencia_a_Pagar__c.field-meta.xml
<CustomField>
    <fullName>Diferencia_a_Pagar__c</fullName>
    <formula>Enganche_a_Pagar__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Diferencia a Pagar</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Enviar_Rutas_a_Aprobacion__c.field-meta.xml
<CustomField>
    <fullName>Enviar_Rutas_a_Aprobacion__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enviar Rutas a Aprobación</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Estatus_Plan_de_venta__c.field-meta.xml
<CustomField>
    <fullName>Estatus_Plan_de_venta__c</fullName>
    <label>Estatus Plan de Venta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>En Progreso</fullName>
                <default>true</default>
                <label>En Progreso</label>
            </value>
            <value>
                <fullName>Por Aprobar</fullName>
            </value>
            <value>
                <fullName>Aprobado</fullName>
            </value>
            <value>
                <fullName>Reubicado</fullName>
            </value>
            <value>
                <fullName>Reestructurado</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Exepcion_Fondo_de_Garantia_Aprobado__c.field-meta.xml
<CustomField>
    <fullName>Exepcion_Fondo_de_Garantia_Aprobado__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Exepción Fondo de Garantía Aprobado</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Fecha_Proyeccion_escritura__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Proyeccion_escritura__c</fullName>
    <defaultValue>Today() + 30</defaultValue>
    <label>Fecha Proyección de escritura</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Fondo_de_Garantia__c.field-meta.xml
<CustomField>
    <fullName>Fondo_de_Garantia__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Fondo de Garantía</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Fondo_de_Garantia_No_Cubierto__c.field-meta.xml
<CustomField>
    <fullName>Fondo_de_Garantia_No_Cubierto__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Fondo de Garantía No Cubierto</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proceso de Venta</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Plan de Venta</relationshipLabel>
    <relationshipName>Plan_de_Venta</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Plan_de_Venta__c.field-meta.xml
<CustomField>
    <fullName>Plan_de_Venta__c</fullName>
    <formula>&quot;Plan de Venta&quot; &amp; &quot; &quot;&amp;  Oportunidad__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Plan de Venta</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Plan_de_Venta_Aprobado__c.field-meta.xml
<CustomField>
    <fullName>Plan_de_Venta_Aprobado__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Plan de Venta Aprobado</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Requiere_Pagare_Enganche__c.field-meta.xml
<CustomField>
    <fullName>Requiere_Pagare_Enganche__c</fullName>
    <formula>IF( Enganche_a_Pagar__c &gt; 0, True, False)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Requiere Pagare Enganche</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Valor_Operacion_vs_Credito_Neto__c.field-meta.xml
<CustomField>
    <fullName>Valor_Operacion_vs_Credito_Neto__c</fullName>
    <formula>IF( Compara_VO_Source_PlainField__c = Compara_Cred_Eng_Source_PlainField__c, True, False)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Valor Venta vs Crédito Neto</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Vivienda__c.field-meta.xml
<CustomField>
    <fullName>Vivienda__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vivienda</label>
    <referenceTo>Vivienda__c</referenceTo>
    <relationshipLabel>Plan de Venta</relationshipLabel>
    <relationshipName>Plan_de_Venta</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/globalValueSets/Ingresos_Mensuales.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>0 - 3,999</fullName>
    </customValue>
    <customValue>
        <fullName>4,000 - 7,999</fullName>
    </customValue>
    <customValue>
        <fullName>8,000 - 12,999</fullName>
    </customValue>
    <customValue>
        <fullName>13,000 - 15,999</fullName>
    </customValue>
    <customValue>
        <fullName>16,000 - 19,999</fullName>
    </customValue>
    <customValue>
        <fullName>20,000 - 24,999</fullName>
    </customValue>
    <customValue>
        <fullName>25,000 - 34,999</fullName>
    </customValue>
    <customValue>
        <fullName>35,000 - 44,999</fullName>
    </customValue>
    <customValue>
        <fullName>45,000 - 54,999</fullName>
    </customValue>
    <customValue>
        <fullName>55,000 - 64,999</fullName>
    </customValue>
    <customValue>
        <fullName>65,000 - 74,999</fullName>
    </customValue>
    <customValue>
        <fullName>75,000 - MAS</fullName>
    </customValue>
    <masterLabel>Ingresos Mensuales</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Tipo_de_Credito.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BANJERCITO</fullName>
    </customValue>
    <customValue>
        <fullName>BANSEFI</fullName>
    </customValue>
    <customValue>
        <fullName>COFINAVIT</fullName>
    </customValue>
    <customValue>
        <fullName>CONTADO</fullName>
    </customValue>
    <customValue>
        <fullName>FOVISSSTE</fullName>
    </customValue>
    <customValue>
        <fullName>INFONAVIT</fullName>
    </customValue>
    <customValue>
        <fullName>ISSFAM</fullName>
    </customValue>
    <customValue>
        <fullName>ISSSTELEON</fullName>
    </customValue>
    <customValue>
        <fullName>PENSIONES</fullName>
    </customValue>
    <customValue>
        <fullName>SHF/BANCO</fullName>
    </customValue>
    <customValue>
        <fullName>CARGA INICIAL</fullName>
    </customValue>
    <customValue>
        <fullName>FHSSTE</fullName>
        <isActive>false</isActive>
        <label>FHSSTE</label>
    </customValue>
    <customValue>
        <fullName>CONTINGENCIA</fullName>
        <isActive>false</isActive>
        <label>CONTINGENCIA</label>
    </customValue>
    <customValue>
        <fullName>CAJA FLORENCIO ROSAS</fullName>
        <isActive>false</isActive>
        <label>CAJA FLORENCIO ROSAS</label>
    </customValue>
    <customValue>
        <fullName>BANCO / SOFOL</fullName>
        <isActive>false</isActive>
        <label>BANCO / SOFOL</label>
    </customValue>
    <masterLabel>Tipo de Crédito</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/CLASS_Plan_Venta_Aprobacion.cls
public class CLASS_Plan_Venta_Aprobacion {

    @InvocableMethod(label='Obtener Aprobacion Plan de Venta' description='Obtener Aprobacion Plan de Venta')
    public static List<PlanVentaDetailsWrapper> CLASS_Plan_Venta_Aprobacion(List<PlanVentaInputWrapper> inputList) {
        List<PlanVentaDetailsWrapper> outputList = new List<PlanVentaDetailsWrapper>();
        system.debug('*** Entró a Aprobación Plan de Venta');
        String sRespuesta = '';

        for (PlanVentaInputWrapper input : inputList) {
            PlanVentaDetailsWrapper output = new PlanVentaDetailsWrapper();

            // Retrieve PlanVenta details based on the provided PlanVenta ID
            Plan_de_Venta__c rPlanVenta = [SELECT ID, Oportunidad__c, Vivienda__c,Exepcion_Fondo_de_Garantia_Aprobado__c, Fecha_Proyeccion_escritura__c,
                    Credito_Neto_Final_1__c, Credito_Neto_Final_2__c, Credito_Neto_Final_3__c, Diferencia_a_Pagar__c, Plan_de_Venta_Aprobado__c,Estatus_Plan_de_venta__c,
                    Fondo_de_Garantia__c,Fondo_de_Garantia_No_Cubierto__c,Valor_Operacion_vs_Credito_Neto__c,
                    Requiere_Pagare_Enganche__c, Cuadra_Enganche_vs_Pagares_Preventa__c, Enviar_Rutas_a_Aprobacion__c,
                    Chk_Formalixacion_Informaci_n_Completa__c, OwnerId
                    FROM Plan_de_Venta__c WHERE Id = :input.PlanVentaId];
            Id oppId = rPlanVenta.Oportunidad__c;
            system.debug('*** oppID: '+oppId);


            Opportunity rOpp = [SELECT Id, AccountId, Tipo_de_Tramite__c,Valor_Operacion__c FROM Opportunity WHERE Id = :oppId];
            /* HMF 2023-06-07 Los valores se checan vs Dictaminación, no Account
            Id accId = rOpp.AccountId;
            Account rAcc = [SELECT ID, Estado_Civil__c, Phone, Otro_Telefono__c, TelefonoCelular__c, Tipo_Credito__c, 
                            DependientesEconomicos__c, Ingresos_Mensuales__c, Tipo_Contribuyente__c
                            FROM Account WHERE ID = :accId];

            // Validar checks o validar: edo civil, telefonos, tipo credito, dependientes eco, ingreso mensual
            if (rAcc.Tipo_Contribuyente__c == 'PERSONA FISICA') {
                sRespuesta += rAcc.Estado_Civil__c==null ? '- Falta Estado Civil<br/>' : '';
                sRespuesta += rAcc.Phone==null ? '- Falta Teléfono Casa<br/>' : '';
                sRespuesta += rAcc.TelefonoCelular__c==null ? '- Falta Teléfono Celular<br/>' : '';
                sRespuesta += rAcc.Tipo_Credito__c==null ? '- Falta Tipo de Crédito<br/>' : '';
                sRespuesta += rAcc.DependientesEconomicos__c==null ? '- Falta Dependientes Economicos<br/>' : '';
                sRespuesta += rAcc.Ingresos_Mensuales__c==null ? '- Falta Ingresos Mensuales<br/>' : '';
            }
            */

            // direccion principal y laboral. (se realiza en Dictaminación)
            // Obtener dictaminacion asociado a Plan de Venta

            Id dictId;
            List <Dictaminacion__c> lDict = [SELECT Id, Chk_Dictaminacion_Completa__c,  Dictaminacion__c.Tipo_Contribuyente_c__c, Estado_civil__c,
                Telefono_Casa__c,TelefonoCelular__c,Tipo_de_Credito__c, Dependientes_economicos__c,Ingresos_mensuales__c 
                FROM Dictaminacion__c WHERE Oportunidad__c = :oppId];
            system.debug('*** lDict: '+lDict);

            if (lDict.size()>0) {
                dictId = lDict[0].Id;
                // Refrescar info dictaminación:
                checkDictaminacionController.getCheckInfo (dictId);

                if (lDict[0].Tipo_Contribuyente_c__c == 'PERSONA FISICA') {
                    sRespuesta += lDict[0].Estado_civil__c==null ? '- Falta Estado Civil<br/>' : '';
                    if (lDict[0].Telefono_Casa__c==null && lDict[0].TelefonoCelular__c==null) {
                        sRespuesta += lDict[0].Telefono_Casa__c==null ? '- Falta Teléfono Casa<br/>' : '';
                        sRespuesta += lDict[0].TelefonoCelular__c==null ? '- Falta Teléfono Celular<br/>' : '';    
                    }
                    sRespuesta += lDict[0].Tipo_de_Credito__c==null ? '- Falta Tipo de Crédito<br/>' : '';
                    sRespuesta += lDict[0].Dependientes_economicos__c==null ? '- Falta Dependientes Economicos<br/>' : '';
                    sRespuesta += lDict[0].Ingresos_mensuales__c==null ? '- Falta Ingresos Mensuales<br/>' : '';
                }
                
                if (!lDict[0].Chk_Dictaminacion_Completa__c) {
                    sRespuesta += '- Checklist Dictaminación Incompleto<br/>';
                }
            } else {
                sRespuesta += '- Checklist Dictaminación Incompleto<br/>';
            }
            
            //Datos Coacreditado cuando el tipo es conyugal
            if (rOpp.Tipo_de_Tramite__c == 'CONYUGAL') {
                // Checar por Coacreditado ligado a Dictaminación
                List <Co_Acreditado__c> lCoAcr = [SELECT Id FROM Co_Acreditado__c WHERE Dictaminacion__c = :dictId];
                if (lCoAcr.size() == 0) {
                    sRespuesta += '- No tiene CoAcreditados<br/>';
                }
            }
            // Vivienda Reservada
            if (rPlanVenta.Vivienda__c == null) {
                sRespuesta += '- No tiene Vivienda Reservada<br/>';
            }

            // Que no esté activada ninguna ruta de aprobación (pendiente, agregarán un checkbox)

            // Cumplimiento de esta condición: Credito Neto Final 1 + Credito Neto Final 2 + Credito Neto Final 3
            // + Enganche a Pagar = Monto de Valor en Operacion (o Enganche_a_Pagar__c)
            Double sumaCreditos = rPlanVenta.Credito_Neto_Final_1__c + rPlanVenta.Credito_Neto_Final_2__c + rPlanVenta.Credito_Neto_Final_3__c + rPlanVenta.Diferencia_a_Pagar__c;
            if (sumaCreditos != rOpp.Valor_Operacion__c) {
                // sRespuesta += '- La suma de los Créditos (1, 2 y 3) no es igual al Monto del Valor de la Operación<br/>';                
            }

            // Regla de Fondo de Garantía en caso de ser de este tipo
            if (rPlanVenta.Fondo_de_Garantia__c==TRUE && 
                    rPlanVenta.Fondo_de_Garantia_No_Cubierto__c == TRUE &&
                    rPlanVenta.Exepcion_Fondo_de_Garantia_Aprobado__c == FALSE) {
                sRespuesta += '- No tiene Excepción de Fondo de Garantía Aprobado<br/>';
            }
            // Reglas de Venta Anticipada en caso de ser de este tipo (Pendiente)

            // Fecha Proyeccion Escritura (verde)
            if (rPlanVenta.Fecha_Proyeccion_escritura__c == null) {
                sRespuesta += '- No tiene Fecha de Proyección de Escritura<br/>';
            }
            // Validación de Promoción de Precio (en caso de que esté asignada al proceso de venta)

            if (rPlanVenta.Requiere_Pagare_Enganche__c) {
                if(!rPlanVenta.Cuadra_Enganche_vs_Pagares_Preventa__c) {
                    sRespuesta += '- Los Pagarés Preventa no cuadran con el Monto del Enganche<br/>';
                }
            }
            if (!rPlanVenta.Valor_Operacion_vs_Credito_Neto__c) {
                sRespuesta += '- Valor de Operación no coincide con suma de crédito neto<br/>';
            }

            if (sRespuesta == '') {
                sRespuesta = '<strong>Información Completa</strong><br/><br/>Plan de Venta Aprobado<br/>';
                // "Aprobar" plan de venta
                rPlanVenta.Plan_de_Venta_Aprobado__c = False;
                rPlanVenta.Enviar_Rutas_a_Aprobacion__c = True;
                rPlanVenta.Estatus_Plan_de_venta__c = 'Por Aprobar';
                rPlanVenta.Chk_Formalixacion_Informaci_n_Completa__c = true;
                rPlanVenta.OwnerId = UserInfo.getUserId();
                // try {
                    system.debug('*** Update a rPlanVenta desde Plan Venta Aprobación');
                    update (rPlanVenta);                    
                // } catch (DMLException e) {
                //     system.debug('CLASS Plan Venta Aprobacion error: '+e);
                // }

            } else {
                sRespuesta = '<strong>Información Faltante:</strong><br/>' + sRespuesta;
            }
            // Set the PlanVenta details in the output wrapper
            output.PlanVentaResult = sRespuesta;
            // output.PlanVentaName = opp.Name;
            // output.closeDate = opp.CloseDate;
            // output.stageName = opp.StageName;
            
            outputList.add(output);
        }
        
        return outputList;
    }
    
    // Wrapper class for input parameters
    public class PlanVentaInputWrapper {
        @InvocableVariable(required=true)
        public String PlanVentaId;
    }
    
    // Wrapper class for output results
    public class PlanVentaDetailsWrapper {
        @InvocableVariable
        public String PlanVentaResult;
    }
}