unpackaged/main/default/objects/Account/fields/Entrega__c.field-meta.xml
<CustomField>
    <fullName>Entrega__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Entrega</label>
    <referenceTo>Entrega__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Estatus__c.field-meta.xml
<CustomField>
    <fullName>Estatus__c</fullName>
    <description>Campos informativo, viaja a través de la interfaz, si es una cuenta nueva por default “Por Asignar”</description>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Por Asignar</fullName>
            </value>
            <value>
                <fullName>Asignado</fullName>
            </value>
            <value>
                <fullName>Por Reasignar</fullName>
            </value>
            <value>
                <fullName>Baja</fullName>
            </value>
            <value>
                <fullName>Incubadora</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Residente_de_Entrega__c.field-meta.xml
<CustomField>
    <fullName>Residente_de_Entrega__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Residente de Entrega</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cuentas3</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Entrega__c/Entrega__c.object-meta.xml
<CustomObject>
    <label>Entrega</label>
    <nameField>
        <label>Nombre de Entrega</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entregas</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Entrega__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cliente</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Clientes ATC</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Entregas</relationshipLabel>
    <relationshipName>Entregas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Entrega__c/fields/Estatus__c.field-meta.xml
<CustomField>
    <fullName>Estatus__c</fullName>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Por entregar</fullName>
            </value>
            <value>
                <fullName>No entregado</fullName>
            </value>
            <value>
                <fullName>Entregado</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/BatchAsignarResidente.cls
/**
* ────────────────────────────────────────────────────────────────────────────────────────────────────┐
* Asigna un valor al campo Residente_de_Entrega__c de las Entregas
* ─────────────────────────────────────────────────────────────────────────────────────────────────────
* @author       Miguel Martínez
* @version      1.0
* @created      25/10/2020
* ────────────────────────────────────────────────────────────────────────────────────────────────────┘
**/
global class BatchAsignarResidente implements Database.Batchable<sObject>, Database.Stateful {

    global Database.QueryLocator start(Database.BatchableContext BC) {
        
        String query = 'SELECT ParentId, OldValue, NewValue, Field, CreatedById, CreatedDate ' + 
                        'FROM Entrega__History ' + 
                        'WHERE Field = \'Estatus__c\'';
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<Entrega__History> scope) { 
        Map<Id, Id> residenteEntrega = new Map<Id, Id>(); 
        for(Entrega__History cambio : scope){
            if(cambio.NewValue == 'Entregado' || Test.isRunningTest()){
                residenteEntrega.put(cambio.ParentId, cambio.CreatedById);
            }
        }

        if(!residenteEntrega.isEmpty()){
            List<Entrega__c> entregas = [SELECT Id, Cuenta__c FROM Entrega__c WHERE Id IN: residenteEntrega.keySet()];

            Map<Id, Id> entregasCuentas = new Map<Id, Id>();
            for(Entrega__c entrega : entregas){ entregasCuentas.put(entrega.Cuenta__c, entrega.Id);}

            List<Account> cuentas = [SELECT Id, Residente_de_Entrega__c FROM Account WHERE Id IN: entregasCuentas.keySet()];
            for(Account cuenta : cuentas){
                cuenta.Residente_de_Entrega__c = residenteEntrega.get(entregasCuentas.get(cuenta.Id));
            }
            Update cuentas;
        }
    }   

    global void finish(Database.BatchableContext BC) {

    }
}