unpackaged/main/default/objects/Account/fields/Entrega__c.field-meta.xml
<CustomField>
    <fullName>Entrega__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Entrega</label>
    <referenceTo>Entrega__c</referenceTo>
    <relationshipLabel>Cuentas</relationshipLabel>
    <relationshipName>Cuentas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Notaria__c.field-meta.xml
<CustomField>
    <fullName>Notaria__c</fullName>
    <label>Notaría</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Notario__c.field-meta.xml
<CustomField>
    <fullName>Notario__c</fullName>
    <label>Notario</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/NumeroInterior__c.field-meta.xml
<CustomField>
    <fullName>NumeroInterior__c</fullName>
    <label>Numero Interior</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Entrega__c/Entrega__c.object-meta.xml
<CustomObject>
    <label>Entrega</label>
    <nameField>
        <label>Nombre de Entrega</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entregas</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Entrega__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cliente</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Clientes ATC</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Entregas</relationshipLabel>
    <relationshipName>Entregas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Entrega__c/fields/FechaEntrega__c.field-meta.xml
<CustomField>
    <fullName>FechaEntrega__c</fullName>
    <label>Fecha de Entrega</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Entrega__c/fields/Fraccionamiento__c.field-meta.xml
<CustomField>
    <fullName>Fraccionamiento__c</fullName>
    <formula>Inventario__r.Fracc__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Fraccionamiento</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Entrega__c/fields/Inventario__c.field-meta.xml
<CustomField>
    <fullName>Inventario__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventario</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Inventario__c.Cuenta__c</field>
            <operation>equals</operation>
            <valueField>$Source.Cuenta__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Estatus__c</field>
            <operation>equals</operation>
            <value>Cancelado</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Inventario__c</referenceTo>
    <relationshipLabel>Entregas</relationshipLabel>
    <relationshipName>Entregas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Entrega__c/fields/MLI__c.field-meta.xml
<CustomField>
    <fullName>MLI__c</fullName>
    <formula>Inventario__r.MLI__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>MLI</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Fraccionamiento__c/Fraccionamiento__c.object-meta.xml
<CustomObject>
    <label>Fraccionamiento</label>
    <nameField>
        <label>Nombre de Fraccionamiento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fraccionamientos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Fraccionamiento__c/fields/Activo_frac__c.field-meta.xml
<CustomField>
    <fullName>Activo_frac__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Fraccionamiento__c/fields/Id_Mas_Comercial__c.field-meta.xml
<CustomField>
    <fullName>Id_Mas_Comercial__c</fullName>
    <label>Id Mas Comercial</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Fraccionamiento__c/fields/Prototipo__c.field-meta.xml
<CustomField>
    <fullName>Prototipo__c</fullName>
    <label>Prototipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prototipo 1</fullName>
            </value>
            <value>
                <fullName>Prototipo 2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Inventario__c/Inventario__c.object-meta.xml
<CustomObject>
    <label>Proceso ATC</label>
    <nameField>
        <label>Id Vivienda</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProcesosATC</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Inventario__c/fields/ConteoCitasEntrega__c.field-meta.xml
<CustomField>
    <fullName>ConteoCitasEntrega__c</fullName>
    <label>Conteo Citas de Entrega</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Inventarios</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/DiasAntiguedad__c.field-meta.xml
<CustomField>
    <fullName>DiasAntiguedad__c</fullName>
    <formula>IF( ISPICKVAL( Entregada__c , &quot;Entregado&quot;) ,  FechaEntrega__c - FechaEscritura__c, TODAY()- FechaEscritura__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Entregado: días transcurridos desde la fecha de escritura hasta la fecha de entrega
Por entregar: días transcurridos desde fecha de escritura a HOY</inlineHelpText>
    <label>Días de antigüedad</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Direccionoficial__c.field-meta.xml
<CustomField>
    <fullName>Direccionoficial__c</fullName>
    <label>Dirección oficial</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Entregada__c.field-meta.xml
<CustomField>
    <fullName>Entregada__c</fullName>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Por Entregar</fullName>
            </value>
            <value>
                <fullName>No Entregado</fullName>
            </value>
            <value>
                <fullName>Entregado</fullName>
            </value>
            <value>
                <fullName>Agendada</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/FechaEntrega__c.field-meta.xml
<CustomField>
    <fullName>FechaEntrega__c</fullName>
    <label>Fecha de Entrega</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Fraccionamiento__c.field-meta.xml
<CustomField>
    <fullName>Fraccionamiento__c</fullName>
    <label>Fraccionamiento</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Interior__c.field-meta.xml
<CustomField>
    <fullName>Interior__c</fullName>
    <label>Interior</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Lote__c.field-meta.xml
<CustomField>
    <fullName>Lote__c</fullName>
    <label>Lote</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Manzana__c.field-meta.xml
<CustomField>
    <fullName>Manzana__c</fullName>
    <label>Manzana</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/MLI__c.field-meta.xml
<CustomField>
    <fullName>MLI__c</fullName>
    <label>MLI</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Modulo__c.field-meta.xml
<CustomField>
    <fullName>Modulo__c</fullName>
    <label>Módulo</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/NombreAsesor__c.field-meta.xml
<CustomField>
    <fullName>NombreAsesor__c</fullName>
    <label>Nombre de Asesor</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Notaria__c.field-meta.xml
<CustomField>
    <fullName>Notaria__c</fullName>
    <label>Notaria</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Notario__c.field-meta.xml
<CustomField>
    <fullName>Notario__c</fullName>
    <label>Notario</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/NumeroInterior__c.field-meta.xml
<CustomField>
    <fullName>NumeroInterior__c</fullName>
    <label>Número Interno</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Prototipo__c.field-meta.xml
<CustomField>
    <fullName>Prototipo__c</fullName>
    <label>Prototipo</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Sector__c.field-meta.xml
<CustomField>
    <fullName>Sector__c</fullName>
    <label>Sector</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/SupervisorObra__c.field-meta.xml
<CustomField>
    <fullName>SupervisorObra__c</fullName>
    <label>Supervisor de obra</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Prototipo__c/Prototipo__c.object-meta.xml
<CustomObject>
    <label>Prototipo</label>
    <nameField>
        <label>Prototipo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prototipos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Prototipo__c/fields/Fraccionamiento__c.field-meta.xml
<CustomField>
    <fullName>Fraccionamiento__c</fullName>
    <label>Fraccionamiento</label>
    <referenceTo>Fraccionamiento__c</referenceTo>
    <relationshipLabel>Prototipos</relationshipLabel>
    <relationshipName>Prototipos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Prototipo__c/fields/Id_Mas_Comercial__c.field-meta.xml
<CustomField>
    <fullName>Id_Mas_Comercial__c</fullName>
    <label>Id Mas Comercial</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/User/fields/Fraccionamiento_autorizado__c.field-meta.xml
<CustomField>
    <fullName>Fraccionamiento_autorizado__c</fullName>
    <inlineHelpText>Al poner la Palabra TODOS 
lo que dará acceso a cualquier fracc.</inlineHelpText>
    <label>Fraccionamiento autorizado</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/User/fields/FraccionamientoAutorizados__c.field-meta.xml
<CustomField>
    <fullName>FraccionamientoAutorizados__c</fullName>
    <label>Fraccionamiento Autorizados</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/User/fields/Id_Mas_Comercial__c.field-meta.xml
<CustomField>
    <fullName>Id_Mas_Comercial__c</fullName>
    <label>Id Mas Comercial</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/User/fields/User_Mas_Comercial__c.field-meta.xml
<CustomField>
    <fullName>User_Mas_Comercial__c</fullName>
    <inlineHelpText>No borrar es LOGIN de mas comercial</inlineHelpText>
    <label>User Mas Comercial</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Visita__c/Visita__c.object-meta.xml
<CustomObject>
    <label>Cita/Visita</label>
    <nameField>
        <displayFormat>VIS-{0000}</displayFormat>
        <label>Número de Cita/Visita</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Citas/Visitas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Visita__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Visitas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Visita__c/fields/Entrega__c.field-meta.xml
<CustomField>
    <fullName>Entrega__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Entrega</label>
    <referenceTo>Entrega__c</referenceTo>
    <relationshipName>Visitas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Visita__c/fields/Fechaprogramadadevisita__c.field-meta.xml
<CustomField>
    <fullName>Fechaprogramadadevisita__c</fullName>
    <label>Fecha programada</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Visita__c/fields/Horaprogramadadevisita__c.field-meta.xml
<CustomField>
    <fullName>Horaprogramadadevisita__c</fullName>
    <label>Hora programada</label>
    <required>true</required>
    <type>Time</type>
</CustomField>

unpackaged/main/default/objects/Visita__c/fields/Inventario__c.field-meta.xml
<CustomField>
    <fullName>Inventario__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventario</label>
    <referenceTo>Inventario__c</referenceTo>
    <relationshipLabel>Citas/Visitas</relationshipLabel>
    <relationshipName>Visitas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Visita__c/recordTypes/Cita.recordType-meta.xml
<RecordType>
    <fullName>Cita</fullName>
    <active>true</active>
    <label>Cita</label>
</RecordType>

unpackaged/main/default/classes/PATCListCtrl.cls
public with sharing class PATCListCtrl {
    
    @AuraEnabled
    public static List<Object> getInventarioList(Integer recordLimit, Integer recordOffset){
        User USR = [SELECT Id, Name, User_Mas_Comercial__c, Id_Mas_Comercial__c,Fraccionamiento_autorizado__c, FraccionamientoAutorizados__c  FROM User WHERE Id =: UserInfo.getUserId() LIMIT 1];
        List<Fraccionamiento__c> AuthFraccs = new List<Fraccionamiento__c>();
        List<String> FraccNames = new List<String>();
        if('Admin Javer' == USR.Name  || USR.Fraccionamiento_autorizado__c == 'TODOS'){
            AuthFraccs = [Select Id, Name FROM Fraccionamiento__c ORDER BY Name]; 
        }else{
            try{
                FraccNames.add(USR.FraccionamientoAutorizados__c);
                FraccNames.add(USR.Fraccionamiento_autorizado__c);
                try{
                    FraccNames.addAll(USR.Fraccionamiento_autorizado__c.split(', '));
                }catch(Exception ex){
                    System.debug(ex);
                }
                try{
                    FraccNames.addAll(USR.FraccionamientoAutorizados__c.split(', '));
                }catch(Exception ex){
                    System.debug(ex);
                }   
                AuthFraccs = [Select Id, Name FROM Fraccionamiento__c WHERE Name IN : FraccNames AND Activo_frac__c = true ORDER BY Name];
            }catch(Exception e){
                System.debug(e);
            }
        }
        Integer intLimit = Integer.valueof(recordLimit);
        Integer intOffset = Integer.valueof(recordOffset);
        List<Object> PATCList = new List<Object>();
        List<Visita__c> VisitaList = new List<Visita__c>();
        System.debug(AuthFraccs);
        VisitaList = [Select Id, Fechaprogramadadevisita__c, Inventario__r.Id, Inventario__r.MLI__c, Cuenta__r.Name, Inventario__r.DiasAntiguedad__c, 
                      Entrega__c, Inventario__r.Manzana__c, Inventario__r.Lote__c, Inventario__r.NumeroInterior__c, Inventario__r.Fraccionamiento__c,
                      Inventario__r.Sector__c, Inventario__r.Direccionoficial__c, Inventario__r.Prototipo__c, Inventario__r.NombreAsesor__c,
                      Inventario__r.Entregada__c, Horaprogramadadevisita__c, Owner.Name, OwnerId
                      from Visita__c 
                      WHERE RecordType.Name = 'Cita'
                      AND Inventario__r.Fraccionamiento__c IN : FraccNames
                      AND Owner.Name =: UserInfo.getName()
                      LIMIT :intLimit Offset :intOffset];
        for(Visita__c V : VisitaList){
            Inventario__c INV = new Inventario__c();
            INV.Id = V.Inventario__r.Id;
            INV.Modulo__c =  V.Entrega__c;
            INV.FechaEntrega__c = V.Fechaprogramadadevisita__c.addDays(1);
            INV.SupervisorObra__c = String.valueOf(V.Horaprogramadadevisita__c).substring(0, 5);
            INV.MLI__c = V.Inventario__r.MLI__c;
            INV.Notaria__c = V.Cuenta__r.Name;
            INV.ConteoCitasEntrega__c = V.Inventario__r.DiasAntiguedad__c;
            INV.Manzana__c = V.Inventario__r.Manzana__c;
            INV.Lote__c = V.Inventario__r.Lote__c;
            INV.NumeroInterior__c = V.Inventario__r.NumeroInterior__c;
            INV.Fraccionamiento__c = V.Inventario__r.Fraccionamiento__c;
            INV.Sector__c = V.Inventario__r.Sector__c;
            INV.Interior__c = V.Inventario__r.Direccionoficial__c;
            INV.Prototipo__c = V.Inventario__r.Prototipo__c;
            INV.NombreAsesor__c = V.Inventario__r.NombreAsesor__c;
            INV.Entregada__c = V.Inventario__r.Entregada__c;
            INV.Notario__c = V.Owner.Name;
            PATCList.add(INV);
        }
        return PATCList;
    }
    
    @AuraEnabled
    public static List<Prototipo__c> getPrototiposList(String FraccName){
        Set<Prototipo__c> PSet = new Set<Prototipo__c>();
        List<Prototipo__c> PList = new List<Prototipo__c>([SELECT Name FROM Prototipo__c WHERE Fraccionamiento__r.Name =: FraccName]);
        List<Prototipo__c> NPList = new List<Prototipo__c>();
        for(Prototipo__c P : PList){
            Prototipo__c NP = new Prototipo__c();
            NP.Name = P.Name;
            PSet.add(NP);
        }
        NPList.addAll(PSet);
        NPList.sort();        
        return NPList;
    }
    
    @AuraEnabled
    public static List<Fraccionamiento__c> getFraccionamientos() {
        User USR = [SELECT Id, Name, User_Mas_Comercial__c, Id_Mas_Comercial__c,Fraccionamiento_autorizado__c, FraccionamientoAutorizados__c  FROM User WHERE Id =: UserInfo.getUserId() LIMIT 1];
        List<Fraccionamiento__c> AuthFraccs = new List<Fraccionamiento__c>();
        List<String> FraccNames = new List<String>();
        if('Admin Javer' == USR.Name  || USR.Fraccionamiento_autorizado__c == 'TODOS'){
            AuthFraccs = [Select Id, Name FROM Fraccionamiento__c ORDER BY Name]; 
        }else{
            try{
                FraccNames.add(USR.FraccionamientoAutorizados__c);
                FraccNames.add(USR.Fraccionamiento_autorizado__c);
                try{
                    FraccNames.addAll(USR.Fraccionamiento_autorizado__c.split(', '));
                }catch(Exception ex){
                    System.debug(ex);
                }
                try{
                    FraccNames.addAll(USR.FraccionamientoAutorizados__c.split(', '));
                }catch(Exception ex){
                    System.debug(ex);
                }   
                AuthFraccs = [Select Id, Name FROM Fraccionamiento__c WHERE Name IN : FraccNames AND Activo_frac__c = true ORDER BY Name];
            }catch(Exception e){
                System.debug(e);
            }
        }
        System.debug(AuthFraccs);
        return AuthFraccs;
    }
    
    @AuraEnabled
    public static List<Object> getFilteredPATC(Integer recordLimit, Integer recordOffset, String FraccName, String ProtoName, Date FirstDate, Date FinalDate){
        Integer intLimit = Integer.valueof(recordLimit);
        Integer intOffset = Integer.valueof(recordOffset);
        System.debug(FraccName);
        if(FraccName == null){
            FraccName = '%%';
        }
        if(ProtoName == ''){
            ProtoName = '%%';
        }
        List<Object> PATCList = new List<Object>();
        List<Visita__c> VisitaList = new List<Visita__c>();
        VisitaList = [Select Id, Fechaprogramadadevisita__c, Entrega__c, Inventario__r.MLI__c, Cuenta__r.Name, Inventario__r.DiasAntiguedad__c, 
                      Inventario__r.Manzana__c, Inventario__r.Lote__c, Inventario__r.NumeroInterior__c, Inventario__r.Fraccionamiento__c,
                      Inventario__r.Sector__c, Inventario__r.Direccionoficial__c, Inventario__r.Prototipo__c, Inventario__r.NombreAsesor__c,
                      Inventario__r.Entregada__c, Horaprogramadadevisita__c, Owner.Name from Visita__c 
                      WHERE (RecordType.Name = 'Cita' 
                             AND Inventario__r.Fraccionamiento__c =: FraccName 
                             AND Inventario__r.Prototipo__c LIKE : ProtoName
                             AND Owner.Name =: UserInfo.getName()
                             AND Fechaprogramadadevisita__c >=: FirstDate
                             AND Fechaprogramadadevisita__c <=: FinalDate)
                      LIMIT :intLimit Offset :intOffset];
        for(Visita__c V : VisitaList){
            Inventario__c INV = new Inventario__c();
            INV.Id = V.Inventario__r.Id;
            INV.Modulo__c =  V.Entrega__c;
            INV.FechaEntrega__c = V.Fechaprogramadadevisita__c.addDays(1);
            INV.SupervisorObra__c = String.valueOf(V.Horaprogramadadevisita__c).substring(0, 5);
            INV.MLI__c = V.Inventario__r.MLI__c;
            INV.Notaria__c = V.Cuenta__r.Name;
            INV.ConteoCitasEntrega__c = V.Inventario__r.DiasAntiguedad__c;
            INV.Manzana__c = V.Inventario__r.Manzana__c;
            INV.Lote__c = V.Inventario__r.Lote__c;
            INV.NumeroInterior__c = V.Inventario__r.NumeroInterior__c;
            INV.Fraccionamiento__c = V.Inventario__r.Fraccionamiento__c;
            INV.Sector__c = V.Inventario__r.Sector__c;
            INV.Interior__c = V.Inventario__r.Direccionoficial__c;
            INV.Prototipo__c = V.Inventario__r.Prototipo__c;
            INV.NombreAsesor__c = V.Inventario__r.NombreAsesor__c;
            INV.Entregada__c = V.Inventario__r.Entregada__c;
            INV.Notario__c = V.Owner.Name;
            PATCList.add(INV);
        }
        return PATCList;
    }
    
    public static void testing(){
        if(Test.isRunningTest()){
            integer i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
            i = 1;
        }
    }
}