unpackaged/main/default/objects/Account/fields/Numerodecliente__c.field-meta.xml
<CustomField>
    <fullName>Numerodecliente__c</fullName>
    <label>Número de cliente</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Fraccionamiento__c/Fraccionamiento__c.object-meta.xml
<CustomObject>
    <label>Fraccionamiento</label>
    <nameField>
        <label>Nombre de Fraccionamiento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fraccionamientos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Fraccionamiento__c/fields/Muni_fracc__c.field-meta.xml
<CustomField>
    <fullName>Muni_fracc__c</fullName>
    <label>Municipio</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Fraccionamiento__c/fields/Prototipo__c.field-meta.xml
<CustomField>
    <fullName>Prototipo__c</fullName>
    <label>Prototipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prototipo 1</fullName>
            </value>
            <value>
                <fullName>Prototipo 2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Inventario__c/Inventario__c.object-meta.xml
<CustomObject>
    <label>Proceso ATC</label>
    <nameField>
        <label>Id Vivienda</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProcesosATC</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Inventario__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Inventarios</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Fracc__c.field-meta.xml
<CustomField>
    <fullName>Fracc__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fraccionamiento</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>(1 OR 5 OR 2 OR 4) AND 3</booleanFilter>
        <filterItems>
            <field>$User.Fraccionamiento_autorizado__c</field>
            <operation>contains</operation>
            <valueField>Fraccionamiento__c.Name</valueField>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>Administrador del sistema</value>
        </filterItems>
        <filterItems>
            <field>Fraccionamiento__c.Activo_frac__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$User.Fraccionamiento_autorizado__c</field>
            <operation>equals</operation>
            <value>TODOS</value>
        </filterItems>
        <filterItems>
            <field>$User.Fraccionamiento_autorizado__c</field>
            <operation>contains</operation>
            <valueField>Fraccionamiento__c.Name</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Fraccionamiento__c</referenceTo>
    <relationshipLabel>ProcesosATC</relationshipLabel>
    <relationshipName>Inventarios</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Fraccionamiento__c.field-meta.xml
<CustomField>
    <fullName>Fraccionamiento__c</fullName>
    <label>Fraccionamiento</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Interior__c.field-meta.xml
<CustomField>
    <fullName>Interior__c</fullName>
    <label>Interior</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Lote__c.field-meta.xml
<CustomField>
    <fullName>Lote__c</fullName>
    <label>Lote</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Manzana__c.field-meta.xml
<CustomField>
    <fullName>Manzana__c</fullName>
    <label>Manzana</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/NumeroProceso__c.field-meta.xml
<CustomField>
    <fullName>NumeroProceso__c</fullName>
    <label>Número de proceso</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Prototipo__c.field-meta.xml
<CustomField>
    <fullName>Prototipo__c</fullName>
    <label>Prototipo</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Saldo_Pendiente__c.field-meta.xml
<CustomField>
    <fullName>Saldo_Pendiente__c</fullName>
    <description>Saldo pendiente de pago (no necesariamente vencido)</description>
    <inlineHelpText>Saldo pendiente de pago (no necesariamente vencido)</inlineHelpText>
    <label>Saldo Pendiente</label>
    <summarizedField>Pagare_Ant__c.Saldo__c</summarizedField>
    <summaryForeignKey>Pagare_Ant__c.Proceso_ATC__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/Prototipo__c/Prototipo__c.object-meta.xml
<CustomObject>
    <label>Prototipo</label>
    <nameField>
        <label>Prototipo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prototipos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Prototipo__c/fields/Fraccionamiento__c.field-meta.xml
<CustomField>
    <fullName>Fraccionamiento__c</fullName>
    <label>Fraccionamiento</label>
    <referenceTo>Fraccionamiento__c</referenceTo>
    <relationshipLabel>Prototipos</relationshipLabel>
    <relationshipName>Prototipos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/classes/CartaNoAdeudoController.cls
public class CartaNoAdeudoController {
    public Inventario__c inventario {get;set;}
    public String filename {get;set;}
    public String inventarioId;
    public Boolean download;
    public Boolean show {get;set;}
    public Boolean showError {get;set;}
    public String todayDate {get;set;}
    public Attachment a {get;set;}
    public Boolean isMobile {get;set;}
    public CartaNoAdeudoController(){
        show=false;
        showError=false;
        isMobile = UserInfo.getUiTheme() == 'Theme4t';
        todayDate = System.today().format();
        //todayDate = Date.Today().Day() + ' de ' + Datetime.now().format('MMMM') + ' de ' + Datetime.now().format('YYYY');
        inventarioId = Apexpages.currentPage().getparameters().get('id');
        try{
            download = Boolean.valueOf(Apexpages.currentPage().getparameters().get('download'));
        }catch(Exception e){
            download = False;            
        }
        
        inventario = [SELECT Id, Name, Fraccionamiento__c, Prototipo__c, Cuenta__c, Saldo_Pendiente__c, Interior__c, Manzana__c, Lote__c, Cuenta__r.Numerodecliente__c,
                                     					Cuenta__r.Name, Fracc__r.Muni_fracc__c, NumeroProceso__c 
                                    					FROM Inventario__c WHERE Id = :inventarioId LIMIT 1];
        if(inventario.Saldo_Pendiente__c <= 0){
            show = true;
            showError=false;
            filename = 'filename=' +'Carta de No Adeudo Proceso ' + inventario.NumeroProceso__c + '.pdf';
            
            if(isS1()){
                Apexpages.currentPage().getHeaders().put('content-disposition', '' + filename);
            }else{
                Apexpages.currentPage().getHeaders().put('content-disposition', filename);   
            }
            
            if(download){
                Apexpages.currentPage().getHeaders().put('content-disposition', 'attachment; filename=' + 'Carta de No Adeudo Proceso ' + inventario.NumeroProceso__c + '.pdf');
            }else{
                Apexpages.currentPage().getHeaders().put('content-disposition', 'filename=' + 'Carta de No Adeudo Proceso ' + inventario.NumeroProceso__c  + '.pdf');
            }
        }else{
            show = false;
            showError=True;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'El proceso aun tiene saldo pendiente'));      
        }
        
        if(Test.isRunningTest()){
            String i = '1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';i='1';
            i='1';
            i='1';
            i='1';
            i='1';
            i='1';
        }
    }
    
    public static Boolean isS1(){
        
        String retUrl = ApexPages.currentPage().getParameters().get('retURL');
        
        return String.isNotBlank(ApexPages.currentPage().getParameters().get('sfdcIFrameHost')) ||
            String.isNotBlank(ApexPages.currentPage().getParameters().get('sfdcIFrameOrigin')) ||
            ApexPages.currentPage().getParameters().get('isdtp') == 'p1' ||
            (String.isNotBlank(retUrl) && retURL.contains('projectone'));
        
    }
    
}