unpackaged/main/default/objects/Account/fields/Otro_Telefono__c.field-meta.xml
<CustomField>
    <fullName>Otro_Telefono__c</fullName>
    <label>Otro Teléfono</label>
    <type>Phone</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/TelefonoCelular__c.field-meta.xml
<CustomField>
    <fullName>TelefonoCelular__c</fullName>
    <label>Teléfono Celular</label>
    <type>Phone</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo de Cuenta</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospecto</fullName>
            </value>
            <value>
                <fullName>Afluente</fullName>
            </value>
            <value>
                <fullName>Cliente</fullName>
            </value>
            <value>
                <fullName>Compañía Javer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Dictaminacion__c/Dictaminacion__c.object-meta.xml
<CustomObject>
    <label>Dictaminación</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Folio</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dictaminación</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Dictaminacion__c/fields/Fraccionamiento__c.field-meta.xml
<CustomField>
    <fullName>Fraccionamiento__c</fullName>
    <formula>Oportunidad__r.Fraccionamiento__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Fraccionamiento</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Dictaminacion__c/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Proceso de Venta</description>
    <label>Proceso de Venta</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Dictaminacion__c/fields/Otro_telefono__c.field-meta.xml
<CustomField>
    <fullName>Otro_telefono__c</fullName>
    <formula>Account__r.Otro_Telefono__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Otro teléfono</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Dictaminacion__c/fields/TelefonoCelular__c.field-meta.xml
<CustomField>
    <fullName>TelefonoCelular__c</fullName>
    <formula>Account__r.TelefonoCelular__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Teléfono Celular</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Direcciones__c/Direcciones__c.object-meta.xml
<CustomObject>
    <label>Dirección</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Folio</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Direcciones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Direcciones__c/fields/Dictaminacion__c.field-meta.xml
<CustomField>
    <fullName>Dictaminacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dictaminación</label>
    <referenceTo>Dictaminacion__c</referenceTo>
    <relationshipLabel>Direcciones</relationshipLabel>
    <relationshipName>Direcciones</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Direcciones__c/fields/Direccion__c.field-meta.xml
<CustomField>
    <fullName>Direccion__c</fullName>
    <formula>Calle__c &amp; &quot; #&quot; &amp; Numero_Exterior__c &amp; IF(Numero_Interior__c=&quot;&quot;,&quot;&quot;, &quot; - &quot;&amp; Numero_Interior__c)  &amp; &quot;, &quot; &amp; 
Colonia__r.Name &amp; &quot;, &quot; &amp;  Municipio__r.Name &amp; &quot;, &quot; &amp; 
Estado__r.Name &amp; &quot;, &quot; &amp; Codigo_Postal__r.Name &amp; &quot;, &quot; &amp; Pais__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Dirección</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Fraccionamiento__c/Fraccionamiento__c.object-meta.xml
<CustomObject>
    <label>Fraccionamiento</label>
    <nameField>
        <label>Nombre de Fraccionamiento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fraccionamientos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Fraccionamiento__c/fields/Ubicacion_Compania__c.field-meta.xml
<CustomField>
    <fullName>Ubicacion_Compania__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ubicación Compañia</label>
    <referenceTo>Ubicacion__c</referenceTo>
    <relationshipLabel>Fraccionamientos</relationshipLabel>
    <relationshipName>Fraccionamientos</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Dictaminacion__c.field-meta.xml
<CustomField>
    <fullName>Dictaminacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dictaminación</label>
    <referenceTo>Dictaminacion__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Fraccionamiento__c.field-meta.xml
<CustomField>
    <fullName>Fraccionamiento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fraccionamiento</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$User.Fraccionamiento_autorizado__c</field>
            <operation>contains</operation>
            <valueField>Fraccionamiento__c.Name</valueField>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>Administrador del sistema</value>
        </filterItems>
        <filterItems>
            <field>Fraccionamiento__c.Activo_frac__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$User.Fraccionamiento_autorizado__c</field>
            <operation>equals</operation>
            <value>TODOS</value>
        </filterItems>
        <filterItems>
            <field>$User.FraccionamientoAutorizados__c</field>
            <operation>contains</operation>
            <valueField>Fraccionamiento__c.Name</valueField>
        </filterItems>
        <filterItems>
            <field>Fraccionamiento__c.Name</field>
            <operation>contains</operation>
            <valueField>Fraccionamiento__c.Name</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Fraccionamiento__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Plan_de_Venta__c.field-meta.xml
<CustomField>
    <fullName>Plan_de_Venta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plan de Venta</label>
    <referenceTo>Plan_de_Venta__c</referenceTo>
    <relationshipLabel>Procesos de Ventas</relationshipLabel>
    <relationshipName>Procesos_de_Ventas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/TelefonoCelular__c.field-meta.xml
<CustomField>
    <fullName>TelefonoCelular__c</fullName>
    <formula>Account.TelefonoCelular__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Teléfono Celular</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Pagare_Preventa__c/Pagare_Preventa__c.object-meta.xml
<CustomObject>
    <label>Pagaré Preventa</label>
    <nameField>
        <displayFormat>{YY}{MM}-{00000}</displayFormat>
        <label>Número de Pagaré Preventa</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pagarés Preventa</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Pagare_Preventa__c/fields/Plan_de_Venta__c.field-meta.xml
<CustomField>
    <fullName>Plan_de_Venta__c</fullName>
    <label>Plan de Venta</label>
    <referenceTo>Plan_de_Venta__c</referenceTo>
    <relationshipLabel>Pagarés Preventa</relationshipLabel>
    <relationshipName>Pagares_Preventa</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/Plan_de_Venta__c.object-meta.xml
<CustomObject>
    <label>Plan de Venta</label>
    <nameField>
        <displayFormat>Plan de Venta-{000000}</displayFormat>
        <label>Plan de Venta</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plan de Venta</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Aval__c.field-meta.xml
<CustomField>
    <fullName>Aval__c</fullName>
    <label>Aval</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Diferencia_a_Pagar__c.field-meta.xml
<CustomField>
    <fullName>Diferencia_a_Pagar__c</fullName>
    <formula>Enganche_a_Pagar__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Diferencia a Pagar</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Domicilio_Aval__c.field-meta.xml
<CustomField>
    <fullName>Domicilio_Aval__c</fullName>
    <label>Domicilio Aval</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Enganche_a_Pagar__c.field-meta.xml
<CustomField>
    <fullName>Enganche_a_Pagar__c</fullName>
    <formula>IF( Valor_Operacion_Plain_Field__c -
	   (Credito_Neto_1_Plain_Field__c +  
		   Credito_Neto_2_Plain_Field__c +  
		   Credito_Neto_3_Plain_Field__c +   
		   Subsidio_Plain_Field__c  + 
		   Anticipo_Plain_Field__c) &lt;= 0,
			0.00,
			Valor_Operacion_Plain_Field__c -
	   (Credito_Neto_1_Plain_Field__c +  
		   Credito_Neto_2_Plain_Field__c +  
		   Credito_Neto_3_Plain_Field__c +   
		   Subsidio_Plain_Field__c  + 
		   Anticipo_Plain_Field__c)
			)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Enganche a Pagar</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proceso de Venta</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Plan de Venta</relationshipLabel>
    <relationshipName>Plan_de_Venta</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Plan_de_Venta__c.field-meta.xml
<CustomField>
    <fullName>Plan_de_Venta__c</fullName>
    <formula>&quot;Plan de Venta&quot; &amp; &quot; &quot;&amp;  Oportunidad__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Plan de Venta</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Telefono_Casa_Aval__c.field-meta.xml
<CustomField>
    <fullName>Telefono_Casa_Aval__c</fullName>
    <label>Teléfono Casa Aval</label>
    <type>Phone</type>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Telefono_Celular_Aval__c.field-meta.xml
<CustomField>
    <fullName>Telefono_Celular_Aval__c</fullName>
    <label>Teléfono Celular Aval</label>
    <type>Phone</type>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Telefono_Otro_Aval__c.field-meta.xml
<CustomField>
    <fullName>Telefono_Otro_Aval__c</fullName>
    <label>Teléfono Otro Aval</label>
    <type>Phone</type>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Ubicacion_Compania__c.field-meta.xml
<CustomField>
    <fullName>Ubicacion_Compania__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ubicación Compañia</label>
    <referenceTo>Ubicacion__c</referenceTo>
    <relationshipLabel>Plan de Venta</relationshipLabel>
    <relationshipName>Plan_de_Venta</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Valor_de_Operacion__c.field-meta.xml
<CustomField>
    <fullName>Valor_de_Operacion__c</fullName>
    <formula>Oportunidad__r.Amount -  Precio_Total_Vivenda__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/classes/CONTROL_FormatoPagarePreventaPdf.cls
public with sharing class CONTROL_FormatoPagarePreventaPdf {
    
    public Id RecordId {get;set;}
    public string compania {get; set;}
    public double cantidad {get; set;}
    public string cantidadl {get; set;}
    public string domicilio {get; set;}
    public string telefono {get; set;}
    public string day {get; set;}
    public string month {get; set;}
    public string year {get; set;}
    public string suscriptor {get; set;}
    public string domicilioS {get; set;}
    public string telefonoS1 {get; set;}
    public string telefonoS2 {get; set;}
    public string telefonoS3 {get; set;}
    public string aval {get; set;}
    public string domicilioA {get; set;}
    public string telefonoA1 {get; set;}
    public string telefonoA2 {get; set;}
    public string telefonoA3 {get; set;}
    public string usuario {get; set;}
    public list<CONTROL_FormatoPagarePreventaPdfAux> aux {get; set;}
    public double total {get; set;}
    
    public CONTROL_FormatoPagarePreventaPdf(ApexPages.StandardController controller) {
        RecordId  = ApexPages.currentPage().getParameters().get('id');
        Plan_de_Venta__c pv = [Select Id, Diferencia_a_Pagar__c, Valor_de_Operacion__c, Aval__c, Domicilio_Aval__c, Ubicacion_Compania__c, 
            Oportunidad__r.Account.Name, Oportunidad__r.Account.BillingAddress, Oportunidad__r.Account.Phone, Oportunidad__r.Account.TelefonoCelular__c, 
            Oportunidad__r.Account.Otro_Telefono__c, Telefono_Celular_Aval__c, Telefono_Casa_Aval__c, Telefono_Otro_Aval__c,Oportunidad__r.Fraccionamiento__c,
            Enganche_a_Pagar__c, Oportunidad__r.Name
            FROM Plan_de_Venta__c
            WHERE Id = :RecordId Limit 1];
        Dictaminacion__c[] dc = [SELECT ID FROM Dictaminacion__c WHERE Oportunidad__c = :pv.Oportunidad__c LIMIT 1];
        Direcciones__c[] dirs = new List<Direcciones__c>();
        if (dc.size()>0){
            dirs = [SELECT Direccion__c FROM Direcciones__c WHERE Dictaminacion__c = :dc[0].Id AND Tipo__c = 'Dirección Principal'];
        }
        // Ubicacion__c[] u = [Select Id, Nombre_de_la_Compania__c, Direccion_Fisica__c, Telefono__c From Ubicacion__c Where Id = :pv.Ubicacion_Compania__c Limit 1];
        Fraccionamiento__c[] fr = [SELECT id, Compania_Asociada__r.Name,Compania_Asociada__r.BillingStreet,Compania_Asociada__r.Phone,
                Compania_Asociada__r.BillingState, Compania_Asociada__r.BillingCity
                FROM Fraccionamiento__c where ID = :pv.Oportunidad__r.Fraccionamiento__c];
        if(fr.size() == 0){
            compania = ' N/A';
            domicilio = ' N/A';
            telefono = ' N/A';
        }
        else{
            compania = ' ' + fr[0].Compania_Asociada__r.Name; //u[0].Nombre_de_la_Compania__c;
            domicilio = ' ' + fr[0].Compania_Asociada__r.BillingStreet+', '+fr[0].Compania_Asociada__r.BillingState+', '+fr[0].Compania_Asociada__r.BillingCity;
            telefono = ' Tel. ' + fr[0].Compania_Asociada__r.Phone;
        }
        cantidad = pv.Enganche_a_Pagar__c; //pv.Valor_de_Operacion__c;
        cantidadL = Numero_a_Letra.convertir(pv.Enganche_a_Pagar__c);
        fecha();
        suscriptor = pv.Oportunidad__r.Account.Name;
        if (dirs.size()>0){
            domicilioS = dirs[0].Direccion__c; // String.ValueOf(pv.Oportunidad__r.Account.BillingStreet);
        }
        
        telefonoS1 = String.ValueOf(pv.Oportunidad__r.Account.Phone);
        telefonoS2 = String.ValueOf(pv.Oportunidad__r.Account.TelefonoCelular__c);
        telefonoS3 = String.ValueOf(pv.Oportunidad__r.Account.Otro_Telefono__c);
        aval = pv.Aval__c;
        domicilioA = pv.Domicilio_Aval__c;
        telefonoA1 = String.ValueOf(pv.Telefono_Celular_Aval__c);
        telefonoA2 = String.ValueOf(pv.Telefono_Casa_Aval__c);
        telefonoA3 = String.ValueOf(pv.Telefono_Otro_Aval__c);
        usuario = UserInfo.getName();

        String codigoPagare = pv.Oportunidad__r.Name;
        String codigoPagareDV = CLASS_Oportunidad.CalculaDigitoVerificador(codigoPagare);

        List<Pagare_Preventa__c> pps = [Select Id, Name, Plan_de_Venta__c, Importe__c, Fecha_de_Vencimiento__c From Pagare_Preventa__c Where Plan_de_Venta__c = :RecordId];
        aux = new list<CONTROL_FormatoPagarePreventaPdfAux>();
        For(Pagare_Preventa__c pp : pps){
            aux.add(new CONTROL_FormatoPagarePreventaPdfAux(codigoPagareDV, (pp.Importe__c), (pp.Fecha_de_Vencimiento__c.format())));
        }
        total = pv.Diferencia_a_Pagar__c;
    }

    public void fecha(){
        Date d =date.today();
        day = ' ' + String.valueOf(d.day());
        Integer monthI = Integer.valueOf(d.month());
        switch on monthI {
            when 1 {
                month = ' Enero';
            }	
            when 2 {
                month = ' Febrero';
            }
            when 3 {
                month = ' Marzo';
            }
            when 4 {
                month = ' Abril';
            }
            when 5 {
                month = ' Mayo';
            }
            when 6 {
                month = ' Junio';
            }
            when 7 {
                month = ' Julio';
            }
            when 8 {
                month = ' Agosto';
            }
            when 9 {
                month = ' Septiembre';
            }
            when 10 {
                month = ' Octubre';
            }
            when 11 {
                month = ' Noviembre';
            }
            when else {
                month = ' Diciembre';
            }
        }
        year = ' ' + String.valueOf(d.year());
    }
}