unpackaged/main/default/objects/Account/fields/Vivienda_Mas_Reciente__c.field-meta.xml
<CustomField>
    <fullName>Vivienda_Mas_Reciente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vivienda Mas Reciente</label>
    <referenceTo>Inventario__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/Inventario__c.object-meta.xml
<CustomObject>
    <label>Proceso ATC</label>
    <nameField>
        <label>Id Vivienda</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProcesosATC</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Inventario__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Inventarios</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/BatchViviendaMasReciente.cls
/**
* ────────────────────────────────────────────────────────────────────────────────────────────────────┐
* Asigna un valor al campo ViviendaMasReciente__c de las Cuentas
* ─────────────────────────────────────────────────────────────────────────────────────────────────────
* @author       Miguel Martínez
* @version      1.0
* @created      15/10/2020
* ────────────────────────────────────────────────────────────────────────────────────────────────────┘
**/
global class BatchViviendaMasReciente implements Database.Batchable<sObject>, Database.Stateful {

    global Database.QueryLocator start(Database.BatchableContext BC) {

        String query = 'SELECT Id, Cuenta__c FROM Inventario__c WHERE Cuenta__c != null';

        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<Inventario__c> scope) {  
        Map<Id, Id> cuentasInventarios = new Map<Id, Id>();
        for(Inventario__c inventario : scope){ cuentasInventarios.put(inventario.Cuenta__c, inventario.Id);}

        List<Account> cuentas = [SELECT Id, Vivienda_Mas_Reciente__c FROM Account WHERE Id IN: cuentasInventarios.keySet()];
        for(Account cuenta : cuentas){ cuenta.Vivienda_Mas_Reciente__c = cuentasInventarios.get(cuenta.Id); }
        update cuentas;

    }   

    global void finish(Database.BatchableContext BC) {

    }
}