unpackaged/main/default/objects/Product2/fields/Numero_Filtro__c.field-meta.xml
<CustomField>
    <fullName>Numero_Filtro__c</fullName>
    <description>Se crea este campo para poder filtrar en diferentes campos de búsqueda de otros objetos relacionados a producto</description>
    <label>Número Filtro</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Precio_Venta__c.field-meta.xml
<CustomField>
    <fullName>Precio_Venta__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Precio Venta al Cliente</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Proveedor__c.field-meta.xml
<CustomField>
    <fullName>Proveedor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Proveedor</label>
    <referenceTo>Proveedor__c</referenceTo>
    <relationshipLabel>Productos</relationshipLabel>
    <relationshipName>Productos</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Product2/recordTypes/Productos_Genericos.recordType-meta.xml
<RecordType>
    <fullName>Productos_Genericos</fullName>
    <active>true</active>
    <label>Productos Genéricos</label>
</RecordType>

unpackaged/main/default/objects/Proveedor__c/Proveedor__c.object-meta.xml
<CustomObject>
    <label>Proveedor</label>
    <nameField>
        <label>Proveedor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proveedores</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Proveedor__c/fields/Contacto__c.field-meta.xml
<CustomField>
    <fullName>Contacto__c</fullName>
    <label>Contacto</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Proveedor__c/fields/Correo__c.field-meta.xml
<CustomField>
    <fullName>Correo__c</fullName>
    <label>Correo</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Proveedor__c/fields/Nombre_Comercial__c.field-meta.xml
<CustomField>
    <fullName>Nombre_Comercial__c</fullName>
    <label>Nombre Comercial</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Proveedor__c/fields/Rfc__c.field-meta.xml
<CustomField>
    <fullName>Rfc__c</fullName>
    <label>RFC</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/CLASS_ProveedoresRelacion_Test.cls
@isTest
public class CLASS_ProveedoresRelacion_Test {
    static TestMethod void testMethod1() {
        Id rtd =  Schema.SObjectType.Product2.getRecordTypeInfosBydevelopername().get('Productos_Genericos').getRecordTypeId();
        Product2 prod1 = new Product2();
        prod1.name = 'test11';
        prod1.Numero_Filtro__c = 2;
        prod1.IsActive = true;
        prod1.Precio_Venta__c = 10.0;
        prod1.Description = 'test';
        prod1.RecordTypeId = rtd;
        insert prod1;
        Proveedor__c Proveedor = new Proveedor__c();
        Proveedor.name = 'Proveedor';
        Proveedor.Rfc__c = 'Rfc';
        Proveedor.Contacto__c = 'Contacto';
        Proveedor.Correo__c = 'test@abc.com';
        Proveedor.Nombre_Comercial__c = 'Nombre_Comercial';
        Test.startTest();
        CLASS_ProveedoresRelacion.creaProveedor(Proveedor, prod1.Id);
        CLASS_ProveedoresRelacion.getRelatedList(prod1.Id);
        Test.stopTest();
    }
}