unpackaged/main/default/objects/Cobranza_Comercial__c/Cobranza_Comercial__c.object-meta.xml
<CustomObject>
    <label>Cobranza Comercial</label>
    <nameField>
        <label>Cobranza Comercial</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cobranza Comercial</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Cobranza_Comercial__c/fields/Proceso_Venta__c.field-meta.xml
<CustomField>
    <fullName>Proceso_Venta__c</fullName>
    <label>Proceso de Venta</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Cobranza Comercial</relationshipLabel>
    <relationshipName>Cobranza_Comercial</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Cobranza_Comercial__c.field-meta.xml
<CustomField>
    <fullName>Cobranza_Comercial__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cobranza Comercial</label>
    <referenceTo>Cobranza_Comercial__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/TRIGGER_Cobranza_Comercial_Test.cls
@isTest
public class TRIGGER_Cobranza_Comercial_Test {
    static TestMethod void testMethod1() {
         Opportunity opp = new Opportunity(Name = 'Test Opportunity');
        opp.StageName = 'Validación';
        opp.CloseDate = Date.today().adddays(10);
        insert opp;
        Cobranza_Comercial__c cc = new Cobranza_Comercial__c();
        cc.Proceso_Venta__c = opp.Id;
        insert cc;
		delete cc;
    }
}