unpackaged/main/default/objects/Cobranza_Comercial__c/Cobranza_Comercial__c.object-meta.xml
<CustomObject>
    <label>Cobranza Comercial</label>
    <nameField>
        <label>Cobranza Comercial</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cobranza Comercial</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Cobranza_Comercial__c/fields/Fecha_Inicio_de_Financiamiento__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Inicio_de_Financiamiento__c</fullName>
    <description>Fecha a partir de la cual el cliente puede empezar a pagar</description>
    <label>Fecha Inicio de Financiamiento</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Cobranza_Comercial__c/fields/Frecuencia__c.field-meta.xml
<CustomField>
    <fullName>Frecuencia__c</fullName>
    <description>Este dato indica cada cuando el cliente tendrá que liquidar los pagarés postventa</description>
    <label>Frecuencia</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Semanal</fullName>
            </value>
            <value>
                <fullName>Quincenal</fullName>
            </value>
            <value>
                <fullName>Mensual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Cobranza_Comercial__c/fields/Plazo__c.field-meta.xml
<CustomField>
    <fullName>Plazo__c</fullName>
    <label>Plazo</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Cobranza_Comercial__c/fields/Suma_Total_de_Pagares__c.field-meta.xml
<CustomField>
    <fullName>Suma_Total_de_Pagares__c</fullName>
    <label>Suma Total de Pagarés</label>
    <summarizedField>Documento__c.Importe__c</summarizedField>
    <summaryFilterItems>
        <field>Documento__c.Tipo__c</field>
        <operation>equals</operation>
        <value>PAGARÉ ENGANCHE, PAGARÉ FINANCIERA, PAGARÉ FONDO DE GARANTÍA, PAGARÉ POSTVENTA, PAGARÉ POSTVENTA REESTRUCTURA FINANCIERA, PAGARÉ SEGURO FINANCIERA, PAGARÉ SUBSIDIO</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Documento__c.RecordTypeId</field>
        <operation>equals</operation>
        <value>Factura</value>
    </summaryFilterItems>
    <summaryForeignKey>Documento__c.Cobranza_Comercial__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/classes/PlanPagosCobranzaComercial2.cls
public class PlanPagosCobranzaComercial2 {
    public Boolean showModal { get; set; }
    public String recordId { get; set; }
    public Integer plazo { get; set; }
    public String frecuencia { get; set; }
    public Date inicio { get; set; }
    public Double diferenciaPagar { get; set; }
    
    public Cobranza_Comercial__c cobranzaComercial {get; set;}

    public PlanPagosCobranzaComercial2() {
        showModal = false;
    }

    public PlanPagosCobranzaComercial2(ApexPages.StandardController stdController) {

        Id idCobranzaComercial = stdController.getId();
        recordId = stdController.getId();
        cobranzaComercial = [SELECT Id, Plazo__c, Frecuencia__c, Fecha_Inicio_de_Financiamiento__c, Suma_Total_de_Pagares__c FROM Cobranza_Comercial__c WHERE Id =: idCobranzaComercial];
        plazo = Integer.ValueOf(cobranzaComercial.Plazo__c);
        frecuencia = cobranzaComercial.Frecuencia__c;
        inicio = cobranzaComercial.Fecha_Inicio_de_Financiamiento__c;
        diferenciaPagar = cobranzaComercial.Suma_Total_de_Pagares__c;
    }

    
    public PageReference executeApexClass() {
        // Id idCobranzaComercial = stdController.getId();
        system.debug('**** Este es el cobranzaComercialID: '+recordId);
        // Apex code to be executed

        // Obtener los datos de Cobranza Comercial

        system.debug('*** Ejecutando crear pagarés');
        
        CLASS_PagareFinanciera.creaPagaresFinanciera(recordId, plazo, frecuencia, inicio, diferenciaPagar, true, true);

        //showModal = false;
        PageReference pg = new PageReference('/' + recordId);
        pg.setRedirect(true);
        return pg;
    }

    //Metodo para cancelar la creacion de plan de pagos
    public PageReference cancelar(){

        PageReference pg = new PageReference('/' + cobranzaComercial.Id);
        pg.setRedirect(true);
        return pg;
    }
}