unpackaged/main/default/objects/Cobranza_Comercial__c/Cobranza_Comercial__c.object-meta.xml
<CustomObject>
    <label>Cobranza Comercial</label>
    <nameField>
        <label>Cobranza Comercial</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cobranza Comercial</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Cobranza_Comercial__c/fields/Aval__c.field-meta.xml
<CustomField>
    <fullName>Aval__c</fullName>
    <label>Aval</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Cobranza_Comercial__c/fields/Compania_Javer__c.field-meta.xml
<CustomField>
    <fullName>Compania_Javer__c</fullName>
    <label>Compañía Javer</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Cobranza_Comercial__c/fields/Diferencia_a_Pagar__c.field-meta.xml
<CustomField>
    <fullName>Diferencia_a_Pagar__c</fullName>
    <formula>Valor_Operacion__c -  Sumatoria_Pagares_Postventa__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Diferencia a Pagar</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Cobranza_Comercial__c/fields/Domicilio_Aval__c.field-meta.xml
<CustomField>
    <fullName>Domicilio_Aval__c</fullName>
    <label>Domicilio Aval</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Cobranza_Comercial__c/fields/Nombre_del_Cliente__c.field-meta.xml
<CustomField>
    <fullName>Nombre_del_Cliente__c</fullName>
    <formula>Cliente__r.Nombre__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nombre del Cliente</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Cobranza_Comercial__c/fields/Proceso_Venta__c.field-meta.xml
<CustomField>
    <fullName>Proceso_Venta__c</fullName>
    <label>Proceso de Venta</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Cobranza Comercial</relationshipLabel>
    <relationshipName>Cobranza_Comercial</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Cobranza_Comercial__c/fields/Valor_Operacion__c.field-meta.xml
<CustomField>
    <fullName>Valor_Operacion__c</fullName>
    <formula>Proceso_Venta__r.Valor_Operacion_Formula_PlanVenta__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Valor Escritura</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Documento__c/Documento__c.object-meta.xml
<CustomObject>
    <label>Documento</label>
    <nameField>
        <displayFormat>3-{0000000000}</displayFormat>
        <label>Documento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documentos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Documento__c/fields/Cobranza_Comercial__c.field-meta.xml
<CustomField>
    <fullName>Cobranza_Comercial__c</fullName>
    <label>Cobranza Comercial.</label>
    <referenceTo>Cobranza_Comercial__c</referenceTo>
    <relationshipLabel>Documentos</relationshipLabel>
    <relationshipName>Documentos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Documento__c/fields/Documento__c.field-meta.xml
<CustomField>
    <fullName>Documento__c</fullName>
    <formula>HYPERLINK(&quot;/lightning/r/Documento__c/&quot;&amp; Id &amp;&quot;/view&quot;, Name &amp; &quot; - &quot; &amp; TEXT(Tipo__c) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Documento</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Documento__c/fields/Fecha_Vencimiento__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Vencimiento__c</fullName>
    <label>Fecha Vencimiento</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Documento__c/fields/Importe__c.field-meta.xml
<CustomField>
    <fullName>Importe__c</fullName>
    <label>Importe</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Cobranza_Comercial__c.field-meta.xml
<CustomField>
    <fullName>Cobranza_Comercial__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cobranza Comercial</label>
    <referenceTo>Cobranza_Comercial__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/TelefonoCelular__c.field-meta.xml
<CustomField>
    <fullName>TelefonoCelular__c</fullName>
    <formula>Account.TelefonoCelular__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Teléfono Celular</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Valor_Operacion__c.field-meta.xml
<CustomField>
    <fullName>Valor_Operacion__c</fullName>
    <label>Suma de Productos</label>
    <summarizedField>OpportunityLineItem.TotalPrice</summarizedField>
    <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/classes/CONTROL_CC_FormatoPagarePdf.cls
public with sharing class CONTROL_CC_FormatoPagarePdf {
    
    public Id RecordId {get;set;}
    public string compania {get; set;}
    public double cantidad {get; set;}
    public string cantidadl {get; set;}
    public string domicilio {get; set;}
    public string telefono {get; set;}
    public string day {get; set;}
    public string month {get; set;}
    public string year {get; set;}
    public string suscriptor {get; set;}
    public string domicilioS {get; set;}
    public string telefonoS1 {get; set;}
    public string telefonoS2 {get; set;}
    public string telefonoS3 {get; set;}
    public string aval {get; set;}
    public string domicilioA {get; set;}
    public string telefonoA1 {get; set;}
    public string telefonoA2 {get; set;}
    public string telefonoA3 {get; set;}
    public string usuario {get; set;}
    public list<CONTROL_FormatoPagarePreventaPdfAux> aux {get; set;}
    public double total {get; set;}
    
    public CONTROL_CC_FormatoPagarePdf(ApexPages.StandardController controller) {
        RecordId  = ApexPages.currentPage().getParameters().get('id');
        Cobranza_Comercial__c cc = [Select Id, name, Valor_Operacion__c, Nombre_del_Cliente__c, Proceso_Venta__c, Compania_Javer__c From cobranza_comercial__c  Where Id = :RecordId Limit 1];
        
        cantidad = cc.Valor_Operacion__c;
        cantidadL = Numero_a_Letra.convertir(cc.Valor_Operacion__c);
        fecha();
        suscriptor = String.ValueOf(cc.Nombre_del_Cliente__c);
     /*   domicilioS = String.ValueOf(cc.Proceso_Venta__r.AccountId.BillingAddress);
        telefonoS1 = String.ValueOf(cc.Proceso_Venta__r.AccountId.Phone);
        telefonoS2 = String.ValueOf(cc.Proceso_Venta__r.AccountId.TelefonoCelular__c);
        telefonoS3 = String.ValueOf(cc.Proceso_Venta__r.AccountId.Otro_Telefono__c);
        aval = cc.Aval__c;
        domicilioA = cc.Domicilio_Aval__c;
        telefonoA1 = String.ValueOf(cc.Telefono_Celular_Aval__c);
        telefonoA2 = String.ValueOf(cc.Telefono_Casa_Aval__c);
        telefonoA3 = String.ValueOf(cc.Telefono_Otro_Aval__c);
        usuario = UserInfo.getName(); */

        List<Documento__c> dpp = [Select Id, Name, Cobranza_Comercial__c, Importe__c, Fecha_Vencimiento__c From Documento__c Where cobranza_comercial__c = :RecordId];
        aux = new list<CONTROL_FormatoPagarePreventaPdfAux>();
        For(Documento__c doc : dpp){
            aux.add(new CONTROL_FormatoPagarePreventaPdfAux(doc.Name, doc.Importe__c, (doc.Fecha_Vencimiento__c.format())));
        }
        total = cc.Diferencia_a_Pagar__c;

    }

    public void fecha(){
        Date d =date.today();
        day = ' ' + String.valueOf(d.day());
        Integer monthI = Integer.valueOf(d.month());
        switch on monthI {
            when 1 {
                month = ' Enero';
            }  
            when 2 {
                month = ' Febrero';
            }
            when 3 {
                month = ' Marzo';
            }
            when 4 {
                month = ' Abril';
            }
            when 5 {
                month = ' Mayo';
            }
            when 6 {
                month = ' Junio';
            }
            when 7 {
                month = ' Julio';
            }
            when 8 {
                month = ' Agosto';
            }
            when 9 {
                month = ' Septiembre';
            }
            when 10 {
                month = ' Octubre';
            }
            when 11 {
                month = ' Noviembre';
            }
            when else {
                month = ' Diciembre';
            }
        }
        year = ' ' + String.valueOf(d.year());
    }
}