unpackaged/main/default/objects/Cobranza_Comercial__c/Cobranza_Comercial__c.object-meta.xml
<CustomObject>
    <label>Cobranza Comercial</label>
    <nameField>
        <label>Cobranza Comercial</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cobranza Comercial</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Documento__c/Documento__c.object-meta.xml
<CustomObject>
    <label>Documento</label>
    <nameField>
        <displayFormat>3-{0000000000}</displayFormat>
        <label>Documento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documentos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Documento__c/fields/Cobranza_Comercial__c.field-meta.xml
<CustomField>
    <fullName>Cobranza_Comercial__c</fullName>
    <label>Cobranza Comercial.</label>
    <referenceTo>Cobranza_Comercial__c</referenceTo>
    <relationshipLabel>Documentos</relationshipLabel>
    <relationshipName>Documentos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Documento__c/fields/Documento__c.field-meta.xml
<CustomField>
    <fullName>Documento__c</fullName>
    <formula>HYPERLINK(&quot;/lightning/r/Documento__c/&quot;&amp; Id &amp;&quot;/view&quot;, Name &amp; &quot; - &quot; &amp; TEXT(Tipo__c) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Documento</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Documento__c/fields/Estatus__c.field-meta.xml
<CustomField>
    <fullName>Estatus__c</fullName>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ABIERTO</fullName>
            </value>
            <value>
                <fullName>CANCELADO</fullName>
            </value>
            <value>
                <fullName>CERRADO</fullName>
            </value>
            <value>
                <fullName>EN_TRANSITO</fullName>
                <label>EN TRÁNSITO</label>
            </value>
            <value>
                <fullName>FALLO_EN_AR</fullName>
                <label>FALLO EN AR</label>
            </value>
            <value>
                <fullName>PARCIAL</fullName>
            </value>
            <value>
                <fullName>RECHAZADO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Documento__c/fields/Fecha_Vencimiento__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Vencimiento__c</fullName>
    <label>Fecha Vencimiento</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Documento__c/fields/Importe__c.field-meta.xml
<CustomField>
    <fullName>Importe__c</fullName>
    <label>Importe</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Documento__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>NC_AHORRO_VOLUNTARIO</fullName>
                <label>NC AHORRO VOLUNTARIO</label>
            </value>
            <value>
                <fullName>NC_BONIFICACION</fullName>
                <label>NC BONIFICACIÓN</label>
            </value>
            <value>
                <fullName>NC_CANCELACION_ESCRITURA</fullName>
                <label>NC CANCELACIÓN ESCRITURA</label>
            </value>
            <value>
                <fullName>NC_CANCELACION_PG_N</fullName>
                <label>NC CANCELACIÓN PG N</label>
            </value>
            <value>
                <fullName>NC_DEVOLUCION_NO_APLICA</fullName>
                <label>NC DEVOLUCIÓN NO APLICA</label>
            </value>
            <value>
                <fullName>NC_GASTO_AVALUO</fullName>
                <label>NC GASTO AVALÚO</label>
            </value>
            <value>
                <fullName>NC_GASTO_CREDITO_DIRECTO</fullName>
                <label>NC GASTO CRÉDITO DIRECTO</label>
            </value>
            <value>
                <fullName>NC_GASTOS_NOTARIALES</fullName>
                <label>NC GASTOS NOTARIALES</label>
            </value>
            <value>
                <fullName>NC_GASTOS_OPERATIVOS</fullName>
                <label>NC GASTOS OPERATIVOS</label>
            </value>
            <value>
                <fullName>NC_RECUPERACION_CARTERA</fullName>
                <label>NC RECUPERACIÓN CARTERA</label>
            </value>
            <value>
                <fullName>NC_REEMBOLSO_AHORRO_VOLUNTARIO</fullName>
                <label>NC REEMBOLSO AHORRO VOLUNTARIO</label>
            </value>
            <value>
                <fullName>NC_REEMBOLSO_CANCELACION</fullName>
                <label>NC REEMBOLSO CANCELACIÓN</label>
            </value>
            <value>
                <fullName>NC_REEMBOLSO_POR_ESCRITURA</fullName>
                <label>NC REEMBOLSO POR ESCRITURA</label>
            </value>
            <value>
                <fullName>NC_REESTRUCTURA_FINANCIERA</fullName>
                <label>NC REESTRUCTURA FINANCIERA</label>
            </value>
            <value>
                <fullName>NC_REESTRUCTURA_POST_VENTA</fullName>
                <label>NC REESTRUCTURA POST VENTA</label>
            </value>
            <value>
                <fullName>PAGARE_AHORRO_VOLUNTARIO</fullName>
                <label>PAGARÉ AHORRO VOLUNTARIO</label>
            </value>
            <value>
                <fullName>PAGARE_CANCELACION_DE_NC_GN</fullName>
                <label>PAGARÉ CANCELACIÓN DE NC GN</label>
            </value>
            <value>
                <fullName>PAGARE_DEVOLUCION_NO_APLICA</fullName>
                <label>PAGARÉ DEVOLUCIÓN NO APLICA</label>
            </value>
            <value>
                <fullName>PAGARE_ENGANCHE</fullName>
                <label>PAGARÉ ENGANCHE</label>
            </value>
            <value>
                <fullName>PAGARE_FINANCIERA</fullName>
                <label>PAGARÉ FINANCIERA</label>
            </value>
            <value>
                <fullName>PAGARE_FONDO_DE_GARANTIA</fullName>
                <label>PAGARÉ FONDO DE GARANTÍA</label>
            </value>
            <value>
                <fullName>PAGARE_GASTO_AVALUO</fullName>
                <label>PAGARÉ GASTO AVALÚO</label>
            </value>
            <value>
                <fullName>PAGARE_GASTO_CREDITO_DIRECTO</fullName>
                <label>PAGARÉ GASTO CRÉDITO DIRECTO</label>
            </value>
            <value>
                <fullName>PAGARE_GASTOS_NOTARIALES</fullName>
                <label>PAGARÉ GASTOS NOTARIALES</label>
            </value>
            <value>
                <fullName>PAGARE_GASTOS_OPERATIVOS</fullName>
                <label>PAGARÉ GASTOS OPERATIVOS</label>
            </value>
            <value>
                <fullName>PAGARE_POSTVENTA</fullName>
                <label>PAGARÉ POSTVENTA</label>
            </value>
            <value>
                <fullName>PAGARE_POSTVENTA_REESTRUCTURA_FINANCIERA</fullName>
                <label>PAGARÉ POSTVENTA REESTRUCTURA FINANCIERA</label>
            </value>
            <value>
                <fullName>PAGARE_PREVENTA</fullName>
                <label>PAGARÉ PREVENTA</label>
            </value>
            <value>
                <fullName>PAGARE_REEMBOLSO_CANCELACION</fullName>
                <label>PAGARÉ REEMBOLSO CANCELACIÓN</label>
            </value>
            <value>
                <fullName>PAGARE_REEMBOLSO_ESCRITURA</fullName>
                <label>PAGARÉ REEMBOLSO ESCRITURA</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Documento__c/fields/Valor_de_la_Operaci_n__c.field-meta.xml
<CustomField>
    <fullName>Valor_de_la_Operaci_n__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Valor de la Operación</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Documento__c/recordTypes/Pagare.recordType-meta.xml
<RecordType>
    <fullName>Pagare</fullName>
    <active>true</active>
    <label>Factura</label>
</RecordType>

unpackaged/main/default/classes/CLASS_PagareFinanciera.cls
public with sharing class CLASS_PagareFinanciera {

    public static void creaPagaresFinanciera(String idCobranzaComercial, Integer plazo, String frecuencia, 
        Date inicio, Decimal diferenciaPagar, Boolean primerPagareFinanciera, Boolean primerPagareFinancieraManual) {

        Id pagareRT = SObjectType.Documento__c.getRecordTypeInfosByDeveloperName().get('Pagare').getRecordTypeId();
        system.debug('*** pagare RT '+pagareRT);

        List<Documento__c> pagaresFinancieraNuevos = new List<Documento__c>();

        Integer aux = 1;
        Double pagar = (diferenciaPagar/plazo);
        if(primerPagareFinanciera == true || primerPagareFinancieraManual == true){

            if(frecuencia == 'Semanal'){
                inicio = inicio.addDays(7);
            }
            else if(frecuencia == 'Quincenal'){
                inicio = inicio.addDays(15);
                aux = 0;
            }
            else if(frecuencia == 'Mensual'){
                inicio = inicio.addMonths(1);
            }
        }        
        
        for(Integer j=0; j<plazo; j++){
            Documento__c pagareFinancieraNuevo = new Documento__c();
            pagareFinancieraNuevo.Cobranza_Comercial__c = idCobranzaComercial;
            pagareFinancieraNuevo.Tipo__c = 'PAGARE_FINANCIERA';
            pagareFinancieraNuevo.RecordTypeId = pagareRT;
            pagareFinancieraNuevo.Estatus__c = 'ABIERTO';
            pagareFinancieraNuevo.Valor_de_la_Operaci_n__c = false; //??

                
            if(frecuencia == 'Semanal'){
                pagareFinancieraNuevo.Fecha_Vencimiento__c = inicio;
                pagareFinancieraNuevo.Importe__c = pagar;
                inicio = inicio.addDays(7);
            }
            else if(frecuencia == 'Quincenal'){
                pagareFinancieraNuevo.Importe__c = pagar;
                if(aux == 1){
                    pagareFinancieraNuevo.Fecha_Vencimiento__c = inicio;
                    aux = 0;
                }else{
                    pagareFinancieraNuevo.Fecha_Vencimiento__c = inicio.addDays(15);
                    aux = 1;
                    inicio = inicio.addMonths(1);
                }
            }
            else if(frecuencia == 'Mensual'){
                pagareFinancieraNuevo.Fecha_Vencimiento__c = inicio;
                pagareFinancieraNuevo.Importe__c = pagar;
                inicio = inicio.addMonths(1);
            }
            pagaresFinancieraNuevos.add(pagareFinancieraNuevo);
        }

        insert pagaresFinancieraNuevos;
        // return pagaresPreventaNuevos;


    }
}