unpackaged/main/default/objects/Aprobacion_Lista_de_Precios__c/Aprobacion_Lista_de_Precios__c.object-meta.xml
<CustomObject>
    <label>Aprobación Lista de Precios</label>
    <nameField>
        <displayFormat>ALP-{00000000}</displayFormat>
        <label>Nombre de Aprobación Lista de PRecios</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Aprobaciones Listas de Precios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Aprobacion_Lista_de_Precios__c/fields/Fraccionamiento__c.field-meta.xml
<CustomField>
    <fullName>Fraccionamiento__c</fullName>
    <formula>Lista_de_precios__r.Fraccionamiento__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Fraccionamiento</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Aprobacion_Lista_de_Precios__c/fields/IVA__c.field-meta.xml
<CustomField>
    <fullName>IVA__c</fullName>
    <label>%IVA</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Aprobacion_Lista_de_Precios__c/fields/Lista_de_precios__c.field-meta.xml
<CustomField>
    <fullName>Lista_de_precios__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lista de precios</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Aprobaciones Listas de Precios</relationshipLabel>
    <relationshipName>Aprobaciones_Listas_de_Precios</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Aprobacion_Lista_de_Precios__c/fields/Precio_de_Compra__c.field-meta.xml
<CustomField>
    <fullName>Precio_de_Compra__c</fullName>
    <formula>Lista_de_precios__r.Precio_de_Compra__c</formula>
    <label>Precio de Compra</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Aprobacion_Lista_de_Precios__c/fields/Precio_de_Venta_Sugerido__c.field-meta.xml
<CustomField>
    <fullName>Precio_de_Venta_Sugerido__c</fullName>
    <formula>Lista_de_precios__r.Precio_de_Venta_Sugerido__c</formula>
    <label>Precio de Venta Sugerido</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Aprobacion_Lista_de_Precios__c/fields/Precio_Total__c.field-meta.xml
<CustomField>
    <fullName>Precio_Total__c</fullName>
    <formula>&quot;$&quot; &amp;
IF( 
  Lista_de_precios__r.Precio_Total__c &gt;= 1000000, 
  TEXT(FLOOR(Lista_de_precios__r.Precio_Total__c / 1000000)) &amp; &quot;,&quot;, 
  &quot;&quot;) &amp; 
IF( 
  Lista_de_precios__r.Precio_Total__c &gt;= 1000, 
  RIGHT(TEXT(FLOOR(Lista_de_precios__r.Precio_Total__c / 1000)), 3) &amp; &quot;,&quot;, 
  &quot;&quot;) &amp; 
RIGHT(TEXT(FLOOR(Lista_de_precios__r.Precio_Total__c)), 3) &amp; &quot;.&quot; &amp; 
IF( 
  MOD(Lista_de_precios__r.Precio_Total__c , 1) * 100 &lt; 10, 
  &quot;0&quot; &amp; TEXT(ROUND(MOD(Lista_de_precios__r.Precio_Total__c , 1), 2) * 100), 
  TEXT(MIN(ROUND(MOD(Lista_de_precios__r.Precio_Total__c , 1), 2) * 100, 99)) 
)</formula>
    <label>Precio Total</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Aprobacion_Lista_de_Precios__c/fields/Prototipo__c.field-meta.xml
<CustomField>
    <fullName>Prototipo__c</fullName>
    <formula>Lista_de_precios__r.Prototipo__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Prototipo</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Aprobacion_Lista_de_Precios__c/fields/Solicitante__c.field-meta.xml
<CustomField>
    <fullName>Solicitante__c</fullName>
    <formula>Lista_de_precios__r.CreatedBy.FirstName &amp; &quot; &quot; &amp; Lista_de_precios__r.CreatedBy.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Solicitante</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Fraccionamiento__c/Fraccionamiento__c.object-meta.xml
<CustomObject>
    <label>Fraccionamiento</label>
    <nameField>
        <label>Nombre de Fraccionamiento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fraccionamientos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Fraccionamiento__c/fields/Prototipo__c.field-meta.xml
<CustomField>
    <fullName>Prototipo__c</fullName>
    <label>Prototipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prototipo 1</fullName>
            </value>
            <value>
                <fullName>Prototipo 2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Pricebook2/fields/Fraccionamiento__c.field-meta.xml
<CustomField>
    <fullName>Fraccionamiento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fraccionamiento</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 AND (2 OR 3)</booleanFilter>
        <filterItems>
            <field>Fraccionamiento__c.Activo_frac__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$User.Fraccionamiento_autorizado__c</field>
            <operation>contains</operation>
            <valueField>Fraccionamiento__c.Name</valueField>
        </filterItems>
        <filterItems>
            <field>$User.FraccionamientoAutorizados__c</field>
            <operation>contains</operation>
            <valueField>Fraccionamiento__c.Name</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Fraccionamiento__c</referenceTo>
    <relationshipLabel>Listas de precios</relationshipLabel>
    <relationshipName>Listas_de_precios</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Pricebook2/fields/IVA__c.field-meta.xml
<CustomField>
    <fullName>IVA__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>%IVA</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Pricebook2/fields/Precio_de_Compra__c.field-meta.xml
<CustomField>
    <fullName>Precio_de_Compra__c</fullName>
    <label>Precio de Compra</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Pricebook2/fields/Precio_de_Venta_Sugerido__c.field-meta.xml
<CustomField>
    <fullName>Precio_de_Venta_Sugerido__c</fullName>
    <label>Precio de Venta Sugerido</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Pricebook2/fields/Precio_Total__c.field-meta.xml
<CustomField>
    <fullName>Precio_Total__c</fullName>
    <label>Precio Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Pricebook2/fields/Prototipo__c.field-meta.xml
<CustomField>
    <fullName>Prototipo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prototipo</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Prototipo__c.Fraccionamiento__c</field>
            <operation>equals</operation>
            <valueField>$Source.Fraccionamiento__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Prototipo__c</referenceTo>
    <relationshipLabel>Listas de precios</relationshipLabel>
    <relationshipName>Listas_de_precios</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Beneficio2__c.field-meta.xml
<CustomField>
    <fullName>Beneficio2__c</fullName>
    <formula>IF(  Precio_de_Compra_con_Impuestos__c= 0, 0.00, (Precio_Venta__c  /   Precio_de_Compra_con_Impuestos__c)-1 )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>% Beneficio</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/IVA__c.field-meta.xml
<CustomField>
    <fullName>IVA__c</fullName>
    <label>% IVA</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Precio_de_Venta_Sugerido__c.field-meta.xml
<CustomField>
    <fullName>Precio_de_Venta_Sugerido__c</fullName>
    <formula>Precio_de_Compra_con_Impuestos__c * 1.2</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Precio de Venta Sugerido</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Precio_Total__c.field-meta.xml
<CustomField>
    <fullName>Precio_Total__c</fullName>
    <formula>Precio_Venta__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Precio Total PV</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Precio_Venta__c.field-meta.xml
<CustomField>
    <fullName>Precio_Venta__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Precio Venta al Cliente</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Prototipo__c/Prototipo__c.object-meta.xml
<CustomObject>
    <label>Prototipo</label>
    <nameField>
        <label>Prototipo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prototipos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Prototipo__c/fields/Fraccionamiento__c.field-meta.xml
<CustomField>
    <fullName>Fraccionamiento__c</fullName>
    <label>Fraccionamiento</label>
    <referenceTo>Fraccionamiento__c</referenceTo>
    <relationshipLabel>Prototipos</relationshipLabel>
    <relationshipName>Prototipos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/classes/AprobacionListasDePaquetes.cls
public class AprobacionListasDePaquetes {
    public Id recId{get;set;}
    public Aprobacion_Lista_de_Precios__c ap{get{
       return [SELECT Lista_de_precios__c, Lista_de_precios__r.Name, Fraccionamiento__c,  Prototipo__c,Solicitante__c FROM Aprobacion_Lista_de_Precios__c WHERE Id =:recId];
    }set;}
    public List<Product2> prodList{get{
        Aprobacion_Lista_de_Precios__c apr = [SELECT Lista_de_precios__c, Lista_de_precios__r.Name, Fraccionamiento__c,  Prototipo__c FROM Aprobacion_Lista_de_Precios__c WHERE Id =:recId];
        String priceBookId = apr.Lista_de_precios__c;
        Set<Id> productIds = new Set<Id>();
        for(PriceBookEntry pe : [SELECT Product2Id FROM PriceBookEntry WHERE PriceBook2Id =:priceBookId]){
            productIds.add(pe.Product2Id);
        }
        return [SELECT Name, Precio_Venta__c, Precio_de_Compra__c, IVA__c, Precio_Total__c, Beneficio2__c, Precio_de_Venta_Sugerido__c FROM Product2 WHERE Id IN:productIds];
    }set;}
    public String actorName{get{
         List<ProcessInstanceWorkitem> pworkList = new List<ProcessInstanceWorkitem>();
        pworkList = [SELECT Id, ProcessInstanceId, OriginalActor.Name, Actor.Name, ElapsedTimeInDays, ElapsedTimeInHours, ElapsedTimeInMinutes, IsDeleted, CreatedDate, CreatedById, SystemModstamp 
                     FROM ProcessInstanceWorkitem 
                     WHERE ProcessInstance.targetObjectId =: recId
                    ];
        if(pworkList.size() > 0){
            return pworkList[0].OriginalActor.Name;
        }
        else{
            return '';
        }
    }set;}
    
    
    public AprobacionListasDePaquetes(){
    }
    public void init(){
        prodList = new List<Product2>();
        
        
        List<ProcessInstanceWorkitem> pworkList = new List<ProcessInstanceWorkitem>();
        pworkList = [SELECT Id, ProcessInstanceId, OriginalActor.Name, Actor.Name, ElapsedTimeInDays, ElapsedTimeInHours, ElapsedTimeInMinutes, IsDeleted, CreatedDate, CreatedById, SystemModstamp 
                     FROM ProcessInstanceWorkitem 
                     WHERE ProcessInstance.targetObjectId =: recId
                    ];
        actorName = '';
        if(pworkList.size() > 0){
            actorName = pworkList[0].OriginalActor.Name;
        }
    }
}