unpackaged/main/default/objects/Lead/fields/Asesores__c.field-meta.xml
<CustomField>
    <fullName>Asesores__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Asesores disponibles para asignar a un lead</description>
    <label>Asesor</label>
    <referenceTo>Asesores__c</referenceTo>
    <relationshipLabel>Prospectos</relationshipLabel>
    <relationshipName>Prospectos</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/ErrorCodeResponseSOAP__c.field-meta.xml
<CustomField>
    <fullName>ErrorCodeResponseSOAP__c</fullName>
    <label>Código de Respuesta</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/JCM_Carga_inicial__c.field-meta.xml
<CustomField>
    <fullName>JCM_Carga_inicial__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo para identificar leads de la carga inicial</description>
    <label>Carga inicial</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/JMC_ApellidoMaterno__c.field-meta.xml
<CustomField>
    <fullName>JMC_ApellidoMaterno__c</fullName>
    <description>Campo para capturar el apellido materno</description>
    <label>Apellido Materno</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/JMC_AsesorAsignado__c.field-meta.xml
<CustomField>
    <fullName>JMC_AsesorAsignado__c</fullName>
    <description>Campo para asignar el nombre del asesor que dará seguimiento al lead</description>
    <label>Asesor Asignado</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/JMC_CanalVenta__c.field-meta.xml
<CustomField>
    <fullName>JMC_CanalVenta__c</fullName>
    <description>Catálogo relacionado al canal de venta</description>
    <label>Canal de Venta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Digital Asesor</fullName>
            </value>
            <value>
                <fullName>Evento</fullName>
            </value>
            <value>
                <fullName>Llamada Call Center</fullName>
            </value>
            <value>
                <fullName>Macroventa</fullName>
            </value>
            <value>
                <fullName>Medio Publicitario</fullName>
            </value>
            <value>
                <fullName>Medios Digitales</fullName>
            </value>
            <value>
                <fullName>Programas Institucionales</fullName>
            </value>
            <value>
                <fullName>Promotor Externo</fullName>
            </value>
            <value>
                <fullName>Prospección</fullName>
            </value>
            <value>
                <fullName>Referidos</fullName>
            </value>
            <value>
                <fullName>Venta Empresarial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/JMC_Estado__c.field-meta.xml
<CustomField>
    <fullName>JMC_Estado__c</fullName>
    <description>Campo que tiene como objetivo mostrar los Estados de la Republica mexicana</description>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aguascalientes</fullName>
            </value>
            <value>
                <fullName>Baja California</fullName>
            </value>
            <value>
                <fullName>Baja California Sur</fullName>
            </value>
            <value>
                <fullName>Campeche</fullName>
            </value>
            <value>
                <fullName>Chiapas</fullName>
            </value>
            <value>
                <fullName>Chihuahua</fullName>
            </value>
            <value>
                <fullName>Ciudad de México</fullName>
            </value>
            <value>
                <fullName>Coahuila</fullName>
            </value>
            <value>
                <fullName>Colima</fullName>
            </value>
            <value>
                <fullName>Durango</fullName>
            </value>
            <value>
                <fullName>Estado de México</fullName>
            </value>
            <value>
                <fullName>Guanajuato</fullName>
            </value>
            <value>
                <fullName>Guerrero</fullName>
            </value>
            <value>
                <fullName>Hidalgo</fullName>
            </value>
            <value>
                <fullName>Jalisco</fullName>
            </value>
            <value>
                <fullName>Michoacán</fullName>
            </value>
            <value>
                <fullName>Morelos</fullName>
            </value>
            <value>
                <fullName>Nayarit</fullName>
            </value>
            <value>
                <fullName>Nuevo León</fullName>
            </value>
            <value>
                <fullName>Oaxaca</fullName>
            </value>
            <value>
                <fullName>Puebla</fullName>
            </value>
            <value>
                <fullName>Querétaro</fullName>
            </value>
            <value>
                <fullName>Quintana Roo</fullName>
            </value>
            <value>
                <fullName>San Luis Potosí</fullName>
            </value>
            <value>
                <fullName>Sinaloa</fullName>
            </value>
            <value>
                <fullName>Sonora</fullName>
            </value>
            <value>
                <fullName>Tabasco</fullName>
            </value>
            <value>
                <fullName>Tamaulipas</fullName>
            </value>
            <value>
                <fullName>Tlaxcala</fullName>
            </value>
            <value>
                <fullName>Veracruz</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/JMC_EstatusLead__c.field-meta.xml
<CustomField>
    <fullName>JMC_EstatusLead__c</fullName>
    <description>Campo relacionado al análisis interno</description>
    <label>Estatus Lead</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No validado</fullName>
            </value>
            <value>
                <fullName>No Interesado</fullName>
            </value>
            <value>
                <fullName>Incubadora</fullName>
            </value>
            <value>
                <fullName>Ilocalizable</fullName>
            </value>
            <value>
                <fullName>Perfilado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/JMC_FechaNacimiento__c.field-meta.xml
<CustomField>
    <fullName>JMC_FechaNacimiento__c</fullName>
    <description>Campo para la fecha de nacimiento</description>
    <label>Fecha de Nacimiento</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/JMC_Fraccionamiento__c.field-meta.xml
<CustomField>
    <fullName>JMC_Fraccionamiento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo para la asignación del fraccionamiento de interés en el que se creará el prospecto</description>
    <label>Fraccionamiento</label>
    <referenceTo>Fraccionamiento__c</referenceTo>
    <relationshipLabel>Prospectos (Fraccionamiento)</relationshipLabel>
    <relationshipName>Prospectos1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/JMC_Fuente__c.field-meta.xml
<CustomField>
    <fullName>JMC_Fuente__c</fullName>
    <description>Campo para identificar el canal por el que se creó el lead</description>
    <label>Fuente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Afluencia_base_externa</fullName>
            </value>
            <value>
                <fullName>Aperturas</fullName>
            </value>
            <value>
                <fullName>Arrayanes</fullName>
            </value>
            <value>
                <fullName>Asesor_para_perfil_FB</fullName>
            </value>
            <value>
                <fullName>ATC Cliente carga manual</fullName>
            </value>
            <value>
                <fullName>Base_de_datos_externa</fullName>
            </value>
            <value>
                <fullName>Base_externa_marzo2017</fullName>
            </value>
            <value>
                <fullName>Blogger/Tania Rendón</fullName>
            </value>
            <value>
                <fullName>Buen Fin</fullName>
            </value>
            <value>
                <fullName>Cadreon</fullName>
            </value>
            <value>
                <fullName>Chatbot_MJ</fullName>
            </value>
            <value>
                <fullName>chatbot fb</fullName>
            </value>
            <value>
                <fullName>chatbot wa</fullName>
            </value>
            <value>
                <fullName>chatbot web</fullName>
            </value>
            <value>
                <fullName>Chat Sitio</fullName>
            </value>
            <value>
                <fullName>Click to Call</fullName>
            </value>
            <value>
                <fullName>Display_lead</fullName>
            </value>
            <value>
                <fullName>Expo_virtual_Javer</fullName>
            </value>
            <value>
                <fullName>Facebook_lead</fullName>
            </value>
            <value>
                <fullName>Facebook_lead_fovissste</fullName>
            </value>
            <value>
                <fullName>Facebook_lead_oc</fullName>
            </value>
            <value>
                <fullName>Facebook Inbox</fullName>
            </value>
            <value>
                <fullName>Facebook Inbox Pagado</fullName>
            </value>
            <value>
                <fullName>Formulario ATC</fullName>
            </value>
            <value>
                <fullName>Fovissste_base_externa</fullName>
            </value>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Inmuebles24</fullName>
            </value>
            <value>
                <fullName>Instagram</fullName>
            </value>
            <value>
                <fullName>Instagram_lead</fullName>
            </value>
            <value>
                <fullName>Instagram Lead</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/JMC_Genero__c.field-meta.xml
<CustomField>
    <fullName>JMC_Genero__c</fullName>
    <description>Sexo del cliente</description>
    <label>Sexo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Masculino</fullName>
            </value>
            <value>
                <fullName>Femenino</fullName>
            </value>
            <value>
                <fullName>Indistinto</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/JMC_LeadProfile__c.field-meta.xml
<CustomField>
    <fullName>JMC_LeadProfile__c</fullName>
    <description>Agente lead profiler que dará seguimiento</description>
    <label>Lead Profiler</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/JMC_Lote__c.field-meta.xml
<CustomField>
    <fullName>JMC_Lote__c</fullName>
    <description>Número de lote de la ubicación reservada</description>
    <label>Lote</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/JMC_Manzana__c.field-meta.xml
<CustomField>
    <fullName>JMC_Manzana__c</fullName>
    <description>Manzana de la ubicación reservada</description>
    <label>Manzana</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/JMC_NSS__c.field-meta.xml
<CustomField>
    <fullName>JMC_NSS__c</fullName>
    <description>NSS del cliente</description>
    <label>NSS</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/JMC_ProspectadorMASComercial__c.field-meta.xml
<CustomField>
    <fullName>JMC_ProspectadorMASComercial__c</fullName>
    <label>Prospectador MAS Comercial</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/JMC_TipoCredito__c.field-meta.xml
<CustomField>
    <fullName>JMC_TipoCredito__c</fullName>
    <description>Catálogo con los tipos de crédito</description>
    <label>Tipo de Crédito</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BANSEFI</fullName>
            </value>
            <value>
                <fullName>BANJERCITO</fullName>
            </value>
            <value>
                <fullName>COFINAVIT</fullName>
            </value>
            <value>
                <fullName>CONTADO</fullName>
            </value>
            <value>
                <fullName>FOVISSSTE</fullName>
            </value>
            <value>
                <fullName>INFONAVIT</fullName>
            </value>
            <value>
                <fullName>ISSFAM</fullName>
            </value>
            <value>
                <fullName>ISSSTELEON</fullName>
            </value>
            <value>
                <fullName>PENSIONES</fullName>
            </value>
            <value>
                <fullName>SHF/BANCO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/JMC_UEN__c.field-meta.xml
<CustomField>
    <fullName>JMC_UEN__c</fullName>
    <description>Campo para identificar la UEN del fraccionamiento de interés</description>
    <label>UEN</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/MsgResponseWS__c.field-meta.xml
<CustomField>
    <fullName>MsgResponseWS__c</fullName>
    <description>Campo para el monitoreo de la respuesta del servicio integrado con Siebel</description>
    <label>Mensaje Siebel</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/classes/UtilsTEST_test.cls
/*
----------------------------------------------------------
* Nombre: UtilsTEST_test
* Autor Saúl González	
* Proyecto: Kavak
* Descripción : Clase con metódos test 
* --------------------------------------------------------------------------------
* Versión       Fecha           Autor                   Desripción<p />
* --------------------------------------------------------------------------------
* 1.0           19/03/2021     Saúl González           	Creación
* --------------------------------------------------------------------------------
*/
@isTest
public class UtilsTEST_test {

    /*
    * @description Method que devuelve un Lead
    * @param String idLead
	* @return Lead
    */ 
    public static Lead getObjLeadAcct(String idAcct) {
        Lead objLead = new Lead();
			objLead = [SELECT id, Name, JMC_ApellidoMaterno__c,JMC_LeadProfile__c,JMC_EstatusLead__c,JMC_AsesorAsignado__c,status, Asesores__r.name,
        		JMC_Fuente__c,FirstName,LastName, OwnerId, Owner.Name,MobilePhone,ErrorCodeResponseSOAP__c, MsgResponseWS__c,IsConverted,
                JMC_FechaNacimiento__c,Phone,Email,JMC_TipoCredito__c,JMC_NSS__c, LastModifiedById,JMC_ProspectadorMASComercial__c,JMC_Manzana__c,
                JMC_Genero__c,JMC_UEN__c,JMC_Estado__c,JMC_Fraccionamiento__c,JMC_Fraccionamiento__r.name,JMC_CanalVenta__c,JMC_Lote__c, JCM_Carga_inicial__c,
                JMC_SubCanalVenta__c,JMC_Asunto__c,JMC_CapacidadCompra__c,JMC_Edad__c,ID_CUENTA__c FROM Lead Where ID_CUENTA__c =: idAcct];     
        return objLead;
    }
    
    /*
    * @description Method que devuelve un Lead
    * @param String idLead
	* @return Lead
    */ 
    public static Lead getObjLeadName(String name) {
        Lead objLead = new Lead();
			objLead = [SELECT id, Name, JMC_ApellidoMaterno__c,JMC_LeadProfile__c,JMC_EstatusLead__c,JMC_AsesorAsignado__c,status, Asesores__r.Name,
        		JMC_Fuente__c,FirstName,LastName, OwnerId, Owner.Name,MobilePhone,ErrorCodeResponseSOAP__c, MsgResponseWS__c,IsConverted,
                JMC_FechaNacimiento__c,Phone,Email,JMC_TipoCredito__c,JMC_NSS__c, LastModifiedById,JMC_ProspectadorMASComercial__c,JMC_Manzana__c,
                JMC_Genero__c,JMC_UEN__c,JMC_Estado__c,JMC_Fraccionamiento__c,JMC_Fraccionamiento__r.name,JMC_CanalVenta__c,JMC_Lote__c,JCM_Carga_inicial__c,
                JMC_SubCanalVenta__c,JMC_Asunto__c,JMC_CapacidadCompra__c,JMC_Edad__c,ID_CUENTA__c FROM Lead Where ID_CUENTA__c =: name];     
        return objLead;
    }
}