unpackaged/main/default/objects/Lead/fields/ErrorCodeResponseSOAP__c.field-meta.xml
<CustomField>
    <fullName>ErrorCodeResponseSOAP__c</fullName>
    <label>Código de Respuesta</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/JMC_CanalVenta__c.field-meta.xml
<CustomField>
    <fullName>JMC_CanalVenta__c</fullName>
    <description>Catálogo relacionado al canal de venta</description>
    <label>Canal de Venta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Digital Asesor</fullName>
            </value>
            <value>
                <fullName>Evento</fullName>
            </value>
            <value>
                <fullName>Llamada Call Center</fullName>
            </value>
            <value>
                <fullName>Macroventa</fullName>
            </value>
            <value>
                <fullName>Medio Publicitario</fullName>
            </value>
            <value>
                <fullName>Medios Digitales</fullName>
            </value>
            <value>
                <fullName>Programas Institucionales</fullName>
            </value>
            <value>
                <fullName>Promotor Externo</fullName>
            </value>
            <value>
                <fullName>Prospección</fullName>
            </value>
            <value>
                <fullName>Referidos</fullName>
            </value>
            <value>
                <fullName>Venta Empresarial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/JMC_Edad__c.field-meta.xml
<CustomField>
    <fullName>JMC_Edad__c</fullName>
    <label>Edad</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/JMC_Estado__c.field-meta.xml
<CustomField>
    <fullName>JMC_Estado__c</fullName>
    <description>Campo que tiene como objetivo mostrar los Estados de la Republica mexicana</description>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aguascalientes</fullName>
            </value>
            <value>
                <fullName>Baja California</fullName>
            </value>
            <value>
                <fullName>Baja California Sur</fullName>
            </value>
            <value>
                <fullName>Campeche</fullName>
            </value>
            <value>
                <fullName>Chiapas</fullName>
            </value>
            <value>
                <fullName>Chihuahua</fullName>
            </value>
            <value>
                <fullName>Ciudad de México</fullName>
            </value>
            <value>
                <fullName>Coahuila</fullName>
            </value>
            <value>
                <fullName>Colima</fullName>
            </value>
            <value>
                <fullName>Durango</fullName>
            </value>
            <value>
                <fullName>Estado de México</fullName>
            </value>
            <value>
                <fullName>Guanajuato</fullName>
            </value>
            <value>
                <fullName>Guerrero</fullName>
            </value>
            <value>
                <fullName>Hidalgo</fullName>
            </value>
            <value>
                <fullName>Jalisco</fullName>
            </value>
            <value>
                <fullName>Michoacán</fullName>
            </value>
            <value>
                <fullName>Morelos</fullName>
            </value>
            <value>
                <fullName>Nayarit</fullName>
            </value>
            <value>
                <fullName>Nuevo León</fullName>
            </value>
            <value>
                <fullName>Oaxaca</fullName>
            </value>
            <value>
                <fullName>Puebla</fullName>
            </value>
            <value>
                <fullName>Querétaro</fullName>
            </value>
            <value>
                <fullName>Quintana Roo</fullName>
            </value>
            <value>
                <fullName>San Luis Potosí</fullName>
            </value>
            <value>
                <fullName>Sinaloa</fullName>
            </value>
            <value>
                <fullName>Sonora</fullName>
            </value>
            <value>
                <fullName>Tabasco</fullName>
            </value>
            <value>
                <fullName>Tamaulipas</fullName>
            </value>
            <value>
                <fullName>Tlaxcala</fullName>
            </value>
            <value>
                <fullName>Veracruz</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/JMC_FechaCaptura__c.field-meta.xml
<CustomField>
    <fullName>JMC_FechaCaptura__c</fullName>
    <label>Fecha de Captura</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/JMC_FechaNacimiento__c.field-meta.xml
<CustomField>
    <fullName>JMC_FechaNacimiento__c</fullName>
    <description>Campo para la fecha de nacimiento</description>
    <label>Fecha de Nacimiento</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/JMC_FechaProspeccion__c.field-meta.xml
<CustomField>
    <fullName>JMC_FechaProspeccion__c</fullName>
    <label>Fecha de Prospección</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/JMC_FechaVencimiento__c.field-meta.xml
<CustomField>
    <fullName>JMC_FechaVencimiento__c</fullName>
    <label>Fecha de Vencimiento</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/JMC_FraccionamientoInterno__c.field-meta.xml
<CustomField>
    <fullName>JMC_FraccionamientoInterno__c</fullName>
    <label>FraccionamientoInterno</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ACACIAS</fullName>
            </value>
            <value>
                <fullName>ALBERI RESIDENCIAL</fullName>
            </value>
            <value>
                <fullName>ALBORETO RESIDENCIAL</fullName>
            </value>
            <value>
                <fullName>ALVENTO</fullName>
            </value>
            <value>
                <fullName>ARBOLADA</fullName>
            </value>
            <value>
                <fullName>ARCOS 7</fullName>
            </value>
            <value>
                <fullName>ARCOS DEL SOL</fullName>
            </value>
            <value>
                <fullName>ARCOS DEL SOL SECTOR ELITE</fullName>
            </value>
            <value>
                <fullName>ARRAYANES HABITAT II</fullName>
            </value>
            <value>
                <fullName>BARRIO ESTRELLA</fullName>
            </value>
            <value>
                <fullName>BELCANTO</fullName>
            </value>
            <value>
                <fullName>BELCANTO II</fullName>
            </value>
            <value>
                <fullName>BELLATERRA</fullName>
            </value>
            <value>
                <fullName>BELLA VISTA 2º SECTOR FOMERREY</fullName>
            </value>
            <value>
                <fullName>BELLA VISTA 3ER SECTOR</fullName>
            </value>
            <value>
                <fullName>BELLO AMANECER RESIDENCIAL</fullName>
            </value>
            <value>
                <fullName>BOSQUE BOREAL</fullName>
            </value>
            <value>
                <fullName>BOSQUE DE LOS NOGALES</fullName>
            </value>
            <value>
                <fullName>BOSQUE REAL</fullName>
            </value>
            <value>
                <fullName>BOSQUES DE CASTILLA</fullName>
            </value>
            <value>
                <fullName>BOSQUES DE LERMA</fullName>
            </value>
            <value>
                <fullName>BOSQUES DEL NEVADO</fullName>
            </value>
            <value>
                <fullName>BOSQUES DE SAN JUAN</fullName>
            </value>
            <value>
                <fullName>BOSQUES DE SAN JUAN 2</fullName>
            </value>
            <value>
                <fullName>BOSQUES DE SAN JUAN 3</fullName>
            </value>
            <value>
                <fullName>BOSQUES DE SAN JUAN IV</fullName>
            </value>
            <value>
                <fullName>BOSQUES DE SAN JUAN V</fullName>
            </value>
            <value>
                <fullName>BOSQUES LA HUASTECA</fullName>
            </value>
            <value>
                <fullName>BULGARIA 533 WELT</fullName>
            </value>
            <value>
                <fullName>CAMPANARIO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/JMC_Genero__c.field-meta.xml
<CustomField>
    <fullName>JMC_Genero__c</fullName>
    <description>Sexo del cliente</description>
    <label>Sexo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Masculino</fullName>
            </value>
            <value>
                <fullName>Femenino</fullName>
            </value>
            <value>
                <fullName>Indistinto</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/JMC_Perfilar__c.field-meta.xml
<CustomField>
    <fullName>JMC_Perfilar__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Perfilar</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/JMC_SubCanalVenta__c.field-meta.xml
<CustomField>
    <fullName>JMC_SubCanalVenta__c</fullName>
    <description>Catálogo con los subcanales de venta disponibles</description>
    <label>Subcanal de Venta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Activación/Evento</fullName>
            </value>
            <value>
                <fullName>Activación/Evento/Periferia</fullName>
            </value>
            <value>
                <fullName>AGS Feria CANADEVI</fullName>
            </value>
            <value>
                <fullName>AGS Moctezuma</fullName>
            </value>
            <value>
                <fullName>AGS San Diego</fullName>
            </value>
            <value>
                <fullName>Ags Villa Asunción</fullName>
            </value>
            <value>
                <fullName>APP INVITADO</fullName>
            </value>
            <value>
                <fullName>Blogger/Tania Rendón</fullName>
            </value>
            <value>
                <fullName>Buen Fin</fullName>
            </value>
            <value>
                <fullName>Call Center / Telemarketing</fullName>
            </value>
            <value>
                <fullName>Cambaceo</fullName>
            </value>
            <value>
                <fullName>Cartelera Móvil</fullName>
            </value>
            <value>
                <fullName>Cartelera PV</fullName>
            </value>
            <value>
                <fullName>Cartera de Clientes</fullName>
            </value>
            <value>
                <fullName>Cartera Propia</fullName>
            </value>
            <value>
                <fullName>Cita Asesor</fullName>
            </value>
            <value>
                <fullName>Colaborador Javer</fullName>
            </value>
            <value>
                <fullName>Compañero de Trabajo</fullName>
            </value>
            <value>
                <fullName>Convenio Pabellon M</fullName>
            </value>
            <value>
                <fullName>Correo</fullName>
            </value>
            <value>
                <fullName>Correo Directo/Carta</fullName>
            </value>
            <value>
                <fullName>Edo Mex Samara</fullName>
            </value>
            <value>
                <fullName>En Empresa (Venta Empresarial)</fullName>
            </value>
            <value>
                <fullName>Espectacular/Cartelera</fullName>
            </value>
            <value>
                <fullName>Eventos (Macroventa, Súpervta)</fullName>
            </value>
            <value>
                <fullName>Expo/Feria</fullName>
            </value>
            <value>
                <fullName>Facebook</fullName>
            </value>
            <value>
                <fullName>Facebook Inbox</fullName>
            </value>
            <value>
                <fullName>Familiar</fullName>
            </value>
            <value>
                <fullName>FB Asesor Orgánico</fullName>
            </value>
            <value>
                <fullName>Prospección</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/JMC_TipoCredito__c.field-meta.xml
<CustomField>
    <fullName>JMC_TipoCredito__c</fullName>
    <description>Catálogo con los tipos de crédito</description>
    <label>Tipo de Crédito</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BANSEFI</fullName>
            </value>
            <value>
                <fullName>BANJERCITO</fullName>
            </value>
            <value>
                <fullName>COFINAVIT</fullName>
            </value>
            <value>
                <fullName>CONTADO</fullName>
            </value>
            <value>
                <fullName>FOVISSSTE</fullName>
            </value>
            <value>
                <fullName>INFONAVIT</fullName>
            </value>
            <value>
                <fullName>ISSFAM</fullName>
            </value>
            <value>
                <fullName>ISSSTELEON</fullName>
            </value>
            <value>
                <fullName>PENSIONES</fullName>
            </value>
            <value>
                <fullName>SHF/BANCO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/JMC_WSResponseEx__c.field-meta.xml
<CustomField>
    <fullName>JMC_WSResponseEx__c</fullName>
    <defaultValue>false</defaultValue>
    <label>WS Response Exc</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/MsgResponseWS__c.field-meta.xml
<CustomField>
    <fullName>MsgResponseWS__c</fullName>
    <description>Campo para el monitoreo de la respuesta del servicio integrado con Siebel</description>
    <label>Mensaje Siebel</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/classes/LeadsUtils_test.cls
/*
----------------------------------------------------------
* Nombre: classLeadsUtils_test
* Autor Saúl González   
* Proyecto: Kavak
* Descripción : Clase con metódos test 
* --------------------------------------------------------------------------------
* Versión       Fecha           Autor                   Desripción<p />
* --------------------------------------------------------------------------------
* 1.0           19/03/2021     Saúl González            Creación
* --------------------------------------------------------------------------------
*/
@isTest
private class LeadsUtils_test {
    @testSetup static void setup() {
        Fraccionamiento__c f = new Fraccionamiento__c();
        f.Name = 'ALVENTO';
        insert f;
        
        Lead l = new Lead();
        l.JMC_WSResponseEx__c = false;
        l.Email = 'noventa@javer.com.mx';
        l.JMC_FechaNacimiento__c = date.valueof('1980-03-21T00:00:00.000Z');
        l.ErrorCodeResponseSOAP__c = '0';
        l.JMC_FraccionamientoInterno__c = 'ALVENTO';
        l.JMC_Genero__c = 'Masculino';
        l.JMC_Estado__c = 'Jalisco';
        l.JMC_FechaCaptura__c = date.valueof('2021-03-19T00:00:00.000Z');
        l.JMC_FechaProspeccion__c = date.valueof('2021-03-19T00:00:00.000Z');
        l.JMC_CanalVenta__c = 'Medios Digitales';
        l.MsgResponseWS__c = 'Cuenta Creada Exitos';
        l.JMC_SubCanalVenta__c = 'Facebook';
        l.JMC_TipoCredito__c = 'CONTADO';
        l.Status = 'Envío MAS Comercial';
        l.JMC_Edad__c = 41;
        l.JMC_FechaVencimiento__c = date.valueof('2021-04-03T00:00:00.000Z');
        l.JMC_Perfilar__c = false;
        l.JMC_Analisisinterno__c = 'Perfilado';
        l.DeleteMailDuplicate__c = false;
        l.ID_CUENTA__c = '1-2MAANPJ';
        l.LeadSource = 'Prospección';
        l.JMC_AsesorAsignado__c = 'ADMINISTRADOR GENERA';
        l.JMC_ProspectadorMASComercial__c = 'LAURA VERONICA LOPEZ';
        l.LastName = 'NOVENTA';
        l.JMC_Fraccionamiento__c = f.Id;
        l.JMC_IdDelete__c = false;
        l.Phone = '528111336699';
        l.JMC_Re_Registro__c = false;
        l.FirstName = 'REGISTRO';
        /*l.MiddleName = 'SALES';*/
        l.JMC_UEN__c = 'UEN3 - JALISCO';
        l.JMC_FechaAsignacion__c = date.valueof('2021-03-19T00:00:00.000Z');
        l.JMC_EstatusLead__c = 'Perfilado';
        insert l;        
    }
    static testMethod void getFracc(){
        Set<Integer> leadset =  new Set<Integer>();
        leadset.add(1);
        Id idOpp = [SELECT Id FROM Lead WHERE ID_CUENTA__c='1-2MAANPJ' limit 1].Id;
        String nF = [SELECT Id, Name FROM Fraccionamiento__c limit 1].Name;
        User usr = [SELECT id, name, JMC_ContadorLeads__c, JMC_FechaActividadContador__c, Id_Lead_Profiler__c FROM User Where Id =: UserInfo.getUserId()];
        usr.Id_Lead_Profiler__c = 1;
        update usr;
        Test.startTest();
        LeadsUtils_ctrl lH = new LeadsUtils_ctrl();
        LeadsUtils_ctrl.getFracc(nF);
        LeadsUtils_ctrl.getOwLead(UserInfo.getUserId());
        LeadsUtils_ctrl.getObjLead(idOpp);
        LeadsUtils_ctrl.getUsersIdSiebel(leadset);
        Test.stopTest();
    } 
    static testMethod void getObjLeadMail(){
        String email = [SELECT Id, email FROM Lead WHERE ID_CUENTA__c='1-2MAANPJ' limit 1].email;
        Test.startTest();
        LeadsUtils_ctrl lH = new LeadsUtils_ctrl();
        LeadsUtils_ctrl.getObjLeadMail(email);
        LeadsUtils_ctrl.validaDatoVacio('');
        LeadsUtils_ctrl.getDataTime('');
        LeadsUtils_ctrl.getDate('');
        LeadsUtils_ctrl.getDecimal('');
        LeadsUtils_ctrl.getDobDecimal(null);
        LeadsUtils_ctrl.getStringDec(null);
        LeadsUtils_ctrl.getDouString(null);
        LeadsUtils_ctrl.getStrToMap('');
        LeadsUtils_ctrl.getAllLabels('Account');
        LeadsUtils_ctrl.getUser(UserInfo.getName());
        LeadsUtils_ctrl.getFilteredPhone('+3216549871');
        LeadsUtils_ctrl.getNewData('','a');
        Test.stopTest();
    }
}