unpackaged/main/default/objects/Lead/fields/JMC_Analisisinterno__c.field-meta.xml
<CustomField>
    <fullName>JMC_Analisisinterno__c</fullName>
    <description>Campo que detona las reglas en las etapas de prospección y el envío a MAS Comercial.</description>
    <label>Análisis interno</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Asesor externo</fullName>
            </value>
            <value>
                <fullName>Aumento de crédito</fullName>
            </value>
            <value>
                <fullName>Baja</fullName>
            </value>
            <value>
                <fullName>Buscando opciones</fullName>
            </value>
            <value>
                <fullName>Compra a largo plazo</fullName>
            </value>
            <value>
                <fullName>En atención</fullName>
                <label>En atención en fracc</label>
            </value>
            <value>
                <fullName>Error registro</fullName>
            </value>
            <value>
                <fullName>Existe</fullName>
            </value>
            <value>
                <fullName>Mailing WhatsApp</fullName>
                <label>Mailing whatsapp</label>
            </value>
            <value>
                <fullName>Mensaje error Infonavit</fullName>
            </value>
            <value>
                <fullName>No contesta</fullName>
            </value>
            <value>
                <fullName>No lo conocen</fullName>
            </value>
            <value>
                <fullName>No validado</fullName>
            </value>
            <value>
                <fullName>Numero invalido</fullName>
                <label>Número inválido</label>
            </value>
            <value>
                <fullName>Numero suspendido</fullName>
                <label>Número suspendido</label>
            </value>
            <value>
                <fullName>Perfilado</fullName>
            </value>
            <value>
                <fullName>Personas mayores</fullName>
            </value>
            <value>
                <fullName>Producto</fullName>
            </value>
            <value>
                <fullName>Puntos posteriores</fullName>
            </value>
            <value>
                <fullName>Referencias</fullName>
            </value>
            <value>
                <fullName>Registro renta</fullName>
            </value>
            <value>
                <fullName>Sin capacidad de compra</fullName>
            </value>
            <value>
                <fullName>Sin confirmar</fullName>
            </value>
            <value>
                <fullName>Sin oferta de vivienda</fullName>
            </value>
            <value>
                <fullName>Sin validar</fullName>
            </value>
            <value>
                <fullName>Tipo de crédito</fullName>
            </value>
            <value>
                <fullName>Ubicación</fullName>
            </value>
            <value>
                <fullName>No existe</fullName>
                <isActive>false</isActive>
                <label>No existe</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/JMC_AsesorAsignado__c.field-meta.xml
<CustomField>
    <fullName>JMC_AsesorAsignado__c</fullName>
    <description>Campo para asignar el nombre del asesor que dará seguimiento al lead</description>
    <label>Asesor Asignado</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/JMC_Estado__c.field-meta.xml
<CustomField>
    <fullName>JMC_Estado__c</fullName>
    <description>Campo que tiene como objetivo mostrar los Estados de la Republica mexicana</description>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aguascalientes</fullName>
            </value>
            <value>
                <fullName>Baja California</fullName>
            </value>
            <value>
                <fullName>Baja California Sur</fullName>
            </value>
            <value>
                <fullName>Campeche</fullName>
            </value>
            <value>
                <fullName>Chiapas</fullName>
            </value>
            <value>
                <fullName>Chihuahua</fullName>
            </value>
            <value>
                <fullName>Ciudad de México</fullName>
            </value>
            <value>
                <fullName>Coahuila</fullName>
            </value>
            <value>
                <fullName>Colima</fullName>
            </value>
            <value>
                <fullName>Durango</fullName>
            </value>
            <value>
                <fullName>Estado de México</fullName>
            </value>
            <value>
                <fullName>Guanajuato</fullName>
            </value>
            <value>
                <fullName>Guerrero</fullName>
            </value>
            <value>
                <fullName>Hidalgo</fullName>
            </value>
            <value>
                <fullName>Jalisco</fullName>
            </value>
            <value>
                <fullName>Michoacán</fullName>
            </value>
            <value>
                <fullName>Morelos</fullName>
            </value>
            <value>
                <fullName>Nayarit</fullName>
            </value>
            <value>
                <fullName>Nuevo León</fullName>
            </value>
            <value>
                <fullName>Oaxaca</fullName>
            </value>
            <value>
                <fullName>Puebla</fullName>
            </value>
            <value>
                <fullName>Querétaro</fullName>
            </value>
            <value>
                <fullName>Quintana Roo</fullName>
            </value>
            <value>
                <fullName>San Luis Potosí</fullName>
            </value>
            <value>
                <fullName>Sinaloa</fullName>
            </value>
            <value>
                <fullName>Sonora</fullName>
            </value>
            <value>
                <fullName>Tabasco</fullName>
            </value>
            <value>
                <fullName>Tamaulipas</fullName>
            </value>
            <value>
                <fullName>Tlaxcala</fullName>
            </value>
            <value>
                <fullName>Veracruz</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/JMC_EstatusLead__c.field-meta.xml
<CustomField>
    <fullName>JMC_EstatusLead__c</fullName>
    <description>Campo relacionado al análisis interno</description>
    <label>Estatus Lead</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No validado</fullName>
            </value>
            <value>
                <fullName>No Interesado</fullName>
            </value>
            <value>
                <fullName>Incubadora</fullName>
            </value>
            <value>
                <fullName>Ilocalizable</fullName>
            </value>
            <value>
                <fullName>Perfilado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/JMC_FechaCaptura__c.field-meta.xml
<CustomField>
    <fullName>JMC_FechaCaptura__c</fullName>
    <label>Fecha de Captura</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/JMC_FechaNacimiento__c.field-meta.xml
<CustomField>
    <fullName>JMC_FechaNacimiento__c</fullName>
    <description>Campo para la fecha de nacimiento</description>
    <label>Fecha de Nacimiento</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/JMC_FechaProspeccion__c.field-meta.xml
<CustomField>
    <fullName>JMC_FechaProspeccion__c</fullName>
    <label>Fecha de Prospección</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/JMC_FechaVencimiento__c.field-meta.xml
<CustomField>
    <fullName>JMC_FechaVencimiento__c</fullName>
    <label>Fecha de Vencimiento</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/JMC_Fraccionamiento__c.field-meta.xml
<CustomField>
    <fullName>JMC_Fraccionamiento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo para la asignación del fraccionamiento de interés en el que se creará el prospecto</description>
    <label>Fraccionamiento</label>
    <referenceTo>Fraccionamiento__c</referenceTo>
    <relationshipLabel>Prospectos (Fraccionamiento)</relationshipLabel>
    <relationshipName>Prospectos1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/JMC_FraccionamientoInterno__c.field-meta.xml
<CustomField>
    <fullName>JMC_FraccionamientoInterno__c</fullName>
    <label>FraccionamientoInterno</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ACACIAS</fullName>
            </value>
            <value>
                <fullName>ALBERI RESIDENCIAL</fullName>
            </value>
            <value>
                <fullName>ALBORETO RESIDENCIAL</fullName>
            </value>
            <value>
                <fullName>ALVENTO</fullName>
            </value>
            <value>
                <fullName>ARBOLADA</fullName>
            </value>
            <value>
                <fullName>ARCOS 7</fullName>
            </value>
            <value>
                <fullName>ARCOS DEL SOL</fullName>
            </value>
            <value>
                <fullName>ARCOS DEL SOL SECTOR ELITE</fullName>
            </value>
            <value>
                <fullName>ARRAYANES HABITAT II</fullName>
            </value>
            <value>
                <fullName>BARRIO ESTRELLA</fullName>
            </value>
            <value>
                <fullName>BELCANTO</fullName>
            </value>
            <value>
                <fullName>BELCANTO II</fullName>
            </value>
            <value>
                <fullName>BELLATERRA</fullName>
            </value>
            <value>
                <fullName>BELLA VISTA 2º SECTOR FOMERREY</fullName>
            </value>
            <value>
                <fullName>BELLA VISTA 3ER SECTOR</fullName>
            </value>
            <value>
                <fullName>BELLO AMANECER RESIDENCIAL</fullName>
            </value>
            <value>
                <fullName>BOSQUE BOREAL</fullName>
            </value>
            <value>
                <fullName>BOSQUE DE LOS NOGALES</fullName>
            </value>
            <value>
                <fullName>BOSQUE REAL</fullName>
            </value>
            <value>
                <fullName>BOSQUES DE CASTILLA</fullName>
            </value>
            <value>
                <fullName>BOSQUES DE LERMA</fullName>
            </value>
            <value>
                <fullName>BOSQUES DEL NEVADO</fullName>
            </value>
            <value>
                <fullName>BOSQUES DE SAN JUAN</fullName>
            </value>
            <value>
                <fullName>BOSQUES DE SAN JUAN 2</fullName>
            </value>
            <value>
                <fullName>BOSQUES DE SAN JUAN 3</fullName>
            </value>
            <value>
                <fullName>BOSQUES DE SAN JUAN IV</fullName>
            </value>
            <value>
                <fullName>BOSQUES DE SAN JUAN V</fullName>
            </value>
            <value>
                <fullName>BOSQUES LA HUASTECA</fullName>
            </value>
            <value>
                <fullName>BULGARIA 533 WELT</fullName>
            </value>
            <value>
                <fullName>CAMPANARIO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/JMC_Genero__c.field-meta.xml
<CustomField>
    <fullName>JMC_Genero__c</fullName>
    <description>Sexo del cliente</description>
    <label>Sexo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Masculino</fullName>
            </value>
            <value>
                <fullName>Femenino</fullName>
            </value>
            <value>
                <fullName>Indistinto</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/JMC_TipoCredito__c.field-meta.xml
<CustomField>
    <fullName>JMC_TipoCredito__c</fullName>
    <description>Catálogo con los tipos de crédito</description>
    <label>Tipo de Crédito</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BANSEFI</fullName>
            </value>
            <value>
                <fullName>BANJERCITO</fullName>
            </value>
            <value>
                <fullName>COFINAVIT</fullName>
            </value>
            <value>
                <fullName>CONTADO</fullName>
            </value>
            <value>
                <fullName>FOVISSSTE</fullName>
            </value>
            <value>
                <fullName>INFONAVIT</fullName>
            </value>
            <value>
                <fullName>ISSFAM</fullName>
            </value>
            <value>
                <fullName>ISSSTELEON</fullName>
            </value>
            <value>
                <fullName>PENSIONES</fullName>
            </value>
            <value>
                <fullName>SHF/BANCO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/JMC_WSResponseEx__c.field-meta.xml
<CustomField>
    <fullName>JMC_WSResponseEx__c</fullName>
    <defaultValue>false</defaultValue>
    <label>WS Response Exc</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/MsgResponseWS__c.field-meta.xml
<CustomField>
    <fullName>MsgResponseWS__c</fullName>
    <description>Campo para el monitoreo de la respuesta del servicio integrado con Siebel</description>
    <label>Mensaje Siebel</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/classes/Lead_tgr_Test.cls
@isTest
public class Lead_tgr_Test {
    static TestMethod void testMethod1() {
         Fraccionamiento__c f = new Fraccionamiento__c();
        f.Name = 'ALVENTO';
        insert f;
        
        Lead l = new Lead();
        l.JMC_WSResponseEx__c = false;
        l.JMC_FechaNacimiento__c = date.valueof('1980-03-21T00:00:00.000Z');
        l.JMC_FraccionamientoInterno__c = 'ALVENTO';
        l.JMC_Estado__c = 'Jalisco';
        l.JMC_FechaCaptura__c = date.valueof('2021-03-19T00:00:00.000Z');
        l.JMC_FechaProspeccion__c = date.valueof('2021-03-19T00:00:00.000Z');
        l.MsgResponseWS__c = 'Cuenta Creada Exitos'; 
        l.JMC_TipoCredito__c = 'CONTADO';
        l.Status = 'Envío MAS Comercial';
        l.JMC_Analisisinterno__c = 'Perfilado';
        l.JMC_EstatusLead__c = 'Perfilado';
        l.JMC_FechaVencimiento__c = date.valueof('2021-04-03T00:00:00.000Z');
        l.JMC_AsesorAsignado__c = 'TEST Asesor Asignado';
        l.FirstName = 'REGISTRO';
        /*l.MiddleName = 'SALES';*/
        l.LastName = 'NOVENTA';
        l.JMC_Genero__c = 'Masculino';
        l.Email = 'noventa@javer.com.mx';
        l.JMC_Fraccionamiento__c = f.Id;
        l.JMC_CanalVenta__c = 'Medios Digitales';
        l.JMC_SubCanalVenta__c = 'Facebook';
        l.JMC_Edad__c = 41;
        l.JMC_Perfilar__c = false;
        l.DeleteMailDuplicate__c = false;
        l.ID_CUENTA__c = '1-TEST1234';
        l.LeadSource = 'Prospección';
        l.JMC_IdDelete__c = false;
        l.Phone = '8111336699';
        l.MobilePhone = '8111336699';
        l.JMC_Re_Registro__c = false;
        l.JMC_UEN__c = 'UEN3 - JALISCO';
        l.JMC_FechaAsignacion__c = date.valueof('2021-03-19T00:00:00.000Z');
        l.JMC_ProspectadorMASComercial__c = userInfo.getUserId();       
        Test.startTest();
        insert l;        
        Test.stopTest();
    }
}