unpackaged/main/default/objects/Bitacora__c/Bitacora__c.object-meta.xml
<CustomObject>
    <label>Bitácora</label>
    <nameField>
        <displayFormat>L-{YY}{MM}{DD}-{0000}</displayFormat>
        <label>Nombre de Bitácora</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bitácora</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Bitacora__c/fields/Mensaje__c.field-meta.xml
<CustomField>
    <fullName>Mensaje__c</fullName>
    <label>Mensaje</label>
    <length>400</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Bitacora__c/fields/Operacion__c.field-meta.xml
<CustomField>
    <fullName>Operacion__c</fullName>
    <label>Operación</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Actualización</fullName>
            </value>
            <value>
                <fullName>Aprobación</fullName>
            </value>
            <value>
                <fullName>Creación</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Bitacora__c/fields/Origen__c.field-meta.xml
<CustomField>
    <fullName>Origen__c</fullName>
    <label>Origen</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Oracle</fullName>
            </value>
            <value>
                <fullName>Salesforce</fullName>
            </value>
            <value>
                <fullName>Sharepoint</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Bitacora__c/fields/ServicioWeb__c.field-meta.xml
<CustomField>
    <fullName>ServicioWeb__c</fullName>
    <label>Servicio Web</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Servicio de Solicitudes de Terrenos en Salesforce</fullName>
            </value>
            <value>
                <fullName>Servicio de Solicitudes de Terrenos en Sharepoint</fullName>
            </value>
            <value>
                <fullName>Servicio de Solicitudes de Trámites y Transferencias en Salesforce</fullName>
            </value>
            <value>
                <fullName>Servicio de Solicitudes de Trámites y Transferencias en Oracle</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Bitacora__c/fields/TipoDeError__c.field-meta.xml
<CustomField>
    <fullName>TipoDeError__c</fullName>
    <label>Tipo de Error</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Estado__c/Estado__c.object-meta.xml
<CustomObject>
    <label>Estado</label>
    <nameField>
        <label>Estado</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estados</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/FlujosDeAprobacion__c/FlujosDeAprobacion__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>FlujosDeAprobacion</label>
</CustomObject>

unpackaged/main/default/objects/FlujosDeAprobacion__c/fields/Javer_XMLNS__c.field-meta.xml
<CustomField>
    <fullName>Javer_XMLNS__c</fullName>
    <label>Javer XMLNS</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/FlujosDeAprobacion__c/fields/Manage_Approval_WS_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Manage_Approval_WS_Endpoint__c</fullName>
    <label>Manage Approval WS Endpoint</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/SolicitudesTramitesYTransferencias__c/SolicitudesTramitesYTransferencias__c.object-meta.xml
<CustomObject>
    <label>Solicitudes de Trámites y Transferencias</label>
    <nameField>
        <label>Numero de Solicitud</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Solicitudes de Trámites y Transferencias</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SolicitudesTramitesYTransferencias__c/fields/Aprobacion_Externa__c.field-meta.xml
<CustomField>
    <fullName>Aprobacion_Externa__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Aprobación Externa</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/SolicitudesTramitesYTransferencias__c/fields/Aprobador__c.field-meta.xml
<CustomField>
    <fullName>Aprobador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Aprobador</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SolicitudesTramitesTransferencias</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SolicitudesTramitesYTransferencias__c/fields/StatusInternoAprobacion__c.field-meta.xml
<CustomField>
    <fullName>StatusInternoAprobacion__c</fullName>
    <label>Status Interno Aprobacion</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/SolicitudTerreno__c/SolicitudTerreno__c.object-meta.xml
<CustomObject>
    <label>Solicitud de Terreno</label>
    <nameField>
        <label>Nombre de Solicitud de Terreno</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Solicitudes de Terreno</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SolicitudTerreno__c/fields/Aprobador__c.field-meta.xml
<CustomField>
    <fullName>Aprobador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Aprobador</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SolicituddeTerreno</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SolicitudTerreno__c/fields/StatusInternoAprobacion__c.field-meta.xml
<CustomField>
    <fullName>StatusInternoAprobacion__c</fullName>
    <description>El campo se actualizara cuando se Apruebe/Rechace una solicitud desde SalesForce.</description>
    <label>Status Interno Aprobacion</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/AprobacionTramitesTransferenciasWS.cls
public with sharing class AprobacionTramitesTransferenciasWS {
    
    public class customException extends Exception {}
    
    List<Bitacora__c> logs = new List<Bitacora__c>();
    public static Map<String,String> ValoresXML;
        
    @future(callout=true)
    public static void ActualizaTramitesTransferencias(String ApprovalType, String ApprovalId, String SourceSystem, String Status, String Approver, String FlowCheckpoint, String UEN, String SolicitudId, String TransactionID)
    {
        
        String mensaje;
        Integer numeroIntentos = 1;
        String requestDate;
        String javerNS;
        String wsEndpoint;
        
        ApprovalType = obtieneTipoRegistro(ApprovalType);
        while(numeroIntentos <= 3)
        {
            try
            {
                FlujosDeAprobacion__c settingsFlujos = FlujosDeAprobacion__c.getOrgDefaults();
                javerNs = settingsFlujos.Javer_XMLNS__c;
                wsEndpoint = settingsFlujos.Manage_Approval_WS_Endpoint__c;
                requestDate = String.valueOf(System.DateTime.now());
                System.Debug('requestDate: ' + requestDate);
                requestDate = requestDate.substring(0,10) + 'T' + requestDate.substring(11);
                
                String resp = '<soap:Envelope xmlns:soap=\"http://www.w3.org/2003/05/soap-envelope\" xmlns:typ=\"' + javerNS + '\">'
                +  '\n <soap:Header/>'
                +  '\n <soap:Body>'
                +  '\n <typ:UpdateApprovalStatusRq RequestDate=\"' +  requestDate + '\" SourceSystem=\"SALESFORCE_SOLCOM\" ApprovalType=\"' + ApprovalType + '\" Version=\"1.1\" TransactionID=\"'+ TransactionID +'\">'
                +  '\n <typ:ApprovalId>' + ApprovalId + '</typ:ApprovalId>'
                +  '\n <typ:SourceSystem>' + SourceSystem + '</typ:SourceSystem>'
                +  '\n <typ:Status>' + Status + '</typ:Status>'
                +  '\n <typ:TramiteAttributes UEN=\"'+ UEN+  '\" Approver=\"' + Approver + '\"/>'
                +  '\n <typ:TerrenoAttributes FlowCheckpoint=\"' + FlowCheckpoint + '\"/>'
                +  '\n </typ:UpdateApprovalStatusRq>'
                +  '\n </soap:Body>'
                +  '\n </soap:Envelope>';
    
    
                HttpRequest req = new HttpRequest();
                req.setEndpoint(wsEndpoint);
                req.setMethod('POST');
                req.setBody(resp);
                req.setHeader('Content-Type', 'application/soap+xml;charset=UTF-8;');
               
                
                req.setHeader('SOAPAction', 'UpdateApprovalStatusRequest');
                req.setHeader('Accept-Encoding', 'gzip,deflate');
                            
                req.setTimeout(120000);
                
                System.Debug('Resp: ' + resp);
                
                Http http = new Http();                                   
                HTTPResponse res = http.send(req);
    
                String respuesta = '<?xml version="1.0"?>'+res.getBody();
                System.Debug('Respuesta: ' + respuesta);

                if(respuesta.contains('404 Not Found'))
                {
                    throw new customException('404 Not Found');
                }
                else
                {
                    getXMLDocument(respuesta);
                }
                
                Bitacora__c log;
                if(valoresXML.get('Success') == 'true')
                {
                 log = new Bitacora__c(Fecha__c = Date.today(),
                                            Origen__c = 'Salesforce', 
                                            ServicioWeb__c = 'Servicio de Solicitudes de Trámites y Transferencias en Salesforce',
                                            Operacion__c =  'Aprobación',
                                            Estado__c = '200 (OK)');
                }
                else
                {
                    mensaje = valoresXML.get('ShortText') +  ' EBS_Id: ' + valoresXML.get('ESB_Id');
                 log = new Bitacora__c(Fecha__c = Date.today(),
                                            Origen__c = 'Salesforce', 
                                            ServicioWeb__c = 'Servicio de Solicitudes de Trámites y Transferencias en Salesforce',
                                            Operacion__c =  'Aprobación',
                                            Estado__c = '400 (ERROR)',
                                            Mensaje__c = mensaje);                  
                }
                                
                SolicitudesTramitesYTransferencias__c SolicitudesTramitesYTransferencias= [SELECT Id
                                        , StatusInternoAprobacion__c
                                        , Aprobacion_Externa__c
                                        , Aprobador__c
                                        FROM SolicitudesTramitesYTransferencias__c 
                                         WHERE Id = : SolicitudId
                                         LIMIT 1 ];
                if(SolicitudesTramitesYTransferencias != null)
                {
                    SolicitudesTramitesYTransferencias.StatusInternoAprobacion__c = null;
                    SolicitudesTramitesYTransferencias.Aprobacion_Externa__c = false;
                    SolicitudesTramitesYTransferencias.Aprobador__c = null;
                
                    try{
                      update SolicitudesTramitesYTransferencias; 
                    } catch(Exception e)
                    {
                        System.debug(System.LoggingLevel.ERROR, 'Error update SolicitudesTramitesYTransferencias__c: ' + e.getDmlMessage(0));
                    }
                }
                try {
                    insert log;
                } catch (Exception e) {
                    System.debug(System.LoggingLevel.ERROR, 'Error inserting webservice logs: ' + e.getDmlMessage(0));
                }
                numeroIntentos = 4;
            }
            catch(Exception ex)
            {
                System.debug(ex.getMessage());
                if(numeroIntentos < 3)
                {
                    numeroIntentos++;
                }
                else
                {
                    SolicitudesTramitesYTransferencias__c SolicitudesTramitesYTransferencias= [SELECT Id
                                            , StatusInternoAprobacion__c
                                            , Aprobacion_Externa__c
                                            , Aprobador__c
                                            FROM SolicitudesTramitesYTransferencias__c 
                                             WHERE Id = : SolicitudId
                                             LIMIT 1 ];
                    if(SolicitudesTramitesYTransferencias != null)
                    {
                        SolicitudesTramitesYTransferencias.StatusInternoAprobacion__c = null;
                        SolicitudesTramitesYTransferencias.Aprobacion_Externa__c = false;
                        SolicitudesTramitesYTransferencias.Aprobador__c = null;
                    
                        try{
                          update SolicitudesTramitesYTransferencias; 
                        } catch(Exception e)
                        {
                            System.debug(System.LoggingLevel.ERROR, 'Error update SolicitudTerreno__c: ' + e.getDmlMessage(0));
                        }
                    }
                    numeroIntentos = 4;
                    Bitacora__c log = new Bitacora__c(Fecha__c = Date.today(),
                                            Origen__c = 'Salesforce', 
                                            ServicioWeb__c = 'Servicio de Solicitudes de Trámites y Transferencias en Salesforce',
                                            Operacion__c =  'Aprobación',
                                            TipoDeError__c = 'COMUNICACION',
                                            Estado__c = '400 (ERROR)');
                                            
                                             
                    try {
                        insert log;
                    } catch (Exception e) {
                        System.debug(System.LoggingLevel.ERROR, 'Error inserting webservice logs: ' + e.getDmlMessage(0));
                    }
                }
                    
            }
        }
    }
    
    public static void getXMLDocument(String respuesta)
    {
        XmlStreamReader reader = new XmlStreamReader(respuesta);
        valoresXML = new Map<String,String>();
        while(reader.hasNext()) {
            if (reader.getEventType() == XmlTag.START_ELEMENT) {
                if ('UpdateApprovalStatusRs' == reader.getLocalName()) {
                    valoresXML.put('ResponseDate', reader.getAttributeValue(null, 'ResponseDate'));
                    valoresXML.put('Success', reader.getAttributeValue(null, 'Success'));
                    valoresXML.put('ESB_Id', reader.getAttributeValue(null, 'ESB_Id'));
                    
                    System.Debug('ResponseDate' + valoresXML.get('ResponseDate'));
                    System.Debug('Success' + valoresXML.get('Success'));
                    System.Debug('ESB_Id' + valoresXML.get('ESB_Id'));
                }else if('Error' == reader.getLocalName())
                {
                    valoresXML.put('Language', reader.getAttributeValue(null, 'Language'));
                    valoresXML.put('Type', reader.getAttributeValue(null, 'Type'));
                    valoresXML.put('ShortText', reader.getAttributeValue(null, 'ShortText'));
                    valoresXML.put('Code', reader.getAttributeValue(null, 'Code'));
                    
                    System.Debug('Language' + valoresXML.get('Language'));
                    System.Debug('Type' + valoresXML.get('Type'));
                    System.Debug('ShortText' + valoresXML.get('ShortText'));
                    System.Debug('Code' + valoresXML.get('Code'));
                }
            }
            reader.next();
        } 
    }
    
    public static String obtieneTipoRegistro(String Id)
    {
        
        RecordType recordType = [SELECT DeveloperName
                                 FROM RecordType
                                 WHERE Id = : Id
                                 LIMIT 1 ];
        if(recordType != null)
        {
            return  recordType.DeveloperName.toUpperCase();
        }
        else
        {
            return '';
        }
                                         
    }

    @future(callout=true)
    public static void ActualizaRegistro(String SolicitudTerrenoId)
    {
        SolicitudesTramitesYTransferencias__c SolicitudesTramitesYTransferencias= [SELECT Id
                                            , StatusInternoAprobacion__c
                                            , Aprobacion_Externa__c
                                            , Aprobador__c
                                            FROM SolicitudesTramitesYTransferencias__c 
                                             WHERE Id = : SolicitudTerrenoId
                                             LIMIT 1 ];
        if(SolicitudesTramitesYTransferencias != null)
        {
            SolicitudesTramitesYTransferencias.StatusInternoAprobacion__c = null;
            SolicitudesTramitesYTransferencias.Aprobacion_Externa__c = false;
            SolicitudesTramitesYTransferencias.Aprobador__c = null;
        
            try{
              update SolicitudesTramitesYTransferencias; 
            } catch(Exception e)
            {
                System.debug(System.LoggingLevel.ERROR, 'Error update SolicitudTerreno__c: ' + e.getDmlMessage(0));
            }
        }               
    }   
    
}