unpackaged/main/default/objects/Integracion_EBS_Aplicaciones__c/Integracion_EBS_Aplicaciones__c.object-meta.xml
<CustomObject>
    <label>Integración EBS Aplicaciones</label>
    <nameField>
        <displayFormat>IEBSA-{00000}</displayFormat>
        <label>Folio Integración Aplicación</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integraciones EBS Aplicaciones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Integracion_EBS_Aplicaciones__c/fields/Estatus_Integracion__c.field-meta.xml
<CustomField>
    <fullName>Estatus_Integracion__c</fullName>
    <label>Estatus Integración</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nuevo</fullName>
            </value>
            <value>
                <fullName>Enviado</fullName>
            </value>
            <value>
                <fullName>Integrado</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Reintentar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Integracion_EBS_Aplicaciones__c/fields/FechaAplicacion__c.field-meta.xml
<CustomField>
    <fullName>FechaAplicacion__c</fullName>
    <label>FechaAplicacion</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Integracion_EBS_Aplicaciones__c/fields/FechaContable__c.field-meta.xml
<CustomField>
    <fullName>FechaContable__c</fullName>
    <label>FechaContable</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Integracion_EBS_Aplicaciones__c/fields/IdAplicacionAr__c.field-meta.xml
<CustomField>
    <fullName>IdAplicacionAr__c</fullName>
    <externalId>true</externalId>
    <label>IdAplicacionAr</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Integracion_EBS_Aplicaciones__c/fields/IdClienteAr__c.field-meta.xml
<CustomField>
    <fullName>IdClienteAr__c</fullName>
    <label>IdClienteAr</label>
    <length>22</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Integracion_EBS_Aplicaciones__c/fields/IdFacturaAr__c.field-meta.xml
<CustomField>
    <fullName>IdFacturaAr__c</fullName>
    <label>IdFacturaAr</label>
    <length>22</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Integracion_EBS_Aplicaciones__c/fields/IdInterfaceCrm__c.field-meta.xml
<CustomField>
    <fullName>IdInterfaceCrm__c</fullName>
    <label>IdInterfaceCrm</label>
    <length>22</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Integracion_EBS_Aplicaciones__c/fields/IdNotaCredAr__c.field-meta.xml
<CustomField>
    <fullName>IdNotaCredAr__c</fullName>
    <label>IdNotaCredAr</label>
    <length>22</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Integracion_EBS_Aplicaciones__c/fields/IdProcesoAr__c.field-meta.xml
<CustomField>
    <fullName>IdProcesoAr__c</fullName>
    <label>IdProcesoAr</label>
    <length>22</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Integracion_EBS_Aplicaciones__c/fields/IdReciboAr__c.field-meta.xml
<CustomField>
    <fullName>IdReciboAr__c</fullName>
    <label>IdReciboAr</label>
    <length>22</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Integracion_EBS_Aplicaciones__c/fields/ImporteACuenta__c.field-meta.xml
<CustomField>
    <fullName>ImporteACuenta__c</fullName>
    <label>ImporteACuenta</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Integracion_EBS_Aplicaciones__c/fields/ImporteAnticipo__c.field-meta.xml
<CustomField>
    <fullName>ImporteAnticipo__c</fullName>
    <label>ImporteAnticipo</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Integracion_EBS_Aplicaciones__c/fields/ImporteAplicado__c.field-meta.xml
<CustomField>
    <fullName>ImporteAplicado__c</fullName>
    <label>ImporteAplicado</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Integracion_EBS_Aplicaciones__c/fields/ImporteFuncional__c.field-meta.xml
<CustomField>
    <fullName>ImporteFuncional__c</fullName>
    <label>ImporteFuncional</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Integracion_EBS_Aplicaciones__c/fields/ImporteNoAplicado__c.field-meta.xml
<CustomField>
    <fullName>ImporteNoAplicado__c</fullName>
    <label>ImporteNoAplicado</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Integracion_EBS_Aplicaciones__c/fields/ImporteNoIdentificado__c.field-meta.xml
<CustomField>
    <fullName>ImporteNoIdentificado__c</fullName>
    <label>ImporteNoIdentificado</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Integracion_EBS_Aplicaciones__c/fields/ImporteOriginal__c.field-meta.xml
<CustomField>
    <fullName>ImporteOriginal__c</fullName>
    <label>ImporteOriginal</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Integracion_EBS_Aplicaciones__c/fields/ImporteReclamo__c.field-meta.xml
<CustomField>
    <fullName>ImporteReclamo__c</fullName>
    <label>ImporteReclamo</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Integracion_EBS_Aplicaciones__c/fields/ImporteResto__c.field-meta.xml
<CustomField>
    <fullName>ImporteResto__c</fullName>
    <label>ImporteResto</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Integracion_EBS_Aplicaciones__c/fields/Mensaje_API__c.field-meta.xml
<CustomField>
    <fullName>Mensaje_API__c</fullName>
    <label>Mensaje API</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Integracion_EBS_Aplicaciones__c/fields/Request_EBS_hacia_CRM__c.field-meta.xml
<CustomField>
    <fullName>Request_EBS_hacia_CRM__c</fullName>
    <label>Request EBS hacia CRM</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Integracion_EBS_Aplicaciones__c/fields/Respuesta_API__c.field-meta.xml
<CustomField>
    <fullName>Respuesta_API__c</fullName>
    <label>Respuesta API</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/classes/IntegracionEBS_AplicacionERPtoSfCRM.cls
/**
 * @description       : 
 * @author            : Jose V. Aguilar Tlaseca
 * @group             : 
 * @last modified on  : 2023-09-25
 * @last modified by  : Jose V. Aguilar Tlaseca
**/
@RestResource(urlMapping='/EBS/Aplicaciones/*')
global with sharing class IntegracionEBS_AplicacionERPtoSfCRM
{
    @HttpPost
    global static ResponseWrapper doPost()
    {
        RestRequest req = RestContext.request;
        Blob body = req.requestBody;
        String requestString = body.toString();

        RequestWrapper reqW = (RequestWrapper)JSON.deserialize(requestString,RequestWrapper.class);

        List<Integracion_EBS_Aplicaciones__c> aplicaciones = new List<Integracion_EBS_Aplicaciones__c>();
        Integracion_EBS_Aplicaciones__c ieba;

        ResponseWrapper respW = new ResponseWrapper();
        
        try
        {
            //ieba = [SELECT Id, Name FROM Integracion_EBS_Aplicaciones__c WHERE Id =: reqW.IdInterfaceCrm];

            respW.MensajeApi = 'Creado en CRM';
            respW.RespuestaApi = '1';

            for(Aplicacion app : reqW.Aplicaciones)
            {
                ieba = new Integracion_EBS_Aplicaciones__c();

                ieba.IdAplicacionAr__c = app.IdAplicacionAr;
                ieba.IdClienteAr__c = app.IdClienteAr;
                ieba.IdFacturaAr__c = app.IdFacturaAr;
                ieba.IdNotaCredAr__c = app.IdNotaCredAr;
                ieba.IdProcesoAr__c = app.IdProcesoAr;
                ieba.IdReciboAr__c = app.IdReciboAr;
                ieba.IdInterfaceCrm__c = app.IdInterfaceCrm;

                ieba.FechaAplicacion__c = app.FechaAplicacion;
                ieba.FechaContable__c = app.FechaContable;
                ieba.ImporteACuenta__c = app.ImporteACuenta;
                ieba.ImporteAnticipo__c = app.ImporteAnticipo;
                ieba.ImporteAplicado__c = app.ImporteAplicado;
                ieba.ImporteFuncional__c = app.ImporteFuncional;
                ieba.ImporteNoAplicado__c = app.ImporteNoAplicado;
                ieba.ImporteNoIdentificado__c = app.ImporteNoIdentificado;
                ieba.ImporteOriginal__c = app.ImporteOriginal;
                ieba.ImporteReclamo__c = app.ImporteReclamo;
                ieba.ImporteResto__c = app.ImporteResto;

                ieba.Mensaje_API__c = app.MensajeApi;
                ieba.Respuesta_API__c = app.RespuestaApi;
                ieba.Request_EBS_hacia_CRM__c = requestString;
                ieba.Estatus_Integracion__c = app.RespuestaApi!='4' ? 'Integrado' : 'Error';

                ieba.Response_EBS_hacia_CRM__c = JSON.serialize(respW);

                aplicaciones.add(ieba);
            }

            insert aplicaciones;

            return respW;
        }
        catch (Exception e)
        {
            String msjApi = 'Error: ' + e.getMessage();
            respW.MensajeApi = msjApi.length() > 2000 ? msjApi.substring(0, 1999) : msjApi;
            respW.RespuestaApi = '-1';

            return respW;
        }

    }
    
    /*
    @HttpGet
    global static void doGet()
    {
        //ToDo
    }

    @HttpDelete
    global static void doDelete()
    {
        //ToDo
    }*/

    global class RequestWrapper
    {
        public List<Aplicacion> Aplicaciones;
        

    }

    global class ResponseWrapper
    {
        public String MensajeApi;
        public String RespuestaApi;
    }

    private class Aplicacion
    {
        public String IdAplicacionAr;
        public String IdClienteAr;
        public String IdFacturaAr;
        public String IdNotaCredAr;
        public String IdProcesoAr;
        public String IdReciboAr;
        
        public String IdInterfaceCrm;
        public Date FechaAplicacion;
        public Date FechaContable;

        public Decimal ImporteACuenta;
        public Decimal ImporteAnticipo;
        public Decimal ImporteAplicado;
        public Decimal ImporteFuncional;
        public Decimal ImporteNoAplicado;
        public Decimal ImporteNoIdentificado;
        public Decimal ImporteOriginal;
        public Decimal ImporteReclamo;
        public Decimal ImporteResto;

        public String MensajeApi;
        public String RespuestaApi;
    }
}