unpackaged/main/default/objects/Integracion_EBS_Pagos__c/Integracion_EBS_Pagos__c.object-meta.xml
<CustomObject>
    <label>Integración EBS Pagos</label>
    <nameField>
        <displayFormat>IEBSP-{00000}</displayFormat>
        <label>Folio Integración Pago</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integraciones EBS Pagos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Integracion_EBS_Pagos__c/fields/ConflictId__c.field-meta.xml
<CustomField>
    <fullName>ConflictId__c</fullName>
    <label>ConflictId</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Integracion_EBS_Pagos__c/fields/Created__c.field-meta.xml
<CustomField>
    <fullName>Created__c</fullName>
    <label>Created</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Integracion_EBS_Pagos__c/fields/DescTipoDocto__c.field-meta.xml
<CustomField>
    <fullName>DescTipoDocto__c</fullName>
    <label>DescTipoDocto</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Integracion_EBS_Pagos__c/fields/Estatus_Integracion__c.field-meta.xml
<CustomField>
    <fullName>Estatus_Integracion__c</fullName>
    <label>Estatus Integración</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Nuevo</fullName>
            </value>
            <value>
                <fullName>Enviado</fullName>
            </value>
            <value>
                <fullName>Integrado</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Integracion_EBS_Pagos__c/fields/FechaDeposito__c.field-meta.xml
<CustomField>
    <fullName>FechaDeposito__c</fullName>
    <label>FechaDeposito</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Integracion_EBS_Pagos__c/fields/FechaRecibo__c.field-meta.xml
<CustomField>
    <fullName>FechaRecibo__c</fullName>
    <label>FechaRecibo</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Integracion_EBS_Pagos__c/fields/IdEstadoVenta__c.field-meta.xml
<CustomField>
    <fullName>IdEstadoVenta__c</fullName>
    <label>IdEstadoVenta</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Integracion_EBS_Pagos__c/fields/IdReestructura__c.field-meta.xml
<CustomField>
    <fullName>IdReestructura__c</fullName>
    <label>IdReestructura</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Integracion_EBS_Pagos__c/fields/IdTipoDocto__c.field-meta.xml
<CustomField>
    <fullName>IdTipoDocto__c</fullName>
    <label>IdTipoDocto</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Integracion_EBS_Pagos__c/fields/ImporteRecibo__c.field-meta.xml
<CustomField>
    <fullName>ImporteRecibo__c</fullName>
    <label>ImporteRecibo</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Integracion_EBS_Pagos__c/fields/IndAnticipo__c.field-meta.xml
<CustomField>
    <fullName>IndAnticipo__c</fullName>
    <label>IndAnticipo</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Integracion_EBS_Pagos__c/fields/IndReversa__c.field-meta.xml
<CustomField>
    <fullName>IndReversa__c</fullName>
    <label>IndReversa</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Integracion_EBS_Pagos__c/fields/Metodo__c.field-meta.xml
<CustomField>
    <fullName>Metodo__c</fullName>
    <label>Metodo</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Integracion_EBS_Pagos__c/fields/ModifecationNum__c.field-meta.xml
<CustomField>
    <fullName>ModifecationNum__c</fullName>
    <label>ModifecationNum</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Integracion_EBS_Pagos__c/fields/NumRecibo__c.field-meta.xml
<CustomField>
    <fullName>NumRecibo__c</fullName>
    <label>NumRecibo</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Integracion_EBS_Pagos__c/fields/Request_EBS_hacia_CRM__c.field-meta.xml
<CustomField>
    <fullName>Request_EBS_hacia_CRM__c</fullName>
    <label>Request EBS hacia CRM</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Integracion_EBS_Pagos__c/fields/Requisicion__c.field-meta.xml
<CustomField>
    <fullName>Requisicion__c</fullName>
    <label>Requisicion</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Integracion_EBS_Pagos__c/fields/Response_EBS_hacia_CRM__c.field-meta.xml
<CustomField>
    <fullName>Response_EBS_hacia_CRM__c</fullName>
    <label>Response EBS hacia CRM</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Integracion_EBS_Pagos__c/fields/Respuesta_API__c.field-meta.xml
<CustomField>
    <fullName>Respuesta_API__c</fullName>
    <label>Respuesta API</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Integracion_EBS_Pagos__c/fields/SesionCajaId__c.field-meta.xml
<CustomField>
    <fullName>SesionCajaId__c</fullName>
    <label>SesionCajaId</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Integracion_EBS_Pagos__c/fields/TipoPago__c.field-meta.xml
<CustomField>
    <fullName>TipoPago__c</fullName>
    <label>TipoPago</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/IntegracionEBS_PagoSfCRMtoEBSResp.cls
/**
 * @description       : Servicio PAGOS Rest Entrada - De EBS a Salesforce, RESPONSE llamado de SF->EBS
 * @author            : Héctor Medina
 * @group             : 
 * @last modified on  : 2023-09-29
 * @last modified by  : Héctor Medina
**/

@RestResource(urlMapping='/EBS/Pagos/*')
global with sharing class IntegracionEBS_PagoSfCRMtoEBSResp
{
    @HttpPost
    global static ResponseWrapper doPost()
    {
        RestRequest req = RestContext.request;
        Blob body = req.requestBody;
        String requestString = body.toString();

        RequestWrapper reqW = (RequestWrapper)JSON.deserialize(requestString,RequestWrapper.class);

        Integracion_EBS_Pagos__c iebc;

        ResponseWrapper respW = new ResponseWrapper();
        
        try
        {
            iebc = [SELECT Id, Name FROM Integracion_EBS_Pagos__c WHERE Id =: reqW.IdInterfaseCrm];

            iebc.IdClienteAr__c = reqW.IdClienteAr;
            iebc.Mensaje_API__c = reqW.MensajeApi;
            iebc.Respuesta_API__c = reqW.RespuestaApi;
            iebc.Request_EBS_hacia_CRM__c = requestString;
            if (reqW.RespuestaApi=='5') { // Exito
                iebc.Estatus_Integracion__c = 'Integrado';
            } else {
                if (reqW.RespuestaApi=='4') { //Error
                    iebc.Estatus_Integracion__c = 'Error';
                }
            }
            // iebc.Estatus_Integracion__c = 'Integrado';
            respW.MensajeApi = 'Actualizado en CRM';
            respW.RespuestaApi = '0';
            iebc.Response_EBS_hacia_CRM__c = JSON.serialize(respW);

            iebc.Created__c = reqw.Created;
            //iebc.CreatedBy__c = reqw.CreatedBy;
            /* *** Esto no va en este servicio, hay otro servicio para ello: ***
            iebc.ModifecationNum__c = reqw.ModifecationNum;
            iebc.ConflictId__c = reqw.ConflictId;
            iebc.FechaContable__c = reqw.FechaContable;
            iebc.FechaDeposito__c = reqw.FechaDeposito;
            iebc.FechaRecibo__c = reqw.FechaRecibo;
            iebc.IdCobranzaMultiple__c = integer.valueof(reqw.IdCobranzaMultiple);
            iebc.IdEstadoVenta__c = decimal.valueof(reqw.IdEstadoVenta);
            iebc.IdInterface__c = reqw.IdInterface;
            iebc.IdReestructura__c = reqw.IdReestructura;
            iebc.IdSector__c = reqw.IdSector;
            iebc.IdTipoDocto__c = reqw.IdTipoDocto;
            iebc.ImporteRecibo__c = decimal.valueof(reqw.ImporteRecibo);
            iebc.IndAnticipo__c = reqw.IndAnticipo;
            iebc.IndReversa__c = reqw.IndReversa;
            iebc.RetryCount__c = reqw.RetryCount;
            iebc.DescTipoDocto__c = reqw.DescTipoDocto;
            iebc.IdMoneda__c = reqw.IdMoneda;
            iebc.IdProcesoAr__c = reqw.IdProcesoAr;
            iebc.IdReciboCrm__c = reqw.IdReciboCrm;
            iebc.Metodo__c = reqw.Metodo;
            iebc.NumRecibo__c = reqw.NumRecibo;
            iebc.Referencia__c = reqw.Referencia;
            iebc.Requisicion__c = reqw.Requisicion;
            iebc.SesionCajaId__c = reqw.SesionCajaId;
            iebc.TipoPago__c = reqw.TipoPago;
            */
            // iebc.LastUdp__c = reqw.LastUdp;
            // iebc.LastUdpBy__c = reqw.LastUdpBy;

            update iebc;

            return respW;
        }
        catch (Exception e)
        {
            String msjApi = 'Error: ' + e.getMessage();
            respW.MensajeApi = msjApi;//.substring(0, 1999);
            respW.RespuestaApi = '-1';

            return respW;
        }

    }
    
    /*
    @HttpGet
    global static void doGet()
    {
        //ToDo
    }

    @HttpDelete
    global static void doDelete()
    {
        //ToDo
    }*/

    global class RequestWrapper
    {
        public String RespuestaApi;
        public String MensajeApi;
        public String IdReciboAr;
        public String IdClienteAr;
        public String IdInterfaseCrm;
        public String RowId;

        public Date Created;
        public String CreatedBy;
        public Integer ModifecationNum;
        public String ConflictId;
        public Date FechaContable;
        public Date FechaDeposito;
        public Date FechaRecibo;
        public String IdCobranzaMultiple;
        public String IdEstadoVenta;
        public Integer IdInterface;
        public Integer IdReestructura;
        public Integer IdSector;
        public Integer IdTipoDocto;
        public String ImporteRecibo;
        public Integer IndAnticipo;
        public Integer IndReversa;
        public Integer RetryCount;
        public String DescTipoDocto;
        public String IdMoneda;
        public String IdProcesoAr;
        public String IdReciboCrm;
        public String Metodo;
        public String NumRecibo;
        public String Referencia;
        public String Requisicion;
        public String SesionCajaId;
        public String TipoPago;
        public Date LastUdp;
        public String LastUdpBy;
    }

    global class ResponseWrapper
    {
        public String MensajeApi;
        public String RespuestaApi;
    }
}