unpackaged/main/default/objects/Fraccionamiento__c/Fraccionamiento__c.object-meta.xml
<CustomObject>
    <label>Fraccionamiento</label>
    <nameField>
        <label>Nombre de Fraccionamiento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fraccionamientos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Fraccionamiento__c/fields/Id_Mas_Comercial__c.field-meta.xml
<CustomField>
    <fullName>Id_Mas_Comercial__c</fullName>
    <label>Id Mas Comercial</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Fraccionamiento__c/fields/Prototipo__c.field-meta.xml
<CustomField>
    <fullName>Prototipo__c</fullName>
    <label>Prototipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prototipo 1</fullName>
            </value>
            <value>
                <fullName>Prototipo 2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Modelos__c/Modelos__c.object-meta.xml
<CustomObject>
    <label>Modelo</label>
    <nameField>
        <label>Modelo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modelos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Modelos__c/fields/ActivoMD__c.field-meta.xml
<CustomField>
    <fullName>ActivoMD__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Modelos__c/fields/Id_Mas_ComercialMD__c.field-meta.xml
<CustomField>
    <fullName>Id_Mas_ComercialMD__c</fullName>
    <label>Id Mas Comercial</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Prototipo__c/Prototipo__c.object-meta.xml
<CustomObject>
    <label>Prototipo</label>
    <nameField>
        <label>Prototipo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prototipos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Prototipo__c/fields/Fraccionamiento__c.field-meta.xml
<CustomField>
    <fullName>Fraccionamiento__c</fullName>
    <label>Fraccionamiento</label>
    <referenceTo>Fraccionamiento__c</referenceTo>
    <relationshipLabel>Prototipos</relationshipLabel>
    <relationshipName>Prototipos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Prototipo__c/fields/Id_Mas_Comercial__c.field-meta.xml
<CustomField>
    <fullName>Id_Mas_Comercial__c</fullName>
    <label>Id Mas Comercial</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/User/fields/Id_Mas_Comercial__c.field-meta.xml
<CustomField>
    <fullName>Id_Mas_Comercial__c</fullName>
    <label>Id Mas Comercial</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/User/fields/User_Mas_Comercial__c.field-meta.xml
<CustomField>
    <fullName>User_Mas_Comercial__c</fullName>
    <inlineHelpText>No borrar es LOGIN de mas comercial</inlineHelpText>
    <label>User Mas Comercial</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/ImportarPrototiposWS.cls
public class ImportarPrototiposWS {
	public List<Prototipo__c> listaPrototipos {get;set;}
    public Integer min {get;set;}
    public Integer max {get;set;}
    public ImportarPrototiposWS(){
        
    }
    
	public PageReference consultar(){
        PageReference page = ApexPages.currentPage();

        listaPrototipos = new List<Prototipo__c>();
        User usuario = [SELECT Id, Name, Id_Mas_Comercial__c, User_Mas_Comercial__c FROM User WHERE Id =: UserInfo.getUserId() LIMIT 1];
        List<Prototipo__c> listAux = [SELECT ID, Name,Id_Mas_Comercial__c,Fraccionamiento__c FROM Prototipo__c LIMIT 48000];
        List<Modelos__c> listModelos = [SELECT ID, Name, Id_Mas_ComercialMd__c FROM Modelos__c LIMIT 48000];
        Set<Id> resultIds = (new Map<Id,SObject>(listAux)).keySet();
        
        List<Modelos__c> modIns = new List<Modelos__c>();
        
        esbJaverComCatprototipos.CatPrototiposPort wsPort =  new esbJaverComCatprototipos.CatPrototiposPort();
        wsPort.timeout_x = 120000;
        
        esbJaverComCommonPrototipos.PrototipoListType respuesta = wsPort.GetPrototipos(usuario.User_Mas_Comercial__c,'SALESFORCE','');
        
        esbJaverComCommonPrototipos.PrototipoType[] prototipos = respuesta.Prototipo;
         if(max == 0){
            max = prototipos.size(); 
        }
        if(prototipos != null){
            try{
            for(Integer i = min; i < max; i++){
                esbJaverComCommonPrototipos.PrototipoType prototipo = prototipos[i];
                
                Modelos__c mod = new Modelos__c();
                
                mod.Id_Mas_ComercialMD__c = '' + prototipo.ID;
                mod.Name = prototipo.Name;
                if(prototipo.Estatus == '1'){
                    
                    mod.ActivoMD__c = true;
                }else{
                    
                    mod.ActivoMD__c = false;
                }
                for(Modelos__c pr : listModelos){
                    if(pr.Id_Mas_ComercialMD__c != null){
                        if((('' + pr.Id_Mas_ComercialMD__c) == ''+prototipo.ID) && pr.Id_Mas_ComercialMD__c != ''){
                            mod.Id = pr.Id;
                        }
                    }
                }

                modIns.add(mod);
            }
            }catch(Exception e){
                
            }
        }
        upsert modIns;
        //upsert listaPrototipos;
        return page;
    }
    public void method(){
        Integer i = 0;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
    }
}