unpackaged/main/default/objects/Fraccionamiento__c/Fraccionamiento__c.object-meta.xml
<CustomObject>
    <label>Fraccionamiento</label>
    <nameField>
        <label>Nombre de Fraccionamiento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fraccionamientos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Fraccionamiento__c/fields/Plaza__c.field-meta.xml
<CustomField>
    <fullName>Plaza__c</fullName>
    <label>Plaza</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Fraccionamiento__c/fields/Segmentacion__c.field-meta.xml
<CustomField>
    <fullName>Segmentacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Segmentación de Fraccionamiento</label>
    <referenceTo>Segmento_de_Fraccionamiento__c</referenceTo>
    <relationshipLabel>Fraccionamientos</relationshipLabel>
    <relationshipName>Fraccionamientos</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Plaza__c/Plaza__c.object-meta.xml
<CustomObject>
    <label>Plaza</label>
    <nameField>
        <label>Nombre de Plaza</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plazas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/SegmentoFraccionamientos.cls
public class SegmentoFraccionamientos {
	@AuraEnabled
    public static Object getFracc(){
        List<SelectFracc> sfList = new List<SelectFracc>();
        for(Fraccionamiento__c f: [SELECT Id,Name,Plaza__c FROM Fraccionamiento__c WHERE Segmentacion__c = null ORDER BY Plaza__c ASC]){
            SelectFracc sf = new SelectFracc();
            sf.check = false;
            sf.frac = f;
            sfList.add(sf);
        }
        return sfList;
    }
    
    @AuraEnabled
    public static String saveFraccs(List<String> fracs, String segId){
        try{
            List<Fraccionamiento__c> fracsToUpdate = new List<Fraccionamiento__c>();
            for(String s: fracs){
                fracsToUpdate.add(new Fraccionamiento__c(Id = s,Segmentacion__c = segId));
            }
            update fracsToUpdate;
            return 'Success';
        }
        catch(Exception e){
            return 'ERROR: '+e.getMessage();
        }
    }
    
    public class SelectFracc{
        @AuraEnabled public Fraccionamiento__c frac;
        @AuraEnabled public Boolean check;
    }
}