unpackaged/main/default/objects/Fraccionamiento__c/Fraccionamiento__c.object-meta.xml
<CustomObject>
    <label>Fraccionamiento</label>
    <nameField>
        <label>Nombre de Fraccionamiento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fraccionamientos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Promocion__c/Promocion__c.object-meta.xml
<CustomObject>
    <label>Material de Apoyo</label>
    <nameField>
        <displayFormat>MA{000000}</displayFormat>
        <label>Material de Apoyo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Materiales de Apoyo</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Promocion__c/fields/Fecha_Final__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Final__c</fullName>
    <label>Fecha Final</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Promocion__c/fields/Fraccionamiento__c.field-meta.xml
<CustomField>
    <fullName>Fraccionamiento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fraccionamiento</label>
    <referenceTo>Fraccionamiento__c</referenceTo>
    <relationshipName>Promociones</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/User/fields/FRACCIONAMIENTOS__c.field-meta.xml
<CustomField>
    <fullName>FRACCIONAMIENTOS__c</fullName>
    <label>FRACCIONAMIENTOS</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ACACIAS</fullName>
            </value>
            <value>
                <fullName>ACACIAS II</fullName>
            </value>
            <value>
                <fullName>ALBERI RESIDENCIAL</fullName>
            </value>
            <value>
                <fullName>ALVENTO</fullName>
            </value>
            <value>
                <fullName>ARBOLADA</fullName>
            </value>
            <value>
                <fullName>BOSQUE REAL</fullName>
            </value>
            <value>
                <fullName>BOSQUES DEL NEVADO</fullName>
            </value>
            <value>
                <fullName>MAGNOLIAS IV</fullName>
            </value>
            <value>
                <fullName>MISION DE LOS ANGELES 1ER SECTOR ARCANGELES</fullName>
            </value>
            <value>
                <fullName>MURIEL RESIDENCIAL</fullName>
            </value>
            <value>
                <fullName>PASEO SAN JUNIPERO</fullName>
            </value>
            <value>
                <fullName>PASEOS DEL SUR</fullName>
            </value>
            <value>
                <fullName>PRIVADA BELTERRA</fullName>
            </value>
            <value>
                <fullName>PRIVADAS CARANDAY</fullName>
            </value>
            <value>
                <fullName>PRIVALIA AMBIENTA</fullName>
            </value>
            <value>
                <fullName>TODOS</fullName>
            </value>
            <value>
                <fullName>VALLE DE LINCOLN SECTOR MINAS</fullName>
            </value>
            <value>
                <fullName>VALLE DE SANTA ELENA</fullName>
            </value>
            <value>
                <fullName>VALLE DE TEJEDA II</fullName>
            </value>
            <value>
                <fullName>VALLE SANTA ISABEL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/PromocionTriggerHandler.cls
public class PromocionTriggerHandler {
    public static void handleAfterInsert(List <Promocion__c> newList) {
        List<String> setFracc = new List<String> ();
        String sFraccs = '';
        Date Fecha;
        Set <String> setFraccs = new Set <String>();
        for (Promocion__c p : newList) {
            Fecha = p.Fecha_Final__c;
            setFraccs.add(p.Fraccionamiento__c);
        }
        for (Fraccionamiento__c f : [SELECT Id, Name FROM Fraccionamiento__c WHERE Id in :setFraccs]) {
            sFraccs = '\''+ f.Name + '\'';
        }

        // Quitar la primer ,
        //sFraccs = sFraccs.substring(2, sFraccs.length() - 1);
        system.debug ('Fraccs: '+sFraccs);
        String stringQry = 'SELECT Id, Email, Name from User WHERE Fraccionamientos__c IN ('+sFraccs+')';
        system.debug('stringQry: '+stringQry);

        // Buscar Usuarios que tengan ese fraccionamiento
        List <User> userSendEmail = Database.Query(stringQry);
        system.debug ('*** userSendEmail: '+userSendEmail);

        for (User usr : userSendEmail){
            String body='<p>Estimado '+usr.Name+':</p><p>Un nuevo material de apoyo ha sido creado y está disponible en el sitio para su consulta y descarga.</p> <p>Consulte la fecha de vigencia que se encuentra en el PDF descargable.</p><br><p>Saludos,</p><p>Equipo Javer</p>';
            EnviaNotificacionNuevoMatierial.Envia(usr.Email, '*TEST* Material de Apoyo Javer', body);
        }
    }
}