unpackaged/main/default/objects/Fraccionamiento__c/Fraccionamiento__c.object-meta.xml
<CustomObject>
    <label>Fraccionamiento</label>
    <nameField>
        <label>Nombre de Fraccionamiento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fraccionamientos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Fraccionamiento__c/fields/Plaza__c.field-meta.xml
<CustomField>
    <fullName>Plaza__c</fullName>
    <label>Plaza</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Activo__c.field-meta.xml
<CustomField>
    <fullName>Activo__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Beneficio__c.field-meta.xml
<CustomField>
    <fullName>Beneficio__c</fullName>
    <label>% Beneficio</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Codigo_de_Producto__c.field-meta.xml
<CustomField>
    <fullName>Codigo_de_Producto__c</fullName>
    <displayFormat>PRD-{00000}</displayFormat>
    <label>Código de Producto</label>
    <type>AutoNumber</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Codigo_de_Producto_Javer__c.field-meta.xml
<CustomField>
    <fullName>Codigo_de_Producto_Javer__c</fullName>
    <label>Id Vivienda</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Direccion__c.field-meta.xml
<CustomField>
    <fullName>Direccion__c</fullName>
    <label>Dirección</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Id_Externo__c.field-meta.xml
<CustomField>
    <fullName>Id_Externo__c</fullName>
    <externalId>true</externalId>
    <label>Id_Externo</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Inactivo__c.field-meta.xml
<CustomField>
    <fullName>Inactivo__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Inactivo</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/IVA__c.field-meta.xml
<CustomField>
    <fullName>IVA__c</fullName>
    <label>% IVA</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Lote__c.field-meta.xml
<CustomField>
    <fullName>Lote__c</fullName>
    <label>Lote</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Manzana__c.field-meta.xml
<CustomField>
    <fullName>Manzana__c</fullName>
    <label>Manzana</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <defaultValue>IF($RecordType.Name == &#39;Productos Genéricos&#39;, &#39;OFICIAL&#39;, &#39;&#39;)</defaultValue>
    <label>Marca</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Num_Interior__c.field-meta.xml
<CustomField>
    <fullName>Num_Interior__c</fullName>
    <label>Num Interior</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Num_Interno__c.field-meta.xml
<CustomField>
    <fullName>Num_Interno__c</fullName>
    <label>Num Interno</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Plaza__c.field-meta.xml
<CustomField>
    <fullName>Plaza__c</fullName>
    <label>Plaza</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Queretaro</fullName>
            </value>
            <value>
                <fullName>Nuevo Leon</fullName>
            </value>
            <value>
                <fullName>Estado de Mexico</fullName>
            </value>
            <value>
                <fullName>Jalisco</fullName>
            </value>
            <value>
                <fullName>Aguascalientes</fullName>
            </value>
            <value>
                <fullName>Distrito Federal</fullName>
            </value>
            <value>
                <fullName>San Luis Potosi</fullName>
            </value>
            <value>
                <fullName>Quintana Roo</fullName>
            </value>
            <value>
                <fullName>Guanajuato</fullName>
            </value>
            <value>
                <fullName>Tamaulipas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Precio_de_Venta_Sugerido__c.field-meta.xml
<CustomField>
    <fullName>Precio_de_Venta_Sugerido__c</fullName>
    <formula>Precio_de_Compra_con_Impuestos__c * 1.2</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Precio de Venta Sugerido</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Precio_Total__c.field-meta.xml
<CustomField>
    <fullName>Precio_Total__c</fullName>
    <formula>Precio_Venta__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Precio Total PV</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Precio_Venta__c.field-meta.xml
<CustomField>
    <fullName>Precio_Venta__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Precio Venta al Cliente</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Proveedor__c.field-meta.xml
<CustomField>
    <fullName>Proveedor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Proveedor</label>
    <referenceTo>Proveedor__c</referenceTo>
    <relationshipLabel>Productos</relationshipLabel>
    <relationshipName>Productos</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Tipo_de_Producto__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Producto__c</fullName>
    <label>Tipo de Producto</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Casa Muestra</fullName>
            </value>
            <value>
                <fullName>Complementos</fullName>
            </value>
            <value>
                <fullName>Otros Gastos</fullName>
            </value>
            <value>
                <fullName>Paquete</fullName>
            </value>
            <value>
                <fullName>Promoción de Venta</fullName>
            </value>
            <value>
                <fullName>Promoción en Especie</fullName>
            </value>
            <value>
                <fullName>Regalo de Marketing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Unidad_Privada__c.field-meta.xml
<CustomField>
    <fullName>Unidad_Privada__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Unidad Privada</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Proveedor__c/Proveedor__c.object-meta.xml
<CustomObject>
    <label>Proveedor</label>
    <nameField>
        <label>Proveedor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proveedores</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Proveedor__c/fields/Direccion__c.field-meta.xml
<CustomField>
    <fullName>Direccion__c</fullName>
    <label>Direccion</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Proveedor__c/fields/Plaza__c.field-meta.xml
<CustomField>
    <fullName>Plaza__c</fullName>
    <label>Plaza</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Aguascalientes</fullName>
                <label>AGUASCALIENTES</label>
            </value>
            <value>
                <fullName>Distrito Federal</fullName>
                <isActive>false</isActive>
                <label>Distrito Federal</label>
            </value>
            <value>
                <fullName>Estado de Mexico</fullName>
                <label>ESTADO DE MEXICO</label>
            </value>
            <value>
                <fullName>Guanajuato</fullName>
                <isActive>false</isActive>
                <label>Guanajuato</label>
            </value>
            <value>
                <fullName>Jalisco</fullName>
                <label>JALISCO</label>
            </value>
            <value>
                <fullName>Nuevo Leon</fullName>
                <label>NUEVO LEON</label>
            </value>
            <value>
                <fullName>Queretaro</fullName>
                <label>QUERETARO</label>
            </value>
            <value>
                <fullName>Quintana Roo</fullName>
                <label>QUINTANA ROO</label>
            </value>
            <value>
                <fullName>San Luis Potosi</fullName>
                <isActive>false</isActive>
                <label>San Luis Potosi</label>
            </value>
            <value>
                <fullName>Tamaulipas</fullName>
                <label>TAMAULIPAS</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Proveedor__c/fields/Producto__c.field-meta.xml
<CustomField>
    <fullName>Producto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Proveedores</relationshipLabel>
    <relationshipName>Proveedores</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Relacion_Precio_Proveedor__c/Relacion_Precio_Proveedor__c.object-meta.xml
<CustomObject>
    <label>Proveedor</label>
    <nameField>
        <displayFormat>RPP-{000000}</displayFormat>
        <label>Folio</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proveedores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Relacion_Precio_Proveedor__c/fields/Producto__c.field-meta.xml
<CustomField>
    <fullName>Producto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Relacion_Productos_Proveedores</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Relacion_Precio_Proveedor__c/fields/Proveedor__c.field-meta.xml
<CustomField>
    <fullName>Proveedor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proveedor</label>
    <referenceTo>Proveedor__c</referenceTo>
    <relationshipName>Relacion_Productos_Proveedores</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Relacion_Producto_Fraccionamiento__c/Relacion_Producto_Fraccionamiento__c.object-meta.xml
<CustomObject>
    <label>Fraccionamiento</label>
    <nameField>
        <label>Nombre de la Relacion</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fraccionamientos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Relacion_Producto_Fraccionamiento__c/fields/Fraccionamiento__c.field-meta.xml
<CustomField>
    <fullName>Fraccionamiento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fraccionamiento</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Fraccionamiento__c.Plaza_Filtro__c</field>
            <operation>contains</operation>
            <valueField>$Source.Plaza_Filtro__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Fraccionamiento__c</referenceTo>
    <relationshipName>Relaci_n_Productos_Fraccionamientos</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Relacion_Producto_Fraccionamiento__c/fields/Producto__c.field-meta.xml
<CustomField>
    <fullName>Producto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Relaci_n_Productos_Fraccionamientos</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Relacion_Producto_Fraccionamiento__c/fields/Relacion_Producto_Plaza_Fraccionamiento__c.field-meta.xml
<CustomField>
    <fullName>Relacion_Producto_Plaza_Fraccionamiento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plaza Relacionada</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.Producto__c</field>
            <operation>notEqual</operation>
            <valueField>Relacion_Producto_Plaza__c.Producto__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Relacion_Producto_Plaza__c</referenceTo>
    <relationshipName>Relacion_Productos_Fraccionamientos</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Relacion_Producto_Plaza__c/Relacion_Producto_Plaza__c.object-meta.xml
<CustomObject>
    <label>Plaza</label>
    <nameField>
        <label>Nombre de la Relacion</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plazas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Relacion_Producto_Plaza__c/fields/Plaza__c.field-meta.xml
<CustomField>
    <fullName>Plaza__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plaza</label>
    <referenceTo>Plaza__c</referenceTo>
    <relationshipName>Relaci_n_Productos_Plazas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Relacion_Producto_Plaza__c/fields/Producto__c.field-meta.xml
<CustomField>
    <fullName>Producto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Relaci_n_Productos_Plazas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/CPPT_Clonar_producto.cls
public class CPPT_Clonar_producto {
    
    public Id idProd {get; set;}
    
    
    //constructor para obtener el registro del producto
    public CPPT_Clonar_producto(ApexPages.StandardController controller) {
        idProd = controller.getId();
    }
    
    public PageReference clonarProducto() {
        System.debug('+++Id Producto: ' + idProd);
        String idNuevoProd = creaProducto(idProd);
        PageReference pageRef = new PageReference('/'+idNuevoProd);
        pageRef.setRedirect(true);
        return pageRef;
    }
    
    public static String creaProducto(String idProd){
        
        //Se obtienen los registros relacionados
        List<Relacion_Precio_Proveedor__c> rsProveedores = [SELECT Id, Proveedor__c  FROM Relacion_Precio_Proveedor__c WHERE Producto__c =: idProd];
        List<Relacion_Producto_Plaza__c> rsPlazas = [SELECT Id, Plaza__c  FROM Relacion_Producto_Plaza__c WHERE Producto__c =: idProd];
        Set<Id> idFraccionamientos = new Set<Id>();
        for(Relacion_Producto_Plaza__c rpf : rsPlazas){
            idFraccionamientos.add(rpf.Id);
        }
        List<Relacion_Producto_Fraccionamiento__c> rsFraccionamientos = [SELECT Id, Fraccionamiento__c  FROM Relacion_Producto_Fraccionamiento__c WHERE Relacion_Producto_Plaza_Fraccionamiento__c IN: idFraccionamientos];
        
        Product2 prod = [SELECT Id, Name,
                         Activo__c, IsActive, Beneficio__c, Codigo_de_Producto__c, ProductCode, Description, Direccion__c, Family, Codigo_de_Producto_Javer__c, ExternalId,
                         Id_Externo__c, Inactivo__c, IVA__c, Lote__c, Manzana__c, Marca__c, Num_Interior__c, Num_Interno__c, Plaza__c, Precio_de_Compra__c, Precio_de_Venta_Sugerido__c,
                         Precio_Total__c, Precio_Venta__c, StockKeepingUnit, Tipo_de_Producto__c, RecordTypeId, QuantityUnitOfMeasure, Unidad_Privada__c, DisplayUrl, Vigencia_Hasta__c
                         FROM Product2 WHERE Id =: idProd];
        
        Product2 nuevoProd = new Product2();
        nuevoProd.Name = prod.Name + '_copia';
        nuevoProd.Activo__c = prod.Activo__c;
        nuevoProd.IsActive = prod.IsActive;
        nuevoProd.Beneficio__c = prod.Beneficio__c;
        nuevoProd.ProductCode = prod.ProductCode;
        nuevoProd.Description= prod.Description;
        nuevoProd.Direccion__c = prod.Direccion__c;
        nuevoProd.Family = prod.Family;
        nuevoProd.Codigo_de_Producto_Javer__c = prod.Codigo_de_Producto_Javer__c;
        nuevoProd.ExternalId = prod.ExternalId;
        nuevoProd.Id_Externo__c = prod.Id_Externo__c;
        nuevoProd.Inactivo__c = prod.Inactivo__c;
        nuevoProd.IVA__c = prod.IVA__c;
        nuevoProd.Lote__c = prod.Lote__c;
        nuevoProd.Manzana__c = prod.Manzana__c;
        nuevoProd.Marca__c = prod.Marca__c;
        nuevoProd.Num_Interior__c = prod.Num_Interior__c;
        nuevoProd.Num_Interno__c = prod.Num_Interno__c;
        nuevoProd.Plaza__c = prod.Plaza__c;
        nuevoProd.Precio_de_Compra__c = prod.Precio_de_Compra__c;
        nuevoProd.Precio_Venta__c = prod.Precio_Venta__c;
        nuevoProd.StockKeepingUnit = prod.StockKeepingUnit;
        nuevoProd.Tipo_de_Producto__c = prod.Tipo_de_Producto__c;
        nuevoProd.RecordTypeId = prod.RecordTypeId;
        nuevoProd.QuantityUnitOfMeasure = prod.QuantityUnitOfMeasure;
        nuevoProd.Unidad_Privada__c = prod.Unidad_Privada__c;
        nuevoProd.DisplayUrl = prod.DisplayUrl;
        nuevoProd.Vigencia_Hasta__c = prod.Vigencia_Hasta__c;
        
        
        insert nuevoProd;
        System.debug('Se inserta nuevo producto');
        
        List<Relacion_Precio_Proveedor__c> proveedoresAsignar = new List<Relacion_Precio_Proveedor__c>();
        for(Relacion_Precio_Proveedor__c idProv: rsProveedores){
            Relacion_Precio_Proveedor__c newProv = New Relacion_Precio_Proveedor__c();
            newProv.Proveedor__c = idProv.Proveedor__c;
            newProv.Producto__c = nuevoProd.Id;
            proveedoresAsignar.add(newProv);
        }
        System.debug('proveedoresAsignar: ' + proveedoresAsignar);
       
        
        List<Relacion_Producto_Plaza__c> plazasAsignar = new List<Relacion_Producto_Plaza__c>();
        for(Relacion_Producto_Plaza__c idPlaza: rsPlazas){
            Relacion_Producto_Plaza__c newPlaza = New Relacion_Producto_Plaza__c();
            newPlaza.Plaza__c = idPlaza.Plaza__c;
            newPlaza.Producto__c = nuevoProd.Id;
            plazasAsignar.add(newPlaza);
        }
        System.debug('plazasAsignar: ' + plazasAsignar);
        
        /*List<Relacion_Producto_Fraccionamiento__c> fraccionamientosAsignar = new List<Relacion_Producto_Fraccionamiento__c>();
        for(Relacion_Producto_Fraccionamiento__c idFracc: rsFraccionamientos){
            Relacion_Producto_Fraccionamiento__c newFrac = New Relacion_Producto_Fraccionamiento__c();
            newFrac.Fraccionamiento__c = idFracc.Fraccionamiento__c;
            newFrac.Producto__c = nuevoProd.Id;
            fraccionamientosAsignar.add(newFrac);
        }
        System.debug('fraccionamientosAsignar: ' + fraccionamientosAsignar);*/
        
        insert proveedoresAsignar;
        System.debug('Se asignan proveedores a nuevo producto ');
        insert plazasAsignar; 
        System.debug('Se asignan plazas a nuevo producto ');
        /*insert fraccionamientosAsignar; 
        System.debug('Se asignan fraccionamientos a nuevo producto ');*/
        
        return nuevoProd.Id;
    }
}