unpackaged/main/default/objects/Fraccionamiento__c/Fraccionamiento__c.object-meta.xml
<CustomObject>
    <label>Fraccionamiento</label>
    <nameField>
        <label>Nombre de Fraccionamiento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fraccionamientos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Fraccionamiento__c/fields/Activo_frac__c.field-meta.xml
<CustomField>
    <fullName>Activo_frac__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Fraccionamiento__c/fields/Estado_fracc__c.field-meta.xml
<CustomField>
    <fullName>Estado_fracc__c</fullName>
    <label>Estado</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Fraccionamiento__c/fields/Id_Mas_Comercial__c.field-meta.xml
<CustomField>
    <fullName>Id_Mas_Comercial__c</fullName>
    <label>Id Mas Comercial</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Fraccionamiento__c/fields/Muni_fracc__c.field-meta.xml
<CustomField>
    <fullName>Muni_fracc__c</fullName>
    <label>Municipio</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Fraccionamiento__c/fields/Plaza__c.field-meta.xml
<CustomField>
    <fullName>Plaza__c</fullName>
    <label>Plaza</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Fraccionamiento__c/fields/UEN__c.field-meta.xml
<CustomField>
    <fullName>UEN__c</fullName>
    <label>UEN</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Plaza__c/Plaza__c.object-meta.xml
<CustomObject>
    <label>Plaza</label>
    <nameField>
        <label>Nombre de Plaza</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plazas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/FraccionamientoWSController.cls
public class FraccionamientoWSController{
    
    public List<Fraccionamiento__c> fraccionamientosTabla {get;set;}
    
        public FraccionamientoWSController(){
        
    }
    
    public PageReference consultar(){
        fraccionamientosTabla = new List<Fraccionamiento__c>();
        List<Id> idsActivos = new List<Id>();
        List<Fraccionamiento__c> todosF = [SELECT Id, Name, Id_Mas_Comercial__c, Estado_fracc__c,Muni_fracc__c,Activo_frac__c FROM Fraccionamiento__c];
        
        PageReference page = ApexPages.currentPage();
        esbJaverComCatfraccionamientos.CatFraccionamientosPort wsPro 
            = new esbJaverComCatfraccionamientos.CatFraccionamientosPort();
        wsPro.timeout_x = 120000; 
        
        esbJaverComCatfraccionamientosTypes.Fraccionamientos_element fraccionamientos = new esbJaverComCatfraccionamientosTypes.Fraccionamientos_element();
         esbJaverComCommonFraccionamiento.FraccionamientoListType ifsdj = wsPro.GetFraccionamientos('true','true','true');
        system.debug('FEEF: '+ ifsdj);
        try{ 
            fraccionamientos = wsPro.GetFraccionamientosWithLocation(true,true,true);
        }catch(Exception e){
            ApexPages.addMessage(new ApexPages.Message
                                 (Apexpages.Severity.ERROR, 
			'Se ha agotado el tiempo de respuesta, favor de intentarlo de nuevo.')); 
        }
        
        System.debug('FRACCS: ' + fraccionamientos);
        
        List<esbJaverComCatfraccionamientosTypes.Fraccionamiento_element> fraccs = fraccionamientos.Fraccionamiento;
        
        for(esbJaverComCatfraccionamientosTypes.Fraccionamiento_element fracc : fraccs){
            Fraccionamiento__c fraccionamiento = new Fraccionamiento__c();
            fraccionamiento.Name = fracc.Name;
            fraccionamiento.Id_Mas_Comercial__c = fracc.ID;
            fraccionamiento.Estado_fracc__c = fracc.Location.Estado.Name;
            fraccionamiento.Muni_fracc__c = fracc.Location.Municipio.Name;
            fraccionamiento.UEN__c = fracc.Location.UEN;
            fraccionamiento.Plaza__c =fracc.Location.UEN + ' - ' +fracc.Location.Estado.Name; 
            //fraccionamiento.Activo_frac__c = Boolean.valueOf(fracc.Status);
            
            
            
            //fraccionamiento.Activo_frac__c = fracc.
            boolean exists = false;
            
            for(Fraccionamiento__c fa : todosF){
                if(fa.Id_Mas_Comercial__c == fraccionamiento.Id_Mas_Comercial__c){
                    fraccionamiento.Id = fa.Id;
                    exists = true;
                }else{
                    fa.Activo_frac__c = false;
                }
            }
            
            if(fracc.Status == '1'){
              fraccionamiento.Activo_frac__c = true;  
            }else{
              fraccionamiento.Activo_frac__c = false;
            }
            
            fraccionamientosTabla.add(fraccionamiento);
        }
        upsert fraccionamientosTabla;
        return page;
    }
    public void method(){
        Integer i = 0;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
        i = 1;
    }
}