unpackaged/main/default/objects/Fraccionamiento__c/Fraccionamiento__c.object-meta.xml
<CustomObject>
    <label>Fraccionamiento</label>
    <nameField>
        <label>Nombre de Fraccionamiento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fraccionamientos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Fraccionamiento__c/fields/Estado_fracc__c.field-meta.xml
<CustomField>
    <fullName>Estado_fracc__c</fullName>
    <label>Estado</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Fraccionamiento__c/fields/Plaza__c.field-meta.xml
<CustomField>
    <fullName>Plaza__c</fullName>
    <label>Plaza</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Fraccionamiento__c/fields/Prototipo__c.field-meta.xml
<CustomField>
    <fullName>Prototipo__c</fullName>
    <label>Prototipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prototipo 1</fullName>
            </value>
            <value>
                <fullName>Prototipo 2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Pricebook2/fields/Fraccionamiento__c.field-meta.xml
<CustomField>
    <fullName>Fraccionamiento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fraccionamiento</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 AND (2 OR 3)</booleanFilter>
        <filterItems>
            <field>Fraccionamiento__c.Activo_frac__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$User.Fraccionamiento_autorizado__c</field>
            <operation>contains</operation>
            <valueField>Fraccionamiento__c.Name</valueField>
        </filterItems>
        <filterItems>
            <field>$User.FraccionamientoAutorizados__c</field>
            <operation>contains</operation>
            <valueField>Fraccionamiento__c.Name</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Fraccionamiento__c</referenceTo>
    <relationshipLabel>Listas de precios</relationshipLabel>
    <relationshipName>Listas_de_precios</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Pricebook2/fields/Precio_superficie_excedente__c.field-meta.xml
<CustomField>
    <fullName>Precio_superficie_excedente__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Precio superficie excedente</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Pricebook2/fields/Precio_Total__c.field-meta.xml
<CustomField>
    <fullName>Precio_Total__c</fullName>
    <label>Precio Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Pricebook2/fields/Prototipo__c.field-meta.xml
<CustomField>
    <fullName>Prototipo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prototipo</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Prototipo__c.Fraccionamiento__c</field>
            <operation>equals</operation>
            <valueField>$Source.Fraccionamiento__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Prototipo__c</referenceTo>
    <relationshipLabel>Listas de precios</relationshipLabel>
    <relationshipName>Listas_de_precios</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Pricebook2/fields/Superficie_excedente__c.field-meta.xml
<CustomField>
    <fullName>Superficie_excedente__c</fullName>
    <label>Superficie excedente</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Pricebook2/fields/Tipo_Lista__c.field-meta.xml
<CustomField>
    <fullName>Tipo_Lista__c</fullName>
    <formula>$RecordType.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tipo Lista</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Pricebook2/fields/Vigente_Desde__c.field-meta.xml
<CustomField>
    <fullName>Vigente_Desde__c</fullName>
    <label>Vigente Desde</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Pricebook2/fields/Vigente_Hasta__c.field-meta.xml
<CustomField>
    <fullName>Vigente_Hasta__c</fullName>
    <label>Vigente Hasta</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Pricebook2/recordTypes/Vivienda.recordType-meta.xml
<RecordType>
    <fullName>Vivienda</fullName>
    <active>true</active>
    <label>Vivienda</label>
</RecordType>

unpackaged/main/default/objects/Product2/fields/Plaza__c.field-meta.xml
<CustomField>
    <fullName>Plaza__c</fullName>
    <label>Plaza</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Queretaro</fullName>
            </value>
            <value>
                <fullName>Nuevo Leon</fullName>
            </value>
            <value>
                <fullName>Estado de Mexico</fullName>
            </value>
            <value>
                <fullName>Jalisco</fullName>
            </value>
            <value>
                <fullName>Aguascalientes</fullName>
            </value>
            <value>
                <fullName>Distrito Federal</fullName>
            </value>
            <value>
                <fullName>San Luis Potosi</fullName>
            </value>
            <value>
                <fullName>Quintana Roo</fullName>
            </value>
            <value>
                <fullName>Guanajuato</fullName>
            </value>
            <value>
                <fullName>Tamaulipas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Precio_Total__c.field-meta.xml
<CustomField>
    <fullName>Precio_Total__c</fullName>
    <formula>Precio_Venta__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Precio Total PV</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Precio_Venta__c.field-meta.xml
<CustomField>
    <fullName>Precio_Venta__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Precio Venta al Cliente</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Proveedor__c.field-meta.xml
<CustomField>
    <fullName>Proveedor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Proveedor</label>
    <referenceTo>Proveedor__c</referenceTo>
    <relationshipLabel>Productos</relationshipLabel>
    <relationshipName>Productos</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Vivienda__c.field-meta.xml
<CustomField>
    <fullName>Vivienda__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vivienda</label>
    <referenceTo>Vivienda__c</referenceTo>
    <relationshipLabel>Productos</relationshipLabel>
    <relationshipName>Productos</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Product2/recordTypes/Vivienda.recordType-meta.xml
<RecordType>
    <fullName>Vivienda</fullName>
    <active>true</active>
    <label>Vivienda</label>
</RecordType>

unpackaged/main/default/objects/Prototipo__c/Prototipo__c.object-meta.xml
<CustomObject>
    <label>Prototipo</label>
    <nameField>
        <label>Prototipo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prototipos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Prototipo__c/fields/Fraccionamiento__c.field-meta.xml
<CustomField>
    <fullName>Fraccionamiento__c</fullName>
    <label>Fraccionamiento</label>
    <referenceTo>Fraccionamiento__c</referenceTo>
    <relationshipLabel>Prototipos</relationshipLabel>
    <relationshipName>Prototipos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Proveedor__c/Proveedor__c.object-meta.xml
<CustomObject>
    <label>Proveedor</label>
    <nameField>
        <label>Proveedor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proveedores</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Proveedor__c/fields/Plaza__c.field-meta.xml
<CustomField>
    <fullName>Plaza__c</fullName>
    <label>Plaza</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Aguascalientes</fullName>
                <label>AGUASCALIENTES</label>
            </value>
            <value>
                <fullName>Distrito Federal</fullName>
                <isActive>false</isActive>
                <label>Distrito Federal</label>
            </value>
            <value>
                <fullName>Estado de Mexico</fullName>
                <label>ESTADO DE MEXICO</label>
            </value>
            <value>
                <fullName>Guanajuato</fullName>
                <isActive>false</isActive>
                <label>Guanajuato</label>
            </value>
            <value>
                <fullName>Jalisco</fullName>
                <label>JALISCO</label>
            </value>
            <value>
                <fullName>Nuevo Leon</fullName>
                <label>NUEVO LEON</label>
            </value>
            <value>
                <fullName>Queretaro</fullName>
                <label>QUERETARO</label>
            </value>
            <value>
                <fullName>Quintana Roo</fullName>
                <label>QUINTANA ROO</label>
            </value>
            <value>
                <fullName>San Luis Potosi</fullName>
                <isActive>false</isActive>
                <label>San Luis Potosi</label>
            </value>
            <value>
                <fullName>Tamaulipas</fullName>
                <label>TAMAULIPAS</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Relacion_Precio_Proveedor__c/Relacion_Precio_Proveedor__c.object-meta.xml
<CustomObject>
    <label>Proveedor</label>
    <nameField>
        <displayFormat>RPP-{000000}</displayFormat>
        <label>Folio</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proveedores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Relacion_Precio_Proveedor__c/fields/Proveedor__c.field-meta.xml
<CustomField>
    <fullName>Proveedor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proveedor</label>
    <referenceTo>Proveedor__c</referenceTo>
    <relationshipName>Relacion_Productos_Proveedores</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Relacion_Producto_Fraccionamiento__c/Relacion_Producto_Fraccionamiento__c.object-meta.xml
<CustomObject>
    <label>Fraccionamiento</label>
    <nameField>
        <label>Nombre de la Relacion</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fraccionamientos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Relacion_Producto_Fraccionamiento__c/fields/Fraccionamiento__c.field-meta.xml
<CustomField>
    <fullName>Fraccionamiento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fraccionamiento</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Fraccionamiento__c.Plaza_Filtro__c</field>
            <operation>contains</operation>
            <valueField>$Source.Plaza_Filtro__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Fraccionamiento__c</referenceTo>
    <relationshipName>Relaci_n_Productos_Fraccionamientos</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Relacion_Producto_Plaza__c/Relacion_Producto_Plaza__c.object-meta.xml
<CustomObject>
    <label>Plaza</label>
    <nameField>
        <label>Nombre de la Relacion</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plazas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Relacion_Producto_Plaza__c/fields/Plaza__c.field-meta.xml
<CustomField>
    <fullName>Plaza__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plaza</label>
    <referenceTo>Plaza__c</referenceTo>
    <relationshipName>Relaci_n_Productos_Plazas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Vivienda__c/Vivienda__c.object-meta.xml
<CustomObject>
    <label>Vivienda</label>
    <nameField>
        <label>Vivienda</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Viviendas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Vivienda__c/fields/Fraccionamiento__c.field-meta.xml
<CustomField>
    <fullName>Fraccionamiento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fraccionamiento</label>
    <referenceTo>Fraccionamiento__c</referenceTo>
    <relationshipLabel>Viviendas</relationshipLabel>
    <relationshipName>Viviendas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Vivienda__c/fields/Precio_Total__c.field-meta.xml
<CustomField>
    <fullName>Precio_Total__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Precio Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Vivienda__c/fields/Prototipo__c.field-meta.xml
<CustomField>
    <fullName>Prototipo__c</fullName>
    <label>Prototipo</label>
    <referenceTo>Prototipo__c</referenceTo>
    <relationshipLabel>Viviendas</relationshipLabel>
    <relationshipName>Viviendas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Vivienda__c/fields/Superficie_Excedente__c.field-meta.xml
<CustomField>
    <fullName>Superficie_Excedente__c</fullName>
    <label>Superficie Excedente</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/ViviendaTrigger_Handler.cls
public class ViviendaTrigger_Handler {
    public static void inVivienda(List<Vivienda__c> newVivienda){
        string PROVEEDOR_JAVER = system.label.PROVEEDOR_JAVER;
        list<Product2> prods = new list<Product2>();            
        List<PricebookEntry> pbeList = new List<PricebookEntry>();
        list<Relacion_Precio_Proveedor__c>provList = new list<Relacion_Precio_Proveedor__c>();
        list<Relacion_Producto_Plaza__c> rppList = new list<Relacion_Producto_Plaza__c>();
        list<Relacion_Producto_Fraccionamiento__c> rpfList = new list<Relacion_Producto_Fraccionamiento__c>();
        Map<String, Id> plazaMap = new Map<String, Id>();
        Map<Id, Fraccionamiento__c> fraccionamientoEstadoMap = new Map<Id, Fraccionamiento__c>();
        Map<String, List<Pricebook2>> pbMap= new Map<String, List<Pricebook2>>();
        Map<Integer,PricebookEntry> prodMap = new Map<Integer,PricebookEntry>();
        Map<Integer,Product2> prodMap1 = new Map<Integer,Product2>();
        Map<String, Id> rPlazaMap = new Map<String,Id>();
        list<string>Estados = new list<string>();  set<id>fracViv = new set<id>(); set<id>ProtoViv = new set<id>();
        
        Id viviendaTR = Schema.SObjectType.Product2.getRecordTypeInfosByName().get('Vivienda').getRecordTypeId();
        // Llenar Sets fracViv y ProtoViv (Fraccionamientos y Prototipos Unicos)
        for(Vivienda__c vv : newVivienda){
            if(vv.Fraccionamiento__c != null){
                fracViv.add(vv.Fraccionamiento__c);  
            }
            if(vv.Prototipo__c != null){
                ProtoViv.add(vv.Prototipo__c);
            }
        }
        
        // Crea mapa de Fraccionamientos Estado
        List<Fraccionamiento__c>  fracc = [SELECT Id, Estado_fracc__c , (Select Id, name from Viviendas__r) FROM Fraccionamiento__c WHERE Id IN :fracViv];
        if(fracc != null && fracc.size()>0){
            for(Fraccionamiento__c f : fracc){
                Estados.add(f.Estado_fracc__c);
                if(f.Viviendas__r != null && f.Viviendas__r.size()>0){
                    for(Vivienda__c v :f.Viviendas__r ){
                        fraccionamientoEstadoMap.put(v.id,f);
                    }
                }
            }
        }
        // obtiene los pricebooks de fraccionamiento/prototipo
        Map<Id, Pricebook2> pricebookMap =  new Map<Id, Pricebook2>([select id, name,Fraccionamiento__r.Estado_fracc__c, Fraccionamiento__c, Prototipo__c, Vigente_Desde__c,Vigente_Hasta__c, IsActive, Precio_superficie_excedente__c from PriceBook2
                                                                     where Fraccionamiento__c IN :fracViv AND Prototipo__c IN :ProtoViv AND IsActive = true 
                                                                     AND Vigente_Desde__c <= : Date.today() AND Vigente_Hasta__c >= : Date.today() 
                                                                     AND Tipo_Lista__c = 'Vivienda']);
        system.debug('pricebookMap'+pricebookMap);
        if(pricebookMap != null && pricebookMap.size()>0){
            for(Pricebook2 pb : pricebookMap.values()){
                if(!pbMap.containsKey(pb.Fraccionamiento__c+'_' +pb.Prototipo__c)){
                    pbMap.put(pb.Fraccionamiento__c+'_' +pb.Prototipo__c, new List<Pricebook2>() );
                }
                pbMap.get(pb.Fraccionamiento__c+'_' +pb.Prototipo__c).add(pb);
            }
        }
        List<PriceBook2> priceBooks = [SELECT Id FROM Pricebook2 WHERE Name = 'Standard Price Book' ORDER BY IsStandard DESC]; 
        Integer count = 1;
        for(Vivienda__c vv : newVivienda){
            Product2 prodVivienda = new Product2();
            prodVivienda.Name = vv.Name;
            prodVivienda.Description = 'Producto Vivienda';
            prodVivienda.Precio_Venta__c = vv.Precio_Total__c; //HMF 7/25 ERA: vv.Precio_Unitario__c;
            prodVivienda.RecordTypeId = viviendaTR;
            prodVivienda.Vivienda__c = vv.Id;
            prodVivienda.Activo__c = true;
            prodVivienda.IsActive = true; 
          //  prodVivienda.Marca__c = 'OFICIAL';
           // prodVivienda.Tipo_de_Producto__c   =   'Casa Muestra';
            prods.add(prodVivienda);
            prodMap1.put(count, prodVivienda);
            
            // Relaciona pricebook al pricebook de la vivienda
            PricebookEntry pbe = new PricebookEntry();
            if(pbMap != null && pbMap.size()>0){
                pbe.Pricebook2Id = pbMap.get(vv.Fraccionamiento__c+'_'+vv.Prototipo__c)[0].id;
            }
            pbe.UnitPrice = vv.Precio_Unitario__c;
            // Cálculo de Total M2 Excedentes se guarda en Pricebook
            try {
                if (vv.Superficie_Excedente__c != null && pbMap.get(vv.Fraccionamiento__c+'_'+vv.Prototipo__c)[0].Precio_superficie_excedente__c != null) {
                    pbe.Total_M2_Excedentes__c = vv.Superficie_Excedente__c * pbMap.get(vv.Fraccionamiento__c+'_'+vv.Prototipo__c)[0].Precio_superficie_excedente__c;
                }
            } catch (Exception e) {
                pbe.Total_M2_Excedentes__c = 0;
            }
            pbe.IsActive = true;
            pbe.UseStandardPrice = false;
            // if (pbe.Pricebook2Id != null) {
                // Solo agregarlo a PricebookEntry si tiene Pricebook2Id
                pbeList.add(pbe); 
                prodMap.put(count, pbe);
                count++;    
            // }
        }
        system.debug('prodMap1'+prodMap1.values()[0]);
        Database.insert(prodMap1.values()) ;
        String idProveedor ;
        list<Plaza__c> PlazaViviendas = [SELECt Id, Name FROM Plaza__c WHERE Name IN: Estados];
        if(PlazaViviendas != null && PlazaViviendas.size()>0){
            for (Plaza__c plaza : plazaViviendas) {
                plazaMap.put(plaza.Name, plaza.Id);
            }
        }
        List<Proveedor__c> proveedorlist = [SELECT Id, Name FROM Proveedor__c WHERE Name =: PROVEEDOR_JAVER LIMIT 1];
        if(proveedorlist != null && proveedorlist.size()>0){
            idProveedor = proveedorlist[0].Id;
        }
        if(prodMap1.values() != null && prodMap1.values().size()>0){
            for(Product2 p : prodMap1.values()){
                Relacion_Precio_Proveedor__c prov = new Relacion_Precio_Proveedor__c();
                prov.Producto__c = p.Id;
                prov.Proveedor__c = idProveedor;
                provList.add(prov);
                if(PlazaViviendas != null && PlazaViviendas.size()>0){
                    for(Plaza__c plaza : PlazaViviendas){
                        if(plazaMap.containsKey(fraccionamientoEstadoMap.get(p.Vivienda__c).Estado_fracc__c)){
                            Relacion_Producto_Plaza__c rpp = new Relacion_Producto_Plaza__c();
                            rpp.Producto__c = p.Id;
                            rpp.Plaza__c = plazaMap.get(fraccionamientoEstadoMap.get(p.Vivienda__c).Estado_fracc__c);
                            rpp.Name = 'Nuevo';
                            rppList.add(rpp);
                        }
                    }
                }
            }
        }
        if(provList != null && provList.size()>0){
            insert provList;
        }
        if(rppList != null && rppList.size()>0){
            insert rppList;
        }
        if(rppList != null && rppList.size()>0){
            for(Relacion_Producto_Plaza__c rp :rppList){
                rPlazaMap.put(rp.Producto__c, rp.Id);
            }
        }
        for(Product2 p : prodMap1.values()){
            Relacion_Producto_Fraccionamiento__c rpf = new Relacion_Producto_Fraccionamiento__c();
            rpf.Producto__c = p.Id;
            rpf.Fraccionamiento__c = fraccionamientoEstadoMap.get(p.Vivienda__c).Id;
            if(rPlazaMap != null && rPlazaMap.size()>0){
                rpf.Relacion_Producto_Plaza_Fraccionamiento__c = rPlazaMap.get(p.Id);
            }
            rpf.Name = 'Nuevo';
            rpfList.add(rpf);
        }
        insert rpfList;
        for(Integer c: prodMap.keyset()){
            prodMap.get(c).Product2Id = prodMap1.get(c).Id;
        }
        insert prodMap.values();
    }
}