unpackaged/main/default/objects/Fraccionamiento__c/Fraccionamiento__c.object-meta.xml
<CustomObject>
    <label>Fraccionamiento</label>
    <nameField>
        <label>Nombre de Fraccionamiento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fraccionamientos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Fraccionamiento__c/fields/Activo_frac__c.field-meta.xml
<CustomField>
    <fullName>Activo_frac__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Fraccionamiento__c/fields/Estado_fracc__c.field-meta.xml
<CustomField>
    <fullName>Estado_fracc__c</fullName>
    <label>Estado</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Fraccionamiento__c/fields/Id_Mas_Comercial__c.field-meta.xml
<CustomField>
    <fullName>Id_Mas_Comercial__c</fullName>
    <label>Id Mas Comercial</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Fraccionamiento__c/fields/Muni_fracc__c.field-meta.xml
<CustomField>
    <fullName>Muni_fracc__c</fullName>
    <label>Municipio</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Fraccionamiento__c/fields/Plaza__c.field-meta.xml
<CustomField>
    <fullName>Plaza__c</fullName>
    <label>Plaza</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Fraccionamiento__c/fields/Plaza_Relacionada__c.field-meta.xml
<CustomField>
    <fullName>Plaza_Relacionada__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plaza</label>
    <referenceTo>Plaza__c</referenceTo>
    <relationshipLabel>Fraccionamientos</relationshipLabel>
    <relationshipName>Fraccionamientos</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Fraccionamiento__c/fields/Segmento__c.field-meta.xml
<CustomField>
    <fullName>Segmento__c</fullName>
    <label>Segmento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Residencial</fullName>
            </value>
            <value>
                <fullName>Media</fullName>
            </value>
            <value>
                <fullName>Interés Social</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Fraccionamiento__c/fields/Webfracc_frac__c.field-meta.xml
<CustomField>
    <fullName>Webfracc_frac__c</fullName>
    <label>Web Fraccionamiento</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Codigo_Producto_Original__c.field-meta.xml
<CustomField>
    <fullName>Codigo_Producto_Original__c</fullName>
    <label>Código Producto Original</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Numero_Filtro__c.field-meta.xml
<CustomField>
    <fullName>Numero_Filtro__c</fullName>
    <description>Se crea este campo para poder filtrar en diferentes campos de búsqueda de otros objetos relacionados a producto</description>
    <label>Número Filtro</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Plaza__c.field-meta.xml
<CustomField>
    <fullName>Plaza__c</fullName>
    <label>Plaza</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Queretaro</fullName>
            </value>
            <value>
                <fullName>Nuevo Leon</fullName>
            </value>
            <value>
                <fullName>Estado de Mexico</fullName>
            </value>
            <value>
                <fullName>Jalisco</fullName>
            </value>
            <value>
                <fullName>Aguascalientes</fullName>
            </value>
            <value>
                <fullName>Distrito Federal</fullName>
            </value>
            <value>
                <fullName>San Luis Potosi</fullName>
            </value>
            <value>
                <fullName>Quintana Roo</fullName>
            </value>
            <value>
                <fullName>Guanajuato</fullName>
            </value>
            <value>
                <fullName>Tamaulipas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Precio_Venta__c.field-meta.xml
<CustomField>
    <fullName>Precio_Venta__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Precio Venta al Cliente</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Producto_Original__c.field-meta.xml
<CustomField>
    <fullName>Producto_Original__c</fullName>
    <label>Producto Original</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Proveedor__c.field-meta.xml
<CustomField>
    <fullName>Proveedor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Proveedor</label>
    <referenceTo>Proveedor__c</referenceTo>
    <relationshipLabel>Productos</relationshipLabel>
    <relationshipName>Productos</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Prototipo__c/Prototipo__c.object-meta.xml
<CustomObject>
    <label>Prototipo</label>
    <nameField>
        <label>Prototipo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prototipos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Prototipo__c/fields/Fraccionamiento__c.field-meta.xml
<CustomField>
    <fullName>Fraccionamiento__c</fullName>
    <label>Fraccionamiento</label>
    <referenceTo>Fraccionamiento__c</referenceTo>
    <relationshipLabel>Prototipos</relationshipLabel>
    <relationshipName>Prototipos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Prototipo__c/fields/Id_Mas_Comercial__c.field-meta.xml
<CustomField>
    <fullName>Id_Mas_Comercial__c</fullName>
    <label>Id Mas Comercial</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Proveedor__c/Proveedor__c.object-meta.xml
<CustomObject>
    <label>Proveedor</label>
    <nameField>
        <label>Proveedor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proveedores</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Proveedor__c/fields/Contacto__c.field-meta.xml
<CustomField>
    <fullName>Contacto__c</fullName>
    <label>Contacto</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Proveedor__c/fields/Correo__c.field-meta.xml
<CustomField>
    <fullName>Correo__c</fullName>
    <label>Correo</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Proveedor__c/fields/Nombre_Comercial__c.field-meta.xml
<CustomField>
    <fullName>Nombre_Comercial__c</fullName>
    <label>Nombre Comercial</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Proveedor__c/fields/Plaza__c.field-meta.xml
<CustomField>
    <fullName>Plaza__c</fullName>
    <label>Plaza</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Aguascalientes</fullName>
                <label>AGUASCALIENTES</label>
            </value>
            <value>
                <fullName>Distrito Federal</fullName>
                <isActive>false</isActive>
                <label>Distrito Federal</label>
            </value>
            <value>
                <fullName>Estado de Mexico</fullName>
                <label>ESTADO DE MEXICO</label>
            </value>
            <value>
                <fullName>Guanajuato</fullName>
                <isActive>false</isActive>
                <label>Guanajuato</label>
            </value>
            <value>
                <fullName>Jalisco</fullName>
                <label>JALISCO</label>
            </value>
            <value>
                <fullName>Nuevo Leon</fullName>
                <label>NUEVO LEON</label>
            </value>
            <value>
                <fullName>Queretaro</fullName>
                <label>QUERETARO</label>
            </value>
            <value>
                <fullName>Quintana Roo</fullName>
                <label>QUINTANA ROO</label>
            </value>
            <value>
                <fullName>San Luis Potosi</fullName>
                <isActive>false</isActive>
                <label>San Luis Potosi</label>
            </value>
            <value>
                <fullName>Tamaulipas</fullName>
                <label>TAMAULIPAS</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Proveedor__c/fields/Producto__c.field-meta.xml
<CustomField>
    <fullName>Producto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Proveedores</relationshipLabel>
    <relationshipName>Proveedores</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Proveedor__c/fields/Rfc__c.field-meta.xml
<CustomField>
    <fullName>Rfc__c</fullName>
    <label>RFC</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Relacion_Precio_Proveedor__c/Relacion_Precio_Proveedor__c.object-meta.xml
<CustomObject>
    <label>Proveedor</label>
    <nameField>
        <displayFormat>RPP-{000000}</displayFormat>
        <label>Folio</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proveedores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Relacion_Precio_Proveedor__c/fields/Producto__c.field-meta.xml
<CustomField>
    <fullName>Producto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Relacion_Productos_Proveedores</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Relacion_Precio_Proveedor__c/fields/Proveedor__c.field-meta.xml
<CustomField>
    <fullName>Proveedor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proveedor</label>
    <referenceTo>Proveedor__c</referenceTo>
    <relationshipName>Relacion_Productos_Proveedores</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Relacion_Producto_Fraccionamiento__c/Relacion_Producto_Fraccionamiento__c.object-meta.xml
<CustomObject>
    <label>Fraccionamiento</label>
    <nameField>
        <label>Nombre de la Relacion</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fraccionamientos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Relacion_Producto_Fraccionamiento__c/fields/Fraccionamiento__c.field-meta.xml
<CustomField>
    <fullName>Fraccionamiento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fraccionamiento</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Fraccionamiento__c.Plaza_Filtro__c</field>
            <operation>contains</operation>
            <valueField>$Source.Plaza_Filtro__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Fraccionamiento__c</referenceTo>
    <relationshipName>Relaci_n_Productos_Fraccionamientos</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Relacion_Producto_Fraccionamiento__c/fields/Producto__c.field-meta.xml
<CustomField>
    <fullName>Producto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Relaci_n_Productos_Fraccionamientos</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Relacion_Producto_Plaza__c/Relacion_Producto_Plaza__c.object-meta.xml
<CustomObject>
    <label>Plaza</label>
    <nameField>
        <label>Nombre de la Relacion</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plazas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Relacion_Producto_Plaza__c/fields/Plaza__c.field-meta.xml
<CustomField>
    <fullName>Plaza__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plaza</label>
    <referenceTo>Plaza__c</referenceTo>
    <relationshipName>Relaci_n_Productos_Plazas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Relacion_Producto_Plaza__c/fields/Producto__c.field-meta.xml
<CustomField>
    <fullName>Producto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Relaci_n_Productos_Plazas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Segmento__c/Segmento__c.object-meta.xml
<CustomObject>
    <label>Segmento</label>
    <nameField>
        <label>Nombre de Segmentos</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Segmentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Segmento__c/fields/Fraccionamiento__c.field-meta.xml
<CustomField>
    <fullName>Fraccionamiento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fraccionamiento</label>
    <referenceTo>Fraccionamiento__c</referenceTo>
    <relationshipLabel>Segmentos</relationshipLabel>
    <relationshipName>Segmentos</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/CPPT_Clonar_producto_Test.cls
@isTest
public class CPPT_Clonar_producto_Test {
    @isTest
    public static void Test1() {
        Product2 prod = new Product2(Precio_Venta__c = 10.0, name = 'test11', IsActive = true, Numero_Filtro__c = 2, Description = 'test', Producto_Original__c = 'testP', Codigo_Producto_Original__c = 'testProd');
        insert prod;
        Proveedor__c p = new Proveedor__c(name = 'new prov',Rfc__c = 'rfc', Contacto__c = 'contact', Correo__c = 'abc@abc.com', Nombre_Comercial__c = 'nom');
        insert p;
        Relacion_Precio_Proveedor__c prov = new Relacion_Precio_Proveedor__c(Producto__c = prod.id,Proveedor__c = p.id);
        insert prov;
        Plaza__c plaza = new Plaza__c(name = 'Nuevo León');
        insert plaza;
        Fraccionamiento__c f = new Fraccionamiento__c(Estado_fracc__c = plaza.name, Plaza_Relacionada__c = plaza.id, Activo_frac__c=true, Id_Mas_Comercial__c='MAS-123456', Muni_fracc__c='San Pedro', Webfracc_frac__c='www.bosquereal.com.mx', Plaza__c='Nuevo León', Segmento__c='Residencial', Tipode_vivienda__c='Residencial', Fecha_Vigencia__c=date.today().addmonths(16),
                                                      Sin_Vigencia__c=true, Codigo_Fraccionamiento__c='66278', Plaza_Filtro__c='Nuevo León', Name='BOSQUE REAL');
        insert f;
        Prototipo__c proto = new Prototipo__c(Name='TAMARINDO', Activo_pro__c=true, Fraccionamiento__c=f.Id, Precio_pro__c=2500000, Prototipo_pro__c='TAMARINDO - BOSQUE REAL', Precio_Presupuesto__c=1850000.00, Version_Precio_Presupuesto__c='Working', Todo__c='TODO');
        insert proto;
        Relacion_Producto_Plaza__c rpp = new Relacion_Producto_Plaza__c(name = 'test',Producto__c = prod.id,Plaza__c = plaza.id);
        insert rpp;
        Relacion_Producto_Fraccionamiento__c rpf = new Relacion_Producto_Fraccionamiento__c(name = 'test',Producto__c = prod.id, Fraccionamiento__c = f.id,Vigencia_Hasta__c = system.today().addDays(-1),
                                                                                            Relacion_Producto_Plaza_Fraccionamiento__c = rpp.id);
        insert rpf;
        Test.setCurrentPage(Page.CPPT_Clonar_producto);
        ApexPages.StandardController pbController = new ApexPages.StandardController(prod);
        CPPT_Clonar_producto producto = new CPPT_Clonar_producto(pbController);
        Test.startTest();
        producto.idProd = prod.Id;
        CPPT_Clonar_producto.creaProducto(prod.Id);
        Test.stopTest();
    }
}