unpackaged/main/default/objects/Fraccionamiento__c/Fraccionamiento__c.object-meta.xml
<CustomObject>
    <label>Fraccionamiento</label>
    <nameField>
        <label>Nombre de Fraccionamiento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fraccionamientos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Fraccionamiento__c/fields/Coordenadas__c.field-meta.xml
<CustomField>
    <fullName>Coordenadas__c</fullName>
    <label>Coordenadas</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Fraccionamiento__c/fields/LigaLogoFracc__c.field-meta.xml
<CustomField>
    <fullName>LigaLogoFracc__c</fullName>
    <label>Liga Logo Fracc</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/Fraccionamiento__c/fields/Sembrado__c.field-meta.xml
<CustomField>
    <fullName>Sembrado__c</fullName>
    <label>Sembrado</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/Inventario__c.object-meta.xml
<CustomObject>
    <label>Proceso ATC</label>
    <nameField>
        <label>Id Vivienda</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProcesosATC</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Inventario__c/fields/Fracc__c.field-meta.xml
<CustomField>
    <fullName>Fracc__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fraccionamiento</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>(1 OR 5 OR 2 OR 4) AND 3</booleanFilter>
        <filterItems>
            <field>$User.Fraccionamiento_autorizado__c</field>
            <operation>contains</operation>
            <valueField>Fraccionamiento__c.Name</valueField>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>Administrador del sistema</value>
        </filterItems>
        <filterItems>
            <field>Fraccionamiento__c.Activo_frac__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$User.Fraccionamiento_autorizado__c</field>
            <operation>equals</operation>
            <value>TODOS</value>
        </filterItems>
        <filterItems>
            <field>$User.Fraccionamiento_autorizado__c</field>
            <operation>contains</operation>
            <valueField>Fraccionamiento__c.Name</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Fraccionamiento__c</referenceTo>
    <relationshipLabel>ProcesosATC</relationshipLabel>
    <relationshipName>Inventarios</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Proto__c.field-meta.xml
<CustomField>
    <fullName>Proto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prototipo</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Prototipo__c.Fraccionamiento__c</field>
            <operation>equals</operation>
            <valueField>$Source.Fracc__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Prototipo__c</referenceTo>
    <relationshipLabel>ProcesosATC</relationshipLabel>
    <relationshipName>Inventarios</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Prototipo__c/Prototipo__c.object-meta.xml
<CustomObject>
    <label>Prototipo</label>
    <nameField>
        <label>Prototipo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prototipos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Prototipo__c/fields/ImgPrototipo__c.field-meta.xml
<CustomField>
    <fullName>ImgPrototipo__c</fullName>
    <label>Img Prototipo</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/Prototipo__c/fields/PlanoArquitectonico__c.field-meta.xml
<CustomField>
    <fullName>PlanoArquitectonico__c</fullName>
    <label>Plano Arquitectónico</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/classes/ImagenVivienda.cls
public class ImagenVivienda {
    
    public Inventario__c inventario {get;set;}
    
    public Double latitude {get;set;}
    public Double longitude {get;set;}
    
	public ImagenVivienda(ApexPages.StandardController controller){
        inventario = (Inventario__c) controller.getRecord();
        inventario = [SELECT 
                      Proto__r.ImgPrototipo__c, 
                      Proto__r.PlanoArquitectonico__c,
                      Fracc__r.LigaLogoFracc__c,
                      Fracc__r.Name,
                      Fracc__r.Coordenadas__c,
                      Fracc__r.Sembrado__c
                      FROM Inventario__c 
                      WHERE Id = :inventario.Id];
        if(inventario.Fracc__r.Coordenadas__c != null){
            latitude = Double.valueOf(inventario.Fracc__r.Coordenadas__c.split(', ')[0]);
            longitude = Double.valueOf(inventario.Fracc__r.Coordenadas__c.split(', ')[1]);
        }else{
            
        }
    }
}