unpackaged/main/default/objects/Fraccionamiento__c/Fraccionamiento__c.object-meta.xml
<CustomObject>
    <label>Fraccionamiento</label>
    <nameField>
        <label>Nombre de Fraccionamiento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fraccionamientos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Fraccionamiento__c/fields/Id_Plaza__c.field-meta.xml
<CustomField>
    <fullName>Id_Plaza__c</fullName>
    <label>Id Plaza</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Asesores__c.field-meta.xml
<CustomField>
    <fullName>Asesores__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Asesores disponibles para asignar a un lead</description>
    <label>Asesor</label>
    <referenceTo>Asesores__c</referenceTo>
    <relationshipLabel>Prospectos</relationshipLabel>
    <relationshipName>Prospectos</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/ErrorCodeResponseSOAP__c.field-meta.xml
<CustomField>
    <fullName>ErrorCodeResponseSOAP__c</fullName>
    <label>Código de Respuesta</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/JMC_ApellidoMaterno__c.field-meta.xml
<CustomField>
    <fullName>JMC_ApellidoMaterno__c</fullName>
    <description>Campo para capturar el apellido materno</description>
    <label>Apellido Materno</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/JMC_AsesorAsignado__c.field-meta.xml
<CustomField>
    <fullName>JMC_AsesorAsignado__c</fullName>
    <description>Campo para asignar el nombre del asesor que dará seguimiento al lead</description>
    <label>Asesor Asignado</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/JMC_CanalVenta__c.field-meta.xml
<CustomField>
    <fullName>JMC_CanalVenta__c</fullName>
    <description>Catálogo relacionado al canal de venta</description>
    <label>Canal de Venta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Digital Asesor</fullName>
            </value>
            <value>
                <fullName>Evento</fullName>
            </value>
            <value>
                <fullName>Llamada Call Center</fullName>
            </value>
            <value>
                <fullName>Macroventa</fullName>
            </value>
            <value>
                <fullName>Medio Publicitario</fullName>
            </value>
            <value>
                <fullName>Medios Digitales</fullName>
            </value>
            <value>
                <fullName>Programas Institucionales</fullName>
            </value>
            <value>
                <fullName>Promotor Externo</fullName>
            </value>
            <value>
                <fullName>Prospección</fullName>
            </value>
            <value>
                <fullName>Referidos</fullName>
            </value>
            <value>
                <fullName>Venta Empresarial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/JMC_Estado__c.field-meta.xml
<CustomField>
    <fullName>JMC_Estado__c</fullName>
    <description>Campo que tiene como objetivo mostrar los Estados de la Republica mexicana</description>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aguascalientes</fullName>
            </value>
            <value>
                <fullName>Baja California</fullName>
            </value>
            <value>
                <fullName>Baja California Sur</fullName>
            </value>
            <value>
                <fullName>Campeche</fullName>
            </value>
            <value>
                <fullName>Chiapas</fullName>
            </value>
            <value>
                <fullName>Chihuahua</fullName>
            </value>
            <value>
                <fullName>Ciudad de México</fullName>
            </value>
            <value>
                <fullName>Coahuila</fullName>
            </value>
            <value>
                <fullName>Colima</fullName>
            </value>
            <value>
                <fullName>Durango</fullName>
            </value>
            <value>
                <fullName>Estado de México</fullName>
            </value>
            <value>
                <fullName>Guanajuato</fullName>
            </value>
            <value>
                <fullName>Guerrero</fullName>
            </value>
            <value>
                <fullName>Hidalgo</fullName>
            </value>
            <value>
                <fullName>Jalisco</fullName>
            </value>
            <value>
                <fullName>Michoacán</fullName>
            </value>
            <value>
                <fullName>Morelos</fullName>
            </value>
            <value>
                <fullName>Nayarit</fullName>
            </value>
            <value>
                <fullName>Nuevo León</fullName>
            </value>
            <value>
                <fullName>Oaxaca</fullName>
            </value>
            <value>
                <fullName>Puebla</fullName>
            </value>
            <value>
                <fullName>Querétaro</fullName>
            </value>
            <value>
                <fullName>Quintana Roo</fullName>
            </value>
            <value>
                <fullName>San Luis Potosí</fullName>
            </value>
            <value>
                <fullName>Sinaloa</fullName>
            </value>
            <value>
                <fullName>Sonora</fullName>
            </value>
            <value>
                <fullName>Tabasco</fullName>
            </value>
            <value>
                <fullName>Tamaulipas</fullName>
            </value>
            <value>
                <fullName>Tlaxcala</fullName>
            </value>
            <value>
                <fullName>Veracruz</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/JMC_EstatusLead__c.field-meta.xml
<CustomField>
    <fullName>JMC_EstatusLead__c</fullName>
    <description>Campo relacionado al análisis interno</description>
    <label>Estatus Lead</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No validado</fullName>
            </value>
            <value>
                <fullName>No Interesado</fullName>
            </value>
            <value>
                <fullName>Incubadora</fullName>
            </value>
            <value>
                <fullName>Ilocalizable</fullName>
            </value>
            <value>
                <fullName>Perfilado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/JMC_FechaNacimiento__c.field-meta.xml
<CustomField>
    <fullName>JMC_FechaNacimiento__c</fullName>
    <description>Campo para la fecha de nacimiento</description>
    <label>Fecha de Nacimiento</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/JMC_Fraccionamiento__c.field-meta.xml
<CustomField>
    <fullName>JMC_Fraccionamiento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo para la asignación del fraccionamiento de interés en el que se creará el prospecto</description>
    <label>Fraccionamiento</label>
    <referenceTo>Fraccionamiento__c</referenceTo>
    <relationshipLabel>Prospectos (Fraccionamiento)</relationshipLabel>
    <relationshipName>Prospectos1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/JMC_Fuente__c.field-meta.xml
<CustomField>
    <fullName>JMC_Fuente__c</fullName>
    <description>Campo para identificar el canal por el que se creó el lead</description>
    <label>Fuente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Afluencia_base_externa</fullName>
            </value>
            <value>
                <fullName>Aperturas</fullName>
            </value>
            <value>
                <fullName>Arrayanes</fullName>
            </value>
            <value>
                <fullName>Asesor_para_perfil_FB</fullName>
            </value>
            <value>
                <fullName>ATC Cliente carga manual</fullName>
            </value>
            <value>
                <fullName>Base_de_datos_externa</fullName>
            </value>
            <value>
                <fullName>Base_externa_marzo2017</fullName>
            </value>
            <value>
                <fullName>Blogger/Tania Rendón</fullName>
            </value>
            <value>
                <fullName>Buen Fin</fullName>
            </value>
            <value>
                <fullName>Cadreon</fullName>
            </value>
            <value>
                <fullName>Chatbot_MJ</fullName>
            </value>
            <value>
                <fullName>chatbot fb</fullName>
            </value>
            <value>
                <fullName>chatbot wa</fullName>
            </value>
            <value>
                <fullName>chatbot web</fullName>
            </value>
            <value>
                <fullName>Chat Sitio</fullName>
            </value>
            <value>
                <fullName>Click to Call</fullName>
            </value>
            <value>
                <fullName>Display_lead</fullName>
            </value>
            <value>
                <fullName>Expo_virtual_Javer</fullName>
            </value>
            <value>
                <fullName>Facebook_lead</fullName>
            </value>
            <value>
                <fullName>Facebook_lead_fovissste</fullName>
            </value>
            <value>
                <fullName>Facebook_lead_oc</fullName>
            </value>
            <value>
                <fullName>Facebook Inbox</fullName>
            </value>
            <value>
                <fullName>Facebook Inbox Pagado</fullName>
            </value>
            <value>
                <fullName>Formulario ATC</fullName>
            </value>
            <value>
                <fullName>Fovissste_base_externa</fullName>
            </value>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Inmuebles24</fullName>
            </value>
            <value>
                <fullName>Instagram</fullName>
            </value>
            <value>
                <fullName>Instagram_lead</fullName>
            </value>
            <value>
                <fullName>Instagram Lead</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/JMC_Genero__c.field-meta.xml
<CustomField>
    <fullName>JMC_Genero__c</fullName>
    <description>Sexo del cliente</description>
    <label>Sexo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Masculino</fullName>
            </value>
            <value>
                <fullName>Femenino</fullName>
            </value>
            <value>
                <fullName>Indistinto</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/JMC_LeadProfile__c.field-meta.xml
<CustomField>
    <fullName>JMC_LeadProfile__c</fullName>
    <description>Agente lead profiler que dará seguimiento</description>
    <label>Lead Profiler</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/JMC_NSS__c.field-meta.xml
<CustomField>
    <fullName>JMC_NSS__c</fullName>
    <description>NSS del cliente</description>
    <label>NSS</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/JMC_TipoCredito__c.field-meta.xml
<CustomField>
    <fullName>JMC_TipoCredito__c</fullName>
    <description>Catálogo con los tipos de crédito</description>
    <label>Tipo de Crédito</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BANSEFI</fullName>
            </value>
            <value>
                <fullName>BANJERCITO</fullName>
            </value>
            <value>
                <fullName>COFINAVIT</fullName>
            </value>
            <value>
                <fullName>CONTADO</fullName>
            </value>
            <value>
                <fullName>FOVISSSTE</fullName>
            </value>
            <value>
                <fullName>INFONAVIT</fullName>
            </value>
            <value>
                <fullName>ISSFAM</fullName>
            </value>
            <value>
                <fullName>ISSSTELEON</fullName>
            </value>
            <value>
                <fullName>PENSIONES</fullName>
            </value>
            <value>
                <fullName>SHF/BANCO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/JMC_UEN__c.field-meta.xml
<CustomField>
    <fullName>JMC_UEN__c</fullName>
    <description>Campo para identificar la UEN del fraccionamiento de interés</description>
    <label>UEN</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/MsgResponseWS__c.field-meta.xml
<CustomField>
    <fullName>MsgResponseWS__c</fullName>
    <description>Campo para el monitoreo de la respuesta del servicio integrado con Siebel</description>
    <label>Mensaje Siebel</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/classes/LeadsUtils_ctrl.cls
/*
----------------------------------------------------------
* Nombre: LeadsUtils_ctrl
* Autor Saúl González
* Proyecto: MC - FreewayConsulting
* Descripción : Clase de utilerias reutilizable para leads

* --------------------------------------------------------------------------------
* Versión       Fecha           Autor                   Desripción<p />
* --------------------------------------------------------------------------------
* 1.0           19/02/2021     Saúl González		   	Creación
* --------------------------------------------------------------------------------
*/


public class LeadsUtils_ctrl {
    public LeadsUtils_ctrl(){}
   /*
    * @description Method que devuelve un Fraccionamiento__c
    * @param String nameFracc
	* @return Fraccionamiento__c
    */ 
    public static Fraccionamiento__c getFracc(String nameFracc){
        Fraccionamiento__c f;
        try{
          f = [SELECT Id, Name FROM Fraccionamiento__c Where Name =:nameFracc];
        } catch (Exception ex) {}
		Return f;
    }
     /*
    * @description Method que devuelve un Lead
    * @param String idLead
	* @return Lead
    */ 
    public static User getOwLead(String idUser){
        final User us = [SELECT Id, Name FROM User Where Id =:idUser];
		Return us;
    }
    
    /*
    * @description Method que devuelve un Lead
    * @param String idLead
	* @return Lead
    */ 
    public static Lead getObjLead(String idLead) {
        Lead objLead = new Lead();
			objLead = [SELECT id, Name, JMC_ApellidoMaterno__c,JMC_LeadProfile__c,JMC_EstatusLead__c,JMC_AsesorAsignado__c,status,
        		JMC_Fuente__c,FirstName,LastName, OwnerId, Owner.Name, /*middlename,*/MobilePhone,ErrorCodeResponseSOAP__c, MsgResponseWS__c,IsConverted,
                JMC_FechaNacimiento__c,Phone,Email,JMC_TipoCredito__c,JMC_NSS__c, LastModifiedById, Asesores__c,Asesores__r.name,
                JMC_Genero__c,JMC_UEN__c,JMC_Estado__c,JMC_Fraccionamiento__c,JMC_Fraccionamiento__r.name, JMC_Fraccionamiento__r.Id_Plaza__c, JMC_CanalVenta__c,
                JMC_SubCanalVenta__c,JMC_Asunto__c,JMC_CapacidadCompra__c,JMC_Edad__c,ID_CUENTA__c FROM Lead Where Id =: idLead];     
        return objLead;
    }
    
    /*
    * @description Method que devuelve un Lead
    * @param String mailLead
	* @return Lead
    */ 
    public static List<Lead> getObjLeadMail(String mailLead){
        System.debug('mailLead::: '+mailLead);
		 Lead[] objLead= [SELECT id, Name, JMC_ApellidoMaterno__c,JMC_LeadProfile__c,JMC_EstatusLead__c,JMC_AsesorAsignado__c,status,IsConverted,
            JMC_Fuente__c,FirstName,LastName, OwnerId, Owner.Name, /*middlename,*/ MobilePhone,ErrorCodeResponseSOAP__c, MsgResponseWS__c,
            JMC_FechaNacimiento__c,Phone,Email,JMC_TipoCredito__c,JMC_NSS__c, LastModifiedById,Asesores__c,Asesores__r.name,
            JMC_Genero__c,JMC_UEN__c,JMC_Estado__c,JMC_Fraccionamiento__c,JMC_Fraccionamiento__r.name,JMC_CanalVenta__c,
            JMC_SubCanalVenta__c,JMC_Asunto__c,JMC_CapacidadCompra__c,JMC_Edad__c,ID_CUENTA__c FROM Lead Where Email =: mailLead];
        return objLead;
    }
    
    /*
    * @description Method que valida que no este vacío el elemnto.
    * @param String obj
	* @return String strResponse
    */ 
    public static String validaDatoVacio(String obj) {
    	return String.isNotBlank(obj) ?  obj : '';
    }
 /*
    * @description valida que no este vacío el elemento y realiza el parse a DateTime
    * @param String obj
    * @return String strResponse
    */
    public static DateTime getDataTime(String obj) {
        return String.isNotBlank(obj) ? datetime.valueOf(obj) : null;
    }
    
    /*
    * @description valida que no este vacío el elemento y realiza el parse a Date
    * @param String obFec
    * @return String strResponse
    */
    public static Date getDate(String obFec) {
        return String.isNotBlank(obFec) ? Date.valueOf(obFec) : null;
    }
    
    /*
    * @description valida que no este vacío el elemento y realiza el parse a Decimal
    * @param String obFec
    * @return String strResponse
    */
    public static Decimal getDecimal(String obFec) {
        return String.isNotBlank(obFec) ? Decimal.valueOf(obFec) : null;
    }
    
    /*
    * @description valida que no este vacío el elemento y realiza el parse a Decimal
    * @param String obFec
    * @return String strResponse
    */
    public static Decimal getDobDecimal(Double obFec) {
        return obFec!=null ? Decimal.valueOf(obFec) : null;
    }
    
    /*
    * @description valida que no este vacío el elemento y realiza el parse a String
    * @param String obFec
    * @return String strResponse
    */
    public static String getStringDec(Decimal obFec) {
        return obFec!=null  ? String.valueOf(obFec) : null;
    }
    
    
    /*
    * @description valida que no este vacío el elemento y realiza el parse a String
    * @param String obFec
    * @return String strResponse
    */
    public static String getDouString(Double obFec) {
        return obFec!=null ? String.valueOf(obFec) : null;
    }
    
    /*
    * @description realiza el parse a Map
    * @param String strJsonObj
    * @return Map<String, Object>
    */
    public static Map<String, Object> getStrToMap(String strJsonObj){
        return String.isNotBlank(strJsonObj) ? (Map<String, Object>)JSON.deserializeUntyped(strJsonObj) : null;
    }
    
    /*
    * @description obtiene una lista de campos del objeto typeObject
    * @param String typeObject
    * @return List<String>
    */
    public static List<String> getAllLabels(String typeObject){
        List<String> AllLabels = new List<String>();
        Map <String, Schema.SObjectField> fieldMap = Schema.getGlobalDescribe().get(typeObject).getDescribe().fields.getMap();
        for(Schema.SObjectField sfield : fieldMap.Values()) {
            schema.describefieldresult dfield = sfield.getDescribe();
            AllLabels.add( dfield.getname());
        }
        return AllLabels;
    }
    
    /*
    * @description Method que devuelve un usuerio a partir del nombre completo
    * @param String name
	* @return User
    */ 
    public static User getUser(String name){
        User objUser;
        name = name.replace('C3', 'Ñ');
        try{
            objUser = [SELECT id, Name FROM User Where Name =: name limit 1];
        } catch (Exception ex) {}
        return objUser;
    }
    
    /*
    * @description Method que devuelve un string con un télefono validado con regex
    * @param String phone
	* @return String
    */ 
	public static String getFilteredPhone(String phone){
        //String filteredPhone = phone != null && String.valueOf(phone.replaceAll('[^0-9]', '')).length() == 10 ? String.valueOf(phone.replaceAll('[^0-9]', '')) : '';
        //return filteredPhone;
        System.debug(phone);
        if(!String.isBlank(phone) && phone.length() == 10 && phone.Substring(0,1) != '+' && phone.Substring(0,4) != '+521' && phone.Substring(0,2) != '52'){
            phone = '+52' + phone;
        }else if(!String.isBlank(phone) && phone.length() > 9){
            if(phone.Substring(0,2) == '52' || (phone.Substring(0,2) == '+1' && phone.length() == 12)){
                phone = '+52' + phone.Substring(2,phone.length());
            }else if(phone.Substring(0,1) == '1' && phone.length() ==  11){
                phone = '+52' + phone.Substring(1,phone.length());
            }else if(phone.Substring(0,3) == '521' && phone.length() ==  13){
                phone = '+52' + phone.Substring(3,phone.length());
            }else if(phone.Substring(0,3) == '+52' && phone.length() == 13){
            }else if(phone.Substring(0,4) == '+521' && phone.length() == 14){
                phone = '+52' + phone.Substring(4,phone.length());
            }else if(phone.length() == 11 && phone.Substring(0,1) == '+'){
                phone = '+52' + phone.Substring(1,phone.length());
            }else if(phone.length() == 10 && phone.Substring(0,1) != '+' && phone.Substring(0,4) != '+521' && phone.Substring(0,2) != '52' ){
                phone = '+52' + phone;
            }else{
                phone = '+52';
            }
        }else{
            phone = '+52';
        }
        System.debug(phone);
        return phone;
 	}
    
    /*
    * @description valida que no este vacío el elemento y si lo esta devuelve el valor del registro
    * @param String strNew, strData
    * @return String string
    */
    public static String getNewData(String strNew, String strData) {
        return String.isNotBlank(strNew) ? strNew : strData;
    }
    
    public static List<User> getUsersIdSiebel(Set<Integer> ids){
        List<User> objUsers;
        try{
            objUsers = [SELECT id, Name, Id_Lead_Profiler__c, JMC_ContadorLeads__c, JMC_FechaActividadContador__c FROM User Where Id_Lead_Profiler__c in :ids];
        } catch (Exception ex) {
            System.debug(ex);
            
        }
        return objUsers;
    }
    
}