unpackaged/main/default/objects/Fraccionamiento__c/Fraccionamiento__c.object-meta.xml
<CustomObject>
    <label>Fraccionamiento</label>
    <nameField>
        <label>Nombre de Fraccionamiento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fraccionamientos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Fraccionamiento__c/fields/Ubicacion_Compania__c.field-meta.xml
<CustomField>
    <fullName>Ubicacion_Compania__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ubicación Compañia</label>
    <referenceTo>Ubicacion__c</referenceTo>
    <relationshipLabel>Fraccionamientos</relationshipLabel>
    <relationshipName>Fraccionamientos</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Fraccionamiento__c.field-meta.xml
<CustomField>
    <fullName>Fraccionamiento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fraccionamiento</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$User.Fraccionamiento_autorizado__c</field>
            <operation>contains</operation>
            <valueField>Fraccionamiento__c.Name</valueField>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>Administrador del sistema</value>
        </filterItems>
        <filterItems>
            <field>Fraccionamiento__c.Activo_frac__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$User.Fraccionamiento_autorizado__c</field>
            <operation>equals</operation>
            <value>TODOS</value>
        </filterItems>
        <filterItems>
            <field>$User.FraccionamientoAutorizados__c</field>
            <operation>contains</operation>
            <valueField>Fraccionamiento__c.Name</valueField>
        </filterItems>
        <filterItems>
            <field>Fraccionamiento__c.Name</field>
            <operation>contains</operation>
            <valueField>Fraccionamiento__c.Name</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Fraccionamiento__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Plan_de_Venta__c.field-meta.xml
<CustomField>
    <fullName>Plan_de_Venta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plan de Venta</label>
    <referenceTo>Plan_de_Venta__c</referenceTo>
    <relationshipLabel>Procesos de Ventas</relationshipLabel>
    <relationshipName>Procesos_de_Ventas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Vivienda__c.field-meta.xml
<CustomField>
    <fullName>Vivienda__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vivienda</label>
    <referenceTo>Vivienda__c</referenceTo>
    <relationshipLabel>Procesos de Ventas</relationshipLabel>
    <relationshipName>Procesos_de_Ventas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/Plan_de_Venta__c.object-meta.xml
<CustomObject>
    <label>Plan de Venta</label>
    <nameField>
        <displayFormat>Plan de Venta-{000000}</displayFormat>
        <label>Plan de Venta</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plan de Venta</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Lote__c.field-meta.xml
<CustomField>
    <fullName>Lote__c</fullName>
    <formula>Vivienda__r.Lote__c</formula>
    <label>Lote</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Manzana__c.field-meta.xml
<CustomField>
    <fullName>Manzana__c</fullName>
    <formula>Vivienda__r.Manzana__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Manzana</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Num_Interior__c.field-meta.xml
<CustomField>
    <fullName>Num_Interior__c</fullName>
    <formula>Vivienda__r.Num_Interior__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Num Interior</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proceso de Venta</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Plan de Venta</relationshipLabel>
    <relationshipName>Plan_de_Venta</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Plan_de_Venta__c.field-meta.xml
<CustomField>
    <fullName>Plan_de_Venta__c</fullName>
    <formula>&quot;Plan de Venta&quot; &amp; &quot; &quot;&amp;  Oportunidad__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Plan de Venta</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Ubicacion_Compania__c.field-meta.xml
<CustomField>
    <fullName>Ubicacion_Compania__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ubicación Compañia</label>
    <referenceTo>Ubicacion__c</referenceTo>
    <relationshipLabel>Plan de Venta</relationshipLabel>
    <relationshipName>Plan_de_Venta</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Vivienda__c.field-meta.xml
<CustomField>
    <fullName>Vivienda__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vivienda</label>
    <referenceTo>Vivienda__c</referenceTo>
    <relationshipLabel>Plan de Venta</relationshipLabel>
    <relationshipName>Plan_de_Venta</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Ubicacion__c/Ubicacion__c.object-meta.xml
<CustomObject>
    <label>Ubicación Compañia</label>
    <nameField>
        <displayFormat>U-{00}</displayFormat>
        <label>Ubicación</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ubicaciones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Ubicacion__c/fields/Banco_Intermediario__c.field-meta.xml
<CustomField>
    <fullName>Banco_Intermediario__c</fullName>
    <label>Banco Intermediario (Cuenta Extranjera)</label>
    <length>22</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Ubicacion__c/fields/CLABE_HSBC__c.field-meta.xml
<CustomField>
    <fullName>CLABE_HSBC__c</fullName>
    <label>CLABE HSBC</label>
    <length>22</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Ubicacion__c/fields/CLABE_Santander__c.field-meta.xml
<CustomField>
    <fullName>CLABE_Santander__c</fullName>
    <label>CLABE Santander</label>
    <length>22</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Ubicacion__c/fields/Clave_RAP_HSBC__c.field-meta.xml
<CustomField>
    <fullName>Clave_RAP_HSBC__c</fullName>
    <label>Clave RAP HSBC</label>
    <length>22</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Ubicacion__c/fields/Convenio_Empresa__c.field-meta.xml
<CustomField>
    <fullName>Convenio_Empresa__c</fullName>
    <label>Convenio / Empresa Santander</label>
    <length>22</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Ubicacion__c/fields/Cuenta_Extranjera__c.field-meta.xml
<CustomField>
    <fullName>Cuenta_Extranjera__c</fullName>
    <label>Cuenta Extranjera</label>
    <length>22</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Ubicacion__c/fields/Direccion_Fisica__c.field-meta.xml
<CustomField>
    <fullName>Direccion_Fisica__c</fullName>
    <label>Dirección Física</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Ubicacion__c/fields/Email_Cobranza__c.field-meta.xml
<CustomField>
    <fullName>Email_Cobranza__c</fullName>
    <label>Email Cobranza</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Ubicacion__c/fields/Nombre_de_la_Compania__c.field-meta.xml
<CustomField>
    <fullName>Nombre_de_la_Compania__c</fullName>
    <formula>Compania__r.Name</formula>
    <label>Nombre de la Compañia</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Ubicacion__c/fields/RFC__c.field-meta.xml
<CustomField>
    <fullName>RFC__c</fullName>
    <label>RFC</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Ubicacion__c/fields/Telefono_Cobranza__c.field-meta.xml
<CustomField>
    <fullName>Telefono_Cobranza__c</fullName>
    <label>Teléfono Cobranza</label>
    <type>Phone</type>
</CustomField>

unpackaged/main/default/objects/Vivienda__c/Vivienda__c.object-meta.xml
<CustomObject>
    <label>Vivienda</label>
    <nameField>
        <label>Vivienda</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Viviendas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Vivienda__c/fields/Fraccionamiento__c.field-meta.xml
<CustomField>
    <fullName>Fraccionamiento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fraccionamiento</label>
    <referenceTo>Fraccionamiento__c</referenceTo>
    <relationshipLabel>Viviendas</relationshipLabel>
    <relationshipName>Viviendas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Vivienda__c/fields/Lote__c.field-meta.xml
<CustomField>
    <fullName>Lote__c</fullName>
    <label>Lote</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Vivienda__c/fields/Manzana__c.field-meta.xml
<CustomField>
    <fullName>Manzana__c</fullName>
    <label>Manzana</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Vivienda__c/fields/Num_Interior__c.field-meta.xml
<CustomField>
    <fullName>Num_Interior__c</fullName>
    <label>Num Interior</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/CONTROL_OpcionesPagoPdf.cls
public with sharing class CONTROL_OpcionesPagoPdf {
    
    public Id RecordId {get;set;}
    public string compania {get; set;}
    public string suscriptor {get; set;}
    public string domicilioV {get; set;}
    public string fraccV {get; set;}
    public string manzV {get; set;}
    public string loteV {get; set;}
    public string interiorV {get; set;}
    public string referencia {get; set;}
    public string RFC {get; set;}
    public string convenioEmpresa_Santander {get; set;}
    public string claveRAP_HSBC {get; set;}
    public string clabe_Santander {get; set;}
    public string clabe_HSBC {get; set;}
    public string telefonoCobranza {get; set;}
    public string correoCobranza {get; set;}
    public string cuentaExtranjera {get; set;}
    public string bancoIntermediario {get; set;}

    public CONTROL_OpcionesPagoPdf(ApexPages.StandardController controller) {
        RecordId  = ApexPages.currentPage().getParameters().get('id');
        Plan_de_Venta__c pv = [Select Id, Name, Oportunidad__r.Account.Name, Vivienda__c, Ubicacion_Compania__c, Oportunidad__r.Name From Plan_de_Venta__c Where Id = :RecordId Limit 1];
        Vivienda__c [] v = [Select Id, Direccion__c, Manzana__c, Lote__c, Num_Interior__c, Fraccionamiento__r.Name From Vivienda__c Where Id = :pv.Vivienda__c Limit 1];
        Ubicacion__c[] u = [Select Id, Nombre_de_la_Compania__c, Direccion_Fisica__c, Telefono__c, Telefono_Cobranza__c, Email_Cobranza__c, RFC__c, Convenio_Empresa__c, CLABE_Santander__c, CLABE_HSBC__c, Clave_RAP_HSBC__c, Banco_Intermediario__c, Cuenta_Extranjera__c From Ubicacion__c Where Id = :pv.Ubicacion_Compania__c Limit 1];
        suscriptor = pv.Oportunidad__r.Account.Name;
        // referencia = ReferenciaDePago.generarReferencia(pv.Name);
        String numPlanVenta = pv.Oportunidad__r.Name; //.substring(2,12);
        system.debug('*** numPlanVenta: '+numPlanVenta);
        // String digito = CLASS_Oportunidad.CalculaDigitoVerificador(numPlanVenta);
        referencia = CLASS_Oportunidad.CalculaDigitoVerificador(numPlanVenta); //pv.Oportunidad__r.Name+'-'+digito;

        if(v.size() == 0){
            domicilioV = ' N/A';
            fraccV = ' N/A';
            manzV = ' N/A';
            loteV = ' N/A';
            interiorV = ' N/A';
        }
        else{
            domicilioV = ' ' + v[0].Direccion__c;
            fraccV = ' ' + v[0].Fraccionamiento__r.Name;
            manzV = ' ' + v[0].Manzana__c;
            loteV = ' ' + v[0].Lote__c;
            interiorV = ' ' + v[0].Num_Interior__c;
        }
        if(u.size() == 0){
            compania = ' N/A';
            RFC = ' N/A';
            convenioEmpresa_Santander = ' N/A';
            claveRAP_HSBC = ' N/A';
            clabe_Santander = ' N/A';
            clabe_HSBC = ' N/A';
            telefonoCobranza = ' N/A';
            correoCobranza = ' N/A';
            bancoIntermediario = ' N/A';
            cuentaExtranjera = ' N/A';
        }
        else{
            compania = ' ' + u[0].Nombre_de_la_Compania__c;
            RFC = ' RFC: ' + u[0].RFC__c;
            convenioEmpresa_Santander = ' ' + u[0].Convenio_Empresa__c;
            claveRAP_HSBC = ' ' + u[0].Clave_RAP_HSBC__c;
            clabe_Santander = ' ' + u[0].CLABE_Santander__c;
            clabe_HSBC = ' ' + u[0].CLABE_HSBC__c;
            telefonoCobranza = ' ' + u[0].Telefono_Cobranza__c;
            correoCobranza = ' ' + u[0].Email_Cobranza__c;
            bancoIntermediario = ' ' + u[0].Banco_Intermediario__c;
            cuentaExtranjera = ' ' + u[0].Cuenta_Extranjera__c;
        }
    }
}