unpackaged/main/default/objects/Fraccionamiento__c/Fraccionamiento__c.object-meta.xml
<CustomObject>
    <label>Fraccionamiento</label>
    <nameField>
        <label>Nombre de Fraccionamiento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fraccionamientos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Fraccionamiento__c/fields/Activo_frac__c.field-meta.xml
<CustomField>
    <fullName>Activo_frac__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Fraccionamiento__c/fields/Codigo_Fraccionamiento__c.field-meta.xml
<CustomField>
    <fullName>Codigo_Fraccionamiento__c</fullName>
    <externalId>true</externalId>
    <label>Código Fraccionamiento</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Fraccionamiento__c/fields/Estado_fracc__c.field-meta.xml
<CustomField>
    <fullName>Estado_fracc__c</fullName>
    <label>Estado</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Fraccionamiento__c/fields/Fecha_Vigencia__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Vigencia__c</fullName>
    <label>Fecha Vigencia</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Fraccionamiento__c/fields/Id_Mas_Comercial__c.field-meta.xml
<CustomField>
    <fullName>Id_Mas_Comercial__c</fullName>
    <label>Id Mas Comercial</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Fraccionamiento__c/fields/Muni_fracc__c.field-meta.xml
<CustomField>
    <fullName>Muni_fracc__c</fullName>
    <label>Municipio</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Fraccionamiento__c/fields/Plaza__c.field-meta.xml
<CustomField>
    <fullName>Plaza__c</fullName>
    <label>Plaza</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Fraccionamiento__c/fields/Plaza_Filtro__c.field-meta.xml
<CustomField>
    <fullName>Plaza_Filtro__c</fullName>
    <label>Plaza_Filtro</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Querétaro</fullName>
            </value>
            <value>
                <fullName>Nuevo León</fullName>
            </value>
            <value>
                <fullName>Estado de México</fullName>
            </value>
            <value>
                <fullName>Jalisco</fullName>
            </value>
            <value>
                <fullName>Aguascalientes</fullName>
            </value>
            <value>
                <fullName>Distrito Federal</fullName>
            </value>
            <value>
                <fullName>San Luis Potosi</fullName>
            </value>
            <value>
                <fullName>Quintana Roo</fullName>
            </value>
            <value>
                <fullName>Guanajuato</fullName>
            </value>
            <value>
                <fullName>Tamaulipas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Fraccionamiento__c/fields/Plaza_Relacionada__c.field-meta.xml
<CustomField>
    <fullName>Plaza_Relacionada__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plaza</label>
    <referenceTo>Plaza__c</referenceTo>
    <relationshipLabel>Fraccionamientos</relationshipLabel>
    <relationshipName>Fraccionamientos</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Fraccionamiento__c/fields/Segmento__c.field-meta.xml
<CustomField>
    <fullName>Segmento__c</fullName>
    <label>Segmento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Residencial</fullName>
            </value>
            <value>
                <fullName>Media</fullName>
            </value>
            <value>
                <fullName>Interés Social</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Fraccionamiento__c/fields/Sin_Vigencia__c.field-meta.xml
<CustomField>
    <fullName>Sin_Vigencia__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sin Vigencia</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Fraccionamiento__c/fields/Tipode_vivienda__c.field-meta.xml
<CustomField>
    <fullName>Tipode_vivienda__c</fullName>
    <label>Tipo de vivienda</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Residencial</fullName>
                <default>true</default>
                <label>Residencial</label>
            </value>
            <value>
                <fullName>Interés Social</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Fraccionamiento__c/fields/Webfracc_frac__c.field-meta.xml
<CustomField>
    <fullName>Webfracc_frac__c</fullName>
    <label>Web Fraccionamiento</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/Pricebook2/fields/Fraccionamiento__c.field-meta.xml
<CustomField>
    <fullName>Fraccionamiento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fraccionamiento</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 AND (2 OR 3)</booleanFilter>
        <filterItems>
            <field>Fraccionamiento__c.Activo_frac__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$User.Fraccionamiento_autorizado__c</field>
            <operation>contains</operation>
            <valueField>Fraccionamiento__c.Name</valueField>
        </filterItems>
        <filterItems>
            <field>$User.FraccionamientoAutorizados__c</field>
            <operation>contains</operation>
            <valueField>Fraccionamiento__c.Name</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Fraccionamiento__c</referenceTo>
    <relationshipLabel>Listas de precios</relationshipLabel>
    <relationshipName>Listas_de_precios</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Pricebook2/fields/Periodo_Inicio__c.field-meta.xml
<CustomField>
    <fullName>Periodo_Inicio__c</fullName>
    <label>Periodo Inicio</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2023-05-01</fullName>
                <label>MAYO 2023</label>
            </value>
            <value>
                <fullName>2023-06-01</fullName>
                <label>JUNIO 2023</label>
            </value>
            <value>
                <fullName>2023-07-01</fullName>
                <label>JULIO 2023</label>
            </value>
            <value>
                <fullName>2023-08-01</fullName>
                <label>AGOSTO 2023</label>
            </value>
            <value>
                <fullName>2023-09-01</fullName>
                <label>SEPTIEMBRE 2023</label>
            </value>
            <value>
                <fullName>2023-10-01</fullName>
                <label>OCTUBRE 2023</label>
            </value>
            <value>
                <fullName>2023-11-01</fullName>
                <label>NOVIEMBRE 2023</label>
            </value>
            <value>
                <fullName>2023-12-01</fullName>
                <label>DICIEMBRE 2023</label>
            </value>
            <value>
                <fullName>ENERO 2024</fullName>
            </value>
            <value>
                <fullName>FEBRERO 2024</fullName>
            </value>
            <value>
                <fullName>MARZO 2024</fullName>
            </value>
            <value>
                <fullName>ABRIL 2024</fullName>
            </value>
            <value>
                <fullName>MAYO 2024</fullName>
            </value>
            <value>
                <fullName>JUNIO 2024</fullName>
            </value>
            <value>
                <fullName>JULIO 2024</fullName>
            </value>
            <value>
                <fullName>AGOSTO 2024</fullName>
            </value>
            <value>
                <fullName>SEPTIEMBRE 2024</fullName>
            </value>
            <value>
                <fullName>OCTUBRE 2024</fullName>
            </value>
            <value>
                <fullName>NOVIEMBRE 2024</fullName>
            </value>
            <value>
                <fullName>DICIEMBRE 2024</fullName>
            </value>
            <value>
                <fullName>ENERO 2025</fullName>
            </value>
            <value>
                <fullName>FEBRERO 2025</fullName>
            </value>
            <value>
                <fullName>MARZO 2025</fullName>
            </value>
            <value>
                <fullName>ABRIL 2025</fullName>
            </value>
            <value>
                <fullName>MAYO 2025</fullName>
            </value>
            <value>
                <fullName>JUNIO 2025</fullName>
            </value>
            <value>
                <fullName>JULIO 2025</fullName>
            </value>
            <value>
                <fullName>AGOSTO 2025</fullName>
            </value>
            <value>
                <fullName>SEPTIEMBRE 2025</fullName>
            </value>
            <value>
                <fullName>OCTUBRE 2025</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Pricebook2/recordTypes/Producto_Generico.recordType-meta.xml
<RecordType>
    <fullName>Producto_Generico</fullName>
    <active>true</active>
    <label>Producto Genérico</label>
</RecordType>

unpackaged/main/default/objects/Product2/fields/Plaza__c.field-meta.xml
<CustomField>
    <fullName>Plaza__c</fullName>
    <label>Plaza</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Queretaro</fullName>
            </value>
            <value>
                <fullName>Nuevo Leon</fullName>
            </value>
            <value>
                <fullName>Estado de Mexico</fullName>
            </value>
            <value>
                <fullName>Jalisco</fullName>
            </value>
            <value>
                <fullName>Aguascalientes</fullName>
            </value>
            <value>
                <fullName>Distrito Federal</fullName>
            </value>
            <value>
                <fullName>San Luis Potosi</fullName>
            </value>
            <value>
                <fullName>Quintana Roo</fullName>
            </value>
            <value>
                <fullName>Guanajuato</fullName>
            </value>
            <value>
                <fullName>Tamaulipas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Precio_Venta__c.field-meta.xml
<CustomField>
    <fullName>Precio_Venta__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Precio Venta al Cliente</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Sin_Vigencia__c.field-meta.xml
<CustomField>
    <fullName>Sin_Vigencia__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Sin Vigencia</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Segmento__c/Segmento__c.object-meta.xml
<CustomObject>
    <label>Segmento</label>
    <nameField>
        <label>Nombre de Segmentos</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Segmentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Segmento__c/fields/Fraccionamiento__c.field-meta.xml
<CustomField>
    <fullName>Fraccionamiento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fraccionamiento</label>
    <referenceTo>Fraccionamiento__c</referenceTo>
    <relationshipLabel>Segmentos</relationshipLabel>
    <relationshipName>Segmentos</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/AsignProductos_Controller_Test.cls
@isTest
public class AsignProductos_Controller_Test {
    static TestMethod void testMethod1() {
        Product2 p = new Product2();
        p.name = 'pro';
        p.Precio_Venta__c = 12;
        p.Description = 'Description';
        insert p;
        PricebookEntry st = new PricebookEntry(Pricebook2Id = Test.getStandardPricebookId(), Product2Id = p.Id, UnitPrice = 100 ,IsActive = true );
        insert st;
        Plaza__c plaza = new Plaza__c(name = 'Nuevo León');
        insert plaza;
        Fraccionamiento__c f = new Fraccionamiento__c(Estado_fracc__c = plaza.name, Plaza_Relacionada__c = plaza.id, Activo_frac__c=true, Id_Mas_Comercial__c='MAS-123456', Muni_fracc__c='San Pedro', Webfracc_frac__c='www.bosquereal.com.mx', Plaza__c='Nuevo León', Segmento__c='Residencial', Tipode_vivienda__c='Residencial', Fecha_Vigencia__c=date.today().addmonths(16),
                                                      Sin_Vigencia__c=true, Codigo_Fraccionamiento__c='66278', Plaza_Filtro__c='Nuevo León', Name='BOSQUE REAL');
        insert f;
        Pricebook2 pb1  = new Pricebook2();
        pb1.Name = 'Standard';
        pb1.Description = 'test';
        pb1.Fraccionamiento__c = f.Id;
        pb1.Periodo_Inicio__c='JUNIO 2023';
        pb1.Periodo_Fin__c='JUNIO 2023';
        pb1.Vigente_Desde__c = system.today() ;
        pb1.Vigente_Hasta__c= Date.newInstance(2023, 06, 30);
        pb1.RecordTypeId = Schema.SObjectType.Pricebook2.getRecordTypeInfosBydevelopername().get('Producto_Generico').getRecordTypeId();
        insert pb1;
        PricebookEntry standardPrice = new PricebookEntry(Pricebook2Id = pb1.Id, Product2Id = p.Id, UnitPrice = 100 ,IsActive = true ,UseStandardPrice = false);
        Boolean exceptionThrown2 = false;
        try {
            insert standardPrice;
        } 
        catch (Exception e) {
            exceptionThrown2 = true;
            Boolean expectedExceptionThrown =  (e.getMessage().contains('anterior al día de hoy')) ? true : false; 
            System.AssertEquals(true, expectedExceptionThrown, e.getMessage()); 
        } 
        List<Map<String, Object>> selectedRecords = new List<Map<String, Object>>();
        Map<String, Object> selectedRecord = new Map<String, Object>();
        selectedRecord.put('Id', P.id);
        selectedRecords.add(selectedRecord);
        Test.startTest();
        try {
            AsignProductos_Controller.asignaProductos(pb1.Id, selectedRecords);
        } 
        catch (Exception e) {
            exceptionThrown2 = true;
            Boolean expectedExceptionThrown =  (e.getMessage().contains('anterior al día de hoy')) ? true : false; 
            System.AssertEquals(true, expectedExceptionThrown, e.getMessage()); 
        } 
        AsignProductos_Controller.getProductos(pb1.id, p.Name);
        Test.stopTest();
    }
}