unpackaged/main/default/objects/Fraccionamiento__c/Fraccionamiento__c.object-meta.xml
<CustomObject>
    <label>Fraccionamiento</label>
    <nameField>
        <label>Nombre de Fraccionamiento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fraccionamientos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Fraccionamiento__c/fields/Prototipo__c.field-meta.xml
<CustomField>
    <fullName>Prototipo__c</fullName>
    <label>Prototipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prototipo 1</fullName>
            </value>
            <value>
                <fullName>Prototipo 2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Pricebook2/fields/Cantidad__c.field-meta.xml
<CustomField>
    <fullName>Cantidad__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Cantidad</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Pricebook2/fields/Estatus_Proceso_de_Venta__c.field-meta.xml
<CustomField>
    <fullName>Estatus_Proceso_de_Venta__c</fullName>
    <label>Estatus Proceso de Venta</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Formalizado</fullName>
            </value>
            <value>
                <fullName>Escriturado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Pricebook2/fields/Fraccionamiento__c.field-meta.xml
<CustomField>
    <fullName>Fraccionamiento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fraccionamiento</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 AND (2 OR 3)</booleanFilter>
        <filterItems>
            <field>Fraccionamiento__c.Activo_frac__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$User.Fraccionamiento_autorizado__c</field>
            <operation>contains</operation>
            <valueField>Fraccionamiento__c.Name</valueField>
        </filterItems>
        <filterItems>
            <field>$User.FraccionamientoAutorizados__c</field>
            <operation>contains</operation>
            <valueField>Fraccionamiento__c.Name</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Fraccionamiento__c</referenceTo>
    <relationshipLabel>Listas de precios</relationshipLabel>
    <relationshipName>Listas_de_precios</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Pricebook2/fields/Ilimitado__c.field-meta.xml
<CustomField>
    <fullName>Ilimitado__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ilimitado</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Pricebook2/fields/Porcentaje_Fianciamiento__c.field-meta.xml
<CustomField>
    <fullName>Porcentaje_Fianciamiento__c</fullName>
    <label>Porcentaje Financiamiento</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Pricebook2/fields/Precio_Min_Autorizado__c.field-meta.xml
<CustomField>
    <fullName>Precio_Min_Autorizado__c</fullName>
    <label>Precio Min Autorizado</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Pricebook2/fields/Precio_Min_Solicitado__c.field-meta.xml
<CustomField>
    <fullName>Precio_Min_Solicitado__c</fullName>
    <label>Precio Min Solicitado</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Pricebook2/fields/Prototipo__c.field-meta.xml
<CustomField>
    <fullName>Prototipo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prototipo</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Prototipo__c.Fraccionamiento__c</field>
            <operation>equals</operation>
            <valueField>$Source.Fraccionamiento__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Prototipo__c</referenceTo>
    <relationshipLabel>Listas de precios</relationshipLabel>
    <relationshipName>Listas_de_precios</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Pricebook2/fields/Vigente_Desde__c.field-meta.xml
<CustomField>
    <fullName>Vigente_Desde__c</fullName>
    <label>Vigente Desde</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Pricebook2/fields/Vigente_Hasta__c.field-meta.xml
<CustomField>
    <fullName>Vigente_Hasta__c</fullName>
    <label>Vigente Hasta</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Pricebook2/recordTypes/Bonificacion.recordType-meta.xml
<RecordType>
    <fullName>Bonificacion</fullName>
    <active>true</active>
    <label>Bonificación</label>
</RecordType>

unpackaged/main/default/objects/Pricebook2/recordTypes/Financiamiento.recordType-meta.xml
<RecordType>
    <fullName>Financiamiento</fullName>
    <active>true</active>
    <label>Financiamiento</label>
</RecordType>

unpackaged/main/default/objects/Pricebook2/recordTypes/Paquete.recordType-meta.xml
<RecordType>
    <fullName>Paquete</fullName>
    <active>true</active>
    <label>Paquete</label>
</RecordType>

unpackaged/main/default/objects/Pricebook2/recordTypes/Producto_Generico.recordType-meta.xml
<RecordType>
    <fullName>Producto_Generico</fullName>
    <active>true</active>
    <label>Producto Genérico</label>
</RecordType>

unpackaged/main/default/objects/Pricebook2/recordTypes/Promocion_Precio.recordType-meta.xml
<RecordType>
    <fullName>Promocion_Precio</fullName>
    <active>true</active>
    <label>Promoción Precio</label>
</RecordType>

unpackaged/main/default/objects/Pricebook2/recordTypes/Promocion_Venta.recordType-meta.xml
<RecordType>
    <fullName>Promocion_Venta</fullName>
    <active>true</active>
    <label>Promoción Venta</label>
</RecordType>

unpackaged/main/default/objects/Pricebook2/recordTypes/Regalo_MKT.recordType-meta.xml
<RecordType>
    <fullName>Regalo_MKT</fullName>
    <active>true</active>
    <label>Regalo MKT</label>
</RecordType>

unpackaged/main/default/objects/Prototipo__c/Prototipo__c.object-meta.xml
<CustomObject>
    <label>Prototipo</label>
    <nameField>
        <label>Prototipo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prototipos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Prototipo__c/fields/Fraccionamiento__c.field-meta.xml
<CustomField>
    <fullName>Fraccionamiento__c</fullName>
    <label>Fraccionamiento</label>
    <referenceTo>Fraccionamiento__c</referenceTo>
    <relationshipLabel>Prototipos</relationshipLabel>
    <relationshipName>Prototipos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/classes/CPPT_Lista_Precios_Test.cls
@isTest
public class CPPT_Lista_Precios_Test {
    static TestMethod void Test1() {
        Fraccionamiento__c f = new Fraccionamiento__c(name = 'ACACIAS');
        insert f;
        Prototipo__c pro = new Prototipo__c(name = 'test pro',Fraccionamiento__c = f.id);
        insert pro;
        
        Prototipo__c p1 = new Prototipo__c(name = 'test1',Fraccionamiento__c = f.id);
        insert p1;
        Pricebook2 pb3 = new Pricebook2(name = 'test',Fraccionamiento__c = f.id,Vigente_Desde__c = system.today(),Vigente_Hasta__c= Date.newInstance(2023, 10, 30),
                                        Description = 'test',Prototipo__c = p1.id); 
        pb3.RecordTypeId = Schema.SObjectType.Pricebook2.getRecordTypeInfosByDeveloperName().get('Paquete').getRecordTypeId();
        insert pb3;
        Pricebook2 pb4 = new Pricebook2(name = 'test',Fraccionamiento__c = f.id,Vigente_Desde__c = system.today(),Vigente_Hasta__c= Date.newInstance(2023, 10, 30),
                                        Description = 'test',Prototipo__c = p1.id);
        pb4.RecordTypeId = Schema.SObjectType.Pricebook2.getRecordTypeInfosByDeveloperName().get('Promocion_Venta').getRecordTypeId();
        insert pb4;
        Pricebook2 pb5= new Pricebook2(name = 'test',Fraccionamiento__c = f.id,Vigente_Desde__c = system.today(),Vigente_Hasta__c= Date.newInstance(2023, 10, 30),
                                       Cantidad__c = 12, Description = 'test',Prototipo__c = p1.id);
        pb5.RecordTypeId  = Schema.SObjectType.Pricebook2.getRecordTypeInfosByDeveloperName().get('Promocion_Precio').getRecordTypeId();
        insert pb5;
        Pricebook2 pb6 = new Pricebook2(name = 'test',Fraccionamiento__c = f.id,Vigente_Desde__c = system.today(),Vigente_Hasta__c= Date.newInstance(2023, 08, 30),
                                        Estatus_Proceso_de_Venta__c = 'Formalizado',Precio_Min_Solicitado__c = 12, Precio_Min_Autorizado__c = 12,Description = 'test',
                                       Prototipo__c = p1.id);
        pb6.RecordTypeId = Schema.SObjectType.Pricebook2.getRecordTypeInfosByDeveloperName().get('Regalo_MKT').getRecordTypeId();
        
        insert pb6;
        Pricebook2 pb8 = new Pricebook2(name = 'test',Fraccionamiento__c = f.id,Vigente_Desde__c = system.today(),Vigente_Hasta__c= Date.newInstance(2023, 10, 30),
                                        Description = 'test');
        pb8.RecordTypeId = Schema.SObjectType.Pricebook2.getRecordTypeInfosByDeveloperName().get('Producto_Generico').getRecordTypeId();
        insert pb8;
        Pricebook2 pb9 = new Pricebook2(name = 'test',Fraccionamiento__c = f.id,Vigente_Desde__c = system.today(),Vigente_Hasta__c= Date.newInstance(2023, 10, 30),
                                        Porcentaje_Fianciamiento__c = 10,Description = 'test',Prototipo__c = p1.id);
        pb9.RecordTypeId = Schema.SObjectType.Pricebook2.getRecordTypeInfosByDeveloperName().get('Financiamiento').getRecordTypeId();
        insert pb9;
        // Exception cases---->
        Pricebook2 pb7 = new Pricebook2(name = 'test',Fraccionamiento__c = f.id,Vigente_Desde__c = Date.newInstance(system.today().addYears(-1).year(), system.today().addMonths(-1).month(), system.today().addDays(-1).day()),
                                        Vigente_Hasta__c= Date.newInstance(2023, 10, 30),Prototipo__c = p1.id,
                                        Description = 'test');
        pb7.RecordTypeId = Schema.SObjectType.Pricebook2.getRecordTypeInfosByDeveloperName().get('Producto_Generico').getRecordTypeId();
        try{
            insert pb7;
        }
        catch(Exception e){
            Boolean expectedExceptionThrown =  e.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION') ? true : false;
            System.assertEquals(expectedExceptionThrown, true);
        }
        
        Pricebook2 pb0 = new Pricebook2(name = 'test',Fraccionamiento__c = f.id,Vigente_Desde__c = system.today().addMonths(-3),
                                        Vigente_Hasta__c= Date.newInstance(system.today().addYears(-1).year(), system.today().addMonths(-1).month(), system.today().addDays(-1).day()),
                                        Description = 'test',Prototipo__c = p1.id);
        pb0.RecordTypeId = Schema.SObjectType.Pricebook2.getRecordTypeInfosByDeveloperName().get('Bonificacion').getRecordTypeId();
       try{
            insert pb0;
       } catch(Exception e){
            Boolean expectedExceptionThrown =  e.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION') ? true : false;
            System.assertEquals(expectedExceptionThrown, true);
        }
        
        Prototipo__c p = new Prototipo__c(name = 'test',Fraccionamiento__c = f.id);
        insert p;
        
        pb3.name = 'test updated';
        pb3.Prototipo__c = p.id;
        try{
            update pb3;
       } catch(Exception e){
            Boolean expectedExceptionThrown =  e.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION') ? true : false;
            System.assertEquals(expectedExceptionThrown, true);
        }
        
        pb4.name = 'test updated';
        pb4.Prototipo__c = p.id;
        try{
            update pb4;
       } catch(Exception e){
            Boolean expectedExceptionThrown =  e.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION') ? true : false;
            System.assertEquals(expectedExceptionThrown, true);
        }
        
        pb5.name = 'test updated';
        pb5.Prototipo__c = p.id;
        pb5.Ilimitado__c = true;
        pb5.Cantidad__c = 12;
        try{
            update pb5;
       } catch(Exception e){
            Boolean expectedExceptionThrown =  e.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION') ? true : false;
            System.assertEquals(expectedExceptionThrown, true);
        }
        pb6.name = 'test updated';
        pb6.Prototipo__c = p.id;
        try{
            update pb6;
       } catch(Exception e){
            Boolean expectedExceptionThrown =  e.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION') ? true : false;
            System.assertEquals(expectedExceptionThrown, true);
        }
        pb9.name = 'test updated';
            update pb9;
           
    }
}