unpackaged/main/default/objects/Fraccionamiento__c/Fraccionamiento__c.object-meta.xml
<CustomObject>
    <label>Fraccionamiento</label>
    <nameField>
        <label>Nombre de Fraccionamiento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fraccionamientos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Fraccionamiento__c/fields/Prototipo__c.field-meta.xml
<CustomField>
    <fullName>Prototipo__c</fullName>
    <label>Prototipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prototipo 1</fullName>
            </value>
            <value>
                <fullName>Prototipo 2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Pricebook2/fields/Fraccionamiento__c.field-meta.xml
<CustomField>
    <fullName>Fraccionamiento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fraccionamiento</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 AND (2 OR 3)</booleanFilter>
        <filterItems>
            <field>Fraccionamiento__c.Activo_frac__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$User.Fraccionamiento_autorizado__c</field>
            <operation>contains</operation>
            <valueField>Fraccionamiento__c.Name</valueField>
        </filterItems>
        <filterItems>
            <field>$User.FraccionamientoAutorizados__c</field>
            <operation>contains</operation>
            <valueField>Fraccionamiento__c.Name</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Fraccionamiento__c</referenceTo>
    <relationshipLabel>Listas de precios</relationshipLabel>
    <relationshipName>Listas_de_precios</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Pricebook2/fields/Prototipo__c.field-meta.xml
<CustomField>
    <fullName>Prototipo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prototipo</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Prototipo__c.Fraccionamiento__c</field>
            <operation>equals</operation>
            <valueField>$Source.Fraccionamiento__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Prototipo__c</referenceTo>
    <relationshipLabel>Listas de precios</relationshipLabel>
    <relationshipName>Listas_de_precios</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Pricebook2/fields/Vigente_Desde__c.field-meta.xml
<CustomField>
    <fullName>Vigente_Desde__c</fullName>
    <label>Vigente Desde</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Pricebook2/fields/Vigente_Hasta__c.field-meta.xml
<CustomField>
    <fullName>Vigente_Hasta__c</fullName>
    <label>Vigente Hasta</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Fraccionamientos__c.field-meta.xml
<CustomField>
    <fullName>Fraccionamientos__c</fullName>
    <label>Fraccionamientos</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Prototipo__c/Prototipo__c.object-meta.xml
<CustomObject>
    <label>Prototipo</label>
    <nameField>
        <label>Prototipo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prototipos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Prototipo__c/fields/Fraccionamiento__c.field-meta.xml
<CustomField>
    <fullName>Fraccionamiento__c</fullName>
    <label>Fraccionamiento</label>
    <referenceTo>Fraccionamiento__c</referenceTo>
    <relationshipLabel>Prototipos</relationshipLabel>
    <relationshipName>Prototipos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/classes/AddProducts.cls
public class AddProducts {
    @AuraEnabled
    public static List<Product2> fetchProducts(){
        List<Product2> prodList = [SELECT Id,Name,ProductCode, Family FROM Product2  Order by CreatedDate desc LIMIT 10 ];
        return prodList;
    }
    @AuraEnabled
    public static List<PriceBook2> fetchPbRecords(String prods){
        List<Product2> prodList = [SELECT Id,Name,Fraccionamientos__c, ProductCode,  RecordType.Name,Family FROM Product2 Where Id = : prods];
        String frac ; String recordtype;
        if(prodList != null && prodList.size()>0){
            frac = prodList[0].Fraccionamientos__c;
            recordtype = prodList[0].RecordType.Name;
        }
        List<PriceBook2> pblist = [select id, Name, Fraccionamiento__c, Description,Prototipo__c, Vigente_Desde__c,Vigente_Hasta__c, IsActive from PriceBook2 
                                   where/* Fraccionamiento__c = :frac AND Prototipo__c IN :ProtoViv   RecordType.Name = :frac AND*/ IsActive = true 
                                   AND Vigente_Desde__c <= : Date.today() AND Vigente_Hasta__c >= : Date.today()  LIMIT 5];
        return pblist;
    }
    @AuraEnabled
    public static void updateProdRecords(String pb, String prods){ 
        List<Product2> prodList = [SELECT Id,Name,Fraccionamientos__c, ProductCode,  RecordType.Name,Family FROM Product2 Where Id = : prods];
        PricebookEntry pb1 = new PricebookEntry();
        pb1.Pricebook2Id=pb;
        pb1.Product2Id=prodList[0].Id;
        pb1.IsActive=true;
        pb1.UnitPrice=0;
        insert pb1;
    }
}