unpackaged/main/default/objects/Cesion_a_Otra_Persona_Fisica_o_Moral__c/Cesion_a_Otra_Persona_Fisica_o_Moral__c.object-meta.xml
<CustomObject>
    <label>Cesión a Otra Persona Física o Moral</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Cesión Persona Física o Moral</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cesiones a Otra Persona Física o Moral</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Cesion_a_Otra_Persona_Fisica_o_Moral__c/fields/Contrato__c.field-meta.xml
<CustomField>
    <fullName>Contrato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contrato Cesión</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Cesiones a Otra Persona Física o Moral</relationshipLabel>
    <relationshipName>Cesiones_a_Otra_Persona_F_sica_o_Moral</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Cesion_a_Otra_Persona_Fisica_o_Moral__c/fields/Dictaminacion__c.field-meta.xml
<CustomField>
    <fullName>Dictaminacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dictaminación Cesión</label>
    <referenceTo>Dictaminacion__c</referenceTo>
    <relationshipLabel>Cesiones a Otra Persona Física o Moral</relationshipLabel>
    <relationshipName>Cesiones_a_Otra_Persona_F_sica_o_Moral</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Cesion_a_Otra_Persona_Fisica_o_Moral__c/recordTypes/Persona_Fisica.recordType-meta.xml
<RecordType>
    <fullName>Persona_Fisica</fullName>
    <active>true</active>
    <label>Persona Física</label>
</RecordType>

unpackaged/main/default/objects/Cesion_a_Otra_Persona_Fisica_o_Moral__c/recordTypes/Persona_Moral.recordType-meta.xml
<RecordType>
    <fullName>Persona_Moral</fullName>
    <active>true</active>
    <label>Persona Moral</label>
</RecordType>

unpackaged/main/default/objects/Contract/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proceso de Venta</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Dictaminación</relationshipLabel>
    <relationshipName>Dictaminacion</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contract/recordTypes/Persona_Fisica.recordType-meta.xml
<RecordType>
    <fullName>Persona_Fisica</fullName>
    <active>true</active>
    <label>Dictaminación</label>
</RecordType>

unpackaged/main/default/objects/Contract/recordTypes/Persona_Moral.recordType-meta.xml
<RecordType>
    <fullName>Persona_Moral</fullName>
    <active>false</active>
    <label>Persona Moral</label>
</RecordType>

unpackaged/main/default/objects/Contrato__c/Contrato__c.object-meta.xml
<CustomObject>
    <label>Contratos</label>
    <nameField>
        <label>No. Interno</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contratos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Dictaminacion__c/Dictaminacion__c.object-meta.xml
<CustomObject>
    <label>Dictaminación</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Folio</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dictaminación</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Dictaminacion__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Dictaminaciones</relationshipLabel>
    <relationshipName>Dictaminaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Dictaminacion__c/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Proceso de Venta</description>
    <label>Proceso de Venta</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Informacion_representante_legal__c/Informacion_representante_legal__c.object-meta.xml
<CustomObject>
    <label>Información Representante Legal</label>
    <nameField>
        <label>Nombre de Rep legal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Información Representantes Legales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Informacion_representante_legal__c/fields/Cesion_a_Otra_Persona_Fisica_o_Moral__c.field-meta.xml
<CustomField>
    <fullName>Cesion_a_Otra_Persona_Fisica_o_Moral__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cesión a Otra Persona Física o Moral</label>
    <referenceTo>Cesion_a_Otra_Persona_Fisica_o_Moral__c</referenceTo>
    <relationshipLabel>Información Representantes Legales</relationshipLabel>
    <relationshipName>Informacion_Representantes_Legales</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Informacion_representante_legal__c/fields/Contrato__c.field-meta.xml
<CustomField>
    <fullName>Contrato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contrato</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Información Representantes Legales</relationshipLabel>
    <relationshipName>Informacion_Representantes_Legales</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Informacion_representante_legal__c/fields/Dictaminacion__c.field-meta.xml
<CustomField>
    <fullName>Dictaminacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dictaminación</label>
    <referenceTo>Dictaminacion__c</referenceTo>
    <relationshipLabel>Información Representantes Legales</relationshipLabel>
    <relationshipName>Informaci_n_Representantes_Legales</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Dictaminacion__c.field-meta.xml
<CustomField>
    <fullName>Dictaminacion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dictaminación</label>
    <referenceTo>Dictaminacion__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/CLASS_PopulateNewRecords.cls
public class CLASS_PopulateNewRecords {

    @AuraEnabled(cacheable=true)
    public static String populaCamposDictaminacion(String oppId) {
        Dictaminacion__c dict = new Dictaminacion__c();
        
        if(oppId != null && oppId != ''){
            
            // Id recordTypeIdFisica = Schema.SObjectType.Contract.getRecordTypeInfosByDeveloperName().get('Persona_Fisica').getRecordTypeId();
            // Id recordTypeIdMoral = Schema.SObjectType.Contract.getRecordTypeInfosByDeveloperName().get('Persona_Moral').getRecordTypeId();
            
            Opportunity opp = [SELECT Id, AccountId, Account.RecordType.DeveloperName FROM Opportunity WHERE Id =: oppId]; 
            
            dict.Account__c = opp.AccountId;
            dict.Oportunidad__c = oppId;
        }else{
            dict.Account__c = '';
            // cont.RecordTypeId = '';
        }
        
        return JSON.serialize(dict);
    }
    
    @AuraEnabled(cacheable=true)
    public static String populaCamposContrato(String oppId) {
        Contract cont = new Contract();
        
        if(oppId != null && oppId != ''){
            
            Id recordTypeIdFisica = Schema.SObjectType.Contract.getRecordTypeInfosByDeveloperName().get('Persona_Fisica').getRecordTypeId();
            // Id recordTypeIdMoral = Schema.SObjectType.Contract.getRecordTypeInfosByDeveloperName().get('Persona_Moral').getRecordTypeId();
            
            Opportunity opp = [SELECT Id, AccountId, Account.RecordType.DeveloperName FROM Opportunity WHERE Id =: oppId]; 
            
            cont.AccountId = opp.AccountId;
            cont.Oportunidad__c = oppId;
            
            // if(opp.Account.RecordType.DeveloperName == 'Prospecto_Persona_Fisica' || opp.Account.RecordType.DeveloperName == 'Afluente_Persona_Fisica' || opp.Account.RecordType.DeveloperName == 'Cliente_Persona_Fisica' ){
                cont.RecordTypeId = recordTypeIdFisica;   
            //}else{
                // cont.RecordTypeId = recordTypeIdMoral;
            //    cont.RecordTypeId = recordTypeIdFisica;
            // }
            
        }else{
            cont.AccountId = '';
            cont.RecordTypeId = '';
        }
        
        return JSON.serialize(cont);
    }
    
    @AuraEnabled(cacheable=true)
    public static String populaCamposInformacionRep(String idCesion){
        
        Informacion_representante_legal__c infoRep = new Informacion_representante_legal__c();
        Cesion_a_Otra_Persona_Fisica_o_Moral__c cesiOtra = new Cesion_a_Otra_Persona_Fisica_o_Moral__c();
        
        if(idCesion != null && idCesion != ''){
            cesiOtra = [SELECT Id, Contrato__c FROM Cesion_a_Otra_Persona_Fisica_o_Moral__c WHERE Id =: idCesion ];	    
            infoRep.Contrato__c = cesiOtra.Contrato__c;
            infoRep.Cesion_a_Otra_Persona_Fisica_o_Moral__c = cesiOtra.Id;
        }else{
            infoRep.Contrato__c = '';
            infoRep.Cesion_a_Otra_Persona_Fisica_o_Moral__c = '';
        }
        
        return JSON.serialize(infoRep);
    } 
}