unpackaged/main/default/objects/Mass_Approval_Config__mdt/Mass_Approval_Config__mdt.object-meta.xml
<CustomObject>
    <label>Mass Approval Config</label>
    <pluralLabel>Mass Approval Configs</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Mass_Approval_Config__mdt/fields/Object_Api_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Api_Name__c</fullName>
    <label>Object Api Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/Plan_de_Venta__c.object-meta.xml
<CustomObject>
    <label>Plan de Venta</label>
    <nameField>
        <displayFormat>Plan de Venta-{000000}</displayFormat>
        <label>Plan de Venta</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plan de Venta</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Casilla_Descuento_Empleado_Javer__c.field-meta.xml
<CustomField>
    <fullName>Casilla_Descuento_Empleado_Javer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Descuento Empleado Javer</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Check_Contrato_Firmado__c.field-meta.xml
<CustomField>
    <fullName>Check_Contrato_Firmado__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Check Contrato Firmado</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Estatus_Plan_de_venta__c.field-meta.xml
<CustomField>
    <fullName>Estatus_Plan_de_venta__c</fullName>
    <label>Estatus Plan de Venta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>En Progreso</fullName>
                <default>true</default>
                <label>En Progreso</label>
            </value>
            <value>
                <fullName>Por Aprobar</fullName>
            </value>
            <value>
                <fullName>Aprobado</fullName>
            </value>
            <value>
                <fullName>Reubicado</fullName>
            </value>
            <value>
                <fullName>Reestructurado</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Excepcion_Descuento_Empleado_JAVER__c.field-meta.xml
<CustomField>
    <fullName>Excepcion_Descuento_Empleado_JAVER__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Excepción Descuento Empleado JAVER2</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Exepcion_Fondo_de_Garantia_Aprobado__c.field-meta.xml
<CustomField>
    <fullName>Exepcion_Fondo_de_Garantia_Aprobado__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Exepción Fondo de Garantía Aprobado</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Fecha_de_actualizacion_plan__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_actualizacion_plan__c</fullName>
    <label>Fecha de actualización plan</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Fecha_Proyeccion_escritura__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Proyeccion_escritura__c</fullName>
    <defaultValue>Today() + 30</defaultValue>
    <label>Fecha Proyección de escritura</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Financiamiento_Plan_de_Venta__c.field-meta.xml
<CustomField>
    <fullName>Financiamiento_Plan_de_Venta__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Financiamiento Plan de Venta</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Fondo_de_Garantia__c.field-meta.xml
<CustomField>
    <fullName>Fondo_de_Garantia__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Fondo de Garantía</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Fondo_de_Garantia_No_Cubierto__c.field-meta.xml
<CustomField>
    <fullName>Fondo_de_Garantia_No_Cubierto__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Fondo de Garantía No Cubierto</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Monto_de_Descuadre_VO__c.field-meta.xml
<CustomField>
    <fullName>Monto_de_Descuadre_VO__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Monto de Descuadre VO</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Paquetes_Promociones_de_Venta_Duplicadas__c.field-meta.xml
<CustomField>
    <fullName>Paquetes_Promociones_de_Venta_Duplicadas__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Este flag y ruta se activa automáticamente cuando se agregan al plan de venta 2 o más productos iguales, considerando el nombre de los Paquetes y/o Promociones.</description>
    <label>Paquetes/Promociones de Venta Duplicadas</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Plan_de_Venta__c.field-meta.xml
<CustomField>
    <fullName>Plan_de_Venta__c</fullName>
    <formula>&quot;Plan de Venta&quot; &amp; &quot; &quot;&amp;  Oportunidad__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Plan de Venta</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Producto_Bonificacion_menor_a_P_M_nim__c.field-meta.xml
<CustomField>
    <fullName>Producto_Bonificacion_menor_a_P_M_nim__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Producto + Bonificación menor a P. Mínimo de Venta</inlineHelpText>
    <label>Prod + Bonif menor a P. Mínimo de Venta</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <description>Identifica si el plan de venta es un plan convencional, o en caso de existir una reestructura, se mostrará el correspondiente como &quot;Reestructura&quot; y el original deberá cambiar a &quot;Plan de Venta Cancelado&quot;</description>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Plan de Venta</fullName>
                <default>true</default>
                <label>Plan de Venta</label>
            </value>
            <value>
                <fullName>Reestructura</fullName>
            </value>
            <value>
                <fullName>Plan de Venta Cancelado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Venta_Anticipada__c.field-meta.xml
<CustomField>
    <fullName>Venta_Anticipada__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Venta Anticipada</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/VO_menor_a_P_M_nimo_de_Venta__c.field-meta.xml
<CustomField>
    <fullName>VO_menor_a_P_M_nimo_de_Venta__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Valor de Operación menor a P. Mínimo de Venta</inlineHelpText>
    <label>V.O. menor a P. Mínimo de Venta</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/MassApprovalTest.cls
/******* Author : Ajay Choudhary (ajay@wakencode.com, Wakencode Technologies)*********
 ******* Last Updated Date : 17th August 2023 ****************************************
 ******* Info : Test Class for MassApproval apex class *******************************
 ******* Update 1 : ________________________________________ *************************
 *************************************************************************************/
@isTest
public class MassApprovalTest {
    
    static testMethod void testMassApproval(){
        Plan_de_Venta__c pagares = new Plan_de_Venta__c(
            Fondo_de_Garantia_No_Cubierto__c = false,                       // Fondo de Garantía No Cubierto
            Exepcion_Fondo_de_Garantia_Aprobado__c = false,                 // Exepción Fondo de Garantía Aprobado
            Tipo__c = 'Plan de Venta',                                      // Tipo
            Estatus_Plan_de_venta__c = 'En Progreso',                       // Estatus Plan de Venta
            Monto_de_Descuadre_VO__c = 0.00,                                // Monto de Descuadre VO
            Casilla_Descuento_Empleado_Javer__c = true,                     // Descuento Empleado Javer
            Excepcion_Descuento_Empleado_JAVER__c = false,                  // Excepción Descuento Empleado JAVER
            Fecha_Proyeccion_escritura__c = Date.today().addDays(120),      // Fecha Proyección de escritura
            Paquetes_Promociones_de_Venta_Duplicadas__c = false,            // Paquetes/Promociones de Venta Duplicadas
            Financiamiento_Plan_de_Venta__c = false,                        // Financiamiento Plan de Venta
            VO_menor_a_P_M_nimo_de_Venta__c = false,                        // V.O. menor a P. Mínimo de Venta
            Producto_Bonificacion_menor_a_P_M_nim__c = false,               // Prod + Bonif menor a P. Mínimo de Venta
            Fondo_de_Garantia__c = false,                                   // Fondo de Garantía
            Venta_Anticipada__c = false,                                    // Venta Anticipada
            Check_Contrato_Firmado__c = false,                              // Check Contrato Firmado
            Revision_APC__c = false,                                        // Revisión APC
            Fecha_de_actualizacion_plan__c = Date.today().addDays(120)      // Fecha de actualización plan
        );
        insert pagares;
        Approval.ProcessSubmitRequest app = new Approval.ProcessSubmitRequest();
        app.setObjectId(pagares.id);
        Approval.ProcessResult result = Approval.process(app);
        Mass_Approval_Config__mdt config = new Mass_Approval_Config__mdt();
        config.MasterLabel = 'Plan de Venta';
        config.Object_Api_Name__c = 'Plan_de_Venta__c';
        config.DeveloperName = 'Plan_de_Venta';
        MassApproval.getObjectConfigs();
        MassApproval.getAllProcessItems('Plan_de_Venta__c', config, 'All');
         MassApproval.getAllProcessItems('Plan_de_Venta__c', config, 'Approved');
        MassApproval.getAllProcessSteps(result.getInstanceId());
        MassApproval.ApprovalRequestData data = new MassApproval.ApprovalRequestData();
        data.actorId = result.getActorIds()[0];
        data.actorName = '';
        data.comments = 'test';
        data.createdByName = 'test';
        data.createdDate = Date.today();
        data.processInstanceId = result.getInstanceId();
        data.recordId = pagares.Id;
        MassApproval.reAssignProcessItems(JSON.serialize(new List<MassApproval.ApprovalRequestData>{data}));
        MassApproval.approveRejectRecords(JSON.serialize(new List<MassApproval.ApprovalRequestData>{data}), 'Approve');
        
    }
    
}