unpackaged/main/default/objects/Contrato__c/Contrato__c.object-meta.xml
<CustomObject>
    <label>Contratos</label>
    <nameField>
        <label>No. Interno</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contratos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Direcciones__c/Direcciones__c.object-meta.xml
<CustomObject>
    <label>Dirección</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Folio</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Direcciones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Direcciones__c/fields/Contrato__c.field-meta.xml
<CustomField>
    <fullName>Contrato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contrato</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Direcciones</relationshipLabel>
    <relationshipName>Direcciones</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Direcciones__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Dirección Afluencia</fullName>
            </value>
            <value>
                <fullName>Dirección Principal</fullName>
            </value>
            <value>
                <fullName>Dirección Laboral</fullName>
            </value>
            <value>
                <fullName>Dirección Empresa</fullName>
            </value>
            <value>
                <fullName>Dirección Principal CO Acreditado</fullName>
            </value>
            <value>
                <fullName>Dirección Laboral CO Acreditado</fullName>
            </value>
            <value>
                <fullName>Dirección Rep Legal Laboral</fullName>
            </value>
            <value>
                <fullName>Dirección Rep Legal / Apoderado</fullName>
            </value>
            <value>
                <fullName>Dirección Tercero Persona Física</fullName>
            </value>
            <value>
                <fullName>Dirección Tercero Laboral Persona Física</fullName>
            </value>
            <value>
                <fullName>Direccion_3ro_Moral_Principal</fullName>
                <label>Dirección 3ro Moral Principal</label>
            </value>
            <value>
                <fullName>Direccion_3ro_Domicilio_Moral</fullName>
                <label>Dirección 3ro Domicilio Moral</label>
            </value>
            <value>
                <fullName>Direccion_3ro_Laboral_Moral</fullName>
                <label>Dirección 3ro Laboral Moral</label>
            </value>
            <value>
                <fullName>Dirección Cesión Principal PF</fullName>
            </value>
            <value>
                <fullName>Dirección Cesión Laboral PF</fullName>
            </value>
            <value>
                <fullName>Dirección Cesión Principal PM</fullName>
            </value>
            <value>
                <fullName>Dirección Cesión Laboral PM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/CLASS_Direcciones.cls
public class CLASS_Direcciones {

    public void validaDireccionesExistentes(list<Direcciones__c> lstNew){
        system.debug('entro');
        Set<String> idsDictaminaciones = new Set<String>();
        
        for(Direcciones__c dir : lstNew){
            idsDictaminaciones.add(dir.Contrato__c);
        }
        
        list<Direcciones__c> lstDirecciones = new list<Direcciones__c>();
        lstDirecciones = [SELECT Id, Name, Tipo__c FROM Direcciones__c WHERE Contrato__c IN: idsDictaminaciones];
        
        if(!lstDirecciones.IsEmpty()){
            for(Direcciones__c dirEntrante : lstNew){
            	for(Direcciones__c dirExistente : lstDirecciones){
                    if(dirEntrante.Tipo__c == dirExistente.Tipo__c){
                        dirEntrante.addError('ya existe una dirección del tipo "' + dirEntrante.Tipo__c + '".');
                    }
            	}    
            }
        }
        
    }
    
    public void validaDireccionesExistentesUp(Map<Id,Direcciones__c> mapOld, list<Direcciones__c> lstNew){
        
        Set<String> idsDictaminaciones = new Set<String>();
        
        for(Direcciones__c dir : lstNew){
            if(mapOld.get(dir.Id).Tipo__c != dir.Tipo__c){
            	idsDictaminaciones.add(dir.Contrato__c);    
            }
        }
        
        if(!idsDictaminaciones.IsEmpty()){
            
            list<Direcciones__c> lstDirecciones = new list<Direcciones__c>();
        	lstDirecciones = [SELECT Id, Name, Tipo__c FROM Direcciones__c WHERE Contrato__c IN: idsDictaminaciones];
            
            for(Direcciones__c dirEntrante : lstNew){
            	for(Direcciones__c dirExistente : lstDirecciones){
                    if(dirEntrante.Tipo__c == dirExistente.Tipo__c){
                        dirEntrante.addError('Ya existe una dirección del tipo "' + dirEntrante.Tipo__c + '".');
                    }
            	}    
            }
        }
        
    }
}