unpackaged/main/default/objects/Ecotecnologia__c/Ecotecnologia__c.object-meta.xml
<CustomObject>
    <label>Acta de Ecotecnología</label>
    <nameField>
        <label>Nombre de Acta</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Histórico Actas de Ecotecnología</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Ecotecnologia__c/fields/AccesoriosBano__c.field-meta.xml
<CustomField>
    <fullName>AccesoriosBano__c</fullName>
    <label>AccesoriosBano</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Ecotecnologia__c/fields/AsientoWC__c.field-meta.xml
<CustomField>
    <fullName>AsientoWC__c</fullName>
    <label>AsientoWC</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Ecotecnologia__c/fields/Bano__c.field-meta.xml
<CustomField>
    <fullName>Bano__c</fullName>
    <label>Bano</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Ecotecnologia__c/fields/BoteBasura__c.field-meta.xml
<CustomField>
    <fullName>BoteBasura__c</fullName>
    <label>BoteBasura</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Ecotecnologia__c/fields/CalentadorSolar__c.field-meta.xml
<CustomField>
    <fullName>CalentadorSolar__c</fullName>
    <label>CalentadorSolar</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Ecotecnologia__c/fields/Cocina__c.field-meta.xml
<CustomField>
    <fullName>Cocina__c</fullName>
    <label>Cocina</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Ecotecnologia__c/fields/Comedor__c.field-meta.xml
<CustomField>
    <fullName>Comedor__c</fullName>
    <label>Comedor</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Ecotecnologia__c/fields/ContratacionServicios__c.field-meta.xml
<CustomField>
    <fullName>ContratacionServicios__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ContratacionServicios</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Ecotecnologia__c/fields/Exteriores__c.field-meta.xml
<CustomField>
    <fullName>Exteriores__c</fullName>
    <label>Exteriores</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Ecotecnologia__c/fields/ExterioresNum__c.field-meta.xml
<CustomField>
    <fullName>ExterioresNum__c</fullName>
    <label>ExterioresNum</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Ecotecnologia__c/fields/FiltroAgua__c.field-meta.xml
<CustomField>
    <fullName>FiltroAgua__c</fullName>
    <label>FiltroAgua</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Ecotecnologia__c/fields/FocoAhorrador__c.field-meta.xml
<CustomField>
    <fullName>FocoAhorrador__c</fullName>
    <label>Foco(s) Ahorrador(es)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Ecotecnologia__c/fields/FocoLED__c.field-meta.xml
<CustomField>
    <fullName>FocoLED__c</fullName>
    <label>FocoLED</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Ecotecnologia__c/fields/Interiores__c.field-meta.xml
<CustomField>
    <fullName>Interiores__c</fullName>
    <label>Interiores</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Ecotecnologia__c/fields/InterioresNum__c.field-meta.xml
<CustomField>
    <fullName>InterioresNum__c</fullName>
    <label>InterioresNum</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Ecotecnologia__c/fields/Jabonera__c.field-meta.xml
<CustomField>
    <fullName>Jabonera__c</fullName>
    <label>Jabonera</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Ecotecnologia__c/fields/LlaveChorro__c.field-meta.xml
<CustomField>
    <fullName>LlaveChorro__c</fullName>
    <label>LlaveChorro</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Ecotecnologia__c/fields/LlaveTarja__c.field-meta.xml
<CustomField>
    <fullName>LlaveTarja__c</fullName>
    <label>LlaveTarja</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Ecotecnologia__c/fields/ManualUsuario__c.field-meta.xml
<CustomField>
    <fullName>ManualUsuario__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ManualUsuario</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Ecotecnologia__c/fields/Mejoras__c.field-meta.xml
<CustomField>
    <fullName>Mejoras__c</fullName>
    <label>Mejoras</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Ecotecnologia__c/fields/MejorasNum__c.field-meta.xml
<CustomField>
    <fullName>MejorasNum__c</fullName>
    <label>MejorasNum</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Ecotecnologia__c/fields/Observaciones__c.field-meta.xml
<CustomField>
    <fullName>Observaciones__c</fullName>
    <label>Observaciones</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Ecotecnologia__c/fields/OtrosDoc__c.field-meta.xml
<CustomField>
    <fullName>OtrosDoc__c</fullName>
    <label>OtrosDoc</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Ecotecnologia__c/fields/OtrosEco__c.field-meta.xml
<CustomField>
    <fullName>OtrosEco__c</fullName>
    <label>OtrosEco</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Ecotecnologia__c/fields/OtrosEcoNum__c.field-meta.xml
<CustomField>
    <fullName>OtrosEcoNum__c</fullName>
    <label>OtrosEcoNum</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Ecotecnologia__c/fields/Paquetes__c.field-meta.xml
<CustomField>
    <fullName>Paquetes__c</fullName>
    <label>Paquetes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Ecotecnologia__c/fields/PaquetesNum__c.field-meta.xml
<CustomField>
    <fullName>PaquetesNum__c</fullName>
    <label>PaquetesNum</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Ecotecnologia__c/fields/Plano__c.field-meta.xml
<CustomField>
    <fullName>Plano__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Plano</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Ecotecnologia__c/fields/PortaRollos__c.field-meta.xml
<CustomField>
    <fullName>PortaRollos__c</fullName>
    <label>PortaRollos</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Ecotecnologia__c/fields/RecamaraPosterior__c.field-meta.xml
<CustomField>
    <fullName>RecamaraPosterior__c</fullName>
    <label>RecamaraPosterior</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Ecotecnologia__c/fields/RecamaraPrincipal__c.field-meta.xml
<CustomField>
    <fullName>RecamaraPrincipal__c</fullName>
    <label>RecamaraPrincipal</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Ecotecnologia__c/fields/Reglamento__c.field-meta.xml
<CustomField>
    <fullName>Reglamento__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Reglamento</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Ecotecnologia__c/fields/Sala__c.field-meta.xml
<CustomField>
    <fullName>Sala__c</fullName>
    <label>Sala</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Ecotecnologia__c/fields/ServiciosDigitales__c.field-meta.xml
<CustomField>
    <fullName>ServiciosDigitales__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ServiciosDigitales</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Ecotecnologia__c/fields/ServiciosPublicos__c.field-meta.xml
<CustomField>
    <fullName>ServiciosPublicos__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ServiciosPublicos</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Ecotecnologia__c/fields/TapaWC__c.field-meta.xml
<CustomField>
    <fullName>TapaWC__c</fullName>
    <label>TapaWC</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Ecotecnologia__c/fields/Toallero__c.field-meta.xml
<CustomField>
    <fullName>Toallero__c</fullName>
    <label>Toallero</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Paquetes__c/Paquetes__c.object-meta.xml
<CustomObject>
    <label>Paquete</label>
    <nameField>
        <label>Nombre de Paquete</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Paquetes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/ActasPDFCtrl.cls
public class ActasPDFCtrl {
	public Ecotecnologia__c ECO {get;set;}
    public String ActaName {get;set;}
    public ActasPDFCtrl(){
        ActaName = Apexpages.currentPage().getParameters().get('ActaName');
        try{
            ECO = [SELECT AccesoriosBano__c, AsientoWC__c, Bano__c, BoteBasura__c, 
                   CalentadorSolar__c, Cocina__c, Comedor__c, FiltroAgua__c, FocoAhorrador__c,
                   FocoLED__c, Jabonera__c, LlaveChorro__c, LlaveTarja__c, Mejoras__c, MejorasNum__c,
                   Observaciones__c, OtrosDoc__c, OtrosEco__c, OtrosEcoNum__c, Paquetes__c, PaquetesNum__c,
                   PortaRollos__c, RecamaraPosterior__c, RecamaraPrincipal__c, Sala__c, TapaWC__c, Toallero__c,
                   InterioresNum__c, ExterioresNum__c, Interiores__c, Exteriores__c, ServiciosPublicos__c, Plano__c,
                   ContratacionServicios__c, Reglamento__c, ServiciosDigitales__c, ManualUsuario__c
                   FROM Ecotecnologia__c WHERE Name =: ActaName LIMIT 1];
        }catch(Exception e){
            ECO = [SELECT AccesoriosBano__c, AsientoWC__c, Bano__c, BoteBasura__c, 
                   CalentadorSolar__c, Cocina__c, Comedor__c, FiltroAgua__c, FocoAhorrador__c,
                   FocoLED__c, Jabonera__c, LlaveChorro__c, LlaveTarja__c, Mejoras__c, MejorasNum__c,
                   Observaciones__c, OtrosDoc__c, OtrosEco__c, OtrosEcoNum__c, Paquetes__c, PaquetesNum__c,
                   PortaRollos__c, RecamaraPosterior__c, RecamaraPrincipal__c, Sala__c, TapaWC__c, Toallero__c,
                   InterioresNum__c, ExterioresNum__c, Interiores__c, Exteriores__c, ServiciosPublicos__c, Plano__c,
                   ContratacionServicios__c, Reglamento__c, ServiciosDigitales__c, ManualUsuario__c
                   FROM Ecotecnologia__c WHERE Name =: 'default' LIMIT 1];
        }
        if(UserInfo.getUiTheme() == 'Theme4t'){
            Apexpages.currentPage().getHeaders().put('content-disposition', 'attachment; filename=' + ActaName + '.pdf');
        }else{
        }
    }
}