unpackaged/main/default/objects/Colaborador_Javer__c/Colaborador_Javer__c.object-meta.xml
<CustomObject>
    <label>Colaborador Javer</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Colaborador Javer</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Lead/fields/Colaborador_Javer__c.field-meta.xml
<CustomField>
    <fullName>Colaborador_Javer__c</fullName>
    <label>Colaborador Javer</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Asesor__c.field-meta.xml
<CustomField>
    <fullName>Asesor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asesor</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>(1 OR 2) AND 3</booleanFilter>
        <filterItems>
            <field>User.Title</field>
            <operation>equals</operation>
            <value>ASESOR</value>
        </filterItems>
        <filterItems>
            <field>User.Title</field>
            <operation>equals</operation>
            <value>GENERICO</value>
        </filterItems>
        <filterItems>
            <field>User.FraccionamientoAutorizados__c</field>
            <operation>contains</operation>
            <valueField>$Source.Nombre_Fraccionamiento__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Procesos_de_Ventas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Colaborador_Javer__c.field-meta.xml
<CustomField>
    <fullName>Colaborador_Javer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Colaborador Javer</label>
    <referenceTo>Colaborador_Javer__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Estado_de_aprobacion__c.field-meta.xml
<CustomField>
    <fullName>Estado_de_aprobacion__c</fullName>
    <label>Estado de aprobación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprobado</fullName>
            </value>
            <value>
                <fullName>En Proceso</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
            <value>
                <fullName>Recuperado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Lead_Profiler__c.field-meta.xml
<CustomField>
    <fullName>Lead_Profiler__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead Profiler</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Oportunidades1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Proceso_de_aprobaci_n__c.field-meta.xml
<CustomField>
    <fullName>Proceso_de_aprobaci_n__c</fullName>
    <description>Utilizado para saber el proceso de aprobación ejecutado y saber el campo de lookup a actualizar (los valores se asignan en directamente en los procesos de aprobación).
Visible solo para el admin</description>
    <inlineHelpText>Utilizado para saber el proceso de aprobación ejecutado y saber el campo de lookup a actualizar (los valores se asignan en directamente en los procesos de aprobación).
Visible solo para el admin</inlineHelpText>
    <label>Proceso de aprobación</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Prospectador__c.field-meta.xml
<CustomField>
    <fullName>Prospectador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prospectador</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>User.Title</field>
            <operation>equals</operation>
            <value>PROSPECTADOR</value>
        </filterItems>
        <filterItems>
            <field>User.Title</field>
            <operation>equals</operation>
            <value>GENERICO</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Valores_previos__c.field-meta.xml
<CustomField>
    <fullName>Valores_previos__c</fullName>
    <description>Unicamente para guardar los valores previos de los campos de lookup &quot;Asesor&quot; y &quot;Lead Profiler&quot; cuando se envia a aprobación y / o se rechaza la oportunidad
Visible solo para el admin del sistema</description>
    <inlineHelpText>Unicamente para guardar los valores previos de los campos de lookup &quot;Asesor&quot; y &quot;Lead Profiler&quot; cuando se envia a aprobación y / o se rechaza la oportunidad
Visible solo para el admin del sistema</inlineHelpText>
    <label>Valores previos</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/CLASS_lookupOppValorPrevio.cls
public class CLASS_lookupOppValorPrevio {
    
    /* Logica */ 
    public static void executeBefore(List<Opportunity> listaOppNew, Map<Id,Opportunity> mapaOppOld){
        for(Opportunity oppNew : listaOppNew){
            // Asesor
            if(oppNew.Asesor__c != mapaOppOld.get(oppNew.Id).Asesor__c){
                
                oppNew.Valores_previos__c = mapaOppOld.get(oppNew.Id).Asesor__c;
            }
            // Prospectador
            if(oppNew.Prospectador__c != mapaOppOld.get(oppNew.Id).Prospectador__c){
                
                oppNew.Valores_previos__c = mapaOppOld.get(oppNew.Id).Prospectador__c;
            }
            // Lead Profiler
            else if(oppNew.Lead_Profiler__c != mapaOppOld.get(oppNew.Id).Lead_Profiler__c){
                
                oppNew.Valores_previos__c = mapaOppOld.get(oppNew.Id).Lead_Profiler__c;
            }
            // Colaborador Javer
            else if(oppNew.Colaborador_Javer__c != mapaOppOld.get(oppNew.Id).Colaborador_Javer__c){
                
                oppNew.Valores_previos__c = mapaOppOld.get(oppNew.Id).Colaborador_Javer__c;
            }
            
        }
    }
    public static void executeAfter(){
        Map<Id,Opportunity> mapaOpp = new Map<Id,Opportunity>();
        //Map<Id,Opportunity> mapaOppRelacionados = new Map<Id,Opportunity>();
        
        for(SObject so : Trigger.new){
            SObject before = Trigger.oldMap.get(so.Id);
            
            Opportunity oppNew = (Opportunity) so;
            Opportunity oppOld = (Opportunity) before;
            // Regresar campos a sus valores originales
            if(oppNew.Estado_de_aprobacion__c == 'Rechazado' && oppOld.Estado_de_aprobacion__c != 'Rechazado'){
                mapaOpp.put(oppNew.Id,oppOld);
                
            }
        }
        
        // Actualizar oportunidad 
        if(mapaOpp.size() > 0){
            crearOpp(mapaOpp);
        }
    }
    
    /* Crear oportunidad a actualizar (Rechazo de aprobación) */
    public static void crearOpp(Map<Id,Opportunity> mapaOpp){
        List<Opportunity> actualizarOpp = new List<Opportunity>();
        for(Opportunity opp : mapaOpp.values()){
            Opportunity opp2 = new Opportunity();
            opp2.Id = opp.Id;
            // Asesor = Proceso de aprobación "Cambia el Asesor en la oportunidad" (1)
            if(opp.Proceso_de_aprobaci_n__c == '1'){
                opp2.Asesor__c = opp.Valores_previos__c; 
            }
            // Prospectador = Proceso de aprobación "Aprobación prospectador" (2)
            else if(opp.Proceso_de_aprobaci_n__c == '2'){
                opp2.Prospectador__c = opp.Valores_previos__c;
            }
            // Lead Profiler = Proceso de aprobación "Aprobación lead profiler" (3)
            else if(opp.Proceso_de_aprobaci_n__c == '3'){
                opp2.Lead_Profiler__c = opp.Valores_previos__c;
            }
            // Colaborador Javer = Proceso de aprobación "Aprobación colaborador Javer" (4)
            else if(opp.Proceso_de_aprobaci_n__c == '4'){
                opp2.Colaborador_Javer__c = opp.Valores_previos__c;
            }
            actualizarOpp.add(opp2);
            
        }
        // Actualizar oportunidad
        System.debug('JG actualizarOpp.size(): '+actualizarOpp.size());
        if(actualizarOpp.size() > 0){
            Database.SaveResult [] updateResult = Database.update(actualizarOpp, false);
        }
    }
}