unpackaged/main/default/objects/Catch__c/Catch__c.object-meta.xml
<CustomObject>
    <label>Catch</label>
    <nameField>
        <displayFormat>Catch-{0000000000}</displayFormat>
        <label>Nombre de Catch</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Catchs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Catch__c/fields/Campo__c.field-meta.xml
<CustomField>
    <fullName>Campo__c</fullName>
    <label>Campo</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Catch__c/fields/Causa__c.field-meta.xml
<CustomField>
    <fullName>Causa__c</fullName>
    <label>Causa</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Catch__c/fields/Descripcion__c.field-meta.xml
<CustomField>
    <fullName>Descripcion__c</fullName>
    <description>Descripción del error. Comunmente el mensaje del Catch y descripciones extras.</description>
    <label>Descripción</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Catch__c/fields/Numero_de_Linea__c.field-meta.xml
<CustomField>
    <fullName>Numero_de_Linea__c</fullName>
    <label>Numero de Línea</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Catch__c/fields/StackTrace__c.field-meta.xml
<CustomField>
    <fullName>StackTrace__c</fullName>
    <label>StackTrace</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Catch__c/recordTypes/DmlException.recordType-meta.xml
<RecordType>
    <fullName>DmlException</fullName>
    <active>true</active>
    <description>Registros generados por Catch de DML</description>
    <label>DmlException</label>
</RecordType>

unpackaged/main/default/objects/Catch__c/recordTypes/Exception.recordType-meta.xml
<RecordType>
    <fullName>Exception</fullName>
    <active>true</active>
    <description>Generica</description>
    <label>Exception</label>
</RecordType>

unpackaged/main/default/objects/Catch__c/recordTypes/SObjectException.recordType-meta.xml
<RecordType>
    <fullName>SObjectException</fullName>
    <active>true</active>
    <label>SObjectException</label>
</RecordType>

unpackaged/main/default/objects/Sistema__c/Sistema__c.object-meta.xml
<CustomObject>
    <label>Sistema</label>
    <nameField>
        <label>Nombre de Sistema</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sistemas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Sistema__c/fields/Correo_Recep_XML_Asunto__c.field-meta.xml
<CustomField>
    <fullName>Correo_Recep_XML_Asunto__c</fullName>
    <label>Correo Recep.XML-Asunto</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Sistema__c/fields/Correo_Recep_XML_Direcciones__c.field-meta.xml
<CustomField>
    <fullName>Correo_Recep_XML_Direcciones__c</fullName>
    <description>Direcciones destino. Las direcciones se separan con dos puntos (&quot;:&quot;)</description>
    <inlineHelpText>Direcciones destino. Las direcciones se separan con dos puntos (&quot;:&quot;)</inlineHelpText>
    <label>Correo Recep.XML-Direcciones</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Sistema__c/fields/Correo_Recep_XML_Mensaje__c.field-meta.xml
<CustomField>
    <fullName>Correo_Recep_XML_Mensaje__c</fullName>
    <label>Correo Recep.XML-Mensaje</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Sistema__c/fields/End_Point_Descripcion__c.field-meta.xml
<CustomField>
    <fullName>End_Point_Descripcion__c</fullName>
    <label>End Point - Descripción</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Sistema__c/fields/Limpieza_de_Aprob_Agendada__c.field-meta.xml
<CustomField>
    <fullName>Limpieza_de_Aprob_Agendada__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Al activarse se agenda un JOB de acuerdo a la recurrencia capturada en &quot;Limpieza Recurrencia&quot;. El Id del JOB generado se guarda el &quot;Limpieza JOB Id&quot;. Al momento de ejecutarse el JOB debe existir un valor en Máxima antiguedad de días sin resolución.</description>
    <inlineHelpText>Al activarse se agenda un JOB de acuerdo a la recurrencia capturada en &quot;Limpieza Recurrencia&quot;. El Id del JOB generado se guarda el &quot;Limpieza JOB Id&quot;. Al momento de ejecutarse el JOB debe existir un valor en Máxima antiguedad de días sin resolución.</inlineHelpText>
    <label>Limpieza de Aprob.Agendada</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Sistema__c/fields/Limpieza_Job_Id__c.field-meta.xml
<CustomField>
    <fullName>Limpieza_Job_Id__c</fullName>
    <description>El Id que genera Salesforce al agendar un JOB. Cuando ya está generado este Id puede utilizarse para detener el JOB.</description>
    <inlineHelpText>El Id que genera Salesforce al agendar un JOB. Cuando ya está generado este Id puede utilizarse para detener el JOB.</inlineHelpText>
    <label>Limpieza Job Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Sistema__c/fields/Limpieza_Recurrencia__c.field-meta.xml
<CustomField>
    <fullName>Limpieza_Recurrencia__c</fullName>
    <description>Es la cadena de texto que utiliza el scheduler para saber la recurrencia del JOB.</description>
    <inlineHelpText>Es la cadena de texto que utiliza el scheduler para saber la recurrencia del JOB.</inlineHelpText>
    <label>Limpieza Recurrencia</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Sistema__c/fields/Max_antiguedad_sin_resolucion__c.field-meta.xml
<CustomField>
    <fullName>Max_antiguedad_sin_resolucion__c</fullName>
    <description>Es un número entero. Es la máxima antigüedad de días para aprobaciones en estatus de &quot;En Proceso de Aprobación&quot;. Las que se encuentren fuera de este rango entran en la lista de remoción. Es necesario este  valor para activar la limpieza programada.</description>
    <inlineHelpText>Es un número entero. Es la máxima antigüedad de días para aprobaciones en estatus de &quot;En Proceso de Aprobación&quot;. Las que se encuentren fuera de este rango entran en la lista de remoción. Es necesario este valor para activar la limpieza programada.</inlineHelpText>
    <label>Máx.antigüedad sin resolución</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/User/fields/EmpId1__c.field-meta.xml
<CustomField>
    <fullName>EmpId1__c</fullName>
    <label>EmpId1</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/User/fields/UserSharePoint__c.field-meta.xml
<CustomField>
    <fullName>UserSharePoint__c</fullName>
    <label>UserSharePoint</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/Javer_ShPn_Util_Test.cls
@isTest 
public class Javer_ShPn_Util_Test {
    
    private static User CreateUserTest(String strProfile){
        Profile prof = [SELECT Id FROM Profile WHERE Name=:strProfile];
        User user = new User();
        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        System.runAs (thisUser) {
            user.FirstName = 'Test';
            user.LastName = 'Name';
            user.CompanyName = 'IT Test Company';
            user.MobilePhone = '123-456-7890';
            user.EmpId1__c = '1-TEST';
            user.UserSharePoint__c = 'test';
            user.Username = 'testUser-' + generateRandomString() + '@test.com';
            user.Email = 'testUser-' + generateRandomString() + '@test.com';
            user.Alias = 'test';
            user.CommunityNickname = 'test1';
            user.TimeZoneSidKey = 'America/New_York';
            user.LocaleSidKey = 'en_US';
            user.EmailEncodingKey = 'UTF-8';
            user.ProfileId = prof.Id;
            user.LanguageLocaleKey = 'en_US';
            
            user.Street = '123 Test St';
            user.City = 'Testcity';
            user.State = 'va';
            user.PostalCode = '23223';
            user.Country = 'USA';
            try{ 
                insert user;
            
            } catch(DmlException e) { System.assertEquals('FIELD_CUSTOM_VALIDATION_EXCEPTION' , e.getDmlStatusCode(0) );  String rtCatch = Schema.SObjectType.Catch__c.getRecordTypeInfosByName().get('DmlException').getRecordTypeId(); Catch__c newCatch = new Catch__c(); newCatch.RecordTypeId = rtCatch; newCatch.Tipo__c = String.ValueOf(e.getDmlType(0)); newCatch.descripcion__c = e.getDmlMessage(0); newCatch.Campo__c = e.getDmlFieldNames(0)[0]; Database.insert(newCatch,false);
            } catch(SObjectException e) { System.debug('SObjectException caught: ' + e.getMessage()); if (e!=null){ if (e.getMessage()!=null){ Catch__c newCatch = new Catch__c(); String rtCatch = Schema.SObjectType.Catch__c.getRecordTypeInfosByName().get('Exception').getRecordTypeId(); String strCause; if (e.getCause()!=null){ Exception ExceptionCause =  e.getCause();strCause = ExceptionCause.getMessage();} newCatch.Causa__c = strCause; newCatch.RecordTypeId = rtCatch; newCatch.Tipo__c = e.getTypeName(); newCatch.descripcion__c = e.getMessage(); newCatch.Numero_de_Linea__c = e.getLineNumber(); newCatch.StackTrace__c = e.getStackTraceString(); Database.insert(newCatch,false); } } 
            } catch (Exception e) { if (e!=null){ if (e.getMessage()!=null){ Catch__c newCatch = new Catch__c(); String rtCatch = Schema.SObjectType.Catch__c.getRecordTypeInfosByName().get('Exception').getRecordTypeId(); String strCause; if (e.getCause()!=null){ Exception ExceptionCause =  e.getCause();strCause = ExceptionCause.getMessage();} newCatch.Causa__c = strCause; newCatch.RecordTypeId = rtCatch; newCatch.Tipo__c = e.getTypeName(); newCatch.descripcion__c = e.getMessage(); newCatch.Numero_de_Linea__c = e.getLineNumber(); newCatch.StackTrace__c = e.getStackTraceString(); Database.insert(newCatch,false); } } 
            } //catch
            
            Sistema__c Sistema = CreateSistemaTest('Configuracion en Javer ShPn Util-Test');
            //Javer_Util_Future.updatePermissionSet(user.Id);
            PermissionSet ps = [Select Id, Name, Label, Description FROM PermissionSet WHERE Name = 'Usuario_SharePoint' LIMIT 1];
            PermissionSetAssignment psa = new PermissionSetAssignment();
            psa.AssigneeId = user.Id;
            psa.PermissionSetId = ps.Id;
            try{ 
                insert psa;  
            } catch(DmlException e) { System.assertEquals('FIELD_CUSTOM_VALIDATION_EXCEPION' , e.getDmlStatusCode(0) );  String rtCatch = Schema.SObjectType.Catch__c.getRecordTypeInfosByName().get('DmlException').getRecordTypeId(); Catch__c newCatch = new Catch__c(); newCatch.RecordTypeId = rtCatch; newCatch.Tipo__c = String.ValueOf(e.getDmlType(0)); newCatch.descripcion__c = e.getDmlMessage(0); newCatch.Campo__c = e.getDmlFieldNames(0)[0]; Database.insert(newCatch,false);System.Debug('*** newCatch *** '+newCatch);
            } catch(SObjectException e) { System.debug('SObjectException caught: ' + e.getMessage()); if (e!=null){ if (e.getMessage()!=null){ Catch__c newCatch = new Catch__c(); String rtCatch = Schema.SObjectType.Catch__c.getRecordTypeInfosByName().get('Exception').getRecordTypeId(); String strCause; if (e.getCause()!=null){ Exception ExceptionCause =  e.getCause();strCause = ExceptionCause.getMessage();} newCatch.Causa__c = strCause; newCatch.RecordTypeId = rtCatch; newCatch.Tipo__c = e.getTypeName(); newCatch.descripcion__c = e.getMessage(); newCatch.Numero_de_Linea__c = e.getLineNumber(); newCatch.StackTrace__c = e.getStackTraceString(); Database.insert(newCatch,false); System.Debug('*** newCatch *** '+newCatch);} } 
            } catch (Exception e) { if (e!=null){ if (e.getMessage()!=null){ Catch__c newCatch = new Catch__c(); String rtCatch = Schema.SObjectType.Catch__c.getRecordTypeInfosByName().get('Exception').getRecordTypeId(); String strCause; if (e.getCause()!=null){ Exception ExceptionCause =  e.getCause();strCause = ExceptionCause.getMessage();} newCatch.Causa__c = strCause; newCatch.RecordTypeId = rtCatch; newCatch.Tipo__c = e.getTypeName(); newCatch.descripcion__c = e.getMessage(); newCatch.Numero_de_Linea__c = e.getLineNumber(); newCatch.StackTrace__c = e.getStackTraceString(); Database.insert(newCatch,false); System.Debug('*** newCatch *** '+newCatch);} } 
            } //catch
        }
        return user;
    }
    
    private static Sistema__c CreateSistemaTest(String strName){
        
        Sistema__c Sistema = new Sistema__c();
        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        //System.runAs (thisUser) {
            Sistema.Name = strName;
            Sistema.Correo_Recep_XML_Asunto__c = 'Asunto';
            Sistema.Correo_Recep_XML_Direcciones__c = 'example@example.com';
            Sistema.Correo_Recep_XML_Mensaje__c = 'Mensaje';
            Sistema.End_Point__c = 'https://endpoint.example.com/url_wrapper';
            Sistema.End_Point_Descripcion__c = 'Direccion de EndPoint de Prueba';
            Sistema.Limpieza_de_Aprob_Agendada__c = false;
            Sistema.Limpieza_Job_Id__c = '';
            Sistema.Limpieza_Recurrencia__c ='0 41 18 * * ?';
            Sistema.Max_antiguedad_sin_resolucion__c =1;
            try{ 
                insert Sistema;  
            } catch(DmlException e) { System.assertEquals('FIELD_CUSTOM_VALIDATION_EXCEPION' , e.getDmlStatusCode(0) );  String rtCatch = Schema.SObjectType.Catch__c.getRecordTypeInfosByName().get('DmlException').getRecordTypeId(); Catch__c newCatch = new Catch__c(); newCatch.RecordTypeId = rtCatch; newCatch.Tipo__c = String.ValueOf(e.getDmlType(0)); newCatch.descripcion__c = e.getDmlMessage(0); newCatch.Campo__c = e.getDmlFieldNames(0)[0]; Database.insert(newCatch,false);System.Debug('*** newCatch *** '+newCatch);
            } catch(SObjectException e) { System.debug('SObjectException caught: ' + e.getMessage()); if (e!=null){ if (e.getMessage()!=null){ Catch__c newCatch = new Catch__c(); String rtCatch = Schema.SObjectType.Catch__c.getRecordTypeInfosByName().get('Exception').getRecordTypeId(); String strCause; if (e.getCause()!=null){ Exception ExceptionCause =  e.getCause();strCause = ExceptionCause.getMessage();} newCatch.Causa__c = strCause; newCatch.RecordTypeId = rtCatch; newCatch.Tipo__c = e.getTypeName(); newCatch.descripcion__c = e.getMessage(); newCatch.Numero_de_Linea__c = e.getLineNumber(); newCatch.StackTrace__c = e.getStackTraceString(); Database.insert(newCatch,false); System.Debug('*** newCatch *** '+newCatch);} } 
            } catch (Exception e) { if (e!=null){ if (e.getMessage()!=null){ Catch__c newCatch = new Catch__c(); String rtCatch = Schema.SObjectType.Catch__c.getRecordTypeInfosByName().get('Exception').getRecordTypeId(); String strCause; if (e.getCause()!=null){ Exception ExceptionCause =  e.getCause();strCause = ExceptionCause.getMessage();} newCatch.Causa__c = strCause; newCatch.RecordTypeId = rtCatch; newCatch.Tipo__c = e.getTypeName(); newCatch.descripcion__c = e.getMessage(); newCatch.Numero_de_Linea__c = e.getLineNumber(); newCatch.StackTrace__c = e.getStackTraceString(); Database.insert(newCatch,false); System.Debug('*** newCatch *** '+newCatch);} } 
            } //catch
            
        //}
        
        return Sistema;
    }
    
    private static String generateRandomString() {
        return '' + math.rint( math.random() * 100000 );
    }
    
    
    
    static testMethod void Proveedores_test() {
       
       User userSharePoint = CreateUserTest('Force.com - A.S.Aprobador');
       
       //System.Debug('*** Sistema *** '+Sistema);
       test.startTest();
       
       Javer_ShPn_Util JaverShPnUtil = new Javer_ShPn_Util();
       Javer_ShPn_Util.Proveedores_test();
       test.stopTest();
    }
    
    static testMethod void Proveedores_Xtest() {
       User userSharePoint = CreateUserTest('Force.com - A.S.Aprobador');
       //Sistema__c Sistema = CreateSistemaTest('Configuracion en Javer ShPn Util-Test');
       //System.Debug('*** Sistema *** '+Sistema);
        test.startTest();
       Javer_ShPn_Util JaverShPnUtil = new Javer_ShPn_Util();
       Javer_ShPn_Util.Proveedores_testX();
       test.stopTest();
    }
    
    static testMethod void Contrato_test() {
       User userSharePoint = CreateUserTest('Force.com - A.S.Aprobador');
       //Sistema__c Sistema = CreateSistemaTest('Configuracion en Javer ShPn Util-Test');
       test.startTest();
       Javer_ShPn_Util JaverShPnUtil = new Javer_ShPn_Util();
       Javer_ShPn_Util.Contrato_test();
       test.stopTest();
    }
    
    static testMethod void Contrato_testX() {
       User userSharePoint = CreateUserTest('Force.com - A.S.Aprobador');
       //Sistema__c Sistema = CreateSistemaTest('Configuracion en Javer ShPn Util-Test');
       test.startTest();
       Javer_ShPn_Util JaverShPnUtil = new Javer_ShPn_Util();
       Javer_ShPn_Util.Contrato_testX();
       test.stopTest();
    }
    
    static testMethod void Insumo_test() {
       User userSharePoint = CreateUserTest('Force.com - A.S.Aprobador');
       //Sistema__c Sistema = CreateSistemaTest('Configuracion en Javer ShPn Util-Test');
       test.startTest();
       Javer_ShPn_Util JaverShPnUtil = new Javer_ShPn_Util();
       Javer_ShPn_Util.Insumo_test();
       test.stopTest();
    }
    
    static testMethod void Insumo_testX() {
       User userSharePoint = CreateUserTest('Force.com - A.S.Aprobador');
       //Sistema__c Sistema = CreateSistemaTest('Configuracion en Javer ShPn Util-Test');
       test.startTest();
       Javer_ShPn_Util JaverShPnUtil = new Javer_ShPn_Util();
       Javer_ShPn_Util.Insumo_testX();
       test.stopTest();
    }
    
}