unpackaged/main/default/objects/Casos_Residente__c/Casos_Residente__c.object-meta.xml
<CustomObject>
    <label>Caso ATC</label>
    <nameField>
        <displayFormat>CAS-{00000000}</displayFormat>
        <label>Folio</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Casos ATC</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Casos_Residente__c/fields/Clasificacion__c.field-meta.xml
<CustomField>
    <fullName>Clasificacion__c</fullName>
    <label>Clasificación</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Tipo__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A1. Corto circuito</fullName>
            </value>
            <value>
                <fullName>A2. Obstrucción</fullName>
            </value>
            <value>
                <fullName>A3. Falta cableado</fullName>
            </value>
            <value>
                <fullName>A4. Falta Accesorio</fullName>
            </value>
            <value>
                <fullName>A5. Falta guía CFE</fullName>
            </value>
            <value>
                <fullName>A6. Falta Guía TV-Cable</fullName>
            </value>
            <value>
                <fullName>A7. Accesorio Dañado y/o Sin Energia</fullName>
            </value>
            <value>
                <fullName>A8. Accesorio mal instalado</fullName>
            </value>
            <value>
                <fullName>A9. Variacion de Voltaje</fullName>
            </value>
            <value>
                <fullName>A10. Filtración por Ductos</fullName>
            </value>
            <value>
                <fullName>A11. Ducto tapado</fullName>
            </value>
            <value>
                <fullName>A12. Otro</fullName>
            </value>
            <value>
                <fullName>A13.Falta de guía de minisplit</fullName>
            </value>
            <value>
                <fullName>B1. Instalación Tapada</fullName>
            </value>
            <value>
                <fullName>B10. Instalación sanitaria</fullName>
            </value>
            <value>
                <fullName>B2. Falta de conexión</fullName>
            </value>
            <value>
                <fullName>B3. Fugas</fullName>
            </value>
            <value>
                <fullName>B4. Mala Instalacion</fullName>
            </value>
            <value>
                <fullName>B5. Dañado</fullName>
            </value>
            <value>
                <fullName>B6. Faltante</fullName>
            </value>
            <value>
                <fullName>B7. Humedad en Muro / Losa</fullName>
            </value>
            <value>
                <fullName>B8. Humedad en Pluvial</fullName>
            </value>
            <value>
                <fullName>B9. Otros</fullName>
            </value>
            <value>
                <fullName>C1. Tapado</fullName>
            </value>
            <value>
                <fullName>C2. Falta de Conexión</fullName>
            </value>
            <value>
                <fullName>C3. Fuga</fullName>
            </value>
            <value>
                <fullName>C4. Mala Instalacion</fullName>
            </value>
            <value>
                <fullName>C5. Dañado</fullName>
            </value>
            <value>
                <fullName>C6. Faltante</fullName>
            </value>
            <value>
                <fullName>C7. Falta de Presion</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Casos_Residente__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Clientes ATC</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Casos ATC</relationshipLabel>
    <relationshipName>Casos_Residentes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Casos_Residente__c/fields/DiasVencimiento__c.field-meta.xml
<CustomField>
    <fullName>DiasVencimiento__c</fullName>
    <label>Días Vencimiento</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Casos_Residente__c/fields/Garantiavencida__c.field-meta.xml
<CustomField>
    <fullName>Garantiavencida__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Garantía vencida</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Casos_Residente__c/fields/Nomenclatura__c.field-meta.xml
<CustomField>
    <fullName>Nomenclatura__c</fullName>
    <label>Nomenclatura</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Casos_Residente__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A. Instalación eléctrica</fullName>
            </value>
            <value>
                <fullName>B. Instalacion sanitaria</fullName>
            </value>
            <value>
                <fullName>C. Instalacion hidráulica</fullName>
            </value>
            <value>
                <fullName>D. Instalación gas</fullName>
            </value>
            <value>
                <fullName>E. Albañilería</fullName>
            </value>
            <value>
                <fullName>F. Acabados Interior</fullName>
            </value>
            <value>
                <fullName>G. Acabado Exterior</fullName>
            </value>
            <value>
                <fullName>H. Aluminio</fullName>
            </value>
            <value>
                <fullName>I. Puertas</fullName>
            </value>
            <value>
                <fullName>J. Impermeabilización</fullName>
            </value>
            <value>
                <fullName>K. Herrería</fullName>
            </value>
            <value>
                <fullName>L. Urbanización</fullName>
            </value>
            <value>
                <fullName>M. Infraestructura</fullName>
            </value>
            <value>
                <fullName>N. Accesorios</fullName>
            </value>
            <value>
                <fullName>O. Servicios</fullName>
            </value>
            <value>
                <fullName>P. Organización Vecinal</fullName>
            </value>
            <value>
                <fullName>Q. Ventas</fullName>
            </value>
            <value>
                <fullName>R. Seguimiento de Ventas</fullName>
            </value>
            <value>
                <fullName>S. Fechas</fullName>
            </value>
            <value>
                <fullName>T. Quejas</fullName>
            </value>
            <value>
                <fullName>U. Cobranza Post.Venta</fullName>
            </value>
            <value>
                <fullName>V. Solicitudes</fullName>
            </value>
            <value>
                <fullName>W. Otros</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Casos_Residente__c/fields/ViviendaProceso__c.field-meta.xml
<CustomField>
    <fullName>ViviendaProceso__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Vivienda</label>
    <referenceTo>Inventario__c</referenceTo>
    <relationshipLabel>Casos ATC</relationshipLabel>
    <relationshipName>Casos_ATC</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Casos_Residente__c/recordTypes/Servicios.recordType-meta.xml
<RecordType>
    <fullName>Servicios</fullName>
    <active>true</active>
    <label>Servicios</label>
</RecordType>

unpackaged/main/default/objects/Entrega__c/Entrega__c.object-meta.xml
<CustomObject>
    <label>Entrega</label>
    <nameField>
        <label>Nombre de Entrega</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entregas</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Entrega__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cliente</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Clientes ATC</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Entregas</relationshipLabel>
    <relationshipName>Entregas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Entrega__c/fields/FechaEntrega__c.field-meta.xml
<CustomField>
    <fullName>FechaEntrega__c</fullName>
    <label>Fecha de Entrega</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Entrega__c/fields/Inventario__c.field-meta.xml
<CustomField>
    <fullName>Inventario__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventario</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Inventario__c.Cuenta__c</field>
            <operation>equals</operation>
            <valueField>$Source.Cuenta__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Estatus__c</field>
            <operation>equals</operation>
            <value>Cancelado</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Inventario__c</referenceTo>
    <relationshipLabel>Entregas</relationshipLabel>
    <relationshipName>Entregas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/Inventario__c.object-meta.xml
<CustomObject>
    <label>Proceso ATC</label>
    <nameField>
        <label>Id Vivienda</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProcesosATC</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Inventario__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Inventarios</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Entregada__c.field-meta.xml
<CustomField>
    <fullName>Entregada__c</fullName>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Por Entregar</fullName>
            </value>
            <value>
                <fullName>No Entregado</fullName>
            </value>
            <value>
                <fullName>Entregado</fullName>
            </value>
            <value>
                <fullName>Agendada</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/FechaEntrega__c.field-meta.xml
<CustomField>
    <fullName>FechaEntrega__c</fullName>
    <label>Fecha de Entrega</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Vencimiento__c/Vencimiento__c.object-meta.xml
<CustomObject>
    <label>Vencimiento</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Nombre de Vencimientos</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vencimientos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Vencimiento__c/fields/VencimientoDias__c.field-meta.xml
<CustomField>
    <fullName>VencimientoDias__c</fullName>
    <label>Vencimiento en Días</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/CrearCasoController.cls
public class CrearCasoController {
    
    public Casos_Residente__c caso {get;set;}
    public Entrega__c entrega {get;set;}
    
    public boolean showButtons {get;set;}
    public CrearCasoController(ApexPages.StandardController controller) {
        RecordType garantia = [SELECT ID, Name FROM RecordType WHERE Name = 'Servicios' LIMIT 1];
        
        caso = (Casos_Residente__c) controller.getRecord();
        caso.OwnerId = UserInfo.getUserId();
        
        String idInventario = '';
        showButtons = true;
        try{
            idInventario = ApexPages.currentPage().getParameters().get('i');
            Inventario__c i = [SELECT ID, Name, Cuenta__c,Entregada__c FROM Inventario__c WHERE Id =: idInventario];
            try{
                entrega = [SELECT Id, Name, FechaEntrega__c FROM Entrega__C WHERE Inventario__c = :i.Id ORDER BY CreatedDate DESC LIMIT 1];
            }catch(Exception o){
                
            }
            
            caso.ViviendaProceso__c = i.Id;
            caso.Cuenta__c = i.Cuenta__c;
            caso.RecordTypeId = garantia.Id;
            
            String c = i.Entregada__c; 
            if(c == 'Entregado' && c != null && c != ''){ 
                showButtons = true;
            }else{ 
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'La vivienda no está entregada.'));
                showButtons = false;
                //alert('La vivienda no está entregada'); 
            }
            
        }catch(Exception o){
            if(!o.getMessage().equals('List has no rows for assignment to SObject')){
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, o.getMessage()));
            }
        }
        
        //Cuenta y vivienda del inventario de donde se haga el caso
    }
    
    public PageReference guardar(){
        PageReference page = ApexPages.currentPage();
        List<Vencimiento__c> v = [SELECT Id, Name, VencimientoDias__c FROM Vencimiento__c  WHERE Clasificacion__c = :caso.Clasificacion__c ORDER BY CreatedDate DESC LIMIT 1];
        
        Entrega__c e = [SELECT Id, Name, FechaEntrega__c FROM Entrega__c WHERE Inventario__c =: caso.ViviendaProceso__c ORDER BY CreatedDate DESC LIMIT 1];
        
        Date fecha = e.FechaEntrega__c;
        if(!v.isEmpty()){
            fecha = fecha.addDays((Integer)v.get(0).VencimientoDias__c);
            caso.DiasVencimiento__c = fecha.daysBetween(System.today());
            if(fecha < (System.today())){
                caso.Garantiavencida__c = true;
                caso.DiasVencimiento__c = -fecha.daysBetween(System.today());
            }
        }
        caso.Nomenclatura__c = caso.Tipo__c.substring(0,1) + ' - ' + caso.Clasificacion__c.substring(0,2);
        
        try{
            caso.Nomenclatura__c += ' - ' + caso.Catalagodefalla__c.substring(0,4);
        }catch(Exception o){
            
        }
        try{
        upsert caso;
        }catch(Exception o){
            
        }
        page = new PageReference('/apex/VisitaCita?caso='+ caso.Id);
        
        return page;
    }
    
}