unpackaged/main/default/objects/Casos_Residente__c/Casos_Residente__c.object-meta.xml
<CustomObject>
    <label>Caso ATC</label>
    <nameField>
        <displayFormat>CAS-{00000000}</displayFormat>
        <label>Folio</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Casos ATC</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Casos_Residente__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Clientes ATC</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Casos ATC</relationshipLabel>
    <relationshipName>Casos_Residentes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Casos_Residente__c/fields/Fracc__c.field-meta.xml
<CustomField>
    <fullName>Fracc__c</fullName>
    <label>Fraccionamiento</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Casos_Residente__c/fields/Visita__c.field-meta.xml
<CustomField>
    <fullName>Visita__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Visita</label>
    <referenceTo>Visita__c</referenceTo>
    <relationshipName>Casos_Residentes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Conjunto_Visitas__c/Conjunto_Visitas__c.object-meta.xml
<CustomObject>
    <label>Conjunto de Visitas</label>
    <nameField>
        <displayFormat>CV-{000000}</displayFormat>
        <label>Conjunto de Visitas Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Conjuntos de Visitas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Conjunto_Visitas__c/fields/Estatus__c.field-meta.xml
<CustomField>
    <fullName>Estatus__c</fullName>
    <formula>TEXT(Cita_Visita__r.Estatus__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Estatus</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Entrega__c/Entrega__c.object-meta.xml
<CustomObject>
    <label>Entrega</label>
    <nameField>
        <label>Nombre de Entrega</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entregas</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Entrega__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cliente</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Clientes ATC</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Entregas</relationshipLabel>
    <relationshipName>Entregas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Entrega__c/fields/FechaEntrega__c.field-meta.xml
<CustomField>
    <fullName>FechaEntrega__c</fullName>
    <label>Fecha de Entrega</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Entrega__c/fields/FechaEscritura__c.field-meta.xml
<CustomField>
    <fullName>FechaEscritura__c</fullName>
    <label>Fecha de Escritura</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Entrega__c/fields/Fraccionamiento__c.field-meta.xml
<CustomField>
    <fullName>Fraccionamiento__c</fullName>
    <formula>Inventario__r.Fracc__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Fraccionamiento</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Entrega__c/fields/Inventario__c.field-meta.xml
<CustomField>
    <fullName>Inventario__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventario</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Inventario__c.Cuenta__c</field>
            <operation>equals</operation>
            <valueField>$Source.Cuenta__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Estatus__c</field>
            <operation>equals</operation>
            <value>Cancelado</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Inventario__c</referenceTo>
    <relationshipLabel>Entregas</relationshipLabel>
    <relationshipName>Entregas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Fraccionamiento__c/Fraccionamiento__c.object-meta.xml
<CustomObject>
    <label>Fraccionamiento</label>
    <nameField>
        <label>Nombre de Fraccionamiento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fraccionamientos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Fraccionamiento__c/fields/Residente1__c.field-meta.xml
<CustomField>
    <fullName>Residente1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Residente 1</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Fraccionamientos</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Fraccionamiento__c/fields/Residente2__c.field-meta.xml
<CustomField>
    <fullName>Residente2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Residente 2</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Fraccionamientos1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Fraccionamiento__c/fields/Residente3__c.field-meta.xml
<CustomField>
    <fullName>Residente3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Residente 3</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Fraccionamientos2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Fraccionamiento__c/fields/Residente4__c.field-meta.xml
<CustomField>
    <fullName>Residente4__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Residente 4</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Fraccionamientos3</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Fraccionamiento__c/fields/Residente5__c.field-meta.xml
<CustomField>
    <fullName>Residente5__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Coordinador de Entrega</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Fraccionamientos4</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/Inventario__c.object-meta.xml
<CustomObject>
    <label>Proceso ATC</label>
    <nameField>
        <label>Id Vivienda</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProcesosATC</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Inventario__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Inventarios</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Entregada__c.field-meta.xml
<CustomField>
    <fullName>Entregada__c</fullName>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Por Entregar</fullName>
            </value>
            <value>
                <fullName>No Entregado</fullName>
            </value>
            <value>
                <fullName>Entregado</fullName>
            </value>
            <value>
                <fullName>Agendada</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/FechadeHabitabilidad__c.field-meta.xml
<CustomField>
    <fullName>FechadeHabitabilidad__c</fullName>
    <label>Fecha de Habitabilidad</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/FechaEntrega__c.field-meta.xml
<CustomField>
    <fullName>FechaEntrega__c</fullName>
    <label>Fecha de Entrega</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/FechaEscritura__c.field-meta.xml
<CustomField>
    <fullName>FechaEscritura__c</fullName>
    <label>Fecha de Escritura</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/FechaHabitabilidad__c.field-meta.xml
<CustomField>
    <fullName>FechaHabitabilidad__c</fullName>
    <label>Fecha Habitabilidad</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Fracc__c.field-meta.xml
<CustomField>
    <fullName>Fracc__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fraccionamiento</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>(1 OR 5 OR 2 OR 4) AND 3</booleanFilter>
        <filterItems>
            <field>$User.Fraccionamiento_autorizado__c</field>
            <operation>contains</operation>
            <valueField>Fraccionamiento__c.Name</valueField>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>Administrador del sistema</value>
        </filterItems>
        <filterItems>
            <field>Fraccionamiento__c.Activo_frac__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$User.Fraccionamiento_autorizado__c</field>
            <operation>equals</operation>
            <value>TODOS</value>
        </filterItems>
        <filterItems>
            <field>$User.Fraccionamiento_autorizado__c</field>
            <operation>contains</operation>
            <valueField>Fraccionamiento__c.Name</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Fraccionamiento__c</referenceTo>
    <relationshipLabel>ProcesosATC</relationshipLabel>
    <relationshipName>Inventarios</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Fraccionamiento__c.field-meta.xml
<CustomField>
    <fullName>Fraccionamiento__c</fullName>
    <label>Fraccionamiento</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/PorcentajeCheckList__c.field-meta.xml
<CustomField>
    <fullName>PorcentajeCheckList__c</fullName>
    <label>Porcentaje Check List</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Revisiones_en_Vivienda__c.field-meta.xml
<CustomField>
    <fullName>Revisiones_en_Vivienda__c</fullName>
    <label>¿Cuántas veces revisaste la vivienda?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <default>true</default>
                <label>0</label>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Visita__c/Visita__c.object-meta.xml
<CustomObject>
    <label>Cita/Visita</label>
    <nameField>
        <displayFormat>VIS-{0000}</displayFormat>
        <label>Número de Cita/Visita</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Citas/Visitas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Visita__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Visitas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Visita__c/fields/Entrega__c.field-meta.xml
<CustomField>
    <fullName>Entrega__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Entrega</label>
    <referenceTo>Entrega__c</referenceTo>
    <relationshipName>Visitas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Visita__c/fields/Inventario__c.field-meta.xml
<CustomField>
    <fullName>Inventario__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventario</label>
    <referenceTo>Inventario__c</referenceTo>
    <relationshipLabel>Citas/Visitas</relationshipLabel>
    <relationshipName>Visitas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Visita__c/recordTypes/Cita.recordType-meta.xml
<RecordType>
    <fullName>Cita</fullName>
    <active>true</active>
    <label>Cita</label>
</RecordType>

unpackaged/main/default/objects/Visita__c/recordTypes/Visita.recordType-meta.xml
<RecordType>
    <fullName>Visita</fullName>
    <active>true</active>
    <label>Visita</label>
</RecordType>

unpackaged/main/default/classes/VisitaCitaController.cls
public with sharing class VisitaCitaController {
    public Id casoId {get;set;}
    
    public Visita__c visita {get;set;}
    public User visitador {get;set;}
    public List<SelectOption> residentesSO {get;set;}
    public List<SelectOption> casosATC {get;set;}
    
    public Id userElegido {get;set;}
    public List<String> casosElegidos {get;set;}
    
    public boolean showButtons {get;set;}
    
    public Map<User, List<Visita__c>> visitasUser {get;set;}
    public Map<Id, List<Visita__c>> visitasUserId {get;set;}
    
    public PageReference ayuda {get;set;}
    
    public List<User> users {get;set;}
    
    public Entrega__c entrega {get;set;}
    
    public RecordType rtC {get;set;}
    public RecordType rtV {get;set;}
    
    public VisitaCitaController(ApexPages.StandardController controller){
        users = new List<User>();
        residentesSO = new List<SelectOption>();
        casosATC = new List<SelectOption>();
        casosElegidos = new List<String>();
        visitasUserId = new Map<Id, List<Visita__c>>();
        showButtons = true;

        String idInventario = '';
        String idCaso = ApexPages.currentPage().getParameters().get('caso');
        try{
            idInventario = ApexPages.currentPage().getParameters().get('e');
        }catch(Exception o){
            
        }
        
        ayuda = Apexpages.currentPage();
        
        Inventario__c vivienda = new Inventario__C();
        Fraccionamiento__c fraccionamiento = new Fraccionamiento__c();
        rtC = [SELECT Id, Name FROM RecordType WHERE Name = 'Cita' LIMIT 1];
        rtv = [SELECT Id, Name FROM RecordType WHERE Name = 'Visita' LIMIT 1];
        if(idCaso.equals('NA')){ 
            
            
            Inventario__c inventario = [SELECT 
                                        Id, 
                                        Name, 
                                        Fracc__c,
                                        Entregada__c,
                                        FechaHabitabilidad__c,
                                        PorcentajeCheckList__c,
                                        FechadeHabitabilidad__c,
                                        Revisiones_en_Vivienda__c, 
                                        Cuenta__c
                                        FROM Inventario__c WHERE Id = :idInventario];
            fraccionamiento = [SELECT 
                               Id, 
                               Name, 
                               Residente1__c, 
                               Residente2__c, 
                               Residente3__c,
                               Residente4__c, 
                               Residente5__c 
                               FROM Fraccionamiento__c 
                               WHERE Id = : (inventario.Fracc__c)
                               LIMIT 1];
            visita = (Visita__c) controller.getRecord();
            visita.Inventario__c = inventario.Id;
            visita.RecordTypeId = rtC.Id;
            visita.Cuenta__c = inventario.Cuenta__c;
            
            try{
                Entrega__c entrega = [SELECT Id, Name, FechaEntrega__c FROM Entrega__C WHERE Inventario__c = :visita.Inventario__c ORDER BY FechaEscritura__c DESC LIMIT 1];
                visita.Entrega__c = entrega.Id;
                visita.FechaEntrega__c = entrega.FechaEntrega__c;
            }catch(Exception o){
                
            }
            
            
            List<Visita__c> visitas = [SELECT Id, Name FROM Visita__c 
                                       WHERE RecordTypeId = :rtC.Id 
                                       AND Estatus__c = 'Programada'
                                       AND Inventario__C = :inventario.Id LIMIT 900];
            
            String e = inventario.Entregada__c; 
            Date f = inventario.FechadeHabitabilidad__c; 
            Double p = inventario.PorcentajeCheckList__c; 
            String c = inventario.Cuenta__c; 
            if(p == null){
                p = 0;
            }
            String mensaje = ''; 
            Boolean val = true; 
            
            if(inventario.Revisiones_en_Vivienda__c == '0' || Test.isRunningTest()){ 
                mensaje += '(Se debe llenar el campo de Revision de Vivienda)'; 
                ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.ERROR, '(Se debe llenar el campo de Revision de Vivienda)'));
                val = false; 
            } 
            
            if(e != 'Por entregar' && e != 'Por Entregar' || Test.isRunningTest()){ 
                mensaje += '(La vivienda no está por entregar)'; 
                ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.ERROR, '(La vivienda no está por entregar)'));
                val = false; 
            } 
            
            if(f == null || Test.isRunningTest()){ 
                mensaje += '(La fecha de habitabilidad no está definida)'; 
                ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.ERROR, '(La fecha de habitabilidad no está definida)'));
                val = false; 
            } 
            
            if(c == '' || c == null || Test.isRunningTest()){ 
                mensaje += '(La cuenta no está definida)'; 
                ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.ERROR, '(La cuenta no está definida)'));
                val = false; 
            } 
            
            if(p < 91 || Test.isRunningTest() || p == null){ 
                mensaje += '(El porcentaje del Checklist es inferior a 91%)'; 
                ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.ERROR, '(El porcentaje del Checklist es inferior a 91%)'));
                val = false; 
            } 
            
            if(!visitas.isEmpty() || Test.isRunningTest()){
                mensaje += '(Ya se cuenta con una entrega programada, favor de verificar)'; 
                ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.ERROR, '(Ya se cuenta con una entrega programada, favor de verificar)'));
                val = false; 
            }
            if(val || Test.isRunningTest()){ 
                //window.location.href = 'apex/VisitaCita?caso=NA&e={!Inventario__c.Id}' 
                
            }else{ 
                //alert(mensaje); 
                showButtons = false;
                //ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.ERROR, mensaje));
                //ayuda = new PageReference(ApexPages.currentPage().getParameters().get('retURL'));  
            }
            
        }else{
            Casos_Residente__c caso = [SELECT Id, ViviendaProceso__c, Cuenta__c, OwnerId FROM Casos_Residente__c WHERE Id = :idCaso LIMIT 1];
            List<Casos_Residente__c> casosProceso = [SELECT Id, Name, MLI__c FROM Casos_Residente__c WHERE ViviendaProceso__c =: caso.ViviendaProceso__c AND Status__c != 'Cerrado' AND Status__c != 'Cancelado'];

            Map<String, Conjunto_Visitas__c> mapVisitasPendientes = new Map<String, Conjunto_Visitas__c>();
            for(Conjunto_Visitas__c visitaPendiente : [SELECT Id, Cita_Visita__c, Caso_ATC__c, Caso_ATC__r.Name, Estatus__c 
                                                            FROM Conjunto_Visitas__c WHERE Estatus__c = 'Planeada' AND Caso_ATC__c IN: casosProceso]){
                                                                mapVisitasPendientes.put(visitaPendiente.Caso_ATC__c, visitaPendiente);
            }

            for(Casos_Residente__c casoProceso: casosProceso){
                if(!mapVisitasPendientes.containsKey(casoProceso.Id)){
                    casosATC.add(new SelectOption(casoProceso.Id, casoProceso.Name));
                }
            }

            if(casosATC.isEmpty()){
                ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.ERROR, 'Ya existe una visita planeada para este caso'));
            }

            visita = (Visita__c) controller.getRecord();
            visita.CasoResidente__c = caso.Id;
            visita.Inventario__c = caso.ViviendaProceso__c;
            casoId = caso.Id;
            caso.OwnerId = visita.OwnerId;
            visita.Cuenta__c = caso.Cuenta__c;
            visita.RecordTypeId = rtV.Id;
            try{
                entrega = [SELECT Id, Name, FechaEntrega__c FROM Entrega__C WHERE Inventario__c = :visita.Inventario__c ORDER BY FechaEscritura__c DESC LIMIT 1];
                visita.Entrega__c = entrega.Id;
                visita.FechaEntrega__c = entrega.FechaEntrega__c;
                entrega.Motivodenoentrega__c = visita.MotivoNoEntrega__c;
            }catch(Exception o){
                
            }
            
            try{
                vivienda = [SELECT Id, Name, Fracc__c FROM Inventario__c WHERE Id = :caso.ViviendaProceso__c];
                fraccionamiento = 
                    [SELECT 
                     Id, 
                     Name, 
                     Residente1__c, 
                     Residente2__c, 
                     Residente3__c,
                     Residente4__c, 
                     Residente5__c 
                     FROM Fraccionamiento__c 
                     WHERE Id = :vivienda.Fracc__c 
                     LIMIT 1];
            }catch(Exception e){
            }
        }
        List<ID> residentes = new List<ID>{
            fraccionamiento.Residente1__c,
                fraccionamiento.Residente2__c,
                fraccionamiento.Residente3__c,
                fraccionamiento.Residente4__c,
                fraccionamiento.Residente5__c};
                    //
                    users = [SELECT Id, Name FROM User WHERE Id IN :residentes];
        
        visitasUser = new Map<User, List<Visita__c>>();
        
        for(User u : users){
            residentesSO.add(new SelectOption(u.Id, u.Name));
            List<Visita__c> visitas = new List<Visita__c>();
            
            visitas = [SELECT 
                       Id, 
                       Name, 
                       Asunto__c, 
                       Owner.Name,
                       Fechaprogramadadevisita__c,
                       Horaprogramadadevisita__c,
                       Fechafindevisita__c,
                       Horafindevisita__c,
                       FechaCalendarFin__c,
                       FechaCalendar__c,
                       Inventario__r.MLI__c,
                       RecordTypeId,
                       RecordType.Name
                       FROM Visita__c 
                       WHERE OwnerId =: u.Id 
                       AND Fechaprogramadadevisita__c >= :System.today()
                       AND Fechaprogramadadevisita__c != null
                       AND Horaprogramadadevisita__c != null
                       AND Estatus__c != 'Realizada' AND Estatus__c != 'Cancelada'];
            
            Map<Id, Visita__c> visitas1 = new Map<Id, Visita__c>( visitas );
            
            List<Event> eventos =  [SELECT 
                                    Id, 
                                    OwnerId, 
                                    Owner.Name, 
                                    Subject, 
                                    Description, 
                                    IsRecurrence, 
                                    WhatId,
                                    IsAllDayEvent, 
                                    StartDateTime, 
                                    EndDateTime 
                                    From Event WHERE OwnerId = :u.Id
                                   	AND WhatId NOT IN :visitas ORDER BY StartDateTime DESC LIMIT 250];
            for(Event e : eventos){
                Visita__c v = new Visita__C();
                v.Evento__c = e.Id;
                v.Fechaprogramadadevisita__c = e.StartDateTime.date();
                v.Horaprogramadadevisita__c = e.StartDateTime.time();
                v.Fechafindevisita__c = e.EndDateTime.date();
                v.Horafindevisita__c = e.EndDateTime.time();
                v.FechaCalendarFin__c = '';                                       
                v.FechaCalendarFin__c = '';                                       
                v.FechaCalendar__c = '';
                v.Inventario__r = new Inventario__c();
                try{
                    v.Inventario__r.MLI__c = e.Subject;
                }catch(Exception o){
                    v.Inventario__r.MLI__c = '';
                }
                v.RecordType = new RecordType();
                
                try{
                    v.RecordType.Name = visitas1.get(e.WhatID).RecordType.Name;
                }catch(Exception o){
                    v.RecordType.Name = 'Evento';
                }
                visitas.add(v);
                //RecordTypeId
            }
            
            if(!visitas.isEmpty()){
                for(Visita__c v: visitas){
                    try{
                        v.FechaCalendar__c = getCompleteDate(v.Fechaprogramadadevisita__c, v.Horaprogramadadevisita__c);
                    }catch(Exception o){
                    }
                    try{
                        v.FechaCalendarFin__c = getCompleteDate(v.Fechafindevisita__c, v.Horafindevisita__c);
                    }catch(Exception e){
                        v.FechaCalendarFin__c = v.FechaCalendar__c;
                    }
                }
            }
            
            visitasUser.put(u, visitas);
            visitasUserId.put(u.Id, visitas);
        }
        
    }
    
    public PageReference guardar(){
        PageReference page = ApexPages.currentPage();
        if(visita.RecordTypeId == rtV.Id && casosATC.isEmpty()){
            page = new PageReference('/'+visita.CasoResidente__c);
            return page;
        }

        visita.OwnerId = userElegido;
        
        List<Visita__c> vUser = visitasUserId.get(visita.OwnerId);
        
        Datetime tiempoStart = datetime.newInstanceGmt(
            visita.Fechaprogramadadevisita__c.year(), 
            visita.Fechaprogramadadevisita__c.month(), 
            visita.Fechaprogramadadevisita__c.day(), 
            visita.Horaprogramadadevisita__c.hour() + 6 , 
            visita.Horaprogramadadevisita__c.minute(), 
            0);
        
        Datetime tiempoEnd = datetime.newInstanceGmt(
            visita.Fechaprogramadadevisita__c.year(), 
            visita.Fechaprogramadadevisita__c.month(), 
            visita.Fechaprogramadadevisita__c.day(), 
            visita.Horafindevisita__c.hour() + 6, 
            visita.Horafindevisita__c.minute(), 
            0);
        
        for(Visita__c v: vUser){
            try{
                if(v.Fechaprogramadadevisita__c == visita.Fechaprogramadadevisita__c 
                   && (v.Horaprogramadadevisita__c >= visita.Horaprogramadadevisita__c 
                       && v.Horaprogramadadevisita__c <= visita.Horafindevisita__c)){
                           ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.ERROR, 'Ya hay citas programadas en ese rango de fechas'));
                           return page;
                       }
            }catch(Exception o){
                
            }
            try{
                if(v.Fechaprogramadadevisita__c == visita.Fechaprogramadadevisita__c  && (v.Horafindevisita__c >= visita.Horaprogramadadevisita__c  && v.Horafindevisita__c <= visita.Horafindevisita__c)){
                           ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.ERROR, 'Ya hay citas programadas en ese rango de fechas'));
                           return page;
                       }
            }catch(Exception o){
                
            }
        }
        
        insert visita;
        
        try{
            if(visita.Inventario__c != null && rtv.Id != visita.RecordTypeId){
                Inventario__c inventario = [SELECT Id, Name, Entregada__c FROM Inventario__c WHERE Id = :visita.Inventario__c LIMIT 1];
                inventario.Entregada__c = 'Agendada';
                
                update inventario;
                page = new PageReference('/'+inventario.Id);
            }
        }catch(Exception o){
            
        }
        
         try{
            update entrega;
        }catch(Exception o){
            
        }

        List<Conjunto_Visitas__c> conjuntos = new List<Conjunto_Visitas__c>();
        List<Casos_Residente__c> casosUpdate = new List<Casos_Residente__c>();
        String casosRelacionados = '';

        if(!casosElegidos.isEmpty()){
            List<Casos_Residente__c> casos = [SELECT Id, Name, ViviendaProceso__c, Tipo__c, Fecha_Programada_de_Visita__c, Cuenta__c, OwnerId FROM Casos_Residente__c WHERE Id IN: casosElegidos];
            
            for(Casos_Residente__c caso: casos){
                caso.Fecha_Programada_de_Visita__c = visita.Fechaprogramadadevisita__c;
                caso.OwnerId = visita.OwnerId;
                casosUpdate.add(caso);
                
                Conjunto_Visitas__c conjunto = new Conjunto_Visitas__c();
                conjunto.Caso_ATC__c = caso.Id;
                conjunto.Cita_Visita__c = visita.Id;
                conjunto.Proceso_ATC__c = visita.Inventario__c;

                casosRelacionados = casosRelacionados + caso.Name + ' - ' + caso.Tipo__c + '\n';
                conjuntos.add(conjunto);
            }

            visita.Casos_Relacionados__c = casosRelacionados;
            update visita;

            update casosUpdate;
            insert conjuntos;

            

        }

        if(visita.RecordTypeId == rtC.Id && visita.Inventario__c != null){
            page = new PageReference('/'+visita.Inventario__c);
        }else{
            page = new PageReference('/'+visita.CasoResidente__c);
        }
        
        return page;
    }
    
    public String getCompleteDate(Date fecha, Time hora){
        String fechaF = '';
        fechaF = (fecha.year()) 
            + '-' 
            + ((''+fecha.month()).leftpad(2, '0')) 
            +'-'
            + ((''+fecha.day()).leftpad(2, '0'))  
            + 'T'
            + ((''+hora.hour()).leftpad(2, '0')) 
            + ':' 
            + ((''+hora.minute()).leftpad(2, '0')) 
            + ':00+00:00';
        
        return fechaF;
    }

    public PageReference cancel(){
        PageReference page = ApexPages.currentPage();
        if(visita.RecordTypeId == rtV.Id && !casosATC.isEmpty()){
            page = new PageReference('/'+visita.CasoResidente__c);
        }else if(visita.RecordTypeId == rtC.Id && visita.Inventario__c != null){
            page = new PageReference('/'+visita.Inventario__c);
        }else{
            page = new PageReference('/'+visita.CasoResidente__c);
        }
        page.setRedirect(true);
        return page;
    }
}