unpackaged/main/default/objects/Casos_Residente__c/Casos_Residente__c.object-meta.xml
<CustomObject>
    <label>Caso ATC</label>
    <nameField>
        <displayFormat>CAS-{00000000}</displayFormat>
        <label>Folio</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Casos ATC</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Casos_Residente__c/fields/CasoResidente__c.field-meta.xml
<CustomField>
    <fullName>CasoResidente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Caso Residentes</label>
    <referenceTo>Casos_Residente__c</referenceTo>
    <relationshipName>CasosResidentes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Casos_Residente__c/fields/Clasificacion__c.field-meta.xml
<CustomField>
    <fullName>Clasificacion__c</fullName>
    <label>Clasificación</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Tipo__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A1. Corto circuito</fullName>
            </value>
            <value>
                <fullName>A2. Obstrucción</fullName>
            </value>
            <value>
                <fullName>A3. Falta cableado</fullName>
            </value>
            <value>
                <fullName>A4. Falta Accesorio</fullName>
            </value>
            <value>
                <fullName>A5. Falta guía CFE</fullName>
            </value>
            <value>
                <fullName>A6. Falta Guía TV-Cable</fullName>
            </value>
            <value>
                <fullName>A7. Accesorio Dañado y/o Sin Energia</fullName>
            </value>
            <value>
                <fullName>A8. Accesorio mal instalado</fullName>
            </value>
            <value>
                <fullName>A9. Variacion de Voltaje</fullName>
            </value>
            <value>
                <fullName>A10. Filtración por Ductos</fullName>
            </value>
            <value>
                <fullName>A11. Ducto tapado</fullName>
            </value>
            <value>
                <fullName>A12. Otro</fullName>
            </value>
            <value>
                <fullName>A13.Falta de guía de minisplit</fullName>
            </value>
            <value>
                <fullName>B1. Instalación Tapada</fullName>
            </value>
            <value>
                <fullName>B10. Instalación sanitaria</fullName>
            </value>
            <value>
                <fullName>B2. Falta de conexión</fullName>
            </value>
            <value>
                <fullName>B3. Fugas</fullName>
            </value>
            <value>
                <fullName>B4. Mala Instalacion</fullName>
            </value>
            <value>
                <fullName>B5. Dañado</fullName>
            </value>
            <value>
                <fullName>B6. Faltante</fullName>
            </value>
            <value>
                <fullName>B7. Humedad en Muro / Losa</fullName>
            </value>
            <value>
                <fullName>B8. Humedad en Pluvial</fullName>
            </value>
            <value>
                <fullName>B9. Otros</fullName>
            </value>
            <value>
                <fullName>C1. Tapado</fullName>
            </value>
            <value>
                <fullName>C2. Falta de Conexión</fullName>
            </value>
            <value>
                <fullName>C3. Fuga</fullName>
            </value>
            <value>
                <fullName>C4. Mala Instalacion</fullName>
            </value>
            <value>
                <fullName>C5. Dañado</fullName>
            </value>
            <value>
                <fullName>C6. Faltante</fullName>
            </value>
            <value>
                <fullName>C7. Falta de Presion</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Casos_Residente__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A. Instalación eléctrica</fullName>
            </value>
            <value>
                <fullName>B. Instalacion sanitaria</fullName>
            </value>
            <value>
                <fullName>C. Instalacion hidráulica</fullName>
            </value>
            <value>
                <fullName>D. Instalación gas</fullName>
            </value>
            <value>
                <fullName>E. Albañilería</fullName>
            </value>
            <value>
                <fullName>F. Acabados Interior</fullName>
            </value>
            <value>
                <fullName>G. Acabado Exterior</fullName>
            </value>
            <value>
                <fullName>H. Aluminio</fullName>
            </value>
            <value>
                <fullName>I. Puertas</fullName>
            </value>
            <value>
                <fullName>J. Impermeabilización</fullName>
            </value>
            <value>
                <fullName>K. Herrería</fullName>
            </value>
            <value>
                <fullName>L. Urbanización</fullName>
            </value>
            <value>
                <fullName>M. Infraestructura</fullName>
            </value>
            <value>
                <fullName>N. Accesorios</fullName>
            </value>
            <value>
                <fullName>O. Servicios</fullName>
            </value>
            <value>
                <fullName>P. Organización Vecinal</fullName>
            </value>
            <value>
                <fullName>Q. Ventas</fullName>
            </value>
            <value>
                <fullName>R. Seguimiento de Ventas</fullName>
            </value>
            <value>
                <fullName>S. Fechas</fullName>
            </value>
            <value>
                <fullName>T. Quejas</fullName>
            </value>
            <value>
                <fullName>U. Cobranza Post.Venta</fullName>
            </value>
            <value>
                <fullName>V. Solicitudes</fullName>
            </value>
            <value>
                <fullName>W. Otros</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Casos_Residente__c/fields/Visita__c.field-meta.xml
<CustomField>
    <fullName>Visita__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Visita</label>
    <referenceTo>Visita__c</referenceTo>
    <relationshipName>Casos_Residentes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Casos_Residente__c/fields/ViviendaProceso__c.field-meta.xml
<CustomField>
    <fullName>ViviendaProceso__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Vivienda</label>
    <referenceTo>Inventario__c</referenceTo>
    <relationshipLabel>Casos ATC</relationshipLabel>
    <relationshipName>Casos_ATC</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Entrega__c/Entrega__c.object-meta.xml
<CustomObject>
    <label>Entrega</label>
    <nameField>
        <label>Nombre de Entrega</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entregas</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Entrega__c/fields/FechaEntrega__c.field-meta.xml
<CustomField>
    <fullName>FechaEntrega__c</fullName>
    <label>Fecha de Entrega</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Entrega__c/fields/Inventario__c.field-meta.xml
<CustomField>
    <fullName>Inventario__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventario</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Inventario__c.Cuenta__c</field>
            <operation>equals</operation>
            <valueField>$Source.Cuenta__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Estatus__c</field>
            <operation>equals</operation>
            <value>Cancelado</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Inventario__c</referenceTo>
    <relationshipLabel>Entregas</relationshipLabel>
    <relationshipName>Entregas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/Inventario__c.object-meta.xml
<CustomObject>
    <label>Proceso ATC</label>
    <nameField>
        <label>Id Vivienda</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProcesosATC</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Inventario__c/fields/FechaEntrega__c.field-meta.xml
<CustomField>
    <fullName>FechaEntrega__c</fullName>
    <label>Fecha de Entrega</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Visita__c/Visita__c.object-meta.xml
<CustomObject>
    <label>Cita/Visita</label>
    <nameField>
        <displayFormat>VIS-{0000}</displayFormat>
        <label>Número de Cita/Visita</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Citas/Visitas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Visita__c/fields/CasoResidente__c.field-meta.xml
<CustomField>
    <fullName>CasoResidente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Caso</label>
    <referenceTo>Casos_Residente__c</referenceTo>
    <relationshipLabel>Citas/Visitas</relationshipLabel>
    <relationshipName>Visitas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Visita__c/fields/Entrega__c.field-meta.xml
<CustomField>
    <fullName>Entrega__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Entrega</label>
    <referenceTo>Entrega__c</referenceTo>
    <relationshipName>Visitas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Visita__c/fields/Fechaprogramadadevisita__c.field-meta.xml
<CustomField>
    <fullName>Fechaprogramadadevisita__c</fullName>
    <label>Fecha programada</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Visita__c/fields/Horafindevisita__c.field-meta.xml
<CustomField>
    <fullName>Horafindevisita__c</fullName>
    <label>Hora fin de visita</label>
    <required>true</required>
    <type>Time</type>
</CustomField>

unpackaged/main/default/objects/Visita__c/fields/Horaprogramadadevisita__c.field-meta.xml
<CustomField>
    <fullName>Horaprogramadadevisita__c</fullName>
    <label>Hora programada</label>
    <required>true</required>
    <type>Time</type>
</CustomField>

unpackaged/main/default/objects/Visita__c/fields/Inventario__c.field-meta.xml
<CustomField>
    <fullName>Inventario__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventario</label>
    <referenceTo>Inventario__c</referenceTo>
    <relationshipLabel>Citas/Visitas</relationshipLabel>
    <relationshipName>Visitas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/CrearVisita_Test.cls
@isTest
public class CrearVisita_Test {
    static TestMethod void testMethod1() {
        Inventario__c inventario = new Inventario__c();
        inventario.Name = 'Test Inventario';
        insert inventario;
        Casos_Residente__c caso = new Casos_Residente__c();
        caso.Clasificacion__c = 'A1. Corto circuito';
        caso.Tipo__c = 'A. Instalación eléctrica';
        Entrega__c entrega = new Entrega__c();
        entrega.Inventario__c = inventario.Id;
        entrega.FechaEntrega__c = Date.today();
        insert entrega;
        caso.ViviendaProceso__c = entrega.Inventario__c;
        insert caso;
        Visita__c v1 = new Visita__c();
        v1.Fechaprogramadadevisita__c = System.today()+1;
        v1.Horaprogramadadevisita__c = time.newInstance(15, 0, 0, 0);
        v1.Horafindevisita__c = time.newInstance(17, 0, 0, 0);        
        v1.CasoResidente__c = caso.Id;
        insert v1;
        Event ev = new Event(EndDateTime =system.today().addDays(+5) ,WhatId=caso.Id, StartDateTime =system.today().addDays(+3),Subject = 'test');
        insert ev;
        delete ev;
    }
    static TestMethod void testMethod2() {
        Event ev = new Event(EndDateTime =system.today().addDays(+5) , StartDateTime =system.today().addDays(+3),Subject = 'test');
        insert ev;
        delete ev;
    }
}