unpackaged/main/default/objects/Casos_Residente__c/Casos_Residente__c.object-meta.xml
<CustomObject>
    <label>Caso ATC</label>
    <nameField>
        <displayFormat>CAS-{00000000}</displayFormat>
        <label>Folio</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Casos ATC</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Casos_Residente__c/fields/Visita__c.field-meta.xml
<CustomField>
    <fullName>Visita__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Visita</label>
    <referenceTo>Visita__c</referenceTo>
    <relationshipName>Casos_Residentes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Entrega__c/Entrega__c.object-meta.xml
<CustomObject>
    <label>Entrega</label>
    <nameField>
        <label>Nombre de Entrega</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entregas</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Entrega__c/fields/FechaEntrega__c.field-meta.xml
<CustomField>
    <fullName>FechaEntrega__c</fullName>
    <label>Fecha de Entrega</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Entrega__c/fields/Inventario__c.field-meta.xml
<CustomField>
    <fullName>Inventario__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventario</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Inventario__c.Cuenta__c</field>
            <operation>equals</operation>
            <valueField>$Source.Cuenta__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Estatus__c</field>
            <operation>equals</operation>
            <value>Cancelado</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Inventario__c</referenceTo>
    <relationshipLabel>Entregas</relationshipLabel>
    <relationshipName>Entregas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/Inventario__c.object-meta.xml
<CustomObject>
    <label>Proceso ATC</label>
    <nameField>
        <label>Id Vivienda</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProcesosATC</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Inventario__c/fields/FechaEntrega__c.field-meta.xml
<CustomField>
    <fullName>FechaEntrega__c</fullName>
    <label>Fecha de Entrega</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/PorcentajeCheckList__c.field-meta.xml
<CustomField>
    <fullName>PorcentajeCheckList__c</fullName>
    <label>Porcentaje Check List</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Visita__c/Visita__c.object-meta.xml
<CustomObject>
    <label>Cita/Visita</label>
    <nameField>
        <displayFormat>VIS-{0000}</displayFormat>
        <label>Número de Cita/Visita</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Citas/Visitas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Visita__c/fields/Entrega__c.field-meta.xml
<CustomField>
    <fullName>Entrega__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Entrega</label>
    <referenceTo>Entrega__c</referenceTo>
    <relationshipName>Visitas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Visita__c/fields/Inventario__c.field-meta.xml
<CustomField>
    <fullName>Inventario__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventario</label>
    <referenceTo>Inventario__c</referenceTo>
    <relationshipLabel>Citas/Visitas</relationshipLabel>
    <relationshipName>Visitas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/VisitaCitaController_Test.cls
@isTest
public without sharing class VisitaCitaController_Test {
    @isTest
    private static void VisitaCitaController_Test(){
        Test.startTest();

        List<Inventario__c> inventarios = TestDataFactory.createInventarios(1);
        insert inventarios;

        Entrega__c entrega = new Entrega__c();
        entrega.Inventario__c = inventarios[0].Id;
        entrega.FechaEntrega__c = Date.today();
        insert entrega; 
        
        List<Visita__c> visitas = TestDataFactory.createVisitas(1);
        insert visitas;

        List<Casos_Residente__c> casos = TestDataFactory.createCasosATC(1);
        insert casos;

        List<Event> events = TestDataFactory.createEvents(1);
        events[0].WhatId = null;
        insert events;

        PageReference page = Page.VisitaCita;
        page.getParameters().put('caso', 'NA');
        Test.setCurrentPageReference(page);

        page.getParameters().put('e', inventarios[0].Id);
        Test.setCurrentPageReference(page);

        ApexPages.StandardController sc = new ApexPages.StandardController(visitas[0]);
        VisitaCitaController vs = new VisitaCitaController(sc);
        vs.userElegido = UserInfo.getUserId();
        vs.guardar();
        vs.cancel();

        page.getParameters().put('caso', casos[0].Id);
        Test.setCurrentPageReference(page);

        page.getParameters().put('e', inventarios[0].Id);
        Test.setCurrentPageReference(page);

        ApexPages.StandardController sc2 = new ApexPages.StandardController(visitas[0]);
        VisitaCitaController vs2 = new VisitaCitaController(sc2);
        vs.userElegido = UserInfo.getUserId();
        vs.guardar();
        vs.cancel();
        vs.entrega = new Entrega__c();
        vs.visitador = new User();
        Test.stopTest();
    }
    @isTest
    private static void VisitaCitaController_Test1(){
        Test.startTest();

        List<Inventario__c> inventarios = TestDataFactory.createInventarios(1);
        inventarios[0].PorcentajeCheckList__c = null;
        insert inventarios;
        
        List<Visita__c> visitas = TestDataFactory.createVisitas(1);
        insert visitas;

        List<Casos_Residente__c> casos = TestDataFactory.createCasosATC(1);
        insert casos;

        List<Event> events = TestDataFactory.createEvents(1);
        events[0].WhatId = null;
        insert events;

        PageReference page = Page.VisitaCita;
        page.getParameters().put('caso', 'NA');
        Test.setCurrentPageReference(page);

        page.getParameters().put('e', inventarios[0].Id);
        Test.setCurrentPageReference(page);

        ApexPages.StandardController sc = new ApexPages.StandardController(visitas[0]);
        VisitaCitaController vs = new VisitaCitaController(sc);
        vs.userElegido = UserInfo.getUserId();
        vs.guardar();
        vs.cancel();

        page.getParameters().put('caso', casos[0].Id);
        Test.setCurrentPageReference(page);

        page.getParameters().put('e', inventarios[0].Id);
        Test.setCurrentPageReference(page);

        ApexPages.StandardController sc2 = new ApexPages.StandardController(visitas[0]);
        VisitaCitaController vs2 = new VisitaCitaController(sc2);
        vs.userElegido = UserInfo.getUserId();
        vs.guardar();
        vs.cancel();
        vs.entrega = new Entrega__c();
        vs.visitador = new User();
        Test.stopTest();
    }
}