unpackaged/main/default/objects/Sistema__c/Sistema__c.object-meta.xml
<CustomObject>
    <label>Sistema</label>
    <nameField>
        <label>Nombre de Sistema</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sistemas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Sistema__c/fields/Limpieza_Job_Id__c.field-meta.xml
<CustomField>
    <fullName>Limpieza_Job_Id__c</fullName>
    <description>El Id que genera Salesforce al agendar un JOB. Cuando ya está generado este Id puede utilizarse para detener el JOB.</description>
    <inlineHelpText>El Id que genera Salesforce al agendar un JOB. Cuando ya está generado este Id puede utilizarse para detener el JOB.</inlineHelpText>
    <label>Limpieza Job Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Sistema__c/fields/Limpieza_Recurrencia__c.field-meta.xml
<CustomField>
    <fullName>Limpieza_Recurrencia__c</fullName>
    <description>Es la cadena de texto que utiliza el scheduler para saber la recurrencia del JOB.</description>
    <inlineHelpText>Es la cadena de texto que utiliza el scheduler para saber la recurrencia del JOB.</inlineHelpText>
    <label>Limpieza Recurrencia</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Sistema__c/fields/Max_antiguedad_sin_resolucion__c.field-meta.xml
<CustomField>
    <fullName>Max_antiguedad_sin_resolucion__c</fullName>
    <description>Es un número entero. Es la máxima antigüedad de días para aprobaciones en estatus de &quot;En Proceso de Aprobación&quot;. Las que se encuentren fuera de este rango entran en la lista de remoción. Es necesario este  valor para activar la limpieza programada.</description>
    <inlineHelpText>Es un número entero. Es la máxima antigüedad de días para aprobaciones en estatus de &quot;En Proceso de Aprobación&quot;. Las que se encuentren fuera de este rango entran en la lista de remoción. Es necesario este valor para activar la limpieza programada.</inlineHelpText>
    <label>Máx.antigüedad sin resolución</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/LimpiezaAprobSchClass.cls
global class LimpiezaAprobSchClass implements Schedulable
{  
    global static String LimpiezaAprobSchMe(String mode )
    {
        LimpiezaAprobSchClass LimpAprob_sch = new LimpiezaAprobSchClass();
        
        String sch = mode; // base this on mode or whatever your params are
        String recurrencia=mode.Substring(0, 6);
        String jobID;
        if (!Test.isRunningTest()) { jobID = system.schedule('Limp.Aprob.Aged'+mode, sch, LimpAprob_sch);
        } else {
            jobID = system.schedule('Limp.Aprob.Aged.Test'+mode, sch, LimpAprob_sch);
        }
        
        return jobID;
    }

  global void execute(SchedulableContext sc)
  {
    String fecha;
    Datetime dt = Datetime.NOW();
    fecha = dt.format('yyyyMMdd');
    CronTrigger ct = [SELECT TimesTriggered, NextFireTime FROM CronTrigger WHERE Id = :sc.getTriggerId()];
    System.Debug('***ct*** '+ct);
    String IdJob = ct.Id;
    IdJob = IdJob.Substring(0,15);
    Javer_Util_Future juf_class = new Javer_Util_Future();
    if (!Test.isRunningTest()) { Sistema__c Sst = [SELECT Id, Name,  Limpieza_Job_Id__c, Limpieza_Recurrencia__c, Max_antiguedad_sin_resolucion__c  FROM Sistema__c WHERE Limpieza_Job_Id__c =:IdJob LIMIT 1]; System.Debug('***Sst*** '+Sst); if (Sst.Max_antiguedad_sin_resolucion__c!=null){ Javer_Util_Future.limpia_aprob_siebel(Integer.ValueOf( Sst.Max_antiguedad_sin_resolucion__c) );  }
    } else {
        Javer_Util_Future.limpia_aprob_siebel(1 );
    } 
    
  }
}