unpackaged/main/default/objects/Visita__c/Visita__c.object-meta.xml
<CustomObject>
    <label>Cita/Visita</label>
    <nameField>
        <displayFormat>VIS-{0000}</displayFormat>
        <label>Número de Cita/Visita</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Citas/Visitas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Visita__c/fields/Estatus__c.field-meta.xml
<CustomField>
    <fullName>Estatus__c</fullName>
    <label>Estatus</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planeada</fullName>
            </value>
            <value>
                <fullName>Programada</fullName>
            </value>
            <value>
                <fullName>Realizada</fullName>
            </value>
            <value>
                <fullName>Cancelada</fullName>
            </value>
            <value>
                <fullName>Reprogramada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/VisitaTriggerHandler_Test.cls
@isTest
public without sharing class VisitaTriggerHandler_Test {

    @testSetup
    public static void setup(){
    }

    @isTest
    private static void VisitaTriggerHandler_Test(){
        Test.startTest();

        List<Visita__c> visitas = TestDataFactory.createVisitas(1);
        insert visitas;

        visitas[0].Estatus__c = 'Cancelada';
        update visitas;

        Test.stopTest();
    }
}