unpackaged/main/default/objects/SolicitudesTramitesYTransferencias__c/SolicitudesTramitesYTransferencias__c.object-meta.xml
<CustomObject>
    <label>Solicitudes de Trámites y Transferencias</label>
    <nameField>
        <label>Numero de Solicitud</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Solicitudes de Trámites y Transferencias</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SolicitudesTramitesYTransferencias__c/fields/Aprobacion_Externa__c.field-meta.xml
<CustomField>
    <fullName>Aprobacion_Externa__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Aprobación Externa</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/SolicitudesTramitesYTransferencias__c/fields/Numero__c.field-meta.xml
<CustomField>
    <fullName>Numero__c</fullName>
    <externalId>true</externalId>
    <label>Número</label>
    <length>38</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/SolicitudesTramitesYTransferencias__c/fields/StatusInternoAprobacion__c.field-meta.xml
<CustomField>
    <fullName>StatusInternoAprobacion__c</fullName>
    <label>Status Interno Aprobacion</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/SolicitudesTramitesYTransferencias__c/recordTypes/Transferencia.recordType-meta.xml
<RecordType>
    <fullName>Transferencia</fullName>
    <active>true</active>
    <label>Transferencias</label>
</RecordType>

unpackaged/main/default/classes/trg_Aprobacion_SolicitudTyT_Test.cls
@isTest
public class trg_Aprobacion_SolicitudTyT_Test {
    static TestMethod void testMethod1() {
        SolicitudesTramitesYTransferencias__c solicitud = new SolicitudesTramitesYTransferencias__c();
        solicitud.Name = 'TEST' ;
        solicitud.Numero__c = 'test';
        solicitud.StatusInternoAprobacion__c = 'xxxxxx';
        solicitud.RecordTypeId =Schema.sObjectType.SolicitudesTramitesYTransferencias__c.getRecordTypeInfosBydevelopername().get('Transferencia').getRecordTypeId();
        insert solicitud;
        Test.startTest();
        solicitud.StatusInternoAprobacion__c = 'Aprobado';
        solicitud.Aprobacion_Externa__c = false;
        update solicitud;
        Test.stopTest();
    }
    static TestMethod void testMethod2() {
        SolicitudesTramitesYTransferencias__c solicitud = new SolicitudesTramitesYTransferencias__c();
        solicitud.Name = 'TEST' ;
        solicitud.Numero__c = 'test';
        solicitud.StatusInternoAprobacion__c = 'xxxxxx';
        solicitud.RecordTypeId =Schema.sObjectType.SolicitudesTramitesYTransferencias__c.getRecordTypeInfosBydevelopername().get('Transferencia').getRecordTypeId();
        insert solicitud;
        Test.startTest();
        solicitud.StatusInternoAprobacion__c = 'Aprobado';
        solicitud.Aprobacion_Externa__c = true;
        update solicitud;
        Test.stopTest();
    }
}