unpackaged/main/default/objects/Informacion_representante_legal__c/Informacion_representante_legal__c.object-meta.xml
<CustomObject>
    <label>Información Representante Legal</label>
    <nameField>
        <label>Nombre de Rep legal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Información Representantes Legales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Informacion_representante_legal__c/fields/Apellido_Materno__c.field-meta.xml
<CustomField>
    <fullName>Apellido_Materno__c</fullName>
    <label>Apellido Materno Rep</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Informacion_representante_legal__c/fields/Apellido_Paterno__c.field-meta.xml
<CustomField>
    <fullName>Apellido_Paterno__c</fullName>
    <label>Apellido Paterno Rep</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Informacion_representante_legal__c/fields/CURP__c.field-meta.xml
<CustomField>
    <fullName>CURP__c</fullName>
    <label>CURP Rep</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Informacion_representante_legal__c/fields/Fecha_de_Nacimiento__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_Nacimiento__c</fullName>
    <label>Fecha de Nacimiento Rep</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Informacion_representante_legal__c/fields/Lugar_de_Nacimiento__c.field-meta.xml
<CustomField>
    <fullName>Lugar_de_Nacimiento__c</fullName>
    <label>Lugar de Nacimiento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lugar_Nacimiento</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Informacion_representante_legal__c/fields/RFC__c.field-meta.xml
<CustomField>
    <fullName>RFC__c</fullName>
    <label>RFC Rep</label>
    <length>13</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/globalValueSets/Lugar_Nacimiento.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AGUASCALIENTES</fullName>
    </customValue>
    <customValue>
        <fullName>BAJA CALIFORNIA</fullName>
    </customValue>
    <customValue>
        <fullName>BAJA CALIFORNIA SUR</fullName>
    </customValue>
    <customValue>
        <fullName>CAMPECHE</fullName>
    </customValue>
    <customValue>
        <fullName>CHIAPAS</fullName>
    </customValue>
    <customValue>
        <fullName>CHIHUAHUA</fullName>
    </customValue>
    <customValue>
        <fullName>CIUDAD DE MEXICO</fullName>
    </customValue>
    <customValue>
        <fullName>COAHUILA</fullName>
    </customValue>
    <customValue>
        <fullName>COLIMA</fullName>
    </customValue>
    <customValue>
        <fullName>DURANGO</fullName>
    </customValue>
    <customValue>
        <fullName>ESTADO DE MEXICO</fullName>
    </customValue>
    <customValue>
        <fullName>EXTRANJERO</fullName>
    </customValue>
    <customValue>
        <fullName>GUANAJUATO</fullName>
    </customValue>
    <customValue>
        <fullName>GUERRERO</fullName>
    </customValue>
    <customValue>
        <fullName>HIDALGO</fullName>
    </customValue>
    <customValue>
        <fullName>JALISCO</fullName>
    </customValue>
    <customValue>
        <fullName>MICHOACAN</fullName>
    </customValue>
    <customValue>
        <fullName>MORELOS</fullName>
    </customValue>
    <customValue>
        <fullName>NAYARIT</fullName>
    </customValue>
    <customValue>
        <fullName>NUEVO LEON</fullName>
    </customValue>
    <customValue>
        <fullName>OAXACA</fullName>
    </customValue>
    <customValue>
        <fullName>PUEBLA</fullName>
    </customValue>
    <customValue>
        <fullName>QUERETARO</fullName>
    </customValue>
    <customValue>
        <fullName>QUINTANA ROO</fullName>
    </customValue>
    <customValue>
        <fullName>SAN LUIS POTOSI</fullName>
    </customValue>
    <customValue>
        <fullName>SINALOA</fullName>
    </customValue>
    <customValue>
        <fullName>SONORA</fullName>
    </customValue>
    <customValue>
        <fullName>TABASCO</fullName>
    </customValue>
    <customValue>
        <fullName>TAMAULIPAS</fullName>
    </customValue>
    <customValue>
        <fullName>TLAXCALA</fullName>
    </customValue>
    <masterLabel>Lugar de Nacimiento</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/InfRepLegalTriggerHandler.cls
public class InfRepLegalTriggerHandler {
    public static void updateRFCyCURP(List<Informacion_representante_legal__c> newList) {
        CurpGenerator curpGenerator;
        Person person;
        for (Informacion_representante_legal__c repLegal : newList) {
            if(validateData(repLegal)){
                person = new Person()
                    .setName(repLegal.Name)
                    .setLastName(repLegal.Apellido_Paterno__c)
                    .setMotherMaidenName(repLegal.Apellido_Materno__c)
                    .setGender(repLegal.Sexo__c)
                    .setBirthDate(repLegal.Fecha_de_Nacimiento__c)
                    .setBirthPlace(repLegal.Lugar_de_nacimiento__c);
    
                curpGenerator = new CurpGenerator(person);
    
                if (repLegal.RFC__c==null) {
                    repLegal.RFC__c = curpGenerator.generateBaseRFC();
                    repLegal.RFC__c += curpGenerator.generateHomoclave();
                }
                if (repLegal.CURP__c==null) {
                    repLegal.CURP__c = curpGenerator.generateCurp();
                }
            }
        }
    }

    private static Boolean validateData(Informacion_representante_legal__c rl){
        return rl.Name != null && 
            rl.Apellido_Paterno__c != null && 
            rl.Apellido_Materno__c != null &&
            rl.Sexo__c != null && rl.Fecha_de_Nacimiento__c != null &&
            rl.Lugar_de_nacimiento__c != null;
    }
}