unpackaged/main/default/objects/Encuesta__c/Encuesta__c.object-meta.xml
<CustomObject>
    <label>Encuesta</label>
    <nameField>
        <displayFormat>E{0000}</displayFormat>
        <label>Nombre de Encuesta</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Encuestas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Inventario__c/Inventario__c.object-meta.xml
<CustomObject>
    <label>Proceso ATC</label>
    <nameField>
        <label>Id Vivienda</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProcesosATC</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Inventario__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Inventarios</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/LogATC__c/LogATC__c.object-meta.xml
<CustomObject>
    <label>LogATC</label>
    <nameField>
        <label>Nombre de LogATC</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LogATC</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/LogATC__c/fields/FechaHora__c.field-meta.xml
<CustomField>
    <fullName>FechaHora__c</fullName>
    <label>Fecha y Hora</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/LogATC__c/fields/Mensaje__c.field-meta.xml
<CustomField>
    <fullName>Mensaje__c</fullName>
    <label>Mensaje</label>
    <length>130000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/LogATC__c/fields/Metodo__c.field-meta.xml
<CustomField>
    <fullName>Metodo__c</fullName>
    <label>Método</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/SurveyInvitation/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Survey Invitations</relationshipLabel>
    <relationshipName>Survey_Invitations</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SurveyInvitation/fields/No_Migrada__c.field-meta.xml
<CustomField>
    <fullName>No_Migrada__c</fullName>
    <defaultValue>false</defaultValue>
    <label>No Migrada</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/SurveyInvitation/fields/Proceso_ATC__c.field-meta.xml
<CustomField>
    <fullName>Proceso_ATC__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proceso ATC</label>
    <referenceTo>Inventario__c</referenceTo>
    <relationshipLabel>Invitaciones de encuestas</relationshipLabel>
    <relationshipName>Invitaciones_de_encuestas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SurveyQuestionResponse__c/SurveyQuestionResponse__c.object-meta.xml
<CustomObject>
    <label>Survey Question Response (ATC)</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Question Responses (ATC)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SurveyQuestionResponse__c/fields/Number_Value__c.field-meta.xml
<CustomField>
    <fullName>Number_Value__c</fullName>
    <label>Number Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/SurveyQuestionResponse__c/fields/ResponseValue__c.field-meta.xml
<CustomField>
    <fullName>ResponseValue__c</fullName>
    <label>Response Value</label>
    <length>3200</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/SurveyQuestionResponse__c/fields/Survey_Question__c.field-meta.xml
<CustomField>
    <fullName>Survey_Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Survey Question</label>
    <referenceTo>SurveyQuestion</referenceTo>
    <relationshipLabel>Survey Question Responses</relationshipLabel>
    <relationshipName>Survey_Question_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SurveyQuestionResponse__c/fields/Survey_Question_Choice__c.field-meta.xml
<CustomField>
    <fullName>Survey_Question_Choice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Survey Question Choice</label>
    <referenceTo>SurveyQuestionChoice</referenceTo>
    <relationshipLabel>Survey Question Responses</relationshipLabel>
    <relationshipName>Survey_Question_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SurveyQuestionResponse__c/fields/Survey_Response__c.field-meta.xml
<CustomField>
    <fullName>Survey_Response__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Survey Response</label>
    <referenceTo>SurveyResponse</referenceTo>
    <relationshipLabel>Survey Question Responses</relationshipLabel>
    <relationshipName>Survey_Question_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SurveyQuestionResponse__c/fields/Survey_Response_ATC__c.field-meta.xml
<CustomField>
    <fullName>Survey_Response_ATC__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Survey Response (ATC)</label>
    <referenceTo>SurveyResponse__c</referenceTo>
    <relationshipLabel>Survey Question Responses</relationshipLabel>
    <relationshipName>Survey_Question_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SurveyResponse__c/SurveyResponse__c.object-meta.xml
<CustomObject>
    <label>Survey Response (ATC)</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Responses (ATC)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SurveyResponse__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>SurveyResponse_Mocks</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SurveyResponse__c/fields/Comentario_Adicional__c.field-meta.xml
<CustomField>
    <fullName>Comentario_Adicional__c</fullName>
    <label>Comentarios (Adicionales)</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/SurveyResponse__c/fields/Encuesta__c.field-meta.xml
<CustomField>
    <fullName>Encuesta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Encuesta</label>
    <referenceTo>Survey</referenceTo>
    <relationshipLabel>Survey Responses (ATC)</relationshipLabel>
    <relationshipName>Survey_Responses_ATC</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SurveyResponse__c/fields/IRC12__c.field-meta.xml
<CustomField>
    <fullName>IRC12__c</fullName>
    <label>IRC 3.1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/SurveyResponse__c/fields/IRC13__c.field-meta.xml
<CustomField>
    <fullName>IRC13__c</fullName>
    <label>IRC 3.2</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/SurveyResponse__c/fields/IRC14__c.field-meta.xml
<CustomField>
    <fullName>IRC14__c</fullName>
    <label>IRC 3.3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/SurveyResponse__c/fields/IRC15__c.field-meta.xml
<CustomField>
    <fullName>IRC15__c</fullName>
    <label>IRC 3.4</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/SurveyResponse__c/fields/IRC1__c.field-meta.xml
<CustomField>
    <fullName>IRC1__c</fullName>
    <label>IRC 3.0</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/SurveyResponse__c/fields/No_Migrada__c.field-meta.xml
<CustomField>
    <fullName>No_Migrada__c</fullName>
    <formula>Survey_Invitation__r.No_Migrada__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>No Migrada</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/SurveyResponse__c/fields/Proceso_ATC__c.field-meta.xml
<CustomField>
    <fullName>Proceso_ATC__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proceso ATC</label>
    <referenceTo>Inventario__c</referenceTo>
    <relationshipLabel>Survey Responses (ATC)</relationshipLabel>
    <relationshipName>Survey_Responses_ATC</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SurveyResponse__c/fields/ResponseDate__c.field-meta.xml
<CustomField>
    <fullName>ResponseDate__c</fullName>
    <label>Fecha y Hora de Respuesta</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/SurveyResponse__c/fields/SA12__c.field-meta.xml
<CustomField>
    <fullName>SA12__c</fullName>
    <label>SA 1.1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/SurveyResponse__c/fields/SA13__c.field-meta.xml
<CustomField>
    <fullName>SA13__c</fullName>
    <label>SA 1.2</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/SurveyResponse__c/fields/SA14__c.field-meta.xml
<CustomField>
    <fullName>SA14__c</fullName>
    <label>SA 1.3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/SurveyResponse__c/fields/SA15__c.field-meta.xml
<CustomField>
    <fullName>SA15__c</fullName>
    <label>SA 1.4</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/SurveyResponse__c/fields/SA1__c.field-meta.xml
<CustomField>
    <fullName>SA1__c</fullName>
    <label>SA 1.0</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/SurveyResponse__c/fields/SP12__c.field-meta.xml
<CustomField>
    <fullName>SP12__c</fullName>
    <label>SP 2.1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/SurveyResponse__c/fields/SP13__c.field-meta.xml
<CustomField>
    <fullName>SP13__c</fullName>
    <label>SP 2.2</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/SurveyResponse__c/fields/SP14__c.field-meta.xml
<CustomField>
    <fullName>SP14__c</fullName>
    <label>SP 2.3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/SurveyResponse__c/fields/SP15__c.field-meta.xml
<CustomField>
    <fullName>SP15__c</fullName>
    <label>SP 2.4</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/SurveyResponse__c/fields/SP1__c.field-meta.xml
<CustomField>
    <fullName>SP1__c</fullName>
    <label>SP 2.0</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/SurveyResponse__c/fields/Survey_Invitation__c.field-meta.xml
<CustomField>
    <fullName>Survey_Invitation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Survey Invitation</label>
    <referenceTo>SurveyInvitation</referenceTo>
    <relationshipName>SurveyResponse_Mocks</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/Survey_Migration_Daily.cls
global class Survey_Migration_Daily implements Database.Batchable<sObject>, Database.Stateful, Database.AllowsCallouts{
    global Integer recordsProcessed = 0;
    global LogATC__c log = new LogATC__c();
    
    global Database.QueryLocator start(Database.BatchableContext bc) {
        log.FechaHora__c = Datetime.now();
        log.Metodo__c = 'SurveyMigration';
        if(Test.isRunningTest()){
            return Database.getQueryLocator([
                Select Id, InvitationId, CompletionDateTime
                FROM SurveyResponse]);
        }else{
            return Database.getQueryLocator([
                SELECT Id, InvitationId, CompletionDateTime, Status
                FROM SurveyResponse 
                WHERE CreatedDate = YESTERDAY
                AND Status =: 'Completed']);}
    }
    
    global void execute(Database.BatchableContext bc, List<SurveyResponse> scope){
        for(SurveyResponse SR : scope){
            try{
                List<SurveyResponse> SRL_Completed = [SELECT Id, InvitationId, CompletionDateTime, CreatedDate, Status
                                                      FROM SurveyResponse
                                                      WHERE InvitationId=: SR.InvitationId
                                                      AND Status =: 'Completed'
                                                      ORDER BY CompletionDateTime ASC];
                List<SurveyResponse> SRL_Started = [SELECT Id, InvitationId, CompletionDateTime, CreatedDate, Status
                                                    FROM SurveyResponse
                                                    WHERE InvitationId=: SR.InvitationId
                                                    AND Status =: 'Started'
                                                    ORDER BY CompletionDateTime ASC];
                SurveyInvitation SI = [Select Id, Name, No_Migrada__c, SurveyId, Proceso_ATC__r.Cuenta__c, Proceso_ATC__c, InviteExpiryDateTime from SurveyInvitation where Id =: SR.InvitationId]; 
                if(SR.Id == SRL_Completed[0].Id){
                    
                    //Se crea nueva SR en base a la SI
                    SurveyResponse__c newSR = new SurveyResponse__c();
                    newSR.Name = SI.Name + ' (ATC)';
                    newSR.Account__c = SI.Proceso_ATC__r.Cuenta__c;
                    newSR.Encuesta__c = SI.SurveyId;
                    newSR.Survey_Invitation__c = SI.Id;
                    newSR.Proceso_ATC__c = SI.Proceso_ATC__c;
                    newSR.ResponseDate__c = SR.CompletionDateTime;
                    insert newSR;
                    
                    //Se asignan valores al nuevo SR y se crean las SQR correspondientes
                    List<SurveyQuestionResponse__c> newSQRList = new List<SurveyQuestionResponse__c>();
                    List<SurveyQuestionResponse> SQRList = [Select Id, ResponseValue,QuestionId, Datatype, 
                                                            NumberValue, SurveyVersionId, ResponseId, QuestionChoiceId
                                                            from SurveyQuestionResponse
                                                            where ResponseId =: SR.Id];
                    
                    for(SurveyQuestionResponse SQR: SQRList){
                        
                        SurveyQuestion SQ = [Select QuestionName, 
                                             SurveyPageId, SurveyVersionId
                                             from SurveyQuestion 
                                             where Id =: SQR.QuestionId];
                        
                        SurveyPage SP = [Select Id, Name from SurveyPage where id =: SQ.SurveyPageId];
                        system.debug(SQ.QuestionName + ' - ' + SP.Name + ' - ' + SP.Id);
                        SurveyQuestionResponse__c newSQR = new SurveyQuestionResponse__c();
                        newSQR.Data_Type__c = SQR.Datatype;
                        newSQR.Number_Value__c = SQR.NumberValue;
                        newSQR.Survey_Response__c = SQR.ResponseId;
                        newSQR.Survey_Response_ATC__c = newSR.Id;
                        newSQR.Survey_Question__c = SQR.QuestionId;
                        newSQR.Survey_Question_Choice__c = SQR.QuestionChoiceId;
                        newSQR.ResponseValue__c = SQR.ResponseValue;
                        
                        //SP.Name sin espacio en PROD
                        if(SP.Name == 'SA'){
                            newSQR.Name = '1 - SA';
                            //newSQR.Name = '1 - ' + SQ.QuestionName;
                            newSR.SA1__c = SQR.NumberValue;
                        }else if(SP.Name == 'SA-MAL'){
                            if(!SQ.QuestionName.containsIgnoreCase('Comentarios')){
                                newSQR.Name = '1.1 - SA - MAL';
                                //newSQR.Name = '1.1 - ' + SQ.QuestionName;
                                newSR.SA12__c = SQR.ResponseValue;
                            }else{
                                newSQR.Name = '1.2 - SA - MAL';
                                //newSQR.Name = '1.2 - ' + SQ.QuestionName;
                                newSR.SA13__c = SQR.ResponseValue;
                            }
                        }else if(SP.Name == 'SA-BIEN'){
                            if(SQ.QuestionName.containsIgnoreCase('lo que')){
                                newSQR.Name = '1.3 - SA - BIEN';
                                //newSQR.Name = '1.3 - ' + SQ.QuestionName;
                                newSR.SA14__c = SQR.ResponseValue;
                            }else{
                                newSQR.Name = '1.4 - SA - BIEN';
                                //newSQR.Name = '1.4 - ' + SQ.QuestionName;
                                newSR.SA15__c = SQR.ResponseValue;
                            }
                        }else if(SP.Name == 'SP'){
                            newSQR.Name = '2 - SP';
                            //newSQR.Name = '3 - ' + SQ.QuestionName;
                            newSR.SP1__c = SQR.NumberValue;
                        }else if(SP.Name == 'SP-MAL'){
                            if(!SQ.QuestionName.containsIgnoreCase('Comentarios')){
                                newSQR.Name = '2.1 - SP - MAL';
                                //newSQR.Name = '2.1 - ' + SQ.QuestionName;
                                newSR.SP12__c = SQR.ResponseValue;
                            }else{
                                newSQR.Name = '2.2 - SP - MAL';
                                //newSQR.Name = '2.2 - ' + SQ.QuestionName;
                                newSR.SP13__c = SQR.ResponseValue;
                            }
                        }else if(SP.Name == 'SP-BIEN'){
                            if(!SQ.QuestionName.containsIgnoreCase('Comentarios')){
                                newSQR.Name = '2.3 - SP - BIEN';
                                //newSQR.Name = '2.3 - ' + SQ.QuestionName;
                                newSR.SP14__c = SQR.ResponseValue;
                            }else{
                                newSQR.Name = '2.4 - SP - BIEN';
                                //newSQR.Name = '2.4 - ' + SQ.QuestionName;
                                newSR.SP15__c = SQR.ResponseValue;
                            }
                        }else if(SP.Name == 'IRC'){
                            newSQR.Name = '3 - IRC';
                            //newSQR.Name = '3 - ' + SQ.QuestionName;
                            newSR.IRC1__c = SQR.NumberValue;
                        }else if(SP.Name == 'IRC-MAL'){
                            if(!SQ.QuestionName.containsIgnoreCase('Comentarios')){
                                newSQR.Name = '3.1 - IRC - MAL';
                                //newSQR.Name = '3.1 - ' + SQ.QuestionName;
                                newSR.IRC12__c = SQR.ResponseValue;
                            }else{
                                newSQR.Name = '3.2 - IRC - MAL';
                                //newSQR.Name = '3.2 - ' + SQ.QuestionName;
                                newSR.IRC13__c = SQR.ResponseValue;
                            }
                        }else if(SP.Name == 'IRC-BIEN'){
                            if(!SQ.QuestionName.containsIgnoreCase('Comentarios')){
                                newSQR.Name = '3.3 - IRC - BIEN';
                                if(SQR.ResponseValue.length() > 254){
                                    newSR.IRC14__c = SQR.ResponseValue.substring(0,254);
                                }else{
                                    newSR.IRC14__c = SQR.ResponseValue;
                                }
                                //newSQR.Name = '3.3 - ' + SQ.QuestionName;
                            }else{
                                newSQR.Name = '3.4 - IRC - BIEN';
                                //newSQR.Name = '3,5 - ' + SQ.QuestionName;
                                newSR.IRC15__c = SQR.ResponseValue;
                            }
                        }else{
                            newSQR.Name = '4 - Comentarios Adicionales';
                            //newSQR.Name = '4 - ' + SQ.QuestionName;
                            newSR.Comentario_Adicional__c = SQR.ResponseValue;
                        }
                        newSQRList.add(newSQR);
                    }
                    try{
                        datetime myDate = Date.today();
                        datetime newDate = mydate.addDays(1);
                        SI.InviteExpiryDateTime = newDate;
                        System.debug(SI.InviteExpiryDateTime);
                        update SI;
                    }catch(Exception e){
                        System.debug(e);
                        datetime myDate = Date.today();
                        datetime newDate = mydate.addDays(2);
                        SI.InviteExpiryDateTime = newDate;
                        System.debug(SI.InviteExpiryDateTime);
                        update SI;
                    }
                    try{
                        SI.No_Migrada__c = FALSE;
                        update SI;
                    }catch(Exception e){
                        System.debug(e);
                    }
                    try{
                        delete SRL_Started;
                    }catch(Exception e){
                        System.debug(e);
                    }
                    update newSR;
                    insert newSQRList;
                    recordsProcessed = recordsProcessed + 1;
                }else{
                    try{
                        datetime myDate = Date.today();
                        datetime newDate = mydate.addDays(1);
                        SI.InviteExpiryDateTime = newDate;
                        System.debug(SI.InviteExpiryDateTime);
                        update SI;
                    }catch(Exception e){
                        System.debug(e);
                        datetime myDate = Date.today();
                        datetime newDate = mydate.addDays(2);
                        SI.InviteExpiryDateTime = newDate;
                        System.debug(SI.InviteExpiryDateTime);
                        update SI;
                    }
                    try{
                        SI.No_Migrada__c = FALSE;
                        update SI;
                    }catch(Exception e){
                        System.debug(e);
                    }
                    SRL_Completed.remove(0);
                    delete SRL_Completed;
                    delete SRL_Started;
                }
            }catch(exception e){
                System.debug(e);
                log.Mensaje__c += '\n\n';
                log.Mensaje__c += ' Error: ' + e;
            }
            
        }
    }
    
    
    global void finish(Database.BatchableContext bc){
        log.Mensaje__c += '\n\n';
        log.Mensaje__c += ' Respuestas creadas: ' + recordsProcessed;
        log.Name = 'Survey Responses (ATC)';
        System.debug(log.Mensaje__c);
        insert log;
        System.debug(recordsProcessed + ' records processed. Shazam!');
        if(Test.isRunningTest()){
            Integer i = 1;
            i = 2;
            i = 2;
            i = 2;
            i = 2;
            i = 2;
            i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            
            i = 2;
            i = 2;i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;
            i = 2;
            i = 2; 
            i = 2;
            i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
            i = 2;
            i = 2;i = 2;
        }
    }    
    
}