unpackaged/main/default/objects/Encuesta__c/Encuesta__c.object-meta.xml
<CustomObject>
    <label>Encuesta</label>
    <nameField>
        <displayFormat>E{0000}</displayFormat>
        <label>Nombre de Encuesta</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Encuestas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Encuesta__c/fields/Comentarios__c.field-meta.xml
<CustomField>
    <fullName>Comentarios__c</fullName>
    <label>Comentarios</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Encuesta__c/fields/Pregunta1__c.field-meta.xml
<CustomField>
    <fullName>Pregunta1__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>(Portal de clientes, Centro de contacto, Correo electrónico, etc.)</inlineHelpText>
    <label>1¿Conoce los medios de contacto Javer?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Encuesta__c/fields/Pregunta2__c.field-meta.xml
<CustomField>
    <fullName>Pregunta2__c</fullName>
    <defaultValue>false</defaultValue>
    <label>2¿Cumplió la expectativa de su vivienda?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Encuesta__c/fields/Pregunta3__c.field-meta.xml
<CustomField>
    <fullName>Pregunta3__c</fullName>
    <inlineHelpText>Del 1 al 10 ¿Que tan probable es que usted recomiende Casas Javer a un amigo o familiar?</inlineHelpText>
    <label>3¿Probabilidad recomiende Casas Javer?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Encuesta__c/fields/Pregunta4__c.field-meta.xml
<CustomField>
    <fullName>Pregunta4__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>¿Te gustaría que Casas Javer ofreciera algún servicio adicional?</inlineHelpText>
    <label>4¿Te gustaría que Casas Javer ofreciera</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Encuesta__c/fields/Resultado__c.field-meta.xml
<CustomField>
    <fullName>Resultado__c</fullName>
    <label>Resultado</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/classes/EncuestaTrigger_Test.cls
@isTest
public class EncuestaTrigger_Test {
    @isTest(seeAllData=true)
    public static void testTrigger() {
        Encuesta__c enc = new Encuesta__c();
        enc.Comentarios__c = 'test';
        enc.Pregunta1__c = true;
        enc.Pregunta2__c = true;
        enc.Pregunta3__c = '';
        enc.Pregunta4__c = true;
        enc.Resultado__c = 11;
        Test.startTest();
        insert enc;
        Test.stopTest();
    }
}