unpackaged/main/default/objects/Opportunity/fields/Numero_Proceso_de_Venta__c.field-meta.xml
<CustomField>
    <fullName>Numero_Proceso_de_Venta__c</fullName>
    <description>2-4993368.</description>
    <displayFormat>2-{0000000000}</displayFormat>
    <label>Número Proceso de Venta</label>
    <type>AutoNumber</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Referencia_Bancaria__c.field-meta.xml
<CustomField>
    <fullName>Referencia_Bancaria__c</fullName>
    <label>Referencia Bancaria</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/NuevoProcesoVentaButtonAuraController.cls
public class NuevoProcesoVentaButtonAuraController {
    @AuraEnabled
    public static Id createOpportunityApex(Id recordId) {
       Opportunity newOpportunity = new Opportunity (
            Name = 'Por asignar',
            AccountId = recordId,
            StageName = 'Validación',
            Probability = 0.2,
            CloseDate = Date.Today()+7,
            Amount = 0);
 
       insert newOpportunity;

       // Obtener nuevo Name
       List <Opportunity> opp = [SELECT Id, Name, Numero_Proceso_de_Venta__c FROM Opportunity WHERE Id = :newOpportunity.Id];
       opp[0].Name = opp[0].Numero_Proceso_de_Venta__c;
       opp[0].Referencia_Bancaria__c = CLASS_Oportunidad.CalculaDigitoVerificador(Opp[0].Numero_Proceso_de_Venta__c);
       update opp;

       return newOpportunity.Id;
    }
 }