unpackaged/main/default/objects/Opportunity/fields/Plan_de_Venta__c.field-meta.xml
<CustomField>
    <fullName>Plan_de_Venta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plan de Venta</label>
    <referenceTo>Plan_de_Venta__c</referenceTo>
    <relationshipLabel>Procesos de Ventas</relationshipLabel>
    <relationshipName>Procesos_de_Ventas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/Plan_de_Venta__c.object-meta.xml
<CustomObject>
    <label>Plan de Venta</label>
    <nameField>
        <displayFormat>Plan de Venta-{000000}</displayFormat>
        <label>Plan de Venta</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plan de Venta</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Plan_de_Venta__c.field-meta.xml
<CustomField>
    <fullName>Plan_de_Venta__c</fullName>
    <formula>&quot;Plan de Venta&quot; &amp; &quot; &quot;&amp;  Oportunidad__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Plan de Venta</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Precio_Venta__c.field-meta.xml
<CustomField>
    <fullName>Precio_Venta__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Precio Venta al Cliente</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Producto_de_Plan_de_Venta__c/Producto_de_Plan_de_Venta__c.object-meta.xml
<CustomObject>
    <label>Producto de Plan de Venta</label>
    <nameField>
        <displayFormat>PPV-{YYYY}-{MM}-{000000}</displayFormat>
        <label>Nombre de Producto de Plan de Venta</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Productos de Plan de Venta</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Producto_de_Plan_de_Venta__c/fields/Plan_de_Venta__c.field-meta.xml
<CustomField>
    <fullName>Plan_de_Venta__c</fullName>
    <label>Plan de Venta</label>
    <referenceTo>Plan_de_Venta__c</referenceTo>
    <relationshipLabel>Productos de Plan de Venta</relationshipLabel>
    <relationshipName>Productos_de_Plan_de_Venta</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Producto_de_Plan_de_Venta__c/fields/Producto_de_oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Producto_de_oportunidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producto de oportunidad</label>
    <referenceTo>OpportunityLineItem</referenceTo>
    <relationshipLabel>Productos de Plan de Venta</relationshipLabel>
    <relationshipName>Productos_de_Plan_de_Venta</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/PlanDeVenta_Clone_Test.cls
@isTest
public class PlanDeVenta_Clone_Test {
    static testmethod void testMigrate1(){
        
        Plan_de_Venta__c p = new Plan_de_Venta__c();
        insert p;
        Id pricebookId = Test.getStandardPricebookId();
        
        //Create your product
        Product2 prod = new Product2(
            Name = 'Product X',
            ProductCode = 'Pro-X',
            isActive = true,
            Precio_Venta__c = 10.0,
            Description = 'test'
        );
        insert prod;
        
        //Create your pricebook entry
        PricebookEntry pbEntry = new PricebookEntry(
            Pricebook2Id = pricebookId,
            Product2Id = prod.Id,
            UnitPrice = 100.00,
            IsActive = true
        );
        insert pbEntry;
        
        opportunity opp = new opportunity();
        opp.Name = 'Test';
        opp.StageName = 'Validación';
        opp.CloseDate = Date.today().adddays(10);
        insert opp;
        
        //create your opportunity line item.  This assumes you already have an opportunity created, called opp
        OpportunityLineItem oli = new OpportunityLineItem(
            OpportunityId = opp.Id,
            Quantity = 5,
            PricebookEntryId = pbEntry.Id
        );
        oli.TotalPrice = oli.quantity * pbEntry.UnitPrice;
        insert oli;
        
        Producto_de_Plan_de_Venta__c prodPlan = new Producto_de_Plan_de_Venta__c();
        prodPlan.Plan_de_Venta__c = p.id;
        prodPlan.Producto_de_oportunidad__c = Oli.id;
        prodPlan.Cantidad__c = 12;
        insert prodPlan;
        test.startTest();
        PlanDeVenta_Clone.clonePDV(p.id);
        test.stopTest();
    }
     static testmethod void testMigrate2(){
         test.startTest();
        PlanDeVenta_Clone.clonePDV('string');
        test.stopTest();
     }
}