unpackaged/main/default/objects/Opportunity/fields/Plan_de_Venta__c.field-meta.xml
<CustomField>
    <fullName>Plan_de_Venta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plan de Venta</label>
    <referenceTo>Plan_de_Venta__c</referenceTo>
    <relationshipLabel>Procesos de Ventas</relationshipLabel>
    <relationshipName>Procesos_de_Ventas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Pagare_Preventa__c/Pagare_Preventa__c.object-meta.xml
<CustomObject>
    <label>Pagaré Preventa</label>
    <nameField>
        <displayFormat>{YY}{MM}-{00000}</displayFormat>
        <label>Número de Pagaré Preventa</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pagarés Preventa</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Pagare_Preventa__c/fields/Creado_Manualmente__c.field-meta.xml
<CustomField>
    <fullName>Creado_Manualmente__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Creado Manualmente</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Pagare_Preventa__c/fields/Eliminado_Manualmente__c.field-meta.xml
<CustomField>
    <fullName>Eliminado_Manualmente__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Eliminado Manualmente</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Pagare_Preventa__c/fields/Modificado_Manualmente_Importe__c.field-meta.xml
<CustomField>
    <fullName>Modificado_Manualmente_Importe__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Modificado Manualmente Importe</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Pagare_Preventa__c/fields/Plan_de_Venta__c.field-meta.xml
<CustomField>
    <fullName>Plan_de_Venta__c</fullName>
    <label>Plan de Venta</label>
    <referenceTo>Plan_de_Venta__c</referenceTo>
    <relationshipLabel>Pagarés Preventa</relationshipLabel>
    <relationshipName>Pagares_Preventa</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Pagare_Preventa__c/fields/Tipo_Documento__c.field-meta.xml
<CustomField>
    <fullName>Tipo_Documento__c</fullName>
    <label>Tipo de Documento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pagaré Preventa</fullName>
                <default>true</default>
                <label>Pagaré Preventa</label>
            </value>
            <value>
                <fullName>Factura</fullName>
            </value>
            <value>
                <fullName>Nota de Crédito</fullName>
                <isActive>false</isActive>
                <label>Nota de Crédito</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/Plan_de_Venta__c.object-meta.xml
<CustomObject>
    <label>Plan de Venta</label>
    <nameField>
        <displayFormat>Plan de Venta-{000000}</displayFormat>
        <label>Plan de Venta</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plan de Venta</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Anticipo__c.field-meta.xml
<CustomField>
    <fullName>Anticipo__c</fullName>
    <label>Anticipo</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Estatus_Plan_de_venta__c.field-meta.xml
<CustomField>
    <fullName>Estatus_Plan_de_venta__c</fullName>
    <label>Estatus Plan de Venta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>En Progreso</fullName>
                <default>true</default>
                <label>En Progreso</label>
            </value>
            <value>
                <fullName>Por Aprobar</fullName>
            </value>
            <value>
                <fullName>Aprobado</fullName>
            </value>
            <value>
                <fullName>Reubicado</fullName>
            </value>
            <value>
                <fullName>Reestructurado</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Fecha_de_Inicio_de_Cobranza__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_Inicio_de_Cobranza__c</fullName>
    <description>Es la fecha a partir de la cual el cliente puede empezar a pagar.</description>
    <label>Fecha de Inicio de Pago</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Fecha_de_Vencimiento__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_Vencimiento__c</fullName>
    <label>Fecha de Vencimiento</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Frecuencia__c.field-meta.xml
<CustomField>
    <fullName>Frecuencia__c</fullName>
    <description>Este dato indica cada cuando el cliente tendrá que liquidar los pagarés preventa de su adeudo</description>
    <label>Frecuencia</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Semanal</fullName>
            </value>
            <value>
                <fullName>Quincenal</fullName>
            </value>
            <value>
                <fullName>Mensual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Modificacion_Automatica__c.field-meta.xml
<CustomField>
    <fullName>Modificacion_Automatica__c</fullName>
    <label>Modificación Automática</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proceso de Venta</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Plan de Venta</relationshipLabel>
    <relationshipName>Plan_de_Venta</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Plan_de_Venta__c.field-meta.xml
<CustomField>
    <fullName>Plan_de_Venta__c</fullName>
    <formula>&quot;Plan de Venta&quot; &amp; &quot; &quot;&amp;  Oportunidad__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Plan de Venta</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Plazo__c.field-meta.xml
<CustomField>
    <fullName>Plazo__c</fullName>
    <description>Es el plazo que se le dará al cliente para pagar su financiamiento preventa.</description>
    <label>Plazo</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Subsidio__c.field-meta.xml
<CustomField>
    <fullName>Subsidio__c</fullName>
    <label>Subsidio</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/classes/AdvancedRelatedListController_Test.cls
@isTest
public class AdvancedRelatedListController_Test {
    static TestMethod void testMethod1() {
        Opportunity opp = new Opportunity(Name = 'Test Opportunity');
        opp.StageName = 'Reservado';
        opp.CloseDate = Date.today().adddays(10);
        insert opp; 

        Plan_de_Venta__c pdv = New Plan_de_Venta__c();
        pdv.Plazo__c = 10;
        pdv.Frecuencia__c = 'Quincenal';
        pdv.Modificacion_Automatica__c = 10;
        pdv.Estatus_Plan_de_venta__c = 'En Progreso';
        pdv.Fecha_de_Vencimiento__c = system.today().addDays(1);
        pdv.Fecha_de_Inicio_de_Cobranza__c = system.today();
        pdv.Subsidio__c  = 10;
        pdv.Anticipo__c = 20;
        pdv.Oportunidad__c = opp.Id;
        insert pdv;
        Pagare_Preventa__c p1 = new Pagare_Preventa__c();
        p1.Plan_de_Venta__c = pdv.id;
        p1.Fecha_de_Vencimiento__c = system.today().addDays(1);
        p1.Eliminado_Manualmente__c = true;
        p1.Modificado_Manualmente_Importe__c = true;
        p1.Creado_Manualmente__c = true;
        p1.Importe__c = 10.0;
        insert p1;
        // pdv.Anticipo__c = 30;
        //    update pdv;
        Pagare_Preventa__c pagares = new Pagare_Preventa__c();
        pagares.Plan_de_Venta__c = pdv.id;
        pagares.Fecha_de_Vencimiento__c = system.today().addDays(1);
        pagares.Importe__c = 10.0;
        pagares.Eliminado_Manualmente__c = true;
        insert pagares; 
        List<String> fieldList = new List<String>();
        fieldList.add('Name');  fieldList.add('Tipo_Documento__c');
        String f  = String.join(fieldList, ',');
        
        Map<String, Object> recordData = new Map<String, Object>();  Map<String, Object> recordDataOriginal = new Map<String, Object>();
        recordData.put('Id', pagares.Id);    recordDataOriginal.put('Id', pagares.Id);
        recordData.put('Tipo_Documento__c', 'Factura'); recordDataOriginal.put('Tipo_Documento__c', 'Nota de Crédito');
        
        Test.startTest();
        AdvancedRelatedListController.fetchRecords(pdv.Id, 'Pagare_Preventa__c', f, 'false');
        AdvancedRelatedListController.saveRecord('Pagare_Preventa__c', JSON.serialize(recordData) , JSON.serialize(recordDataOriginal));
        AdvancedRelatedListController.enableCreateRecordStages(pdv.Id);
        AdvancedRelatedListController.enableCreateRecordAmounts(pdv.Id);
        AdvancedRelatedListController.enableDeleteRecords(pdv.Id);
        AdvancedRelatedListController.enableUpdateRecord(pdv.Id);
        AdvancedRelatedListController.deleteRecord('Pagare_Preventa__c', pagares.Id, pdv.Id);
        AdvancedRelatedListController.deleteRecord('contact', pagares.Id, pdv.Id);
        AdvancedRelatedListController.PagaresPreventaOriginales paga = new AdvancedRelatedListController.PagaresPreventaOriginales();
        
        Boolean exceptionThrown = false;
        try {
            AdvancedRelatedListController.deleteRecords('Pagare_Preventa__c', pdv.Id);
            
        } 
        catch (Exception e) {
            exceptionThrown = true;
        }  
        try {
            AdvancedRelatedListController.deleteRecord(null, pagares.Id, pdv.Id);
            
        } 
        catch (Exception e) {
            exceptionThrown = true;
            system.debug('getMessage'+e.getMessage());
        }  
        try {
           AdvancedRelatedListController.fetchRecords(pdv.Id, null, f, 'false');
            
        } 
        catch (Exception e) {
            exceptionThrown = true;
        }
        try {
           AdvancedRelatedListController.fetchRecords(pdv.Id, 'contact', f, 'false');
            
        } 
        catch (Exception e) {
            exceptionThrown = true;
        }
        try {
           AdvancedRelatedListController.saveRecord('null', JSON.serialize(recordData) , JSON.serialize(recordDataOriginal));
            
        } 
        catch (Exception e) {
            exceptionThrown = true;
        }
        Test.stopTest();
    }
}