unpackaged/main/default/objects/Documento__c/Documento__c.object-meta.xml
<CustomObject>
    <label>Documento</label>
    <nameField>
        <displayFormat>3-{0000000000}</displayFormat>
        <label>Documento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documentos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Documento__c/fields/Documento__c.field-meta.xml
<CustomField>
    <fullName>Documento__c</fullName>
    <formula>HYPERLINK(&quot;/lightning/r/Documento__c/&quot;&amp; Id &amp;&quot;/view&quot;, Name &amp; &quot; - &quot; &amp; TEXT(Tipo__c) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Documento</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Documento__c/fields/IdFacturaAr__c.field-meta.xml
<CustomField>
    <fullName>IdFacturaAr__c</fullName>
    <externalId>true</externalId>
    <label>IdFacturaAr</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Documento__c/recordTypes/Factura.recordType-meta.xml
<RecordType>
    <fullName>Factura</fullName>
    <active>false</active>
    <label>FacturaNoSeUsa</label>
</RecordType>

unpackaged/main/default/objects/Integracion_EBS_Facturas__c/Integracion_EBS_Facturas__c.object-meta.xml
<CustomObject>
    <label>Integración EBS Facturas</label>
    <nameField>
        <displayFormat>IEBSF-{00000}</displayFormat>
        <label>Folio Integración Factura</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integraciones EBS Facturas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Integracion_EBS_Facturas__c/fields/Estatus_Integracion__c.field-meta.xml
<CustomField>
    <fullName>Estatus_Integracion__c</fullName>
    <label>Estatus Integración</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nuevo</fullName>
            </value>
            <value>
                <fullName>Enviado</fullName>
            </value>
            <value>
                <fullName>Actualizado</fullName>
            </value>
            <value>
                <fullName>Integrado</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Integracion_EBS_Facturas__c/fields/IdClienteAr__c.field-meta.xml
<CustomField>
    <fullName>IdClienteAr__c</fullName>
    <label>IdClienteAr</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Integracion_EBS_Facturas__c/fields/IdFacturaAr__c.field-meta.xml
<CustomField>
    <fullName>IdFacturaAr__c</fullName>
    <label>IdFacturaAr</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Integracion_EBS_Facturas__c/fields/IdFacturaCrm__c.field-meta.xml
<CustomField>
    <fullName>IdFacturaCrm__c</fullName>
    <label>IdFacturaCrm</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Integracion_EBS_Facturas__c/fields/IdInterfaceCrm__c.field-meta.xml
<CustomField>
    <fullName>IdInterfaceCrm__c</fullName>
    <label>IdInterfaceCrm</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Integracion_EBS_Facturas__c/fields/Response_EBS_hacia_CRM__c.field-meta.xml
<CustomField>
    <fullName>Response_EBS_hacia_CRM__c</fullName>
    <label>Response EBS hacia CRM</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/classes/IntegracionEBS_FacturasSfCRMtoEBSResp.cls
/**
 * @description       : 
 * @author            : Jose V. Aguilar Tlaseca
 * @group             : 
 * @last modified on  : 2023-07-31
 * @last modified by  : Jose V. Aguilar Tlaseca
**/
@RestResource(urlMapping='/EBS/Facturas/*')
global with sharing class IntegracionEBS_FacturasSfCRMtoEBSResp
{
    @HttpPost
    global static ResponseWrapper doPost()
    {
        RestRequest req = RestContext.request;
        Blob body = req.requestBody;
        String requestString = body.toString();

        RequestWrapper reqW = (RequestWrapper)JSON.deserialize(requestString,RequestWrapper.class);

        Integracion_EBS_Facturas__c iebc;

        ResponseWrapper respW = new ResponseWrapper();
        
        try
        {
            iebc = [SELECT Id, Name, IdFacturaCrm__c FROM Integracion_EBS_Facturas__c WHERE Id =: reqW.IdInterfaseCrm];

            iebc.IdClienteAr__c = reqW.IdClienteAr;
            iebc.Mensaje_API__c = reqW.MensajeApi;
            iebc.Respuesta_API__c = reqW.RespuestaApi;
            iebc.IdFacturaAr__c = reqW.IdFacturaAr;
            iebc.IdInterfaceCrm__c = reqW.IdInterfaseCrm;
            iebc.Request_EBS_hacia_CRM__c = requestString;
            iebc.Estatus_Integracion__c = 'Integrado';
            // if (reqW.RespuestaApi=='5') { // Exito
            //     iebc.Estatus_Integracion__c = 'Integrado';
            // } else {
            //     if (reqW.RespuestaApi=='4') { //Error
            //         iebc.Estatus_Integracion__c = 'Error';
            //     }
            // }
            // iebc.Estatus_Integracion__c = 'Integrado';
            respW.MensajeApi = 'Actualizado en CRM';
            respW.RespuestaApi = '1';
            iebc.Response_EBS_hacia_CRM__c = JSON.serialize(respW);

            update iebc;

            // Actualizar datos de Factura (Quizá mandarlo a asyncronous flow)
            List <Documento__c> lDoc = [SELECT Id, IdFacturaAr__c 
                FROM Documento__c WHERE Name = :iebc.IdFacturaCrm__c];

            if (lDoc.size() > 0) {
                lDoc[0].IdFacturaAr__c = reqW.IdFacturaAr;

                update lDoc;
            }

            return respW;
        }
        catch (Exception e)
        {
            String msjApi = 'Error: ' + e.getMessage();
            respW.MensajeApi = msjApi;//.substring(0, 1999);
            respW.RespuestaApi = '-1';

            return respW;
        }

    }
    
    /*
    @HttpGet
    global static void doGet()
    {
        //ToDo
    }

    @HttpDelete
    global static void doDelete()
    {
        //ToDo
    }*/

    global class RequestWrapper
    {
        public String RespuestaApi;
        public String MensajeApi;
        public String IdFacturaAr;
        public String IdClienteAr;
        public String IdInterfaseCrm;
        public String RowId;
    }

    global class ResponseWrapper
    {
        public String MensajeApi;
        public String RespuestaApi;
    }
}