unpackaged/main/default/objects/CPPT_Cancelacion__c/CPPT_Cancelacion__c.object-meta.xml
<CustomObject>
    <label>Cancelación</label>
    <nameField>
        <displayFormat>CAN-{000000}</displayFormat>
        <label>Cancelación</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cancelaciones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CPPT_Cancelacion__c/fields/CPPTS_Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>CPPTS_Oportunidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proceso de Venta</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Cancelaciones</relationshipLabel>
    <relationshipName>Cancelaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CPPT_Cancelacion__c/fields/CPPTS_Saldo_a_Cuenta__c.field-meta.xml
<CustomField>
    <fullName>CPPTS_Saldo_a_Cuenta__c</fullName>
    <label>Saldo a Cuenta</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/CPPT_Cancelacion__c/fields/Plan_de_Venta__c.field-meta.xml
<CustomField>
    <fullName>Plan_de_Venta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plan de Venta</label>
    <referenceTo>Plan_de_Venta__c</referenceTo>
    <relationshipLabel>Cancelaciones</relationshipLabel>
    <relationshipName>Cancelaciones</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Fraccionamiento__c/Fraccionamiento__c.object-meta.xml
<CustomObject>
    <label>Fraccionamiento</label>
    <nameField>
        <label>Nombre de Fraccionamiento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fraccionamientos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Fraccionamiento__c/fields/Prototipo__c.field-meta.xml
<CustomField>
    <fullName>Prototipo__c</fullName>
    <label>Prototipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prototipo 1</fullName>
            </value>
            <value>
                <fullName>Prototipo 2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Fraccionamiento__c.field-meta.xml
<CustomField>
    <fullName>Fraccionamiento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fraccionamiento</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$User.Fraccionamiento_autorizado__c</field>
            <operation>contains</operation>
            <valueField>Fraccionamiento__c.Name</valueField>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>Administrador del sistema</value>
        </filterItems>
        <filterItems>
            <field>Fraccionamiento__c.Activo_frac__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$User.Fraccionamiento_autorizado__c</field>
            <operation>equals</operation>
            <value>TODOS</value>
        </filterItems>
        <filterItems>
            <field>$User.FraccionamientoAutorizados__c</field>
            <operation>contains</operation>
            <valueField>Fraccionamiento__c.Name</valueField>
        </filterItems>
        <filterItems>
            <field>Fraccionamiento__c.Name</field>
            <operation>contains</operation>
            <valueField>Fraccionamiento__c.Name</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Fraccionamiento__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Plan_de_Venta__c.field-meta.xml
<CustomField>
    <fullName>Plan_de_Venta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plan de Venta</label>
    <referenceTo>Plan_de_Venta__c</referenceTo>
    <relationshipLabel>Procesos de Ventas</relationshipLabel>
    <relationshipName>Procesos_de_Ventas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Prototipo__c.field-meta.xml
<CustomField>
    <fullName>Prototipo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prototipo</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>El valor ingresado no coincide con los prototipos disponibles para el fraccionamiento</errorMessage>
        <filterItems>
            <field>Prototipo__c.Fraccionamiento__c</field>
            <operation>equals</operation>
            <valueField>$Source.Fraccionamiento__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Prototipo__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/Plan_de_Venta__c.object-meta.xml
<CustomObject>
    <label>Plan de Venta</label>
    <nameField>
        <displayFormat>Plan de Venta-{000000}</displayFormat>
        <label>Plan de Venta</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plan de Venta</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Estatus_Plan_de_venta__c.field-meta.xml
<CustomField>
    <fullName>Estatus_Plan_de_venta__c</fullName>
    <label>Estatus Plan de Venta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>En Progreso</fullName>
                <default>true</default>
                <label>En Progreso</label>
            </value>
            <value>
                <fullName>Por Aprobar</fullName>
            </value>
            <value>
                <fullName>Aprobado</fullName>
            </value>
            <value>
                <fullName>Reubicado</fullName>
            </value>
            <value>
                <fullName>Reestructurado</fullName>
            </value>
            <value>
                <fullName>Rechazado</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Fecha_de_Inicio_de_Cobranza__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_Inicio_de_Cobranza__c</fullName>
    <description>Es la fecha a partir de la cual el cliente puede empezar a pagar.</description>
    <label>Fecha de Inicio de Pago</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Fecha_de_Vencimiento__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_Vencimiento__c</fullName>
    <label>Fecha de Vencimiento</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Frecuencia__c.field-meta.xml
<CustomField>
    <fullName>Frecuencia__c</fullName>
    <description>Este dato indica cada cuando el cliente tendrá que liquidar los pagarés preventa de su adeudo</description>
    <label>Frecuencia</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Semanal</fullName>
            </value>
            <value>
                <fullName>Quincenal</fullName>
            </value>
            <value>
                <fullName>Mensual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Lista_de_Precios_Vivienda__c.field-meta.xml
<CustomField>
    <fullName>Lista_de_Precios_Vivienda__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lista de Precios Vivienda</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Plan de Venta Vivienda</relationshipLabel>
    <relationshipName>Plan_de_Venta</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Modificacion_Automatica__c.field-meta.xml
<CustomField>
    <fullName>Modificacion_Automatica__c</fullName>
    <label>Modificación Automática</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proceso de Venta</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Plan de Venta</relationshipLabel>
    <relationshipName>Plan_de_Venta</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Plan_de_Venta__c.field-meta.xml
<CustomField>
    <fullName>Plan_de_Venta__c</fullName>
    <formula>&quot;Plan de Venta&quot; &amp; &quot; &quot;&amp;  Oportunidad__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Plan de Venta</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Plazo__c.field-meta.xml
<CustomField>
    <fullName>Plazo__c</fullName>
    <description>Es el plazo que se le dará al cliente para pagar su financiamiento preventa.</description>
    <label>Plazo</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Plan_de_Venta__c/fields/Prototipo__c.field-meta.xml
<CustomField>
    <fullName>Prototipo__c</fullName>
    <formula>Oportunidad__r.Prototipo__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Prototipo</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Pricebook2/fields/Cantidad__c.field-meta.xml
<CustomField>
    <fullName>Cantidad__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Cantidad</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Pricebook2/fields/Fraccionamiento__c.field-meta.xml
<CustomField>
    <fullName>Fraccionamiento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fraccionamiento</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 AND (2 OR 3)</booleanFilter>
        <filterItems>
            <field>Fraccionamiento__c.Activo_frac__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>$User.Fraccionamiento_autorizado__c</field>
            <operation>contains</operation>
            <valueField>Fraccionamiento__c.Name</valueField>
        </filterItems>
        <filterItems>
            <field>$User.FraccionamientoAutorizados__c</field>
            <operation>contains</operation>
            <valueField>Fraccionamiento__c.Name</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Fraccionamiento__c</referenceTo>
    <relationshipLabel>Listas de precios</relationshipLabel>
    <relationshipName>Listas_de_precios</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Pricebook2/fields/Precio_Lista__c.field-meta.xml
<CustomField>
    <fullName>Precio_Lista__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Precio Lista</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Pricebook2/fields/Prototipo__c.field-meta.xml
<CustomField>
    <fullName>Prototipo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prototipo</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Prototipo__c.Fraccionamiento__c</field>
            <operation>equals</operation>
            <valueField>$Source.Fraccionamiento__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Prototipo__c</referenceTo>
    <relationshipLabel>Listas de precios</relationshipLabel>
    <relationshipName>Listas_de_precios</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Pricebook2/fields/Vigente_Desde__c.field-meta.xml
<CustomField>
    <fullName>Vigente_Desde__c</fullName>
    <label>Vigente Desde</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Pricebook2/fields/Vigente_Hasta__c.field-meta.xml
<CustomField>
    <fullName>Vigente_Hasta__c</fullName>
    <label>Vigente Hasta</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Prototipo__c/Prototipo__c.object-meta.xml
<CustomObject>
    <label>Prototipo</label>
    <nameField>
        <label>Prototipo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prototipos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Prototipo__c/fields/Fraccionamiento__c.field-meta.xml
<CustomField>
    <fullName>Fraccionamiento__c</fullName>
    <label>Fraccionamiento</label>
    <referenceTo>Fraccionamiento__c</referenceTo>
    <relationshipLabel>Prototipos</relationshipLabel>
    <relationshipName>Prototipos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/classes/CPPTS_Comp_Cancelaciones_Test.cls
@isTest
public class CPPTS_Comp_Cancelaciones_Test {
    @isTest
    static void testMeth1() {
        opportunity opp = new opportunity();
        opp.Name = 'Test';
        opp.StageName = 'Validación';
        opp.CloseDate = Date.today().adddays(10);
        insert opp;
        CPPT_Cancelacion__c canc = new CPPT_Cancelacion__c();
        canc.CPPTS_Oportunidad__c = opp.Id;
        insert canc;
        Test.startTest();
        CPPTS_Comp_Cancelaciones.obtenerBooleanos(canc.Id); 
        CPPTS_Comp_Cancelaciones.cancelaProceso(canc.Id); 
        CPPTS_Comp_Cancelaciones.calculaGasto(canc.Id);
        CPPTS_Comp_Cancelaciones.reprocesaReembolso(canc.Id);
        Test.stopTest();
    }
    @isTest
    static void testMeth2() {
        opportunity opp = new opportunity();
        opp.Name = 'Test';
        opp.StageName = 'Entregado';
        opp.CloseDate = Date.today().adddays(10);
        insert opp;
        Fraccionamiento__c f = new Fraccionamiento__c(name = 'test');
        insert f;
        Prototipo__c p = new Prototipo__c(name = 'test',Fraccionamiento__c = f.id);
        insert p;
        Pricebook2 pb5= new Pricebook2(name = 'test',Fraccionamiento__c = f.id,Vigente_Desde__c = system.today(),Vigente_Hasta__c= Date.newInstance(2023, 06, 30),
                                       Cantidad__c = 12, Description = 'test', Precio_Lista__c = 950000,Prototipo__c = p.id);
        insert pb5;
        CPPT_Cancelacion__c canc = new CPPT_Cancelacion__c();
        canc.CPPTS_Oportunidad__c = opp.Id;
        canc.CPPTS_Saldo_a_Cuenta__c = 600000;
        insert canc;
        Plan_de_Venta__c pdv = New Plan_de_Venta__c();
        pdv.Plazo__c = 10;
        pdv.Frecuencia__c = 'Semanal';
        pdv.Modificacion_Automatica__c = 10;
        pdv.Estatus_Plan_de_venta__c = 'En Progreso';
        pdv.Fecha_de_Vencimiento__c = system.today().addDays(1);
        pdv.Fecha_de_Inicio_de_Cobranza__c = system.today();
        pdv.Lista_de_Precios_Vivienda__c = pb5.Id;
        pdv.Oportunidad__c = opp.Id;
        insert pdv;
        Test.startTest();
        CPPTS_Comp_Cancelaciones.cancelaProceso(canc.Id); 
        CPPTS_Comp_Cancelaciones.calculaGasto(canc.Id);
        Test.stopTest();
    }
     @isTest
    static void testMeth3() {
        opportunity opp = new opportunity();
        opp.Name = 'Test';
        opp.StageName = 'Reservado';
        opp.CloseDate = Date.today().adddays(10);
        insert opp;
        CPPT_Cancelacion__c canc = new CPPT_Cancelacion__c();
        canc.CPPTS_Oportunidad__c = opp.Id;
        insert canc;
        Test.startTest();
        CPPTS_Comp_Cancelaciones.cancelaProceso(canc.Id); 
        CPPTS_Comp_Cancelaciones.calculaGasto(canc.Id);
        Test.stopTest();
    }
   
}