unpackaged/main/default/objects/Entrega__c/Entrega__c.object-meta.xml
<CustomObject>
    <label>Entrega</label>
    <nameField>
        <label>Nombre de Entrega</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entregas</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Entrega__c/fields/ControlE__c.field-meta.xml
<CustomField>
    <fullName>ControlE__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ControlE</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Entrega__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cliente</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Clientes ATC</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Entregas</relationshipLabel>
    <relationshipName>Entregas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Entrega__c/fields/Estatus__c.field-meta.xml
<CustomField>
    <fullName>Estatus__c</fullName>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Por entregar</fullName>
            </value>
            <value>
                <fullName>No entregado</fullName>
            </value>
            <value>
                <fullName>Entregado</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Entrega__c/fields/FechaEntrega__c.field-meta.xml
<CustomField>
    <fullName>FechaEntrega__c</fullName>
    <label>Fecha de Entrega</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Entrega__c/fields/FechaEscritura__c.field-meta.xml
<CustomField>
    <fullName>FechaEscritura__c</fullName>
    <label>Fecha de Escritura</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Entrega__c/fields/Inventario__c.field-meta.xml
<CustomField>
    <fullName>Inventario__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventario</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Inventario__c.Cuenta__c</field>
            <operation>equals</operation>
            <valueField>$Source.Cuenta__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Estatus__c</field>
            <operation>equals</operation>
            <value>Cancelado</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Inventario__c</referenceTo>
    <relationshipLabel>Entregas</relationshipLabel>
    <relationshipName>Entregas</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Entrega__c/fields/Numero_Proceso__c.field-meta.xml
<CustomField>
    <fullName>Numero_Proceso__c</fullName>
    <formula>MID(Name, FIND(&quot;_&quot;, Name)+ 1, LEN(Name) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>No Proceso</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/Inventario__c.object-meta.xml
<CustomObject>
    <label>Proceso ATC</label>
    <nameField>
        <label>Id Vivienda</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProcesosATC</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Inventario__c/fields/ControlE__c.field-meta.xml
<CustomField>
    <fullName>ControlE__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ControlE</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Inventarios</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/Entregada__c.field-meta.xml
<CustomField>
    <fullName>Entregada__c</fullName>
    <label>Estatus</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Por Entregar</fullName>
            </value>
            <value>
                <fullName>No Entregado</fullName>
            </value>
            <value>
                <fullName>Entregado</fullName>
            </value>
            <value>
                <fullName>Agendada</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/FechaEntrega__c.field-meta.xml
<CustomField>
    <fullName>FechaEntrega__c</fullName>
    <label>Fecha de Entrega</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/FechaEscritura__c.field-meta.xml
<CustomField>
    <fullName>FechaEscritura__c</fullName>
    <label>Fecha de Escritura</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Inventario__c/fields/NumeroProceso__c.field-meta.xml
<CustomField>
    <fullName>NumeroProceso__c</fullName>
    <label>Número de proceso</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/ActualizarEstatusProcesoATC.cls
global class ActualizarEstatusProcesoATC{

    @future
	global static void execute(){ 
        List<Inventario__c> listInventariosQ = [SELECT id,(SELECT Estatus__c,Numero_Proceso__c,FechaEntrega__c,FechaEscritura__c,Cuenta__c from entregas__r ORDER by FechaEscritura__c DESC) from Inventario__c where ControlE__c = true];
        List<Inventario__c> listInventario = new List<Inventario__c>();
        if(Test.isRunningTest())
            pass();
        for(Inventario__c inventario : listInventariosQ){
            try{
            inventario.Entregada__c = inventario.entregas__r[0].Estatus__c;
            inventario.NumeroProceso__c = inventario.entregas__r[0].Numero_Proceso__c; 
            inventario.FechaEscritura__c = inventario.entregas__r[0].FechaEscritura__c;
            inventario.Cuenta__c = inventario.entregas__r[0].Cuenta__c;
            inventario.FechaEntrega__c = inventario.entregas__r[0].FechaEntrega__c;
            
            inventario.ControlE__c = false;
            listInventario.add(inventario);
            }catch(Exception e){
                system.debug('Error al actualizar el registro: '+e.getLineNumber());
                system.debug('Detalle: '+e.getCause());
            }
        }      
        try{
        	update listInventario;
        }catch(Exception ex){
            System.debug('Error al actualizar datos: '+ex.getLineNumber());
            System.debug('Detalle: '+ex.getCause());
        }
    }
    
    global static void pass(){
        String test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
        test='';
    }

}