unpackaged/main/default/objects/Inventario__c/Inventario__c.object-meta.xml
<CustomObject>
    <label>Proceso ATC</label>
    <nameField>
        <label>Id Vivienda</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProcesosATC</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/LogATC__c/LogATC__c.object-meta.xml
<CustomObject>
    <label>LogATC</label>
    <nameField>
        <label>Nombre de LogATC</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LogATC</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/LogATC__c/fields/FechaHora__c.field-meta.xml
<CustomField>
    <fullName>FechaHora__c</fullName>
    <label>Fecha y Hora</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/LogATC__c/fields/Metodo__c.field-meta.xml
<CustomField>
    <fullName>Metodo__c</fullName>
    <label>Método</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/EntregasWS_Queueable_Test.cls
@isTest(SeeAllData = true)
public class EntregasWS_Queueable_Test {
    
    static testmethod void test() {   
        LogATC__c log = new LogATC__c();
        log.FechaHora__c = Datetime.now();
        log.Metodo__c = 'ImportarEntregaWS';
        
        Map<String, Account> mapAyudaCuenta = new Map<String, Account>();
        
        Map<String, Account> rCuenta = new Map<String, Account>();
        
        Map<String, Inventario__c> rInventario = new Map<String, Inventario__c>();
        
        EntregaWS_Schedulable EM = new EntregaWS_Schedulable();
        EM.execute(null);
        
        EntregaWS_Schedulable_1Day EM1 = new EntregaWS_Schedulable_1Day();
        EM1.execute(null);
        
        EntregasWSInventario_Queueable EntregasWSInventario_Queueable = new EntregasWSInventario_Queueable(1, log, mapAyudaCuenta);
        ID jobID = System.enqueueJob(EntregasWSInventario_Queueable);
        
        EntregasWSEntregas_Queueable EntregasWSEntregas_Queueable = new EntregasWSEntregas_Queueable(1, log, rCuenta, rInventario);
        ID jobID2 = System.enqueueJob(EntregasWSEntregas_Queueable);
    }
    
}